### ISSUE TITLE
git-submodule: Cannot update private repos

### ISSUE THREAD

**Issue by mkellock** [renovatebot/renovate#10043]
Hi, pretty sure I've set up things correctly (hopefully I haven't and this isn't a bug), I don't seem to be able to update the submodules in the parent repo. I have Renovate in both the parent and submodule repos, however, when Renovate goes to pull, it runs into an auth issue. All repos are private, I'm assuming this is a likely candidate. However happy to be doing something wrong...

Renovate config:
`{
  "extends": [
    "config:base"
  ],
  "kubernetes": {
    "fileMatch": ["\\.yaml$"]
  },
  "git-submodules": {
    "enabled": true
  },
  "reviewers": ["team:smart-badge-platform"]
}
`

Log snippet:
`WARN: Unable to initialise git submodule at monitoring
{
  "err": {
    "task": {
      "commands": [
        "submodule",
        "update",
        "--init",
        "monitoring"
      ],
      "format": "utf-8"
    },
    "message": "Submodule 'kubernetes-monitoring' (https://github.com/polr-software/kubernetes-monitoring) registered for path 'monitoring'\nCloning into '/mnt/renovate/gh/polr-software/kubernetes/monitoring'...\nfatal: could not read Username for 'https://github.com': No such device or address\nfatal: clone of 'https://github.com/polr-software/kubernetes-monitoring' into submodule path '/mnt/renovate/gh/polr-software/kubernetes/monitoring' failed\nFailed to clone 'monitoring'. Retry scheduled\nCloning into '/mnt/renovate/gh/polr-software/kubernetes/monitoring'...\nfatal: could not read Username for 'https://github.com': No such device or address\nfatal: clone of 'https://github.com/polr-software/kubernetes-monitoring' into submodule path '/mnt/renovate/gh/polr-software/kubernetes/monitoring' failed\nFailed to clone 'monitoring' a second time, aborting\n",
    "stack": "Error: Submodule 'kubernetes-monitoring' (https://github.com/polr-software/kubernetes-monitoring) registered for path 'monitoring'\nCloning into '/mnt/renovate/gh/polr-software/kubernetes/monitoring'...\nfatal: could not read Username for 'https://github.com': No such device or address\nfatal: clone of 'https://github.com/polr-software/kubernetes-monitoring' into submodule path '/mnt/renovate/gh/polr-software/kubernetes/monitoring' failed\nFailed to clone 'monitoring'. Retry scheduled\nCloning into '/mnt/renovate/gh/polr-software/kubernetes/monitoring'...\nfatal: could not read Username for 'https://github.com': No such device or address\nfatal: clone of 'https://github.com/polr-software/kubernetes-monitoring' into submodule path '/mnt/renovate/gh/polr-software/kubernetes/monitoring' failed\nFailed to clone 'monitoring' a second time, aborting\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:92:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:90:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:74:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  }
}`

**Comment by viceice** [comment]
Please fill our issue template and format your code
