### ISSUE TITLE
Hosted app isn't authenticating to github.com correctly

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/renovate#10524]
### Discussed in https://github.com/renovatebot/renovate/discussions/10334

Transferring here because it seems to be an actual bug - authentication is supported by the datasource, but the GitHub auth isn't working for some reason

<div type='discussions-op-text'>

<sup>Originally posted by **mikebryant** June  7, 2021</sup>
I'm using the hosted app, this particular run is https://app.renovatebot.com/dashboard#github/BulbEnergy/argocd-root/371774361

The private repository has ArgoCD dependencies on other private repositories within the same organisation.

Error is:
```
DEBUG: Found argocd package files
DEBUG: Found 42 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "master",
  "stats": {
    "managers": {
      "argocd": {
        "fileCount": 42,
        "depCount": 44
      }
    },
    "total": {
      "fileCount": 42,
      "depCount": 44
    }
  }
}
DEBUG: Datasource unknown error
{
  "datasource": "git-tags",
  "lookupName": "https://github.com/BulbEnergy/cluster-base.git",
  "err": {
    "task": {
      "commands": [
        "ls-remote",
        "https://github.com/BulbEnergy/cluster-base.git"
      ],
      "format": "utf-8"
    },
    "message": "fatal: could not read Username for 'https://github.com': No such device or address\n",
    "stack": "Error: fatal: could not read Username for 'https://github.com': No such device or address\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  }
}
DEBUG: Failed to look up dependency https://github.com/BulbEnergy/cluster-base.git (https://github.com/BulbEnergy/cluster-base.git)(packageFile="objects/bulb-ci-prod/europe-west2/ci-primary/apps/bulbenrg-cluster-base.yaml", dependency="https://github.com/BulbEnergy/cluster-base.git")
```

I was expecting Renovate to have access to this repository - indeed, hosted Renovate is currently running correctly against https://github.com/BulbEnergy/cluster-base.git

But when it tries to do the listing of references, it doesn't appear to be populating the token

The file it's failing on (eliding other config), is:
```
spec:
  project: default
  source:
    repoURL: https://github.com/BulbEnergy/cluster-base.git
    targetRevision: 1.0.1
````</div>

**Comment by rarkins** [comment]
@mikebryant please reformat using the bug report template: https://raw.githubusercontent.com/renovatebot/renovate/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mikebryant** [comment]
Done :)

**Comment by mikebryant** [comment]
Mhm, fair. I've just gone through those steps, and created a new minimal private org for reproduction: https://github.com/renovate-test-private-org/

I've invited you as an owner - happy to invite anyone else who needs access, or feel free to add people yourself

**Comment by mikebryant** [comment]
Same error is occuring there (on the `private-repo` repo:
```
DEBUG: Datasource unknown error
{
  "datasource": "git-tags",
  "lookupName": "https://github.com/renovate-test-private-org/private-dependency.git",
  "err": {
    "task": {
      "commands": [
        "ls-remote",
        "https://github.com/renovate-test-private-org/private-dependency.git"
      ],
      "format": "utf-8"
    },
    "message": "fatal: could not read Username for 'https://github.com': No such device or address\n",
    "stack": "Error: fatal: could not read Username for 'https://github.com': No such device or address\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  }
}
DEBUG: Failed to look up dependency https://github.com/renovate-test-private-org/private-dependency.git (https://github.com/renovate-test-private-org/private-dependency.git)(packageFile="private-dependency.yaml", dependency="https://github.com/renovate-test-private-org/private-dependency.git")
```

**Comment by mikebryant** [comment]
I've also included a corresponding example with a public dependency, just to check the format of the files is valid etc

**Comment by drewboswell** [comment]
I am having the same problem in the following configuration
* renovate: self-hosted
* github-enterprise: self-hosted

**Comment by JamieMagee** [comment]
@drewboswell This issue is about the hosted Renovate app, not self-hosted. Could you please create a new issue?

**Comment by rarkins** [comment]
@mikebryant can you tell if this problem still reproduces?

**Comment by rarkins** [comment]
BTW I don't appear to still have access to the org & private repos

**Comment by mikebryant** [comment]
I've just re-invited you, the UI showed:
>Invitation expired. User did not accept this invite for 7 days

Looks like it's still failing here: https://github.com/renovate-test-private-org/private-repo/issues/3

**Comment by herebebeasties** [comment]
I think it's possible this is also what's causing git submodule updates for private repo submodules to not work in #10149 - I'm seeing:
```
    "message": "fatal: could not read Username for 'https://github.com': No such device or address\n",
```
...in the logs for that.
