### ISSUE TITLE
Tass failing because of Docker's SIGTERM

### ISSUE THREAD

**Issue by expobrain** [renovatebot/renovate#10769]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [x] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.52.7

**Describe the bug**

Renovate is failing because `exec interrupted by SIGTERM - run needs to be aborted`, that is the `docker run` step is failing because it's taking too long.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: exec interrupted by SIGTERM - run needs to be aborted(branch="renovate/isort-5.x-lockfile")
{
  "err": {
    "killed": false,
    "code": null,
    "signal": "SIGTERM",
    "cmd": "docker run --rm --name=renovate_python --label=renovate_child -v \"/mnt/renovate/gh/BulbEnergy/bulb-py\":\"/mnt/renovate/gh/BulbEnergy/bulb-py\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e POETRY_HTTP_BASIC_BULB_USERNAME -e POETRY_HTTP_BASIC_BULB_PASSWORD -w \"/mnt/renovate/gh/BulbEnergy/bulb-py/bulb_smart_energy_clients\" docker.io/renovate/python:3.9.6 bash -l -c \"pip install poetry && poetry update --lock --no-interaction isort\"",
    "stdout": "Defaulting to user installation because normal site-packages is not writeable\nCollecting poetry\n  Downloading poetry-1.1.7-py2.py3-none-any.whl (173 kB)\nCollecting requests<3.0,>=2.18\n  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)\nCollecting cachy<0.4.0,>=0.3.0\n  Downloading cachy-0.3.0-py2.py3-none-any.whl (20 kB)\nCollecting packaging<21.0,>=20.4\n  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)\nCollecting clikit<0.7.0,>=0.6.2\n  Downloading clikit-0.6.2-py2.py3-none-any.whl (91 kB)\nCollecting pexpect<5.0.0,>=4.7.0\n  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)\nCollecting html5lib<2.0,>=1.0\n  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)\nCollecting keyring<22.0.0,>=21.2.0\n  Downloading keyring-21.8.0-py3-none-any.whl (32 kB)\nCollecting requests-toolbelt<0.10.0,>=0.9.1\n  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)\nCollecting poetry-core<1.1.0,>=1.0.3\n  Downloading poetry_core-1.0.3-py2.py3-none-any.whl (424 kB)\nCollecting tomlkit<1.0.0,>=0.7.0\n  Downloading tomlkit-0.7.2-py2.py3-none-any.whl (32 kB)\nCollecting cachecontrol[filecache]<0.13.0,>=0.12.4\n  Downloading CacheControl-0.12.6-py2.py3-none-any.whl (19 kB)\nCollecting cleo<0.9.0,>=0.8.1\n  Downloading cleo-0.8.1-py2.py3-none-any.whl (21 kB)\nCollecting virtualenv<21.0.0,>=20.0.26\n  Downloading virtualenv-20.4.7-py2.py3-none-any.whl (7.2 MB)\nCollecting pkginfo<2.0,>=1.4\n  Downloading pkginfo-1.7.0-py2.py3-none-any.whl (25 kB)\nCollecting shellingham<2.0,>=1.1\n  Downloading shellingham-1.4.0-py2.py3-none-any.whl (9.4 kB)\nCollecting crashtest<0.4.0,>=0.3.0\n  Downloading crashtest-0.3.1-py3-none-any.whl (7.0 kB)\nCollecting msgpack>=0.5.2\n  Downloading msgpack-1.0.2-cp39-cp39-manylinux1_x86_64.whl (294 kB)\nCollecting lockfile>=0.9\n  Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)\nCollecting pastel<0.3.0,>=0.2.0\n  Downloading pastel-0.2.1-py2.py3-none-any.whl (6.0 kB)\nCollecting pylev<2.0,>=1.3\n  Downloading pylev-1.4.0-py2.py3-none-any.whl (6.1 kB)\nCollecting six>=1.9\n  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)\nCollecting webencodings\n  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)\nCollecting SecretStorage>=3.2\n  Downloading SecretStorage-3.3.1-py3-none-any.whl (15 kB)\nCollecting jeepney>=0.4.2\n  Downloading jeepney-0.6.0-py3-none-any.whl (45 kB)\nCollecting pyparsing>=2.0.2\n  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)\nCollecting ptyprocess>=0.5\n  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)\nCollecting certifi>=2017.4.17\n  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)\nCollecting chardet<5,>=3.0.2\n  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)\nCollecting urllib3<1.27,>=1.21.1\n  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)\nCollecting idna<3,>=2.5\n  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)\nCollecting cryptography>=2.0\n  Downloading cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)\nCollecting cffi>=1.12\n  Downloading cffi-1.14.6-cp39-cp39-manylinux1_x86_64.whl (405 kB)\nCollecting pycparser\n  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)\nCollecting appdirs<2,>=1.4.3\n  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)\nCollecting distlib<1,>=0.3.1\n  Downloading distlib-0.3.2-py2.py3-none-any.whl (338 kB)\nCollecting filelock<4,>=3.0.0\n  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)\nInstalling collected packages: pycparser, urllib3, idna, chardet, cffi, certifi, requests, pylev, pastel, msgpack, jeepney, cryptography, crashtest, webencodings, six, SecretStorage, pyparsing, ptyprocess, lockfile, filelock, distlib, clikit, cachecontrol, appdirs, virtualenv, tomlkit, shellingham, requests-toolbelt, poetry-core, pkginfo, pexpect, packaging, keyring, html5lib, cleo, cachy, poetry\nSuccessfully installed SecretStorage-3.3.1 appdirs-1.4.4 cachecontrol-0.12.6 cachy-0.3.0 certifi-2021.5.30 cffi-1.14.6 chardet-4.0.0 cleo-0.8.1 clikit-0.6.2 crashtest-0.3.1 cryptography-3.4.7 distlib-0.3.2 filelock-3.0.12 html5lib-1.1 idna-2.10 jeepney-0.6.0 keyring-21.8.0 lockfile-0.12.2 msgpack-1.0.2 packaging-20.9 pastel-0.2.1 pexpect-4.8.0 pkginfo-1.7.0 poetry-1.1.7 poetry-core-1.0.3 ptyprocess-0.7.0 pycparser-2.20 pylev-1.4.0 pyparsing-2.4.7 requests-2.25.1 requests-toolbelt-0.9.1 shellingham-1.4.0 six-1.16.0 tomlkit-0.7.2 urllib3-1.26.6 virtualenv-20.4.7 webencodings-0.5.1\nCreating virtualenv bulb-smart-energy-clients-J4NdQJmt-py3.9 in /home/ubuntu/.cache/pypoetry/virtualenvs\nUpdating dependencies\nResolving dependencies...\n",
    "stderr": "",
    "message": "Command failed: docker run --rm --name=renovate_python --label=renovate_child -v \"/mnt/renovate/gh/BulbEnergy/bulb-py\":\"/mnt/renovate/gh/BulbEnergy/bulb-py\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e POETRY_HTTP_BASIC_BULB_USERNAME -e POETRY_HTTP_BASIC_BULB_PASSWORD -w \"/mnt/renovate/gh/BulbEnergy/bulb-py/bulb_smart_energy_clients\" docker.io/renovate/python:3.9.6 bash -l -c \"pip install poetry && poetry update --lock --no-interaction isort\"\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_python --label=renovate_child -v \"/mnt/renovate/gh/BulbEnergy/bulb-py\":\"/mnt/renovate/gh/BulbEnergy/bulb-py\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e POETRY_HTTP_BASIC_BULB_USERNAME -e POETRY_HTTP_BASIC_BULB_PASSWORD -w \"/mnt/renovate/gh/BulbEnergy/bulb-py/bulb_smart_energy_clients\" docker.io/renovate/python:3.9.6 bash -l -c \"pip install poetry && poetry update --lock --no-interaction isort\"\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:467:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Socket.<anonymous> (internal/child_process.js:439:11)\n    at Socket.emit (events.js:315:20)\n    at Socket.EventEmitter.emit (domain.js:467:12)\n    at Pipe.<anonymous> (net.js:673:12)"
  }
}
DEBUG: Passing TEMPORARY_ERROR error up(branch="renovate/isort-5.x-lockfile")
INFO: Temporary error - aborting
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 2209,
    "extract": 8241,
    "lookup": 38027
  },
  "total": 824469
}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

We are using the Poetry as package manager and indeed the `Resolving dependencies` takes a good chunk of time, I reckon that a timeout on the process is pre-empting it (the reported total run of the Renovate task is 824469ms, round 13 minutes).

**Comment by rarkins** [comment]
Yes, we should make child process timeouts admin-configurable. Not sure if we have an issue open already for that or not but we can keep this one until we find one.

**Comment by HonkingGoose** [comment]
@rarkins Maybe this is the issue you're thinking of? 😉 

Quote from issue:

> Add a safeguard timeout for each child process we call, including Docker. Ideally configured as an object that includes type: value mappings, e.g. `"npm": 600` meaning 600s timeout for npm install.
> 
> When using Docker, it should ideally kill the container too, if the timeout occurs.

It's issue #2804.

**Comment by expobrain** [comment]
Seems like there's no active progress in a while. Is there any workaround for this issue in the meanwhile?

**Comment by rarkins** [comment]
@expobrain if you run self hosted with a more powerful server than you'll hopefully not hit the timeout. 

Otherwise, a PR allowing admin customisation of the timeout value would be accepted, and then we can increase it for your repo specifically in the app

**Comment by expobrain** [comment]
@rarkins unfortunately we don't have plans yet to run Renovate on our hardware.

I'm planning to exclude the package's directory causing the slowness from Renovate for the time being so other packages in the same repo can take advantage of Renovate in the meantime.

As soon as I've some spare time I'll have a look at how to add the timeout feature to Renovate and make a PR.
