### ISSUE TITLE
RangeError exception updating an existing MR on gitlab

### ISSUE THREAD

**Issue by dlouzan** [renovatebot/renovate#10808]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: 25.52.5 (gitlab template v1.46.8)

**Describe the bug**

Renovate exits with an error trying to update an existing MR, going from `"@gitbeaker/node": "24.3.0"` to `"@gitbeaker/node": "31.0.0"`.  The error looks to happen while processing the unicode text in the changelogs.

- The initial MR is created correctly
- Subsequent runs trying to update this MR will fail with the exception below. Deleting the MR starts again the cycle, allowing the MR to be re-created but not to be updated.

My assumption is that something on the changelogs of gitbeaker is tripping renovate's parsing.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: getBranchPr(renovate/gitbeaker-node-31.x) (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
DEBUG: findPr(renovate/gitbeaker-node-31.x, undefined, open) (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
DEBUG: getPr(67) (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
DEBUG: getMR(67) (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
DEBUG: getBranchStatus(renovate/gitbeaker-node-31.x) (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
DEBUG: Got res with 1 results (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
DEBUG: Found existing PR (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
DEBUG: Processing existing PR (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
ERROR: Failed to ensure PR: chore(deps): update dependency @gitbeaker/node to v31 (repository=foo/bar, branch=renovate/gitbeaker-node-31.x)
       "err": {
         "message": "Invalid code point NaN",
         "stack": "RangeError: Invalid code point NaN\n    at Function.fromCodePoint (<anonymous>)\n    at Object.fromCodepointToUnicode (/usr/src/app/node_modules/emojibase/src/generateEmoticonPermutations.ts:22:5)\n    at stripEmoji (/usr/src/app/node_modules/renovate/lib/util/emoji.ts:97:18)\n    at String.replace (<anonymous>)\n    at Object.stripEmojis (/usr/src/app/node_modules/renovate/lib/util/emoji.ts:102:16)\n    at Object.ensurePr (/usr/src/app/node_modules/renovate/lib/workers/pr/index.ts:360:32)\n    at Object.processBranch (/usr/src/app/node_modules/renovate/lib/workers/branch/index.ts:592:33)\n    at Object.writeUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/write.ts:38:17)\n    at Object.update (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:129:11)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:50:17)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:111:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
       }
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

If this doesn't ring a bell already, I will try to create a repro case on gitlab.com.

**Additional context**

...

/cc @max-wittig @bufferoverflow @fgreinacher @ercanucan

**Comment by rarkins** [comment]
So strange that it only fails on updates and not creations when the content is in theory the same. Seems to be being thrown from the emoji library we use too. Can it be reproduced in a public repo?

**Comment by fgreinacher** [comment]
Seems to be GitLab-specific, as the same upgrade works on GitHub: https://github.com/fgreinacher/renovate-range-error/pull/2

**Comment by rarkins** [comment]
Can you try gitlab.com to see if it's all of Gitlab and jot something specific to your server?

**Comment by dlouzan** [comment]
@rarkins I'm trying to create a repro case on gitlab.com, will keep you posted

**Comment by dlouzan** [comment]
Here, just got the same error on a pipeline with this repo: https://gitlab.com/dlouzan/renovate-repro-10808

**Comment by dlouzan** [comment]
I'm not sure this helps you guys but actually something else I observed:

- Initially I created the repro case without a github token for release notes. That created the MRs but I noticed in the logs that release notes had not been downloaded
- I then added the token and triggered the second run. Interestingly, this still made the pipeline fail with the code point error. Since renovate died, the notes were never added to the MR
- I just now deleted the MRs and triggered the pipelines again. Same behaviour, but now with release notes on the MR.

**Comment by rarkins** [comment]
Interesting! Definitely confirms the observation that it happens on update and not create. Maybe we have a different logic path for MR body massaging for create and update, which may be a bug itself.

**Comment by dlouzan** [comment]
I just gave this another try on the repro repository and these are the findings:

- [Updating to latest renovate template 1.60.1](https://gitlab.com/dlouzan/renovate-repro-10808/-/commit/acbd202f9383daa472b63b4a5ce077c52622f63e) made the run work properly: https://gitlab.com/dlouzan/renovate-repro-10808/-/pipelines/351087097
- I then [reverted to the previous version 1.47.4](https://gitlab.com/dlouzan/renovate-repro-10808/-/commit/d5cb4ab1a53894812f0230c1685346aea84fc909) and let the pipeline run again. This also worked: https://gitlab.com/dlouzan/renovate-repro-10808/-/jobs/1492997526
- So this means that either the new gitbeaker dependency v32, or the latest gitlab 14.1 makes renovate not die anymore. I have no idea which. 

I'll unquarantine this dependency on our own internal renovate and let it run overnight, let's see if the problem is fixed too.

**Comment by dlouzan** [comment]
This issue is back with gitbeaker dependency v34 🙃

**Comment by PhilipAbed** [comment]
@rarkins i tried to reproduce on gitlab, I wasn't able to the new version doesn't fail apparently.
 but if you look at the StackTrace you can imagine where the issue is coming from probably:
 
![image](https://user-images.githubusercontent.com/42116482/161076704-75ed6e36-865d-43dc-81f2-d61abb209b85.png)

the code is failing on `stripEmoji` (`Invalid code point NaN`)

i've also noticed a comment in the code pointing out to: https://github.com/renovatebot/renovate/issues/12875

@dlouzan if it works on Creation, but not on Updating, 
then we might be creating some emoji or text that the emoji regex is catching but is unable to figure it out so 
we maybe can see if you have one of those merge-requests that you ran on and couldn't update? 
maybe we put it in a unit-test case and try to reproduce?

when i look at your current repo i see that it worked fine

**Comment by rarkins** [comment]
@PhilipAbed perhaps you can add a try/catch around the block which you think throws and we see if we can just ignore it?
