### ISSUE TITLE
Composer plugin API version is bumped

### ISSUE THREAD

**Issue by mbrodala** [renovatebot/renovate#11019]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: 25.58.0

**Describe the bug**

Renovate bumps the Composer plugin API version (virtual package `plugin-api-version`), in our case from `2.0.0` to `2.1.0`.

The reason for this is that the latest Composer version (currently 2.1.5) is used automatically.

Can anything be done about this aside from enforcing a Composer patch version? (see #6352)

Technically this should not be an issue but this is an unexpected change bundled with a regular package update so this _could_ have undesired side effects. So this report can also be seen as a note to keep in mind.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository: https://github.com/mbrodala/renovate-composer-plugin-api-version/pull/2
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by rarkins** [comment]
Sorry, I'm my a Composer user myself and don't really follow. Do you think Renovate is doing something wrong, or you want it to do something more advanced, or something else?

**Comment by mbrodala** [comment]
My point is mostly that Renovate should avoid such unrelated changes if possible. Bumping the Composer plugin API version could be done but that should happen in a separate change.

I could imagine that the update MR would even fail if there where package installed which require _exactly_ version `2.0.0` of the plugin API.

If you think there is nothing Renovate can do about this ATM, we can close this. I just wanted to be sure that people searching for this find at least a statement how the opinion of Renovate is about this.

**Comment by rarkins** [comment]
I wouldn't close this yet until either I understand it better or someone else chimes in. Do you mean for example that the composer API shouldn't be higher than the version of composer itself?

In general, it's always possible that Renovate can propose changes which are incompatible or don't work out of the box, but we prefer users to be aware there's a change needing action than to suppress them and the user is unaware. An example is with major breaking changes of a package. We do not claim that the PR we raise will work, but it's better than the user not knowing there's a major update pending.

**Comment by mbrodala** [comment]
My expected workflow would be:

- Renovate inspects the `composer.lock` for hints about the last Composer version used like `plugin-api-version`
- Renovate uses the same Composer major/minor version to prepare an update

This would ensure that the manifest/lockfile really only contains the necessary changes for a package update, nothing else. Again, we could require e.g. `composer-runtime-api` in version `2.0.0` (which is respected by Renovate AFAIK) to avoid unintentional lockfile updates by newer Composer versions.

Separately Renovate could attempt to update the lockfile without package updates using the latest Composer version. This would ensure that there's a notification about Composer (API) updates. Also this change would be minimal again and focus on lockfile migrations by newer Composer versions.

**Comment by viceice** [comment]
This is how we parse the composer version:

https://github.com/renovatebot/renovate/blob/74d7691befa635c1220d8569936273bfb950e748/lib/manager/composer/utils.ts#L20-L48

Do `composer-runtime-api` and `composer` `{major}.{minor}` version always match?

**Comment by mbrodala** [comment]
@viceice Interesting that you already respect `plugin-api-version`.

You currently only extract the major part of the version, this would explain the behavior I see. If the minor version was extracted too, Renovate would use Composer 2.0.* in our case, right?

In any case I cannot find a clear statement whether `plugin-api-version` always matches the Composer version.

The latest bump from 2.0.0 to 2.1.0 implies this however:

https://github.com/composer/composer/commit/7dd95a768bc1dd8c6f296ee0081f41ffa1444bbe

This change was published with the first RC for Composer 2.1.

I guess I'll ask the Composer devs about this.

**Comment by mbrodala** [comment]
Did that now: https://github.com/composer/composer/discussions/10030

**Comment by rarkins** [comment]
I think we could switch to "minor stream" precision for composer if that's what's confirmed.

**Comment by mbrodala** [comment]
@viceice Is the `reproduction:needed` tag still necessary?

**Comment by viceice** [comment]
Yes

**Comment by mbrodala** [comment]
I wonder why though. The issue itself is clear from my POV and even the location where this should be fixed:

https://github.com/renovatebot/renovate/blob/aa4fabe5997e07b2cb4f9f1b5eca8ed9810fc059/lib/manager/composer/utils.ts#L75-L79

**Comment by viceice** [comment]
Feel free to open a PR to fix, but it would need a test repo anyways. 🤷‍♂️

**Comment by viceice** [comment]
I thought we are waiting for an official answer of composer too?

**Comment by mbrodala** [comment]
Yes, unfortunately yes. I just wanted to be sure this issue here is not closed automatically before that.

**Comment by mbrodala** [comment]
@viceice OK, here we go:

https://github.com/mbrodala/renovate-composer-plugin-api-version/pull/2/files#diff-f37acfaa6b11f575a9a6f41a75fa73a61d0f8ebc2c9b8cddc215d8aca10e44f5R880

![image](https://user-images.githubusercontent.com/5037116/129522641-87dca28c-0df6-483b-9329-62cb886adc67.png)

**Comment by mbrodala** [comment]
Here Symfony Console is updated as expected but the `plugin-api-version` is also changed unintentionally.

**Comment by mbrodala** [comment]
The discussion in https://github.com/composer/composer/discussions/10030 now confirmed that `plugin-api-version` and `runtime-api-version` are independent from the specific Composer version. This means determining the Composer version from one of these two is futile. So e.g. Composer 2.2 could be released and still use plugin API version 2.1. And in theory Composer 3 could be released with runtime API version 2.x.

Long story short: It seems like we could need a repository option to configure the desired Composer major+minor version. Renovate could then use this to pick a suitable Docker image or do a runtime installation of Composer.

What do you think?

**Comment by rarkins** [comment]
When you say "a repository option" do you mean a Renovate config option? Or you mean that the Composer community needs a way to specify the Composer version in use, and then Renovate could utilize that?

**Comment by mbrodala** [comment]
I [mean the former](https://docs.renovatebot.com/configuration-options/), so basically within the per-project `renovate.json`. I wrote "repository option" to make a clear distinction to the "[global/admin options](https://docs.renovatebot.com/self-hosted-configuration/)".

**Comment by rarkins** [comment]
Doesn't `constraints.composer` already work?

**Comment by mbrodala** [comment]
@rarkins What do you mean exactly?

If you mean requiring `composer/composer` then no, since that would actually download and install Composer as dependency. This only makes sense for Composer plugin packages, not regular packages.

With Composer 2.2 there will be a [new platform package called `composer`](https://github.com/composer/composer/issues/9963) which could be used for this.

**Comment by rarkins** [comment]
I mean the existing renovate config option "constraints"

**Comment by mbrodala** [comment]
@rarkins Honestly I didn't know of this option.

I just gave it a try but got "some error":

https://github.com/mbrodala/renovate-composer-plugin-api-version/pull/2#issuecomment-901217255

Unfortunately https://app.renovatebot.com/dashboard#github/mbrodala/renovate-composer-plugin-api-version does not show me anything besides a `Bad credentials` HTTP fetch error in console/network pane.

**Comment by viceice** [comment]
can you paste the stderr and stdout from logs here, as we aren't allowed to see you logs by default

**Comment by mbrodala** [comment]
@viceice I'd gladly do that if you tell me how. Again, the Renovate dashboard does not show me anything. Are the logs available somewhere else, too?

**Comment by viceice** [comment]
No, we need to wait for @rarkins to fix the api server again.

**Comment by mbrodala** [comment]
OK, got it. I was still logged in using GitLab from long time ago. After logging out and logging in using Github again, I was able to see the logs.

Here's the latest one:

<details>

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "25.76.1"
}
DEBUG: Using localDir: /mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version
DEBUG: Repository cache is valid
DEBUG: initRepo("mbrodala/renovate-composer-plugin-api-version")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: mbrodala/renovate-composer-plugin-api-version default branch = master
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: Resetting npmrc
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: Checking cached config file name
DEBUG: Existing config file confirmed
DEBUG: Repo is onboarded
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ],
    "constraints": {
      "composer": "2.0"
    },
    "rangeStrategy": "update-lockfile"
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ],
    "constraints": {
      "composer": "2.0"
    },
    "rangeStrategy": "update-lockfile"
  }
}
DEBUG: Setting hostRules from config
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/__fixtures__/**"
  ]
}
DEBUG: detectSemanticCommits()
DEBUG: No vulnerability alerts found
DEBUG: No vulnerability alerts found
DEBUG: No baseBranches
DEBUG: extract()
DEBUG: Found cached extract
{
  "baseBranch": "master",
  "baseBranchSha": "6302c634a29aeeb7d735e55bd1b09afd5c757006"
}
DEBUG: Deleted cached dep updates
INFO: Dependency extraction complete
{
  "baseBranch": "master",
  "stats": {
    "managers": {
      "composer": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 1
    }
  }
}
DEBUG: Package releases lookups complete
{
  "baseBranch": "master"
}
DEBUG: branchifyUpgrades
DEBUG: Using group branchName template
DEBUG: Dependency symfony/console is part of group symfony packages
DEBUG: 1 flattened updates found: symfony/console
DEBUG: Returning 1 branch(es)
DEBUG: Fetching changelog: https://github.com/symfony/console (5.2.14 -> 5.3.6)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "composer": [
      {
        "packageFile": "composer.json",
        "deps": [
          {
            "depType": "require",
            "depName": "symfony/console",
            "currentValue": "^5.2",
            "datasource": "packagist",
            "lockedVersion": "5.2.14",
            "depIndex": 0,
            "warnings": [],
            "versioning": "composer",
            "sourceUrl": "https://github.com/symfony/console",
            "homepage": "https://symfony.com",
            "currentVersion": "5.2.14",
            "isSingleVersion": true,
            "fixedVersion": "5.2.14",
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "5.3.6",
                "newValue": "^5.2",
                "releaseTimestamp": "2021-07-27T19:10:22.000Z",
                "newMajor": 5,
                "newMinor": 3,
                "updateType": "minor",
                "isRange": true,
                "isLockfileUpdate": true,
                "branchName": "renovate/symfony"
              }
            ]
          }
        ],
        "lockFiles": [
          "composer.lock"
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/symfony
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 2 Pull Requests
DEBUG: currentHourStart=2021-08-18T15:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/symfony)
DEBUG: findPr(renovate/symfony, undefined, open)
DEBUG: Found PR #2
DEBUG: Returning from graphql open PR list
DEBUG: 1 PRs are currently open
DEBUG: PR concurrent limit remaining: 19
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 2
}
DEBUG: PullRequests limit = 2
DEBUG: Calculating hourly PRs remaining
DEBUG: currentHourStart=2021-08-18T15:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating branchConcurrentLimit (20)
DEBUG: 1 already existing branches found: renovate/symfony
DEBUG: Branch concurrent limit remaining: 19
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 2
}
DEBUG: Branches limit = 2
DEBUG: Setting current branch to master(branch="renovate/symfony")
DEBUG: Initializing git repository into /mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version(branch="renovate/symfony")
DEBUG: git clone completed(branch="renovate/symfony")
{
  "durationMs": 642
}
DEBUG: latest repository commit(branch="renovate/symfony")
{
  "latestCommit": {
    "hash": "6302c634a29aeeb7d735e55bd1b09afd5c757006",
    "date": "2021-08-18T17:36:16+02:00",
    "message": "[TASK] Require Composer 2.0 for Renovate updates",
    "refs": "HEAD -> master, origin/master, origin/HEAD",
    "body": "See https://docs.renovatebot.com/configuration-options/#constraints\r\nAnd https://github.com/renovatebot/renovate/issues/11019#issuecomment-901184853",
    "author_name": "Mathias Brodala",
    "author_email": "mbrodala@pagemachine.de"
  }
}
DEBUG: Setting git author name(branch="renovate/symfony")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/symfony")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: Setting branchPrefix: renovate/(branch="renovate/symfony")
DEBUG: latest commit(branch="renovate/symfony")
{
  "branchName": "master",
  "latestCommitDate": "2021-08-18T17:36:16+02:00"
}
DEBUG: branchExists=true(branch="renovate/symfony")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/symfony")
DEBUG: PR rebase requested=true(branch="renovate/symfony")
DEBUG: Checking if PR has been edited(branch="renovate/symfony")
DEBUG: Found existing branch PR(branch="renovate/symfony")
DEBUG: Checking schedule(at any time, null)(branch="renovate/symfony")
DEBUG: No schedule defined(branch="renovate/symfony")
DEBUG: Branch already exists(branch="renovate/symfony")
DEBUG: Manual rebase requested via PR checkbox for #2(branch="renovate/symfony")
DEBUG: Using reuseExistingBranch: false(branch="renovate/symfony")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/symfony")
DEBUG: Starting search at index 47(packageFile="composer.json", branch="renovate/symfony")
{
  "depName": "symfony/console"
}
DEBUG: Found match at index 47(packageFile="composer.json", branch="renovate/symfony")
{
  "depName": "symfony/console"
}
DEBUG: Found composer lock file(packageFile="composer.json", branch="renovate/symfony")
DEBUG: No content changed(packageFile="composer.json", branch="renovate/symfony")
{
  "depName": "symfony/console"
}
DEBUG: update-lockfile add(packageFile="composer.json", branch="renovate/symfony")
{
  "depName": "symfony/console"
}
DEBUG: composer.updateArtifacts(composer.json)(branch="renovate/symfony")
DEBUG: Using cache directory from admin config(branch="renovate/symfony")
{
  "cacheDir": "/tmp/renovate-cache/others/composer"
}
DEBUG: Using composer constraint from config(branch="renovate/symfony")
{
  "version": "2.0"
}
DEBUG: composer command(branch="renovate/symfony")
{
  "cmd": "composer",
  "args": "update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins"
}
DEBUG: Using docker to execute(branch="renovate/symfony")
DEBUG: No tag or tagConstraint specified(branch="renovate/symfony")
{
  "image": "docker.io/renovate/php"
}
DEBUG: Fetching Docker image: docker.io/renovate/php(branch="renovate/symfony")
DEBUG: Finished fetching Docker image(branch="renovate/symfony")
DEBUG: Executing command(branch="renovate/symfony")
{
  "command": [
    "docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\""
  ]
}
DEBUG: rawExec err(branch="renovate/symfony")
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"",
    "stdout": "Installing tool composer v2.0\nInvalid version: 2.0\n",
    "stderr": "",
    "message": "Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:467:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  }
}
DEBUG: Failed to generate composer.lock(branch="renovate/symfony")
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"",
    "stdout": "Installing tool composer v2.0\nInvalid version: 2.0\n",
    "stderr": "",
    "message": "Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:467:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  }
}
DEBUG: Updated 1 package files(branch="renovate/symfony")
DEBUG: No updated lock files in branch(branch="renovate/symfony")
DEBUG: Branch timestamp: 2021-07-27T19:10:22.000Z(branch="renovate/symfony")
DEBUG: PR is older than 2 hours, raise PR with lock file errors(branch="renovate/symfony")
DEBUG: 1 file(s) to commit(branch="renovate/symfony")
DEBUG: Committing files to branch renovate/symfony(branch="renovate/symfony")
WARN: Detected empty commit - aborting git push(branch="renovate/symfony")
{
  "commitRes": {
    "author": null,
    "branch": "",
    "commit": "",
    "root": false,
    "summary": {
      "changes": 0,
      "insertions": 0,
      "deletions": 0
    }
  }
}
DEBUG: Checking if we can automerge branch(branch="renovate/symfony")
DEBUG: mergeStatus=no automerge(branch="renovate/symfony")
DEBUG: Ensuring PR(branch="renovate/symfony")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/symfony")
DEBUG: Found existing PR(branch="renovate/symfony")
DEBUG: Forcing PR because of artifact errors(branch="renovate/symfony")
DEBUG: Processing existing PR(branch="renovate/symfony")
DEBUG: updatePr(2, Update dependency symfony/console to v5.3.6, body)(branch="renovate/symfony")
DEBUG: PR updated(branch="renovate/symfony")
{
  "pr": 2
}
INFO: PR updated(branch="renovate/symfony")
{
  "pr": 2,
  "prTitle": "Update dependency symfony/console to v5.3.6"
}
WARN: artifactErrors(branch="renovate/symfony")
{
  "artifactErrors": [
    {
      "lockFile": "composer.lock",
      "stderr": "Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\n"
    }
  ]
}
DEBUG: Retrieved closed PR list with graphql(branch="renovate/symfony")
{
  "prNumbers": [
    1
  ]
}
DEBUG: Getting comments for #2(branch="renovate/symfony")
DEBUG: Found 1 comments(branch="renovate/symfony")
DEBUG: Ensuring comment "⚠ Artifact update problem" in #2(branch="renovate/symfony")
DEBUG: Comment is already update-to-date(branch="renovate/symfony")
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/symfony"
  ],
  "renovateBranches": [
    "renovate/symfony"
  ]
}
DEBUG: remainingBranches=
DEBUG: No branches to clean up
DEBUG: Retrieving issueList
DEBUG: Retrieved 0 issues
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 1665,
    "extract": 2,
    "lookup": 462,
    "update": 28107
  },
  "total": 30484
}
DEBUG: http statistics
{
  "hostStats": [
    "api.github.com, 11 requests, 269ms request average, 0ms queue average"
  ],
  "totalRequests": 11
}
INFO: Repository finished
{
  "durationMs": 30484
}
```

</details>

**Comment by mbrodala** [comment]
`Invalid version: 2.0` sounds like I need a full version? That would be a bit too restricting IMO ...

**Comment by viceice** [comment]
nope, we use https://github.com/composer/composer/releases to install composer, so you should use a range or a full composer version

Here is how we compute the contraint
https://github.com/renovatebot/renovate/blob/aa4fabe5997e07b2cb4f9f1b5eca8ed9810fc059/lib/manager/composer/utils.ts#L8-L45

maybe we need to improve it for composer to not accept short versions

**Comment by mbrodala** [comment]
Alright, it worked with the latest 2.0 version (2.0.14) now:

<details>

```
DEBUG: exec completed(branch="renovate/symfony")
{
  "cmd": "docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\":\"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/mbrodala/renovate-composer-plugin-api-version\" docker.io/renovate/php bash -l -c \"install-tool composer 2.0.14 && composer update symfony/console --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"",
  "durationMs": 4177,
  "stdout": "Installing tool composer v2.0.14\nComposer version 2.0.14 2021-05-21 17:03:37\n",
  "stderr": "Loading composer repositories with package information\nUpdating dependencies\nLock file operations: 1 install, 1 update, 0 removals\n  - Upgrading symfony/console (v5.2.14 => v5.3.6)\n  - Locking symfony/deprecation-contracts (v2.4.0)\nWriting lock file\nInstalling dependencies from lock file (including require-dev)\nPackage operations: 11 installs, 0 updates, 0 removals\n  - Downloading symfony/polyfill-php80 (v1.23.1)\n  - Downloading symfony/polyfill-mbstring (v1.23.1)\n  - Downloading symfony/polyfill-intl-normalizer (v1.23.0)\n  - Downloading symfony/polyfill-intl-grapheme (v1.23.1)\n  - Downloading symfony/polyfill-ctype (v1.23.0)\n  - Downloading symfony/string (v5.3.3)\n  - Downloading psr/container (1.1.1)\n  - Downloading symfony/service-contracts (v2.4.0)\n  - Downloading symfony/polyfill-php73 (v1.23.0)\n  - Downloading symfony/deprecation-contracts (v2.4.0)\n  - Downloading symfony/console (v5.3.6)\n  - Installing symfony/polyfill-php80 (v1.23.1): Extracting archive\n  - Installing symfony/polyfill-mbstring (v1.23.1): Extracting archive\n  - Installing symfony/polyfill-intl-normalizer (v1.23.0): Extracting archive\n  - Installing symfony/polyfill-intl-grapheme (v1.23.1): Extracting archive\n  - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive\n  - Installing symfony/string (v5.3.3): Extracting archive\n  - Installing psr/container (1.1.1): Extracting archive\n  - Installing symfony/service-contracts (v2.4.0): Extracting archive\n  - Installing symfony/polyfill-php73 (v1.23.0): Extracting archive\n  - Installing symfony/deprecation-contracts (v2.4.0): Extracting archive\n  - Installing symfony/console (v5.3.6): Extracting archive\n10 packages you are using are looking for funding.\nUse the `composer fund` command to find out more!\n"
}
```

</details

https://github.com/mbrodala/renovate-composer-plugin-api-version/pull/2/files

Now `plugin-api-version` is not bumped anymore. :-)

**Comment by herndlm** [comment]
@mbrodala since https://github.com/renovatebot/renovate/pull/13187 the minor version is extracted as well on constraint detection, this might help too. I have not tried it yet but https://docs.renovatebot.com/self-hosted-configuration/#binarysource (set to install) sounds very promising too, I think this is going to become the default at some point.

**Comment by mbrodala** [comment]
Thanks for the info, right now it seems to work fine in any case so I'll close this.

**Comment by jeroennoten** [comment]
I don't think this problem is resolved by that change. `plugin-api-version` in `composer.lock` is still updated if not on the most recent version, because it now for example parses `"plugin-api-version": "2.0.0"` to a constraint `"composer": "^2.0", which is satisfied by version 2.2 of composer, and therefore the `plugin-api-version` will be updated to `2.2.0` in this case.
