### ISSUE TITLE
Could not read script <name>.gradle as it does not exist (RN with Gradle 7.1)

### ISSUE THREAD

**Issue by leotm** [renovatebot/renovate#11054]
**Running**

- [x] WhiteSource Renovate hosted app on github.com

Platform

- [x] github.com

Renovate version: 25.63.1

**Describe the bug**

Similar to https://github.com/renovatebot/renovate/issues/4632#issuecomment-561836382

```sh
DEBUG: rawExec err
...
WARN: Gradle extraction failed
...

```

Noticed since adding [Dependency Dashboard](https://github.com/leotm/react-native-template-typescript/issues/71) (Master Issue) hr ago

Diving deeper past 7 hrs of logs too

```sh
Could not read script '.../node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist
```

**Relevant debug logs**

<details><summary>Logs summary</summary>

```sh
DEBUG: rawExec err
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/leotm/react-native-template-typescript\":\"/mnt/renovate/gh/leotm/react-native-template-typescript\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/leotm/react-native-template-typescript/android\" docker.io/renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"",
    "stdout": "Downloading https://services.gradle.org/distributions/gradle-7.1.1-bin.zip\n..........10%...........20%...........30%..........40%...........50%...........60%..........70%...........80%...........90%...........100%\n\nWelcome to Gradle 7.1.1!\n\nHere are the highlights of this release:\n - Faster incremental Java compilation\n - Easier source set configuration in the Kotlin DSL\n\nFor more details see https://docs.gradle.org/7.1.1/release-notes.html\n\nTo honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.1.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.\nDaemon will be stopped at the end of the build \n",
    "stderr": "\nFAILURE: Build failed with an exception.\n\n* Where:\nSettings file '/mnt/renovate/gh/leotm/react-native-template-typescript/android/settings.gradle' line: 2\n\n* What went wrong:\nA problem occurred evaluating settings 'MyApp'.\n> Could not read script '/mnt/renovate/gh/leotm/react-native-template-typescript/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 37s\n",
    "message": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/leotm/react-native-template-typescript\":\"/mnt/renovate/gh/leotm/react-native-template-typescript\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/leotm/react-native-template-typescript/android\" docker.io/renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\n\nFAILURE: Build failed with an exception.\n\n* Where:\nSettings file '/mnt/renovate/gh/leotm/react-native-template-typescript/android/settings.gradle' line: 2\n\n* What went wrong:\nA problem occurred evaluating settings 'MyApp'.\n> Could not read script '/mnt/renovate/gh/leotm/react-native-template-typescript/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 37s\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/leotm/react-native-template-typescript\":\"/mnt/renovate/gh/leotm/react-native-template-typescript\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/leotm/react-native-template-typescript/android\" docker.io/renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\n\nFAILURE: Build failed with an exception.\n\n* Where:\nSettings file '/mnt/renovate/gh/leotm/react-native-template-typescript/android/settings.gradle' line: 2\n\n* What went wrong:\nA problem occurred evaluating settings 'MyApp'.\n> Could not read script '/mnt/renovate/gh/leotm/react-native-template-typescript/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 37s\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:467:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  }
}
WARN: Gradle extraction failed
{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/leotm/react-native-template-typescript\":\"/mnt/renovate/gh/leotm/react-native-template-typescript\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/leotm/react-native-template-typescript/android\" docker.io/renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\n\nFAILURE: Build failed with an exception.\n\n* Where:\nSettings file '/mnt/renovate/gh/leotm/react-native-template-typescript/android/settings.gradle' line: 2\n\n* What went wrong:\nA problem occurred evaluating settings 'MyApp'.\n> Could not read script '/mnt/renovate/gh/leotm/react-native-template-typescript/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 37s\n"
}
```

</details>

**Minimal repro repo?**

- [x] Happens in public repository https://github.com/leotm/react-native-template-typescript

**Additional context**

Last working log _417188290_, but it used a cached extract

Upgraded from Gradle 6.9 to 7.1 over wk ago, so doubt its caching Gradle 6.9 (https://github.com/leotm/react-native-template-typescript/commit/2fd5737c331f57eecd34d1c7c130070e38570806

It also might not be _postinstall_'ing my [native_modules.gradle patch](https://github.com/leotm/react-native-template-typescript/commit/2fd5737c331f57eecd34d1c7c130070e38570806#diff-3be5207148e8e78c67a2211b3ecf474f3210cf7e6925c627fd8f228771b2fde0)

**Comment by viceice** [comment]
Please don't remove issue template parts

**Comment by rarkins** [comment]
Is that `node_modules` that Gradle can't find something which needs to be dynamically installed prior to `gradle` being run? If so then we don't have that capability.

However, we recommend you add the preset `:switchToGradleLite` to use our JS-based gradle parser instead of using Gradle itself. That way a project doesn't need to fully resolve in order to parse the dependency declarations.

**Comment by leotm** [comment]
Yes for Android (and iOS via Podfile) native modules auto-linking (https://github.com/facebook/react-native/commit/261197d85705dad1a362cc4637aa308c0382dcbe)

`node_modules` should be there after clone/yarn right

```sh
...
DEBUG: git clone completed
...
DEBUG: Spawning yarn install
...
// Should have node_modules here
```

The warning's weirdly fixed/resolved at least for now

But seems there's some cause to the error logs showing

```sh
...
DEBUG: git clone completed
...
// 🪦 
...
DEBUG: Spawning yarn install
// Too late
```

Cheers for the speedy responses

**Comment by leotm** [comment]
Merging https://github.com/leotm/react-native-template-typescript/pull/72 seems to re-trigger the above

**Comment by rarkins** [comment]
Unfortunately there is nothing that can be done at present. Renovate does not perform any `yarn install` prior to Gradle extract, please see my recommendation earlier: https://github.com/renovatebot/renovate/issues/11054#issuecomment-891195310

**Comment by leotm** [comment]
checking _switchToGradleLite_'s legit feels bit like chasing a ghost, with the stale doc refs

![Capture](https://user-images.githubusercontent.com/1881059/130137349-01874f0c-cc96-4b59-aa4c-b6c0e652b4ee.PNG)

![Capture3](https://user-images.githubusercontent.com/1881059/130137367-d26a9e1c-a783-4ec3-88fa-db82241d099c.PNG)

![Capture](https://user-images.githubusercontent.com/1881059/130138307-e048ad38-5d94-4eb0-a7bb-17dc20c6dc92.PNG)

want me to PR a public _Internal Presets_ section in the docs findable via search engines?

![Capture](https://user-images.githubusercontent.com/1881059/130138023-919b8ec2-fd31-40b2-a082-586474bfebed.PNG)

**Comment by viceice** [comment]
We've release renovate v26, which has switched to Gradle lite by default.

So please open a new discussion if you've any new problems.
