### ISSUE TITLE
Renovate is not working with Yarn v2 & v3 scoped private repositories

### ISSUE THREAD

**Issue by BryanHunt** [renovatebot/renovate#11100]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x ] GitLab self-hosted

Renovate version: 25.67.0

**Describe the bug**

Renovate is attempting to use https://registry.npmjs.org to locate a scoped package instead of the private registry configured in the `.yarnrc.yml`.

...

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
[34mDEBUG[39m: Using RE2 as regex engine
[34mDEBUG[39m: Parsing configs
[34mDEBUG[39m: File config
       "config": {
         "repositories": [
           "hwinf-microservice/examples/test-b"
         ],
         "requireConfig": true,
         "onboarding": true,
         "onboardingConfig": {"extends": ["config:base"]},
         "enabledManagers": ["npm"]
       }
[34mDEBUG[39m: CLI config
       "config": {}
[34mDEBUG[39m: Env config
       "config": {
         "hostRules": [
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "platform": "gitlab",
         "endpoint": "https://gitlab-master.******.com/api/v4",
         "token": "***********"
       }
[34mDEBUG[39m: Combined config
       "config": {
         "repositories": [
           "hwinf-microservice/examples/test-b"
         ],
         "requireConfig": true,
         "onboarding": true,
         "onboardingConfig": {"extends": ["config:base"]},
         "enabledManagers": ["npm"],
         "hostRules": [
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "platform": "gitlab",
         "endpoint": "https://gitlab-master.******.com/api/v4",
         "token": "***********"
       }
[34mDEBUG[39m: Adding trailing slash to endpoint
[34mDEBUG[39m: GitLab version is: 14.0.6
[34mDEBUG[39m: Using platform gitAuthor: ******************
[34mDEBUG[39m: Adding token authentication for gitlab-master.******.com to hostRules
[34mDEBUG[39m: Using baseDir: /tmp/renovate
[34mDEBUG[39m: Using cacheDir: /tmp/renovate/cache
[34mDEBUG[39m: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
[34mDEBUG[39m: Commits limit = null
[34mDEBUG[39m: Clearing hostRules
[34mDEBUG[39m: Adding token authentication for github.com to hostRules
[34mDEBUG[39m: Adding token authentication for gitlab-master.******.com to hostRules


[34mDEBUG[39m: Clearing hostRules
[34mDEBUG[39m: Adding token authentication for github.com to hostRules
[34mDEBUG[39m: Adding token authentication for gitlab-master.******.com to hostRules
[32m INFO[39m: Repository started[90m (repository=hwinf-microservice/examples/test-b)[39m
       "renovateVersion": "25.67.0"
[34mDEBUG[39m: Using localDir: /tmp/renovate/repos/gitlab/hwinf-microservice/examples/test-b[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: hwinf-microservice/examples/test-b default branch = main[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Enabling Git FS[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: hwinf-microservice/examples/test-b http URL = https://gitlab-master.******.com/hwinf-microservice/examples/test-b.git[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: resetMemCache()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Resetting npmrc[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: checkOnboarding()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: isOnboarded()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: findFile(renovate.json)[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Initializing git repository into /tmp/renovate/repos/gitlab/hwinf-microservice/examples/test-b[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: git clone completed[90m (repository=hwinf-microservice/examples/test-b)[39m
       "durationMs": 397
[34mDEBUG[39m: latest repository commit[90m (repository=hwinf-microservice/examples/test-b)[39m
       "latestCommit": {
         "hash": "ca294f62fde136989bc0bc5d24d81e896c555a39",
         "date": "2021-08-04T19:22:07+00:00",
         "message": "Merge branch 'renovate/pin-dependencies' into 'main'",
         "refs": "HEAD -> main, origin/main, origin/HEAD",
         "body": "Pin dependency typescript to 4.3.5\n\nSee merge request hwinf-microservice/examples/test-b!1",
         "author_name": "GPUWA Ops",
         "author_email": "******@******.com"
       }
[34mDEBUG[39m: Setting git author name[90m (repository=hwinf-microservice/examples/test-b)[39m
       "gitAuthorName": "GPUWA Ops"
[34mDEBUG[39m: Setting git author email[90m (repository=hwinf-microservice/examples/test-b)[39m
       "gitAuthorEmail": "******@******.com"
[34mDEBUG[39m: Config file exists[90m (repository=hwinf-microservice/examples/test-b)[39m
       "fileName": "renovate.json"
[34mDEBUG[39m: ensureIssueClosing()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Repo is onboarded[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Found renovate.json config file[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Repository config[90m (repository=hwinf-microservice/examples/test-b)[39m
       "fileName": "renovate.json",
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": ["config:js-lib"],
         "packageRules": [
           {"matchUpdateTypes": ["minor", "patch", "pin", "digest"], "automerge": true}
         ],
         "assignees": ["bhunt"]
       }
[34mDEBUG[39m: migrateAndValidate()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: No config migration necessary[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: massaged config[90m (repository=hwinf-microservice/examples/test-b)[39m
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": ["config:js-lib"],
         "packageRules": [
           {"matchUpdateTypes": ["minor", "patch", "pin", "digest"], "automerge": true}
         ],
         "assignees": ["bhunt"]
       }
[34mDEBUG[39m: migrated config[90m (repository=hwinf-microservice/examples/test-b)[39m
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": ["config:js-lib"],
         "packageRules": [
           {"matchUpdateTypes": ["minor", "patch", "pin", "digest"], "automerge": true}
         ],
         "assignees": ["bhunt"]
       }
[34mDEBUG[39m: Setting hostRules from config[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Found repo ignorePaths[90m (repository=hwinf-microservice/examples/test-b)[39m
       "ignorePaths": [
         "**/node_modules/**",
         "**/bower_components/**",
         "**/vendor/**",
         "**/examples/**",
         "**/__tests__/**",
         "**/test/**",
         "**/tests/**",
         "**/__fixtures__/**"
       ]
[34mDEBUG[39m: detectSemanticCommits()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: getCommitMessages[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Semantic commits detection: unknown[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: No semantic commits detected[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Setting branchPrefix: renovate/[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: No vulnerability alerts found[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: No baseBranches[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: extract()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Setting current branch to main[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: latest commit[90m (repository=hwinf-microservice/examples/test-b)[39m
       "branchName": "main",
       "latestCommitDate": "2021-08-04T19:22:07+00:00"
[34mDEBUG[39m: Applying enabledManagers filtering[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Using file match: (^|/)package.json$ for manager npm[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Matched 1 file(s) for manager npm: package.json[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: npm file package.json has name "@hwinf-microservice/test-b"[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Detecting pnpm Workspaces[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Detecting Lerna and Yarn Workspaces[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Finding locked versions[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Found npm package files[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Found 1 package file(s)[90m (repository=hwinf-microservice/examples/test-b)[39m
[32m INFO[39m: Dependency extraction complete[90m (repository=hwinf-microservice/examples/test-b)[39m
       "baseBranch": "main",
       "stats": {
         "managers": {"npm": {"fileCount": 1, "depCount": 4}},
         "total": {"fileCount": 1, "depCount": 4}
       }
[34mDEBUG[39m: Dependency lookup failure: not found[90m (repository=hwinf-microservice/examples/test-b)[39m
       "err": {
         "name": "HTTPError",
         "timings": {
           "start": 1628109128505,
           "socket": 1628109128505,
           "lookup": 1628109128518,
           "connect": 1628109128541,
           "secureConnect": 1628109128779,
           "upload": 1628109128780,
           "response": 1628109128935,
           "end": 1628109128935,
           "phases": {
             "wait": 0,
             "dns": 13,
             "tcp": 23,
             "tls": 238,
             "request": 1,
             "firstByte": 155,
             "download": 0,
             "total": 430
           }
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/25.67.0 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://registry.npmjs.org/@hwinf-microservice%2Ftest-a",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 404,
           "statusMessage": "Not Found",
           "body": {"error": "Not found"},
           "headers": {
             "date": "Wed, 04 Aug 2021 20:32:08 GMT",
             "content-type": "application/json",
             "content-length": "21",
             "connection": "close",
             "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
             "vary": "Accept-Encoding",
             "server": "cloudflare",
             "cf-ray": "679a8da6e9c1ed2f-SJC"
           },
           "httpVersion": "1.1"
         }
       },
       "packageName": "@hwinf-microservice/test-a"
[34mDEBUG[39m: Failed to look up dependency @hwinf-microservice/test-a[90m (repository=hwinf-microservice/examples/test-b, packageFile=package.json, dependency=@hwinf-microservice/test-a)[39m
[34mDEBUG[39m: Package releases lookups complete[90m (repository=hwinf-microservice/examples/test-b)[39m
       "baseBranch": "main"
[34mDEBUG[39m: branchifyUpgrades[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: 0 flattened updates found: [90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Returning 0 branch(es)[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: config.repoIsOnboarded=true[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: packageFiles with updates[90m (repository=hwinf-microservice/examples/test-b)[39m
       "config": {
         "npm": [
           {
             "packageFile": "package.json",
             "deps": [
               {
                 "depType": "devDependencies",
                 "depName": "@hwinf-microservice/test-a",
                 "currentValue": "^1.0.1",
                 "datasource": "npm",
                 "prettyDepType": "devDependency",
                 "lockedVersion": "1.0.1",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "@hwinf-microservice/test-a",
                     "message": "Failed to look up dependency @hwinf-microservice/test-a"
                   }
                 ],
                 "versioning": "npm"
               },
               {
                 "depType": "devDependencies",
                 "depName": "typescript",
                 "currentValue": "4.3.5",
                 "datasource": "npm",
                 "prettyDepType": "devDependency",
                 "lockedVersion": "4.3.5",
                 "depIndex": 1,
                 "updates": [],
                 "warnings": [],
                 "versioning": "npm",
                 "sourceUrl": "https://github.com/Microsoft/TypeScript",
                 "homepage": "https://www.typescriptlang.org/",
                 "currentVersion": "4.3.5",
                 "fixedVersion": "4.3.5"
               },
               {
                 "depType": "volta",
                 "depName": "node",
                 "currentValue": "16.6.0",
                 "datasource": "github-tags",
                 "lookupName": "nodejs/node",
                 "versioning": "node",
                 "commitMessageTopic": "Node.js",
                 "prettyDepType": "volta",
                 "depIndex": 2,
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": "https://github.com/nodejs/node",
                 "currentVersion": "16.6.0",
                 "fixedVersion": "16.6.0"
               },
               {
                 "depType": "volta",
                 "depName": "yarn",
                 "currentValue": "1.22.11",
                 "datasource": "npm",
                 "commitMessageTopic": "Yarn",
                 "prettyDepType": "volta",
                 "depIndex": 3,
                 "updates": [],
                 "warnings": [],
                 "versioning": "npm",
                 "sourceUrl": "https://github.com/yarnpkg/yarn",
                 "currentVersion": "1.22.11",
                 "fixedVersion": "1.22.11"
               }
             ],
             "packageJsonName": "@hwinf-microservice/test-b",
             "packageFileVersion": "1.0.0",
             "packageJsonType": "library",
             "yarnLock": "yarn.lock",
             "managerData": {},
             "skipInstalls": true,
             "constraints": {"yarn": "^2.2.0"},
             "lockFiles": ["yarn.lock"]
           }
         ]
       }
[34mDEBUG[39m: processRepo()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Processing 0 branches: [90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Calculating hourly PRs remaining[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: currentHourStart=2021-08-04T20:00:00.000+00:00[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: PR hourly limit remaining: 2[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Calculating prConcurrentLimit (20)[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: 0 PRs are currently open[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: PR concurrent limit remaining: 20[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Calculated maximum PRs remaining this run[90m (repository=hwinf-microservice/examples/test-b)[39m
       "prsRemaining": 2
[34mDEBUG[39m: PullRequests limit = 2[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Calculating hourly PRs remaining[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: currentHourStart=2021-08-04T20:00:00.000+00:00[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: PR hourly limit remaining: 2[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Calculating branchConcurrentLimit (20)[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: 0 already existing branches found: [90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Branch concurrent limit remaining: 20[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Calculated maximum branches remaining this run[90m (repository=hwinf-microservice/examples/test-b)[39m
       "branchesRemaining": 2
[34mDEBUG[39m: Branches limit = 2[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Removing any stale branches[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: config.repoIsOnboarded=true[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: No renovate branches found[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: ensureIssueClosing()[90m (repository=hwinf-microservice/examples/test-b)[39m
[34mDEBUG[39m: Repository timing splits (milliseconds)[90m (repository=hwinf-microservice/examples/test-b)[39m
       "splits": {"init": 1305, "extract": 347, "lookup": 459, "update": 130},
       "total": 2244
[34mDEBUG[39m: http statistics[90m (repository=hwinf-microservice/examples/test-b)[39m
       "hostStats": [
         "gitlab-master.******.com, 3 requests, 151ms request average, 0ms queue average"
       ],
       "totalRequests": 3
[32m INFO[39m: Repository finished[90m (repository=hwinf-microservice/examples/test-b)[39m
       "durationMs": 2244


[34mDEBUG[39m: Renovate exiting
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

.yarnrc.yml:

```yml
nodeLinker: node-modules

npmScopes:
  hwinf-microservice:
    npmPublishRegistry: "https://gitlab-master.*****.com/api/v4/projects/47937/packages/npm/"
    npmRegistryServer: "https://gitlab-master.*****.com/api/v4/packages/npm/"

yarnPath: ".yarn/releases/yarn-berry.cjs"
```
...

**Comment by viceice** [comment]
This is not currently supported by renovate, as we don't parse `.yarnrc.yaml` file.

Workaround: add `npmrc` option to `renovate.json`
```json
{
  "npmrc": "registry=https://gitlab-master.*****.com/api/v4/packages/npm/"
}
```

@rarkins I think this looks more like a feature request than a bug to me.

**Comment by HonkingGoose** [comment]
Maybe we should make an issue that tracks Yarn 3 support for Renovate?

**Comment by viceice** [comment]
> Maybe we should make an issue that tracks Yarn 3 support for Renovate?

It's both, Yarn v2 and v3 are using the `.yarnrc.yaml`, so we don't support custom / private registries for yarn v2+

**Comment by rarkins** [comment]
For anyone else reading this:
- Renovate doesn't currently parse registry information from `.yarnrc.yaml`, so when it does its lookups it will try registry.npmjs.org
- Yarn itself should still see the `.yarnrc.yaml` file if Renovate spawns it, so that part should still succeed

Right now adding `config.npmrc` is the best workaround because it means Renovate will learn the registry that way, but it won't impact Yarn itself.

**Comment by BryanHunt** [comment]
Thanks for the workaround.  I am now unblocked.  In the case of scoped packages, you need to use a scoped registry.   In my particular case, this was the workaround:

```
{
  "npmrc": "@hwinf-microservice:registry=https://gitlab-master.*****.com/api/v4/packages/npm/"
}
```
