### ISSUE TITLE
Author identity unknown

### ISSUE THREAD

**Issue by UziTech** [renovatebot/renovate#11554]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

26.16.0

### Describe the bug

getting this error even with `gitAuthor` specified in the config.

```
WARN: Error updating branch (repository=******, branch=renovate/jose-3.x)
       "err": {
         "task": {
           "commands": [
             "commit",
             "-m",
             "Update dependency jose to v3.15.5",
             "--no-verify"
           ],
           "format": "utf-8"
         },
         "message": "Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: unable to auto-detect email address (got 'ubuntu@runner-9zcw2jgx-project-28820951-concurrent-0.(none)')\n",
         "stack": "Error: Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: unable to auto-detect email address (got 'ubuntu@runner-9zcw2jgx-project-28820951-concurrent-0.(none)')\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       }
```

seems related to #6540 and #11536

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by EspadaV8** [comment]
For now I've "resolved" this by adding

```
image: renovate/renovate:26.15.3-slim@sha256:ca341ff030b4b3201ff7da89a4252a06c9706b9d512c50cd6603bf6f7017478a
```

To the top of my `.gitlab-ci.yml` file to downgrade to v26.15.3.

**Comment by UziTech** [comment]
or you can pin the version with:

```
include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v3.14.3
```
v3.14.3 == renovate@v26.15.3

**Comment by rarkins** [comment]
The problem logged in this issue was already fixed in 26.17.0, however there possibly remains a problem with *onboarding* commits. See #11546

**Comment by UziTech** [comment]
https://gitlab.com/renovate-bot/renovate-runner/ hasn't been updated with a version that works yet.

**Comment by rarkins** [comment]
It requires this version to propagate: https://github.com/renovatebot/renovate/releases/tag/26.18.2

**Comment by viceice** [comment]
@UziTech fix is now released to gitlab runner
