### ISSUE TITLE
Author identity unknown

### ISSUE THREAD

**Issue by hpschry** [renovatebot/renovate#11578]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of Renovate you run.

26.19.0

### Describe the bug

getting this error, even with gitAuthor specified (which btw. not necessary in the past) - this seems to be similar to #11554: 
```
message": "Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <renovate-bot@xxx.xx>) not allowed\n",
18:17:40           "stack": "Error: Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <renovate-bot@xxx.xx>) not allowed\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
```

### Relevant debug logs

<details><summary>Logs</summary>

Hope this section is sufficient, let me know, if you need more (it is slightly redacted)
```
"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","packageFile":"sample-chart/Chart.yaml","depName":"ing-data-transfer","msg":"Found match at index 4589","time":"2021-09-03T16:17:40.186Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","packageFile":"sample-chart/Chart.yaml","depName":"ing-data-transfer","msg":"Contents updated","time":"2021-09-03T16:17:40.187Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","msg":"helmv3.updateArtifacts(sample-chart/Chart.yaml)","time":"2021-09-03T16:17:40.188Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","msg":"No Chart.lock found","time":"2021-09-03T16:17:40.188Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","msg":"Updated 1 package files","time":"2021-09-03T16:17:40.188Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","msg":"No updated lock files in branch","time":"2021-09-03T16:17:40.190Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","msg":"1 file(s) to commit","time":"2021-09-03T16:17:40.190Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","msg":"Committing files to branch renovate/master-ice-helm-charts","time":"2021-09-03T16:17:40.191Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","gitAuthorEmail":"renovate-bot@xxxx.xxx","msg":"Setting git author email","time":"2021-09-03T16:17:40.191Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","err":{"task":{"commands":["commit","-m","DEVOPS-681 fix: Update Helm release ing-data-transfer to v1.18.0","--no-verify"],"format":"utf-8"},"message":"Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <renovate-bot@xxxx.xxx>) not allowed\n","stack":"Error: Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <renovate-bot@xxxx.xxx>) not allowed\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"},"msg":"Unknown error committing files","time":"2021-09-03T16:17:40.303Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":40,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","branch":"renovate/master-ice-helm-charts","err":{"task":{"commands":["commit","-m","DEVOPS-681 fix: Update Helm release ing-data-transfer to v1.18.0","--no-verify"],"format":"utf-8"},"message":"Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <renovate-bot@xxxx.xxx>) not allowed\n","stack":"Error: Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <renovate-bot@xxxx.xxx>) not allowed\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"},"msg":"Error updating branch","time":"2021-09-03T16:17:40.303Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","msg":"Closing Dependency Dashboard","time":"2021-09-03T16:17:40.304Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","msg":"ensureIssueClosing(Dependency Dashboard)","time":"2021-09-03T16:17:40.304Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","msg":"Removing any stale branches","time":"2021-09-03T16:17:40.304Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","msg":"config.repoIsOnboarded=true","time":"2021-09-03T16:17:40.304Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","msg":"No renovate branches found","time":"2021-09-03T16:17:40.304Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","msg":"ensureIssueClosing(Action Required: Fix Renovate Configuration)","time":"2021-09-03T16:17:40.305Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","splits":{"init":998,"extract":1028,"lookup":1271,"update":320},"total":3633,"msg":"Repository timing splits (milliseconds)","time":"2021-09-03T16:17:40.320Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","hostStats":{"auto-test-w002.vm.xxxx.xxx":{"requestCount":1,"requestAvgMs":36,"queueAvgMs":0},"bitbucket.xxxx.xxx":{"requestCount":3,"requestAvgMs":97,"queueAvgMs":0}},"totalRequests":4,"msg":"http statistics","time":"2021-09-03T16:17:40.321Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":30,"logContext":"GbNLXET1Q","repository":"DEV/renovate-sample","durationMs":3633,"msg":"Repository finished","time":"2021-09-03T16:17:40.321Z","v":0}
{"name":"renovate","hostname":"18c0c1e12d44","pid":7,"level":20,"logContext":"GbNLXET1Q","msg":"Renovate exiting","time":"2021-09-03T16:17:40.321Z","v":0}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by hpschry** [comment]
Provided logs, s. above.

**Comment by viceice** [comment]
Looks like the platform didn't extract a username. 

Are you configuring any gitAuthor?

**Comment by bobvandevijver** [comment]
I see the same issue on a self hosted Gitlab instance, and it looks like it is caused by https://github.com/renovatebot/renovate/pull/11536.

**Comment by hpschry** [comment]
> Looks like the platform didn't extract a username.
> 
> Are you configuring any gitAuthor?

I was, now I removed the gitAuthor again and it seems that the repo can be processed again.
