### ISSUE TITLE
Some Renovate tests on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by olegkrivtsov** [renovatebot/renovate#11612]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Cloned the latest available commit 2a09db0f23fd7b6d792ad3db168b3b260edede9e

### Describe the bug

I forked/cloned the latest version of Renovate and installed it on my Ubuntu 18.04 as adviced here: https://github.com/renovatebot/renovate/blob/main/docs/development/local-development.md

I ran the following commands:

yarn install
yarn build
yarn test

Some tests failed (see the logs attached). Please advice what could be wrong.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```
[log.txt](https://github.com/renovatebot/renovate/files/7118992/log.txt)

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
Please past relevant logs to the issue template instead of attachments

**Comment by olegkrivtsov** [comment]
Hi @viceice I'm sorry, but GitHub doesn't allow me to use long issue templates (the log file is too long). I've attached the TXT file, it is safe, I guess.

**Comment by viceice** [comment]
Please trim and past the relevant lines only to the issue. We don't have the time to scan huge logs.

So simply past only the error lines and some context lines.

**Comment by olegkrivtsov** [comment]
No problem @viceice please find the relevant fragments below:

1.

```
PASS lib/manager/gradle-wrapper/artifacts-real.spec.ts (119.633 s, 199 MB heap size)
FAIL lib/util/git/index.spec.ts (191 MB heap size)
  ● util/git/index › checkoutBranch(branchName) › sets the base branch as master

    error: unknown option `show-current'
    usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
       or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
       or: git branch [<options>] [-r] (-d | -D) <branch-name>...
       or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
       or: git branch [<options>] (-c | -C) [<old-branch>] <new-branch>
       or: git branch [<options>] [-r | -a] [--points-at]
       or: git branch [<options>] [-r | -a] [--format]

    Generic options
        -v, --verbose         show hash and subject, give twice for upstream branch
        -q, --quiet           suppress informational messages
        -t, --track           set up tracking mode (see git-pull(1))
        -u, --set-upstream-to <upstream>
                              change the upstream info
        --unset-upstream      Unset the upstream info
        --color[=<when>]      use colored output
        -r, --remotes         act on remote-tracking branches
        --contains <commit>   print only branches that contain the commit
        --no-contains <commit>
                              print only branches that don't contain the commit
        --abbrev[=<n>]        use <n> digits to display SHA-1s

    Specific git-branch actions:
        -a, --all             list both remote-tracking and local branches
        -d, --delete          delete fully merged branch
        -D                    delete branch (even if not merged)
        -m, --move            move/rename a branch and its reflog
        -M                    move/rename a branch, even if target exists
        -c, --copy            copy a branch and its reflog
        -C                    copy a branch, even if target exists
        --list                list branch names
        -l, --create-reflog   create the branch's reflog
        --edit-description    edit the description for the branch
        -f, --force           force creation, move/rename, deletion
        --merged <commit>     print only branches that are merged
        --no-merged <commit>  print only branches that are not merged
        --column[=<style>]    list branches in columns
        --sort <key>          field name to sort on
        --points-at <object>  print only branches of the object
        -i, --ignore-case     sorting and filtering are case insensitive
        --format <format>     format to use for the output

      at Object.action (node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)
      at PluginStore.exec (node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)
      at node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40
      at GitExecutorChain.handleTaskData (node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)
      at GitExecutorChain.<anonymous> (node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)
      at fulfilled (node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)
```

2.

```
util/git/index › checkoutBranch(branchName) › sets the base branch as master

    TypeError: Cannot read property 'cleanup' of undefined

      86 |
      87 |   afterEach(async () => {
    > 88 |     await tmpDir.cleanup();
         |                  ^
      89 |     await origin.cleanup();
      90 |     jest.restoreAllMocks();
      91 |   });

      at Object.<anonymous> (lib/util/git/index.spec.ts:88:18)
```

**Comment by viceice** [comment]
You need a newer git, see our local development docs.
