### ISSUE TITLE
Unknown dependencies

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [renovatebot/renovate#11702]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

All dependencies are unknown and there is a warning:

```
WARN: Error updating branch
```

https://github.com/JavierSegoviaCordoba/massive-catalogs/issues/227

Technically, there are only two catalogs inside `gradle` folder, so I don't know why those libraries are appearing there.

### Relevant debug logs

<summary>

<details>

```

WARN: Error updating branch(branch="renovate/all")
{
  "err": {
    "task": {
      "commands": [
        "push",
        "origin",
        "renovate/all:renovate/all",
        "--force",
        "-u",
        "--no-verify",
        "--verbose",
        "--porcelain"
      ],
      "format": "utf-8"
    },
    "message": "Pushing to https://github.com/JavierSegoviaCordoba/massive-catalogs.git\nremote: Permission to JavierSegoviaCordoba/massive-catalogs.git denied to renovate[bot].\nfatal: unable to access 'https://github.com/JavierSegoviaCordoba/massive-catalogs.git/': The requested URL returned error: 403\n",
    "stack": "Error: Pushing to https://github.com/JavierSegoviaCordoba/massive-catalogs.git\nremote: Permission to JavierSegoviaCordoba/massive-catalogs.git denied to renovate[bot].\nfatal: unable to access 'https://github.com/JavierSegoviaCordoba/massive-catalogs.git/': The requested URL returned error: 403\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
WARN: Error updating branch(branch="renovate/major-all")
{
  "err": {
    "task": {
      "commands": [
        "push",
        "origin",
        "renovate/major-all:renovate/major-all",
        "--force",
        "-u",
        "--no-verify",
        "--verbose",
        "--porcelain"
      ],
      "format": "utf-8"
    },
    "message": "Pushing to https://github.com/JavierSegoviaCordoba/massive-catalogs.git\nremote: Permission to JavierSegoviaCordoba/massive-catalogs.git denied to renovate[bot].\nfatal: unable to access 'https://github.com/JavierSegoviaCordoba/massive-catalogs.git/': The requested URL returned error: 403\n",
    "stack": "Error: Pushing to https://github.com/JavierSegoviaCordoba/massive-catalogs.git\nremote: Permission to JavierSegoviaCordoba/massive-catalogs.git denied to renovate[bot].\nfatal: unable to access 'https://github.com/JavierSegoviaCordoba/massive-catalogs.git/': The requested URL returned error: 403\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
WARN: Could not ensure issue
{
  "err": {
    "message": "integration-unauthorized",
    "stack": "Error: integration-unauthorized\n    at handleGotError (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:60:15)\n    at GithubHttp.request (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:161:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async GithubHttp.requestJson (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/index.js:176:21)\n    at async Proxy.ensureIssue (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/index.js:924:17)\n    at async ensureDependencyDashboard (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/dependency-dashboard.js:285:9)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:81:13)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:400:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:644:5"
  }
}

```
</details>

</summary>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by JavierSegoviaCordoba** [comment]
For some reason it has no permissions to push, but the repo is enabled in the renovate github app.

**Comment by rarkins** [comment]
Could you elaborate on "All dependencies are unknown"? Do you mean that every single dependency in the log is not found in https://github.com/renovate-tests/massive-catalogs/blob/main/gradle/libs.versions.toml or other similar files?

**Comment by rarkins** [comment]
These stats seem extremely high when I run on this repo in my fork:

```
DEBUG: http statistics (repository=renovate-tests/massive-catalogs)
       "hostStats": {
         "api.github.com": {"requestCount": 378, "requestAvgMs": 290, "queueAvgMs": 0},
         "dl.google.com": {"requestCount": 498, "requestAvgMs": 97, "queueAvgMs": 0},
         "maven.pkg.jetbrains.space": {
           "requestCount": 239,
           "requestAvgMs": 703,
           "queueAvgMs": 0
         },
         "repo.maven.apache.org": {
           "requestCount": 16676,
           "requestAvgMs": 108,
           "queueAvgMs": 0
         },
         "services.gradle.org": {
           "requestCount": 1,
           "requestAvgMs": 175,
           "queueAvgMs": 1
         }
       },
       "totalRequests": 17792
```

@zharinov can you take a look if the new catalogs support is somehow wrong?

**Comment by JavierSegoviaCordoba** [comment]
Not sure if all, but probably because I have ktor in the version 1.6.3 in libs.versions.toml and in the dashboard I was getting a message to update to 1.6.3 so probably all those dependencies are transitive or something so.

**Comment by JavierSegoviaCordoba** [comment]
I found the problem, I have a disabled module which have a toml file inside, but it is not in the gradle folder, so I think renovate is looking for all toml files in the project, not only inside Gradle folder.

I totally forgot that module, it was disabled for months.

**Comment by rarkins** [comment]
Here is the current `fileMatch`: https://github.com/renovatebot/renovate/blob/e108537964a1ec1b1b981248074feb879861bb2c/lib/manager/gradle/index.ts#L32-L37

Would you change anything about that? e.g. look only directly inside `gradle/` folder instead of within any subdirectory?

**Comment by JavierSegoviaCordoba** [comment]
Up to you, I think allowing add toml files to any folder is good, because Gradle allow that (like it is right now in renovate), but it should be documented as well.

**Comment by rarkins** [comment]
OK, in that case an update to the docs would be appreciated

**Comment by viceice** [comment]
Yes, we shouldn't widen these file matches, as other managers are using toml files too and we get too many false positives.

But a user can always override the `fileMatch` via config. 🙃

**Comment by JavierSegoviaCordoba** [comment]
The global match is `*.versions.toml`, do you think that pattern is used in other managers?

**Comment by viceice** [comment]
no, but we have at lease two other matches 😏 So we shouln't use `*.toml` as match for any manager by default.

https://github.com/renovatebot/renovate/blob/13bbc5d6a2847dd147ac6f8a3f79c44adcc75643/lib/manager/cargo/index.ts#L13
https://github.com/renovatebot/renovate/blob/4200ed96ec72ca2cb7d33d0bec9b33e3e40cf6e0/lib/manager/poetry/index.ts#L10

**Comment by JavierSegoviaCordoba** [comment]
*.toml is not there, there is a gradle/*.toml, but I think that is fine too.

**Comment by rarkins** [comment]
I think it will be any toml file at any depth inside a gradle folder?

**Comment by JavierSegoviaCordoba** [comment]
I think so too

**Comment by JavierSegoviaCordoba** [comment]
Fixed https://github.com/renovatebot/renovate/pull/11717
