### ISSUE TITLE
Artifact Update Problem with Yarn v3/yarn.lock

### ISSUE THREAD

**Issue by viktoria-schwarz** [renovatebot/renovate#11724]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

We're running Renovate on our [public repository](https://github.com/marigold-ui/marigold/blob/main/.github/renovate.json) and lately encounter the Artifact Update Problem, so auto-merge fails. 

Renovate comments in the failing PR that the concerning file is `yarn.lock` but doesn't specify any details. Don't know where to start debugging, help needed!

Thank you.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: rawExec err(branch="renovate/typescript-eslint-monorepo")
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/marigold-ui/marigold\":\"/mnt/renovate/gh/marigold-ui/marigold\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_ENABLE_IMMUTABLE_INSTALLS -e YARN_HTTP_TIMEOUT -e YARN_GLOBAL_FOLDER -e YARN_ENABLE_GLOBAL_CACHE -w \"/mnt/renovate/gh/marigold-ui/marigold\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install --mode=update-lockfile\"",
    "stdout": "\n> yarn@1.22.11 preinstall /home/ubuntu/.npm-global/lib/node_modules/yarn\n> :; (node ./preinstall.js > /dev/null 2>&1 || true)\n\n/home/ubuntu/.npm-global/bin/yarn -> /home/ubuntu/.npm-global/lib/node_modules/yarn/bin/yarn.js\n/home/ubuntu/.npm-global/bin/yarnpkg -> /home/ubuntu/.npm-global/lib/node_modules/yarn/bin/yarn.js\n+ yarn@1.22.11\nadded 1 package in 2.585s\nUnknown Syntax Error: Invalid option name (\"--mode=update-lockfile\").\n\n$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--skip-builds]\n",
    "stderr": "",
    "message": "Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/marigold-ui/marigold\":\"/mnt/renovate/gh/marigold-ui/marigold\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_ENABLE_IMMUTABLE_INSTALLS -e YARN_HTTP_TIMEOUT -e YARN_GLOBAL_FOLDER -e YARN_ENABLE_GLOBAL_CACHE -w \"/mnt/renovate/gh/marigold-ui/marigold\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install --mode=update-lockfile\"\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/marigold-ui/marigold\":\"/mnt/renovate/gh/marigold-ui/marigold\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_ENABLE_IMMUTABLE_INSTALLS -e YARN_HTTP_TIMEOUT -e YARN_GLOBAL_FOLDER -e YARN_ENABLE_GLOBAL_CACHE -w \"/mnt/renovate/gh/marigold-ui/marigold\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install --mode=update-lockfile\"\n\n    at ChildProcess.exithandler (child_process.js:390:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  }
}
DEBUG: lock file error(branch="renovate/typescript-eslint-monorepo")
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/marigold-ui/marigold\":\"/mnt/renovate/gh/marigold-ui/marigold\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_ENABLE_IMMUTABLE_INSTALLS -e YARN_HTTP_TIMEOUT -e YARN_GLOBAL_FOLDER -e YARN_ENABLE_GLOBAL_CACHE -w \"/mnt/renovate/gh/marigold-ui/marigold\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install --mode=update-lockfile\"",
    "stdout": "\n> yarn@1.22.11 preinstall /home/ubuntu/.npm-global/lib/node_modules/yarn\n> :; (node ./preinstall.js > /dev/null 2>&1 || true)\n\n/home/ubuntu/.npm-global/bin/yarn -> /home/ubuntu/.npm-global/lib/node_modules/yarn/bin/yarn.js\n/home/ubuntu/.npm-global/bin/yarnpkg -> /home/ubuntu/.npm-global/lib/node_modules/yarn/bin/yarn.js\n+ yarn@1.22.11\nadded 1 package in 2.585s\nUnknown Syntax Error: Invalid option name (\"--mode=update-lockfile\").\n\n$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--skip-builds]\n",
    "stderr": "",
    "message": "Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/marigold-ui/marigold\":\"/mnt/renovate/gh/marigold-ui/marigold\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_ENABLE_IMMUTABLE_INSTALLS -e YARN_HTTP_TIMEOUT -e YARN_GLOBAL_FOLDER -e YARN_ENABLE_GLOBAL_CACHE -w \"/mnt/renovate/gh/marigold-ui/marigold\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install --mode=update-lockfile\"\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/marigold-ui/marigold\":\"/mnt/renovate/gh/marigold-ui/marigold\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_ENABLE_IMMUTABLE_INSTALLS -e YARN_HTTP_TIMEOUT -e YARN_GLOBAL_FOLDER -e YARN_ENABLE_GLOBAL_CACHE -w \"/mnt/renovate/gh/marigold-ui/marigold\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install --mode=update-lockfile\"\n\n    at ChildProcess.exithandler (child_process.js:390:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  },
  "type": "yarn"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by viceice** [comment]
you need to update your local yarn to v3 release, you are using a prerelease which is lacking support.

You are using 3.0.0-rc.2

ref #11012
