### ISSUE TITLE
Renovate fails to clone a Bitbucket Server repository since the `--depth=10` option was removed

### ISSUE THREAD

**Issue by ericcitaire** [renovatebot/renovate#11759]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.5.0

### Describe the bug

Removing `--depth=10` option in https://github.com/renovatebot/renovate/commit/d6d4124b11ee66f1db019d0359cc47606f8d946d makes Renovate fail with an error.

### Relevant debug logs

<details><summary>Logs</summary>

```
 WARN: Host error (repository=prj/repo)
       "hostType": "git",
       "lookupName": undefined,
       "err": {
         "task": {
           "commands": [
             "clone",
             "--filter=blob:none",
             "https://****:**redacted**@bitbucket.acme.com/scm/prj/repo.git",
             "."
           ],
           "format": "utf-8"
         },
         "message": "Cloning into '.'...\nwarning: filtering not recognized by server, ignoring\nerror: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.\nerror: 6653 bytes of body are still expected\nfetch-pack: unexpected disconnect while reading sideband packet\nfatal: early EOF\nfatal: fetch-pack: invalid index-pack output\n",
         "stack": "Error: Cloning into '.'...\nwarning: filtering not recognized by server, ignoring\nerror: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.\nerror: 6653 bytes of body are still expected\nfetch-pack: unexpected disconnect while reading sideband packet\nfatal: early EOF\nfatal: fetch-pack: invalid index-pack output\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
@rarkins maybe we simply add a global option for git clone options, wich default to `['--filter=blob:none']` ?

 @ericcitaire Which version of BitBucket Server are you using?

**Comment by ericcitaire** [comment]
We are using BitBucket Server v7.6.1

**Comment by viceice** [comment]
@rarkins should we  add a config option or disable blobless via experimental env ?

**Comment by rarkins** [comment]
@viceice I'd be curious to know if Bitbucket Server 7.6.9 supports the necessary git capabilities. If so then I'm not interested in adding a workaround to Renovate

**Comment by viceice** [comment]
```sh
> docker run --rm -it atlassian/bitbucket:7.6.9 git --version
Unable to find image 'atlassian/bitbucket:7.6.9' locally
7.6.9: Pulling from atlassian/bitbucket
35807b77a593: Already exists
93d71b8f96bb: Pull complete
eec3d23cb0f5: Pull complete
957042ad36f5: Pull complete
a7f0fd04d1bb: Pull complete
904d540fc13a: Pull complete
055d9e17f7a1: Pull complete
587c4c7ea69a: Pull complete
373ce4a8d870: Pull complete
8ce1029f718f: Pull complete
fc7f924abae9: Pull complete
Digest: sha256:e13060504e1e664c3f9a53afeb5c836184826cae90434b423a3edfcb329e8631
Status: Downloaded newer image for atlassian/bitbucket:7.6.9
git version 2.28.1

**Comment by viceice** [comment]
```sh
docker run --rm -it atlassian/bitbucket:7.6.1 git --version
Unable to find image 'atlassian/bitbucket:7.6.1' locally
7.6.1: Pulling from atlassian/bitbucket
35807b77a593: Already exists
93d71b8f96bb: Already exists
eec3d23cb0f5: Already exists
f037d8b75c5e: Pull complete
4401cb9abbcf: Pull complete
904d540fc13a: Pull complete
55c8c176f535: Pull complete
11b92a580b34: Pull complete
58416abc7ce5: Pull complete
8ce1029f718f: Pull complete
9d5d03659bc7: Pull complete
Digest: sha256:bd711c385c26f83f6e4ee42fb35b81cc50541194c802dbc0ad6b53176022440a
Status: Downloaded newer image for atlassian/bitbucket:7.6.1
git version 2.28.1
```

**Comment by viceice** [comment]
I think you need at least v2.29 on server, because this needs git wire protocoll v2

https://github.blog/2020-10-19-git-2-29-released/

**Comment by viceice** [comment]
git v2.29 needs bitbucker server v7.7 or later 😕 

https://jira.atlassian.com/browse/BSERV-12634

**Comment by rarkins** [comment]
OK in that case we should support falling back to a full clone. Let's make it a first class option `gitCloneOptions` and default it to `['--filter=blob:none']`

**Comment by ericcitaire** [comment]
I was able too use Renovate 28 with BitBucket v7.6.1 with this workaround :
```
git config --global pack.depth 10
```

**Comment by ericcitaire** [comment]
> @ericcitaire is that an option you run on Bitbucket itself, or prior to executing Renovate?

@rarkins : I run it client-side, just before executing Renovate.
