### ISSUE TITLE
extractVersionTemplate prevents github-releases digests from working

### ISSUE THREAD

**Issue by languitar** [renovatebot/renovate#11809]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.14.0

### Describe the bug

The `github-releases` datasource cannot handle providing digests in case `extractVersionTemplate` is used to change the name of the release version in a regex manager. The code trying to find out the file with the current digest fails, because it tries to access the release after `extractVersionTemplate` was applied.

https://github.com/languitar/renovate-extract-version-issue demonstrates the problem. Trying to run renovate on this repo results in the error shown below. The datasource should have requested `https://api.github.com/repos/jgraph/drawio-desktop/releases/tags/v14.9.6`, but due to the extract configuration, the `v` is missing in the tag name.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Matched 1 file(s) for manager regex: test (repository=languitar/renovate-extract-version-issue)
DEBUG: Found regex package files (repository=languitar/renovate-extract-version-issue)
DEBUG: Found 1 package file(s) (repository=languitar/renovate-extract-version-issue)
 INFO: Dependency extraction complete (repository=languitar/renovate-extract-version-issue)
       "baseBranch": "main",
       "stats": {
         "managers": {"regex": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }
DEBUG: getDigest (repository=languitar/renovate-extract-version-issue)
       "repo": "jgraph/drawio-desktop",
       "currentValue": "14.9.6",
       "currentDigest": "bf04065bcd9df7c07d35c487720e2389dab7e2c7b216c189db8687aac70fbe05",
       "registryUrl": "https://github.com",
       "newValue": "15.2.7"
DEBUG: GitHub 404 (repository=languitar/renovate-extract-version-issue)
       "url": "https://api.github.com/repos/jgraph/drawio-desktop/releases/tags/14.9.6"
ERROR: Repository has unknown error (repository=languitar/renovate-extract-version-issue)
       "err": {
         "name": "HTTPError",
         "timings": {
           "start": 1632080762427,
           "socket": 1632080762427,
           "lookup": 1632080762427,
           "connect": 1632080762463,
           "secureConnect": 1632080762499,
           "upload": 1632080762499,
           "response": 1632080762664,
           "end": 1632080762665,
           "phases": {
             "wait": 0,
             "dns": 0,
             "tcp": 36,
             "tls": 36,
             "request": 0,
             "firstByte": 165,
             "download": 1,
             "total": 238
           }
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/home/languitar/src/renovate-runner/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/27.14.0 (https://github.com/renovatebot/renovate)",
             "accept": "application/vnd.github.v3+json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://api.github.com/repos/jgraph/drawio-desktop/releases/tags/14.9.6",
           "hostType": "github-releases",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 404,
           "statusMessage": "Not Found",
           "body": {
             "message": "Not Found",
             "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name"
           },
           "headers": {
             "server": "GitHub.com",
             "date": "Sun, 19 Sep 2021 19:46:02 GMT",
             "content-type": "application/json; charset=utf-8",
             "transfer-encoding": "chunked",
             "x-oauth-scopes": "delete:packages, repo, workflow, write:discussion, write:packages",
             "x-accepted-oauth-scopes": "repo",
             "github-authentication-token-expiration": "2021-09-26 19:45:41 UTC",
             "x-github-media-type": "github.v3; format=json",
             "x-ratelimit-limit": "5000",
             "x-ratelimit-remaining": "4994",
             "x-ratelimit-reset": "1632084355",
             "x-ratelimit-used": "6",
             "x-ratelimit-resource": "core",
             "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
             "access-control-allow-origin": "*",
             "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
             "x-frame-options": "deny",
             "x-content-type-options": "nosniff",
             "x-xss-protection": "0",
             "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
             "content-security-policy": "default-src 'none'",
             "vary": "Accept-Encoding, Accept, X-Requested-With",
             "content-encoding": "gzip",
             "x-github-request-id": "D8E0:B189:39844:4E3ED:6147937A",
             "connection": "close"
           },
           "httpVersion": "1.1"
         }
       }
DEBUG: Repository timing splits (milliseconds) (repository=languitar/renovate-extract-version-issue)
       "splits": {"init": 2856, "extract": 258},
       "total": 4495
DEBUG: http statistics (repository=languitar/renovate-extract-version-issue)
       "urls": {
         "https://api.github.com/graphql (POST)": 3,
         "https://api.github.com/repos/jgraph/drawio-desktop/releases (GET)": 1,
         "https://api.github.com/repos/languitar/renovate-extract-version-issue/contents/renovate.json (GET)": 1
       },
       "hostStats": {"api.github.com": {"requestCount": 5, "requestAvgMs": 428, "queueAvgMs": 0}},
       "totalRequests": 5
 INFO: Repository finished (repository=languitar/renovate-extract-version-issue)
       "durationMs": 4495
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "02J6dLbPg",
           "repository": "languitar/renovate-extract-version-issue",
           "err": {
             "name": "HTTPError",
             "timings": {
               "start": 1632080762427,
               "socket": 1632080762427,
               "lookup": 1632080762427,
               "connect": 1632080762463,
               "secureConnect": 1632080762499,
               "upload": 1632080762499,
               "response": 1632080762664,
               "end": 1632080762665,
               "phases": {
                 "wait": 0,
                 "dns": 0,
                 "tcp": 36,
                 "tls": 36,
                 "request": 0,
                 "firstByte": 165,
                 "download": 1,
                 "total": 238
               }
             },
             "message": "Response code 404 (Not Found)",
             "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/home/languitar/src/renovate-runner/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
             "options": {
               "headers": {
                 "user-agent": "RenovateBot/27.14.0 (https://github.com/renovatebot/renovate)",
                 "accept": "application/vnd.github.v3+json",
                 "authorization": "***********",
                 "accept-encoding": "gzip, deflate, br"
               },
               "url": "https://api.github.com/repos/jgraph/drawio-desktop/releases/tags/14.9.6",
               "hostType": "github-releases",
               "username": "",
               "password": "",
               "method": "GET",
               "http2": false
             },
             "response": {
               "statusCode": 404,
               "statusMessage": "Not Found",
               "body": {
                 "message": "Not Found",
                 "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name"
               },
               "headers": {
                 "server": "GitHub.com",
                 "date": "Sun, 19 Sep 2021 19:46:02 GMT",
                 "content-type": "application/json; charset=utf-8",
                 "transfer-encoding": "chunked",
                 "x-oauth-scopes": "delete:packages, repo, workflow, write:discussion, write:packages",
                 "x-accepted-oauth-scopes": "repo",
                 "github-authentication-token-expiration": "2021-09-26 19:45:41 UTC",
                 "x-github-media-type": "github.v3; format=json",
                 "x-ratelimit-limit": "5000",
                 "x-ratelimit-remaining": "4994",
                 "x-ratelimit-reset": "1632084355",
                 "x-ratelimit-used": "6",
                 "x-ratelimit-resource": "core",
                 "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
                 "access-control-allow-origin": "*",
                 "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
                 "x-frame-options": "deny",
                 "x-content-type-options": "nosniff",
                 "x-xss-protection": "0",
                 "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
                 "content-security-policy": "default-src 'none'",
                 "vary": "Accept-Encoding, Accept, X-Requested-With",
                 "content-encoding": "gzip",
                 "x-github-request-id": "D8E0:B189:39844:4E3ED:6147937A",
                 "connection": "close"
               },
               "httpVersion": "1.1"
             }
           },
           "msg": "Repository has unknown error"
         }
       ]
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by malmor** [comment]
Hey, we are facing this issue aswell.

Versions:
- Renovate: 28.21.2 (latest) self-hosted
- Platform: GitLab self-hosted

Same use-case: we are removing a `v` using extractVersion, which results in the github-releases datasource calling `https://api.github.com/repos/prometheus/node_exporter/releases/tags/1.1.2` instead of `https://api.github.com/repos/prometheus/node_exporter/releases/tags/v1.1.2`.

Would be great to see this fixed - it is really annoying and time-consuming to manually update the digests (because our pipeline fails if the digests are not correct). ✌

**Comment by viceice** [comment]
I don't think this is easily fixable.

@rarkins Maybe we need to return an `originalVersion` value from datasource after extraction and pass through, so getDigest can use that value?

**Comment by rarkins** [comment]
Maybe. I think it will need someone with this problem determined to fix it

**Comment by Gabriel-Ladzaretti** [comment]
Here is a workaround using regex manager -

```diff
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["^test$"],
      "matchStrings": [
-        "version=(?<currentValue>.*?)\n",
-        "checksum=(?<currentDigest>.*?)\n"
+        "version=(?<currentValue>.*?)\nchecksum=(?<currentDigest>.*?)",
      ],
      "matchStringsStrategy": "combination",
      "depNameTemplate": "jgraph/drawio-desktop",
      "datasourceTemplate": "github-releases",
-      "extractVersionTemplate": "^v(?<version>.*)$"
+      "currentValueTemplate": "v{{{currentValue}}}",
+      "autoReplaceStringTemplate": "version={{{replace 'v' '' newVersion}}}\nchecksum={{{newDigest}}}"
    }
  ]
}
```
- https://github.com/ladzaretti/renovate-extract-version-issue/pull/1

No sure if this closes this issue as I was not using `extractVersionTemplate` in this workaround.

ill let the maintainer decide as it might be a configuration issue after all.

@rarkins @viceice 
wdyt?

**Comment by malmor** [comment]
Thanks for this workaround @Gabriel-Ladzaretti - I will definitely give it a try in our setup 👍

**Comment by malmor** [comment]
Hey, I can confirm that @Gabriel-Ladzaretti's suggestion is working like a charm - Renovate updates both the version and the checksum and our pipelines pass without any additional manual work required.

Thanks a lot for this 🥇
