### ISSUE TITLE
Improve branch name massaging

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#12097]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Configuring `"branchPrefix": "[Dependency-Update]"` results in an invalid branch name. Per https://stackoverflow.com/a/67151923/3005034 we need to massage out all these characters: `: ? [ \ ^ ~` (not sure about `]` but we can add that to be safe).

### Relevant debug logs

<details><summary>Logs</summary>

```
{
  "level": 20,
  "branch": "[Dependency-Update]pyzabbix-1.x",
  "err": {
    "task": {
      "commands": [
        "checkout",
        "-B",
        "[Dependency-Update]pyzabbix-1.x",
        "origin/master"
      ],
      "format": "utf-8"
    },
    "message": "fatal: '[Dependency-Update]pyzabbix-1.x' is not a valid branch name.\n",
    "stack": "Error: fatal: '[Dependency-Update]pyzabbix-1.x' is not a valid branch name.\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  },
  "msg": "Unknown error committing files",
  "time": "2021-10-10T13:46:19.286Z"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rangelfinal** [comment]
There's a related issue for the `[` character on clean-git-ref, but that project seems to be abandoned: https://github.com/TheSavior/clean-git-ref/issues/33  
Would a `.replace(/[\[\]\?\:\\\^\~]/g, '')` be enough here?

**Comment by RahulGautamSingh** [comment]
I have already worked on the specified file and function while fixing #12025 , I can update this function and close this issue with #12025.
