### ISSUE TITLE
Crash with RequestError: Timeout awaiting 'request' for 60000ms 

### ISSUE THREAD

**Issue by sclorng** [renovatebot/renovate#12115]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.31.10

### Describe the bug

Renovate crash when a timeout occurs. In the logfile, I can't see any error, so I guess the exception is not trapped and stop the process and it is hard to know what call actually timeouts.

### Relevant debug logs

<details><summary>Logs</summary>

```
INFO: Repository started (repository=capture-process)
       "renovateVersion": "27.31.10"
 INFO: Dependency extraction complete (repository=capture-process)
       "baseBranch": "develop",
       "stats": {
         "managers": {
           "dockerfile": {"fileCount": 1, "depCount": 1},
           "gitlabci-include": {"fileCount": 1, "depCount": 2},
           "maven": {"fileCount": 1, "depCount": 17}
         },
         "total": {"fileCount": 3, "depCount": 20}
       }

/usr/src/app/node_modules/got/dist/source/core/index.js:956
            error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);
                                                                ^
RequestError: Timeout awaiting 'request' for 60000ms
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:956:65)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.emit (domain.js:475:12)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (/usr/src/app/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:559:11)
    at processTimers (internal/timers.js:500:7)
```

Last line of file logs

```
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":30,"logContext":"UvjvDILkT","repository":"capture-process","baseBranch":"develop","stats":{"managers":{"dockerfile":{"fileCount":1,"depCount":1},"gitlabci-include":{"fileCount":1,"depCount":2},"maven":{"fileCount":1,"depCount":17}},"total":{"fileCount":3,"depCount":20}},"msg":"Dependency extraction complete","time":"2021-10-11T10:09:36.786Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.springframework.boot:spring-boot-starter-parent in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.817Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.springframework.cloud:spring-cloud-dependencies in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.820Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up com.github.java-json-tools:json-patch in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.822Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up com.company.bos:envelope in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.827Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.829Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 61 new releases for org.springframework.cloud:spring-cloud-dependencies in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.849Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 4 new releases for com.github.java-json-tools:json-patch in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.859Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 139 new releases for org.springframework.boot:spring-boot-starter-parent in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.862Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 77 new releases for org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.868Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://repo.maven.apache.org/maven2/com/company/bos/envelope/maven-metadata.xml","time":"2021-10-11T10:09:36.873Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up com.company.bos:envelope in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:36.873Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.springframework.cloud:spring-cloud-dependencies in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:36.879Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up com.github.java-json-tools:json-patch in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:36.880Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.springframework.boot:spring-boot-starter-parent in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:36.889Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/org/springframework/cloud/spring-cloud-dependencies/maven-metadata.xml","time":"2021-10-11T10:09:36.907Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter-webapp in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.916Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/org/springframework/boot/spring-boot-starter-parent/maven-metadata.xml","time":"2021-10-11T10:09:36.932Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.camunda.bpm.extension:camunda-bpm-assert in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.948Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 19 new releases for com.company.bos:envelope in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:36.952Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 77 new releases for org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter-webapp in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.956Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 4 new releases for org.camunda.bpm.extension:camunda-bpm-assert in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:36.963Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:36.971Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter-webapp in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:36.984Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.camunda.bpm.extension:camunda-bpm-assert in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:37.005Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/org/camunda/bpm/springboot/camunda-bpm-spring-boot-starter-webapp/maven-metadata.xml","time":"2021-10-11T10:09:37.011Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up io.cucumber:cucumber-junit in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.019Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/com/github/java-json-tools/json-patch/maven-metadata.xml","time":"2021-10-11T10:09:37.024Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up io.cucumber:cucumber-spring in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.030Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/org/camunda/bpm/extension/camunda-bpm-assert/maven-metadata.xml","time":"2021-10-11T10:09:37.033Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up com.kjetland:mbknor-jackson-jsonschema_2.13 in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.040Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 85 new releases for io.cucumber:cucumber-junit in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.044Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 85 new releases for io.cucumber:cucumber-spring in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.047Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 5 new releases for com.kjetland:mbknor-jackson-jsonschema_2.13 in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.050Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/org/springframework/boot/spring-boot-starter-parent/2.5.5/spring-boot-starter-parent-2.5.5.pom","time":"2021-10-11T10:09:37.060Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.mapstruct:mapstruct in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.067Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up com.kjetland:mbknor-jackson-jsonschema_2.13 in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:37.069Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 32 new releases for org.mapstruct:mapstruct in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.073Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up io.cucumber:cucumber-spring in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:37.081Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up io.cucumber:cucumber-junit in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:37.081Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/org/camunda/bpm/springboot/camunda-bpm-spring-boot-starter/maven-metadata.xml","time":"2021-10-11T10:09:37.082Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up io.swagger:swagger-codegen-maven-plugin in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.091Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.mapstruct:mapstruct in repository https://gitlab.company/api/v4/groups/110818/-/packages/maven/","time":"2021-10-11T10:09:37.096Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Found 36 new releases for io.swagger:swagger-codegen-maven-plugin in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.101Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/io/cucumber/cucumber-junit/maven-metadata.xml","time":"2021-10-11T10:09:37.116Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.jacoco:jacoco-maven-plugin in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.123Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/io/cucumber/cucumber-spring/maven-metadata.xml","time":"2021-10-11T10:09:37.127Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up com.trivago.rta:cluecumber-report-plugin in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.135Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Content is not found for Maven url: https://gitlab.company/api/v4/groups/110818/-/packages/maven/org/mapstruct/mapstruct/maven-metadata.xml","time":"2021-10-11T10:09:37.135Z","v":0}
{"name":"renovate","hostname":"runner-sfivd7tg-project-67591-concurrent-0pshd5","pid":11,"level":20,"logContext":"UvjvDILkT","repository":"capture-process","msg":"Looking up org.apache.maven.plugins:maven-compiler-plugin in repository https://repo.maven.apache.org/maven2/","time":"2021-10-11T10:09:37.143Z","v":0}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
@zharinov @rarkins it seems again a graphql issue 😟

**Comment by rarkins** [comment]
1. Yes, seems related to the change to github-tags change to GraphQL
2. It doesn't seem unique to github/graphql though, can happen to npmjs too

@zharinov can we catch timeouts and reduce the query size like we do with other GraphQL problems?

**Comment by rarkins** [comment]
Seeing success with page shrinking, the discussion has been here: https://github.com/renovatebot/renovate/discussions/18413#discussioncomment-3930548

@GraemeF can you check the logs/result for your own repo? Please tell me a recent job ID if it's *not* working. You might see 1 or more errors but then it should shrink the graphql page size and recover.

**Comment by GraemeF** [comment]
> @GraemeF can you check the logs/result for your own repo? Please tell me a recent job ID if it's _not_ working. You might see 1 or more errors but then it should shrink the graphql page size and recover.

Yep, that's exactly what's happening, and no failed jobs since yesterday. Thanks so much! 💥
