### ISSUE TITLE
Go modules with old improper semver tags like kubernetes client break renovatebot

### ISSUE THREAD

**Issue by StevenACoffman** [renovatebot/renovate#12137]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Renovatebot is broken when dependencies include Go libraries that switched to correct Semantic versioning scheme for proper Go Modules support as here: kubernetes/client-go@7624422

There is a fairly old v12.0.0 tag: https://github.com/kubernetes/client-go/releases/tag/v12.0.0. Renovate detects the tag as a major version bump. I assume the tag is the cause but the authors have said they will never remove it.

Please see this minimal reproduction: https://github.com/StevenACoffman/repro/pull/1 

##### Main broken issue I noticed:
Renovatebot is broken when dependencies include Go libraries that switched to correct Semantic versioning scheme for proper Go Modules support

##### reproduced error:

```
Command failed: docker run --rm --name=renovate_go --label=renovate_child -v "/mnt/renovate/gh/StevenACoffman/repro":"/mnt/renovate/gh/StevenACoffman/repro" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w "/mnt/renovate/gh/StevenACoffman/repro" docker.io/renovate/go:1.17.2 bash -l -c "git config --global url.\"https://**redacted**@github.com/\".insteadOf \"https://github.com/\" && go get -d ./... && go mod tidy && go mod tidy"
go: k8s.io/client-go/v12@v12.0.0: go.mod has non-.../v12 module path "k8s.io/client-go" (and .../v12/go.mod does not exist) at revision v12.0.0

```

##### Other possibly relevant issues:

+ https://github.com/renovatebot/renovate/issues/4991

+ https://github.com/kubernetes/client-go/issues/670

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "28.0.3"
}
DEBUG: Using localDir: /mnt/renovate/gh/StevenACoffman/repro
DEBUG: Repository cache is valid
DEBUG: initRepo("StevenACoffman/repro")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: StevenACoffman/repro default branch = main
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: Resetting npmrc
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: Checking cached config file name
DEBUG: Existing config file confirmed
DEBUG: Repo is onboarded
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base",
      ":rebaseStalePrs"
    ],
    "baseBranches": [
      "main"
    ],
    "postUpdateOptions": [
      "gomodTidy"
    ],
    "postUpgradeTasks": {
      "commands": [
        "modupdate.sh"
      ],
      "executionMode": "update"
    },
    "groupName": "all dependencies",
    "separateMajorMinor": false,
    "groupSlug": "all",
    "packageRules": [
      {
        "matchPackagePatterns": [
          "*"
        ],
        "matchFiles": [
          "go.mod"
        ],
        "matchPaths": [
          "go.mod"
        ],
        "excludePackagePrefixes": [
          "k8s.io"
        ],
        "excludePackageNames": [
          "k8s.io/client-go"
        ],
        "extends": [
          "schedule:weekly"
        ],
        "groupName": "all dependencies",
        "groupSlug": "all"
      }
    ],
    "lockFileMaintenance": {
      "enabled": true
    },
    "constraints": {
      "go": "1.17"
    }
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base",
      ":rebaseStalePrs"
    ],
    "baseBranches": [
      "main"
    ],
    "postUpdateOptions": [
      "gomodTidy"
    ],
    "postUpgradeTasks": {
      "commands": [
        "modupdate.sh"
      ],
      "executionMode": "update"
    },
    "groupName": "all dependencies",
    "separateMajorMinor": false,
    "groupSlug": "all",
    "packageRules": [
      {
        "matchPackagePatterns": [
          "*"
        ],
        "matchFiles": [
          "go.mod"
        ],
        "matchPaths": [
          "go.mod"
        ],
        "excludePackagePrefixes": [
          "k8s.io"
        ],
        "excludePackageNames": [
          "k8s.io/client-go"
        ],
        "extends": [
          "schedule:weekly"
        ],
        "groupName": "all dependencies",
        "groupSlug": "all"
      }
    ],
    "lockFileMaintenance": {
      "enabled": true
    },
    "constraints": {
      "go": "1.17"
    }
  }
}
DEBUG: Setting hostRules from config
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/__fixtures__/**"
  ]
}
DEBUG: detectSemanticCommits()
DEBUG: No vulnerability alerts found
DEBUG: No vulnerability alerts found
DEBUG: findIssue(Dependency Dashboard)
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
DEBUG: Found issue 2
DEBUG: baseBranches
{
  "baseBranches": [
    "main"
  ]
}
DEBUG: baseBranch: main
DEBUG: extract()
DEBUG: Found cached extract
{
  "baseBranch": "main",
  "baseBranchSha": "1c8950a5100f05bbe247f74306a5081d6317ab33"
}
DEBUG: Deleted cached dep updates
INFO: Dependency extraction complete
{
  "baseBranch": "main",
  "stats": {
    "managers": {
      "gomod": {
        "fileCount": 1,
        "depCount": 2
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 2
    }
  }
}
DEBUG: baseBranch: main
DEBUG: Go lookup source url
{
  "goModule": "k8s.io/apimachinery",
  "goSourceUrl": "https://github.com/kubernetes/apimachinery"
}
DEBUG: Go lookup source url
{
  "goModule": "k8s.io/client-go",
  "goSourceUrl": "https://github.com/kubernetes/client-go"
}
DEBUG: Go lookup source url
{
  "goModule": "k8s.io/client-go",
  "goSourceUrl": "https://github.com/kubernetes/client-go"
}
DEBUG: Package releases lookups complete
{
  "baseBranch": "main"
}
DEBUG: branchifyUpgrades
DEBUG: Using group branchName template
DEBUG: Dependency k8s.io/client-go is part of group all dependencies
DEBUG: 1 flattened updates found: k8s.io/client-go
DEBUG: Returning 1 branch(es)
DEBUG: Fetching changelog: https://github.com/kubernetes/client-go (v0.0.0-00010101000000-000000000000 -> v12.0.0)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "gomod": [
      {
        "packageFile": "go.mod",
        "constraints": {
          "go": "^1.17"
        },
        "deps": [
          {
            "managerData": {
              "lineNumber": 5,
              "multiLine": true
            },
            "depName": "k8s.io/apimachinery",
            "depType": "require",
            "currentValue": "v0.22.2",
            "datasource": "go",
            "depIndex": 0,
            "warnings": [],
            "versioning": "semver",
            "sourceUrl": "https://github.com/kubernetes/apimachinery",
            "currentVersion": "v0.22.2",
            "fixedVersion": "v0.22.2",
            "updates": []
          },
          {
            "managerData": {
              "lineNumber": 6,
              "multiLine": true
            },
            "depName": "k8s.io/client-go",
            "depType": "require",
            "currentValue": "v0.0.0-00010101000000-000000000000",
            "datasource": "go",
            "currentDigest": "000000000000",
            "digestOneAndOnly": true,
            "depIndex": 1,
            "warnings": [],
            "versioning": "semver",
            "sourceUrl": "https://github.com/kubernetes/client-go",
            "currentVersion": "v0.0.0-00010101000000-000000000000",
            "isSingleVersion": true,
            "fixedVersion": "v0.0.0-00010101000000-000000000000",
            "updates": [
              {
                "bucket": "latest",
                "newVersion": "v12.0.0",
                "newValue": "v12.0.0",
                "newMajor": 12,
                "newMinor": 0,
                "updateType": "major",
                "newDigest": "c1ea390cb7f7ca6d6345b4d3bcfd5546028cee20",
                "branchName": "renovate/all"
              }
            ]
          }
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/all
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 1 Pull Requests
DEBUG: currentHourStart=2021-10-12T23:00:00.000+00:00
DEBUG: PR hourly limit remaining: 1
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/all)
DEBUG: findPr(renovate/all, undefined, open)
DEBUG: Found PR #1
DEBUG: Returning from graphql open PR list
DEBUG: 1 PRs are currently open
DEBUG: PR concurrent limit remaining: 19
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 1
}
DEBUG: PullRequests limit = 1
DEBUG: Calculating hourly PRs remaining
DEBUG: currentHourStart=2021-10-12T23:00:00.000+00:00
DEBUG: PR hourly limit remaining: 1
DEBUG: Calculating branchConcurrentLimit (20)
DEBUG: 1 already existing branches found: renovate/all
DEBUG: Branch concurrent limit remaining: 19
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 1
}
DEBUG: Branches limit = 1
DEBUG: Setting current branch to main(branch="renovate/all")
DEBUG: Initializing git repository into /mnt/renovate/gh/StevenACoffman/repro(branch="renovate/all")
DEBUG: git clone completed(branch="renovate/all")
{
  "durationMs": 892
}
DEBUG: latest repository commit(branch="renovate/all")
{
  "latestCommit": {
    "hash": "1c8950a5100f05bbe247f74306a5081d6317ab33",
    "date": "2021-10-12T19:47:02-04:00",
    "message": "add replace and exclude",
    "refs": "HEAD -> main, origin/main, origin/HEAD",
    "body": "Signed-off-by: Steve Coffman <steve@khanacademy.org>\n",
    "author_name": "Steve Coffman",
    "author_email": "steve@khanacademy.org"
  }
}
DEBUG: latest commit(branch="renovate/all")
{
  "branchName": "main",
  "latestCommitDate": "2021-10-12T19:47:02-04:00"
}
DEBUG: branchExists=true(branch="renovate/all")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/all")
DEBUG: PR rebase requested=true(branch="renovate/all")
DEBUG: Checking if PR has been edited(branch="renovate/all")
DEBUG: Found existing branch PR(branch="renovate/all")
DEBUG: Checking schedule(at any time, null)(branch="renovate/all")
DEBUG: No schedule defined(branch="renovate/all")
DEBUG: Branch already exists(branch="renovate/all")
DEBUG: Manual rebase requested via PR checkbox for #1(branch="renovate/all")
DEBUG: Using reuseExistingBranch: false(branch="renovate/all")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/all")
DEBUG: gomod.updateDependency: v12.0.0(branch="renovate/all")
DEBUG: gomod: major update(branch="renovate/all")
{
  "depName": "k8s.io/client-go"
}
DEBUG: Updating k8s.io/client-go in go.mod(branch="renovate/all")
DEBUG: gomod.updateArtifacts(go.mod)(branch="renovate/all")
DEBUG: go get command included(branch="renovate/all")
{
  "cmd": "go",
  "args": "get -d ./..."
}
DEBUG: go mod tidy command included(branch="renovate/all")
{
  "cmd": "go",
  "args": "mod tidy"
}
DEBUG: additional go mod tidy command included(branch="renovate/all")
{
  "cmd": "go",
  "args": "mod tidy"
}
DEBUG: Using docker to execute(branch="renovate/all")
DEBUG: Found version constraint - checking for a compatible image to use(branch="renovate/all")
{
  "depName": "docker.io/renovate/go",
  "scheme": "npm",
  "constraint": "^1.17"
}
DEBUG: getLabels(https://index.docker.io, renovate/go, latest)(branch="renovate/all")
DEBUG: Found compatible image version(branch="renovate/all")
{
  "depName": "docker.io/renovate/go",
  "scheme": "npm",
  "constraint": "^1.17",
  "version": "1.17.2"
}
DEBUG: Resolved tag constraint(branch="renovate/all")
{
  "image": "docker.io/renovate/go",
  "tagConstraint": "^1.17",
  "tagVersioning": "npm",
  "tag": "1.17.2"
}
DEBUG: Fetching Docker image: docker.io/renovate/go:1.17.2(branch="renovate/all")
DEBUG: Finished fetching Docker image(branch="renovate/all")
DEBUG: Executing command(branch="renovate/all")
{
  "command": [
    "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/StevenACoffman/repro\":\"/mnt/renovate/gh/StevenACoffman/repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/StevenACoffman/repro\" docker.io/renovate/go:1.17.2 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./... && go mod tidy && go mod tidy\""
  ]
}
DEBUG: rawExec err(branch="renovate/all")
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/StevenACoffman/repro\":\"/mnt/renovate/gh/StevenACoffman/repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/StevenACoffman/repro\" docker.io/renovate/go:1.17.2 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./... && go mod tidy && go mod tidy\"",
    "stdout": "",
    "stderr": "go: k8s.io/client-go/v12@v12.0.0: go.mod has non-.../v12 module path \"k8s.io/client-go\" (and .../v12/go.mod does not exist) at revision v12.0.0\n",
    "message": "Command failed: docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/StevenACoffman/repro\":\"/mnt/renovate/gh/StevenACoffman/repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/StevenACoffman/repro\" docker.io/renovate/go:1.17.2 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://**redacted**@v12.0.0: go.mod has non-.../v12 module path \"k8s.io/client-go\" (and .../v12/go.mod does not exist) at revision v12.0.0\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/StevenACoffman/repro\":\"/mnt/renovate/gh/StevenACoffman/repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/StevenACoffman/repro\" docker.io/renovate/go:1.17.2 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://**redacted**@v12.0.0: go.mod has non-.../v12 module path \"k8s.io/client-go\" (and .../v12/go.mod does not exist) at revision v12.0.0\n\n    at ChildProcess.exithandler (child_process.js:390:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  }
}
DEBUG: Failed to update go.sum(branch="renovate/all")
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/StevenACoffman/repro\":\"/mnt/renovate/gh/StevenACoffman/repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/StevenACoffman/repro\" docker.io/renovate/go:1.17.2 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./... && go mod tidy && go mod tidy\"",
    "stdout": "",
    "stderr": "go: k8s.io/client-go/v12@v12.0.0: go.mod has non-.../v12 module path \"k8s.io/client-go\" (and .../v12/go.mod does not exist) at revision v12.0.0\n",
    "message": "Command failed: docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/StevenACoffman/repro\":\"/mnt/renovate/gh/StevenACoffman/repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/StevenACoffman/repro\" docker.io/renovate/go:1.17.2 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://**redacted**@v12.0.0: go.mod has non-.../v12 module path \"k8s.io/client-go\" (and .../v12/go.mod does not exist) at revision v12.0.0\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/StevenACoffman/repro\":\"/mnt/renovate/gh/StevenACoffman/repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/StevenACoffman/repro\" docker.io/renovate/go:1.17.2 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://**redacted**@v12.0.0: go.mod has non-.../v12 module path \"k8s.io/client-go\" (and .../v12/go.mod does not exist) at revision v12.0.0\n\n    at ChildProcess.exithandler (child_process.js:390:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  }
}
DEBUG: Updated 1 package files(branch="renovate/all")
DEBUG: No updated lock files in branch(branch="renovate/all")
DEBUG: PR has no releaseTimestamp(branch="renovate/all")
DEBUG: 1 file(s) to commit(branch="renovate/all")
DEBUG: Committing files to branch renovate/all(branch="renovate/all")
DEBUG: Setting git author name(branch="renovate/all")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/all")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/all")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/all",
    "commit": "629f62d",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 1
    }
  }
}
DEBUG: git push(branch="renovate/all")
{
  "result": {
    "pushed": [],
    "branch": {
      "local": "renovate/all",
      "remote": "renovate/all",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/all"
    },
    "remoteMessages": {
      "all": []
    }
  }
}
INFO: Branch updated(branch="renovate/all")
{
  "commitSha": "629f62d"
}
DEBUG: Updating status check state to failed(branch="renovate/all")
DEBUG: Setting branch status(branch="renovate/all")
{
  "context": "renovate/artifacts",
  "state": "red"
}
DEBUG: Checking if we can automerge branch(branch="renovate/all")
DEBUG: mergeStatus=no automerge(branch="renovate/all")
DEBUG: Ensuring PR(branch="renovate/all")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/all")
DEBUG: Found existing PR(branch="renovate/all")
DEBUG: Forcing PR because of artifact errors(branch="renovate/all")
DEBUG: Processing existing PR(branch="renovate/all")
DEBUG: updatePr(1, Update module k8s.io/client-go to v12, body)(branch="renovate/all")
DEBUG: PR updated(branch="renovate/all")
{
  "pr": 1
}
INFO: PR updated(branch="renovate/all")
{
  "pr": 1,
  "prTitle": "Update module k8s.io/client-go to v12"
}
WARN: artifactErrors(branch="renovate/all")
{
  "artifactErrors": [
    {
      "lockFile": "go.sum",
      "stderr": "Command failed: docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/StevenACoffman/repro\":\"/mnt/renovate/gh/StevenACoffman/repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/StevenACoffman/repro\" docker.io/renovate/go:1.17.2 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./... && go mod tidy && go mod tidy\"\ngo: k8s.io/client-go/v12@v12.0.0: go.mod has non-.../v12 module path \"k8s.io/client-go\" (and .../v12/go.mod does not exist) at revision v12.0.0\n"
    }
  ]
}
DEBUG: getClosedPrs(): no graphql data(branch="renovate/all")
DEBUG: Getting comments for #1(branch="renovate/all")
DEBUG: Found 1 comments(branch="renovate/all")
DEBUG: Ensuring comment "⚠ Artifact update problem" in #1(branch="renovate/all")
DEBUG: Comment is already update-to-date(branch="renovate/all")
DEBUG: Ensuring Dependency Dashboard
DEBUG: ensureIssue(Dependency Dashboard)
DEBUG: Issue is open and up to date - nothing to do
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/all"
  ],
  "renovateBranches": [
    "renovate/all"
  ]
}
DEBUG: remainingBranches=
DEBUG: No branches to clean up
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 1878,
    "extract": 368,
    "lookup": 857,
    "update": 17697
  },
  "total": 21066
}
DEBUG: http statistics
{
  "urls": {
    "https://api.github.com/graphql (POST)": 5,
    "https://api.github.com/repos/StevenACoffman/repro/commits/629f62d99e164bd9a36b2b2d0c6b6a4d983bb079/statuses (GET)": 2,
    "https://api.github.com/repos/StevenACoffman/repro/commits/renovate/all/status (GET)": 1,
    "https://api.github.com/repos/StevenACoffman/repro/contents/renovate.json (GET)": 1,
    "https://api.github.com/repos/StevenACoffman/repro/issues/1/comments (GET)": 1,
    "https://api.github.com/repos/StevenACoffman/repro/issues/2 (GET)": 2,
    "https://api.github.com/repos/StevenACoffman/repro/pulls (GET)": 1,
    "https://api.github.com/repos/StevenACoffman/repro/pulls/1 (PATCH)": 1,
    "https://api.github.com/repos/StevenACoffman/repro/statuses/629f62d99e164bd9a36b2b2d0c6b6a4d983bb079 (POST)": 1,
    "https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json (GET)": 1,
    "https://k8s.io/apimachinery (GET)": 1,
    "https://k8s.io/client-go (GET)": 1
  },
  "hostStats": {
    "api.github.com": {
      "requestCount": 16,
      "requestAvgMs": 328,
      "queueAvgMs": 0
    },
    "k8s.io": {
      "requestCount": 2,
      "requestAvgMs": 146,
      "queueAvgMs": 0
    }
  },
  "totalRequests": 18
}
INFO: Repository finished
{
  "durationMs": 21066
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Please rewrite the above to include one problem only and remove the rest - pick the one which should be solved first

**Comment by rarkins** [comment]
I am optimistic that using GOPROXY should work around most of these problems. To be confident in that we'd need to:
- Confirm the reproduction repo using the renovate CLI (e.g. it attempts to update to v12)
- Configure GOPROXY to point to the default public proxy
- Test again and see if it behaves as expected

**Comment by rarkins** [comment]
Actually, the repro repo is not minimal. It contains 25+ dependencies and 49 lines of Renovate config. First step will be to trim it down.
