### ISSUE TITLE
Cannot find preset's package: github>whitesource/merge-confidence:beta

### ISSUE THREAD

**Issue by nils-a** [renovatebot/renovate#12226]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

I had two issues opened by renovate recently, which I can not explain.
One is https://github.com/cake-contrib/Cake.ESLint/issues/95, the other is https://github.com/cake-contrib/CakeContrib.Guidelines/issues/162.

The issue is:
> **Action Required: Fix Renovate Configuration**
> There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.
> Error type: Cannot find preset's package (github>whitesource/merge-confidence:beta)

However, `https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json` downloads fine.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "28.1.8"
}
DEBUG: Using localDir: /mnt/renovate/gh/cake-contrib/Cake.ESLint
DEBUG: Repository cache is valid
DEBUG: initRepo("cake-contrib/Cake.ESLint")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: cake-contrib/Cake.ESLint default branch = develop
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: Resetting npmrc
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: Checking cached config file name
DEBUG: Existing config file confirmed
DEBUG: Repo is onboarded
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "github>nils-a/renovate-config"
    ],
    "packageRules": [
      {
        "matchPackageNames": [
          "cake.tool",
          "Cake.Core"
        ],
        "enabled": false
      }
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "github>nils-a/renovate-config"
    ],
    "packageRules": [
      {
        "matchPackageNames": [
          "cake.tool",
          "Cake.Core"
        ],
        "enabled": false
      }
    ]
  }
}
DEBUG: GitHub 404
{
  "url": "https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json"
}
DEBUG: Failed to retrieve beta.json from repo
{
  "statusCode": 404,
  "url": "https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json"
}
DEBUG: Preset fetch error
{
  "preset": "github>whitesource/merge-confidence:beta",
  "err": {
    "message": "dep not found",
    "stack": "Error: dep not found\n    at fetchJSONFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/github/index.js:22:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async fetchPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/util.js:32:23)\n    at async getPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:189:24)\n    at async Object.resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:253:37)\n    at async mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/merge.js:214:61)\n    at async getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:12:14)\n    at async initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:26:14)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:400:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:644:5"
  }
}
INFO: Throwing preset error
{
  "validationError": "Cannot find preset's package (github>whitesource/merge-confidence:beta)"
}
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (github>whitesource/merge-confidence:beta)",
    "message": "config-validation",
    "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:265:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/merge.js:214:61)\n    at async getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:12:14)\n    at async initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:26:14)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:400:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:644:5"
  }
}
DEBUG: raiseConfigWarningIssue()
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, undefined, open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 52 Pull Requests
DEBUG: findPr(renovate/configure, undefined, closed)
DEBUG: ensureIssue(Action Required: Fix Renovate Configuration)
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
INFO: Issue created
WARN: Config Warning
{
  "configError": {
    "validationError": "Cannot find preset's package (github>whitesource/merge-confidence:beta)",
    "message": "config-validation",
    "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:265:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/merge.js:214:61)\n    at async getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:12:14)\n    at async initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:26:14)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:400:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:644:5"
  },
  "res": "created"
}
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {},
  "total": 3741
}
DEBUG: http statistics
{
  "urls": {
    "https://api.github.com/graphql (POST)": 2,
    "https://api.github.com/repos/cake-contrib/Cake.ESLint/contents/.github/renovate.json (GET)": 1,
    "https://api.github.com/repos/cake-contrib/Cake.ESLint/issues (POST)": 1,
    "https://api.github.com/repos/cake-contrib/Cake.ESLint/pulls (GET)": 1
  },
  "hostStats": {
    "api.github.com": {
      "requestCount": 5,
      "requestAvgMs": 579,
      "queueAvgMs": 0
    }
  },
  "totalRequests": 5
}
INFO: Repository finished
{
  "durationMs": 3741
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by stephtr** [comment]
I had the same issue, but it just got automatically closed by renovatebot.

**Comment by JamieMagee** [comment]
GitHub was returning 404s for that API call temporarily. We use [`got`](https://github.com/sindresorhus/got) and it's not configured to retry HTTP calls for 404s.

I think this was an external (to Renovate) issue and not something we can really fix. If this occurs again I can investigate more from the GitHub side, but for now I would close this issue as a transient error.

Do you agree with that @nils-a?

**Comment by rarkins** [comment]
@JamieMagee any idea if "random 404s" is a known problem from GitHub? It's hitting me during initRepo too

**Comment by nils-a** [comment]
@JamieMagee agreed. Both issues were closed automatically with the next run.

Perhaps the text of the issue could be adapted to provide a link to the dashboard (`https://app.renovatebot.com/dashboard`) like it's done on the PRs. (Most likely the logs should be analysed anyways.) And maybe also add some text to ensure the use that this issue will be auto-closed when the problem is fixed.
