### ISSUE TITLE
Renovate fails to run on projects that use Ruby 3.0

### ISSUE THREAD

**Issue by deiga** [renovatebot/renovate#12231]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

I have a repository that uses Ruby 3.0 and Renovate fails to update the Gemfile.lock because it's trying to use ruby 2.7
https://github.com/deiga/dorcadiini/pull/2

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/pin-dependencies")
DEBUG: Starting search at index 206(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "minitest"
}
DEBUG: Found match at index 206(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "minitest"
}
DEBUG: Found Gemfile.lock file(packageFile="Gemfile", branch="renovate/pin-dependencies")
DEBUG: Contents updated(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "minitest"
}
DEBUG: Starting search at index 179(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "rake"
}
DEBUG: Found match at index 179(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "rake"
}
DEBUG: Found Gemfile.lock file(packageFile="Gemfile", branch="renovate/pin-dependencies")
DEBUG: Contents updated(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "rake"
}
DEBUG: Starting search at index 230(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "rubocop"
}
DEBUG: Found match at index 230(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "rubocop"
}
DEBUG: Found Gemfile.lock file(packageFile="Gemfile", branch="renovate/pin-dependencies")
DEBUG: Contents updated(packageFile="Gemfile", branch="renovate/pin-dependencies")
{
  "depName": "rubocop"
}
DEBUG: bundler.updateArtifacts(Gemfile)(branch="renovate/pin-dependencies")
DEBUG: Found bundler version(branch="renovate/pin-dependencies")
{
  "bundlerVersion": "2.2.26"
}
DEBUG: Using docker to execute(branch="renovate/pin-dependencies")
DEBUG: No tag or tagConstraint specified(branch="renovate/pin-dependencies")
{
  "image": "docker.io/renovate/ruby"
}
DEBUG: Fetching Docker image: docker.io/renovate/ruby(branch="renovate/pin-dependencies")
DEBUG: Finished fetching Docker image(branch="renovate/pin-dependencies")
DEBUG: Executing command(branch="renovate/pin-dependencies")
{
  "command": [
    "docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/deiga/dorcadiini\":\"/mnt/renovate/gh/deiga/dorcadiini\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/deiga/dorcadiini\" docker.io/renovate/ruby bash -l -c \"ruby --version && gem install bundler -v 2.2.26 && bundle lock --update minitest rake rubocop\""
  ]
}
DEBUG: rawExec err(branch="renovate/pin-dependencies")
{
  "err": {
    "killed": false,
    "code": 6,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/deiga/dorcadiini\":\"/mnt/renovate/gh/deiga/dorcadiini\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/deiga/dorcadiini\" docker.io/renovate/ruby bash -l -c \"ruby --version && gem install bundler -v 2.2.26 && bundle lock --update minitest rake rubocop\"",
    "stdout": "ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]\nSuccessfully installed bundler-2.2.26\n1 gem installed\nFetching gem metadata from https://rubygems.org/.........\nResolving dependencies...\n",
    "stderr": "Bundler found conflicting requirements for the Ruby\u0000 version:\n  In Gemfile:\n    Ruby\u0000\n\n    dorcadiini was resolved to 0.1.0, which depends on\n      Ruby\u0000 (>= 3.0.0)\n\n    rubocop-minitest was resolved to 0.15.0, which depends on\n      Ruby\u0000 (>= 2.5.0)\n\nRuby\u0000 (>= 3.0.0), which is required by gem 'dorcadiini', is not available in the\nlocal ruby installation\nBundler could not find compatible versions for gem \"dorcadiini\":\n  In snapshot (Gemfile.lock):\n    dorcadiini (= 0.1.0)\n\n  In Gemfile:\n    dorcadiini\n\nRunning `bundle update` will rebuild your snapshot from scratch, using only\nthe gems in your Gemfile, which may resolve the conflict.\n",
    "message": "Command failed: docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/deiga/dorcadiini\":\"/mnt/renovate/gh/deiga/dorcadiini\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/deiga/dorcadiini\" docker.io/renovate/ruby bash -l -c \"ruby --version && gem install bundler -v 2.2.26 && bundle lock --update minitest rake rubocop\"\nBundler found conflicting requirements for the Ruby\u0000 version:\n  In Gemfile:\n    Ruby\u0000\n\n    dorcadiini was resolved to 0.1.0, which depends on\n      Ruby\u0000 (>= 3.0.0)\n\n    rubocop-minitest was resolved to 0.15.0, which depends on\n      Ruby\u0000 (>= 2.5.0)\n\nRuby\u0000 (>= 3.0.0), which is required by gem 'dorcadiini', is not available in the\nlocal ruby installation\nBundler could not find compatible versions for gem \"dorcadiini\":\n  In snapshot (Gemfile.lock):\n    dorcadiini (= 0.1.0)\n\n  In Gemfile:\n    dorcadiini\n\nRunning `bundle update` will rebuild your snapshot from scratch, using only\nthe gems in your Gemfile, which may resolve the conflict.\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/deiga/dorcadiini\":\"/mnt/renovate/gh/deiga/dorcadiini\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/deiga/dorcadiini\" docker.io/renovate/ruby bash -l -c \"ruby --version && gem install bundler -v 2.2.26 && bundle lock --update minitest rake rubocop\"\nBundler found conflicting requirements for the Ruby\u0000 version:\n  In Gemfile:\n    Ruby\u0000\n\n    dorcadiini was resolved to 0.1.0, which depends on\n      Ruby\u0000 (>= 3.0.0)\n\n    rubocop-minitest was resolved to 0.15.0, which depends on\n      Ruby\u0000 (>= 2.5.0)\n\nRuby\u0000 (>= 3.0.0), which is required by gem 'dorcadiini', is not available in the\nlocal ruby installation\nBundler could not find compatible versions for gem \"dorcadiini\":\n  In snapshot (Gemfile.lock):\n    dorcadiini (= 0.1.0)\n\n  In Gemfile:\n    dorcadiini\n\nRunning `bundle update` will rebuild your snapshot from scratch, using only\nthe gems in your Gemfile, which may resolve the conflict.\n\n    at ChildProcess.exithandler (child_process.js:390:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  }
}
DEBUG: Bundler has a resolve error(branch="renovate/pin-dependencies")
{
  "err": {
    "killed": false,
    "code": 6,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/deiga/dorcadiini\":\"/mnt/renovate/gh/deiga/dorcadiini\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/deiga/dorcadiini\" docker.io/renovate/ruby bash -l -c \"ruby --version && gem install bundler -v 2.2.26 && bundle lock --update minitest rake rubocop\"",
    "stdout": "ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]\nSuccessfully installed bundler-2.2.26\n1 gem installed\nFetching gem metadata from https://rubygems.org/.........\nResolving dependencies...\n",
    "stderr": "Bundler found conflicting requirements for the Ruby\u0000 version:\n  In Gemfile:\n    Ruby\u0000\n\n    dorcadiini was resolved to 0.1.0, which depends on\n      Ruby\u0000 (>= 3.0.0)\n\n    rubocop-minitest was resolved to 0.15.0, which depends on\n      Ruby\u0000 (>= 2.5.0)\n\nRuby\u0000 (>= 3.0.0), which is required by gem 'dorcadiini', is not available in the\nlocal ruby installation\nBundler could not find compatible versions for gem \"dorcadiini\":\n  In snapshot (Gemfile.lock):\n    dorcadiini (= 0.1.0)\n\n  In Gemfile:\n    dorcadiini\n\nRunning `bundle update` will rebuild your snapshot from scratch, using only\nthe gems in your Gemfile, which may resolve the conflict.\n",
    "message": "Command failed: docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/deiga/dorcadiini\":\"/mnt/renovate/gh/deiga/dorcadiini\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/deiga/dorcadiini\" docker.io/renovate/ruby bash -l -c \"ruby --version && gem install bundler -v 2.2.26 && bundle lock --update minitest rake rubocop\"\nBundler found conflicting requirements for the Ruby\u0000 version:\n  In Gemfile:\n    Ruby\u0000\n\n    dorcadiini was resolved to 0.1.0, which depends on\n      Ruby\u0000 (>= 3.0.0)\n\n    rubocop-minitest was resolved to 0.15.0, which depends on\n      Ruby\u0000 (>= 2.5.0)\n\nRuby\u0000 (>= 3.0.0), which is required by gem 'dorcadiini', is not available in the\nlocal ruby installation\nBundler could not find compatible versions for gem \"dorcadiini\":\n  In snapshot (Gemfile.lock):\n    dorcadiini (= 0.1.0)\n\n  In Gemfile:\n    dorcadiini\n\nRunning `bundle update` will rebuild your snapshot from scratch, using only\nthe gems in your Gemfile, which may resolve the conflict.\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/deiga/dorcadiini\":\"/mnt/renovate/gh/deiga/dorcadiini\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/deiga/dorcadiini\" docker.io/renovate/ruby bash -l -c \"ruby --version && gem install bundler -v 2.2.26 && bundle lock --update minitest rake rubocop\"\nBundler found conflicting requirements for the Ruby\u0000 version:\n  In Gemfile:\n    Ruby\u0000\n\n    dorcadiini was resolved to 0.1.0, which depends on\n      Ruby\u0000 (>= 3.0.0)\n\n    rubocop-minitest was resolved to 0.15.0, which depends on\n      Ruby\u0000 (>= 2.5.0)\n\nRuby\u0000 (>= 3.0.0), which is required by gem 'dorcadiini', is not available in the\nlocal ruby installation\nBundler could not find compatible versions for gem \"dorcadiini\":\n  In snapshot (Gemfile.lock):\n    dorcadiini (= 0.1.0)\n\n  In Gemfile:\n    dorcadiini\n\nRunning `bundle update` will rebuild your snapshot from scratch, using only\nthe gems in your Gemfile, which may resolve the conflict.\n\n    at ChildProcess.exithandler (child_process.js:390:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
  }
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
More importantly, is there any indication in this repo we missed where we should know what the version used is? Eg inside Gemfile.lock or a rubyenv file

**Comment by viceice** [comment]
[`Gemfile`](https://github.com/deiga/dorcadiini/blob/e5fdf5d88690a5ead67e5aa6f5747c4a4310a765/Gemfile#L9)
