### ISSUE TITLE
Cloning of repositories fails with ___ since 27.0

### ISSUE THREAD

**Issue by cascornelissen** [renovatebot/renovate#12255]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of Renovate you run.

28.6.0, based on renovate/renovate:slim

### Describe the bug

We're using the [`renovate/renovate` Docker image](https://github.com/renovatebot/docker-renovate) and are seeing problems since `27.0.0`. The issue is that the `git clone` for each repository Renovate runs on throws the error included below.

**Tested the following versions**
* `26.21.7` has no problems
* `27.0.0`, `27.1.0` and `28.6.0` throw the error included below for each repository that Renovate runs on

**Things I've tried already**
* The [release notes of `27.0.0`](https://github.com/renovatebot/renovate/releases/tag/27.0.0) mention that at least git `2.33.0` is needed and running `git --version` within the container returns `2.33.0`.
* The password used in the `git clone` command is an alphanumerical string
* Running the command `git clone --filter=blob:none https://<username>:<password>@<repository-url>.git .` from within the container works without issues.

**Other things I noticed**
* What's interesting is that the revision identifier `8eb2636b29df5b60f15872f4124488749873b116` is the same for each project.

### Relevant debug logs

<details><summary>Logs</summary>

```
build	21-Oct-2021 11:49:03	DEBUG: git clone error (repository=ddnei/expert-insight-wrapper)
build	21-Oct-2021 11:49:03	       "err": {
build	21-Oct-2021 11:49:03	         "task": {
build	21-Oct-2021 11:49:03	           "commands": [
build	21-Oct-2021 11:49:03	             "clone",
build	21-Oct-2021 11:49:03	             "--filter=blob:none",
build	21-Oct-2021 11:49:03	             "https://<username>:<password>@<repository-url>.git",
build	21-Oct-2021 11:49:03	             "."
build	21-Oct-2021 11:49:03	           ],
build	21-Oct-2021 11:49:03	           "format": "utf-8"
build	21-Oct-2021 11:49:03	         },
build	21-Oct-2021 11:49:03	         "message": "Cloning into '.'...\nfatal: bad revision '8eb2636b29df5b60f15872f4124488749873b116'\nerror: <repository-url>.git did not send all necessary objects\n\nfatal: bad revision '8eb2636b29df5b60f15872f4124488749873b116'\nerror: <repository-url>.git did not send all necessary objects\n\nfatal: bad revision '8eb2636b29df5b60f15872f4124488749873b116'\nerror: <repository-url>.git did not send all necessary objects\n\nerror: unable to read sha1 file of <file> (8eb2636b29df5b60f15872f4124488749873b116)\nfatal: bad revision '65015f13a45ac21064c4fd448bf4970bdab691f7'\nerror: <repository-url>.git did not send all necessary objects\n
...
fatal: unable to checkout working tree\nwarning: Clone succeeded, but checkout failed.\nYou can inspect what was checked out with 'git status'\nand retry with 'git restore --source=HEAD :/'\n\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
build	21-Oct-2021 11:49:03	       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Probably a duplicate of #11759
