### ISSUE TITLE
Renovate PR Title, CommitMessage and Branchname bug when using `{{ ` and `}}`.

### ISSUE THREAD

**Issue by picnic-sven** [renovatebot/renovate#12449]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.18.1

### Describe the bug

# Renovate PR Title, CommitMessage and Branchname bug when using ``{{ and }}``.

Given a repository with the structure:
```
root
—{{project_template}}/Pipfile
.renovaterc.json
```

and upgrading packages using the `Pipfile` in `{{project_template}}`
and the relevant configuration parameters in `renovaterc.json` are set like:

```
"additionalBranchPrefix": "{{parentDir}}-",
"commitMessagePrefix": “TicketID- {{parentDir}}:",
```

The expect PR has the following properties:

```
PR Title = “TicketID {{project_template}}: Upgrade {{Project_Name}}” 
commit message = “TicketID {{project_template}}: Upgrade dependency `package` to `new_version`” 
branch name = renovate/{{project_name}}-parentdir
```

The actual PR has the following properties: 

```
PR Title = “TicketID: Upgrade” 
commit message = “TicketID: Upgrade dependency” 
branch name = renovate/-parentdir
```

An identical project named `project_template` is added to showcase the expected Renovate behaviour.

Minimal repository: https://github.com/picnic-sven/Renovate-PRTitle-CommitMessage-Branchname-Bug
Bug confirmed with Renovate versions 27.18.1 (self-hosted) and 28.21.4 (GH app)

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Renovate compiles using handlebars. Have you experimented with any of its escaping techniques? when I googled I saw some recommendations for "Whitespace control": https://handlebarsjs.com/guide/expressions.html#whitespace-control

**Comment by picnic-sven** [comment]
> Renovate compiles using handlebars. Have you experimented with any of its escaping techniques? when I googled I saw some recommendations for "Whitespace control": https://handlebarsjs.com/guide/expressions.html#whitespace-control

Thanks for responding so quickly! I tried both approaches, but sadly no success.

## [Approach 1](https://github.com/picnic-sven/Renovate-PRTitle-CommitMessage-Branchname-Bug/commit/3f32784b9f80be35256a1c3490e2eb4382a0c8f7) (raw block helpers):

- Only 1 PR was created.
- PR title, commit message and branchname(`renovate/rawparentdirraw`) all incorrect.
- Relevant logs:

```
DEBUG: branchifyUpgrades
DEBUG: Using group branchName template
DEBUG: Dependency pandas is part of group {{{{raw}}}}{{parentDir}}{{{{/raw}}}}
INFO: Disallowed variable name in template
{
  "varName": "raw",
  "template": "renovate/{{{{raw}}}}{{parentDir}}{{{{/raw}}}}-{{{groupSlug}}}"
}
DEBUG: Using group branchName template
DEBUG: Dependency pandas is part of group {{{{raw}}}}{{parentDir}}{{{{/raw}}}}
INFO: Disallowed variable name in template
{
  "varName": "raw",
  "template": "renovate/{{{{raw}}}}{{parentDir}}{{{{/raw}}}}-{{{groupSlug}}}"
}
DEBUG: 2 flattened updates found: pandas, pandas
DEBUG: Returning 1 branch(es)
INFO: Disallowed variable name in template(branch="renovate/-rawparentdirraw")
{
  "varName": "raw",
  "template": "TicketID {{{{raw}}}}{{parentDir}}{{{{/raw}}}}: Update dependency {{depName}} to {{#if isMajor}}v{{{newMajor}}}{{else}}{{#if isSingleVersion}}v{{{newVersion}}}{{else}}{{{newValue}}}{{/if}}{{/if}} "
}
INFO: Disallowed variable name in template(branch="renovate/-rawparentdirraw")
{
  "varName": "raw",
  "template": "TicketID {{{{raw}}}}{{parentDir}}{{{{/raw}}}}: Update dependency {{depName}} to {{#if isMajor}}v{{{newMajor}}}{{else}}{{#if isSingleVersion}}v{{{newVersion}}}{{else}}{{{newValue}}}{{/if}}{{/if}} "
}
```


## [Approach 2](https://github.com/picnic-sven/Renovate-PRTitle-CommitMessage-Branchname-Bug/commit/b73003182524e1c02308527f1af75f419ae53270) (inline escapes):

- No PR was created, only a renovate config [issue ticket](https://github.com/picnic-sven/Renovate-PRTitle-CommitMessage-Branchname-Bug/issues/5).
- Relevant logs:

```
DEBUG: Found .renovaterc.json config file
DEBUG: Error parsing renovate config
{
  "renovateConfig": "{\n    \"$schema\": \"https://json.schemastore.org/renovate\",\n    \"additionalBranchPrefix\": \"\\{{parentDir}}-\",\n    \"commitMessagePrefix\": \"TicketID \\{{parentDir}}:\",\n    \"enabledManagers\": [\"pipenv\"],\n    \"packageRules\": [\n      {\n        \"groupName\": \"\\{{parentDir}}\",\n        \"matchPackagePatterns\": [\".*\"]\n      }\n    ],\n    \"prHeader\": \"Type: opt\\nTicket: TicketID\",\n    \"rangeStrategy\": \"bump\",\n    \"includePaths\": [\n      \"{{project_template}}/Pipfile\",\n      \"project_template/Pipfile\"\n    ]\n  }"
}
INFO: Repository has invalid config
{
  "error": {
    "validationSource": ".renovaterc.json",
    "validationError": "Invalid JSON (parsing failed)",
    "validationMessage": "JSON.parse error:  Unexpected token { in JSON at position 90",
    "message": "config-validation",
    "stack": "Error: config-validation\n    at checkForRepoConfigError (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/merge.js:165:19)\n    at mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/merge.js:185:5)\n    at async getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:15:14)\n    at async initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:26:14)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:401:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:645:5"
  }
}
```

**Comment by rarkins** [comment]
I think you should try Approach 2 with valid JSON. It should be possible to try it with JSON that parses. e.g. check in https://jsonlint.com/

**Comment by picnic-sven** [comment]
Thanks again for the quick reply. 
One step closer; adding `\\` before `{{parentDir}}` at `additionalBranchPrefix` and `commitMessagePrefix` does [result](https://github.com/picnic-sven/Renovate-PRTitle-CommitMessage-Branchname-Bug/pulls) in the correct naming of the branch and commit message!

Adding `\\` before `{{parentDir}}` at `packageRules:[{“groupName”:{{parentDir}}”}]` does not generate the expected PR Title.

Relevant logs:
```
DEBUG: migrated config
{
  "config": {
    "$schema": "https://json.schemastore.org/renovate",
    "additionalBranchPrefix": "\\{{parentDir}}-",
    "commitMessagePrefix": "TicketID \\{{parentDir}}:",
    "enabledManagers": [
      "pipenv"
    ],
    "packageRules": [
      {
        "groupName": "\\{{parentDir}}",
        "matchPackagePatterns": [
          ".*"
        ]
      }
    ],
    "prHeader": "Type: opt\nTicket: TicketID",
    "rangeStrategy": "bump",
    "includePaths": [
      "{{project_template}}/Pipfile",
      "project_template/Pipfile"
    ],
    "extends": [
      "github>whitesource/merge-confidence:beta"
    ]
  }
}

….

Creating PR(branch="renovate/{{project_template}}-parentdir")
{
  "prTitle": "TicketID : Update dependency pandas to ~=1.3.4"
}
DEBUG: Creating PR(branch="renovate/{{project_template}}-parentdir")
{
  "title": "TicketID : Update dependency pandas to ~=1.3.4",
  "head": "picnic-sven:renovate/{{project_template}}-parentdir",
  "base": "main",
  "draft": false
}

```

**Comment by rarkins** [comment]
groupName might get compiled twice. Can you set your repo to reproduce this particular problem?

**Comment by picnic-sven** [comment]
I've update the `README.md` in my [repo](https://github.com/picnic-sven/Renovate-PRTitle-CommitMessage-Branchname-Bug). The rest of the repo is setup to produce the unexpected behaviour.

**Comment by rarkins** [comment]
Unfortunately I can't work out any way to get it to work, but maybe on day someone will figure it out

**Comment by olegkrivtsov** [comment]
I'd like to help with this one.

**Comment by rarkins** [comment]
Only if it's a quick fix

**Comment by olegkrivtsov** [comment]
Hi @rarkins I'm sorry, but I feel that I lack Renovate intrinsics knowledge to fix this quickly enough, without investing time into familiarizing myself with Handlebars compilation and commit message prefixes.

**Comment by klutchell** [comment]
This might be worth a new bug, but as far as I can tell `template.compile()` is never called for `groupName` or `groupSlug` and as a result the branch name and similar fields are just the slugified group name without templates applied.

If this is accurate, at the very least we should update the docs to indicate that those two fields are not passed to templating as indicated today.

Going forward, we would need to identify the best place to compile those fields before they are inherited by the group object or otherwise slugified.

**Comment by secustor** [comment]
@klutchell  Can you check again if this is still the case? 
Potentially https://github.com/renovatebot/renovate/pull/25490 has already fixed this.
