### ISSUE TITLE
Unnoticed breaking change: Field 'autoMergeAllowed' doesn't exist on type 'Repository'

### ISSUE THREAD

**Issue by KnisterPeter** [renovatebot/renovate#12451]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of Renovate you run.

28.15.2

### Describe the bug

Since some versions (minor/patch updates) renovate complains with these error output:

```
 INFO: Repository started (repository=fea/renovate-bot-test)
       "renovateVersion": "28.21.5"
DEBUG: Using localDir: /tmp/fea/renovate-bot-test (repository=fea/renovate-bot-test)
DEBUG: initRepo("fea/renovate-bot-test") (repository=fea/renovate-bot-test)
DEBUG: Overriding default GitHub endpoint (repository=fea/renovate-bot-test)
       "endpoint": "https://xxxx/api/v3/"
DEBUG: res (repository=fea/renovate-bot-test)
       "errors": [
         {
           "path": ["query", "repository", "autoMergeAllowed"],
           "extensions": {
             "code": "undefinedField",
             "typeName": "Repository",
             "fieldName": "autoMergeAllowed"
           },
           "locations": [{"line": 8, "column": 5}],
           "message": "Field 'autoMergeAllowed' doesn't exist on type 'Repository'"
         }
       ]
DEBUG: Caught initRepo error (repository=fea/renovate-bot-test)
       "err": {
         "message": "not-found",
         "stack": "Error: not-found\n    at Proxy.initRepo (/xxxx/node_modules/renovate/lib/platform/github/index.ts:220:5)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at getPlatformConfig (/xxxx/node_modules/renovate/lib/workers/repository/init/apis.ts:52:26)\n    at initApis (/xxxx/node_modules/renovate/lib/workers/repository/init/apis.ts:64:12)\n    at initRepo (/xxxx/node_modules/renovate/lib/workers/repository/init/index.ts:30:12)\n    at Object.renovateRepository (/xxxx/node_modules/renovate/lib/workers/repository/index.ts:44:14)\n    at runRenovate (/xxxx/bots/renovate-bot/src/runner.ts:92:3)\n    at /xxxx/bots/renovate-bot/src/basic.integration-test.ts:69:3"
       }
ERROR: Repository is not found (repository=fea/renovate-bot-test)
DEBUG: Repository timing splits (milliseconds) (repository=fea/renovate-bot-test)
       "splits": {},
       "total": 228
```

### Relevant debug logs

<details><summary>Logs</summary>

```
See above for the relevant log parts
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by KnisterPeter** [comment]
This is most likely caused by https://github.com/renovatebot/renovate/pull/12398
The field `autoMergeAllowed` is not supported to at least GitHub Enterprise Server 3.0.16.

**Comment by viceice** [comment]
With version of GitHub Enterprise are you using? Looks like v2 which is EOL, so no longer supported by renovate.

Seems to be related to #12439.

**Comment by viceice** [comment]
V3.0 seems to get EOL soon too at `2022-02-16`

https://docs.github.com/en/enterprise-server@3.0/admin/release-notes

**Comment by viceice** [comment]
I think you should update to 3.0.18 as fast as possible because of known security issues.

**Comment by KnisterPeter** [comment]
We are using GitHub Enterprise Server 3.0.16 which is still supported but will be dropped as you stated.

**Comment by rarkins** [comment]
@KnisterPeter are you running it using a github app token or a PAT?

**Comment by KnisterPeter** [comment]
We are using both, the app token in our production setup a PAT for your integration tests.

**Comment by rarkins** [comment]
Are you able to tell if both fail? (trying to work out if it's app-specific)

**Comment by KnisterPeter** [comment]
According to the docs of github, the field `autoMergeAllowed` does not exist in the GraphQL schema.
https://docs.github.com/en/enterprise-server@3.0/graphql/reference/objects#repository

It's quite are to get an app token and test it, but I can do so if you think that it could really make a difference.

**Comment by rarkins** [comment]
https://docs.github.com/en/github-ae@latest/graphql/overview/changelog#schema-changes-for-2021-08-03

Looks like we're going to need to go back to detecting the GHE version and changing our behavior based on that.

We probably need to do it during `initPlatform()`

**Comment by rarkins** [comment]
A `HEAD` to the URL should return header `X-GitHub-Enterprise-Version` with value e.g. `3.0.1`

**Comment by rarkins** [comment]
@zharinov have you found anything which confirms that `autoMergeAllowed` is supported in *any* GHE versions?

**Comment by gustavkj** [comment]
FYI, I did also run into this problem today after bumping `renovate` and we're using Github Enterprise 3.2.2.

**Comment by viceice** [comment]
@zharinov it seems we need to check for `3.2.x` too 🤔

**Comment by zharinov** [comment]
Okay, so I've just excluded `3.2.x` branch completely. This one seems really strange to me.

**Comment by gustavkj** [comment]
> Btw, I have a question: is it just one graphql field or whole auto-merge functionality unavailable for GHE?

The auto-merge feature is available, it was added in [3.1](https://docs.github.com/enterprise-server@3.1/admin/release-notes#pull-request-auto-merge). It seems it's only the GraphQL field that has not been added.

**Comment by rarkins** [comment]
Let's remove the automerge detection completely from GHE for now. But keep version detection as I'll use it for the issue disabling detection.

**Comment by KnisterPeter** [comment]
There was an attempt to fix this with https://github.com/renovatebot/renovate/pull/12458
But in fact it is still not working with latest version (v28.23.1).

There are the logs I get.

```
yarn run v1.22.10
$ yarn build packages/*
$ tsc -b packages/probot-server
$ jest --selectProjects renovate-bot/integration
Running one project: renovate-bot/integration
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /xxxx/config
DEBUG: No config file found on disk - skipping
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {
         "onboardingConfig": {"extends": ["@xingternal:hops-app"]},
         "branchPrefix": "some-branch/"
       }
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "hostRules": [],
         "onboardingConfig": {"extends": ["@xingternal:hops-app"]},
         "branchPrefix": "some-branch/"
       }
DEBUG: Adding token authentication for source.xing.com to hostRules
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
 INFO: Repository started (repository=fea/renovate-bot-test)
       "renovateVersion": "28.23.1"
DEBUG: Using localDir: /tmp/fea/renovate-bot-test (repository=fea/renovate-bot-test)
DEBUG: initRepo("fea/renovate-bot-test") (repository=fea/renovate-bot-test)
DEBUG: Overriding default GitHub endpoint (repository=fea/renovate-bot-test)
       "endpoint": "https://source.xing.com/api/v3/"
  console.log
    
    query($owner: String!, $name: String!) {
      repository(owner: $owner, name: $name) {
        isFork
        isArchived
        nameWithOwner
        hasIssuesEnabled
        autoMergeAllowed
        mergeCommitAllowed
        rebaseMergeAllowed
        squashMergeAllowed
        defaultBranchRef {
          name
          target {
            oid
          }
        }
      }
    }

      at Proxy.initRepo (../../node_modules/renovate/lib/platform/github/index.ts:233:5)

  console.log
    {
      errors: [
        {
          path: [Array],
          extensions: [Object],
          locations: [Array],
          message: "Field 'autoMergeAllowed' doesn't exist on type 'Repository'"
        }
      ]
    } res

      at Proxy.initRepo (../../node_modules/renovate/lib/platform/github/index.ts:242:5)

DEBUG: Caught initRepo error (repository=fea/renovate-bot-test)
       "err": {
         "message": "not-found",
         "stack": "Error: not-found\n    at Proxy.initRepo (/xxxx/node_modules/renovate/lib/platform/github/index.ts:246:5)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at getPlatformConfig (/xxxx/node_modules/renovate/lib/workers/repository/init/apis.ts:52:26)\n    at initApis (/xxxx/node_modules/renovate/lib/workers/repository/init/apis.ts:64:12)\n    at initRepo (/xxxx/node_modules/renovate/lib/workers/repository/init/index.ts:30:12)\n    at Object.renovateRepository (/xxxx/node_modules/renovate/lib/workers/repository/index.ts:44:14)\n    at runRenovate (/xxxx/bots/renovate-bot/src/runner.ts:92:3)\n    at /xxxx/bots/renovate-bot/src/basic.integration-test.ts:69:3"
       }
ERROR: Repository is not found (repository=fea/renovate-bot-test)
DEBUG: Repository timing splits (milliseconds) (repository=fea/renovate-bot-test)
       "splits": {},
       "total": 275
DEBUG: http statistics (repository=fea/renovate-bot-test)
       "urls": {"https://source.xing.com/api/graphql (POST)": 1},
       "hostStats": {"source.xing.com": {"requestCount": 1, "requestAvgMs": 136, "queueAvgMs": 2}},
       "totalRequests": 1
 INFO: Repository finished (repository=fea/renovate-bot-test)
       "durationMs": 275
```

@zharinov @rarkins Can you reopen this?

**Comment by KnisterPeter** [comment]
There was an attempt to fix this with https://github.com/renovatebot/renovate/pull/12458
But in fact it is still not working with latest version (v28.23.1).

There are the logs I get.

```
yarn run v1.22.10
$ yarn build packages/*
$ tsc -b packages/probot-server
$ jest --selectProjects renovate-bot/integration
Running one project: renovate-bot/integration
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /xxxx/config
DEBUG: No config file found on disk - skipping
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "hostRules": [],
         "onboardingConfig": {},
         "branchPrefix": "some-branch/"
       }
DEBUG: Adding token authentication for xxx to hostRules
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
 INFO: Repository started (repository=fea/renovate-bot-test)
       "renovateVersion": "28.23.1"
DEBUG: Using localDir: /tmp/fea/renovate-bot-test (repository=fea/renovate-bot-test)
DEBUG: initRepo("fea/renovate-bot-test") (repository=fea/renovate-bot-test)
DEBUG: Overriding default GitHub endpoint (repository=fea/renovate-bot-test)
       "endpoint": "https://xxx/api/v3/"
  console.log
    
    query($owner: String!, $name: String!) {
      repository(owner: $owner, name: $name) {
        isFork
        isArchived
        nameWithOwner
        hasIssuesEnabled
        autoMergeAllowed
        mergeCommitAllowed
        rebaseMergeAllowed
        squashMergeAllowed
        defaultBranchRef {
          name
          target {
            oid
          }
        }
      }
    }

      at Proxy.initRepo (../../node_modules/renovate/lib/platform/github/index.ts:233:5)

  console.log
    {
      errors: [
        {
          path: [Array],
          extensions: [Object],
          locations: [Array],
          message: "Field 'autoMergeAllowed' doesn't exist on type 'Repository'"
        }
      ]
    } res

      at Proxy.initRepo (../../node_modules/renovate/lib/platform/github/index.ts:242:5)

DEBUG: Caught initRepo error (repository=fea/renovate-bot-test)
       "err": {
         "message": "not-found",
         "stack": "Error: not-found\n    at Proxy.initRepo (/xxxx/node_modules/renovate/lib/platform/github/index.ts:246:5)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at getPlatformConfig (/xxxx/node_modules/renovate/lib/workers/repository/init/apis.ts:52:26)\n    at initApis (/xxxx/node_modules/renovate/lib/workers/repository/init/apis.ts:64:12)\n    at initRepo (/xxxx/node_modules/renovate/lib/workers/repository/init/index.ts:30:12)\n    at Object.renovateRepository (/xxxx/node_modules/renovate/lib/workers/repository/index.ts:44:14)\n    at runRenovate (/xxxx/bots/renovate-bot/src/runner.ts:92:3)\n    at /xxxx/bots/renovate-bot/src/basic.integration-test.ts:69:3"
       }
ERROR: Repository is not found (repository=fea/renovate-bot-test)
DEBUG: Repository timing splits (milliseconds) (repository=fea/renovate-bot-test)
       "splits": {},
       "total": 275
DEBUG: http statistics (repository=fea/renovate-bot-test)
       "urls": {"https://xxx/api/graphql (POST)": 1},
       "hostStats": {"xxx": {"requestCount": 1, "requestAvgMs": 136, "queueAvgMs": 2}},
       "totalRequests": 1
 INFO: Repository finished (repository=fea/renovate-bot-test)
       "durationMs": 275
```

@zharinov @rarkins Can you reopen this?

**Comment by viceice** [comment]
@KnisterPeter Where are the `console.log` comes from?

**Comment by KnisterPeter** [comment]
I've added them locally to inspect the query and the result.
Just to prove that the fields are still in there.

**Comment by viceice** [comment]
you should see a debug message on error here:
https://github.com/renovatebot/renovate/blob/6be7e756fcf699bb29d59d437ddecd3a24d32e23/lib/util/http/github.ts#L287

**Comment by KnisterPeter** [comment]
Interesting, since without the console.log statements I only saw this:
```
ERROR: Repository is not found (repository=fea/renovate-bot-test)
```

**Comment by viceice** [comment]
ok, so the api returns a 200 but the body contains errors, thats why we don't see the log message

**Comment by Kesin11** [comment]
I'm also facing this issue when renovate v28.20.0.
I just retry using v29.3.4 and it works correctly.

My environment:

- Self-hosted ( javascript. not docker )
- GitHub Enterprise Server v3.1.8

**Comment by rarkins** [comment]
I think we can now close this
