### ISSUE TITLE
Concurrency issue with Cargo dependencies in the same private repo?

### ISSUE THREAD

**Issue by edude03** [renovatebot/renovate#12612]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

29.3

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

Public cloud version

### Describe the bug

We use cloudsmith to host our cargo private dependencies. When we run renovate it fails with the logs shown in  the debug log section. 

The git error changes, sometimes it says unable to open shallow.lock or something like that. I've seen this issue before in other projects when multiple git processes access the same directory, which seems to be the case here. 

Digging into it, simple git seems to have a parameter for number of git processes, but I've yet to figure out how that can be set via renovates config. 

I haven't made a reproduction repo because as far as I can tell, this will only happen with private repos that have multiple dependencies from that repo. 

### Relevant debug logs

<details><summary>Logs</summary>

```
{"name":"renovate","hostname":"renovate-manual-05-hwwtt","pid":9,"level":40,"logContext":"51anmjh4l","err":{"task":{"commands":["clone","--depth=1","https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6"],"format":"utf-8"},"message":"Cloning into '/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6'...\nerror: could not lock config file /tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6/.git/config: No such file or directory\nfatal: could not set 'core.repositoryformatversion' to '0'\n","stack":"Error: Cloning into '/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6'...\nerror: could not lock config file /tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6/.git/config: No such file or directory\nfatal: could not set 'core.repositoryformatversion' to '0'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)"},"lookupName":"dep1","registryUrl":"https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","msg":"failed cloning git registry","time":"2021-11-09T16:59:09.654Z","v":0}
{"name":"renovate","hostname":"renovate-manual-05-hwwtt","pid":9,"level":40,"logContext":"51anmjh4l","err":{"task":{"commands":["clone","--depth=1","https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6"],"format":"utf-8"},"message":"Cloning into '/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6'...\nerror: could not lock config file /tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6/.git/config: No such file or directory\nfatal: could not set 'core.repositoryformatversion' to '0'\n","stack":"Error: Cloning into '/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6'...\nerror: could not lock config file /tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6/.git/config: No such file or directory\nfatal: could not set 'core.repositoryformatversion' to '0'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)"},"lookupName":"dep2","registryUrl":"https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","msg":"Previous git clone failed, bailing out.","time":"2021-11-09T16:59:09.655Z","v":0}
{"name":"renovate","hostname":"renovate-manual-05-hwwtt","pid":9,"level":40,"logContext":"51anmjh4l","err":{"task":{"commands":["clone","--depth=1","https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6"],"format":"utf-8"},"message":"Cloning into '/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6'...\nerror: could not lock config file /tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6/.git/config: No such file or directory\nfatal: could not set 'core.repositoryformatversion' to '0'\n","stack":"Error: Cloning into '/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6'...\nerror: could not lock config file /tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6/.git/config: No such file or directory\nfatal: could not set 'core.repositoryformatversion' to '0'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)"},"lookupName":"dep3","registryUrl":"https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","msg":"Previous git clone failed, bailing out.","time":"2021-11-09T16:59:09.655Z","v":0}
{"name":"renovate","hostname":"renovate-manual-05-hwwtt","pid":9,"level":40,"logContext":"51anmjh4l","err":{"task":{"commands":["clone","--depth=1","https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6"],"format":"utf-8"},"message":"Cloning into '/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6'...\nerror: could not lock config file /tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6/.git/config: No such file or directory\nfatal: could not set 'core.repositoryformatversion' to '0'\n","stack":"Error: Cloning into '/tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6'...\nerror: could not lock config file /tmp/renovate/cache/__renovate-private-cache/crate-registry-https-dl.cloudsmith.io-0e04ba6/.git/config: No such file or directory\nfatal: could not set 'core.repositoryformatversion' to '0'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)"},"lookupName":"dep4","registryUrl":"https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","msg":"Previous git clone failed, bailing out.","time":"2021-11-09T16:59:09.655Z","v":0}
{"name":"renovate","hostname":"renovate-manual-05-hwwtt","pid":9,"level":20,"logContext":"51anmjh4l","registryUrl":"https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","msg":"Could not fetch registry info","time":"2021-11-09T16:59:09.655Z","v":0}
{"name":"renovate","hostname":"renovate-manual-05-hwwtt","pid":9,"level":20,"logContext":"51anmjh4l","registryUrl":"https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","msg":"Could not fetch registry info","time":"2021-11-09T16:59:09.655Z","v":0}
{"name":"renovate","hostname":"renovate-manual-05-hwwtt","pid":9,"level":20,"logContext":"51anmjh4l","registryUrl":"https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","msg":"Could not fetch registry info","time":"2021-11-09T16:59:09.655Z","v":0}
{"name":"renovate","hostname":"renovate-manual-05-hwwtt","pid":9,"level":20,"logContext":"51anmjh4l","registryUrl":"https://dl.cloudsmith.io/password/mycomapny/ourrepo/cargo/index.git","msg":"Could not fetch registry info","time":"2021-11-09T16:59:09.655Z","v":0}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
crate private repositories uses git, so your guess about concurrency is probably correct. We should see if there's a way to enforce that the cloning is done once, but unless it's a really easy fix it's likely going to have to wait for someone who can reproduce it locally.
