### ISSUE TITLE
Revanote cannot find a preset that actually exists

### ISSUE THREAD

**Issue by chalkygames123** [renovatebot/renovate#12642]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Revanote reports ["Cannot find preset's package"](https://github.com/chalkygames123/front-end-template/issues/265) but it actually [exists](https://github.com/chalkygames123/renovate-config/blob/e34fa733a047f98bcada15b3d9afe2eabafe8973/group:allNonMajorDevDependenciesExceptNodeJs.json). What's wrong?

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "29.6.1"
}
DEBUG: Using localDir: /mnt/renovate/gh/chalkygames123/front-end-template
DEBUG: Repository cache is valid
DEBUG: initRepo("chalkygames123/front-end-template")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: chalkygames123/front-end-template default branch = master
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: Resetting npmrc
DEBUG: detectSemanticCommits()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: Checking cached config file name
DEBUG: Existing config file confirmed
DEBUG: Repo is onboarded
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "github>chalkygames123/renovate-config",
      "github>chalkygames123/renovate-config:group:allNonMajorDependenciesExceptNodeJs",
      ":followTag(@11ty/eleventy, beta)"
    ],
    "packageRules": [
      {
        "matchPackagePatterns": [
          "^browser-sync"
        ],
        "enabled": false
      }
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "github>chalkygames123/renovate-config",
      "github>chalkygames123/renovate-config:group:allNonMajorDependenciesExceptNodeJs",
      ":followTag(@11ty/eleventy, beta)"
    ],
    "packageRules": [
      {
        "matchPackagePatterns": [
          "^browser-sync"
        ],
        "enabled": false
      }
    ]
  }
}
DEBUG: GitHub 404
{
  "url": "https://api.github.com/repos/undefined/contents/default.json"
}
DEBUG: Failed to retrieve default.json from repo
{
  "statusCode": 404,
  "url": "https://api.github.com/repos/undefined/contents/default.json"
}
INFO: Fallback to renovate.json file as a preset is deprecated, please use a default.json file instead.
DEBUG: GitHub 404
{
  "url": "https://api.github.com/repos/undefined/contents/renovate.json"
}
DEBUG: Failed to retrieve renovate.json from repo
{
  "statusCode": 404,
  "url": "https://api.github.com/repos/undefined/contents/renovate.json"
}
DEBUG: Preset fetch error
{
  "preset": "github>chalkygames123/renovate-config:group:allNonMajorDevDependenciesExceptNodeJs",
  "err": {
    "message": "dep not found",
    "stack": "Error: dep not found\n    at fetchJSONFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/github/index.js:31:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async fetchPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/util.js:27:27)\n    at async getPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:204:24)\n    at async resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:270:37)\n    at async Object.resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:306:38)\n    at async mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/merge.js:214:61)\n    at async getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:15:14)\n    at async initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:26:14)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:402:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:646:5"
  }
}
INFO: Throwing preset error
{
  "validationError": "Cannot find preset's package (github>chalkygames123/renovate-config:group:allNonMajorDevDependenciesExceptNodeJs). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself."
}
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (github>chalkygames123/renovate-config:group:allNonMajorDevDependenciesExceptNodeJs). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself.",
    "message": "config-validation",
    "stack": "Error: config-validation\n    at resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:282:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:306:38)\n    at async mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/merge.js:214:61)\n    at async getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:15:14)\n    at async initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:26:14)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:402:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:646:5"
  }
}
DEBUG: raiseConfigWarningIssue()
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, undefined, open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 310 Pull Requests
DEBUG: findPr(renovate/configure, undefined, closed)
DEBUG: ensureIssue(Action Required: Fix Renovate Configuration)
DEBUG: Retrieving issueList
DEBUG: Retrieved 2 issues
DEBUG: Issue is open and up to date - nothing to do
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {},
  "total": 6944
}
DEBUG: http statistics
{
  "urls": {
    "https://api.github.com/graphql (POST)": 2,
    "https://api.github.com/repos/chalkygames123/front-end-template/contents/renovate.json (GET)": 1,
    "https://api.github.com/repos/chalkygames123/front-end-template/issues/265 (GET)": 1,
    "https://api.github.com/repos/chalkygames123/front-end-template/pulls (GET)": 1,
    "https://api.github.com/repos/chalkygames123/renovate-config/contents/default.json (GET)": 1,
    "https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json (GET)": 1,
    "https://api.github.com/repositories/116818623/pulls (GET)": 3
  },
  "hostStats": {
    "api.github.com": {
      "requestCount": 10,
      "requestAvgMs": 732,
      "queueAvgMs": 0
    }
  },
  "totalRequests": 10
}
INFO: Repository finished
{
  "durationMs": 6944
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Use of : in custom preset names doesn't seem to be supported

**Comment by chalkygames123** [comment]
Given that [this PR](https://github.com/chalkygames123/front-end-template/pull/341) has been created, it should have worked before. Do you mean it was not intended to?

**Comment by rarkins** [comment]
It wasn't intended to work before, and was accidentally broken by a refactoring.

**Comment by chalkygames123** [comment]
Okay, I'll update my config accordingly. Thank you! 😊
