### ISSUE TITLE
Repo "not found" on rebase request

### ISSUE THREAD

**Issue by TheDutchCoder** [renovatebot/renovate#12871]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

When asking for a rebase/retry, I get the "not found" error for some reason.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: No dangling containers to remove
INFO: Repository started
{
  "renovateVersion": "29.26.0"
}
DEBUG: Using localDir: /mnt/renovate/gh/creativelayer/creativelayer
DEBUG: Repository cache is valid
DEBUG: initRepo("creativelayer/creativelayer")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: Caught initRepo error
{
  "err": {
    "message": "not-found",
    "stack": "Error: not-found\n    at Proxy.initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/index.js:164:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async getPlatformConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/apis.js:38:28)\n    at async initApis (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/apis.js:47:14)\n    at async initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:25:14)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:43:18)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:423:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:673:5"
  }
}
ERROR: Repository is not found
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {},
  "total": 329
}
DEBUG: http statistics
{
  "urls": {
    "https://api.github.com/graphql (POST)": 1
  },
  "hostStats": {
    "api.github.com": {
      "requestCount": 1,
      "requestAvgMs": 210,
      "queueAvgMs": 0
    }
  },
  "totalRequests": 1
}
INFO: Repository finished
{
  "durationMs": 329
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Does it produce the same result for every rebase request? And works every time for scheduled runs?

**Comment by TheDutchCoder** [comment]
> Does it produce the same result for every rebase request? And works every time for scheduled runs?

Second time around it seems to have worked normally, though it's still marked as "unsuccessful" in Github:
![image](https://user-images.githubusercontent.com/1668207/143774046-1d4a9452-a047-4335-8a02-6dfe7f48c860.png)

The first issue might've just been a network hiccup I assume?
Not sure about the second. Shouldn't it update to be "passing" after it successfully rebased and ran?
