### ISSUE TITLE
git-submodule manager/git-refs datadource fails on Let's Encrypt certs

### ISSUE THREAD

**Issue by nairb774** [renovatebot/renovate#12877]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

It seems like the git-refs datasource, used by the git-submodule manager, fails due to cert issues when the public repository utilizes Let's Encrypt (ISRG X1/R3) certs. A minimal reproduction can be found at: https://github.com/nairb774/cabug where you can find a single submodule pointing at the [Arch User Repository](https://aur.archlinux.org/) which utilizes Let's Encrypt for https.

### Relevant debug logs

<details><summary>Logs</summary>

Copied from https://app.renovatebot.com/dashboard#github/nairb774/cabug/517665622

```
<snip/>
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base"
    ],
    "git-submodules": {
      "enabled": true
    }
  }
}
<snip/>
DEBUG: Matched 1 file(s) for manager git-submodules: .gitmodules
DEBUG: Found git-submodules package files
DEBUG: Found 1 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "master",
  "stats": {
    "managers": {
      "git-submodules": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 1
    }
  }
}
DEBUG: Datasource unknown error
{
  "datasource": "git-refs",
  "lookupName": "https://aur.archlinux.org/conftest.git",
  "err": {
    "task": {
      "commands": [
        "ls-remote",
        "https://aur.archlinux.org/conftest.git"
      ],
      "format": "utf-8"
    },
    "message": "fatal: unable to access 'https://aur.archlinux.org/conftest.git/': server certificate verification failed. CAfile: none CRLfile: none\n",
    "stack": "Error: fatal: unable to access 'https://aur.archlinux.org/conftest.git/': server certificate verification failed. CAfile: none CRLfile: none\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
DEBUG: Failed to look up dependency conftest (conftest)(packageFile=".gitmodules", dependency="conftest")
DEBUG: Package releases lookups complete
{
  "baseBranch": "master"
}
DEBUG: branchifyUpgrades
DEBUG: 0 flattened updates found:
DEBUG: Returning 0 branch(es)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "git-submodules": [
      {
        "packageFile": ".gitmodules",
        "deps": [
          {
            "depName": "conftest",
            "lookupName": "https://aur.archlinux.org/conftest.git",
            "currentValue": "master",
            "currentDigest": "f5fd47d0e61d4e861c2d85522e90ef3a46d78f96",
            "depIndex": 0,
            "updates": [],
            "warnings": [
              {
                "topic": "conftest",
                "message": "Failed to look up dependency conftest"
              }
            ],
            "versioning": "git"
          }
        ],
        "datasource": "git-refs"
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 0 branches:
<snip/>
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
When I run locally, it does not reproduce. This would indicate that it's related to the Ubuntu-based base image we use to run Renovate in the app. I'll keep debugging further.

**Comment by viceice** [comment]
I'm using those certs too and do not have any issues with renovate.

I think @nairb774  is blocking the certificate validation request or the server is missing the intermediate certificate.

He needs to use the chained certificate files for the server, so it can send the intermediate certificate to the client.

**Comment by rarkins** [comment]
@viceice are you using the same type of certs with the hosted app though?

**Comment by viceice** [comment]
no, i'm using our docker image, published manually to ghcr

https://github.com/visualon/docker-images/blob/main/linux/renovate/Dockerfile

I don't need to configure any cert's on renovate, it works out of the box for me

**Comment by viceice** [comment]
so it miust be a difference to the hosted app docker image
