### ISSUE TITLE
forking renovate failures

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#13170]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

I observed that a number of Google repos using Forking Renovate are failing to update due to GitHub fork patch errors. Looking back through logs, it started with a 500 error, and then is followed by non-stop 404 errors.

It doesn't seem like it could be related to any changes we made on the Renovate side, and is most likely a GitHub bug such as corrupted git state during one of their recent outages.. but who knows.

I found that it can be resolved by manually removing the cloned repo. However we prefer not to do that if there's any outstanding PR open, because it would leave it orphaned. If any are urgent, I can do the delete and restart approach if requested.

I'm going to increase logging to double check that the url/sha we're sending is definitely correct, and then raise a ticket with GitHub.

FYI @justinbeckwith @stephaniewang526

### Relevant debug logs

<details><summary>Initial 500 error</summary>

```
{
  "wait": 0,
  "dns": 1,
  "tcp": 8,
  "tls": 11,
  "request": 0,
  "firstByte": 210,
  "download": 0,
  "total": 230
}
},
"message": "Response code 500 (Internal Server Error)",
"stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
"options": {
"headers": {
  "user-agent": "Renovate Bot (GitHub App 2740)",
  "accept": "application/vnd.github.v3+json",
  "authorization": "***********",
  "content-type": "application/json",
  "content-length": "63",
  "accept-encoding": "gzip, deflate, br"
},
"url": "https://api.github.com/repos/renovate-bot/gax-java/git/refs/heads/main",
"hostType": "github",
"username": "",
"password": "",
"method": "PATCH",
"http2": false
},
"response": {
"statusCode": 500,
"statusMessage": "Internal Server Error",
"body": "",
"headers": {
  "server": "GitHub.com",
  "date": "Mon, 29 Nov 2021 18:41:56 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "0",
  "x-oauth-scopes": "delete_repo, repo, user",
  "x-accepted-oauth-scopes": "repo",
  "x-github-media-type": "github.v3; format=json",
  "x-ratelimit-limit": "5000",
  "x-ratelimit-remaining": "4266",
  "x-ratelimit-reset": "1638213582",
  "x-ratelimit-used": "734",
  "x-ratelimit-resource": "core",
  "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
  "access-control-allow-origin": "*",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "content-security-policy": "default-src 'none'",
  "vary": "Accept-Encoding, Accept, X-Requested-With",
  "x-github-request-id": "DD82:85AF:1075CA8:114DD17:61A51EF3",
  "connection": "close"
},
"httpVersion": "1.1"
}
},
"msg": "GitHub failure: 5xx",
"time": "2021-11-29T18:41:56.117Z"
}
```

</details>

<details><summary>Subsequent 404 errors</summary>

```
{
  "level": 40,
  "err": {
    "name": "HTTPError",
    "code": "ERR_NON_2XX_3XX_RESPONSE",
    "timings": {
      "start": 1638217304228,
      "socket": 1638217304228,
      "lookup": 1638217304228,
      "connect": 1638217304237,
      "secureConnect": 1638217304247,
      "upload": 1638217304247,
      "response": 1638217304445,
      "end": 1638217304446,
      "phases": {
        "wait": 0,
        "dns": 0,
        "tcp": 9,
        "tls": 10,
        "request": 0,
        "firstByte": 198,
        "download": 1,
        "total": 218
      }
    },
    "message": "Response code 404 (Not Found)",
    "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept": "application/vnd.github.v3+json",
        "authorization": "***********",
        "content-type": "application/json",
        "content-length": "63",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://api.github.com/repos/renovate-bot/gax-java/git/refs/heads/main",
      "hostType": "github",
      "username": "",
      "password": "",
      "method": "PATCH",
      "http2": false
    },
    "response": {
      "statusCode": 404,
      "statusMessage": "Not Found",
      "body": {
        "message": "Not Found",
        "documentation_url": "https://docs.github.com/rest/reference/git#update-a-reference"
      },
      "headers": {
        "server": "GitHub.com",
        "date": "Mon, 29 Nov 2021 20:21:44 GMT",
        "content-type": "application/json; charset=utf-8",
        "transfer-encoding": "chunked",
        "x-oauth-scopes": "delete_repo, repo, user",
        "x-accepted-oauth-scopes": "repo",
        "x-github-media-type": "github.v3; format=json",
        "x-ratelimit-limit": "5000",
        "x-ratelimit-remaining": "4886",
        "x-ratelimit-reset": "1638220802",
        "x-ratelimit-used": "114",
        "x-ratelimit-resource": "core",
        "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
        "access-control-allow-origin": "*",
        "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
        "x-frame-options": "deny",
        "x-content-type-options": "nosniff",
        "x-xss-protection": "0",
        "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
        "content-security-policy": "default-src 'none'",
        "vary": "Accept-Encoding, Accept, X-Requested-With",
        "content-encoding": "gzip",
        "x-github-request-id": "A6BE:9CAE:A83BA:ADD32:61A53658",
        "connection": "close"
      },
      "httpVersion": "1.1"
    }
  },
  "msg": "Error updating fork from upstream - cannot continue",
  "time": "2021-11-29T20:21:44.449Z"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
I have filed a bug, but I'm not sure if it can be expected to be diagnosed or fixed quickly.

Known affected repos, which I'm not deleting due to open PRs, include:

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory
https://github.com/GoogleCloudPlatform/python-docs-samples
https://github.com/googleapis/gapic-generator-go
https://github.com/metacontroller/metacontroller
https://github.com/googleapis/google-cloudevents

**Comment by JustinBeckwith** [comment]
Thank you for noticing and digging into this!  Honestly, deleting the forks and re-sending PRs isn't a big deal here.  Especially if it helps you debug what's happening :)

**Comment by rarkins** [comment]
I'm trying to remember what the problem was last time I deleted forks. IIRC it means open PRs are simply closed - which means "ignored" - and not recreated. But if I log in with the bot's credentials and rename+close them first then it should work, if you're ok with that?

**Comment by JustinBeckwith** [comment]
Tell you what - I don't want to make that decision unilaterally, and everyone at Google is off today through the weekend :) I am going to plus in @bcoe and @danoscarmike as FYI.

**Comment by rarkins** [comment]
FYI I found that GitHub's web UI allowed me to manually resolve those repos, so at this moment I'm not aware of any still outstanding
