### ISSUE TITLE
Gradle extraction failed because of configuration cache

### ISSUE THREAD

**Issue by eygraber** [renovatebot/renovate#13478]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Describe the bug

I have `"deepExtract": true` in my config, and got an error related to Gradle's configuration cache (which I have enabled).

As a quick fix, could `--no-configuration-cache` be used to avoid the error?

This is happening in https://github.com/eygraber/android-date-input

### Relevant debug logs

<details><summary>Logs</summary>

```
{
  "errMessage": "Command failed: docker run --rm --name=renovate_java --label=renovate_child -v \"/mnt/renovate/gh/eygraber/android-date-input\":\"/mnt/renovate/gh/eygraber/android-date-input\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/eygraber/android-date-input\" docker.io/renovate/java:16.0.2 bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nConfiguration cache state could not be cached: field 'actions' from type 'org.gradle.api.DefaultTask': error writing value of type 'java.util.ArrayList'\n> Configuration cache state could not be cached: field 'closure' from type 'org.gradle.api.internal.AbstractTask$ClosureTaskAction': error writing value of type 'renovate_plugin_a45naq30jar8u06fmsoeoa83s$_run_closure1$_closure3$_closure4'\n   > Configuration cache state could not be cached: field 'output' from type 'renovate_plugin_a45naq30jar8u06fmsoeoa83s$_run_closure1$_closure3$_closure4': error writing value of type 'groovy.lang.Reference'\n      > Configuration cache state could not be cached: field 'value' from type 'groovy.lang.Reference': error writing value of type 'java.util.concurrent.ConcurrentLinkedQueue'\n         > Unable to make private void java.util.concurrent.ConcurrentLinkedQueue.writeObject(java.io.ObjectOutputStream) throws java.io.IOException accessible: module java.base does not \"opens java.util.concurrent\" to unnamed module @1805dff6\n\n* Try:\n> Run with --stacktrace option to get the stack trace.\n> Run with --info or --debug option to get more log output.\n> Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 6m 47s\n"
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
We are planning to remove Gradle deep functionality in a future major release, perhaps the next one. Have you tested using the regular gradle, and if so then what led you to switch?

**Comment by eygraber** [comment]
I haven't tested regular Gradle yet. I saw the option to use deepExtract and thought it was better. I'll give it a try.

**Comment by viceice** [comment]
@HonkingGoose can you suggest a docs change to mark that feature as deprecated, so users see it?

**Comment by eygraber** [comment]
I removed `"deepExtract": true` from my config, and it mostly worked.

Now I get the following error:

```
DEBUG: Setting git author email(branch="renovate/io.kotest")
{
  "gitAuthorEmail": "<redacted>"
}
DEBUG: Unknown error committing files(branch="renovate/io.kotest")
{
  "err": {
    "task": {
      "commands": [
        "commit",
        "-m",
        "Update dependency io.kotest:kotest-assertions-core to v5.0.3",
        "--no-verify"
      ],
      "format": "utf-8",
      "parser": "[function]"
    },
    "message": "Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <redacted>) not allowed\n",
    "stack": "Error: Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <redacted>) not allowed\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
WARN: Error updating branch(branch="renovate/io.kotest")
{
  "err": {
    "task": {
      "commands": [
        "commit",
        "-m",
        "Update dependency io.kotest:kotest-assertions-core to v5.0.3",
        "--no-verify"
      ],
      "format": "utf-8",
      "parser": "[function]"
    },
    "message": "Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <redacted>) not allowed\n",
    "stack": "Error: Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <redacted>) not allowed\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
```

I do have `gitAuthor` set to an email in my config.
