### ISSUE TITLE
Renovate not correctly handling Terraform range constraints

### ISSUE THREAD

**Issue by ocofaigh** [renovatebot/renovate#13491]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.22.1

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

2.22.25

### Describe the bug

According to the documentation [here](https://docs.renovatebot.com/modules/manager/terraform/), the following Terraform range constraint is supported: 
```
terraform {
  required_version = ">= 1.0.0, < 1.1.3"
}
```

However when I run renovate against this, it always removes the starting version in the range (aka `>= 1.0.0`). So what we see is PR being created with the following update: `>= 1.0.0, < 1.1.0` -> `< 1.1.4` which is not what I want. This update would mean that versions below 1.0.0 are allowed, and that is not what I want.
I would expect the update to be like this: `>= 1.0.0, < 1.1.0` -> `>= 1.0.0, < 1.1.4`

I have tried updating the `rangeStrategy` value to `auto`,  `pin`, `bump`, `replace`, `widen`, and `update-lockfile` but all have the same affect. 

Is this a bug, or is there some configuration possible to achieve this? 

Minimum reproduction repo: https://github.com/ocofaigh/tf-temp

### Relevant debug logs

```
> dependency-updater@1.0.0 renovate
> renovate

DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /usr/src/app/config.js
 WARN: Config needs migrating
       "originalConfig": {
         "repositories": ["OCOFAIGH/temp-tf"],
         "token": "***********",
         "endpoint": "https://github.ibm.com/api/v3",
         "platform": "github",
         "logFileLevel": "debug",
         "logLevel": "debug",
         "logFile": "renovate/renovate.log",
         "trustLevel": "high",
         "hostRules": []
       },
       "migratedConfig": {
         "repositories": ["OCOFAIGH/temp-tf"],
         "token": "***********",
         "endpoint": "https://github.ibm.com/api/v3",
         "platform": "github",
         "logFileLevel": "debug",
         "logLevel": "debug",
         "logFile": "renovate/renovate.log",
         "allowCustomCrateRegistries": true,
         "allowScripts": true,
         "exposeAllEnv": true,
         "hostRules": []
       }
DEBUG: Enabling debug logging to renovate/renovate.log
DEBUG: File config
       "config": {
         "repositories": ["OCOFAIGH/temp-tf"],
         "token": "***********",
         "endpoint": "https://github.ibm.com/api/v3",
         "platform": "github",
         "logFileLevel": "debug",
         "logLevel": "debug",
         "logFile": "renovate/renovate.log",
         "allowCustomCrateRegistries": true,
         "allowScripts": true,
         "exposeAllEnv": true,
         "hostRules": []
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "repositories": ["OCOFAIGH/temp-tf"],
         "token": "***********",
         "endpoint": "https://github.ibm.com/api/v3",
         "platform": "github",
         "logFileLevel": "debug",
         "logLevel": "debug",
         "logFile": "renovate/renovate.log",
         "allowCustomCrateRegistries": true,
         "allowScripts": true,
         "exposeAllEnv": true,
         "hostRules": []
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Found valid git version: 2.34.1
DEBUG: Platform config
       "platformConfig": {
         "hostType": "github",
         "endpoint": "https://github.ibm.com/api/v3/",
         "isGhe": true,
         "gheVersion": "2.22.25"
       },
       "renovateUsername": "OCOFAIGH"
DEBUG: Using platform gitAuthor: CONALL O'COFAIGH <OCOFAIGH@ie.ibm.com>
DEBUG: Adding token authentication for github.ibm.com to hostRules
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for github.ibm.com to hostRules
 INFO: Repository started (repository=OCOFAIGH/temp-tf)
       "renovateVersion": "31.22.1"
DEBUG: Using localDir: /tmp/renovate/repos/github/OCOFAIGH/temp-tf (repository=OCOFAIGH/temp-tf)
DEBUG: initRepo("OCOFAIGH/temp-tf") (repository=OCOFAIGH/temp-tf)
DEBUG: Overriding default GitHub endpoint (repository=OCOFAIGH/temp-tf)
       "endpoint": "https://github.ibm.com/api/v3/"
DEBUG: OCOFAIGH/temp-tf default branch = master (repository=OCOFAIGH/temp-tf)
DEBUG: Using personal access token for git init (repository=OCOFAIGH/temp-tf)
DEBUG: resetMemCache() (repository=OCOFAIGH/temp-tf)
DEBUG: Resetting npmrc (repository=OCOFAIGH/temp-tf)
DEBUG: detectSemanticCommits() (repository=OCOFAIGH/temp-tf)
DEBUG: Initializing git repository into /tmp/renovate/repos/github/OCOFAIGH/temp-tf (repository=OCOFAIGH/temp-tf)
DEBUG: Performing blobless clone (repository=OCOFAIGH/temp-tf)
DEBUG: git clone completed (repository=OCOFAIGH/temp-tf)
       "durationMs": 1710
DEBUG: latest repository commit (repository=OCOFAIGH/temp-tf)
       "latestCommit": {
         "hash": "61dd73530da10d4ca4df8c8ed861622498fe4a83",
         "date": "2022-01-11T12:32:23+00:00",
         "message": "Update version.tf",
         "refs": "HEAD -> master, origin/master, origin/HEAD",
         "body": "",
         "author_name": "CONALL O'COFAIGH",
         "author_email": "OCOFAIGH@ie.ibm.com"
       }
DEBUG: getCommitMessages (repository=OCOFAIGH/temp-tf)
DEBUG: Semantic commits detection: unknown (repository=OCOFAIGH/temp-tf)
DEBUG: No semantic commits detected (repository=OCOFAIGH/temp-tf)
DEBUG: checkOnboarding() (repository=OCOFAIGH/temp-tf)
DEBUG: isOnboarded() (repository=OCOFAIGH/temp-tf)
DEBUG: findFile(renovate.json) (repository=OCOFAIGH/temp-tf)
DEBUG: Config file exists (repository=OCOFAIGH/temp-tf)
       "fileName": "renovate.json"
DEBUG: Retrieving issueList (repository=OCOFAIGH/temp-tf)
DEBUG: Retrieved 0 issues (repository=OCOFAIGH/temp-tf)
DEBUG: Repo is onboarded (repository=OCOFAIGH/temp-tf)
DEBUG: Found renovate.json config file (repository=OCOFAIGH/temp-tf)
DEBUG: Repository config (repository=OCOFAIGH/temp-tf)
       "fileName": "renovate.json",
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "force": {"recreateClosed": true},
         "packageRules": [
           {
             "matchManagers": ["terraform"],
             "matchDepTypes": ["required_provider"],
             "rangeStrategy": "replace"
           }
         ]
       }
DEBUG: migrateAndValidate() (repository=OCOFAIGH/temp-tf)
DEBUG: No config migration necessary (repository=OCOFAIGH/temp-tf)
DEBUG: massaged config (repository=OCOFAIGH/temp-tf)
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "force": {"recreateClosed": true},
         "packageRules": [
           {
             "matchManagers": ["terraform"],
             "matchDepTypes": ["required_provider"],
             "rangeStrategy": "replace"
           }
         ]
       }
DEBUG: migrated config (repository=OCOFAIGH/temp-tf)
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "force": {"recreateClosed": true},
         "packageRules": [
           {
             "matchManagers": ["terraform"],
             "matchDepTypes": ["required_provider"],
             "rangeStrategy": "replace"
           }
         ]
       }
DEBUG: Found repo ignorePaths (repository=OCOFAIGH/temp-tf)
       "ignorePaths": ["**/node_modules/**", "**/bower_components/**"]
DEBUG: No vulnerability alerts found (repository=OCOFAIGH/temp-tf)
DEBUG: No vulnerability alerts found (repository=OCOFAIGH/temp-tf)
DEBUG: No baseBranches (repository=OCOFAIGH/temp-tf)
DEBUG: extract() (repository=OCOFAIGH/temp-tf)
DEBUG: Setting current branch to master (repository=OCOFAIGH/temp-tf)
DEBUG: latest commit (repository=OCOFAIGH/temp-tf)
       "branchName": "master",
       "latestCommitDate": "2022-01-11T12:32:23+00:00"
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)requirements\.ya?ml$ for manager ansible-galaxy (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)galaxy\.ya?ml$ for manager ansible-galaxy (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: azure.*pipelines?.*\.ya?ml$ for manager azure-pipelines (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)batect(-bundle)?\.yml$ for manager batect (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)batect$ for manager batect-wrapper (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)WORKSPACE(|\.bazel)$ for manager bazel (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.bzl$ for manager bazel (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)\.?bitbucket-pipelines\.ya?ml$ for manager bitbucket-pipelines (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)Gemfile$ for manager bundler (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.cake$ for manager cake (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)cloudbuild.ya?ml for manager cloudbuild (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)Podfile$ for manager cocoapods (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/).gitmodules$ for manager git-submodules (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^workflow-templates|\.github\/workflows)\/[^/]+\.ya?ml$ for manager github-actions (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|\/)action\.ya?ml$ for manager github-actions (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.gitlab-ci\.yml$ for manager gitlabci-include (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)go.mod$ for manager gomod (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|\/)gradle\.properties$ for manager gradle (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|\/)gradle\/.+\.toml$ for manager gradle (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.versions\.toml$ for manager gradle (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)requirements\.yaml$ for manager helm-requirements (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)values.yaml$ for manager helm-values (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)helmfile.yaml$ for manager helmfile (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)Chart.yaml$ for manager helmv3 (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.html?$ for manager html (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)plugins\.(txt|ya?ml)$ for manager jenkins (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)jsonnetfile.json$ for manager jsonnet-bundler (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)kustomization\.yaml for manager kustomize (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.pom\.xml$ for manager maven (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)package.js$ for manager meteor (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)mix\.exs$ for manager mix (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/).node-version$ for manager nodenv (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)package.json$ for manager npm (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.(?:props|targets)$ for manager nuget (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|\/)dotnet-tools\.json$ for manager nuget (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|\/)global\.json$ for manager nuget (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)\.nvmrc$ for manager nvm (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)([\w-]*)requirements\.(txt|pip)$ for manager pip_requirements (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)Pipfile$ for manager pipenv (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)\.pre-commit-config\.yaml$ for manager pre-commit (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/).python-version$ for manager pyenv (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.sbt$ for manager sbt (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)setup\.cfg$ for manager setup-cfg (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)Package\.swift for manager swift (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: \.tf$ for manager terraform (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)\.terraform-version$ for manager terraform-version (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)terragrunt\.hcl$ for manager terragrunt (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: (^|/)\.terragrunt-version$ for manager terragrunt-version (repository=OCOFAIGH/temp-tf)
DEBUG: Using file match: ^.travis.yml$ for manager travis (repository=OCOFAIGH/temp-tf)
DEBUG: Matched 1 file(s) for manager terraform: version.tf (repository=OCOFAIGH/temp-tf)
DEBUG: Found terraform package files (repository=OCOFAIGH/temp-tf)
DEBUG: Found 1 package file(s) (repository=OCOFAIGH/temp-tf)
 INFO: Dependency extraction complete (repository=OCOFAIGH/temp-tf)
       "baseBranch": "master",
       "stats": {
         "managers": {"terraform": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }
DEBUG: GitHub failure: rate limit (repository=OCOFAIGH/temp-tf)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1641904358365,
           "socket": 1641904358365,
           "lookup": 1641904358367,
           "connect": 1641904358408,
           "secureConnect": 1641904358492,
           "upload": 1641904358493,
           "response": 1641904358533,
           "end": 1641904358534,
           "phases": {
             "wait": 0,
             "dns": 2,
             "tcp": 41,
             "tls": 84,
             "request": 1,
             "firstByte": 40,
             "download": 1,
             "total": 169
           }
         },
         "message": "Response code 403 (rate limit exceeded)",
         "stack": "HTTPError: Response code 403 (rate limit exceeded)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/31.22.1 (https://github.com/renovatebot/renovate)",
             "accept": "application/vnd.github.v3+json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://api.github.com/repos/hashicorp/terraform/releases?per_page=100",
           "hostType": "github-releases",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 403,
           "statusMessage": "rate limit exceeded",
           "body": {
             "message": "API rate limit exceeded for 80.111.104.69. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
             "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
           },
           "headers": {
             "date": "Tue, 11 Jan 2022 12:32:40 GMT",
             "server": "Varnish",
             "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
             "x-content-type-options": "nosniff",
             "x-frame-options": "deny",
             "x-xss-protection": "1; mode=block",
             "content-security-policy": "default-src 'none'; style-src 'unsafe-inline'",
             "access-control-allow-origin": "*",
             "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
             "content-type": "application/json; charset=utf-8",
             "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
             "x-github-media-type": "github.v3; format=json",
             "x-ratelimit-limit": "60",
             "x-ratelimit-remaining": "0",
             "x-ratelimit-reset": "1641905871",
             "x-ratelimit-resource": "core",
             "x-ratelimit-used": "60",
             "content-length": "279",
             "x-github-request-id": "D111:B14F:AE2458:B36B69:61DD78E8",
             "connection": "close"
           },
           "httpVersion": "1.1"
         }
       }
DEBUG: Package releases lookups complete (repository=OCOFAIGH/temp-tf)
       "baseBranch": "master"
DEBUG: branchifyUpgrades (repository=OCOFAIGH/temp-tf)
DEBUG: 1 flattened updates found: hashicorp/terraform (repository=OCOFAIGH/temp-tf)
DEBUG: Returning 1 branch(es) (repository=OCOFAIGH/temp-tf)
DEBUG: Fetching changelog: https://github.com/hashicorp/terraform (1.1.2 -> 1.1.3) (repository=OCOFAIGH/temp-tf)
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=OCOFAIGH/temp-tf)
       "manager": "terraform",
       "depName": "hashicorp/terraform",
       "sourceUrl": "https://github.com/hashicorp/terraform"
DEBUG: config.repoIsOnboarded=true (repository=OCOFAIGH/temp-tf)
DEBUG: packageFiles with updates (repository=OCOFAIGH/temp-tf)
       "config": {
         "terraform": [
           {
             "packageFile": "version.tf",
             "deps": [
               {
                 "currentValue": ">= 1.0.0, < 1.1.3",
                 "lineNumber": 1,
                 "depType": "required_version",
                 "datasource": "github-tags",
                 "depName": "hashicorp/terraform",
                 "extractVersion": "v(?<version>.*)$",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "1.1.3",
                     "newValue": "< 1.1.4",
                     "newMajor": 1,
                     "newMinor": 1,
                     "updateType": "patch",
                     "isRange": true,
                     "branchName": "renovate/hashicorp-terraform-1.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "hashicorp",
                 "sourceUrl": "https://github.com/hashicorp/terraform",
                 "currentVersion": "1.1.2",
                 "isSingleVersion": false
               }
             ]
           }
         ]
       }
DEBUG: processRepo() (repository=OCOFAIGH/temp-tf)
DEBUG: Processing 1 branch: renovate/hashicorp-terraform-1.x (repository=OCOFAIGH/temp-tf)
DEBUG: Calculated maximum PRs remaining this run (repository=OCOFAIGH/temp-tf)
       "prsRemaining": 99
DEBUG: PullRequests limit = 99 (repository=OCOFAIGH/temp-tf)
DEBUG: Calculated maximum branches remaining this run (repository=OCOFAIGH/temp-tf)
       "branchesRemaining": 99
DEBUG: Branches limit = 99 (repository=OCOFAIGH/temp-tf)
DEBUG: Setting current branch to master (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: latest commit (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
       "branchName": "master",
       "latestCommitDate": "2022-01-11T12:32:23+00:00"
DEBUG: getBranchPr(renovate/hashicorp-terraform-1.x) (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: findPr(renovate/hashicorp-terraform-1.x, undefined, open) (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Retrieving PR list (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Retrieved 9 Pull Requests (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: findPr(renovate/hashicorp-terraform-1.x, undefined, closed) (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Found PR #9 (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Found autoclosed PR for branch (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
       "autoclosedPr": {
         "number": 9,
         "sourceBranch": "renovate/hashicorp-terraform-1.x",
         "sha": "2ef57b625245b6fc12f5c26b2c4ae5e9ee9c1a77",
         "title": "Update Terraform hashicorp/terraform to < 1.1.4 - autoclosed",
         "state": "closed",
         "createdAt": "2022-01-11T12:29:39Z",
         "closedAt": "2022-01-11T12:31:50Z",
         "sourceRepo": "OCOFAIGH/temp-tf"
       }
DEBUG: Recreated autoclosed branch (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
       "branchName": "renovate/hashicorp-terraform-1.x",
       "sha": "2ef57b625245b6fc12f5c26b2c4ae5e9ee9c1a77"
 INFO: Successfully reopened autoclosed PR (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
       "branchName": "renovate/hashicorp-terraform-1.x",
       "title": "Update Terraform hashicorp/terraform to < 1.1.4",
       "number": 9
DEBUG: Returning from graphql open PR list (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: branchExists=false (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: dependencyDashboardCheck=undefined (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: PR rebase requested=false (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Checking schedule(at any time, null) (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: No schedule defined (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Branch needs creating (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Using reuseExistingBranch: false (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Starting search at index 34 (repository=OCOFAIGH/temp-tf, packageFile=version.tf, branch=renovate/hashicorp-terraform-1.x)
       "depName": "hashicorp/terraform"
DEBUG: Found match at index 34 (repository=OCOFAIGH/temp-tf, packageFile=version.tf, branch=renovate/hashicorp-terraform-1.x)
       "depName": "hashicorp/terraform"
DEBUG: Contents updated (repository=OCOFAIGH/temp-tf, packageFile=version.tf, branch=renovate/hashicorp-terraform-1.x)
       "depName": "hashicorp/terraform"
DEBUG: terraform.updateArtifacts(version.tf) (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: No .terraform.lock.hcl found (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Updated 1 package files (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: No updated lock files in branch (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: 1 file(s) to commit (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Committing files to branch renovate/hashicorp-terraform-1.x (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Setting git author name (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
       "gitAuthorName": "CONALL O'COFAIGH"
DEBUG: Setting git author email (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
       "gitAuthorEmail": "OCOFAIGH@ie.ibm.com"
DEBUG: git commit (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/hashicorp-terraform-1.x",
         "commit": "45f27fa",
         "root": false,
         "summary": {"changes": 1, "insertions": 1, "deletions": 1}
       }
 INFO: Branch update was rejected because local copy is not up-to-date. (repository=OCOFAIGH/temp-tf, branch=renovate/hashicorp-terraform-1.x)
DEBUG: Closing Dependency Dashboard (repository=OCOFAIGH/temp-tf)
DEBUG: Removing any stale branches (repository=OCOFAIGH/temp-tf)
DEBUG: config.repoIsOnboarded=true (repository=OCOFAIGH/temp-tf)
DEBUG: No renovate branches found (repository=OCOFAIGH/temp-tf)
DEBUG: Repository timing splits (milliseconds) (repository=OCOFAIGH/temp-tf)
       "splits": {"init": 3959, "extract": 384, "lookup": 898, "update": 4652},
       "total": 9915
DEBUG: http statistics (repository=OCOFAIGH/temp-tf)
       "urls": {
         "https://api.github.com/repos/hashicorp/terraform/tags (GET)": 1,
         "https://api.github.com/repositories/17728164/tags (GET)": 2,
         "https://github.ibm.com/api/graphql (POST)": 4,
         "https://github.ibm.com/api/v3/repos/OCOFAIGH/temp-tf/git/refs (POST)": 1,
         "https://github.ibm.com/api/v3/repos/OCOFAIGH/temp-tf/pulls (GET)": 1,
         "https://github.ibm.com/api/v3/repos/OCOFAIGH/temp-tf/pulls/9 (PATCH)": 1
       },
       "hostStats": {
         "api.github.com": {"requestCount": 3, "requestAvgMs": 289, "queueAvgMs": 0},
         "github.ibm.com": {"requestCount": 7, "requestAvgMs": 671, "queueAvgMs": 0}
       },
       "totalRequests": 10
 INFO: Repository finished (repository=OCOFAIGH/temp-tf)
       "durationMs": 9915
DEBUG: Renovate exiting
```

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment]
Reproduction isn't accessable, please copy to github.com

**Comment by rarkins** [comment]
Reproduction forked to https://github.com/renovate-reproductions/13491

**Comment by ocofaigh** [comment]
Thank you @hasanwhitesource - this works well!
