### ISSUE TITLE
Renovate display creds upon failure

### ISSUE THREAD

**Issue by renan-alm** [renovatebot/renovate#13807]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

31.48.0

### Describe the bug

Hi team,

This Renovate instance is connecting to an on-prem BitBucket using password authentication.

Upon (intermittent) failure to reach the repository, the credentials are exposed on the logs.

See also: https://github.com/renovatebot/renovate/discussions/13374

### Relevant debug logs

<details><summary>Logs</summary>

```

[2022-01-12T12:16:53.454Z] ERROR: Repository has unknown error (repository=renan-repo)
[2022-01-12T12:16:53.454Z]        "err": {
[2022-01-12T12:16:53.454Z]          "task": {
[2022-01-12T12:16:53.454Z]            "commands": [
[2022-01-12T12:16:53.454Z]              "ls-remote",
[2022-01-12T12:16:53.454Z]              "--heads",
[2022-01-12T12:16:53.454Z]              "https://renovatebot:SECRET_PWD@renan.net/repo/renan-repo.git"
[2022-01-12T12:16:53.454Z]            ],
[2022-01-12T12:16:53.454Z]            "format": "utf-8",
[2022-01-12T12:16:53.454Z]            "parser": "[function]"
[2022-01-12T12:16:53.454Z]          },
[2022-01-12T12:16:53.455Z]          "message": "fatal: unable to access 'https://renan.net/repo/renan-repo.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.\n",
[2022-01-12T12:16:53.455Z]          "stack": "Error: fatal: unable to access 'https://renan.net/repo/renan-repo.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
[2022-01-12T12:16:53.455Z]        }
[2022-01-12T12:16:53.455Z] DEBUG: Unknown res (repository=cd/renan-repo)
[2022-01-12T12:16:53.455Z]        "res": "unknown-error"
[2022-01-12T12:16:53.455Z] DEBUG: Repository timing splits (milliseconds) (repository=cd/renan-repo)
[2022-01-12T12:16:53.455Z]        "splits": {},
[2022-01-12T12:16:53.455Z]        "total": 20300
[2022-01-12T12:16:53.455Z] DEBUG: http statistics (repository=cd/renan-repo)
[2022-01-12T12:16:53.455Z]        "urls": {
[2022-01-12T12:16:53.455Z]          "https://renan.net/./rest/api/1.0/projects/cd/repos/renan-repo (GET)": 1,
[2022-01-12T12:16:53.455Z]          "https://renan.net/./rest/api/1.0/projects/cd/repos/renan-repo/branches/default (GET)": 1
[2022-01-12T12:16:53.455Z]        },
[2022-01-12T12:16:53.455Z]        "hostStats": {
[2022-01-12T12:16:53.455Z]          "renan.net": {
[2022-01-12T12:16:53.455Z]            "requestCount": 2,
[2022-01-12T12:16:53.455Z]            "requestAvgMs": 61,
[2022-01-12T12:16:53.455Z]            "queueAvgMs": 0
[2022-01-12T12:16:53.455Z]          }
[2022-01-12T12:16:53.455Z]        },
[2022-01-12T12:16:53.455Z]        "totalRequests": 2
[2022-01-12T12:16:53.455Z]  INFO: Repository finished (repository=renan-repo)
[2022-01-12T12:16:53.455Z]        "durationMs": 20300
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Please describe here how you are configuring/running the bot, e.g. CLI params you pass, env params you use, and any config file such as `config.js`

**Comment by renan-alm** [comment]
Full `config.js` file below:

```
module.exports = {
    "onboardingPrTitle": "[skip ci] Configure Renovate",
    "onboardingCommitMessage": "[skip ci] Add renovate.json",
    "autodiscover": true,
    "autodiscoverFilter": "{cd/*}",
    "onboardingConfig": {
        "extends": [ "local>cd/renovate-cd-config" ]
    },
    "baseDir": "/cache",
    "repositoryCache": "enabled"
}
```

**Comment by rarkins** [comment]
I can't reproduce this, so doing some code inspection.

Renovate clears sanitization values before each repo.

Renovate adds sanitization values in the following circumstances:
- Any decrypted string (repo init)
- When `secrets` values are applied to config (repo init)
- In npm datasource logic (npmrc handling)
- Bundler artifacts
- Azure repo init
- Whenever adding `hostRules`:
  * After call to `initPlatform`
  * Before calling `repositoryWorker.renovateRepository()`
  * After resolving repo config

So for this case, the `password` would need to be part of `hostRules` in order to be sanitized. It looks like it is from the platform code..

@renan-alm can you provide the full debug log for a run where this occurs? I want to look for hostRules debug messages.

**Comment by renan-alm** [comment]
The error is intermittent and I missed saving the logs from last time, it should occur in the next few days. I will post it here as soon as I have it.

**Comment by renan-alm** [comment]
Uploading the two full logs from Jan28 and Feb1.

I noticed something new, only the logs from Jan28 which does a `ls-remote` display the creds, not the one which does `push` (Feb1).

[consoleText_Renovate_Jan28.txt](https://github.com/renovatebot/renovate/files/7978260/consoleText_Renovate_Jan28.txt)
[consoleText_Renovate_Feb1.txt](https://github.com/renovatebot/renovate/files/7978263/consoleText_Renovate_Feb1.txt)

**Comment by rarkins** [comment]
Thanks. I think this is the relevant part:

```
[2022-01-28T08:28:46.507Z] DEBUG: Clearing hostRules
[2022-01-28T08:28:46.507Z] DEBUG: Adding token authentication for github.com to hostRules
[2022-01-28T08:28:46.507Z] DEBUG: Adding password authentication for scm.prod..se to hostRules
[2022-01-28T08:28:46.507Z]  INFO: Repository started (repository=tp/millistream-mdf-client-lib)
[2022-01-28T08:28:46.507Z]        "renovateVersion": "31.48.0"
[2022-01-28T08:28:46.507Z] DEBUG: Using localDir: /cache/repos/bitbucket-server/tp/millistream-mdf-client-lib (repository=tp/millistream-mdf-client-lib)
[2022-01-28T08:28:46.507Z] DEBUG: Repository cache is valid (repository=tp/millistream-mdf-client-lib)
[2022-01-28T08:28:46.507Z] DEBUG: initRepo("{
[2022-01-28T08:28:46.507Z]          "repository": "tp/millistream-mdf-client-lib"
[2022-01-28T08:28:46.507Z]        }") (repository=tp/millistream-mdf-client-lib)
[2022-01-28T08:28:46.763Z] DEBUG: tp/millistream-mdf-client-lib owner = TP (repository=tp/millistream-mdf-client-lib)
[2022-01-28T08:29:08.693Z] DEBUG: git error (repository=tp/millistream-mdf-client-lib)
[2022-01-28T08:29:08.693Z]        "err": {
[2022-01-28T08:29:08.693Z]          "task": {
[2022-01-28T08:29:08.693Z]            "commands": [
[2022-01-28T08:29:08.693Z]              "ls-remote",
[2022-01-28T08:29:08.693Z]              "--heads",
[2022-01-28T08:29:08.693Z]              "https://renovatebot:ODI0Nj.....@renan.net/scm/tp/millistream-mdf-client-lib.git"
[2022-01-28T08:29:08.693Z]            ],
[2022-01-28T08:29:08.693Z]            "format": "utf-8",
[2022-01-28T08:29:08.693Z]            "parser": "[function]"
[2022-01-28T08:29:08.693Z]          },
[2022-01-28T08:29:08.693Z]          "message": "fatal: unable to access 'https://renan.net/scm/tp/millistream-mdf-client-lib.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.\n",
[2022-01-28T08:29:08.693Z]          "stack": "Error: fatal: unable to access 'https://renan.net/scm/tp/millistream-mdf-client-lib.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
[2022-01-28T08:29:08.693Z]        }
```

Lines 2 and 3 indicate us adding a token (github.com?) and password auth to our hostRules, and they are not cleared again before the error. So it *seems* like the password should have been added to our sanitizations there, although we can't be 100% sure. The other possibility is that secrets within `err` are not hitting our sanitizations.

**Comment by rarkins** [comment]
I can't reproduce this using unit tests, e.g. the following passes:

```
it('handles nested secrets', () => {
    const err = partial<Error & Record<string, unknown>>({
      task: {
        commands: [
          'ls-remote',
          '--heads',
          'https://renovatebot:helloworld@host.net/scm/to/lib.git',
        ],
        format: 'utf-8',
        parser: '[function]',
      },
    });
    hostRules.clear();
    hostRules.add({
      hostType: 'any',
      username: 'renovatebot',
      password: 'helloworld',
    });
    const sanitized = sanitizeValue({ err, message: 'some message' });
    expect(sanitized).toMatchInlineSnapshot(`
      Object {
        "err": Object {
          "task": Object {
            "commands": Array [
              "ls-remote",
              "--heads",
              "https://renovatebot:**redacted**@host.net/scm/to/lib.git",
            ],
            "format": "utf-8",
            "parser": "[function]",
          },
        },
        "message": "some message",
      }
    `);
    expect(JSON.stringify(sanitized.err.task.commands)).not.toInclude(
      'helloworld'
    );
  });
```

**Comment by rarkins** [comment]
I got it to work once, but still no reproduction:

```
DEBUG: Converting git error to ExternalHostError (repository=renovate-tests/npm85)
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--heads",
             "https://**redacted**1@github.com/renovate-tests/npm85.git"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n",
         "stack": "Error: remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n\n    at Object.action (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/plugin-store.ts:24:29)\n    at /Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/renovatebot/renovate/node_modules/simple-git/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
 WARN: Host error (repository=renovate-tests/npm85)
       "hostType": "git",
       "lookupName": undefined,
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--heads",
             "https://**redacted**1@github.com/renovate-tests/npm85.git"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n",
         "stack": "Error: remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n\n    at Object.action (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/plugin-store.ts:24:29)\n    at /Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/renovatebot/renovate/node_modules/simple-git/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
 INFO: External host error causing abort - skipping (repository=renovate-tests/npm85)
```

I'm kind of tapped out - spent hours trying to reproduce and cannot

**Comment by rarkins** [comment]
I got an even closer reproduction failure by removing the platform external error:

```
DEBUG: git error (repository=renovate-tests/npm85)
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--heads",
             "https://**redacted**000@github.com/renovate-tests/npm85.git"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n",
         "stack": "Error: remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n\n    at Object.action (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/plugin-store.ts:24:29)\n    at /Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/renovatebot/renovate/node_modules/simple-git/cjs/index.js:55:24)"
       }
ERROR: Repository has unknown error (repository=renovate-tests/npm85)
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--heads",
             "https://**redacted**000@github.com/renovate-tests/npm85.git"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n",
         "stack": "Error: remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n\n    at Object.action (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/plugin-store.ts:24:29)\n    at /Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/renovatebot/renovate/node_modules/simple-git/cjs/index.js:55:24)"
       }
```

**Comment by viceice** [comment]
Maybe you need two repos to scan, and when starting the second, the sanitized values are missing?

**Comment by rarkins** [comment]
Nope, that didn't work out either. BTW the git timeout on this is massive - maybe a half hour or an hour or something.

**Comment by viceice** [comment]
So we should add some timeout for git operations

https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-TIMEOUT.md

**Comment by rarkins** [comment]
Here's the last log for reference:

```
 INFO: Repository finished (repository=renovate-tests/npm86)
       "durationMs": 6120
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for api.github.com to hostRules
DEBUG: No dangling containers to remove
 INFO: Repository started (repository=renovate-tests/npm85)
       "renovateVersion": "0.0.0-semantic-release"
DEBUG: Using localDir: /tmp/renovate/repos/github/renovate-tests/npm85 (repository=renovate-tests/npm85)
DEBUG: Repository cache not found (repository=renovate-tests/npm85)
       "cacheFileName": "/tmp/renovate/cache/renovate/repository/github/renovate-tests/npm85.json"
DEBUG: initRepo("renovate-tests/npm85") (repository=renovate-tests/npm85)
DEBUG: Overriding default GitHub endpoint (repository=renovate-tests/npm85)
       "endpoint": "https://api.github.com/"
DEBUG: renovate-tests/npm85 default branch = main (repository=renovate-tests/npm85)
DEBUG: Using personal access token for git init (repository=renovate-tests/npm85)
DEBUG: git error (repository=renovate-tests/npm85)
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--heads",
             "https://**redacted**000@github.com/renovate-tests/npm85.git"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n",
         "stack": "Error: remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n\n    at Object.action (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/plugin-store.ts:24:29)\n    at /Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/renovatebot/renovate/node_modules/simple-git/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
ERROR: Repository has unknown error (repository=renovate-tests/npm85)
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--heads",
             "https://**redacted**000@github.com/renovate-tests/npm85.git"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n",
         "stack": "Error: remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n\n    at Object.action (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/plugin-store.ts:24:29)\n    at /Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/renovatebot/renovate/node_modules/simple-git/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
DEBUG: Unknown res (repository=renovate-tests/npm85)
       "res": "unknown-error"
DEBUG: Repository timing splits (milliseconds) (repository=renovate-tests/npm85)
       "splits": {},
       "total": 2333710
DEBUG: http statistics (repository=renovate-tests/npm85)
       "urls": {"https://api.github.com/graphql (POST)": 1},
       "hostStats": {"api.github.com": {"requestCount": 1, "requestAvgMs": 349, "queueAvgMs": 0}},
       "totalRequests": 1
 INFO: Repository finished (repository=renovate-tests/npm85)
       "durationMs": 2333710
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "mIA9wp5kTVjQwr0TTyuvw",
           "repository": "renovate-tests/npm85",
           "err": {
             "task": {
               "commands": [
                 "ls-remote",
                 "--heads",
                 "https://**redacted**000@github.com/renovate-tests/npm85.git"
               ],
               "format": "utf-8",
               "parser": "[function]"
             },
             "message": "remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n",
             "stack": "Error: remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/renovate-tests/npm85.git/'\n\n    at Object.action (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/plugins/plugin-store.ts:24:29)\n    at /Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/renovatebot/renovate/node_modules/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/renovatebot/renovate/node_modules/simple-git/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
           },
           "msg": "Repository has unknown error"
         }
       ]
```

**Comment by rarkins** [comment]
Marking this as blocked and lowering priority due to our inability to reproduce it or work out where/how to fix it
