### ISSUE TITLE
binarySource=install for npm fails

### ISSUE THREAD

**Issue by okgolove** [renovatebot/renovate#13834]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.55.0

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

Github

### Describe the bug

I'd like to keep my npm lock file updated, I use lockfile version 2 and I must use npm >7.0.0 to work with 2nd version.
I'd like to run Renovate in Kubernetes using image provided by Whitesource, so, I can't use binarySource=docker (don't want to mount docker socket to Renovate's pod).
I set up `binarySource=install` to keep my npm up to date and maintain 2nd version lockfile but it fails after npm version update.

Reproduction repository is here https://github.com/okgolove/renovate-npm-bug

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Using buildpack dynamic installs (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
DEBUG: Resolved version (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
       "toolName": "npm",
       "constraint": "^8.1.0",
       "resolvedVersion": "8.3.2"
DEBUG: Executing command (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
       "command": "install-tool npm 8.3.2"
DEBUG: exec completed (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
       "cmd": "install-tool npm 8.3.2",
       "durationMs": 11253,
       "stdout": "Installing tool npm v8.3.2\n/usr/local/npm/8.3.2/bin/npm -> /usr/local/npm/8.3.2/lib/node_modules/npm/bin/npm-cli.js\n/usr/local/npm/8.3.2/bin/npx -> /usr/local/npm/8.3.2/lib/node_modules/npm/bin/npx-cli.js\n+ npm@8.3.2\nadded 214 packages from 96 contributors in 8.701s\n8.3.2\n",
       "stderr": "npm WARN using --force I sure hope you know what you are doing.\n"
DEBUG: Executing command (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
       "command": "hash -d npm 2>/dev/null || true"
DEBUG: rawExec err (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
       "err": {
         "errno": -2,
         "code": "ENOENT",
         "syscall": "spawn /bin/sh",
         "path": "/bin/sh",
         "spawnargs": ["-c", "hash -d npm 2>/dev/null || true"],
         "cmd": "hash -d npm 2>/dev/null || true",
         "stdout": "",
         "stderr": "",
         "message": "spawn /bin/sh ENOENT",
         "stack": "Error: spawn /bin/sh ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)\n    at onErrorNT (internal/child_process.js:469:16)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
       }
DEBUG: lock file error (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
       "err": {
         "errno": -2,
         "code": "ENOENT",
         "syscall": "spawn /bin/sh",
         "path": "/bin/sh",
         "spawnargs": ["-c", "hash -d npm 2>/dev/null || true"],
         "cmd": "hash -d npm 2>/dev/null || true",
         "stdout": "",
         "stderr": "",
         "message": "spawn /bin/sh ENOENT",
         "stack": "Error: spawn /bin/sh ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)\n    at onErrorNT (internal/child_process.js:469:16)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
       },
       "type": "npm"
 WARN: Unable to delete custom npmrc (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
DEBUG: No updated lock files in branch (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
DEBUG: Branch timestamp: 2021-05-03T19:07:19.375Z (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
DEBUG: PR is older than 2 hours, raise PR with lock file errors (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
DEBUG: isBranchConflicted(master, renovate/big.js-6.x) (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
DEBUG: Setting git author name (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
       "gitAuthorName": "Renovate Bot"
DEBUG: Error setting git author config (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
       "err": {
         "task": {
           "commands": ["config", "--local", "user.name", "Renovate Bot"],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "Error: spawn git ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)\n    at onErrorNT (internal/child_process.js:469:16)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)",
         "stack": "Error: Error: spawn git ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)\n    at onErrorNT (internal/child_process.js:469:16)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)"
       },
       "gitAuthorName": "Renovate Bot",
       "gitAuthorEmail": "petrovich@gmail.com"
DEBUG: Passing TEMPORARY_ERROR error up (repository=okgolove/renovate-npm-bug, branch=renovate/big.js-6.x)
 INFO: Temporary error - aborting (repository=okgolove/renovate-npm-bug)
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Are you running using the slim image, or full image?

**Comment by okgolove** [comment]
Full version

renovate/renovate:31.55.0

**Comment by viceice** [comment]
@rarkins the hash command is obsolete.

But the cause seems to be the shell used by node. I somewhere read it will use `/bin/bash` on ubuntu. 🤔

`/bin/sh` is a link to `dash` and `hash` is only a `bash` buildin.

**Comment by rarkins** [comment]
I can't reproduce the problem. Steps:

1. Forked repo
2. Ran the following:
`docker run --rm -e LOG_LEVEL=debug -e RENOVATE_INCLUDE_FORKS=true -e RENOVATE_TOKEN -e RENOVATE_BINARY_SOURCE=install renovate/renovate:31.55.0 renovate-reproductions/13834`
3. Got this success:
```
DEBUG: Using buildpack dynamic installs (repository=renovate-reproductions/13834, branch=renovate/big.js-6.x)
DEBUG: Resolved version (repository=renovate-reproductions/13834, branch=renovate/big.js-6.x)
       "toolName": "npm",
       "constraint": "^8.1.0",
       "resolvedVersion": "8.3.2"
DEBUG: Executing command (repository=renovate-reproductions/13834, branch=renovate/big.js-6.x)
       "command": "install-tool npm 8.3.2"
DEBUG: exec completed (repository=renovate-reproductions/13834, branch=renovate/big.js-6.x)
       "cmd": "install-tool npm 8.3.2",
       "durationMs": 9736,
       "stdout": "Installing tool npm v8.3.2\n/home/ubuntu/npm/8.3.2/bin/npm -> /home/ubuntu/npm/8.3.2/lib/node_modules/npm/bin/npm-cli.js\n/home/ubuntu/npm/8.3.2/bin/npx -> /home/ubuntu/npm/8.3.2/lib/node_modules/npm/bin/npx-cli.js\n+ npm@8.3.2\nadded 214 packages from 96 contributors in 8.275s\n8.3.2\n",
       "stderr": "npm WARN using --force I sure hope you know what you are doing.\n"
DEBUG: Executing command (repository=renovate-reproductions/13834, branch=renovate/big.js-6.x)
       "command": "hash -d npm 2>/dev/null || true"
DEBUG: exec completed (repository=renovate-reproductions/13834, branch=renovate/big.js-6.x)
       "cmd": "hash -d npm 2>/dev/null || true",
       "durationMs": 15,
       "stdout": "",
       "stderr": ""
DEBUG: Executing command (repository=renovate-reproductions/13834, branch=renovate/big.js-6.x)
       "command": "npm install --package-lock-only --no-audit --ignore-scripts"
DEBUG: exec completed (repository=renovate-reproductions/13834, branch=renovate/big.js-6.x)
       "cmd": "npm install --package-lock-only --no-audit --ignore-scripts",
       "durationMs": 613,
       "stdout": "\nup to date in 397ms\n\n1 package is looking for funding\n  run `npm fund` for details\n",
       "stderr": ""
```

**Comment by rarkins** [comment]
@okgolove what steps to reproduce are you using compared to what I detailed in the above?

**Comment by okgolove** [comment]
@rarkins I used Makefile to run container interactively and somehow I added an option `-u 0`. And it seems as soon as you run renovate using default user it works properly. Sorry for inconvenience.
