### ISSUE TITLE
GHE: Error processing vulnerabity alerts

### ISSUE THREAD

**Issue by onigoetz** [renovatebot/renovate#13865]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.19.1

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

3.3.1

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Related to https://github.com/renovatebot/renovate/issues/11911

GitHub Security advisories have an issue that some of the advisories answer with an incomplete payload and this breaks in Renovate with : `Cannot read properties of null (reading 'package')`

I don't have a reproduction repository since it happens only on GHE, however would it be enough if I provide an example payload ?

I could not find a relevant bug on GHE's side to which I can link to

### Relevant debug logs

<details><summary>Logs</summary>

```
ERROR: Error processing vulnerabity alerts (repository=gorohash/renovate-playground)
       "err": {
         "message": "Cannot read properties of null (reading 'package')",
         "stack": "TypeError: Cannot read properties of null (reading 'package')\n    at Proxy.getVulnerabilityAlerts (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/platform/github/index.js:1298:108)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async detectVulnerabilityAlerts (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/vulnerability.js:48:20)\n    at async initRepo (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/index.js:31:14)\n    at async Object.renovateRepository (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async Object.start (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/global/index.js:116:13)\n    at async /home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/renovate.js:33:24"
       }
 WARN: Error parsing vulnerability alert (repository=gorohash/renovate-playground)
       "err": {
         "message": "Cannot read properties of null (reading 'firstPatchedVersion')",
         "stack": "TypeError: Cannot read properties of null (reading 'firstPatchedVersion')\n    at detectVulnerabilityAlerts (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/vulnerability.js:75:46)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async initRepo (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/index.js:31:14)\n    at async Object.renovateRepository (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async Object.start (/home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/global/index.js:116:13)\n    at async /home/circleci/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/renovate.js:33:24"
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Please upgrade and test with the fix from this PR: https://github.com/renovatebot/renovate/pull/13788
