### ISSUE TITLE
Gitea - 409 Conflict response in createPr with every trigger

### ISSUE THREAD

**Issue by mmalyska** [renovatebot/renovate#14336]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.89

### Please select which platform you are using if self-hosting.

Gitea

### If you're self-hosting Renovate, tell us what version of the platform you run.

1.16.1

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

After fresh renovate install on k8s cluster the first run was OK.
Each next runs(every hour) produces this error.
I've set this up on cluster using kustomize.
The config is:
```yaml
config.json: |-
    {
      "platform": "gitea",
      "repositories": ["home/k8s-deployments"],
      "endpoint": "https://redacted/api/v1"
    }
```
The job looks like this:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on
              # the manifest
              image: renovate/renovate:31.89
              # Environment Variables
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
```

The repository have renovate config:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "labels": [
    "renovate"
  ],
  "reviewers": [
    "XXX"
  ],
  "dependencyDashboard": true,
  "dependencyDashboardTitle": "Renovate Dashboard",
  "commitBody": "Signed-off-by: XXX",
  "rebaseWhen": "conflicted"
}
```

This is present in dashboard:
![obraz](https://user-images.githubusercontent.com/999598/154937093-d0345b5b-4615-4a45-bc81-31a428987524.png)

Additionally when I close PR it is not ignored as stated in PR, but still gets created.
![obraz](https://user-images.githubusercontent.com/999598/154937784-9d820919-3ff0-4f2d-983d-60ac6aaee47f.png)

I think in general the problem is that the bot is not finding the PRs in Gitea.
I cannot provide real repo(as it is private Gitea instance) with dashboard and PRs, but I have prepared reproduction repo without secrets and redacted urls:
https://github.com/mmalyska/renovate-gitea-bug-repro

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: getBranchPr(renovate/sealed-secrets-2.x) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: findPr(renovate/sealed-secrets-2.x, undefined, open) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Retrieved 11 Pull Requests (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: branchExists=true (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: dependencyDashboardCheck=undefined (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: recreateClosed is false (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: findPr(renovate/sealed-secrets-2.x, Update Helm release sealed-secrets to v2.1.3, !open) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: prAlreadyExisted=false (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Checking if PR has been edited (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Branch has not been modified (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
       "branchName": "renovate/sealed-secrets-2.x"
DEBUG: Checking schedule(at any time, null) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: No schedule defined (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Branch already exists (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: getBranchPr(renovate/sealed-secrets-2.x) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: findPr(renovate/sealed-secrets-2.x, undefined, open) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Skipping stale branch check due to rebaseWhen=conflicted (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: isBranchConflicted(main, renovate/sealed-secrets-2.x) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Setting git author name (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
       "gitAuthorName": "Renovate Bot"
DEBUG: Setting git author email (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
       "gitAuthorEmail": "bot@renovateapp.com"
DEBUG: Branch does not need rebasing (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Using reuseExistingBranch: true (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=true (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Branch dep is already updated (repository=home/k8s-deployments, packageFile=sealed-secrets/Chart.yaml, branch=renovate/sealed-secrets-2.x)
       "depName": "sealed-secrets"
DEBUG: No content changed (repository=home/k8s-deployments, packageFile=sealed-secrets/Chart.yaml, branch=renovate/sealed-secrets-2.x)
       "depName": "sealed-secrets"
DEBUG: No package files need updating (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: No updated lock files in branch (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: No files to commit (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Checking if we can automerge branch (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: mergeStatus=no automerge (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Ensuring PR (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: There are 0 errors and 0 warnings (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: getBranchPr(renovate/sealed-secrets-2.x) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: findPr(renovate/sealed-secrets-2.x, undefined, open) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Creating PR (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
       "prTitle": "Update Helm release sealed-secrets to v2.1.3"
DEBUG: Creating pull request: Update Helm release sealed-secrets to v2.1.3 (renovate/sealed-secrets-2.x => main) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: lookupLabelByName(renovate) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Retrieved 8 repo labels (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Retrieved 0 org labels (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
 WARN: Attempting to gracefully recover from 409 Conflict response in createPr(Update Helm release sealed-secrets to v2.1.3, renovate/sealed-secrets-2.x) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: findPr(renovate/sealed-secrets-2.x, undefined, open) (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Retrieved 11 Pull Requests (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
DEBUG: Pull request creation error (repository=home/k8s-deployments, branch=renovate/sealed-secrets-2.x)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1645438821043,
           "socket": 1645438821043,
           "lookup": 1645438821046,
           "connect": 1645438821047,
           "secureConnect": 1645438821055,
           "upload": 1645438821055,
           "response": 1645438821123,
           "end": 1645438821124,
           "phases": {
             "wait": 0,
             "dns": 3,
             "tcp": 1,
             "tls": 8,
             "request": 0,
             "firstByte": 68,
             "download": 1,
             "total": 81
           }
         },
         "message": "Response code 409 (Conflict)",
         "stack": "HTTPError: Response code 409 (Conflict)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/31.89.4 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "866",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://redacted/api/v1/repos/home/k8s-deployments/pulls",
           "hostType": "gitea",
           "username": "",
           "password": "",
           "method": "POST",
           "http2": false
         },
         "response": {
           "statusCode": 409,
           "statusMessage": "Conflict",
           "body": {
             "message": "pull request already exists for these targets [id: 30, issue_id: 12, head_repo_id: 13, base_repo_id: 13, head_branch: renovate/sealed-secrets-2.x, base_branch: main]",
             "url": "https://redacted/api/swagger"
           },
           "headers": {
             "server": "nginx",
             "date": "Mon, 21 Feb 2022 10:20:21 GMT",
             "content-type": "application/json;charset=utf-8",
             "content-length": "225",
             "connection": "close",
             "set-cookie": [
               "i_like_gitea=33f271218a7a24d8; Path=/; HttpOnly; SameSite=Lax",
               "_csrf=Yf0gEoz6iglsvGjk1zUF6ucWLac6MTY0NTQzODgyMTQ3MjExODc2OQ; Path=/; Expires=Tue, 22 Feb 2022 10:20:21 GMT; HttpOnly; SameSite=Lax"
             ],
             "vary": "Origin",
             "x-content-type-options": "nosniff, nosniff",
             "x-frame-options": "SAMEORIGIN, DENY",
             "x-xss-protection": "1; mode=block"
           },
           "httpVersion": "1.1"
         }
       }
DEBUG: getBranchPr(renovate/sealed-secrets-2.x) (repository=home/k8s-deployments)
DEBUG: findPr(renovate/sealed-secrets-2.x, undefined, open) (repository=home/k8s-deployments)
DEBUG: Ensuring Dependency Dashboard (repository=home/k8s-deployments)
DEBUG: ensureIssue(Renovate Dashboard) (repository=home/k8s-deployments)
DEBUG: Updating Issue #9 (repository=home/k8s-deployments)
DEBUG: Removing any stale branches (repository=home/k8s-deployments)
DEBUG: config.repoIsOnboarded=true (repository=home/k8s-deployments)
DEBUG: Branch lists (repository=home/k8s-deployments)
       "branchList": ["renovate/sealed-secrets-2.x"],
       "renovateBranches": ["renovate/sealed-secrets-2.x"]
DEBUG: remainingBranches= (repository=home/k8s-deployments)
DEBUG: No branches to clean up (repository=home/k8s-deployments)
DEBUG: ensureIssueClosing(Action Required: Fix Renovate Configuration) (repository=home/k8s-deployments)
DEBUG: Repository timing splits (milliseconds) (repository=home/k8s-deployments)
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Do existing PRs already exist?

Are they created by the same user as you are running with?

What do you have in your bot `config.json`? username, password, token, etc.

**Comment by mmalyska** [comment]
1. The PR from screenshot is the existing one. The time is 37s because for the test i deleted PR and branch to see if it is created without errors(and indeed it is).
2. Yes the running user is always `renovate` (bot account).
3. The config.json is in example repository -> https://github.com/mmalyska/renovate-gitea-bug-repro/blob/main/renovate/resources/config.yaml
The only thing that exist in secret is `GITHUB_COM_TOKEN` and `RENOVATE_TOKEN` env variables

**Comment by rarkins** [comment]
You should see a dump of URLs at the end of each run. Is there one for listing PRs there?

**Comment by mmalyska** [comment]
this is the list of urls to my gitea instance:
```
         "https://redacted/api/v1/orgs/home/labels (GET)": 1,
         "https://redacted/api/v1/repos/home/k8s-deployments (GET)": 1,
         "https://redacted/api/v1/repos/home/k8s-deployments/issues (GET)": 1,
         "https://redacted/api/v1/repos/home/k8s-deployments/issues/9 (GET)": 2,
         "https://redacted/api/v1/repos/home/k8s-deployments/issues/9 (PATCH)": 1,
         "https://redacted/api/v1/repos/home/k8s-deployments/labels (GET)": 1,
         "https://redacted/api/v1/repos/home/k8s-deployments/pulls (GET)": 2,
```
