### ISSUE TITLE
Renovate failing to make PR on Gitea

### ISSUE THREAD

**Issue by xoxys** [renovatebot/renovate#14396]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.89.12

### Please select which platform you are using if self-hosting.

Gitea

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitea Version: 1.17.0+dev-201-gf1b147263 

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When attempting to post a Pull Request to a repository, there is a 422 Unprocessable Entity returned by Gitea to Renovate. This seems to be due to a malformed JSON input from Renovate to Gitea.

Reproduced at https://try.gitea.io/xoxys/test/issues/1

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found dockerfile package files (repository=xoxys/test)
DEBUG: Found 1 package file(s) (repository=xoxys/test)
 INFO: Dependency extraction complete (repository=xoxys/test)
       "baseBranch": "master",
       "stats": {
         "managers": {"dockerfile": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }
DEBUG: getLabels(https://index.docker.io, amd64/node, latest) (repository=xoxys/test)
DEBUG: getManifestResponse(https://index.docker.io, amd64/node, latest) (repository=xoxys/test)
DEBUG: Package releases lookups complete (repository=xoxys/test)
       "baseBranch": "master"
DEBUG: branchifyUpgrades (repository=xoxys/test)
DEBUG: 1 flattened updates found: node (repository=xoxys/test)
DEBUG: Returning 1 branch(es) (repository=xoxys/test)
DEBUG: config.repoIsOnboarded=true (repository=xoxys/test)
DEBUG: packageFiles with updates (repository=xoxys/test)
       "config": {
         "dockerfile": [
           {
             "packageFile": "Dockerfile",
             "deps": [
               {
                 "depName": "node",
                 "currentValue": "14",
                 "replaceString": "amd64/node:14",
                 "autoReplaceStringTemplate": "{{lookupName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "lookupName": "amd64/node",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "major",
                     "newVersion": "17",
                     "newValue": "17",
                     "newMajor": 17,
                     "newMinor": null,
                     "updateType": "major",
                     "branchName": "renovate/node-17.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "14",
                 "isSingleVersion": true,
                 "fixedVersion": "14"
               }
             ]
           }
         ]
       }
DEBUG: processRepo() (repository=xoxys/test)
DEBUG: Processing 1 branch: renovate/node-17.x (repository=xoxys/test)
DEBUG: Calculating hourly PRs remaining (repository=xoxys/test)
DEBUG: Retrieved 2 Pull Requests (repository=xoxys/test)
DEBUG: currentHourStart=2022-02-24T13:00:00.000+00:00 (repository=xoxys/test)
DEBUG: PR hourly limit remaining: 0 (repository=xoxys/test)
DEBUG: Calculating prConcurrentLimit (10) (repository=xoxys/test)
DEBUG: getBranchPr(renovate/node-17.x) (repository=xoxys/test)
DEBUG: findPr(renovate/node-17.x, undefined, open) (repository=xoxys/test)
DEBUG: 0 PRs are currently open (repository=xoxys/test)
DEBUG: PR concurrent limit remaining: 10 (repository=xoxys/test)
DEBUG: Calculated maximum PRs remaining this run (repository=xoxys/test)
       "prsRemaining": 0
DEBUG: PullRequests limit = 0 (repository=xoxys/test)
DEBUG: Calculating hourly PRs remaining (repository=xoxys/test)
DEBUG: currentHourStart=2022-02-24T13:00:00.000+00:00 (repository=xoxys/test)
DEBUG: PR hourly limit remaining: 0 (repository=xoxys/test)
DEBUG: Calculating branchConcurrentLimit (10) (repository=xoxys/test)
DEBUG: 1 already existing branches found: renovate/node-17.x (repository=xoxys/test)
DEBUG: Branch concurrent limit remaining: 9 (repository=xoxys/test)
DEBUG: Calculated maximum branches remaining this run (repository=xoxys/test)
       "branchesRemaining": 0
DEBUG: Branches limit = 0 (repository=xoxys/test)
DEBUG: Setting current branch to master (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: latest commit (repository=xoxys/test, branch=renovate/node-17.x)
       "branchName": "master",
       "latestCommitDate": "2022-02-24T14:33:18+01:00"
DEBUG: getBranchPr(renovate/node-17.x) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: findPr(renovate/node-17.x, undefined, open) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: branchExists=true (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: dependencyDashboardCheck=retry (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: recreateClosed is false (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: findPr(renovate/node-17.x, chore(deps): update node.js to v17, !open) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: prAlreadyExisted=false (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Checking if PR has been edited (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Branch has not been modified (repository=xoxys/test, branch=renovate/node-17.x)
       "branchName": "renovate/node-17.x"
DEBUG: Checking schedule(at any time, null) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: No schedule defined (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Branch already exists (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: getBranchPr(renovate/node-17.x) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: findPr(renovate/node-17.x, undefined, open) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Skipping stale branch check due to rebaseWhen=auto (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: isBranchConflicted(master, renovate/node-17.x) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Setting git author name (repository=xoxys/test, branch=renovate/node-17.x)
       "gitAuthorName": "ownCloud Renovatebot"
DEBUG: Setting git author email (repository=xoxys/test, branch=renovate/node-17.x)
       "gitAuthorEmail": "renovatebot@example.com"
DEBUG: Branch does not need rebasing (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Using reuseExistingBranch: true (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=true (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Branch dep is already updated (repository=xoxys/test, packageFile=Dockerfile, branch=renovate/node-17.x)
       "depName": "node"
DEBUG: No content changed (repository=xoxys/test, packageFile=Dockerfile, branch=renovate/node-17.x)
       "depName": "node"
DEBUG: No package files need updating (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: No updated lock files in branch (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: No files to commit (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Checking if we can automerge branch (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: mergeStatus=no automerge (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Ensuring PR (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: There are 0 errors and 0 warnings (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: getBranchPr(renovate/node-17.x) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: findPr(renovate/node-17.x, undefined, open) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Creating PR (repository=xoxys/test, branch=renovate/node-17.x)
       "prTitle": "chore(deps): update node.js to v17"
DEBUG: Creating pull request: chore(deps): update node.js to v17 (renovate/node-17.x => master) (repository=xoxys/test, branch=renovate/node-17.x)
DEBUG: Pull request creation error (repository=xoxys/test, branch=renovate/node-17.x)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1645709902607,
           "socket": 1645709902608,
           "lookup": 1645709902621,
           "connect": 1645709902701,
           "secureConnect": 1645709902780,
           "upload": 1645709902781,
           "response": 1645709902992,
           "end": 1645709902993,
           "phases": {
             "wait": 1,
             "dns": 13,
             "tcp": 80,
             "tls": 79,
             "request": 1,
             "firstByte": 211,
             "download": 1,
             "total": 386
           }
         },
         "message": "Response code 422 (Unprocessable Entity)",
         "stack": "HTTPError: Response code 422 (Unprocessable Entity)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/31.89.12 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "800",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://try.gitea.io/api/v1/repos/xoxys/test/pulls",
           "hostType": "gitea",
           "username": "",
           "password": "",
           "method": "POST",
           "http2": false
         },
         "response": {
           "statusCode": 422,
           "statusMessage": "Unprocessable Entity",
           "body": {
             "message": "[]: json: string unexpected end of JSON input",
             "url": "https://try.gitea.io/api/swagger"
           },
           "headers": {
             "content-length": "101",
             "content-type": "application/json;charset=utf-8",
             "date": "Thu, 24 Feb 2022 13:38:22 GMT",
             "set-cookie": [
               "i_like_gitea=f7579e4c8cb052dd; Path=/; HttpOnly; SameSite=Lax",
               "_csrf=b86tXgFqvmxjxwYcPEBOnqoYv-c6MTY0NTcwOTkwMjgxOTQ5OTg1OA; Path=/; Expires=Fri, 25 Feb 2022 13:38:22 GMT; HttpOnly; SameSite=Lax"
             ],
             "x-content-type-options": "nosniff",
             "x-frame-options": "SAMEORIGIN",
             "connection": "close"
           },
           "httpVersion": "1.1"
         }
       }
DEBUG: getBranchPr(renovate/node-17.x) (repository=xoxys/test)
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment]
Does it work on gitea v1.15 or v1.16.0?

**Comment by xoxys** [comment]
Don't know, I don't have an old Gitea version available to test. What I can tell is that the same config works in some cases on 1.16.1.

**Comment by xoxys** [comment]
It seems to be related to `sematicCommits` but only in some situations :thinking: https://try.gitea.io/xoxys/test/commit/a7865a9b1254d7e5cefd073a1a645741a3c2c4ee removing the presets from the renovate config "fixed" it in the test repo.

**Comment by xoxys** [comment]
It's really strange, as I can promise that semantic comments definitely work on Gitea 1.16.1, but I haven't found the exact "trigger" that causes renovate to fail -.-

![image](https://user-images.githubusercontent.com/3391958/155537340-c4553807-10e3-4b59-8a91-46bcd1a1af2b.png)

**Comment by xoxys** [comment]
To make it even more strange: https://try.gitea.io/xoxys/test/pulls/4 The PR was created successfully. If you now add back `:semanticCommits` and `:semanticCommitType(deps)` to the renovate config, renovate will **successfuly** rename the existing PR. Closing and renaming the PR will trigger the failure again and PR cant be recreated.

**Comment by viceice** [comment]
Can you try to debug and get the PR title and body, which will fail? Maybe there is a gitea bug.

If we have the exact body, we can manually try to create the PR and see if it's failing too.

**Comment by xoxys** [comment]
How can I get the PR title and body?

**Comment by xoxys** [comment]
I was not able to get the exact body from renovate but I played a bit with the PR body template:

```
# thats the default one according to the docs; does not work; PR creation failed
RENOVATE_PR_BODY_TEMPLATE={{{header}}}{{{notes}}}{{{table}}}{{{changelogs}}}{{{configDescription}}}{{{controls}}}{{{footer}}}

# but it seems to be not the length, this one (quotes added around {{{table}}}) works 
# RENOVATE_PR_BODY_TEMPLATE={{{header}}}{{{notes}}}"{{{table}}}"{{{changelogs}}}{{{configDescription}}}{{{controls}}}{{{footer}}}
```

So this might be some quoting/escaping foo in the gitea api?

**Comment by xoxys** [comment]
Ok tracing helps, will try to 

```
TRACE: got request (repository=xoxys/test, branch=renovate/node-17.x)
       "url": "https://try.gitea.io/api/v1/repos/xoxys/test/pulls",
       "options": {
         "method": "post",
         "context": {"hostType": "gitea"},
         "hostType": "gitea",
         "baseUrl": "https://try.gitea.io/api/v1/",
         "json": {
           "base": "master",
           "head": "renovate/node-17.x",
           "title": "chore(deps): update node.js to v17",
           "body": "This PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| node | final | major | `14` -> `17` |\n\n---\n\n### Configuration\n\n📅 **Schedule**: At any time (no schedule defined).\n\n🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update again.\n\n---\n\n - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click this checkbox.\n\n---\n\nThis PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
           "labels": []
         },
         "responseType": "json",
         "hooks": {"beforeRedirect": ["[function]"]},
         "headers": {
           "user-agent": "RenovateBot/31.81.7 (https://github.com/renovatebot/renovate)",
           "authorization": "***********"
         },
         "timeout": 60000
       }
DEBUG: Pull request creation error (repository=xoxys/test, branch=renovate/node-17.x)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1645734756980,
           "socket": 1645734756980,
           "lookup": 1645734756985,
           "connect": 1645734757064,
           "secureConnect": 1645734757143,
           "upload": 1645734757144,
           "response": 1645734757251,
           "end": 1645734757252,
           "phases": {
             "wait": 0,
             "dns": 5,
             "tcp": 79,
             "tls": 79,
             "request": 1,
             "firstByte": 107,
             "download": 1,
             "total": 272
           }
         },
         "message": "Response code 422 (Unprocessable Entity)",
         "stack": "HTTPError: Response code 422 (Unprocessable Entity)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
```

Creating the PR manually with an exact copy of the body from the trace works for me:

```
curl -v -X 'POST'   'https://try.gitea.io/api/v1/repos/xoxys/test/pulls?access_token=**************'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
   "base": "master",
   "head": "renovate/node-17.x",
   "title": "chore(deps): update node.js to v17",
   "body": "This PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| node | final | major | `14` -> `17` |\n\n---\n\n### Configuration\n\n📅 **Schedule**: At any time (no schedule defined).\n\n🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won'\''t be reminded about this update again.\n\n---\n\n - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click this checkbox.\n\n---\n\nThis PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
   "labels": []
 }'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 167.99.148.217:443...
* Connected to try.gitea.io (167.99.148.217) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=try.gitea.io
*  start date: Jan 17 20:41:10 2022 GMT
*  expire date: Apr 17 20:41:09 2022 GMT
*  subjectAltName: host "try.gitea.io" matched cert's "try.gitea.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55a70fca1dc0)
> POST /api/v1/repos/xoxys/test/pulls?access_token=************** HTTP/2
> Host: try.gitea.io
> user-agent: curl/7.79.1
> accept: application/json
> content-type: application/json
> content-length: 827
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* We are completely uploaded and fine
< HTTP/2 201 
< content-type: application/json;charset=utf-8
< date: Thu, 24 Feb 2022 20:46:49 GMT
< set-cookie: i_like_gitea=ccccb3746993d5cd; Path=/; HttpOnly; SameSite=Lax
< set-cookie: _csrf=0QUGCCrLgi0fPZLOaUnkT6ysmcI6MTY0NTczNTYwOTEyMDY5OTYxMw; Path=/; Expires=Fri, 25 Feb 2022 20:46:49 GMT; HttpOnly; SameSite=Lax
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< 
```

PR created successfully.

**Comment by xoxys** [comment]
Adding a minimal header like `RENOVATE_PR_HEADER=## Updates` let renovate bot create the PR successfully as well -.- I don't really understand it :D

**Comment by rarkins** [comment]
Lowered priority to normal as I'm not sure if this is even a Renovate problem or how to fix

**Comment by xoxys** [comment]
Is there something else I can provide?

**Comment by rarkins** [comment]
> Is there something else I can provide?

Have you identified the root cause? e.g. is it a Gitea problem or a Renovate problem? And if it's a Gitea problem, do we know exactly how to work around it reliably?

Sorry if I missed it from the above.

**Comment by xoxys** [comment]
No, I have not found the exact root cause, but that might be related to my very limited knowledge of the renovate source code. The summary so far is:

- I was able to reproduce it in try.gitea.io with a minimal reproduction repo
- I have used renovates trace mode to get the PR body of the faulty renovate run
- While renovate fails to create the PR I was able to copy and paste the exact body to a curl request that creates the PR **successfuly** via the Gitea API (https://github.com/renovatebot/renovate/issues/14396#issuecomment-1050259623)

That's why I thought it has to be renovate related in some kind.

**Comment by trailfog** [comment]
I've also had a similar issue with Gitea 1.17.2. I'm getting a 500 internal server error. Manually executing the above curl also didn't work. However, after removing the emojis, the PR was successfully created.

After setting the [unicodeEmoji](https://docs.renovatebot.com/self-hosted-configuration/#unicodeemoji) setting to false, I have not had any further issues creating PR requests.

However, this seems to be a database issue on the Gitea side, as I also get a 500 status when creating a PR/Issue on the web interface containing an emoji in either the title or body or in a comment (Which might relate back to the "Unprocessable Entity" described in this issue?). The [try.gitea.io](try.gitea.io) site does not suffer from this issue, and I have not tested renovate against it with the `unicodeEmoji` setting disabled.

**Comment by rarkins** [comment]
Can we add this advice to our Gitea doc?

**Comment by xoxys** [comment]
Afaik is the emoji issue a different one and only affects gitea instances that use a mariadb/mysql database with utf8 istead of utf8mb4. On postgres utf8mb4 is the default since years and is not affected.

**Comment by viceice** [comment]
the same applies to bitbucket server. i think we've something in our docs for it, so we should do same for gitea.

**Comment by xoxys** [comment]
But this is still completely unrelated to the initial issue. That's why I think changing the tag on this issue and closing it by a docs adjustment is not the best way.

**Comment by trailfog** [comment]
> Afaik is the emoji issue a different one and only affects gitea instances that use a mariadb/mysql database with utf8 istead of utf8mb4. On postgres utf8mb4 is the default since years and is not affected.
> 
> https://docs.gitea.io/en-us/database-prep/#mysql

The fix I described might be unrelated, and the issue probably needs to be kept open.

I am using MariaDB with the recommended utf8mb4 character set for the Gitea DB. The database was also created using the guide you provided.
