### ISSUE TITLE
Pull request creation error - body is too long (maximum is 65536 characters)

### ISSUE THREAD

**Issue by christoferolaison** [renovatebot/renovate#14551]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate fails to create PR when using `groupName`. See the attached logs for more details

<img width="723" alt="Screenshot 2022-03-07 at 11 16 39" src="https://user-images.githubusercontent.com/6023146/157012132-bf645121-1508-4646-bba8-cf22d988a8e3.png">

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Pull request creation error(branch="renovate/hello-world")
{
  "err": {
    "hostType": "github",
    "err": {
      "name": "HTTPError",
      "code": "ERR_NON_2XX_3XX_RESPONSE",
      "timings": {
        "start": 1646643660083,
        "socket": 1646643660084,
        "lookup": 1646643660084,
        "connect": 1646643660095,
        "secureConnect": 1646643660106,
        "upload": 1646643660107,
        "response": 1646643660585,
        "end": 1646643660585,
        "phases": {
          "wait": 1,
          "dns": 0,
          "tcp": 11,
          "tls": 11,
          "request": 1,
          "firstByte": 478,
          "download": 0,
          "total": 502
        }
      },
      "message": "Response code 422 (Unprocessable Entity)",
      "stack": "HTTPError: Response code 422 (Unprocessable Entity)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
      "options": {
        "headers": {
          "user-agent": "Renovate Bot (GitHub App 2740)",
          "accept": "application/vnd.github.machine-man-preview+json",
          "authorization": "***********",
          "content-type": "application/json",
          "content-length": "73385",
          "accept-encoding": "gzip, deflate, br"
        },
        "url": "https://api.github.com/repos/mentimeter/mm-js/pulls",
        "hostType": "github",
        "username": "",
        "password": "",
        "method": "POST",
        "http2": false
      },
      "response": {
        "statusCode": 422,
        "statusMessage": "Unprocessable Entity",
        "body": {
          "message": "Validation Failed",
          "errors": [
            {
              "resource": "Issue",
              "code": "custom",
              "field": "body",
              "message": "body is too long (maximum is 65536 characters)"
            }
          ],
          "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"
        },
        "headers": {
          "server": "GitHub.com",
          "date": "Mon, 07 Mar 2022 09:01:00 GMT",
          "content-type": "application/json; charset=utf-8",
          "content-length": "242",
          "x-github-media-type": "github.v3; param=machine-man-preview; format=json",
          "x-ratelimit-limit": "8900",
          "x-ratelimit-remaining": "8861",
          "x-ratelimit-reset": "1646645396",
          "x-ratelimit-used": "39",
          "x-ratelimit-resource": "core",
          "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
          "access-control-allow-origin": "*",
          "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
          "x-frame-options": "deny",
          "x-content-type-options": "nosniff",
          "x-xss-protection": "0",
          "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
          "content-security-policy": "default-src 'none'",
          "vary": "Accept-Encoding, Accept, X-Requested-With",
          "x-github-request-id": "8CF2:3E4A:8E14B2:93A218:6225C9CC",
          "connection": "close"
        },
        "httpVersion": "1.1"
      }
    },
    "message": "external-host-error",
    "stack": "Error: external-host-error\n    at handleGotError (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:92:16)\n    at GithubHttp.request (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/github.js:219:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async GithubHttp.requestJson (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/http/index.js:149:21)\n    at async Proxy.createPr (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/index.js:1174:17)\n    at async ensurePr (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/pr/index.js:349:22)\n    at async processBranch (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/branch/index.js:497:32)\n    at async writeUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/write.js:25:21)\n    at async update (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/extract-update.js:108:15)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:41:21)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:427:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:678:5"
  }
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
Looks like we need to trim PR body ? `body is too long (maximum is 65536 characters)`

**Comment by christoferolaison** [comment]
Created a [minimal reproduction](https://github.com/christoferolaison/renovate-body-is-too-long). Let me know if you need additional  information!

**Comment by hasanwhitesource** [comment]
@christoferolaison Isn't this the [pr](https://github.com/hasanwhitesource/renovate-body-is-too-long/pull/3) that you are expecting?

**Comment by rarkins** [comment]
FWIW I'm pretty sure our GitHub layer truncates PRs to 60k characters so I'm not sure where this 60-65k difference comes from

**Comment by christoferolaison** [comment]
> @christoferolaison Isn't this the [pr](https://github.com/hasanwhitesource/renovate-body-is-too-long/pull/3) that you are expecting?

That's the expected behaviour, yes. 

I just ran renovate on my [reporduction](https://github.com/christoferolaison/renovate-body-is-too-long) without any luck 🤔 

Still the same error, any idea what might cause this?  @hasanwhitesource

**Comment by hasanwhitesource** [comment]
@rarkins @christoferolaison  I believe its cause of this option `"extends": ["github>whitesource/merge-confidence:beta"]` in the config.

Removing it will make it work.

**Comment by rarkins** [comment]
It still needs reproducing then fixing though

**Comment by hasanwhitesource** [comment]
Managed to reproduce with this config: 
```{
  
  "extends": ["github>whitesource/merge-confidence:beta"],
  "major": {
    "enabled": false
  },
  "packageRules": [
    {
      "groupName": "all deps",
      "matchPaths": ["+(package.json)"]
    }
  ]
}
```
But works with : 
```
  "extends": ["config:base"],
  "major": {
    "enabled": false
  },
  "packageRules": [
    {
      "groupName": "all deps",
      "matchPaths": ["+(package.json)"]
    }
  ]
}
```

**Comment by MaronHatoum** [comment]
Hi,
After debugging the issue this is the PR body that we got:
[bodyIsTooLong.txt](https://github.com/renovatebot/renovate/files/8387290/bodyIsTooLong.txt)
I think we can handle this issue by changing the PR body before creating the PR.
any suggestions on how to trim the body? if we have an extra text in the body that we can remove or if we have a long text that we can shorten?

**Comment by rarkins** [comment]
@MaronHatoum we already have a "smart truncate" function for most platforms. GitHub's is here: https://github.com/renovatebot/renovate/blob/53667eac460b9ebb04740494b9002ce80b4dd334/lib/modules/platform/github/index.ts#L1663-L1676

You cam see that we're intending to truncate it to 60k. Have you debugged the reproduction case and confirmed manually how long the string is which we are sending to github in the API call which gets rejected?

We could of course just cut it back to 50k and that probably fixes it, but it would be nice to understand why the 60k is not working. I didn't think we were adding another 5k+ to the body, but maybe github does some HTML transforms and that's how it blows out

**Comment by MaronHatoum** [comment]
Thanks @rarkins.
I debugged the `smart truncate` function, we are sending a string with length **348454** and it returns a string with length **67422**.
the problem in the `smart truncate` function is this replace when returning the result:
https://github.com/renovatebot/renovate/blob/34623d9dcb9aa55444e64099eb46ffb1007ffa7e/lib/modules/platform/utils/pr-body.ts#L17-L20
The length of this part: `releaseNotes.slice(0, availableLength) + divider` is **57044**
the problem here is `releaseNote` value is a part of the `input` value and we want to replace `releaseNote` with a shortened string but after replacing the common part between `releaseNote` and `input` there are ~10000 characters more (`input` side) so we are replacing `releaseNote` (the common part) with a string length 57044 and then adding ~10000 characters.

**Notice:** I tried to run the flow with `smartTruncate(input, 55000)` and it is working

**Comment by rarkins** [comment]
Great! Can you fix the logic in our truncate or do you think a quick fix with lower threshold is better?
