### ISSUE TITLE
Renovate should not be case-sensitive regarding repository name

### ISSUE THREAD

**Issue by Mogztter** [renovatebot/renovate#14621]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.97.3

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

If a repository has been renamed, the code currently checks that the new name is strictly equals to the repository name specified:

https://github.com/renovatebot/renovate/blob/887e9f31728f768d50a7d906277ed150643487e5/lib/modules/platform/github/index.ts#L280

Using `mogztter/asciidoctor-web-pdf` instead of `Mogztter/asciidoctor-web-pdf` will throw an exception (even though GitHub repository names are case insensitive):

```
DEBUG: Repository has been renamed (repository=mogztter/asciidoctor-web-pdf)
       "this_repository": "Mogztter/asciidoctor-web-pdf"
DEBUG: Caught initRepo error (repository=mogztter/asciidoctor-web-pdf)
       "err": {
         "message": "renamed",
         "stack": "Error: renamed\n    at Proxy.initRepo (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/platform/github/index.js:183:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async getPlatformConfig (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/apis.js:38:28)\n    at async initApis (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/apis.js:47:14)\n    at async initRepo (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/index.js:25:14)\n    at async Object.renovateRepository (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/index.js:37:18)\n    at async Object.start (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/global/index.js:116:13)\n    at async /home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/renovate.js:15:24"
       }
 INFO: Repository has been renamed - skipping (repository=mogztter/asciidoctor-web-pdf)
```

### Relevant debug logs

<details><summary>Stacktrace</summary>

```
Error: renamed
    at Proxy.initRepo (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/platform/github/index.js:183:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getPlatformConfig (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/apis.js:38:28)
    at async initApis (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/apis.js:47:14)
    at async initRepo (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/init/index.js:25:14)
    at async Object.renovateRepository (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/repository/index.js:37:18)
    at async Object.start (/home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/workers/global/index.js:116:13)
    at async /home/guillaume/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/dist/renovate.js:15:24
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
This can be fixed by adding `toLowerCase()` to the compared fields on that line
