### ISSUE TITLE
Bitbucket : reviewers config seems to always return "Malformed reviewers list"

### ISSUE THREAD

**Issue by scarmouchesupralog** [renovatebot/renovate#14716]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.6

### Please select which platform you are using if self-hosting.

Bitbucket Cloud (bitbucket.org)

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Hello , 

I'm trying to add reviewers on PR create by renovate  , why self hosted renovate ( from docker image ) on bitbucket cloud server . 

Here is my renovate.json file on the repo ( not the real mail here ) : 

{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "reviewers": [
      "bitbucket@mail.com"
    ]
}

I have try every ID possible for a bitbucket user ( mail , username , nickname, id  )  , and when a add them by hand its working ( not a permission issue or inactive user
)

### Relevant debug logs

<details><summary>Logs</summary>

```

DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /usr/src/app/config.js
.....
.....

DEBUG: addAssigneesReviewers(pr=33) (repository=supralogteam/devops-ansible,  branch=renovate/coverage-6.x)
DEBUG: Adding reviewers 'bitbucket@mail.com' to #33 (repository=supralogteam/devops-ansible, branch=renovate/coverage-6.x)
DEBUG: Failed to add reviewers (repository=supralogteam/devops-ansible, branch=renovate/coverage-6.x)
       "reviewers": ["bitbucket@mail.com"],
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1647536382514,
           "socket": 1647536382515,
           "lookup": 1647536382515,
           "connect": 1647536382608,
           "secureConnect": 1647536382792,
           "upload": 1647536382792,
           "response": 1647536383271,
           "end": 1647536383271,
           "phases": {
             "wait": 1,
             "dns": 0,
             "tcp": 93,
             "tls": 184,
             "request": 0,
             "firstByte": 479,
             "download": 0,
             "total": 757
           }
         },
         "message": "Response code 400 (Bad Request)",
         "stack": "HTTPError: Response code 400 (Bad Request)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.6.3 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "109",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://api.bitbucket.org/2.0/repositories/supralogteam/devops-ansible/pullrequests/33",
           "hostType": "bitbucket",
           "username": "",
           "password": "",
           "method": "PUT",
           "http2": false
         },
         "response": {
           "statusCode": 400,
           "statusMessage": "Bad Request",
           "body": {
             "type": "error",
             "error": {
               "fields": {"reviewers": ["Malformed reviewers list"]},
               "message": "reviewers: Malformed reviewers list"
             }

      }
           },
           "headers": {
             "server": "nginx",
             "vary": "Authorization, Origin",
             "cache-control": "no-cache, no-store, must-revalidate, max-age=0",
             "content-type": "application/json; charset=utf-8",
             "x-b3-traceid": "5fae0725b9b4ea77",
             "x-oauth-scopes": "runner:write, pipeline:variable, webhook, snippet:write, wiki, issue:write, pullrequest:write, repository:delete, repository:admin, project:write, team:write, account:write",
             "x-usage-output-ops": "0",
             "x-dc-location": "Micros",
             "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
             "date": "Thu, 17 Mar 2022 16:59:43 GMT",
             "x-usage-user-time": "0.062107",
             "x-usage-system-time": "0.001549",
             "expires": "Thu, 17 Mar 2022 16:59:43 GMT",
             "x-served-by": "f2a8096329ab",
             "x-view-name": "bitbucket.apps.pullrequests.api.v20.handlers.PullRequestHandler",
             "x-static-version": "9199a160f11f",
             "x-credential-type": "apppassword",
             "x-render-time": "0.374577999115",
             "x-accepted-oauth-scopes": "pullrequest:write",
             "connection": "close",
             "x-usage-input-ops": "152",
             "x-request-count": "3419",
             "x-frame-options": "SAMEORIGIN",
             "x-version": "9199a160f11f",
             "content-length": "133"
           },
           "httpVersion": "1.1"
         }
       }

    .....
    ....
       "durationMs": 24590
DEBUG: Renovate exiting



```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rohitvermasrt** [comment]
Hi there, 

Also came across the same error. I have been trying to use package rules and based on it, assign the pull request. But no matter what reviewers I add, it assigns to 2 users who are not even mentioned in the list. And after debugging the renovate cli step in the pipeline, I found out it is throwing the same error as mentioned here.

**Comment by scarmouchesupralog** [comment]
Finaly resolve the issue. The things is about the user ID which is use by bitbucket api ( through renovate ) . The right id for the API is the 'uuid' field returned  by this api : 
` curl -X GET -u 'user:password' 'https://api.bitbucket.org/2.0/workspaces/{workspace}/members' | jq '.values[].user | "\(.display_name) \(.uuid)"'`
Then you can add an uuid list to your renovate.json 
`{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "reviewers": ["edccaf72-xxxx-4ce1-82cb-382c9808203998"]
}`
