### ISSUE TITLE
Renovate throws a preset error because of github secondary rate limit

### ISSUE THREAD

**Issue by mlarente** [renovatebot/renovate#14830]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.7.5

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.9.1-ee

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When running renovate on our gitlab instance with many repositories, it sometimes fail on some of them when trying to fetch the `github>whitesource/merge-confidence:beta` preset:
```json
{
  "documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."
}
```

Our config does have a github token configured but it doesn't seem to have an effect for this limit. I'm not sure if the limit has changed or if it's because we added some new repositories that we're hitting this. The configuration is setup as [per the documentation](https://docs.renovatebot.com/merge-confidence/#enabling-and-disabling), but Renovate requesting that for every single repo without caching the result seems to trip that limit.

### Relevant debug logs

<details><summary>Logs</summary>

```
{"name":"renovate","hostname":"runner-gpqw9voo-project-653-concurrent-0","pid":14,"level":20,"logContext":"q5wPTBrXDl2rxw5uSxwTb","repository":"********","err":{"name":"HTTPError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1648480011941,"socket":1648480011941,"lookup":1648480011957,"connect":1648480012003,"secureConnect":1648480012055,"upload":1648480012055,"response":1648480012121,"end":1648480012123,"phases":{"wait":0,"dns":16,"tcp":46,"tls":52,"request":0,"firstByte":66,"download":2,"total":182}},"message":"Response code 403 (Forbidden)","stack":"HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","options":{"headers":{"user-agent":"RenovateBot/32.7.5 (https://github.com/renovatebot/renovate)","accept":"application/vnd.github.v3+json","authorization":"***********","accept-encoding":"gzip, deflate, br"},"url":"https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json","hostType":"github","username":"","password":"","method":"GET","http2":false},"response":{"statusCode":403,"statusMessage":"Forbidden","body":{"documentation_url":"https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits","message":"You have exceeded a secondary rate limit. Please wait a few minutes before you try again."},"headers":{"server":"GitHub.com","date":"Mon, 28 Mar 2022 15:06:52 GMT","content-type":"application/json; charset=utf-8","transfer-encoding":"chunked","retry-after":"60","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","access-control-allow-origin":"*","x-github-media-type":"github.v3; format=json","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-frame-options":"deny","x-content-type-options":"nosniff","x-xss-protection":"0","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","expect-ct":"max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"","content-security-policy":"default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.githubapp.com collector.github.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events translator.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src render.githubusercontent.com viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com collector.githubapp.com collector.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com objects-origin.githubusercontent.com secured-user-images.githubusercontent.com/; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/","vary":"Accept-Encoding, Accept, X-Requested-With","content-encoding":"gzip","x-github-request-id":"DE19:7B3A:26FC47B:4A65927:6241CF0C","connection":"close"},"httpVersion":"1.1"}},"msg":"GitHub failure: secondary rate limit","time":"2022-03-28T15:06:52.127Z","v":0}
{"name":"renovate","hostname":"runner-gpqw9voo-project-653-concurrent-0","pid":14,"level":20,"logContext":"q5wPTBrXDl2rxw5uSxwTb","repository":"********","url":"https://api.github.com/repos/whitesource/merge-confidence/contents/beta.json","msg":"Failed to retrieve beta.json from repo","time":"2022-03-28T15:06:52.128Z","v":0}
{"name":"renovate","hostname":"runner-gpqw9voo-project-653-concurrent-0","pid":14,"level":20,"logContext":"q5wPTBrXDl2rxw5uSxwTb","repository":"********","preset":"github>whitesource/merge-confidence:beta","err":{"message":"dep not found","stack":"Error: dep not found\n    at fetchJSONFile (/usr/src/app/node_modules/renovate/lib/config/presets/github/index.ts:40:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at fetchPreset (/usr/src/app/node_modules/renovate/lib/config/presets/util.ts:49:19)\n    at getPreset (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:198:22)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:275:27)\n    at mergeRenovateConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/merge.ts:220:5)\n    at getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:16:12)\n    at initRepo (/usr/src/app/node_modules/renovate/lib/workers/repository/init/index.ts:31:12)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:40:14)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:150:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"},"msg":"Preset fetch error","time":"2022-03-28T15:06:52.151Z","v":0}
{"name":"renovate","hostname":"runner-gpqw9voo-project-653-concurrent-0","pid":14,"level":30,"logContext":"q5wPTBrXDl2rxw5uSxwTb","repository":"********","validationError":"Cannot find preset's package (github>whitesource/merge-confidence:beta)","msg":"Throwing preset error","time":"2022-03-28T15:06:52.152Z","v":0}
{"name":"renovate","hostname":"runner-gpqw9voo-project-653-concurrent-0","pid":14,"level":30,"logContext":"q5wPTBrXDl2rxw5uSxwTb","repository":"********","error":{"validationError":"Cannot find preset's package (github>whitesource/merge-confidence:beta)","message":"config-validation","stack":"Error: config-validation\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:286:25)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at mergeRenovateConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/merge.ts:220:5)\n    at getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:16:12)\n    at initRepo (/usr/src/app/node_modules/renovate/lib/workers/repository/init/index.ts:31:12)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:40:14)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:150:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"},"msg":"Repository has invalid config","time":"2022-03-28T15:06:52.152Z","v":0}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Where do you configure this preset (eg global, repo, or a centralised config) and at which stage does it throw the error? Eg part way through the run when it validates a new repo?

**Comment by mlarente** [comment]
> Where do you configure this preset (eg global, repo, or a centralised config) and at which stage does it throw the error? Eg part way through the run when it validates a new repo?

It's global.

I haven't seen this in a long time however, even though we've onboarded even more repositories by now. Maybe it was an issue with the rate limit implementation on the GitHub side and they fixed it? Either way, I don't have an issue anymore so I guess this could be closed.
