### ISSUE TITLE
Git error 'unknown option' adding github workflows file

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#14982]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Git adds are getting rejected with "unknown option".

I'm not sure where the `--` is getting introduced. Here's what I think is the relevant line: https://github.com/renovatebot/renovate/blob/3bb6451da2841b3afdf54d774e0b6344c4a6cea3/lib/util/git/index.ts#L871

### Relevant debug logs

<details><summary>Logs</summary>

```
{
  "level": 20,
  "branch": "renovate/codecov-codecov-action-3.x",
  "err": {
    "task": {
      "commands": [
        "add",
        "--.github/workflows/workflows.yaml"
      ],
      "format": "utf-8",
      "parser": "[function]"
    },
    "message": "error: unknown option `.github/workflows/workflows.yaml'\nusage: git add [<options>] [--] <pathspec>...\n\n    -n, --dry-run         dry run\n    -v, --verbose         be verbose\n\n    -i, --interactive     interactive picking\n    -p, --patch           select hunks interactively\n    -e, --edit            edit current diff and apply\n    -f, --force           allow adding otherwise ignored files\n    -u, --update          update tracked files\n    --renormalize         renormalize EOL of tracked files (implies -u)\n    -N, --intent-to-add   record only the fact that the path will be added later\n    -A, --all             add changes from all tracked and untracked files\n    --ignore-removal      ignore paths removed in the working tree (same as --no-all)\n    --refresh             don't add, only refresh the index\n    --ignore-errors       just skip files which cannot be added because of errors\n    --ignore-missing      check if - even missing - files are ignored in dry run\n    --sparse              allow updating entries outside of the sparse-checkout cone\n    --chmod (+|-)x        override the executable bit of the listed files\n    --pathspec-from-file <file>\n                          read pathspec from file\n    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character\n\n",
    "stack": "Error: error: unknown option `.github/workflows/workflows.yaml'\nusage: git add [<options>] [--] <pathspec>...\n\n    -n, --dry-run         dry run\n    -v, --verbose         be verbose\n\n    -i, --interactive     interactive picking\n    -p, --patch           select hunks interactively\n    -e, --edit            edit current diff and apply\n    -f, --force           allow adding otherwise ignored files\n    -u, --update          update tracked files\n    --renormalize         renormalize EOL of tracked files (implies -u)\n    -N, --intent-to-add   record only the fact that the path will be added later\n    -A, --all             add changes from all tracked and untracked files\n    --ignore-removal      ignore paths removed in the working tree (same as --no-all)\n    --refresh             don't add, only refresh the index\n    --ignore-errors       just skip files which cannot be added because of errors\n    --ignore-missing      check if - even missing - files are ignored in dry run\n    --sparse              allow updating entries outside of the sparse-checkout cone\n    --chmod (+|-)x        override the executable bit of the listed files\n    --pathspec-from-file <file>\n                          read pathspec from file\n    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character\n\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1194:25)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1229:29)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1589:43\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1587:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1571:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  },
  "msg": "Unknown error committing files",
  "time": "2022-04-06T05:08:55.871Z"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
seems to be a bug in `simple-git` ? Was there a recent update?

**Comment by rarkins** [comment]
Yes there was some security update IIRC

**Comment by rarkins** [comment]
Recent: https://app.renovatebot.com/package-diff?name=simple-git&from=3.4.0&to=3.5.0

**Comment by rarkins** [comment]
I'll try rolling back some simple-git versions and see if it still reproduces. Reproduction is here: https://github.com/renovate-reproductions/14982

**Comment by viceice** [comment]
That update is not related to the called code,

**Comment by viceice** [comment]
Looks the path needs to be quoted, as it's `--.github/workflows/workflows.yaml`, checkout the reproduction repo.

**Comment by viceice** [comment]
Very bad idea to start a git filename with a dash or double dash

**Comment by viceice** [comment]
we should probaly tighten the github workflow fileMatch?

**Comment by rarkins** [comment]
Oh ha... I thought we were adding the `--`. This is not so important then

**Comment by viceice** [comment]
> It works in 3.4.0

🤔 So it's related to the new checkout changes. we should open an upstream issue.

**Comment by rarkins** [comment]
Created upstream issue, we should also tighten our fileMatch

**Comment by steveukx** [comment]
Hi, there have been changes recently to disallow use of the `--upload-pack` argument as a potential command pollution vulnerability.

There has been no recent (since early 2021) change to handling of `git.add`, and in my test case I have been unable to show the use of `git.add('--anything')` with any file prefixed with a double dash working.

Given that the workflow directory is named `.github`, is it possible that the `--` should be supplied with a space so it marks the following string as a file path?

```
git.add(['--', '.github/workflows/workflow.yaml'])
```

**Comment by steveukx** [comment]
In chatting to @rarkins in the simple-git issue - this is caused by a file path that has a double-dash prefix. In order to add files with this prefix, prepareCommit would need to be changed to build the addParams as:

```
const addParams = [
  ...(fileName === configFileNames[0] ? ['-f'] : []),
  '--',
  fileName
];
await git.raw(addParams);
```

I can create a pull request for you later today if you've not time to fix it before.

**Comment by rarkins** [comment]
Thanks @steveukx. Do I understand correctly that you recommend to add the `--` separator before every file name, just in case? i.e. don't check for special cases - just escape it with the separator every time?

**Comment by steveukx** [comment]
You would only need the one `--` as a separator between any command switches (like the `-f`) and path specs, so if you had multiple files with an optional switch you would use:

```
const addParams = [
  ...(fileName === configFileNames[0] ? ['-f'] : []),
  '--',
  fileNameOne,
  fileNameTwo,
];
await git.raw(addParams);
```
