### ISSUE TITLE
renovate bot 403 when pushing to branch

### ISSUE THREAD

**Issue by Morriz** [renovatebot/renovate#15147]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Hi, renovate bot receives `403`'s when pushing to branches:
```
DEBUG: Pushing branch renovate/all-npm(branch="renovate/all-npm")
DEBUG: Git function thrown(branch="renovate/all-npm")
{
  "err": {
    "task": {
      "commands": [
        "push",
        "origin",
        "renovate/all-npm:renovate/all-npm",
        "--force-with-lease",
        "-u",
        "--no-verify",
        "--verbose",
        "--porcelain"
      ],
      "format": "utf-8",
      "parser": "[function]"
    },
    "message": "Pushing to https://github.com/redkubes/otomi-tasks.git\nremote: Permission to redkubes/otomi-tasks.git denied to renovate[bot].\nfatal: unable to access 'https://github.com/redkubes/otomi-tasks.git/': The requested URL returned error: 403\n",
    "stack": "Error: Pushing to https://github.com/redkubes/otomi-tasks.git\nremote: Permission to redkubes/otomi-tasks.git denied to renovate[bot].\nfatal: unable to access 'https://github.com/redkubes/otomi-tasks.git/': The requested URL returned error: 403\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1194:25)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1229:29)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1589:43\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1587:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1571:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
DEBUG: Converting git error to ExternalHostError(branch="renovate/all-npm")
{
  "err": {
    "task": {
      "commands": [
        "push",
        "origin",
        "renovate/all-npm:renovate/all-npm",
        "--force-with-lease",
        "-u",
        "--no-verify",
        "--verbose",
        "--porcelain"
      ],
      "format": "utf-8",
      "parser": "[function]"
    },
    "message": "Pushing to https://github.com/redkubes/otomi-tasks.git\nremote: Permission to redkubes/otomi-tasks.git denied to renovate[bot].\nfatal: unable to access 'https://github.com/redkubes/otomi-tasks.git/': The requested URL returned error: 403\n",
    "stack": "Error: Pushing to https://github.com/redkubes/otomi-tasks.git\nremote: Permission to redkubes/otomi-tasks.git denied to renovate[bot].\nfatal: unable to access 'https://github.com/redkubes/otomi-tasks.git/': The requested URL returned error: 403\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1194:25)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1229:29)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1589:43\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1587:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1571:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
```
I don't think this has anything to do with the protection rules on main branch as the bot is trying to push to self managed branches.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by Morriz** [comment]
I have `RENOVATE_TOKEN` set with correct scope (tried curling: ` x-oauth-scopes: admin:org, repo, workflow, write:packages`)

**Comment by Morriz** [comment]
And it as working fine before. Still see Dependency Dashboard issue that has been created by Renovate Bot.

**Comment by Morriz** [comment]
fixed by completely removing renovate app from github, and reregistering...state issue on renovate end perhaps?
