### ISSUE TITLE
Japanese file names are renamed incorrectly every time in PR.

### ISSUE THREAD

**Issue by kondei** [renovatebot/renovate#15538]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Japanese file names are renamed incorrectly every time in pull requests.
I show an example below.

original file name:
`技術選定.md`

first PR commit diff on console:

```
rename from 技術選定.md
rename to "\"\\346\\212\\200\\350\\241\\223\\351\\201\\270\\345\\256\\232.md\""
```

second PR commit diff on console:

```
rename from "\"\\346\\212\\200\\350\\241\\223\\351\\201\\270\\345\\256\\232.md\""
rename to "\"\\\"\\\\346\\\\212\\\\200\\\\350\\\\241\\\\223\\\\351\\\\201\\\\270\\\\345\\\\256\\\\232.md\\\"\""
```

and more...

diff image on PR page:

<img width="1034" alt="スクリーンショット 2022-05-11 11 23 27" src="https://user-images.githubusercontent.com/7499665/167756249-2da905e1-c348-428a-9a96-b55fdbeda93d.png">

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
looks like a Unicode issue. can be caused by renovate itself, simple-git or nodejs.

**Comment by kondei** [comment]
I created reproduction at https://github.com/kondei/minimal-reporoduction-renovate-unicode-issue/pull/3/files .
I am sorry, I am not so sure that renovate.json in the repository is really minimal.

**Comment by PhilipAbed** [comment]
i'm unable to confirm reproduction since i get an error: 
```
 WARN: Host error (repository=StinkyLord/japanese-name)
       "hostType": "npm",
       "packageName": "@storybook/addon-actions",
       "err": {
         "name": "RequestError",
         "code": "ETIMEDOUT",
         "timings": {
           "start": 1652791294373,
           "socket": 1652791294374,
           "lookup": 1652791294523,
           "error": 1652791315564,
           "phases": {"wait": 1, "dns": 149, "total": 21191}
         },
         "message": "connect ETIMEDOUT 2606:4700::6810:1123:443",
         "stack": "RequestError: connect ETIMEDOUT 2606:4700::6810:1123:443\n    at ClientRequest.<anonymous> (C:\\github\\renovateWs\\node_modules\\got\\dist\\source\\core\\index.js:962:111)\n    at Object.onceWrapper (node:events:
640:26)\n    at ClientRequest.emit (node:events:532:35)\n    at ClientRequest.emit (node:domain:475:12)\n    at ClientRequest.origin.emit (C:\\github\\renovateWs\\node_modules\\@szmarczak\\http-timer\\dist\\source\\index.js:43:20)\n
    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:164:8)\n    at emitErrorCloseN
T (node:internal/streams/destroy:129:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/0.0.0-semantic-release (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://registry.npmjs.org/@storybook%2Faddon-actions",
           "hostType": "npm",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         }
       }
 INFO: External host error causing abort - skipping (repository=StinkyLord/japanese-name)

```

**Comment by rarkins** [comment]
OK, we need a reproduction which doesn't use any private packages

**Comment by hannoeru** [comment]
@rarkins 
`@storybook/addon-actions` is a public package from storybook.

FYI: https://www.npmjs.com/package/@storybook/addon-actions/v/6.4.13

**Comment by rarkins** [comment]
In that case @PhilipAbed this sounds like a problem in your environment

**Comment by PhilipAbed** [comment]
i noticed it happened on another repository too, its random, ill try to reproduce again.

**Comment by rarkins** [comment]
Could be related to IPv6, based on your logs

**Comment by KisaragiEffective** [comment]
More cases: following commits from https://github.com/sozysozbot/linzklar-typesetting (2022-09-26 to 2022-12-15, newest to oldest):
* [`7c26a777205c0113e18728fa8d7ca7bdf9021016`](https://github.com/sozysozbot/linzklar-typesetting/commit/7c26a777205c0113e18728fa8d7ca7bdf9021016)
* [`56087a6995ffdc84af4efa97878e9bf5e0ffc03d`](https://github.com/sozysozbot/linzklar-typesetting/commit/56087a6995ffdc84af4efa97878e9bf5e0ffc03d)
* [`69430419a601c40d1efcbec4f4bfd53a19769844`](https://github.com/sozysozbot/linzklar-typesetting/commit/69430419a601c40d1efcbec4f4bfd53a19769844)
* [`549e6372bbd34475d46b824485c58385c6b2f940`](https://github.com/sozysozbot/linzklar-typesetting/commit/549e6372bbd34475d46b824485c58385c6b2f940)
* [`8d7329b386f6d0a5faeb904cc7abafd656e82cbe`](https://github.com/sozysozbot/linzklar-typesetting/commit/8d7329b386f6d0a5faeb904cc7abafd656e82cbe)
* [`9e64d1d9d1568e2417ad5c79bd7d798e5ae3a27c`](https://github.com/sozysozbot/linzklar-typesetting/commit/9e64d1d9d1568e2417ad5c79bd7d798e5ae3a27c)
* [`5684b8582bb1860cf55db5dfd6539b9b4a44153a`](https://github.com/sozysozbot/linzklar-typesetting/commit/5684b8582bb1860cf55db5dfd6539b9b4a44153a)
* [`97b234fd16157a808b7187ab2dc11a973c00abb9`](https://github.com/sozysozbot/linzklar-typesetting/commit/97b234fd16157a808b7187ab2dc11a973c00abb9)
* [`a42cad885f2a6da37021fb786ddeed6cdde7c03c`](https://github.com/sozysozbot/linzklar-typesetting/commit/a42cad885f2a6da37021fb786ddeed6cdde7c03c)
* [`7e279c2f7d4cc7188ec46b081f2b2952037ec4b7`](https://github.com/sozysozbot/linzklar-typesetting/commit/7e279c2f7d4cc7188ec46b081f2b2952037ec4b7)

**Comment by KisaragiEffective** [comment]
maybe this issue can be closed, since https://github.com/renovatebot/renovate/pull/18963 was merged
