### ISSUE TITLE
Failed to get git default branch

### ISSUE THREAD

**Issue by blackb1rd** [renovatebot/renovate#16070]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

running with docker on gitlab with latest version

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

with the my git clone, there is warning:

`warning: remote HEAD refers to nonexistent ref, unable to checkout.`

Below are the my debuging step:
```
cat .git/HEAD        
ref: refs/heads/master

git rev-parse --abbrev-ref HEAD
HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

git branch --show-current
master

git symbolic-ref --short HEAD
master

git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref

git remote show origin
~~~~~~
HEAD branch: (unknown)
```

Refer: https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git

I also find out this is related with gitlab default branch setting, I set the default branch to `main` to all project but I did not change this specific project from `master` to `main` yet then it's causing the warning.

However, it would be great to support `git branch --show-current` command.

### Relevant debug logs

<details><summary>Logs</summary>

```
         {
           "name": "renovate",
           "level": 50,
           "logContext": "~~",
           "repository": "~~~",
           "err": {
             "task": {
               "commands": ["rev-parse", "HEAD"],
               "format": "utf-8",
               "parser": "[function]"
             },
             "message": "HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
             "stack": "Error: HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
           },
           "msg": "Repository has unknown error"
         }

```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by blackb1rd** [comment]
Cannot provide the full log.

However, I think it's enough to fix issues with   my debugging step details as above.

According to renovate source code, using git rev-parse to get the default branch is not possible for this case, it would be a standard if using `git branch --show-current` with git version 2.22 and above

**Comment by viceice** [comment]
we need the sanitized debug logs. the messages around the error should be enough.

**Comment by blackb1rd** [comment]
<details><summary>Logs</summary>

```
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /usr/src/app/config.js
 WARN: Config needs migrating
       "originalConfig": {
         "endpoint": "https://gitlab.host/api/v4/",
         "token": "***********",
         "platform": "gitlab",
         "repositories": ["repo/repo"],
         "logLevel": "debug",
         "requireConfig": true,
         "onboarding": true,
         "onboardingConfig": {"extends": ["config:base"]}
       },
       "migratedConfig": {
         "endpoint": "https://gitlab.host/api/v4/",
         "token": "***********",
         "platform": "gitlab",
         "repositories": ["repo/repo"],
         "logLevel": "debug",
         "requireConfig": "required",
         "onboarding": true,
         "onboardingConfig": {"extends": ["config:base"]}
       }
DEBUG: File config
       "config": {
         "endpoint": "https://gitlab.host/api/v4/",
         "token": "***********",
         "platform": "gitlab",
         "repositories": ["repo/repo"],
         "logLevel": "debug",
         "requireConfig": "required",
         "onboarding": true,
         "onboardingConfig": {"extends": ["config:base"]}
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": [], "platform": "gitlab", "token": "***********"}
DEBUG: Combined config
       "config": {
         "endpoint": "https://gitlab.host/api/v4/",
         "token": "***********",
         "platform": "gitlab",
         "repositories": ["repo/repo"],
         "logLevel": "debug",
         "requireConfig": "required",
         "onboarding": true,
         "onboardingConfig": {"extends": ["config:base"]},
         "hostRules": []
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Found valid git version: 2.36.1
DEBUG: GitLab version is: 15.0.2
DEBUG: Using platform gitAuthor: blackb1rd
DEBUG: Adding token authentication for gitlab.host to hostRules
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
DEBUG: Setting global hostRules
DEBUG: Adding token authentication for gitlab.host to hostRules
DEBUG: validatePresets()
DEBUG: Reinitializing hostRules for repo
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for gitlab.host to hostRules
 INFO: Repository started (repository=repo/repo)
       "renovateVersion": "32.85.0"
DEBUG: Using localDir: /tmp/renovate/repos/gitlab/repo/repo (repository=repo/repo)
DEBUG: PackageFiles.clear() - Package files deleted (repository=repo/repo)
       "baseBranches": []
DEBUG: resetMemCache() (repository=repo/repo)
DEBUG: repo/repo default branch = master (repository=repo/repo)
DEBUG: Enabling Git FS (repository=repo/repo)
DEBUG: using http URL (repository=repo/repo)
       "url": "https://gitlab.host/repo/repo.git"
DEBUG: Resetting npmrc (repository=repo/repo)
DEBUG: detectSemanticCommits() (repository=repo/repo)
DEBUG: Initializing git repository into /tmp/renovate/repos/gitlab/repo/repo (repository=repo/repo)
DEBUG: Performing blobless clone (repository=repo/repo)
DEBUG: git clone completed (repository=repo/repo)
       "durationMs": 586
ERROR: Repository has unknown error (repository=repo/repo)
       "err": {
         "task": {
           "commands": ["rev-parse", "HEAD"],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       }
DEBUG: Unknown res (repository=repo/repo)
       "res": "unknown-error"
DEBUG: Repository result: unknown-error, status: unknown, enabled: undefined, onboarded: undefined (repository=repo/repo)
DEBUG: Repository timing splits (milliseconds) (repository=repo/repo)
       "splits": {},
       "total": 1685
 INFO: Repository finished (repository=repo/repo)
       "durationMs": 1685
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "-IJnM9Ouf0bDO51GnQxjc",
           "repository": "repo/repo",
           "err": {
             "task": {
               "commands": ["rev-parse", "HEAD"],
               "format": "utf-8",
               "parser": "[function]"
             },
             "message": "HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
             "stack": "Error: HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
           },
           "msg": "Repository has unknown error"
         }
       ]

```

</details>

**Comment by rarkins** [comment]
That confirms that it's this line throwing an error: https://github.com/renovatebot/renovate/blob/87f85951a20b60c1aaf2242e2bfb097cb3ac2fde/lib/util/git/index.ts#L389

**Comment by blackb1rd** [comment]
> BTW do you think that it's the "unable to checkout" part which is the problem? i.e. it's cloned, but no branch checked out, so therefore no HEAD to rev-parse?

As I described on the debugging step with my repo, there is HEAD:

```
cat .git/HEAD
ref: refs/heads/master
```

Let me try to create the method to reproduce in a public repository with my private server.

**Comment by blackb1rd** [comment]
[bug.zip](https://github.com/renovatebot/renovate/files/8924343/bug.zip)

You could try to checkout by:
 `git checkout master`

or checking HEAD

**Comment by rarkins** [comment]
What exactly is in the zip file and how did you create it? e.g. is this a problem you could reproduce in a new repo through certain steps, not just the existing one with problems?

**Comment by blackb1rd** [comment]
> What exactly is in the zip file and how did you create it? e.g. is this a problem you could reproduce in a new repo through certain steps, not just the existing one with problems?

Just git clone repo and zip file. Didn't do anything else.

Actually, it's the same issues with the existing one(when git clone repo, there is a warning massage same as the existing one).

You could try git rev-parse command after you do the checkout.

Not every repo could repoduce the issues, I try to create the new one but it's not working.

I'm not sure, this is called the file corrupted or there is something going wrong but I could do the checkout/commit and push.

**Comment by rarkins** [comment]
It doesn't seem to reproduce. After unzipping:

```
~/Downloads/onlinetv-thailand master
❯ git checkout master
branch 'master' set up to track 'origin/master'.
Already on 'master'

~/Downloads/onlinetv-thailand master
❯ git rev-parse HEAD
f6954fd2d1ca55f9ddc4e248ae7125aecf675439
```

**Comment by blackb1rd** [comment]
> It doesn't seem to reproduce. After unzipping:
> 
> ```
> ~/Downloads/onlinetv-thailand master
> ❯ git checkout master
> branch 'master' set up to track 'origin/master'.
> Already on 'master'
> 
> ~/Downloads/onlinetv-thailand master
> ❯ git rev-parse HEAD
> f6954fd2d1ca55f9ddc4e248ae7125aecf675439
> ```

ummm... sorry for confusing,

After clone, perform `git rev-parse HEAD` without checkout, so it will failed:
https://github.com/renovatebot/renovate/blob/87f85951a20b60c1aaf2242e2bfb097cb3ac2fde/lib/util/git/index.ts#L389

And there is additional command to get default branch `git rev-parse --abbrev-ref origin/HEAD` also failed after checkout:
https://github.com/renovatebot/renovate/blob/87f85951a20b60c1aaf2242e2bfb097cb3ac2fde/lib/util/git/index.ts#L112

but if using `git rev-parse --abbrev-ref HEAD` to get default branch, it will not fail.

**Comment by eliashaeussler** [comment]
Hi together,

we are running a self-hosted Renovate on GitLab and have a similar issue during onboarding:

```
DEBUG: git commit (repository=*****)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/configure",
         "commit": "b8d906a6224f3f4b1e0a08134ec187acf7941795",
         "root": false,
         "summary": {"changes": 1, "insertions": 6, "deletions": 0}
       }
DEBUG: Git function thrown (repository=*****)
       "err": {
         "task": {
           "commands": ["diff", "HEAD", "origin/renovate/configure"],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/opt/buildpack/tools/renovate/34.117.1/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/buildpack/tools/renovate/34.117.1/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/buildpack/tools/renovate/34.117.1/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/buildpack/tools/renovate/34.117.1/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/buildpack/tools/renovate/34.117.1/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/buildpack/tools/renovate/34.117.1/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
DEBUG: Pushing refSpec renovate/configure:renovate/configure (repository=*****)
```

However, this never happened before and currently only affects a single repository.

**Comment by zaclohrenz** [comment]
I'm experiencing this, too, likewise a private repo, so I've obscured data:
`INFO: Repository started (repository=org/team/proj-aws-restore)
11639       "renovateVersion": "35.69.1"
11640DEBUG: Using localDir: /scratch/builds/org/team/renovatebot-group/renovatebot/renovate/repos/gitlab/org/team/proj-aws-restore (repository=org/team/proj-aws-restore)
11641DEBUG: PackageFiles.clear() - Package files deleted (repository=org/team/proj-aws-restore)
11642DEBUG: org/team/proj-aws-restore default branch = master (repository=org/team/proj-aws-restore)
11643DEBUG: Enabling Git FS (repository=org/team/proj-aws-restore)
11644DEBUG: Using http URL: https://my.domain/org/team/proj-aws-restore.git (repository=org/team/proj-aws-restore)
11645DEBUG: RepoCacheBase.load() - expecting data of type 'string' received 'object' instead - skipping (repository=org/team/proj-aws-restore)
11646DEBUG: Resetting npmrc (repository=org/team/proj-aws-restore)
11647DEBUG: checkOnboarding() (repository=org/team/proj-aws-restore)
11648DEBUG: isOnboarded() (repository=org/team/proj-aws-restore)
11649DEBUG: Repo is onboarded (repository=org/team/proj-aws-restore)
11650DEBUG: Initializing git repository into /scratch/builds/org/team/renovatebot-group/renovatebot/renovate/repos/gitlab/org/team/proj-aws-restore (repository=org/team/proj-aws-restore)
11651DEBUG: Performing blobless clone (repository=org/team/proj-aws-restore)
11652DEBUG: git clone completed (repository=org/team/proj-aws-restore)
11653       "durationMs": 622
11654ERROR: Repository has unknown error (repository=org/team/proj-aws-restore)
11655       "err": {
11656         "task": {
11657           "commands": ["rev-parse", "HEAD"],
11658           "format": "utf-8",
11659           "parser": "[function]"
11660         },
11661         "message": "HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
11662         "stack": "Error: HEAD\nfatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/opt/buildpack/tools/renovate/35.69.1/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/buildpack/tools/renovate/35.69.1/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/buildpack/tools/renovate/35.69.1/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/buildpack/tools/renovate/35.69.1/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/buildpack/tools/renovate/35.69.1/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/buildpack/tools/renovate/35.69.1/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
11663       }
11664DEBUG: Unknown res: unknown-error (repository=org/team/proj-aws-restore)
11665DEBUG: Repository result: unknown-error, status: unknown, enabled: undefined, onboarded: undefined (repository=org/team/proj-aws-restore)
11666DEBUG: Repository timing splits (milliseconds) (repository=org/team/proj-aws-restore)
11667       "splits": {},
11668       "total": 1330
11669DEBUG: Package cache statistics (repository=org/team/proj-aws-restore)
11670       "get": {"count": 0},
11671       "set": {"count": 0}
11672DEBUG: Package lookup durations (repository=org/team/proj-aws-restore)
11673DEBUG: dns cache (repository=org/team/proj-aws-restore)
11674       "hosts": []
11675 INFO: Repository finished (repository=org/team/proj-aws-restore)
11676       "cloned": true,
11677       "durationMs": 1330
11678DEBUG: Reinitializing hostRules for repo
11679DEBUG: Clearing hostRules
11680DEBUG: Adding token authentication for my.domain to hostRules
11681DEBUG: Adding token authentication for my.domain to hostRules`

blackb1rd's suggestions don't work, here:
git rev-parse HEAD
git rev-parse --abbrev-ref origin/HEAD
git rev-parse --abbrev-ref HEAD

All fail.

I then cloned Master into Main, set Main as the default branch, protected it, removed Master, and retried... The local git commands all succeed now, but RenovateBot continued to fail in the same manner. 

I thought it was something to do with the REPOSITORY_CACHE setting holding onto some type of HEAD reference or something, so I set it to "reset" per the doc and that doesn't help, either.
