### ISSUE TITLE
Cannot read properties of null (reading 'indexOf')

### ISSUE THREAD

**Issue by MarkvTurnhout** [renovatebot/renovate#16417]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

29.34.1

### Please select which platform you are using if self-hosting.

Azure DevOps (dev.azure.com)

### If you're self-hosting Renovate, tell us what version of the platform you run.

latest

### Was this something which used to work for you, and then stopped?

We used the same template we use in other projects, it is not working on this new project.

### Describe the bug

We have a PackageRule where we gather all minor updates (except FluentMigrator):

```
    {
      "matchPackagePatterns": [
        "*"
      ],
      "excludePackagePatterns": [ "^FluentMigrator"],
      "matchUpdateTypes": [
        "minor",
        "patch"
      ],
      "groupName": "all non-major dependencies",
      "groupSlug": "all-minor-patch"
    }
```

While running Renovate we get this error twice, once on the minor updates and once on the major update for the same package: Microsoft.Net.Test.SDK and on the same UnitTestProject.

```
"err": {
         "message": "Cannot read properties of null (reading 'indexOf')",
         "stack": "TypeError: Cannot read properties of null (reading 'indexOf')\n    at doAutoReplace (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\branch\\auto-replace.js:94:39)\n    at getUpdatedPackageFiles (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\branch\\get-updated.js:76:66)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async processBranch (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\branch\\index.js:267:21)\n    at async writeUpdates (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\repository\\process\\write.js:25:21)\n    at async update (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\repository\\process\...
       }
```

What have we tried:

- Excluding the Microsoft.Test package, this gave the same error on a different package.
- Excluding the UnitTest project, this gave the same error on a different test project.

Other branches and PR are being created. We also use this package rule for other repositories and it seems to work fine there.

I have removed some info (company name etc.) in the logs, if there is more info needed please let me know.
I have added the TRACE log where the error occurs, and the log above it where the error does not occur.

### Relevant debug logs

<details><summary>Logs</summary>
2022-07-04T15:09:34.9773116Z TRACE: nuget.extractPackageFile() (repository=Repo, packageFile=UniteTestProject1.csproj, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9774088Z DEBUG: found NuGet.config (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9774568Z        "nuGetConfigPath": nuget.config
2022-07-04T15:09:34.9775195Z DEBUG: clearing registry URLs (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9775694Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9776234Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/Products/_packaging/ArtifactFeed1/nuget/v3/index.json"
2022-07-04T15:09:34.9776758Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9777284Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed2/nuget/v3/index.json"
2022-07-04T15:09:34.9777795Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9778322Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed3/nuget/v3/index.json"
2022-07-04T15:09:34.9778834Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9779352Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed4/nuget/v3/index.json"
2022-07-04T15:09:34.9779855Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9780399Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed5/nuget/v3/index.json"
2022-07-04T15:09:34.9780924Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9781468Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed6/nuget/v3/index.json"
2022-07-04T15:09:34.9782259Z DEBUG: Contents updated (repository=Repo, packageFile=UniteTestProject1.csproj, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9782930Z        "depName": "Microsoft.NET.Test.Sdk"
2022-07-04T15:09:34.9783345Z TRACE: autoReplace replaceString (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9783773Z        "depName": "Microsoft.NET.Test.Sdk",
2022-07-04T15:09:34.9784060Z        "replaceString": "16.5.0"
2022-07-04T15:09:34.9784745Z DEBUG: Starting search at index 534 (repository=Repo, packageFile=UniteTestProject2.csproj, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9785454Z        "depName": "Microsoft.NET.Test.Sdk"
2022-07-04T15:09:34.9786144Z DEBUG: Found match at index 534 (repository=Repo, packageFile=UniteTestProject2.csproj, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9786836Z        "depName": "Microsoft.NET.Test.Sdk"
2022-07-04T15:09:34.9787277Z TRACE: Replacing 16.5.0 with 16.11.0 at index 534 (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9788127Z TRACE: nuget.extractPackageFile() (repository=Repo, packageFile=UniteTestProject2.csproj, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9789001Z DEBUG: found NuGet.config (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9789735Z        "nuGetConfigPath": nuget.config
2022-07-04T15:09:34.9790390Z DEBUG: clearing registry URLs (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9790932Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9791489Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/Products/_packaging/ArtifactFeed1/nuget/v3/index.json"
2022-07-04T15:09:34.9792064Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9792614Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed2/nuget/v3/index.json"
2022-07-04T15:09:34.9793183Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9793740Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed3/nuget/v3/index.json"
2022-07-04T15:09:34.9794472Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9794996Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed4/nuget/v3/index.json"
2022-07-04T15:09:34.9795535Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9796077Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed5/nuget/v3/index.json"
2022-07-04T15:09:34.9796812Z DEBUG: adding registry URL (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9797537Z        "registryUrl": "https://pkgs.dev.azure.com/Orginisation/_packaging/ArtifactFeed6/nuget/v3/index.json"
2022-07-04T15:09:34.9798374Z DEBUG: Contents updated (repository=Repo, packageFile=UniteTestProject2.csproj, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9799268Z        "depName": "Microsoft.NET.Test.Sdk"
2022-07-04T15:09:34.9799711Z TRACE: autoReplace replaceString (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9800175Z        "depName": "Microsoft.NET.Test.Sdk",
2022-07-04T15:09:34.9800484Z        "replaceString": "16.5.0"
2022-07-04T15:09:34.9800914Z  WARN: Error updating branch (repository=Repo, branch=renovate/all-minor-patch)
2022-07-04T15:09:34.9801286Z        "err": {
2022-07-04T15:09:34.9801633Z          "message": "Cannot read properties of null (reading 'indexOf')",
2022-07-04T15:09:34.9806409Z          "stack": "TypeError: Cannot read properties of null (reading 'indexOf')\n    at doAutoReplace (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\branch\\auto-replace.js:94:39)\n    at getUpdatedPackageFiles (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\branch\\get-updated.js:76:66)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async processBranch (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\branch\\index.js:267:21)\n    at async writeUpdates (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\repository\\process\\write.js:25:21)\n    at async update (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\repository\\process\\extract-update.js:108:15)\n    at async Object.renovateRepository (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\repository\\index.js:47:21)\n    at async Object.start (C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\workers\\global\\index.js:95:13)\n    at async C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\73cd147534ef80c8\\node_modules\\renovate\\dist\\renovate.js:15:24"
2022-07-04T15:09:34.9810754Z        }

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Please update to the latest Renovate

**Comment by MarkvTurnhout** [comment]
Unfortunately our version of git on the pipelines does not play nice with Renovate, so we have to update the pipelines first. This will take around 2 weeks. 

I don't know if you want to close this ticket and I can open a new one if it doesn't work after the update. Or keep it open?

**Comment by PhilipAbed** [comment]
i believe the null pointer is here, caused by some issue in extraction/lookup:
see `indexOf(replaceString!);`

for some reason we are ignoring the possibility of `replaceString` being null, but something happened before that, which caused the `replaceString` and the `currentValue` both to be null hence the null ..

```
 const replaceString = upgrade.replaceString ?? currentValue;
  logger.trace({ depName, replaceString }, 'autoReplace replaceString');
  let searchIndex = existingContent.indexOf(replaceString!);
  if (searchIndex === -1) {
    logger.info(
      { packageFile, depName, existingContent, replaceString },
      'Cannot find replaceString in current file content. Was it already updated?'
    );
    return existingContent;
  }
```

better upgrade to new renovate, see if the issue before that could've been resolved ,
i cant know the issue unless i see logs or minimal repository reproduction

**Comment by kwlin** [comment]
We have tested with version 32.135.1 and it's fixed.
