### ISSUE TITLE
docker registry zalan.do errors

### ISSUE THREAD

**Issue by universam1** [renovatebot/renovate#16464]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.105.4

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitlab CE

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

docker registry `registry.opensource.zalan.do` cannot be parsed any more.

`Unexpected token O in JSON at position 0 in \"https://registry.opensource.zalan.do/v2/\"`

It used to be working in the past, not clear if the registry API changed or renovatebot's behaviour changed.

Example image refs:
- registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.1.17-3-g2ccd690
- registry.opensource.zalan.do/teapot/skipper:v0.13.217
- registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.13.0

example deployment:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ingress-aws-controller
  namespace: kube-system
  labels:
    application: kube-ingress-aws-controller
    component: ingress
spec:
  selector:
    matchLabels:
      application: kube-ingress-aws-controller
      component: ingress
  template:
    spec:
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.13.0
```

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Error obtaining docker token (repository=on/eks)
       "registryHost": "https://registry.opensource.zalan.do/",
       "dockerRepository": "teapot/kube-metrics-adapter",
       "err": {
         "err": {
           "name": "ParseError",
           "code": "ERR_BODY_PARSE_FAILURE",
           "timings": {
             "start": 1657187331689,
             "socket": 1657187331689,
             "lookup": 1657187331723,
             "connect": 1657187332231,
             "secureConnect": 1657187332581,
             "upload": 1657187332582,
             "response": 1657187332684,
             "end": 1657187332684,
             "phases": {
               "wait": 0,
               "dns": 34,
               "tcp": 508,
               "tls": 350,
               "request": 1,
               "firstByte": 102,
               "download": 0,
               "total": 995
             }
           },
           "message": "Unexpected token O in JSON at position 0 in \"https://registry.opensource.zalan.do/v2/\"",
           "stack": "RequestError: Unexpected token O in JSON at position 0 in \"https://registry.opensource.zalan.do/v2/\"\n    at Object.parseBody [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/parse-body.js:22:15)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:72:61)\n    at runMicrotasks (<anonymous>)\n    at JSON.parse (<anonymous>)\n    at parseJson (/usr/src/app/node_modules/got/dist/source/index.js:118:35)\n    at Object.parseBody [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/parse-body.js:11:48)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:72:61)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
           "options": {
             "headers": {
               "user-agent": "RenovateBot/32.105.4 (https://github.com/renovatebot/renovate)",
               "accept": "application/json",
               "accept-encoding": "gzip, deflate, br"
             },
             "url": "https://registry.opensource.zalan.do/v2/",
             "hostType": "docker",
             "username": "",
             "password": "",
             "method": "GET",
             "http2": false
           },
           "response": {
             "statusCode": 200,
             "statusMessage": "OK",
             "body": "OK",
             "headers": {
               "content-type": "application/octet-stream",
               "date": "Thu, 07 Jul 2022 09:48:52 GMT",
               "docker-distribution-api-version": "registry/2.0",
               "server": "Jetty(9.2.z-SNAPSHOT)",
               "strict-transport-security": "max-age=31536000; includeSubDomains",
               "content-length": "2",
               "connection": "Close"
             },
             "httpVersion": "1.1"
           }
         },
         "message": "external-host-error",
         "stack": "Error: external-host-error\n    at Http.request (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:183:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Http.requestJson (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:222:17)\n    at getAuthHeaders (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:62:30)\n    at DockerDatasource.getManifestResponse (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:381:23)\n    at DockerDatasource.getConfigDigest (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:458:30)\n    at DockerDatasource.getLabels (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:[568](https://mygit.org/on/renovate-runner/-/jobs/11358454#L568):28)\n    at /usr/src/app/node_modules/renovate/lib/util/cache/package/decorator.ts:78:20\n    at DockerDatasource.getReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:915:20)\n    at getRegistryReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:73:15)\n    at fetchReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:293:15)\n    at getPkgReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:352:7)\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:80:32)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:58:15)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
 WARN: Error obtaining docker token (repository=on/eks)
       "registryHost": "https://registry.opensource.zalan.do",
       "dockerRepository": "teapot/skipper",
       "err": {
         "err": {
           "name": "ParseError",
           "code": "ERR_BODY_PARSE_FAILURE",
           "timings": {
             "start": 16[571](https://mygit.org/on/renovate-runner/-/jobs/11358454#L571)87331689,
             "socket": 1657187331689,
             "lookup": 1657187331723,
             "connect": 1657187332231,
             "secureConnect": 1657187332581,
             "upload": 1657187332582,
             "response": 1657187332684,
             "end": 1657187332684,
             "phases": {
               "wait": 0,
               "dns": 34,
               "tcp": 508,
               "tls": 350,
               "request": 1,
               "firstByte": 102,
               "download": 0,
               "total": 995
             }
           },
           "message": "Unexpected token O in JSON at position 0 in \"https://registry.opensource.zalan.do/v2/\"",
           "stack": "RequestError: Unexpected token O in JSON at position 0 in \"https://registry.opensource.zalan.do/v2/\"\n    at Object.parseBody [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/parse-body.js:22:15)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:72:61)\n    at runMicrotasks (<anonymous>)\n    at JSON.parse (<anonymous>)\n    at parseJson (/usr/src/app/node_modules/got/dist/source/index.js:118:35)\n    at Object.parseBody [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/parse-body.js:11:48)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:72:61)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
           "options": {
             "headers": {
               "user-agent": "RenovateBot/32.105.4 (https://github.com/renovatebot/renovate)",
               "accept": "application/json",
               "accept-encoding": "gzip, deflate, br"
             },
             "url": "https://registry.opensource.zalan.do/v2/",
             "hostType": "docker",
             "username": "",
             "password": "",
             "method": "GET",
             "http2": false
           },
           "response": {
             "statusCode": 200,
             "statusMessage": "OK",
             "body": "OK",
             "headers": {
               "content-type": "application/octet-stream",
               "date": "Thu, 07 Jul 2022 09:48:52 GMT",
               "docker-distribution-api-version": "registry/2.0",
               "server": "Jetty(9.2.z-SNAPSHOT)",
               "strict-transport-security": "max-age=31536000; includeSubDomains",
               "content-length": "2",
               "connection": "Close"
             },
             "httpVersion": "1.1"
           }
         },
         "message": "external-host-error",
         "stack": "Error: external-host-error\n    at Http.request (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:183:15)\n    at Http.requestJson (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:222:17)\n    at getAuthHeaders (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:62:30)\n    at DockerDatasource.getManifestResponse (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:381:23)\n    at DockerDatasource.getConfigDigest (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:458:30)\n    at DockerDatasource.getLabels (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:568:28)\n    at /usr/src/app/node_modules/renovate/lib/util/cache/package/decorator.ts:78:20\n    at DockerDatasource.getReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:915:20)\n    at getRegistryReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:73:15)\n    at fetchReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:293:15)\n    at getPkgReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:352:7)\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:80:32)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:58:15)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
 WARN: Error obtaining docker token (repository=on/eks)
       "registryHost": "https://registry.opensource.zalan.do",
       "dockerRepository": "teapot/kube-ingress-aws-controller",
       "err": {
         "err": {
           "name": "ParseError",
           "code": "ERR_BODY_PARSE_FAILURE",
           "timings": {
             "start": 1657187331689,
             "socket": 1657187331689,
             "lookup": 1657187331723,
             "connect": 1657187332231,
             "secureConnect": 1657187332581,
             "upload": 1657187332582,
             "response": 1657187332684,
             "end": 1657187332684,
             "phases": {
               "wait": 0,
               "dns": 34,
               "tcp": 508,
               "tls": 350,
               "request": 1,
               "firstByte": 102,
               "download": 0,
               "total": 995
             }
           },
           "message": "Unexpected token O in JSON at position 0 in \"https://registry.opensource.zalan.do/v2/\"",
           "stack": "RequestError: Unexpected token O in JSON at position 0 in \"https://registry.opensource.zalan.do/v2/\"\n    at Object.parseBody [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/parse-body.js:22:15)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:72:61)\n    at runMicrotasks (<anonymous>)\n    at JSON.parse (<anonymous>)\n    at parseJson (/usr/src/app/node_modules/got/dist/source/index.js:118:35)\n    at Object.parseBody [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/parse-body.js:11:48)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:72:61)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
           "options": {
             "headers": {
               "user-agent": "RenovateBot/32.105.4 (https://github.com/renovatebot/renovate)",
               "accept": "application/json",
               "accept-encoding": "gzip, deflate, br"
             },
             "url": "https://registry.opensource.zalan.do/v2/",
             "hostType": "docker",
             "username": "",
             "password": "",
             "method": "GET",
             "http2": false
           },
           "response": {
             "statusCode": 200,
             "statusMessage": "OK",
             "body": "OK",
             "headers": {
               "content-type": "application/octet-stream",
               "date": "Thu, 07 Jul 2022 09:48:52 GMT",
               "docker-distribution-api-version": "registry/2.0",
               "server": "Jetty(9.2.z-SNAPSHOT)",
               "strict-transport-security": "max-age=3153[600](https://mygit.org/on/renovate-runner/-/jobs/11358454#L600)0; includeSubDomains",
               "content-length": "2",
               "connection": "Close"
             },
             "httpVersion": "1.1"
           }
         },
         "message": "external-host-error",
         "stack": "Error: external-host-error\n    at Http.request (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:183:15)\n    at Http.requestJson (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:222:17)\n    at getAuthHeaders (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:62:30)\n    at DockerDatasource.getManifestResponse (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:381:23)\n    at DockerDatasource.getConfigDigest (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:458:30)\n    at DockerDatasource.getLabels (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:568:28)\n    at /usr/src/app/node_modules/renovate/lib/util/cache/package/decorator.ts:78:20\n    at DockerDatasource.getReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/docker/index.ts:915:20)\n    at getRegistryReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:73:15)\n    at fetchReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:293:15)\n    at getPkgReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:352:7)\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:80:32)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:58:15)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment]
looks like an issue with the docket API, as we didn't changed anything recently

**Comment by rarkins** [comment]
I'm not sure what the problem is but here is some debugging:

```
❯ curl -v https://registry.opensource.zalan.do/v2/
*   Trying 18.196.163.104:443...
* Connected to registry.opensource.zalan.do (18.196.163.104) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.opensource.zalan.do
*  start date: Apr 20 00:00:00 2022 GMT
*  expire date: May 19 23:59:59 2023 GMT
*  subjectAltName: host "registry.opensource.zalan.do" matched cert's "*.opensource.zalan.do"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /v2/ HTTP/1.1
> Host: registry.opensource.zalan.do
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< Date: Fri, 08 Jul 2022 05:49:38 GMT
< Docker-Distribution-API-Version: registry/2.0
< Server: Jetty(9.2.z-SNAPSHOT)
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Content-Length: 2
< Connection: keep-alive
<
* Connection #0 to host registry.opensource.zalan.do left intact
OK
```

compare to:

```
❯ curl -v https://quay.io/v2/
*   Trying 54.144.203.57:443...
* Connected to quay.io (54.144.203.57) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.quay.io
*  start date: Feb 25 00:00:00 2022 GMT
*  expire date: Mar 26 23:59:59 2023 GMT
*  subjectAltName: host "quay.io" matched cert's "quay.io"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fde28810a00)
> GET /v2/ HTTP/2
> Host: quay.io
> user-agent: curl/7.79.1
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 401
< date: Fri, 08 Jul 2022 05:50:43 GMT
< content-type: text/html; charset=utf-8
< content-length: 4
< server: nginx/1.20.1
< www-authenticate: Bearer realm="https://quay.io/v2/auth",service="quay.io"
< docker-distribution-api-version: registry/2.0
<
* Connection #0 to host quay.io left intact
true
```

**Comment by viceice** [comment]
I've already prepared a fix
- https://github.com/renovatebot/renovate/pull/16482

**Comment by universam1** [comment]
> I've already prepared a fix

Looking forward, thanks for that!
Just wanted to stress that other registries do respond with JSON, not sure if that matters.
