### ISSUE TITLE
Autodiscover Filter: re2 fails to parse regex with negative lookahead assertion

### ISSUE THREAD

**Issue by Stefan-J-Hanke** [renovatebot/renovate#16470]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.105.4

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.0

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I'd like to autodiscover every repository below a certain GitLab Group _except_ a single one.

Fortunately, Renovate not only allows to use minimatch, but regular expressions also (https://docs.renovatebot.com/self-hosted-configuration/#autodiscoverfilter), so it should be possible using a negative lookahead assertion (from an SO answer in another context)

The autodiscover filter in question is  **"/groupname1/groupname2/(?!excluded-project-name).*/"** which matches every direct project below **groupname1/groupname2** except **excluded-project-name**

I noticed that renovate is preferring to use "re2" as regex library instead of the node one. "re2" just fails to parse this regular expression - the default one can parse it. I've forcefully removed "re2" (by just "rm -rf"ing the folder **/usr/src/app/node_modules/re2**) to verify this, however that's not a line of code that can stay.

### Relevant debug logs

<details><summary>Logs</summary>

```
"loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "_z-kTL3a9lsDo6wDD_aPj",
           "err": {
             "message": "Failed to parse regex pattern \"/groupname1/groupname2/(?!excluded-project-name).*/\"",
             "stack": "Error: Failed to parse regex pattern \"/groupname1/groupname2/(?!excluded-project-name).*/\"\n    at autodiscoverRepositories (/usr/src/app/node_modules/renovate/lib/workers/global/autodiscover.ts:37:15)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:131:14)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
           },
           "msg": "Fatal error: Failed to parse regex pattern \"/groupname1/groupname2/(?!excluded-project-name).*/\""
         }
]
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by secustor** [comment]
This is expected behaviour as RE2 does not support look arounds. 

> It is also not a goal to implement all of the features offered by Perl, PCRE and other engines. As a matter of principle, RE2 does not support constructs for which only backtracking solutions are known to exist. Thus, backreferences and look-around assertions are not supported.

What you can do is use an internal feature regex negation   
`!/mygroup/example-project/`
