### ISSUE TITLE
renovate reports an error but unclear which file it is

### ISSUE THREAD

**Issue by robvdnieuw** [renovatebot/renovate#16656]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.119.1

### Please select which platform you are using if self-hosting.

Azure DevOps Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

Azure DevOps Server 2020 Update 1.1

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

for some reason the allNonMajor updates in one of our repo's is not working anymore, we see a warning but no clue whether that is the reason: (log file attached) 

2022-07-19T12:10:12.1746228Z    WARN: Error updating branch (repository=OCC/COES, branch=renovate/all-minor-patch)
2022-07-19T12:10:12.1747118Z          "err": {
2022-07-19T12:10:12.1747623Z            "message": "Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: d",
2022-07-19T12:10:12.1767883Z            "stack": "Error: Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: d\n    at error (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\sax\\lib\\sax.js:651:10)\n    at strictFail (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\sax\\lib\\sax.js:677:7)\n    at beginWhiteSpace (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\sax\\lib\\sax.js:951:7)\n    at SAXParser.write (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\sax\\lib\\sax.js:1006:11)\n    at new XmlDocument (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\xmldoc\\lib\\xmldoc.js:281:17)\n    at getDependentPackageFiles (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\modules\\manager\\nuget\\package-tree.js:37:21)\n    at async updateArtifacts (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\modules\\manager\\nuget\\artifacts.js:84:13)\n    at async getUpdatedPackageFiles (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\update\\branch\\get-updated.js:197:29)\n    at async processBranch (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\update\\branch\\index.js:292:21)\n    at async writeUpdates (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\process\\write.js:25:21)\n    at async update (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\process\\extract-update.js:109:15)\n    at async Object.renovateRepository (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\index.js:43:25)\n    at async Object.start (C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\global\\index.js:119:13)\n    at async C:\\agent01\\_work\\348\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\renovate.js:15:24"
2022-07-19T12:10:12.1773165Z          
[renovate.log](https://github.com/renovatebot/renovate/files/9141912/renovate.log)
}

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by robvdnieuw** [comment]
Logs are uploaded as file in the description called renovate.log

**Comment by rarkins** [comment]
Logs are insufficient and also difficult to read due to the formatting

**Comment by robvdnieuw** [comment]
[renovate-debug.log](https://github.com/renovatebot/renovate/files/9149515/renovate-debug.log)

original logfile

**Comment by rarkins** [comment]
Warning: you appear to have a token in this log. You should revoke and rotate it if so

**Comment by HonkingGoose** [comment]
[Renovate docs, line endings](https://docs.renovatebot.com/getting-started/installing-onboarding/#self-hosting-on-windows).

**Comment by MaxClaessen** [comment]
> Warning: you appear to have a token in this log. You should revoke and rotate it if so

FYI; we rotated the token ;).
