### ISSUE TITLE
Go module under GitLab subgroup is not detected when GOPROXY is not set

### ISSUE THREAD

**Issue by at-wat** [renovatebot/renovate#16743]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.122.6

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I found it during testing https://github.com/renovatebot/renovate/pull/16712 and I don't actually use Go modules under GitLab subgroup.

Reproduction repository: https://github.com/at-wat/renovate-16712/pulls
PRs with `[local no-GOPROXY]` are created by self-hosted Renovate without GOPROXY.
**Expected**: `Update module gitlab.com/at-wat-group/subgroup/renovate-test/submodule to v1.0.3` is created
**Actual**: not created

As in the attached log, Renovate tries to `git ls-remote` https://gitlab.com/at-wat-group/subgroup/renovate-test/submodule.

https://gitlab.com/at-wat-group/subgroup/renovate-test/submodule?go-get=1 returns
```html
<html><head>
<meta name="go-import" content="gitlab.com/at-wat-group/subgroup/renovate-test git https://gitlab.com/at-wat-group/subgroup/renovate-test.git" />
<meta name="go-source" content="gitlab.com/at-wat-group/subgroup/renovate-test https://gitlab.com/at-wat-group/subgroup/renovate-test https://gitlab.com/at-wat-group/subgroup/renovate-test/-/tree/main{/dir} https://gitlab.com/at-wat-group/subgroup/renovate-test/-/blob/main{/dir}/{file}#L{line}" />
</head><body>
go get https://gitlab.com/at-wat-group/subgroup/renovate-test
</body></html>
```
which says the client should fetch https://gitlab.com/at-wat-group/subgroup/renovate-test for this module.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Datasource unknown error (repository=at-wat/renovate-16712)
       "datasource": "go",
       "packageName": "gitlab.com/at-wat-group/subgroup/renovate-test/submodule",
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "https://**redacted**@gitlab.com/at-wat-group/subgroup/renovate-test/submodule",
             "refs/tags/v*"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: The project you were looking for could not be found or you don't have permission to view it.\nfatal: repository 'https://gitlab.com/at-wat-group/subgroup/renovate-test/submodule/' not found\n",
         "stack": "Error: remote: The project you were looking for could not be found or you don't have permission to view it.\nfatal: repository 'https://gitlab.com/at-wat-group/subgroup/renovate-test/submodule/' not found\n\n    at Object.action (/home/at-wat/Projects/renovate/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/home/at-wat/Projects/renovate/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /home/at-wat/Projects/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/at-wat/Projects/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/home/at-wat/Projects/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/at-wat/Projects/renovate/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by micronull** [comment]
We have the same problem. We use GOPRIVATE for our private gitlab repository.

**Comment by rrey** [comment]
Facing the issue as well with self-hosted GItlab (`16.5`) and renovate `37.288.0`.

Redacted log processing the submodule:
```

DEBUG: Fetching gitlab.example.com/group/subgroup/repository1/gosubmodule via GONOPROXY match (repository=group/subgroup/repository2)
DEBUG: hostRules: no authentication for gitlab.example.com (repository=group/subgroup/repository2)
DEBUG: Fetching gitlab.example.com/group/subgroup/repository1 via GONOPROXY match (repository=group/subgroup/repository2)
DEBUG: Go lookup source url https://gitlab.example.com/group/subgroup for module gitlab.example.com/group/subgroup/repository1/gosubmodule (repository=group/subgroup/repository2)
DEBUG: Go lookup source url https://gitlab.example.com/group/subgroup for module gitlab.example.com/group/subgroup/repository1 (repository=group/subgroup/repository2)
DEBUG: GET https://gitlab.example.com/api/v4/projects/group%2Fsubgroup%2Frepository1%2Fgosubmodule/repository/tags?per_page=100 = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=38) (repository=group/subgroup/repository2)
DEBUG: GitLab API 404 (repository=group/subgroup/repository2)
       "url": "https://gitlab.example.com/api/v4/projects/group%2Fsubgroup%2Frepository1%2Fgosubmodule/repository/tags?per_page=100"
DEBUG: Datasource 404 (repository=group/subgroup/repository2)
       "datasource": "go",
       "packageName": "gitlab.example.com/group/subgroup/repository1/gosubmodule",
       "url": "https://gitlab.example.com/api/v4/projects/group%2Fsubgroup%2Frepository1%2Fgosubmodule/repository/tags?per_page=100"
DEBUG: Failed to look up go package gitlab.example.com/group/subgroup/repository1/gosubmodule (repository=group/subgroup/repository2, packageFile=go.mod, dependency=gitlab.example.com/group/subgroup/repository1/gosubmodule)
```

This makes renovate unable to process go submodules located in a repository under sub-groups in GitLab.

**Comment by RPCMoritz** [comment]
I have a suspicion:
https://docs.gitlab.com/ee/api/rest/#personalprojectgroup-access-tokens documents that basic auth does not work for API requests (verified, if I use a PAT in the way documented, access works, basic auth fails with 404).
Without having looked at the source code yet, I assume that is the underlying problem here, and potentially something that Gitlab changed at some point, or where the inconsistency within Gitlab (basic auth works elsewhere) is tripping up the code.

I'll have a look into the code, and see if I can just change the URL, then that would be an easy fix.

**Comment by RPCMoritz** [comment]
I did an initial analysis, and it looks like this line: https://github.com/renovatebot/renovate/blob/da1a5c76bb5e54f8d20aecb0cecb2ac5d61955ae/lib/util/http/auth.ts#L70 should inject the credentials in the right way.

**Comment by rrey** [comment]
@RPCMoritz see this comment I made on Gitlab : https://gitlab.com/gitlab-org/gitlab/-/issues/36354#note_1872690860

The maintainer answered that basic auth with token will not work and that .netrc is the only thing designed to work because it is supported by Go.
