### ISSUE TITLE
Ignorepaths not completely working

### ISSUE THREAD

**Issue by robvdnieuw** [renovatebot/renovate#16753]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.122.4

### Please select which platform you are using if self-hosting.

Azure DevOps Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

Azure DevOps Server 2020 Update 1.1

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

after the previous issue we reported we now see the file that is causing the error. But we have added that path to the ignorepaths, so we expect that the file would be ignored.

Configuration:

 "extends" : [
    "config:base",
    "group:allNonMajor",
    ":preserveSemverRanges"
  ],
  "ignorePaths": [
           "**/IPC/python-based/**"
   ],

### Relevant debug logs

<details><summary>Logs</summary>

```
}
           ],
           "azureWorkItemId": 395202,
           "platformAutomerge": true
         }
  DEBUG: massaged config (repository=OCC/COES)
         "config": {
           "$schema": "[https://docs.renovatebot.com/renovate-schema.json",](https://docs.renovatebot.com/renovate-schema.json%22,)
           "extends": [
             "config:base",
             "config:base",
             "group:allNonMajor",
             ":preserveSemverRanges"
           ],
           "ignorePaths": ["**/IPC/python-based/**"],
           "lockFileMaintenance": {"enabled": true},
           "baseBranches": ["main"],
           "packageRules": [
             {
               "description": ["Pin typescript for angular 12"],
               "matchFiles": [
                 "COES/Test.Build.DotNetwithAngular/ClientApp/package.json"
               ],
               "matchPackageNames": ["typescript"],
               "allowedVersions": ">=4.2.3 <4.3"
             },
             {
               "description": [
                 "disable all the default maven/gradle updates due to Renovate issue"
               ],
               "matchManagers": ["gradle"],
               "enabled": false
             }
           ],
           "azureWorkItemId": 395202,
           "platformAutomerge": true
         }

  DEBUG: failed to parse file as XML document (repository=OCC/COES, branch=renovate/all-minor-patch)
         "err": {
           "message": "Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: d",
           "stack": "Error: Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: d\n    at error (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\sax\\lib\\sax.js:651:10)\n    at strictFail (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\sax\\lib\\sax.js:677:7)\n    at beginWhiteSpace (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\sax\\lib\\sax.js:951:7)\n    at SAXParser.write (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\sax\\lib\\sax.js:1006:11)\n    at new XmlDocument (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\xmldoc\\lib\\xmldoc.js:295:17)\n    at readFileAsXmlDocument (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\modules\\manager\\nuget\\util.js:14:21)\n    at async getDependentPackageFiles (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\modules\\manager\\nuget\\package-tree.js:34:21)\n    at async updateArtifacts (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\modules\\manager\\nuget\\artifacts.js:84:13)\n    at async getUpdatedPackageFiles (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\update\\branch\\get-updated.js:197:29)\n    at async processBranch (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\update\\branch\\index.js:292:21)\n    at async writeUpdates (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\process\\write.js:25:21)\n    at async update (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\process\\extract-update.js:109:15)\n    at async Object.renovateRepository (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\index.js:43:25)\n    at async Object.start (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\global\\index.js:119:13)\n    at async C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\renovate.js:15:24"
         },
         "file": "interfaces/IPC/python-based/templates/cs/&{module.name.lower()}/csharp/&{module.name.lower()}.csharp.csproj"
   WARN: Error updating branch (repository=OCC/COES, branch=renovate/all-minor-patch)
         "err": {
           "message": "Invalid xml file: interfaces/IPC/python-based/templates/cs/&{module.name.lower()}/csharp/&{module.name.lower()}.csharp.csproj",
           "stack": "Error: Invalid xml file: interfaces/IPC/python-based/templates/cs/&{module.name.lower()}/csharp/&{module.name.lower()}.csharp.csproj\n    at getDependentPackageFiles (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\modules\\manager\\nuget\\package-tree.js:36:19)\n    at async updateArtifacts (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\modules\\manager\\nuget\\artifacts.js:84:13)\n    at async getUpdatedPackageFiles (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\update\\branch\\get-updated.js:197:29)\n    at async processBranch (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\update\\branch\\index.js:292:21)\n    at async writeUpdates (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\process\\write.js:25:21)\n    at async update (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\process\\extract-update.js:109:15)\n    at async Object.renovateRepository (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\repository\\index.js:43:25)\n    at async Object.start (C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\workers\\global\\index.js:119:13)\n    at async C:\\agent01\\_work\\396\\s\\RenovateBot\\RenovateBot\\node_modules\\renovate\\dist\\renovate.js:15:24"
         }

```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment]
Prettified Renovate config:

```json
{
  "extends": ["config:base", "group:allNonMajor", ":preserveSemverRanges"],
  "ignorePaths": ["/IPC/python-based/"]
}
```
