### ISSUE TITLE
Updates of php dependencies fails with "Process exited with exit code "2""

### ISSUE THREAD

**Issue by kolaente** [renovatebot/renovate#16874]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.135.1 via docker renovate/renovate:32

### Please select which platform you are using if self-hosting.

Gitea

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitea 1.17.0

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When renovate tries to update a dependency in a project which manages dependencies with composer, it fails with this comment:

> ⚠ Artifact update problem
>
> Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.
> 
> ♻ Renovate will retry this branch, including artifacts, only when one of the following happens:
> 
> * any of the package files in this branch needs updating, or
> * the branch becomes conflicted, or
> * you click the rebase/retry checkbox if found above, or
>* you rename this PR's title to start with "rebase!" to trigger it manually
>
> The artifact failure details are included below:
> File name: composer.lock
> 
> Process exited with exit code "2"

### Relevant debug logs

<details><summary>Logs</summary>

```
{
  "name": "renovate",
  "hostname": "f7d4b05fe7b7",
  "pid": 20,
  "level": 40,
  "logContext": "6vsE_iN293tlv3USJPbej",
  "repository": "org/repo",
  "branch": "renovate/laravel-framework-9.x",
  "artifactErrors": [
    {
      "lockFile": "composer.lock",
      "stderr": "Process exited with exit code \"2\""
    }
  ],
  "msg": "artifactErrors",
  "time": "2022-07-31T14:07:08.453Z",
  "v": 0
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by elchenberg** [comment]
Same problem here with renovate v32.137.0.

`stderr` already contains the message that would be helpful in that situation, for example:

```
DEBUG: composer command (repository=**redacted**, branch=renovate/codeception-module-asserts-3.x)
       "cmd": "composer",
       "args": "update codeception/module-asserts --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins"
DEBUG: Executing command (repository=**redacted**, branch=renovate/codeception-module-asserts-3.x)
       "command": "composer update codeception/module-asserts --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins"
DEBUG: rawExec err (repository=**redacted**, branch=renovate/codeception-module-asserts-3.x)
       "err": {
         "name": "ExecError",
         "cmd": "/bin/sh -c composer update codeception/module-asserts --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins",
         "stderr": "Loading composer repositories with package information\nInfo from https://repo.packagist.org: #StandWithUkraine\nDependency codeception/codeception is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.\nDependency codeception/phpunit-wrapper is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.\nDependency phpunit/phpunit is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.\nUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - codeception/codeception is locked to version 4.2.1 and an update of this package was not requested.\n    - codeception/module-asserts 3.0.0 conflicts with codeception/codeception <5.0.\n    - Root composer.json requires codeception/module-asserts 3.0.0 -> satisfiable by codeception/module-asserts[3.0.0].\n\nUse the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.\n",
         "stdout": "",
         "options": {
           "cwd": "/tmp/renovate/repos/gitlab/**redacted**",
           "encoding": "utf-8",
           "env": {
             "COMPOSER_CACHE_DIR": "/tmp/renovate/cache/others/composer",
             "COMPOSER_AUTH": "{\"github-oauth\":{\"github.com\":\"**redacted**\"},\"gitlab-token\":{\"**redacted**\":\"**redacted**\"},\"gitlab-domains\":[\"**redacted**\"]}",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.10.5/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 2,
         "message": "Process exited with exit code \"2\"",
         "stack": "ExecError: Process exited with exit code \"2\"\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/lib/util/exec/common.ts:95:16)\n    at ChildProcess.emit (events.js:412:35)\n    at ChildProcess.emit (domain.js:475:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)"
       }
DEBUG: Failed to generate composer.lock (repository=**redacted**, branch=renovate/codeception-module-asserts-3.x)
       "err": {
         "name": "ExecError",
         "cmd": "/bin/sh -c composer update codeception/module-asserts --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins",
         "stderr": "Loading composer repositories with package information\nInfo from https://repo.packagist.org: #StandWithUkraine\nDependency codeception/codeception is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.\nDependency codeception/phpunit-wrapper is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.\nDependency phpunit/phpunit is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.\nUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - codeception/codeception is locked to version 4.2.1 and an update of this package was not requested.\n    - codeception/module-asserts 3.0.0 conflicts with codeception/codeception <5.0.\n    - Root composer.json requires codeception/module-asserts 3.0.0 -> satisfiable by codeception/module-asserts[3.0.0].\n\nUse the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.\n",
         "stdout": "",
         "options": {
           "cwd": "/tmp/renovate/repos/gitlab/**redacted**",
           "encoding": "utf-8",
           "env": {
             "COMPOSER_CACHE_DIR": "/tmp/renovate/cache/others/composer",
             "COMPOSER_AUTH": "{\"github-oauth\":{\"github.com\":\"**redacted**\"},\"gitlab-token\":{\"**redacted**\":\"**redacted**\"},\"gitlab-domains\":[\"**redacted**\"]}",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.10.5/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 2,
         "message": "Process exited with exit code \"2\"",
         "stack": "ExecError: Process exited with exit code \"2\"\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/lib/util/exec/common.ts:95:16)\n    at ChildProcess.emit (events.js:412:35)\n    at ChildProcess.emit (domain.js:475:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)"
       }
```

**Comment by rarkins** [comment]
@elchenberg it does not seem to be the same problem, and also not a renovate problem unless there's additional info you've left out. Please create your own GitHub discussion if so

**Comment by rarkins** [comment]
@elchenberg sorry, based on your discussion it looks like we can treat this as the same. I got confused when reading your previous comment. We should copy in the stderr like you suggest

**Comment by elchenberg** [comment]
@rarkins Sorry for that confusing comment! :smile:

**Comment by PhilipAbed** [comment]
should be solved by this PR https://github.com/renovatebot/renovate/pull/16961
can you please confirm

**Comment by kolaente** [comment]
Looks like its fixed.
