### ISSUE TITLE
Release notes fetches fail on hosted gitlab

### ISSUE THREAD

**Issue by growse** [renovatebot/renovate#16896]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.122.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitlab EE 14.9.2-ee

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When running against a repository that includes a `.gitlab-ci.yml` pipeline which in turn uses a `includes` section referencing a different project tag on the same instance, then updates for that tag fail.

E.g. with a repo where the following is in the `.gitlab-ci.yml` file:

```
include:
  - project: 'my.group/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'
    ref: v8.152.0
```

Renovate fails getting the releasenotes for this repository, because it tries to call `linkify` on the releasenotes body, which appears to try and render the markdown using remarkjs and the `remarkjs-github` plugin. This plugin the seems to try and figure out what github repo its hosted on, which fails with an error:

```
Error linkifying (repository=Andrew.Rowson/renovate-runner)
       "err": {
         "message": "Missing `repository` field in `options`",
```

There's some logic in `release-notes` where this function doesn't get called if `baseUrl` is `https://gitlab.com`, but it's obivously not a safe assumption that the dependency is on github if that isn't true.

https://github.com/renovatebot/renovate/blob/2f93a5e064730161c574aa7b5d7aafdf99d3290c/lib/workers/repository/update/pr/changelog/release-notes.ts#L169-L178

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Error linkifying (repository=my.group/renovate-runner)
       "err": {
         "message": "Missing `repository` field in `options`",
         "stack": "Error: Missing `repository` field in `options`\n  
  at Function.github (/usr/src/app/node_modules/remark-github/index.js:99:11)\n  
  at freeze (/usr/src/app/node_modules/unified/index.js:125:31)\n  
  at Function.process (/usr/src/app/node_modules/unified/index.js:349:5)\n  
  at linkify (/usr/src/app/node_modules/renovate/lib/util/markdown.ts:38:6)\n  
  at releaseNotesResult (/usr/src/app/node_modules/renovate/lib/workers/repository/update/pr/changelog/release-notes.ts:172:42)\n  
  at getReleaseNotes (/usr/src/app/node_modules/renovate/lib/workers/repository/update/pr/changelog/release-notes.ts:132:24)\n  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)\n  
  at addReleaseNotes (/usr/src/app/node_modules/renovate/lib/workers/repository/update/pr/changelog/release-notes.ts:403:24)\n  
  at Object.getChangeLogJSON (/usr/src/app/node_modules/renovate/lib/workers/repository/update/pr/changelog/source-gitlab.ts:153:9)\n  
  at getChangeLogJSON (/usr/src/app/node_modules/renovate/lib/workers/repository/update/pr/changelog/index.ts:33:15)\n  
  at embedChangelog (/usr/src/app/node_modules/renovate/lib/workers/repository/changelog/index.ts:7:21)\n  
  at /usr/src/app/node_modules/p-map/index.js:57:22""
       },
       "baseUrl": "https://my-hosted-gitlab.example.com/"
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
It's hard for any non-gitlab self-hosted user to work on this, so this probably requires a community contribution.

Instead of looking hardcoded for `gitlab.com` we should leverage our [detectPlatform](https://github.com/renovatebot/renovate/blob/fb9303c19081e341c123581c00b3e72701c1c8c9/lib/modules/platform/util.ts#L14) function
