### ISSUE TITLE
Cannot find @redis/client running renovate bot

### ISSUE THREAD

**Issue by kwlin** [renovatebot/renovate#16890]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest (32.136.0)

### Please select which platform you are using if self-hosting.

Azure DevOps (dev.azure.com)

### If you're self-hosting Renovate, tell us what version of the platform you run.

Azure DevOps 

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Our build pipeline with Renovate Bot (32.136.0/latest version) fails to install Renovate Bot with the following message:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@redis/client'
Require stack:
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\decorator.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\datasource\docker\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\ansible\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\api.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\config\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\workers\global\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\renovate.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\index.js:7:41)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\redis\\dist\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\redis.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\decorator.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\datasource\\docker\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\ansible\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\api.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\config\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\workers\\global\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\renovate.js'
  ]
}
```

It seems that it can't find @redis/client npm package

### Relevant debug logs

<details><summary>Logs</summary>

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@redis/client'
Require stack:
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\decorator.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\datasource\docker\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\ansible\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\api.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\config\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\workers\global\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\renovate.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\index.js:7:41)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\redis\\dist\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\redis.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\decorator.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\datasource\\docker\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\ansible\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\api.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\config\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\workers\\global\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\renovate.js'
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
What is the log from your npm install command?

**Comment by kwlin** [comment]
@rarkins 

We're executing with the following command:

```
        git config --global user.email 'bot@renovateapp.com'
        git config --global user.name 'Renovate Bot'
        npx renovate
```

the output of the command is:

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@redis/client'
Require stack:
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\decorator.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\datasource\docker\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\ansible\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\api.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\config\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\workers\global\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\renovate.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\index.js:7:41)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\redis\\dist\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\redis.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\decorator.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\datasource\\docker\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\ansible\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\api.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\config\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\workers\\global\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\renovate.js'
  ]
}
```

Can I add any logging arguments to npx command?

**Comment by viceice** [comment]
Looks like an npm / registry issue. Are you using a custom npm registry? or any other npm related global settings?


works on my local WSL2 ubuntu

**Comment by kwlin** [comment]
Hi @viceice ,

not that I know of. But I'm not an expert in npm :) 

* Is there a specific command I can execute to check? I would gladly check it out.
* Should I explicit install @redis/client (like node-gyp) with npm before executing npx Renovate?

Our current template yaml file is:
```
parameters:
  - name: RenovateConfigFile
    type: string

steps:
  #  Install/setup dependencies for WhiteSource Renovate
  - task: UseNode@1
    displayName: 'Use node'
    inputs:
      version: '16.x'
      checkLatest: true

  - task: Npm@1
    displayName: 'NPM install'
    inputs:
      command: 'install'

  # Build tools for NodeJS (https://www.npmjs.com/package/@mapbox/node-pre-gyp)
  - task: PowerShell@2
    displayName: 'install node-gy'
    inputs:
      targetType: 'inline'
      script: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}      
  # Build & deployment tools for NodeJS (https://www.npmjs.com/package/@mapbox/node-pre-gyp)
  - script: npm i @mapbox/node-pre-gyp
    displayName: 'install node-pre-gyp'

  # Setup node-gyp
  - task: PowerShell@2
    displayName: 'config npm the visual studio folder'
    inputs:
      targetType: 'inline'
      script: |
        if (Test-Path -Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise") {
          npm config set msvs_version "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        } else {
          npm config set msvs_version "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
        }

  # Run, Forest! Run!
  - task: PowerShell@2
    displayName: 'Execute Renovate'
    inputs:
      targetType: 'inline'
      script: |
        git config --global user.email 'bot@renovateapp.com'
        git config --global user.name 'Renovate Bot'
        npx renovate
    env:
      TOKEN: $(System.AccessToken)
      GITHUB_COM_TOKEN: $(GITHUB_COM_PAT_TOKEN)
      LOG_LEVEL: $(LOG_LEVEL)
      RENOVATE_CONFIG_FILE: ${{ parameters.RenovateConfigFile }}
    retryCountOnTaskFailure: 3
```

Our current config looks like this
```
module.exports = {
  baseDir: 'c:/w',
  platform: 'azure',
  endpoint: 'https://dev.azure.com/xxx/',
  token: process.env.TOKEN,
  hostRules: [
    {
      hostType: 'docker',
      matchHost: 'xxx.io',
      username: '',
      password: process.env.TOKEN,
    },
    {
      hostType: 'npm',
      matchHost: 'pkgs.dev.azure.com',
      username: 'apikey',
      password: process.env.TOKEN,
    },
    {
      hostType: 'nuget',
      matchHost: 'pkgs.dev.azure.com',
      username: '',
      password: process.env.TOKEN,
    },
  ],
  onboardingConfig: {
    extends: ['config:base'],
  },
  repositories: [
    'Products/xxx'
  ],
};
```

Output of the yaml build is:
```

Starting: Use node
==============================================================================
Task         : Use Node.js ecosystem
Description  : Set up a Node.js environment and add it to the PATH, additionally providing proxy support
Version      : 1.206.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
Found tool in cache: node 16.16.0 x64
Prepending PATH environment variable with directory: D:\a\_tool\node\16.16.0\x64
Finishing: Use node


Starting: NPM install
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.202.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tool\node\16.16.0\x64\npm.cmd --version"
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.11.0
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tool\node\16.16.0\x64\npm.cmd config list"
; "env" config from environment

userconfig = "D:\\a\\18\\npm\\339574.npmrc" 

; node bin location = D:\a\_tool\node\16.16.0\x64\node.exe
; node version = v16.16.0
; npm local prefix = D:\a\18\s
; npm version = 8.11.0
; cwd = D:\a\18\s
; HOME = C:\Users\AzDevOps
; Run `npm config ls -l` to show all defaults.
C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tool\node\16.16.0\x64\npm.cmd install"
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

up to date, audited 1 package in 305ms

found 0 vulnerabilities
Finishing: NPM install


Starting: install node-gy
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\daa1219a-3977-4290-88f9-b80d9f644892.ps1'"
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 94 packages, and audited 95 packages in 4s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Finishing: install node-gy


Starting: install node-pre-gyp
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents: shell
npm i @mapbox/node-pre-gyp
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\ae7371ec-2e62-4838-9f2a-b3f5a52dff1b.cmd""
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

added 56 packages, and audited 57 packages in 3s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Finishing: install node-pre-gyp


Starting: config npm the visual studio folder
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\164502a5-8b9f-49b9-a9c3-3e761a057583.ps1'"
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Finishing: config npm the visual studio folder


    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\index.js:7:41)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\redis\\dist\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\redis.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\util\\cache\\package\\decorator.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\datasource\\docker\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\ansible\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\api.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\modules\\manager\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\config\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\workers\\global\\index.js',
    'C:\\Users\\AzDevOps\\AppData\\Local\\npm-cache\\_npx\\05eeecd92f4e18e0\\node_modules\\renovate\\dist\\renovate.js'
  ]
}
##[error]PowerShell exited with code '1'.
##[warning]RetryHelper encountered task failure, will retry (attempt #: 1 out of 3) after 1000 ms
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\b8cf8c12-f1f4-46c0-9f49-810a9eff86c6.ps1'"
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@redis/client'
Require stack:
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\decorator.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\datasource\docker\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\ansible\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\api.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\modules\manager\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\config\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\workers\global\index.js
- C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\renovate.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\redis\dist\index.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AzDevOps\AppData\Local\npm-cache\_npx\05eeecd92f4e18e0\node_modules\renovate\dist\util\cache\package\redis.js:6:17)

```
