### ISSUE TITLE
renovate-config-validator fails on private repo presets

### ISSUE THREAD

**Issue by joekur** [renovatebot/renovate#17007]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

I believe this has to do with https://github.com/renovatebot/renovate/pull/16468

`renovate-config-validator` has started to fail. We have a private repo that hosts the presets, and private repos that extend those presets.

Example run:
```
❯ LOG_LEVEL=debug RENOVATE_CONFIG_FILE=js-libs.json5 npx -p renovate@latest renovate-config-validator
DEBUG: Using RE2 as regex engine
DEBUG: Checking for config file in /Users/joekurleto/dev/renovate-config/js-libs.json5
 INFO: Validating js-libs.json5
DEBUG: GitHub 404
       "url": "https://api.github.com/repos/stitchfix/renovate-config/contents/js-shared.json5"
DEBUG: Failed to retrieve js-shared.json5 from repo
       "statusCode": 404,
       "url": "https://api.github.com/repos/stitchfix/renovate-config/contents/js-shared.json5"
DEBUG: Could not resolve preset during config validation
       "err": {
         "message": "dep not found",
         "stack": "Error: dep not found\n    at fetchJSONFile (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config/presets/github/index.js:30:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async fetchPreset (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config/presets/util.js:36:23)\n    at async getPreset (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config/presets/index.js:182:24)\n    at async validateConfig (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config/validation.js:242:41)\n    at async validate (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config-validator.js:24:17)\n    at async /Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config-validator.js:102:21"
       },
       "preset": "github>stitchfix/renovate-config:js-shared.json5"
ERROR: js-libs.json5 contains errors
       "errors": [
         {
           "topic": "Configuration Warning",
           "message": "Invalid Preset github>stitchfix/renovate-config:js-shared.json5"
         }
       ]
```

The failing config file has the following:

```json5
extends: [
    "github>stitchfix/renovate-config:js-shared.json5",
]
```

In this case the `stitchfix/renovate-config` repo is private. I can understand why this is 404ing, but I'm not sure how it's intended to work?

### Relevant debug logs

<details><summary>Logs</summary>

```
❯ LOG_LEVEL=debug RENOVATE_CONFIG_FILE=js-libs.json5 npx -p renovate@latest renovate-config-validator
DEBUG: Using RE2 as regex engine
DEBUG: Checking for config file in /Users/joekurleto/dev/renovate-config/js-libs.json5
 INFO: Validating js-libs.json5
DEBUG: GitHub 404
       "url": "https://api.github.com/repos/stitchfix/renovate-config/contents/js-shared.json5"
DEBUG: Failed to retrieve js-shared.json5 from repo
       "statusCode": 404,
       "url": "https://api.github.com/repos/stitchfix/renovate-config/contents/js-shared.json5"
DEBUG: Could not resolve preset during config validation
       "err": {
         "message": "dep not found",
         "stack": "Error: dep not found\n    at fetchJSONFile (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config/presets/github/index.js:30:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async fetchPreset (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config/presets/util.js:36:23)\n    at async getPreset (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config/presets/index.js:182:24)\n    at async validateConfig (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config/validation.js:242:41)\n    at async validate (/Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config-validator.js:24:17)\n    at async /Users/joekurleto/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/config-validator.js:102:21"
       },
       "preset": "github>stitchfix/renovate-config:js-shared.json5"
ERROR: js-libs.json5 contains errors
       "errors": [
         {
           "topic": "Configuration Warning",
           "message": "Invalid Preset github>stitchfix/renovate-config:js-shared.json5"
         }
       ]
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by mlarente** [comment]
I have the same problem on GitLab self-hosted.

**Comment by rarkins** [comment]
@PhilipAbed

**Comment by viceice** [comment]
@rarkins that's what I expected from the recent validation change for presets. 🙈

**Comment by rarkins** [comment]
Let's revert until we can think if/how this can work

**Comment by viceice** [comment]
sounds good

**Comment by rarkins** [comment]
Perhaps we default to warn and add the capability to --strict=true to error when not found

**Comment by PhilipAbed** [comment]
Can u revert it somehow fast or should i create a revert PR?

**Comment by PhilipAbed** [comment]
can we instead check if its error `statusCode 404`  and ignore? that way ignore errors that come from private repo for now?
i mean here
https://github.com/PhilipAbed/renovate/blob/44a96404e4d6f97cd6e03bcfc47c2e711340620f/lib/config/validation.ts#L278-L285

**Comment by rarkins** [comment]
I don't recall seeing it reverted already. I don't think you can distinguish between a 404 from a typo and a 404 from private

**Comment by viceice** [comment]
- #17012

seeing same on gitea

**Comment by PhilipAbed** [comment]
fix for https://github.com/renovatebot/renovate/issues/15999 was reverted,
the issue has beeen re-opened.

Closing this.
