### ISSUE TITLE
"RangeError: Invalid string length" when sanitizing secrets

### ISSUE THREAD

**Issue by cdemire1** [renovatebot/renovate#17196]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:32.156.0-slim

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I use the renovate bot with the following github action from the example. https://github.com/renovatebot/github-action#example.

I redacted the config details and shared the keys used for configuration in debug logs.

Action fails to execute with the below error.

```
 Status: Downloaded newer image for renovate/renovate:32.156.0-slim
 WARN: Config needs migrating
       "originalConfig": {
...
       },
       "migratedConfig": {
...
       }

/usr/src/app/node_modules/renovate/lib/util/sanitize.ts:32
  [globalSecrets, repoSecrets].forEach((secrets) => {
                               ^
RangeError: Invalid string length
    at String.replace (<anonymous>)
    at /usr/src/app/node_modules/renovate/lib/util/sanitize.ts:35:25
    at Set.forEach (<anonymous>)
    at /usr/src/app/node_modules/renovate/lib/util/sanitize.ts:33:13
    at Array.forEach (<anonymous>)
    at sanitize (/usr/src/app/node_modules/renovate/lib/util/sanitize.ts:32:32)
    at sanitizeValue (/usr/src/app/node_modules/renovate/lib/logger/utils.ts:106:20)
    at sanitizeValue (/usr/src/app/node_modules/renovate/lib/logger/utils.ts:157:52)
    at Object.write (/usr/src/app/node_modules/renovate/lib/logger/utils.ts:181:19)
    at Logger._emit (/usr/src/app/node_modules/bunyan/lib/bunyan.js:923:22)
    at Logger.error (/usr/src/app/node_modules/bunyan/lib/bunyan.js:1045:24)
    at Object.error (/usr/src/app/node_modules/renovate/lib/logger/index.ts:68:26)
    at process.<anonymous> (/usr/src/app/node_modules/renovate/lib/renovate.ts:9:10)
    at process.emit (node:events:527:28)
    at process.emit (/usr/src/app/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/renovatebot/github-action/v32.156.0/dist/index.js:1679:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/renovatebot/github-action/v32.156.0/dist/index.js:1662:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/renovatebot/github-action/v32.156.0/dist/index.js:1556:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Error: Error: The process '/usr/bin/docker' failed with exit code 1
```

I found the following https://www.garysieling.com/blog/fixing-node-error-invalid-string-length/ which looks relevant.

### Relevant debug logs

<details><summary>Logs</summary>

```
Status: Downloaded newer image for renovate/renovate:32.156.0-slim
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /github-action/renovate-config.js
 WARN: Config needs migrating
       "originalConfig": {
        ...
       },
       "migratedConfig": {
        ...
       }
DEBUG: File config
       "config": {
        ...
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": [], "binarySource": "docker", "token": "***********"}
DEBUG: Combined config
       "config": {
         "dryRun": "full",
         "gitAuthor": "<email>",
         "onboarding": false,
         "platform": "github",
         "repositories": ["<repo>"],
         "username": "<username>",
         "hostRules": [],
         "binarySource": "docker",
         "token": "***********"
       }
DEBUG: Found valid git version: 2.37.2
DEBUG: Using default github endpoint: https://api.github.com/
DEBUG: Platform config
       "platformConfig": {
         "hostType": "github",
         "endpoint": "https://api.github.com/",
         "isGHApp": true,
         "isGhe": false
       },
       "renovateUsername": "<username>"
DEBUG: Using configured gitAuthor (<email>)
DEBUG: Adding token authentication for api.github.com to hostRules

<--- Last few GCs --->

[8:0x6564640]    52684 ms: Scavenge 2036.2 (2074.7) -> 2036.3 (2079.7) MB, 14.3 / 0.0 ms  (average mu = 0.218, current mu = 0.181) allocation failure 
[8:0x6564640]    52724 ms: Scavenge 2039.1 (2079.7) -> 2039.3 (2080.7) MB, 16.7 / 0.0 ms  (average mu = 0.218, current mu = 0.181) allocation failure 
[8:0x6564640]    52748 ms: Scavenge 2040.1 (2080.7) -> 2039.8 (2091.7) MB, 19.6 / 0.0 ms  (average mu = 0.218, current mu = 0.181) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb0a860 node::Abort() [/opt/buildpack/tools/node/16.16.0/bin/node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [/opt/buildpack/tools/node/16.16.0/bin/node]
 3: 0xcf9a6e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/buildpack/tools/node/16.16.0/bin/node]
 4: 0xcf9de7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/buildpack/tools/node/16.16.0/bin/node]
 5: 0xeb1685  [/opt/buildpack/tools/node/16.16.0/bin/node]
 6: 0xeb2166  [/opt/buildpack/tools/node/16.16.0/bin/node]
 7: 0xec068e  [/opt/buildpack/tools/node/16.16.0/bin/node]
 8: 0xec10d0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/buildpack/tools/node/16.16.0/bin/node]
 9: 0xec3fc5 v8::internal::Heap::HandleGCRequest() [/opt/buildpack/tools/node/16.16.0/bin/node]
10: 0xe51667 v8::internal::StackGuard::HandleInterrupts() [/opt/buildpack/tools/node/16.16.0/bin/node]
11: 0x11fda25 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/opt/buildpack/tools/node/16.16.0/bin/node]
12: 0x15f2d39  [/opt/buildpack/tools/node/16.16.0/bin/node]
Error: The process '/usr/bin/docker' failed with exit code 134
    at ExecState._setResult (/home/runner/work/_actions/renovatebot/github-action/v32.156.0/dist/index.js:1679:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/renovatebot/github-action/v32.156.0/dist/index.js:1662:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/renovatebot/github-action/v32.156.0/dist/index.js:1556:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Error: Error: The process '/usr/bin/docker' failed with exit code 134
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Renovate
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
it seems you have a `null` or `undefined` value for a secret, you should fix your config
