### ISSUE TITLE
"fatal: ambiguous argument..." when running git diff during branch push

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#17319]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

from source

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Although things work, I'm seeing an error logged during the git commit/push.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: git commit (repository=renovate-tests/npm101)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/configure",
         "commit": "29ce6d29147bf5190831a3afdfda544eed2e7a6e",
         "root": false,
         "summary": {"changes": 1, "insertions": 3, "deletions": 0}
       }
DEBUG: Git function thrown (repository=renovate-tests/npm101)
       "err": {
         "task": {
           "commands": ["diff", "HEAD", "origin/renovate/configure"],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/dist/cjs/index.js:55:24)"
       }
DEBUG: Pushing branch renovate/configure (repository=renovate-tests/npm101)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by Gabriel-Ladzaretti** [comment]
When using the repro, be sure to remove the `renovate.json` as i was able to reproduce this when committing to the `renovate/configure` branch i.e. onboarding.

<details><summary>log</summary>

```
DEBUG: git commit (repository=ladzaretti/npm101)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/configure",
         "commit": "5d3aeecf5373fd1029a92d40a511bf150a041129",
         "root": false,
         "summary": {"changes": 1, "insertions": 3, "deletions": 0}
       }
DEBUG: Git function thrown (repository=ladzaretti/npm101)
       "err": {
         "task": {
           "commands": ["diff", "HEAD", "origin/renovate/configure"],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'
git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like thi
s:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (C:\\projects\\ladzaretti-renovate\\node_modules\\simple-git\\src\\lib\\plugins\\error-detection.plugin.ts:4
2:29)\n    at PluginStore.exec (C:\\projects\\ladzaretti-renovate\\node_modules\\simple-git\\src\\lib\\plugins\\plugin-store.ts:29:29)\n    at C:\\projects\\ladzaretti-renovate\\node_
modules\\simple-git\\src\\lib\\runners\\git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (C:\\projects\\ladzaretti-renovate\\node
_modules\\simple-git\\src\\lib\\runners\\git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (C:\\projects\\ladzaretti-renovate\\node_modules\\simple-git\\src\\lib\\run
ners\\git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\projects\\ladzaretti-renovate\\node_modules\\simple-git\\dist\\cjs\\index.js:55:24)\n  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
DEBUG: Pushing branch renovate/configure (repository=ladzaretti/npm101)
```

</details>

**Comment by rarkins** [comment]
When forking repos, GitHub now offers the option to fork only the default branch (e.g. `main`). This is typically the right thing when we are doing reproductions although occasionally we may *want* to preserve a Renovate branch for reproduction reasons.

**Comment by viceice** [comment]
so it seeems we didn't pushed `renovate/configure` atfer commit, so the `origin/renovate/configure` branch doesn't exist and the diff fails.

**Comment by Gabriel-Ladzaretti** [comment]
> so it seeems we didn't pushed `renovate/configure` atfer commit, so the `origin/renovate/configure` branch doesn't exist and the diff fails.

Based on the logs we indeed pushing the branch after we get this error message. 

The repro had the renovate config committed to the default branch, therefore it has to be removed in order to reproduce this, at least from my experience with it.

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/f02610619242311cf389346d07aa7eb5fe9480d7/lib/util/git/index.ts#L972-L982

`hasDiff` call seems to be wrong

**Comment by viceice** [comment]
we need to check remnote branch existance before we diff

**Comment by rarkins** [comment]
Seems strange that we'd be assuming a remote branch exists when it doesn't though. e.g. could indicate some other root cause

**Comment by uhthomas** [comment]
@rarkins I believe this can be caused when a push fails and repository data is persisted. We've had to update a lot of our commit policies for Renovate and sometimes only find out which when Renovate fails to push. Thus, the branch will exist locally and not remotely for the next run.

**Comment by uhthomas** [comment]
It may also be worth noting that this causes Renovate to hang, which is not great. So I guess there are two things:
- Renovate should check if the remote branch exists before diffing.
- Renovate should not hang when attempting to push. I would have thought a `gitTimeout` would prevent this, but it doesn't.
