### ISSUE TITLE
Renovate fails with external host error - registry.npmjs.org TLS error

### ISSUE THREAD

**Issue by alexg-axis** [renovatebot/renovate#17677]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

For several days we've been missing updates from Renovate. After checking the logs it became apparent that it's due to an external host error. Out of the 20 jobs I can see over at app.renovatebot.com, one succeeded. The rest have been labeled `external-host-error`.  

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Aggregate error is thrown
{
  "err": {
    "name": "AggregateError",
    "message": "\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)",
    "stack": "AggregateError: \n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    at next (/home/ubuntu/renovateapp/node_modules/p-map/index.js:43:14)\n    at /home/ubuntu/renovateapp/node_modules/p-map/index.js:59:6\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
DEBUG: Aggregate error is thrown
{
  "err": {
    "name": "AggregateError",
    "message": "\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22",
    "stack": "AggregateError: \n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at runMicrotasks (<anonymous>)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22\n    at next (/home/ubuntu/renovateapp/node_modules/p-map/index.js:43:14)\n    at /home/ubuntu/renovateapp/node_modules/p-map/index.js:67:7\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
WARN: Host error
{
  "hostType": "npm",
  "packageName": "@yarnpkg/cli",
  "err": {
    "code": "ECONNRESET",
    "host": "registry.npmjs.org",
    "port": 443,
    "message": "Client network socket disconnected before secure TLS connection was established",
    "stack": "Error: Client network socket disconnected before secure TLS connection was established\n    at connResetException (internal/errors.js:639:14)\n    at TLSSocket.onConnectEnd (_tls_wrap.js:1570:19)\n    at TLSSocket.emit (events.js:412:35)\n    at TLSSocket.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
  }
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
What's a recent job ID?

**Comment by alexg-axis** [comment]
803613664

**Comment by alexg-axis** [comment]
Thank you for taking the time. Yes, they are expected - I'll look into fixing the auth issues. When it comes to the error I get, why would I see TLS issues with NPM? I would expect 404s, 401 or something if the issue was private packages, not the TLS error I'm getting.

**Comment by davebarr** [comment]
We've also had timeouts and external host failures.  A lot of `DEBUG: Aggregate error is thrown` in the logs, with stack traces.  `Error: external-host-error\n        at getDependency` ...

We haven't had a successful run in 2 days.  805329817 and 805208511 are recent ones.

**Comment by rarkins** [comment]
Example from @davebarr's repo:

```
{"level":20,"err":{"name":"AggregateError","message":"\n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22","stack":"AggregateError: \n    Error: external-host-error\n        at getDependency (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/get.js:164:19)\n        at async NpmDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/npm/index.js:26:21)\n        at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n        at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:240:23)\n        at async getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:294:34)\n        at async lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:52:51)\n        at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:51:25)\n        at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22\n    at next (/home/ubuntu/renovateapp/node_modules/p-map/index.js:43:14)\n    at /home/ubuntu/renovateapp/node_modules/p-map/index.js:67:7\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"},"msg":"Aggregate error is thrown","time":"2022-09-09T03:55:14.160Z"}
...
...
{"level":20,"dependency":"xxx","msg":"Dependency is disabled","time":"2022-09-09T03:55:20.930Z"}
{"level":40,"msg":"Job timeout","time":"2022-09-09T04:40:03.990Z"}
```

First of all there is an external errors from npm. I will assume this is still the root cause, but it would seem there's also some type of unfulfilled promise that never returns and leaves the whole thing hanging until it times out later (check the time stamps of the last two messages).

**Comment by rarkins** [comment]
Very interesting that a user experiences similar problems when running from GitHub Actions: #17646

i.e. this could mean it's not environment specific only to the hosted app we run, but instead a result of things like:
- High throughput environments are getting rate limited or shadow banned, or
- Excess memory or socket use in VMs which are lower powered than we all probably use when trying to replicate it locally

**Comment by rarkins** [comment]
@Leksat could you remove the `timeout` setting you added to your repo? I suspect the low setting of 10s means your repo will always hit external host errors on npmjs. Some manifests are >100MB each.

**Comment by rarkins** [comment]
@davebarr the last couple of runs on your repo ended successfully. @alexg-axis for your repo, they've essentially all been successful too:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/6311784/189361286-bb964e75-aee5-4d25-874d-6838065e969e.png">

I think the one which had no end was due to us terminating some workers non-gracefully today as part of our troubleshooting for this issue

**Comment by alexg-axis** [comment]
Weird! No change on our end and I assume no change on your end, right?

**Comment by rarkins** [comment]
Actually we've been trying a few things. I disabled http2 for npmjs this morning which seems to have coincided with when the errors reduced or maybe stopped for your repo. Strangely right after my last message your repo got this error:

```
{
  "level": 40,
  "hostType": "npm",
  "packageName": "@fluentui/react-components",
  "err": {
    "name": "HTTPError",
    "code": "ERR_NON_2XX_3XX_RESPONSE",
    "timings": {
      "start": 1662731085987,
      "socket": 1662731085987,
      "lookup": 1662731087433,
      "connect": 1662731087433,
      "secureConnect": 1662731088549,
      "upload": 1662731088564,
      "response": 1662731090121,
      "end": 1662731090126,
      "phases": {
        "wait": 0,
        "dns": 1446,
        "tcp": 0,
        "tls": 1116,
        "request": 15,
        "firstByte": 1557,
        "download": 5,
        "total": 4139
      }
    },
    "message": "Response code 500 (Internal Server Error)",
    "stack": "HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://registry.npmjs.org/@fluentui%2Freact-components",
      "hostType": "npm",
      "username": "",
      "password": "",
      "method": "GET",
      "http2": false
    },
    "response": {
      "statusCode": 500,
      "statusMessage": "Internal Server Error",
      "body": {
        "error": "KV GET failed: 503 Service temporarily unavailable"
      },
      "headers": {
        "date": "Fri, 09 Sep 2022 13:44:49 GMT",
        "content-type": "application/json",
        "content-length": "62",
        "connection": "close",
        "vary": "Accept-Encoding",
        "server": "cloudflare",
        "cf-ray": "74805c577ac5c509-SEA"
      },
      "httpVersion": "1.1"
    }
  },
  "msg": "Host error",
  "time": "2022-09-09T13:45:26.352Z"
}
```

.. and at least with that one I'm pretty certain it's not our fault and instead an indication of a fault in npmjs's CDN.

**Comment by alexg-axis** [comment]
On my side there's nothing stopping us from closing this issue. Thanks for the help!

**Comment by florianmutter** [comment]
Using this config still gives an error for me (running as github action):
```
           {
             "matchHost": "registry.npmjs.org",
             "timeout": 240000,
             "enableHttp2": false
           },
```
Error:
```
WARN: Host error (repository=fadi-nextgen-shop/ngshop)
       "hostType": "npm",
       "packageName": "next",
       "err": {
         "name": "TimeoutError",
         "code": "ETIMEDOUT",
         "timings": {
           "start": 1662734433267,
           "socket": 1662734433267,
           "lookup": 1662734433273,
           "connect": 1662734433287,
           "secureConnect": 1662734434359,
           "upload": 1662734434365,
           "response": 1662734441391,
           "error": 1662734677920,
           "abort": 1662734677948,
           "phases": {
             "wait": 0,
             "dns": 6,
             "tcp": 14,
             "tls": 1072,
             "request": 6,
             "firstByte": 7026,
             "total": 244681
           }
         },
         "event": "request",
         "message": "Timeout awaiting 'request' for 240000ms",
         "stack": "RequestError: Timeout awaiting 'request' for 240000ms\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:970:65)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.emit (node:domain:489:12)\n    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/usr/src/app/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (node:internal/timers:561:11)\n    at processTimers (node:internal/timers:502:7)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.194.2 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://registry.npmjs.org/next",
           "hostType": "npm",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 200,
           "statusMessage": "OK",
           "headers": {
             "date": "Fri, 09 Sep 2022 14:40:34 GMT",
             "content-type": "application/json",
             "transfer-encoding": "chunked",
             "connection": "close",
             "cf-ray": "7480ae06cdc26fec-IAD",
             "access-control-allow-origin": "*",
             "age": "132",
             "cache-control": "public, max-age=300",
             "etag": "W/\"e0364b8097c93c88b7bf0931365c69ea\"",
             "last-modified": "Thu, 08 Sep 2022 23:08:00 GMT",
             "vary": "accept-encoding, accept",
             "cf-cache-status": "HIT",
             "x-amz-replication-status": "PENDING",
             "server": "cloudflare",
             "content-encoding": "gzip"
           },
           "httpVersion": "1.1"
         }
       }
```

**Comment by davebarr** [comment]
@rarkins thanks for looking, things are looking better today!  one job had a failure due to rate limiting from docker.io, but the rest succeeded.

**Comment by Leksat** [comment]
In my case it still does not work.

<details>
  <summary>But the external-host-error joined the timeout party</summary>
  
  <img width="829" alt="Screen Shot 2022-09-10 at 08 40 37" src="https://user-images.githubusercontent.com/989015/189470913-a110b231-c62f-4ace-b3b4-18d68eff50e1.png">

  https://app.renovatebot.com/dashboard#github/AmazeeLabs/silverback-mono
</details>

**Comment by rarkins** [comment]
@Leksat did you remove your timeout settings?

**Comment by Leksat** [comment]
> @Leksat did you remove your timeout settings?

I removed the `hostRules.timeout` setting and it looks good now. Thank you!

**Comment by tetienne** [comment]
@rarkins I still see a timeout of 1 min in our logs. Your configuration update is not yet deployed? (Job 890371391)

<details>
<summary>Logs</summary>

```
Host error
{
  "hostType": "npm",
  "packageName": "@grpc/grpc-js",
  "err": {
    "name": "TimeoutError",
    "code": "ETIMEDOUT",
    "timings": {
      "start": 1668523105932,
      "socket": 1668523105932,
      "lookup": 1668523109867,
      "connect": 1668523109867,
      "secureConnect": 1668523109887,
      "upload": 1668523109933,
      "response": 1668523114901,
      "error": 1668523168639,
      "abort": 1668523170570,
      "phases": {
        "wait": 0,
        "dns": 3935,
        "tcp": 0,
        "tls": 20,
        "request": 46,
        "firstByte": 4968,
        "total": 64638
      }
    },
    "event": "request",
    "message": "Timeout awaiting 'request' for 60000ms",
    "stack": "RequestError: Timeout awaiting 'request' for 60000ms\n    at ClientRequest.<anonymous> (/home/ubuntu/renovateapp/node_modules/got/dist/source/core/index.js:970:65)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.emit (node:domain:489:12)\n    at ClientRequest.origin.emit (/home/ubuntu/renovateapp/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/home/ubuntu/renovateapp/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (node:internal/timers:561:11)\n    at processTimers (node:internal/timers:502:7)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://registry.npmjs.org/@grpc%2Fgrpc-js",
      "hostType": "npm",
      "username": "",
      "password": "",
      "method": "GET",
      "http2": false
    },
    "response": {
      "statusCode": 200,
      "statusMessage": "OK",
      "headers": {
        "date": "Tue, 15 Nov 2022 14:38:29 GMT",
        "content-type": "application/json",
        "transfer-encoding": "chunked",
        "connection": "close",
        "cf-ray": "76a8bb1cd933c377-SEA",
        "access-control-allow-origin": "*",
        "age": "13",
        "cache-control": "public, max-age=300",
        "etag": "W/\"16fa2b36ff16e99c8000b53fdf64b67f\"",
        "last-modified": "Fri, 21 Oct 2022 17:33:12 GMT",
        "vary": "accept-encoding, accept",
        "cf-cache-status": "HIT",
        "x-amz-replication-status": "COMPLETED",
        "server": "cloudflare",
        "content-encoding": "gzip"
      },
      "httpVersion": "1.1",
      "retryCount": 2
    }
  }
}
```

</details>
