### ISSUE TITLE
Gitlab Go Module in Subdirectory Tag Lookup Broken

### ISSUE THREAD

**Issue by msvechla** [renovatebot/renovate#17921]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.201

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.3.3-ee

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We have some Go modules hosted in Gitlab within a sub-directory of a Gitlab project.
Renovate is unable to resolve the tags. 

As you can see, renovate tries to retrieve the tags of the repo via this URL:

```
https://gitlab.mycompany.com/api/v4/projects/group%2Fproject%2Fsubdirectory/repository/tags?per_page=100
```

Unfortunately this is incorrect, as the repository URL should not include the sub-directory when looking up tags.

This appears to be a bug because Go can natively handle module updates of this kind without any issues.

### Relevant debug logs

<details><summary>Logs</summary>

```json
WARN: Host error (repository=group/project)
       "hostType": "go",
       "packageName": "gitlab.mycompany.com/group/project/subdirectory",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1660910192991,
           "socket": 1660910192991,
           "lookup": 1660910192991,
           "connect": 1660910192993,
           "secureConnect": 1660910193033,
           "upload": 1660910193034,
           "response": 1660910193081,
           "end": 1660910193082,
           "phases": {
             "wait": 0,
             "dns": 0,
             "tcp": 2,
             "tls": 40,
             "request": 1,
             "firstByte": 47,
             "download": 1,
             "total": 91
           }
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.161.2 (https://github.com/renovatebot/renovate)",
             "private-token": "**redacted**",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://gitlab.mycompany.com/api/v4/projects/group%2Fproject%2Fsubdirectory/repository/tags?per_page=100",
           "hostType": "gitlab-tags",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 404,
           "statusMessage": "Not Found",
           "body": {"message": "404 Project Not Found"},
           "headers": {
             "cache-control": "no-cache",
             "content-type": "application/json",
             "date": "Fri, 19 Aug 2022 11:56:33 GMT",
             "referrer-policy": "strict-origin-when-cross-origin",
             "vary": "Origin",
             "x-content-type-options": "nosniff",
             "x-frame-options": "SAMEORIGIN",
             "x-request-id": "01GATZCJCBHCMGGW1AMJC6SD6K",
             "x-runtime": "0.025395",
             "content-length": "35",
             "connection": "Close"
           },
           "httpVersion": "1.1"
         }
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Can this be reproduced on gitlab.com?
