### ISSUE TITLE
Automatically use the Renovate token to authenticate against the container registry

### ISSUE THREAD

**Issue by baurmatt** [renovatebot/renovate#17940]
### What would you like Renovate to be able to do?

Using Renovate to update container images, that are hosted in private projects, currently requires the user to specify `hostRules` defining the credentials. At least on Gitlab, this might not be necessary if Renovate is already a member of the relevant project and the token has the right scope (`read_repository`).

### If you have any ideas on how this should be implemented, please tell us here.

Automatically use the Renovate token to authenticate against the container registry.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
What's an example `hostRules` you need to add today manually?

**Comment by baurmatt** [comment]
@rarkins Thanks for your quick response! :) I've updated the description of this issue with the relevant `hostrules`.

**Comment by rarkins** [comment]
Questions:

1. If the registry is `registry.example.de`, what's the `endpoint` value you pass to Renovate?
2. Is the `username` a dummy string, or is that the real username which the PAT is created from?
3. Does this mean that the GitLab registry uses Basic Authorization instead of Bearer?

**Comment by baurmatt** [comment]
1. The `endpoint` value would be `gitlab.example.de`. I guess it would be good if the `endpoint` API could be used to retrieve the registry hostname? :)
2. In this case, it's the name of the PAT but it doesn't matter for Gitlab. It could be any random string.
3. I'm not 100% sure what Gitlab registry uses as an authentication method, but I'm pretty sure it's not basic auth :)

**Comment by baurmatt** [comment]
So best way I could find is this:

# List registry repositories Within a project
-> https://docs.gitlab.com/ee/api/container_registry.html#within-a-project

```bash
$ curl -s --header "PRIVATE-TOKEN: $GITLAB_API_PRIVATE_TOKEN" "https://gitlab.example.de/api/v4/projects/mygroup%2Fterratest/registry/repositories" | jq '.'
[
  {
    "id": 470,
    "name": "",
    "path": "mygroup/terratest",
    "project_id": 5762,
    "location": "registry.example.de/mygroup/terratest",
    "created_at": "2021-11-05T13:56:11.890Z",
    "cleanup_policy_started_at": null
  }
]
```

Basically: Use the project full path to get the container repository of that project. The hostname of `.[].location` can be IMHO securely treated as the relevant registry.

**Comment by rarkins** [comment]
I think we might want to treat this as opt-in as it would involve this one extra API call per repo per run

**Comment by rarkins** [comment]
BTW if you configure username+password in a host rule in Renovate, it will be treated as Basic authentication

**Comment by baurmatt** [comment]
> BTW if you configure username+password in a host rule in Renovate, it will be treated as Basic authentication

Interesting, thanks! 🤔 Wasn't aware that Docker registry uses basic auth as authentication method.

**Comment by saibotk** [comment]
When defining the hostRule mentioned in the description, sadly it destroys normal docker.io lookups, where it tries to connect via empty username / password credentials.

It also overwrites the default token for gitlab itself, when using a the gitlab host with a port eg. `git.example.com:5000`. It will then add the basic auth for both `git.example.com:5000` and `git.example.com`.

**Comment by rarkins** [comment]
@saibotk in the description it has hostType=docker, so it should not overwrite the default token for non-docker requests. You are right though that it would apply to all ports, so you could restrict this by using `matchHost=https://git.example.com/`

**Comment by saibotk** [comment]
> @saibotk in the description it has hostType=docker, so it should not overwrite the default token for non-docker requests. You are right though that it would apply to all ports, so you could restrict this by using `matchHost=https://git.example.com/`

Right it does not, that is correct. Having this rule respect ports would be another issue, yet it still does not work and causes regular docker.io lookups to fail:

```
"message": "Response code 401 (Unauthorized)",
         "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.208.0 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://auth.docker.io/token?service=registry.docker.io&scope=repository:gitlab/gitlab-runner:pull",
           "hostType": "docker",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 401,
           "statusMessage": "Unauthorized",
           "body": {"details": "incorrect username or password"},
```

**Comment by rarkins** [comment]
I believe the rule does support ports, for example using the syntax I gave

**Comment by saibotk** [comment]
While it does support ports, as mentioned in my example, i believe it wrongly adds authentication rules for both the domain + port and domain, and yes i already use `matchHost` or could you give an example on how to configure docker credentials only for a specific domain + port configuration with GitLab on the same domain (but not port). 
Currently, this will error, since it tries to use the wrong credentials.

**Comment by MalteMagnussen** [comment]
OP mentions we have to use "hostType", but the documentation says different? 
https://docs.renovatebot.com/modules/platform/gitlab/

> Set the RENOVATE_HOST_RULES CI variable to [{"matchHost": "${CI_REGISTRY}","username": "${GITLAB_USER_NAME}","password": "${RENOVATE_TOKEN}"}].

```
  "hostRules": [
    {
      "description": "Personal token of the Gitlab renovate user with read_registry scope only.",
      "hostType": "docker",
      "matchHost": "registry.example.de",
      "username": "renovate-read-registry",
      "password": "glpat-xxxxxxxxxx"
    }
  ],
```

**Comment by rarkins** [comment]
Docs are in this repo, PRs welcome

**Comment by rarkins** [comment]
Hi @MalteMagnussen, glad to hear it, and here's a direct link to the source .md file: https://github.com/renovatebot/renovate/blob/main/lib/modules/platform/gitlab/index.md

I think the edit button gets it wrong because this particular page is semi-autogenerated from source instead of docs/. @HonkingGoose do you know if we can fix that manually?

**Comment by HonkingGoose** [comment]
@rarkins I think this issue has the information we need:

- https://github.com/renovatebot/renovate/issues/19309

If I understand correctly we need to put some kind of override into the Markdown files or the code.

**Comment by eFAILution** [comment]
I have been running around in circles trying to get this to work in a self-hosted instance and @stefan-lange saves the day!  None of these env vars are documented and should be provided in the self-hosted/private gitlab examples.

**Comment by baurmatt** [comment]
On Premise Helm Chart configuration needed:

```
  extraEnvVars:
    - name: RENOVATE_DETECT_HOST_RULES_FROM_ENV
      value: 'true'
    - name: DOCKER_REGISTRY_EXAMPLE_DE_USERNAME
      value: renovate-bot
    - name: DOCKER_REGISTRY_EXAMPLE_DE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mendRnvGitlabPat
          name: mend-renovate-ce
```

**Comment by baurmatt** [comment]
This has been implemented for _Github_ with:

* https://github.com/renovatebot/renovate/issues/17705
* https://github.com/renovatebot/renovate/pull/25214

**Comment by viceice** [comment]
> This has been implemented for _Github_ with:
> 
> * https://github.com/renovatebot/renovate/issues/17705
> * https://github.com/renovatebot/renovate/pull/25214

- https://github.com/renovatebot/renovate/pull/25361

is now opt-in ☝️

**Comment by sys11token** [comment]
@viceice Thanks! :) Do you know if I can create a hostRule with a regex in matchHost? This would help to implement automatic hostRules for Gitlab Packages repositories as they're served on the same domain as Gitlab itself. Thinking about something like this:

```json
  "hostRules": [
    {
      "hostType": "npm",
      "matchHost": "https://gitlab.com/api/v4/projects/[0-9]+/packages/npm/",
      "token": "glpat-xyz1234567890"
    }
  ],
```

**Comment by baurmatt** [comment]
I wasn't even aware that you are a maintainer 🙄 But sure, blame me publicly. Good way to interact with the community!

**Comment by douglasparker** [comment]
You’re on the wrong platform if you don’t want to be spoken to.

Douglas Parker
Software Engineer

**Comment by douglasparker** [comment]
Yikes, these guys seem hostile.

Douglas Parker
Software Engineer

**Comment by mbrodala** [comment]
Thanks **a lot**. This also works with [GitLab deploy tokens](https://docs.gitlab.com/ee/user/project/deploy_tokens/index.html) (set using CI/CD variables):

```env
DOCKER_REGISTRY_GITLAB_COM_USERNAME=gitlab+deploy-token-...
DOCKER_REGISTRY_GITLAB_COM_PASSWORD=gldt-...
```

The apparently most important `DEBUG` log lines which indicate that everything is working:

```ndjson
{...,"msg":"Adding password authentication for registry.gitlab.com (hostType=docker) to hostRules",...}
{...","msg":"hostRules: basic auth for https://registry.gitlab.com",...}
```
