### ISSUE TITLE
Onboarding error with .editorconfig present

### ISSUE THREAD

**Issue by eliashaeussler** [renovatebot/renovate#18540]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.241.4

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab 15.4.2 EE

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Since Renovate 32.241.4, onboarding a project with the following `.editorconfig` fails:

```editorconfig
#
# .editorconfig
#
# http://editorconfig.org
#
# The EditorConfig project consists of a file format for defining coding styles
# and a collection of text editor plugins that enable editors to read the file
# format and adhere to defined styles.
#

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
indent_style = space
indent_size = 4
insert_final_newline = true

# package.json specific rules
[package.json]
indent_size = 2

# .yml specific rules
[*.yml]
indent_size = 2
```

This worked prior to 32.241.4, so it's probably a side-effect of the `editorconfig` dependency update at #18427.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found gitlabci package files (repository=xxx/yyy)
DEBUG: Found npm package files (repository=xxx/yyy)
DEBUG: Found 3 package file(s) (repository=xxx/yyy)
DEBUG: Need to create onboarding PR (repository=xxx/yyy)
DEBUG: createOnboardingBranch() (repository=xxx/yyy)
ERROR: Repository has unknown error (repository=xxx/yyy)
       "err": {
         "message": "unreachable",
         "stack": "RuntimeError: unreachable\n    at null.<anonymous> (wasm://wasm/00051056:1:55953)\n    at null.<anonymous> (wasm://wasm/00051056:1:62171)\n    at null.<anonymous> (wasm://wasm/00051056:1:70209)\n    at null.<anonymous> (wasm://wasm/00051056:1:70338)\n    at null.<anonymous> (wasm://wasm/00051056:1:69214)\n    at null.<anonymous> (wasm://wasm/00051056:1:17561)\n    at null.<anonymous> (wasm://wasm/00051056:1:47453)\n    at null.<anonymous> (wasm://wasm/00051056:1:58421)\n    at null.<anonymous> (wasm://wasm/00051056:1:54915)\n    at module.exports.parse_to_uint32array (/usr/src/app/node_modules/@one-ini/wasm/one_ini.js:235:14)\n    at parseBuffer (/usr/src/app/node_modules/editorconfig/lib/index.js:58:52)\n    at processFileContents (/usr/src/app/node_modules/editorconfig/lib/index.js:234:25)\n    at getConfig (/usr/src/app/node_modules/editorconfig/lib/index.js:272:12)\n    at getAllConfigs (/usr/src/app/node_modules/editorconfig/lib/index.js:310:24)\n    at parse (/usr/src/app/node_modules/editorconfig/lib/index.js:440:21)\n    at Function.getCodeFormat (/usr/src/app/node_modules/renovate/lib/util/json-writer/editor-config.ts:10:24)\n    at getOnboardingConfigContents (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/config.ts:89:22)\n    at createOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/create.ts:21:20)\n    at checkOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/index.ts:65:20)\n    at getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:15:12)"
       }
DEBUG: Unknown res (repository=xxx/yyy)
       "res": "unknown-error"
DEBUG: Repository result: unknown-error, status: unknown, enabled: undefined, onboarded: undefined (repository=xxx/yyy)
```

</details>

Formatted error message with stacktrace:

```
RuntimeError: unreachable
    at null.<anonymous> (wasm://wasm/00051056:1:55953)
    at null.<anonymous> (wasm://wasm/00051056:1:62171)
    at null.<anonymous> (wasm://wasm/00051056:1:70209)
    at null.<anonymous> (wasm://wasm/00051056:1:70338)
    at null.<anonymous> (wasm://wasm/00051056:1:69214)
    at null.<anonymous> (wasm://wasm/00051056:1:17561)
    at null.<anonymous> (wasm://wasm/00051056:1:47453)
    at null.<anonymous> (wasm://wasm/00051056:1:58421)
    at null.<anonymous> (wasm://wasm/00051056:1:54915)
    at module.exports.parse_to_uint32array (/usr/src/app/node_modules/@one-ini/wasm/one_ini.js:235:14)
    at parseBuffer (/usr/src/app/node_modules/editorconfig/lib/index.js:58:52)
    at processFileContents (/usr/src/app/node_modules/editorconfig/lib/index.js:234:25)
    at getConfig (/usr/src/app/node_modules/editorconfig/lib/index.js:272:12)
    at getAllConfigs (/usr/src/app/node_modules/editorconfig/lib/index.js:310:24)
    at parse (/usr/src/app/node_modules/editorconfig/lib/index.js:440:21)
    at Function.getCodeFormat (/usr/src/app/node_modules/renovate/lib/util/json-writer/editor-config.ts:10:24)
    at getOnboardingConfigContents (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/config.ts:89:22)
    at rebaseOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/rebase.ts:31:20)
    at checkOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/index.ts:38:20)
    at getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:15:12)
```

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
How are you running renovate? are you using the full docker image? Can you test v34 then?

So maybe node v14 isn't fully compatible with the new wasm version of editorconfig.

**Comment by viceice** [comment]
opened an upstream issue

**Comment by eliashaeussler** [comment]
We use the slim Docker image. I already tested this with 33.1 and 33.2 and got the same result.

**Comment by PhilipAbed** [comment]
i tried unit test:
 
![image](https://user-images.githubusercontent.com/42116482/197759774-66c302c8-663b-40e9-82b4-cd5eded9e096.png)

**Comment by PhilipAbed** [comment]
@viceice i think u need to put the input file too in your upstream issue

**Comment by PhilipAbed** [comment]
this seems to be a problem in the input file problem for the library itself

on the other hand, we should exit gracefully, and not error with null in this case

**Comment by viceice** [comment]
@PhilipAbed Can you create a quick fix PR, which ignores that error?

**Comment by PhilipAbed** [comment]
@viceice  on it, is it ok if i add a test on this? and once the library is fixed the test will fail? :D that's how we know its fixed?

**Comment by rarkins** [comment]
Yes, add a test which fails on current code and then is fixed by your change

**Comment by PhilipAbed** [comment]
@rarkins 
the test will fail at current
Succeed with results UNDEFINED at new fix.
Succeeds with actual results if the library has fixed the parsing issue

**Comment by PhilipAbed** [comment]
@eliashaeussler 
I tried finding a workaround, by removing stuff from the file to see where the error is coming from..
apparently they fail at parsing Empty comments 
so if you add 
`# `
it will fail.
so i removed the empty comments from your file and it worked fine, 

this works fine
```
# .editorconfig
# http://editorconfig.org
# The EditorConfig project consists of a file format for defining coding styles
# and a collection of text editor plugins that enable editors to read the file
# format and adhere to defined styles.

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
indent_style = space
indent_size = 4
insert_final_newline = true

# package.json specific rules
[package.json]
indent_size = 2

# .yml specific rules
[*.yml]
indent_size = 2

```

**Comment by viceice** [comment]
> @viceice on it, is it ok if i add a test on this? and once the library is fixed the test will fail? :D that's how we know its fixed?


it's ok to let a test fail, when the lib fixed the issue

**Comment by viceice** [comment]
opened another upstream issue:
- https://github.com/one-ini/core/issues/27

**Comment by eliashaeussler** [comment]
Thanks guys!

**Comment by viceice** [comment]
upstream bug is fixed and released too. 🎉
