### ISSUE TITLE
Renovate fails to update Artifacts but doesn't provide error information

### ISSUE THREAD

**Issue by cfra** [renovatebot/renovate#18690]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

After recent updates, renovate started to fail javascript dependency updates with an "Artifact update problem" for `package-lock.json`.

Looking at the changes from the updates, it seems `package.json` gets updated, but `package-lock.json` does not.

The section "failure details" in the "Artifact update problem" comment is completely empty, and the only warning/error information that I can find in the Renovate log is that updating `package-lock.json` failed, with no information as to why it happened.

This for example affects PR#1697 on PicturePipe/hatch

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by cfra** [comment]
The log is too long to be included in a GitHub comment, so I uploaded it here: https://nowhere.ws/dump/renovatelog.txt

**Comment by viceice** [comment]
Trim the log to the relevant branch, where the error occures. We don't have time to search such big logs. 😕

**Comment by cfra** [comment]
I am sorry @viceice - I can understand your frustration, I just did not know how to filter the log properly.

I have trimmed it to the problematic branch now and hope I haven't dropped relevant information in the process:

<details><summary>Click me to see logs</summary>

```
DEBUG: syncBranchState()(branch="renovate/jquery-3.x")
DEBUG: syncBranchState(): update baseBranchSha(branch="renovate/jquery-3.x")
DEBUG: branch.isUpToDate(): using cached result "true"(branch="renovate/jquery-3.x")
DEBUG: getBranchPr(renovate/jquery-3.x)(branch="renovate/jquery-3.x")
DEBUG: findPr(renovate/jquery-3.x, undefined, open)(branch="renovate/jquery-3.x")
DEBUG: Found PR #1697(branch="renovate/jquery-3.x")
DEBUG: branchExists=true(branch="renovate/jquery-3.x")
DEBUG: dependencyDashboardCheck=rebase(branch="renovate/jquery-3.x")
DEBUG: PR rebase requested=false(branch="renovate/jquery-3.x")
DEBUG: Checking if PR has been edited(branch="renovate/jquery-3.x")
DEBUG: branch.isModified(): using cached result "false"(branch="renovate/jquery-3.x")
DEBUG: Found existing branch PR(branch="renovate/jquery-3.x")
DEBUG: Checking schedule(at any time, Europe/Berlin)(branch="renovate/jquery-3.x")
DEBUG: No schedule defined(branch="renovate/jquery-3.x")
DEBUG: Manual rebase requested via Dependency Dashboard(branch="renovate/jquery-3.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/jquery-3.x")
DEBUG: Setting current branch to develop(branch="renovate/jquery-3.x")
DEBUG: latest commit(branch="renovate/jquery-3.x")
{
  "branchName": "develop",
  "latestCommitDate": "2022-11-01T14:45:34+01:00"
}
DEBUG: manager.getUpdatedPackageFiles() reuseExistingBranch=false(branch="renovate/jquery-3.x")
DEBUG: npm.updateDependency(): dependencies.jquery = 3.6.1(branch="renovate/jquery-3.x")
DEBUG: Updating jquery in package.json(branch="renovate/jquery-3.x")
DEBUG: Updated 1 package files(branch="renovate/jquery-3.x")
DEBUG: Getting updated lock files(branch="renovate/jquery-3.x")
DEBUG: Writing package.json files(branch="renovate/jquery-3.x")
{
  "packageFiles": [
    "package.json"
  ]
}
DEBUG: Writing package-lock.json(branch="renovate/jquery-3.x")
DEBUG: Writing any updated package files(branch="renovate/jquery-3.x")
DEBUG: Writing package.json(branch="renovate/jquery-3.x")
DEBUG: npmrc file found in repository(branch="renovate/jquery-3.x")
DEBUG: Generating package-lock.json for .(branch="renovate/jquery-3.x")
DEBUG: Spawning npm install to create ./package-lock.json(branch="renovate/jquery-3.x")
DEBUG: Performing node_modules install(branch="renovate/jquery-3.x")
DEBUG: No node constraint found - using latest(branch="renovate/jquery-3.x")
DEBUG: Performing npm dedupe(branch="renovate/jquery-3.x")
DEBUG: Setting CONTAINERBASE_CACHE_DIR to /tmp/containerbase(branch="renovate/jquery-3.x")
DEBUG: Using docker to execute(branch="renovate/jquery-3.x")
{
  "image": "sidecar"
}
DEBUG: Resolved stable matching version(branch="renovate/jquery-3.x")
{
  "toolName": "node",
  "constraint": null,
  "resolvedVersion": "v18.12.0"
}
DEBUG: Resolved stable matching version(branch="renovate/jquery-3.x")
{
  "toolName": "npm",
  "constraint": "<7",
  "resolvedVersion": "6.14.17"
}
DEBUG: containerbaseDir is separate from cacheDir(branch="renovate/jquery-3.x")
DEBUG: No tag or tagConstraint specified(branch="renovate/jquery-3.x")
{
  "image": "docker.io/renovate/sidecar"
}
DEBUG: Fetching Docker image: docker.io/renovate/sidecar(branch="renovate/jquery-3.x")
DEBUG: Finished fetching Docker image docker.io/renovate/sidecar@sha256:4d5e8d8c16dbd2b9c6c52955c468d7d9cbccd22022559b65e216aa37f25fec22(branch="renovate/jquery-3.x")
DEBUG: Executing command(branch="renovate/jquery-3.x")
{
  "command": "docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/PicturePipe/hatch\":\"/mnt/renovate/gh/PicturePipe/hatch\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e NPM_CONFIG_CACHE -e npm_config_store -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/PicturePipe/hatch\" docker.io/renovate/sidecar bash -l -c \"install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe\""
}
DEBUG: rawExec err(branch="renovate/jquery-3.x")
{
  "err": {
    "name": "ExecError",
    "cmd": "/bin/sh -c docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/PicturePipe/hatch\":\"/mnt/renovate/gh/PicturePipe/hatch\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e NPM_CONFIG_CACHE -e npm_config_store -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/PicturePipe/hatch\" docker.io/renovate/sidecar bash -l -c \"install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe\"",
    "stderr": "",
    "stdout": "installing v2 tool node v18.12.0\nlinking tool node v18.12.0\nnode: v18.12.0 /usr/local/bin/node\nnpm: 8.19.2  /usr/local/bin/npm\nInstalled v2 /usr/local/buildpack/tools/v2/node.sh in 7 seconds\nskip cleanup, not a docker build: fad8b4ca1d43\ninstalling v2 tool npm v6.14.17\n\nadded 1 package in 16s\nnpm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.\nnpm WARN deprecated fs-access@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.\nnpm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\n\nadded 397 packages, removed 13 packages, and changed 18 packages in 38s\nlinking tool npm v6.14.17\n6.14.17\nInstalled v2 /usr/local/buildpack/tools/v2/npm.sh in 58 seconds\nskip cleanup, not a docker build: fad8b4ca1d43\n",
    "options": {
      "cwd": "/mnt/renovate/gh/PicturePipe/hatch",
      "encoding": "utf-8",
      "env": {
        "NPM_CONFIG_CACHE": "/tmp/renovate-cache/others/npm",
        "npm_config_store": "/tmp/renovate-cache/others/pnpm",
        "HOME": "/home/user",
        "PATH": "/home/user/.local/bin:/home/user/bin:/opt/buildpack/tools/python/3.9.3/bin:/home/user/.npm-global/bin:/home/ubuntu/renovateapp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LC_ALL": "C.UTF-8",
        "LANG": "C.UTF-8",
        "BUILDPACK_CACHE_DIR": "/tmp/containerbase",
        "CONTAINERBASE_CACHE_DIR": "/tmp/containerbase"
      },
      "maxBuffer": 10485760,
      "timeout": 900000
    },
    "exitCode": 1,
    "message": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/PicturePipe/hatch\":\"/mnt/renovate/gh/PicturePipe/hatch\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e NPM_CONFIG_CACHE -e npm_config_store -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/PicturePipe/hatch\" docker.io/renovate/sidecar bash -l -c \"install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe\"\n",
    "stack": "ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/PicturePipe/hatch\":\"/mnt/renovate/gh/PicturePipe/hatch\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e NPM_CONFIG_CACHE -e npm_config_store -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/PicturePipe/hatch\" docker.io/renovate/sidecar bash -l -c \"install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe\"\n\n    at ChildProcess.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/exec/common.js:87:24)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)"
  }
}
DEBUG: lock file error(branch="renovate/jquery-3.x")
{
  "err": {
    "name": "ExecError",
    "cmd": "/bin/sh -c docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/PicturePipe/hatch\":\"/mnt/renovate/gh/PicturePipe/hatch\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e NPM_CONFIG_CACHE -e npm_config_store -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/PicturePipe/hatch\" docker.io/renovate/sidecar bash -l -c \"install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe\"",
    "stderr": "",
    "stdout": "installing v2 tool node v18.12.0\nlinking tool node v18.12.0\nnode: v18.12.0 /usr/local/bin/node\nnpm: 8.19.2  /usr/local/bin/npm\nInstalled v2 /usr/local/buildpack/tools/v2/node.sh in 7 seconds\nskip cleanup, not a docker build: fad8b4ca1d43\ninstalling v2 tool npm v6.14.17\n\nadded 1 package in 16s\nnpm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.\nnpm WARN deprecated fs-access@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.\nnpm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\n\nadded 397 packages, removed 13 packages, and changed 18 packages in 38s\nlinking tool npm v6.14.17\n6.14.17\nInstalled v2 /usr/local/buildpack/tools/v2/npm.sh in 58 seconds\nskip cleanup, not a docker build: fad8b4ca1d43\n",
    "options": {
      "cwd": "/mnt/renovate/gh/PicturePipe/hatch",
      "encoding": "utf-8",
      "env": {
        "NPM_CONFIG_CACHE": "/tmp/renovate-cache/others/npm",
        "npm_config_store": "/tmp/renovate-cache/others/pnpm",
        "HOME": "/home/user",
        "PATH": "/home/user/.local/bin:/home/user/bin:/opt/buildpack/tools/python/3.9.3/bin:/home/user/.npm-global/bin:/home/ubuntu/renovateapp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LC_ALL": "C.UTF-8",
        "LANG": "C.UTF-8",
        "BUILDPACK_CACHE_DIR": "/tmp/containerbase",
        "CONTAINERBASE_CACHE_DIR": "/tmp/containerbase"
      },
      "maxBuffer": 10485760,
      "timeout": 900000
    },
    "exitCode": 1,
    "message": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/PicturePipe/hatch\":\"/mnt/renovate/gh/PicturePipe/hatch\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e NPM_CONFIG_CACHE -e npm_config_store -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/PicturePipe/hatch\" docker.io/renovate/sidecar bash -l -c \"install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe\"\n",
    "stack": "ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/PicturePipe/hatch\":\"/mnt/renovate/gh/PicturePipe/hatch\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e NPM_CONFIG_CACHE -e npm_config_store -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/PicturePipe/hatch\" docker.io/renovate/sidecar bash -l -c \"install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe\"\n\n    at ChildProcess.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/exec/common.js:87:24)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)"
  },
  "type": "npm"
}
DEBUG: No updated lock files in branch(branch="renovate/jquery-3.x")
DEBUG: Branch timestamp: 2022-08-26T17:54:24.768Z(branch="renovate/jquery-3.x")
DEBUG: PR is older than 2 hours, raise PR with lock file errors(branch="renovate/jquery-3.x")
DEBUG: isBranchConflicted(develop, renovate/jquery-3.x)(branch="renovate/jquery-3.x")
DEBUG: branch.isConflicted(): using git to calculate(branch="renovate/jquery-3.x")
DEBUG: branch.isConflicted(): false(branch="renovate/jquery-3.x")
DEBUG: 1 file(s) to commit(branch="renovate/jquery-3.x")
DEBUG: Preparing files for committing to branch renovate/jquery-3.x(branch="renovate/jquery-3.x")
DEBUG: git commit(branch="renovate/jquery-3.x")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/jquery-3.x",
    "commit": "baa1087ee348e0904013f43a9d2be24163f43f55",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 1
    }
  }
}
DEBUG: resetToCommit(647c43b26618a003376bc59dc31153d343622343)(branch="renovate/jquery-3.x")
DEBUG: Fetching branch renovate/jquery-3.x(branch="renovate/jquery-3.x")
INFO: Branch updated(branch="renovate/jquery-3.x")
{
  "commitSha": "c23e001d7bea9d2ef1a1b2838e992cc90d6b9a9d"
}
DEBUG: Updating status check state to failed(branch="renovate/jquery-3.x")
DEBUG: Setting branch status(branch="renovate/jquery-3.x")
{
  "context": "renovate/artifacts",
  "state": "red"
}
DEBUG: Checking if we can automerge branch(branch="renovate/jquery-3.x")
DEBUG: mergeStatus=no automerge(branch="renovate/jquery-3.x")
DEBUG: Ensuring PR(branch="renovate/jquery-3.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/jquery-3.x")
DEBUG: getBranchPr(renovate/jquery-3.x)(branch="renovate/jquery-3.x")
DEBUG: findPr(renovate/jquery-3.x, undefined, open)(branch="renovate/jquery-3.x")
DEBUG: Found PR #1697(branch="renovate/jquery-3.x")
DEBUG: Found existing PR(branch="renovate/jquery-3.x")
DEBUG: Forcing PR because of artifact errors(branch="renovate/jquery-3.x")
DEBUG: Fetching changelog: https://github.com/jquery/jquery (3.6.0 -> 3.6.1)(branch="renovate/jquery-3.x")
DEBUG: Processing existing PR(branch="renovate/jquery-3.x")
DEBUG: Pull Request #1697 does not need updating(branch="renovate/jquery-3.x")
WARN: artifactErrors(branch="renovate/jquery-3.x")
{
  "artifactErrors": [
    {
      "lockFile": "package-lock.json",
      "stderr": ""
    }
  ]
}
DEBUG: setBranchCommit()(branch="renovate/jquery-3.x")
```

</details>

**Comment by rarkins** [comment]
This is the `stdout`, formatted:

```
installing v2 tool node v18.12.0
linking tool node v18.12.0
node: v18.12.0 /usr/local/bin/node
npm: 8.19.2  /usr/local/bin/npm
Installed v2 /usr/local/buildpack/tools/v2/node.sh in 7 seconds
skip cleanup, not a docker build: fad8b4ca1d43
installing v2 tool npm v6.14.17

added 1 package in 16s
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated fs-access@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 397 packages, removed 13 packages, and changed 18 packages in 38s
linking tool npm v6.14.17
6.14.17
Installed v2 /usr/local/buildpack/tools/v2/npm.sh in 58 seconds
skip cleanup, not a docker build: fad8b4ca1d43
```

and the stack:

```
ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/PicturePipe/hatch\":\"/mnt/renovate/gh/PicturePipe/hatch\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e NPM_CONFIG_CACHE -e npm_config_store -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/PicturePipe/hatch\" docker.io/renovate/sidecar bash -l -c \"install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe\"

    at ChildProcess.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/exec/common.js:87:24)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

So it's also not clear from `npm` about why it exited with an error. I tried reproducing to see if installing npm v6 into node 18 failed:

```
❯ docker run --rm -it containerbase/sidecar
ubuntu@9ab849c603ba:/$ install-tool node v18.12.0
installing v2 tool node v18.12.0
linking tool node v18.12.0
node: v18.12.0 /usr/local/bin/node
npm: 8.19.2  /usr/local/bin/npm
Installed v2 /usr/local/buildpack/tools/v2/node.sh in 11 seconds
skip cleanup, not a docker build: 9ab849c603ba
ubuntu@9ab849c603ba:/$ install-tool npm v6.14.17 && echo "success"
installing v2 tool npm v6.14.17

added 1 package in 27s
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated fs-access@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 397 packages, removed 13 packages, and changed 18 packages in 55s
linking tool npm v6.14.17
6.14.17
Installed v2 /usr/local/buildpack/tools/v2/npm.sh in 91 seconds
skip cleanup, not a docker build: 9ab849c603ba
success
ubuntu@9ab849c603ba:/$
```

So it seems like the `npm install --no-audit --ignore-scripts` is either not running or it's showing no logs

**Comment by cfra** [comment]
Running the following locally on the jquery renovate branch where artifact updating fails seems to work fine and returns with `EXIT_SUCCESS` (0):

```
docker run --rm --name=renovate_sidecar --label=renovate_child \
    -v "$(pwd):/mnt/renovate/gh/PicturePipe/hatch" \
    -e NPM_CONFIG_CACHE \
    -e npm_config_store \
    -e BUILDPACK_CACHE_DIR \
    -e CONTAINERBASE_CACHE_DIR \
    -w /mnt/renovate/gh/PicturePipe/hatch docker.io/renovate/sidecar \
    bash \
        -l \
        -c "install-tool node v18.12.0 && install-tool npm 6.14.17 && hash -d npm 2>/dev/null || true && npm install --no-audit --ignore-scripts && npm dedupe"
```

The renovate cache and the containerbase from `/tmp` are both missing here though, so I am not sure how comparable that is.

**Comment by xC0dex** [comment]
Hey @cfra @rarkins ,

I'm facing the same or a similar issue since a couple of days. Renovate no longer can update the `package.-lock.json`. I'm using the following docker image: `renovate/renovate:34.24` with the config `RENOVATE_BINARY_SOURCE="install"`. The `package-lock.json` has the lockfileVersion 2.

This is the snippet of the debug log.
```log
DEBUG: manager.getUpdatedPackageFiles() reuseExistingBranch=false (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: npm.updateDependency(): devDependencies.mini-css-extract-plugin = 2.7.0 (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Updating mini-css-extract-plugin in Scripts/package.json (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Updated 1 package files (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Getting updated lock files (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Writing package.json files (repository=group/project, branch=renovate/all-minor-patch)
       "packageFiles": [
         "Scripts/package.json"
       ]
DEBUG: Writing Scripts/package-lock.json (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Massaging npm lock file before writing to disk (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Writing any updated package files (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Writing Scripts/package.json (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: npmrc file found in repository (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Writing updated .npmrc file to Scripts/.npmrc (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Generating package-lock.json for Scripts (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Spawning npm install to create Scripts/package-lock.json (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Updating lock file only (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: No node constraint found - using latest (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Setting CONTAINERBASE_CACHE_DIR to /builds/group/renovate-bot/renovate/cache/containerbase (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Using containerbase dynamic installs (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: GET https://nodejs.org/dist/index.json = (code=SELF_SIGNED_CERT_IN_CHAIN, statusCode=-1 retryCount=0, duration=290) (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Datasource connection error (repository=group/project, branch=renovate/all-minor-patch)
       "datasource": "node",
       "packageName": "node",
       "url": undefined,
       "errCode": "SELF_SIGNED_CERT_IN_CHAIN"
DEBUG: lock file error (repository=group/project, branch=renovate/all-minor-patch)
       "err": {
         "message": "No tool releases found.",
         "stack": "Error: No tool releases found.\n    at resolveConstraint (/usr/src/app/node_modules/renovate/lib/util/exec/containerbase.ts:190:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at generateInstallCommands (/usr/src/app/node_modules/renovate/lib/util/exec/containerbase.ts:241:27)\n    at prepareRawExec (/usr/src/app/node_modules/renovate/lib/util/exec/index.ts:145:11)\n    at exec (/usr/src/app/node_modules/renovate/lib/util/exec/index.ts:172:39)\n    at Object.generateLockFile (/usr/src/app/node_modules/renovate/lib/modules/manager/npm/post-update/npm.ts:124:5)\n    at getAdditionalFiles (/usr/src/app/node_modules/renovate/lib/modules/manager/npm/post-update/index.ts:545:17)\n    at processBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/update/branch/index.ts:432:31)\n    at writeUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/write.ts:160:17)\n    at update (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:151:11)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:61:19)\n    at attributes.repository (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:173:11)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:158:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:17:22"
       },
       "type": "npm"
DEBUG: No updated lock files in branch (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Branch timestamp: 2022-11-16T20:13:42.802Z (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: PR is older than 2 hours, raise PR with lock file errors (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: 1 file(s) to commit (repository=group/project, branch=renovate/all-minor-patch)
DEBUG: Preparing files for committing to branch renovate/all-minor-patch (repository=group/project, branch=renovate/all-minor-patch)
```

**Comment by viceice** [comment]
@xC0dex `SELF_SIGNED_CERT_IN_CHAIN` Do you use a proxy?  You need to configure additional root certificates for self signed certificates.

**Comment by ajdergute** [comment]
I was affected by this bug too. It seems to be working again with the latest version.

**Comment by kopach** [comment]
Hi. Any updates here? 
Also, this discussion seems like describes a similar issue https://github.com/renovatebot/renovate/discussions/15755

**Comment by rarkins** [comment]
Let's have a reproduction repo to debug if it's still happening for anyone

**Comment by thielepaul** [comment]
I had the same issue and was able to resolve it by adding the following config to the gitlab-ci.yml:

```yaml
RENOVATE_CUSTOM_ENV_VARIABLES: '{"PIP_CERT": "/etc/ssl/certs/ca-certificates.crt", "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt", "REQUESTS_CA_BUNDLE": "/etc/ssl/certs/ca-certificates.crt", "CURL_CA_BUNDLE": "/etc/ssl/certs/ca-certificates.crt", "SSL_CERT_FILE": "/etc/ssl/certs/ca-certificates.crt", "NODE_EXTRA_CA_CERTS": "/etc/ssl/certs/ca-certificates.crt"}'
```

Would it make sense to add this information to the docs? https://docs.renovatebot.com/examples/self-hosting/#self-signed-tlsssl-certificates
