### ISSUE TITLE
Cannot authenticate to rennovate github repo when running renovate locally 

### ISSUE THREAD

**Issue by NeillShazly** [renovatebot/renovate#18975]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.27.1

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitlab 14.0.12-ee Self Hosted

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When running Renovate locally in a docker container:

```
docker run -it -e RENOVATE_TOKEN=$RENOVATE_TOKEN -e GITHUB_COM_TOKEN=$GITHUB_COM_TOKEN renovate/renovate:34.27.1 /bin/bash

$ renovate --dry-run
```
Results in this error. This is a partial output:

```
DEBUG: Found valid git version: 2.37.0
DEBUG: Using default github endpoint: https://api.github.com/
DEBUG: GET https://api.github.com/user = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=300)
DEBUG: GitHub failure: Bad credentials
       "token": "***********",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
```

The Github token is valid and can be used to authenticate to the github api. Previously this worked without issue.

Renovate runs in the gitlab pipeline without issue, this issue occurs when running locally using the cli, or using the cli in the running docker conatiner.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found valid git version: 2.37.0
DEBUG: Using default github endpoint: https://api.github.com/
DEBUG: GET https://api.github.com/user = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=300)
DEBUG: GitHub failure: Bad credentials
       "token": "***********",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1668722653549,
           "socket": 1668722653550,
           "lookup": 1668722653551,
           "connect": 1668722653639,
           "secureConnect": 1668722653735,
           "upload": 1668722653735,
           "response": 1668722653846,
           "end": 1668722653849,
           "phases": {
             "wait": 1,
             "dns": 1,
             "tcp": 88,
             "tls": 96,
             "request": 0,
             "firstByte": 111,
             "download": 3,
             "total": 300
           }
         },
         "message": "Response code 401 (Unauthorized)",
         "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/opt/homebrew/lib/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/34.27.1 (https://github.com/renovatebot/renovate)",
             "accept": "application/vnd.github.v3+json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://api.github.com/user",
           "hostType": "github",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 401,
           "statusMessage": "Unauthorized",
           "body": {
             "message": "Bad credentials",
             "documentation_url": "https://docs.github.com/rest"
           },
           "headers": {
             "server": "GitHub.com",
             "date": "Thu, 17 Nov 2022 22:04:13 GMT",
             "content-type": "application/json; charset=utf-8",
             "content-length": "80",
             "x-github-media-type": "github.v3; format=json",
             "x-ratelimit-limit": "60",
             "x-ratelimit-remaining": "58",
             "x-ratelimit-reset": "1668726244",
             "x-ratelimit-used": "2",
             "x-ratelimit-resource": "core",
             "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
             "access-control-allow-origin": "*",
             "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
             "x-frame-options": "deny",
             "x-content-type-options": "nosniff",
             "x-xss-protection": "0",
             "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
             "content-security-policy": "default-src 'none'",
             "vary": "Accept-Encoding, Accept, X-Requested-With",
             "x-github-request-id": "68B5:3489:EF197:1E9C44:6376AFDD",
             "connection": "close"
           },
           "httpVersion": "1.1",
           "retryCount": 0
         }
       }
DEBUG: Error authenticating with GitHub
       "err": {
         "hostType": "github",
         "err": {
           "name": "HTTPError",
           "code": "ERR_NON_2XX_3XX_RESPONSE",
           "timings": {
             "start": 1668722653549,
             "socket": 1668722653550,
             "lookup": 1668722653551,
             "connect": 1668722653639,
             "secureConnect": 1668722653735,
             "upload": 1668722653735,
             "response": 1668722653846,
             "end": 1668722653849,
             "phases": {
               "wait": 1,
               "dns": 1,
               "tcp": 88,
               "tls": 96,
               "request": 0,
               "firstByte": 111,
               "download": 3,
               "total": 300
             }
           },
           "message": "Response code 401 (Unauthorized)",
           "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/opt/homebrew/lib/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
           "options": {
             "headers": {
               "user-agent": "RenovateBot/34.27.1 (https://github.com/renovatebot/renovate)",
               "accept": "application/vnd.github.v3+json",
               "authorization": "***********",
               "accept-encoding": "gzip, deflate, br"
             },
             "url": "https://api.github.com/user",
             "hostType": "github",
             "username": "",
             "password": "",
             "method": "GET",
             "http2": false
           },
           "response": {
             "statusCode": 401,
             "statusMessage": "Unauthorized",
             "body": {
               "message": "Bad credentials",
               "documentation_url": "https://docs.github.com/rest"
             },
             "headers": {
               "server": "GitHub.com",
               "date": "Thu, 17 Nov 2022 22:04:13 GMT",
               "content-type": "application/json; charset=utf-8",
               "content-length": "80",
               "x-github-media-type": "github.v3; format=json",
               "x-ratelimit-limit": "60",
               "x-ratelimit-remaining": "58",
               "x-ratelimit-reset": "1668726244",
               "x-ratelimit-used": "2",
               "x-ratelimit-resource": "core",
               "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
               "access-control-allow-origin": "*",
               "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
               "x-frame-options": "deny",
               "x-content-type-options": "nosniff",
               "x-xss-protection": "0",
               "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
               "content-security-policy": "default-src 'none'",
               "vary": "Accept-Encoding, Accept, X-Requested-With",
               "x-github-request-id": "68B5:3489:EF197:1E9C44:6376AFDD",
               "connection": "close"
             },
             "httpVersion": "1.1",
             "retryCount": 0
           }
         },
         "message": "external-host-error",
         "stack": "Error: external-host-error\n    at handleGotError (/opt/homebrew/lib/node_modules/renovate/dist/util/http/github.js:77:20)\n    at GithubHttp.request (/opt/homebrew/lib/node_modules/renovate/dist/util/http/github.js:230:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async GithubHttp.requestJson (/opt/homebrew/lib/node_modules/renovate/dist/util/http/index.js:189:21)\n    at async getUserDetails (/opt/homebrew/lib/node_modules/renovate/dist/modules/platform/github/user.js:10:27)\n    at async Proxy.initPlatform (/opt/homebrew/lib/node_modules/renovate/dist/modules/platform/github/index.js:82:69)\n    at async initPlatform (/opt/homebrew/lib/node_modules/renovate/dist/modules/platform/index.js:39:26)\n    at async globalInitialize (/opt/homebrew/lib/node_modules/renovate/dist/workers/global/initialize.js:68:14)\n    at async /opt/homebrew/lib/node_modules/renovate/dist/workers/global/index.js:97:22\n    at async Object.start (/opt/homebrew/lib/node_modules/renovate/dist/workers/global/index.js:89:9)\n    at async /opt/homebrew/lib/node_modules/renovate/dist/renovate.js:16:24"
       }
FATAL: Authentication failure
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "13v--5js8Tk7wL3-oderb",
           "msg": "Authentication failure"
         }
       ]
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
what your token type? is it a Pat or app token or something else?

**Comment by viceice** [comment]
you probably forgot to set the platform? the default is GitHub. this hasn't changed ever.

do you use our gitlab pipeline templates for CI runs?

**Comment by rarkins** [comment]
If running on GitHub, `RENOVATE_TOKEN` and `GITHUB_COM_TOKEN` are going to conflict as they both will apply to api.github.com

**Comment by viceice** [comment]
did you configure platform config option? i don't see that in your ENV. do you use a config file too?
