### ISSUE TITLE
AWS CodeCommit - ensure comments is throwing an exception

### ISSUE THREAD

**Issue by PhilipAbed** [renovatebot/renovate#19293]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.50.2

### If you're self-hosting Renovate, select which platform you are using.

AWS CodeCommit

### If you're self-hosting Renovate, tell us what version of the platform you run.

-

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

got a weird exception on AWS while ensuring comment:
```
 Unable to retrieve pr comments (repository=RenovateTest3, branch=renovate/commander-9.x)
"__type": "CommitIdRequiredException",
"message": "A commit ID is required, but no commit ID was specified.",
```
but when i checked AWS API,  it's calling `GetCommentsForPullRequest`,
yet according to the docs the commit id is not required. 
see https://docs.aws.amazon.com/codecommit/latest/APIReference/API_GetCommentsForPullRequest.html

seems that there are some cases where it's required, and it drops this exception `CommitIdRequiredException`

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Checking if PR has been edited (repository=PhilipRenovateAWSDemo, branch=renovate/commander-9.x)
DEBUG: branch.isModified(): using git to calculate (repository=PhilipRenovateAWSDemo, branch=renovate/commander-9.x)
DEBUG: branch.isModified() = true (repository=PhilipRenovateAWSDemo, branch=renovate/commander-9.x)
       "branchName": "renovate/commander-9.x",
       "lastAuthor": "a",
       "gitAuthorEmail": "philipabed451@gmail.com"
DEBUG: Found existing branch PR (repository=PhilipRenovateAWSDemo, branch=renovate/commander-9.x)
DEBUG: PR has been edited, PrNo:60 (repository=PhilipRenovateAWSDemo, branch=renovate/commander-9.x)
DEBUG: Ensuring comment to indicate that rebasing is not possible (repository=PhilipRenovateAWSDemo, branch=renovate/commander-9.x)
DEBUG: ensureComment(60, Edited/Blocked Notification, content) (repository=PhilipRenovateAWSDemo, branch=renovate/commander-9.x)
DEBUG: Unable to retrieve pr comments (repository=PhilipRenovateAWSDemo, branch=renovate/commander-9.x)
       "err": {
         "name": "CommitIdRequiredException",
         "$fault": "client",
         "$metadata": {
           "httpStatusCode": 400,
           "requestId": "864df818-ab88-4224-9bc6-f5d924f7eb50",
           "attempts": 1,
           "totalRetryDelay": 0
         },
         "__type": "CommitIdRequiredException",
         "message": "A commit ID is required, but no commit ID was specified.",
         "stack": "CommitIdRequiredException: A commit ID is required, but no commit ID was specified.\n    at deserializeAws_json1_1CommitIdRequiredExceptionResponse (C:\\github\\renovate\\node_modules\\@aws-sdk\\client-codecommit\\dist-cjs\\prot
ocols\\Aws_json1_1.js:6620:23)\n    at deserializeAws_json1_1GetCommentsForPullRequestCommandError (C:\\github\\renovate\\node_modules\\@aws-sdk\\client-codecommit\\dist-cjs\\protocols\\Aws_json1_1.js:2875:25)\n    at runMicrotasks (<anonymous>)\n
    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async C:\\github\\renovate\\node_modules\\@aws-sdk\\middleware-serde\\dist-cjs\\deserializerMiddleware.js:7:24\n    at async C:\\github\\renovate\\node_modules\\@aws
-sdk\\middleware-signing\\dist-cjs\\middleware.js:11:20\n    at async StandardRetryStrategy.retry (C:\\github\\renovate\\node_modules\\@aws-sdk\\middleware-retry\\dist-cjs\\StandardRetryStrategy.js:51:46)\n    at async C:\\github\\renovate\\node_m
odules\\@aws-sdk\\middleware-logger\\dist-cjs\\loggerMiddleware.js:6:22\n    at async Object.getPrComments (C:\\github\\renovate\\lib\\modules\\platform\\codecommit\\codecommit-client.ts:89:10)\n    at async Proxy.ensureComment (C:\\github\\renova
te\\lib\\modules\\platform\\codecommit\\index.ts:602:26)\n    at async ensureComment (C:\\github\\renovate\\lib\\modules\\platform\\comment.ts:19:17)\n    at async handleModifiedPr (C:\\github\\renovate\\lib\\workers\\repository\\update\\branch\\h
andle-existing.ts:94:5)\n    at async processBranch (C:\\github\\renovate\\lib\\workers\\repository\\update\\branch\\index.ts:213:11)\n    at async writeUpdates (C:\\github\\renovate\\lib\\workers\\repository\\process\\write.ts:159:17)\n    at asy
nc update (C:\\github\\renovate\\lib\\workers\\repository\\process\\extract-update.ts:151:11)\n    at async Object.renovateRepository (C:\\github\\renovate\\lib\\workers\\repository\\index.ts:61:19)\n    at async attributes.repository (C:\\github\
\renovate\\lib\\workers\\global\\index.ts:173:11)\n    at async Object.start (C:\\github\\renovate\\lib\\workers\\global\\index.ts:158:7)\n    at async C:\\github\\renovate\\lib\\renovate.ts:17:22"
       }

```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
`GetCommentsForPullRequest` input:

```
{
   "afterCommitId": "string",
   "beforeCommitId": "string",
   "maxResults": number,
   "nextToken": "string",
   "pullRequestId": "string",
   "repositoryName": "string"
}
```

`GetPullRequest` output:

```
{
   "[pullRequest](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_GetPullRequest.html#CodeCommit-GetPullRequest-response-pullRequest)": { 
      "[approvalRules](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-approvalRules)": [ 
         { 
            "[approvalRuleContent](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ApprovalRule.html#CodeCommit-Type-ApprovalRule-approvalRuleContent)": "string",
            "[approvalRuleId](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ApprovalRule.html#CodeCommit-Type-ApprovalRule-approvalRuleId)": "string",
            "[approvalRuleName](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ApprovalRule.html#CodeCommit-Type-ApprovalRule-approvalRuleName)": "string",
            "[creationDate](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ApprovalRule.html#CodeCommit-Type-ApprovalRule-creationDate)": number,
            "[lastModifiedDate](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ApprovalRule.html#CodeCommit-Type-ApprovalRule-lastModifiedDate)": number,
            "[lastModifiedUser](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ApprovalRule.html#CodeCommit-Type-ApprovalRule-lastModifiedUser)": "string",
            "[originApprovalRuleTemplate](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ApprovalRule.html#CodeCommit-Type-ApprovalRule-originApprovalRuleTemplate)": { 
               "[approvalRuleTemplateId](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_OriginApprovalRuleTemplate.html#CodeCommit-Type-OriginApprovalRuleTemplate-approvalRuleTemplateId)": "string",
               "[approvalRuleTemplateName](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_OriginApprovalRuleTemplate.html#CodeCommit-Type-OriginApprovalRuleTemplate-approvalRuleTemplateName)": "string"
            },
            "[ruleContentSha256](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ApprovalRule.html#CodeCommit-Type-ApprovalRule-ruleContentSha256)": "string"
         }
      ],
      "[authorArn](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-authorArn)": "string",
      "[clientRequestToken](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-clientRequestToken)": "string",
      "[creationDate](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-creationDate)": number,
      "[description](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-description)": "string",
      "[lastActivityDate](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-lastActivityDate)": number,
      "[pullRequestId](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-pullRequestId)": "string",
      "[pullRequestStatus](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-pullRequestStatus)": "string",
      "[pullRequestTargets](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-pullRequestTargets)": [ 
         { 
            "[destinationCommit](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequestTarget.html#CodeCommit-Type-PullRequestTarget-destinationCommit)": "string",
            "[destinationReference](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequestTarget.html#CodeCommit-Type-PullRequestTarget-destinationReference)": "string",
            "[mergeBase](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequestTarget.html#CodeCommit-Type-PullRequestTarget-mergeBase)": "string",
            "[mergeMetadata](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequestTarget.html#CodeCommit-Type-PullRequestTarget-mergeMetadata)": { 
               "[isMerged](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_MergeMetadata.html#CodeCommit-Type-MergeMetadata-isMerged)": boolean,
               "[mergeCommitId](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_MergeMetadata.html#CodeCommit-Type-MergeMetadata-mergeCommitId)": "string",
               "[mergedBy](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_MergeMetadata.html#CodeCommit-Type-MergeMetadata-mergedBy)": "string",
               "[mergeOption](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_MergeMetadata.html#CodeCommit-Type-MergeMetadata-mergeOption)": "string"
            },
            "[repositoryName](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequestTarget.html#CodeCommit-Type-PullRequestTarget-repositoryName)": "string",
            "[sourceCommit](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequestTarget.html#CodeCommit-Type-PullRequestTarget-sourceCommit)": "string",
            "[sourceReference](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequestTarget.html#CodeCommit-Type-PullRequestTarget-sourceReference)": "string"
         }
      ],
      "[revisionId](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-revisionId)": "string",
      "[title](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_PullRequest.html#CodeCommit-Type-PullRequest-title)": "string"
   }
}
```

**Comment by rarkins** [comment]
Can't you get afterCommitId from the pullRequest.pullRequestTargets.destinationCommit field, and beforeCommitId from pullRequest.pullRequestTargets.sourceCommit field?

**Comment by PhilipAbed** [comment]
![image](https://user-images.githubusercontent.com/42116482/206486006-fdd31cd1-4e3e-47da-9c96-296cac06beec.png)
u still lose context since the main branch sha has changed, 


![image](https://user-images.githubusercontent.com/42116482/206486251-99370981-4a0b-4bec-8f52-f072945d9d20.png)
we lose context on the pull request branch as well if we push anything to it

CodeCommit is deisgned in a way that when you create a comment we attach to it `beforeCommit` + `afterCommit`

u can get those manually i believe, 
but the SDK doesn't allow you to retrieve `All Comments of PR`, nor lets u `list all commits on branch`  
so no matter what we do, the commits just can be lost, and we are not able to retrieve comments.

**Comment by PhilipAbed** [comment]
i believed first that since it says the `beforeCommitId` + `afterCommitId` are not required for the api to get all comments on PR
so you can just pull all comments on PR using the `GetCommentsForPullRequest`.
but that is not true 
hence the exception you see in this ticket.

**Comment by rarkins** [comment]
I'm not sure about the "losing context" you mention. Are you sure about it?

**Comment by PhilipAbed** [comment]
let me show you the API limit:

from GetCommentsForPullRequests:
![image](https://user-images.githubusercontent.com/42116482/206890820-d9c6ccb5-a9a7-4b6b-95b4-ec78337eb5d2.png)

the comment is tied to a commit id

if we commit over it, the comment cannot be retrieved since we lose the commitId and there's no way to list all commits or all comments to retrieve it.

from GetPR:: targets:
![image](https://user-images.githubusercontent.com/42116482/206890951-18d500de-d2dd-4104-b8aa-2c24ad2e0994.png)
![image](https://user-images.githubusercontent.com/42116482/206890982-0765f227-8fd8-4c06-a551-ac29a6aa902c.png)

the commit ID changes depending on new commits...

from getBranch
![image](https://user-images.githubusercontent.com/42116482/206891000-1f0379ea-7dc3-4972-9fb3-a2c8f5effe56.png)

the commitId changes too,

we don't save a commitID of the source/target branch of when the comment was created, we have no way of doing that.

**Comment by rarkins** [comment]
Are these commit IDs just SHAs, or something internal to AWS?

**Comment by PhilipAbed** [comment]
code commit uses git, so i suppose it's the same git sha of every commit out there for every other platform nothing new.

do you thing  any git command can help us get all comments made to a specific PR
using https://git-scm.com/docs/git-log for example? 
i tried but nothing good is coming out of it

**Comment by rarkins** [comment]
If we enable repo cache then we could have the base branch sha from that

**Comment by PhilipAbed** [comment]
So using cache is mandatory for aws ?
Ill investigate and see what can be done using cache
