### ISSUE TITLE
"Cannot find preset's package" when using 

### ISSUE THREAD

**Issue by jamietanna** [renovatebot/renovate#19433]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.238.1, 34.58.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

This has definitely worked previously when I've been using this - 

When using the following `config.js`:

```js
module.exports = {
  requireConfig: "ignore",
  onboarding: false,
  includeForks: true,
  globalExtends: [
    "github>jamietanna/renovate-private-presets"
  ],
};
```

And running:

```sh
env LOG_LEVEL=debug npx renovate@32.238.1 --token $GITHUB_TOKEN --dry-run jamietanna/oapi-codegen 
```

Then we get:

```
ERROR: Error resolving config preset
       "err": {
         "validationError": "Cannot find preset's package (github>jamietanna/renovate-private-presets)",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at fetchPreset (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/index.js:293:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async resolveConfigPresets (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/index.js:238:39)\n    at async resolveGlobalExtends (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:77:32)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:94:65\n    at async Object.start (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:89:9)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/renovate.js:16:24"
       }
FATAL: Fatal error: config-presets-invalid
       "err": {
         "message": "config-presets-invalid",
         "stack": "Error: config-presets-invalid\n    at resolveGlobalExtends (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:82:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:94:65\n    at async Object.start (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:89:9)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/renovate.js:16:24"
       }
```

There doesn't appear to be a token being sent to the presets API endpoint (as spotted in the trace logs)

### Relevant debug logs

<details><summary>Debug Logs</summary>

```
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /Users/jamietanna/workspaces/dependency-management-data/tmp/config.js
 WARN: cli config dryRun property has been changed to full
DEBUG: File config
       "config": {
         "requireConfig": "ignore",
         "onboarding": false,
         "includeForks": true,
         "globalExtends": ["github>jamietanna/renovate-private-presets"]
       }
DEBUG: CLI config
       "config": {
         "repositories": ["jamietanna/oapi-codegen"],
         "dryRun": "full",
         "token": "***********"
       }
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "requireConfig": "ignore",
         "onboarding": false,
         "includeForks": true,
         "globalExtends": ["github>jamietanna/renovate-private-presets"],
         "hostRules": [],
         "repositories": ["jamietanna/oapi-codegen"],
         "dryRun": "full",
         "token": "***********"
       }
DEBUG: GET https://api.github.com/repos/jamietanna/renovate-private-presets/contents/default.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=224)
DEBUG: Preset file default.json not found in jamietanna/renovate-private-presets
DEBUG: GET https://api.github.com/repos/jamietanna/renovate-private-presets/contents/renovate.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=239)
DEBUG: Preset file renovate.json not found in jamietanna/renovate-private-presets
DEBUG: Preset fetch error
       "preset": "github>jamietanna/renovate-private-presets",
       "err": {
         "message": "dep not found",
         "stack": "Error: dep not found\n    at fetchJSONFile (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/github/index.js:30:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async fetchPreset (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/util.js:31:27)\n    at async getPreset (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/index.js:182:24)\n    at async fetchPreset (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/index.js:281:16)\n    at async resolveConfigPresets (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/index.js:238:39)\n    at async resolveGlobalExtends (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:77:32)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:94:65\n    at async Object.start (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:89:9)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/renovate.js:16:24"
       }
 INFO: Throwing preset error
       "validationError": "Cannot find preset's package (github>jamietanna/renovate-private-presets)"
ERROR: Error resolving config preset
       "err": {
         "validationError": "Cannot find preset's package (github>jamietanna/renovate-private-presets)",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at fetchPreset (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/index.js:293:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async resolveConfigPresets (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/config/presets/index.js:238:39)\n    at async resolveGlobalExtends (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:77:32)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:94:65\n    at async Object.start (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:89:9)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/renovate.js:16:24"
       }
FATAL: Fatal error: config-presets-invalid
       "err": {
         "message": "config-presets-invalid",
         "stack": "Error: config-presets-invalid\n    at resolveGlobalExtends (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:82:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:94:65\n    at async Object.start (/Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/workers/global/index.js:89:9)\n    at async /Users/jamietanna/workspaces/dependency-management-data/tmp/node_modules/renovate/dist/renovate.js:16:24"
       }
```

</details>

<details><summary>Trace Logs</summary>

```
TRACE: mergeChildConfig
       "parent": {
         "requireConfig": "ignore",
         "onboarding": false,
         "includeForks": true,
         "globalExtends": ["github>jamietanna/renovate-private-presets"]
       },
       "child": {"hostRules": []}
TRACE: mergeChildConfig
       "parent": {
         "requireConfig": "ignore",
         "onboarding": false,
         "includeForks": true,
         "globalExtends": ["github>jamietanna/renovate-private-presets"],
         "hostRules": []
       },
       "child": {
         "repositories": ["jamietanna/oapi-codegen"],
         "dryRun": "full",
         "token": "***********"
       }
TRACE: mergeable option: hostRules
TRACE: Merged config.hostRules
       "result": [{"timeout": 60000}]
TRACE: Default config
       "config": {
         ...
         "hostRules": [{"timeout": 60000}],
DEBUG: File config
       "config": {
         "requireConfig": "ignore",
         "onboarding": false,
         "includeForks": true,
         "globalExtends": ["github>jamietanna/renovate-private-presets"]
       }
DEBUG: CLI config
       "config": {
         "repositories": ["jamietanna/oapi-codegen"],
         "dryRun": "full",
         "token": "***********"
       }
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "requireConfig": "ignore",
         "onboarding": false,
         "includeForks": true,
         "globalExtends": ["github>jamietanna/renovate-private-presets"],
         "hostRules": [],
         "repositories": ["jamietanna/oapi-codegen"],
         "dryRun": "full",
         "token": "***********"
       }
TRACE: resolveConfigPresets
       "config": {"extends": ["github>jamietanna/renovate-private-presets"]},
       "existingPresets": []
TRACE: Resolving preset "github>jamietanna/renovate-private-presets"
TRACE: getPreset(github>jamietanna/renovate-private-presets)
TRACE: Preset URL
       "url": "https://api.github.com/repos/jamietanna/renovate-private-presets/contents/default.json"
TRACE: No throttle
       "host": "api.github.com"
TRACE: No concurrency limits
       "host": "api.github.com"
TRACE: got request
       "url": "https://api.github.com/repos/jamietanna/renovate-private-presets/contents/default.json",
       "options": {
         "method": "get",
         "context": {"hostType": "github"},
         "hostType": "github",
         "baseUrl": "https://api.github.com/",
         "responseType": "json",
         "headers": {
           "accept": "application/json, application/vnd.github.v3+json",
           "user-agent": "RenovateBot/34.58.0 (https://github.com/renovatebot/renovate)"
         },
         "throwHttpErrors": true,
         "hooks": {"beforeRedirect": ["[function]"]}
       }
DEBUG: GET https://api.github.com/repos/jamietanna/renovate-private-presets/contents/default.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=238)
DEBUG: Preset file default.json not found in jamietanna/renovate-private-presets
TRACE: Preset URL
       "url": "https://api.github.com/repos/jamietanna/renovate-private-presets/contents/renovate.json"
TRACE: got request
       "url": "https://api.github.com/repos/jamietanna/renovate-private-presets/contents/renovate.json",
       "options": {
         "method": "get",
         "context": {"hostType": "github"},
         "hostType": "github",
         "baseUrl": "https://api.github.com/",
         "responseType": "json",
         "headers": {
           "accept": "application/json, application/vnd.github.v3+json",
           "user-agent": "RenovateBot/34.58.0 (https://github.com/renovatebot/renovate)"
         },
         "throwHttpErrors": true,
         "hooks": {"beforeRedirect": ["[function]"]}
       }
DEBUG: GET https://api.github.com/repos/jamietanna/renovate-private-presets/contents/renovate.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=255)
```

</summary>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by jamietanna** [comment]
Could this be similar to https://github.com/renovatebot/renovate/issues/7238 and the fact that it's a public repo retrieving private config?

**Comment by jamietanna** [comment]
This appears to only happen when using `globalExtends`, where `extends` does not throw this error.
