### ISSUE TITLE
YAMLException: duplicated mapping key when generating pnpm-lock.yaml

### ISSUE THREAD

**Issue by andreademasi** [renovatebot/renovate#19959]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It never worked

### Describe the bug

Renovate can't generate pnpm-lock.yaml for any dep update. 
You can check the failing PRs in my public repo: https://github.com/openw2g/openW2G/pulls
Full gist [here](https://gist.github.com/andreademasi/d7e3ea1021583cab1517c011a7225e9b)

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Generating pnpm-lock.yaml for .(branch="renovate/chrome-0.x")
DEBUG: Spawning pnpm install to create pnpm-lock.yaml(branch="renovate/chrome-0.x")
DEBUG: lock file error(branch="renovate/chrome-0.x")
{
  "cmd": "pnpm",
  "err": {
    "name": "YAMLException",
    "reason": "duplicated mapping key",
    "mark": {
      "name": null,
      "buffer": "lockfileVersion: 5.4\n\nspecifiers:\n  '@floating-ui/react-dom-interactions': ^0.13.3\n  '@plasmohq/prettier-plugin-sort-imports': ^3.6.1\n  '@plasmohq/storage': ^0.13.1\n  '@trpc/client': ^10.7.0\n  '@trpc/server': ^10.7.0\n  '@types/chrome': ^0.0.203\n  '@types/jest': ^29.2.4\n ........",
      "position": 6072,
      "line": 186,
      "column": 2,
      "snippet": " 184 |       jsesc: 2.5.2\n 185 |     dev: true\n 186 | \n 187 |   /@babel/helper-compilation-targ ...\n---------^\n 188 |     resolution: {integrity: sha51 ...\n 189 |     engines: {node: '>=6.9.0'}"
    },
    "message": "duplicated mapping key (187:3)\n\n 184 |       jsesc: 2.5.2\n 185 |     dev: true\n 186 | \n 187 |   /@babel/helper-compilation-targ ...\n---------^\n 188 |     resolution: {integrity: sha51 ...\n 189 |     engines: {node: '>=6.9.0'}",
    "stack": "YAMLException: duplicated mapping key (187:3)\n\n 184 |       jsesc: 2.5.2\n 185 |     dev: true\n 186 | \n 187 |   /@babel/helper-compilation-targ ...\n---------^\n 188 |     resolution: {integrity: sha51 ...\n 189 |     engines: {node: '>=6.9.0'}\n    at generateError (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:183:10)\n    at throwError (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:187:9)\n    at storeMappingPair (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:358:7)\n    at readBlockMapping (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:1173:9)\n    at composeNode (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readDocument (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:1625:3)\n    at loadDocuments (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:1688:5)\n    at load (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/loader.js:1714:19)\n    at getPnpmConstraint (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/npm/post-update/pnpm.js:104:49)\n    at async Object.generateLockFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/npm/post-update/pnpm.js:24:54)\n    at async getAdditionalFiles (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/npm/post-update/index.js:556:21)\n    at async processBranch (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/update/branch/index.js:312:37)\n    at async writeUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/write.js:120:21)\n    at async update (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/extract-update.js:126:15)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:60:25)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:260:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:454:5"
  },
  "type": "pnpm"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
looks like a pnpm bug? 🤔

**Comment by andreademasi** [comment]
> looks like a pnpm bug? thinking

Works fine locally (pnpm v7.18.2), maybe renovate uses a different pnpm version?

**Comment by viceice** [comment]
if you don't constraint it, then renovate will use the latest version

**Comment by andreademasi** [comment]
It was indeed a broken lockfile generated by pnpm, a `pnpm install` fixed it.
