### ISSUE TITLE
Dependency lookup failed in 3.109.2

### ISSUE THREAD

**Issue by bytestream** [renovatebot/renovate#20009]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

3.112.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.3.2

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Since Renovate 34.109.2 I've started getting a warning on the dependency dashboard about dependency lookup failed. In `composer.lock`:
```
 {
            "name": "phpclasses/mimeparser",
            "version": "1.85",
            "dist": {
                "type": "zip",
                "url": "https://raw.githubusercontent.com/redacted/satis/main/packages/phpclasses/mimeparser/mimeparser-1.85.0.zip",
                "shasum": "9ad6ada0ac29e783f6e7a4bcb47b00dd912b6a33"
            },
            "type": "library",
            "autoload": {
                "classmap": [
                    "mime_parser.php",
                    "rfc822_addresses.php"
                ]
            }
        },
```

In `composer.json` `repositories` (where `phpclasses/mimeparser` package exists):
```
       {
            "type": "composer",
            "url": "https://redacted.github.io/satis"
        },
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: GET https://packagist.org/p2/phpclasses/mimeparser.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=233) (repository=foo/helpdesk)
DEBUG: GET https://packagist.org/p2/phpclasses/mimeparser~dev.json = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=235) (repository=foo/helpdesk)
DEBUG: Aggregate error is thrown (repository=foo/helpdesk)
       "err": {
         "name": "AggregateError",
         "message": "\n    HTTPError: Response code 404 (Not Found)\n        at Request.<anonymous> (/builds/foo/gitlab/renovate-bot/node_modules/got/dist/source/as-promise/index.js:118:42)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    HTTPError: Response code 404 (Not Found)\n        at Request.<anonymous> (/builds/foo/gitlab/renovate-bot/node_modules/got/dist/source/as-promise/index.js:118:42)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "stack": "AggregateError: \n    HTTPError: Response code 404 (Not Found)\n        at Request.<anonymous> (/builds/foo/gitlab/renovate-bot/node_modules/got/dist/source/as-promise/index.js:118:42)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    HTTPError: Response code 404 (Not Found)\n        at Request.<anonymous> (/builds/foo/gitlab/renovate-bot/node_modules/got/dist/source/as-promise/index.js:118:42)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at next (/builds/foo/gitlab/renovate-bot/node_modules/p-map/index.js:43:14)\n    at /builds/foo/gitlab/renovate-bot/node_modules/p-map/index.js:67:7\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
DEBUG: Datasource 404 (repository=foo/helpdesk)
       "datasource": "packagist",
       "packageName": "phpclasses/mimeparser",
       "url": "https://packagist.org/p2/phpclasses/mimeparser.json"
DEBUG: Failed to look up packagist dependency phpclasses/mimeparser (repository=foo/helpdesk, packageFile=composer.json, dependency=phpclasses/mimeparser)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by bytestream** [comment]
This must be something to do with https://github.com/renovatebot/renovate/pull/19930

**Comment by zharinov** [comment]
Hi @bytestream, is it correct that `phpclasses/mimeparser` is a private package not related to `packagist.org` repository?

**Comment by rarkins** [comment]
@zharinov should we roll back this change?

@bytestream do you have an any before and after logs from when it worked to when it didn't? especially `packageFiles with updates`.

**Comment by zharinov** [comment]
Here is my minimal reproduction: https://github.com/renovate-testing/test-20009-packagist-404

@bytestream Is it similar to your use-case? I see `404` and `AggregateError` in my logs.

**Comment by zharinov** [comment]
> @zharinov should we roll back this change?

In the upper layer, we handle `HTTPError` in a certain way. When it's wrapped in `AggregateError`, seems like we're aborting processing. Possible solutions:
- Unwrap `AggregateError` in the level of `packagist`
- Handle `AggregateError` properly somewhere in upper level

**Comment by rarkins** [comment]
If you don't know, let's revert

**Comment by bytestream** [comment]
@zharinov 
```
               {
                 "depType": "require",
                 "depName": "phpclasses/mimeparser",
                 "currentValue": "1.85",
                 "datasource": "packagist",
                 "lockedVersion": "1.85",
                 "registryUrls": [
                   "https://redacted.github.io/satis",
                   "https://gitlab.redacted.com/api/v4/group/2/-/packages/composer",
                   "https://packagist.org"
                 ],
                 "depIndex": 35,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "phpclasses/mimeparser",
                     "message": "Failed to look up packagist dependency phpclasses/mimeparser"
                   }
                 ],
                 "versioning": "composer"
               },
```

**Comment by zharinov** [comment]
Now I see, we need to revert
