### ISSUE TITLE
Pushing to PR branches fails with "No such device or address" when Renovate is run from within jenkins

### ISSUE THREAD

**Issue by soenkeliebau** [renovatebot/renovate#20292]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.119.2

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We are trying to self host renovate and want to use the `renovate/renovate` docker container for this.

I am running it from my laptop with the following command:

`docker run --rm -e "RENOVATE_TOKEN=xxx" -v /home/sliebau/renovate/config.js:/usr/src/app/config.js" renovate/renovate`

and this works perfectly fine.

In order to make it accessible to the entire team, the config.js was checked into our ci github repository, and we created a Jenkins job to run basically the same command, after checking out that repo.

The job starts up alright, does authenticate with github and looks at the correct repositories, so I think that any token or config related problems can be provisionally ruled out.

However, as soon as renovate actually needs to push to a branch it fails with the error shown in the log below.

I strongly suspect that this is something to do with our Jenkins setup, but am at my wits end as to what it might be. I'll briefly explain how we run Jenkins and which scenarios I tested manually to see where the error may originate.

We have a VM that runs Jenkins in a Docker container. That docker container has `/var/run/docker.sock` mounted into it, so that any docker commands started inside the container talk to the docker daemon on the actual VM. This is working fine in principle and not [unusual](https://ro14nd.de/Docker-Wormhole-Pattern) afaik.

In Jenkins we have our renovate job configured to run the following command:

```
docker run --rm \
  --volume "$HOST_WORKSPACE/renovate/config.js:/usr/src/app/config.js" \
  --env RENOVATE_TOKEN="$GITHUB_TOKEN" \
  --env LOG_LEVEL=debug \
  renovate/renovate
```
and this fails with the error shown in the log below.

I have run the docker command I mentioned above directly from a shell on the VM and this works.

I have also attached a shell to the Jenkins container with `docker exec -it ... /bin/bash` and run the command from there. Works fine as well.

At the moment I am pretty much out of ideas what might cause this. The "Execute shell" module in Jenkins is a prime suspect of course, but if this was any escaping or quoting shenanigans I'd expect something more fundamental to break and renovate not finding repos, not being able to read, ...

Any help would be highly appreciated!

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Setting git author name: Stacky McStackface (repository=stackabletech/operator-templating, branch=renovate/reviewdog-action-hadolint-1.x)
DEBUG: Setting git author email: serviceaccounts@stackable.de (repository=stackabletech/operator-templating, branch=renovate/reviewdog-action-hadolint-1.x)
DEBUG: git commit (repository=stackabletech/operator-templating, branch=renovate/reviewdog-action-hadolint-1.x)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/reviewdog-action-hadolint-1.x",
         "commit": "d01270a513c9b4b6666c9e13d7d59b57a69fa038",
         "root": false,
         "summary": {"changes": 2, "insertions": 2, "deletions": 2}
       }
DEBUG: Pushing refSpec renovate/reviewdog-action-hadolint-1.x:renovate/reviewdog-action-hadolint-1.x (repository=stackabletech/operator-templating, branch=renovate/reviewdog-action-hadolint-1.x)
DEBUG: Git function thrown (repository=stackabletech/operator-templating, branch=renovate/reviewdog-action-hadolint-1.x)
       "err": {
         "task": {
           "commands": [
             "push",
             "origin",
             "renovate/reviewdog-action-hadolint-1.x:renovate/reviewdog-action-hadolint-1.x",
             "--force-with-lease",
             "-u",
             "--no-verify",
             "--verbose",
             "--porcelain"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "Pushing to https://**redacted**@github.com/': No such device or address\n",
         "stack": "Error: Pushing to https://**redacted**@github.com/': No such device or address\n\n    at Object.action (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
DEBUG: Unknown error committing files (repository=stackabletech/operator-templating, branch=renovate/reviewdog-action-hadolint-1.x)
       "err": {
         "task": {
           "commands": [
             "push",
             "origin",
             "renovate/reviewdog-action-hadolint-1.x:renovate/reviewdog-action-hadolint-1.x",
             "--force-with-lease",
             "-u",
             "--no-verify",
             "--verbose",
             "--porcelain"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "Pushing to https://**redacted**@github.com/': No such device or address\n",
         "stack": "Error: Pushing to https://**redacted**@github.com/': No such device or address\n\n    at Object.action (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
 WARN: Error updating branch (repository=stackabletech/operator-templating, branch=renovate/reviewdog-action-hadolint-1.x)
       "err": {
         "task": {
           "commands": [
             "push",
             "origin",
             "renovate/reviewdog-action-hadolint-1.x:renovate/reviewdog-action-hadolint-1.x",
             "--force-with-lease",
             "-u",
             "--no-verify",
             "--verbose",
             "--porcelain"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "Pushing to https://**redacted**@github.com/': No such device or address\n",
         "stack": "Error: Pushing to https://**redacted**@github.com/': No such device or address\n\n    at Object.action (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/buildpack/tools/renovate/34.119.2/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
DEBUG: Closing Dependency Dashboard (repository=stackabletech/operator-templating)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
This should be a discussion, not a bug report
