### ISSUE TITLE
Artifact update problem; lockfiles not being updated

### ISSUE THREAD

**Issue by tgoeblu** [renovatebot/renovate#20459]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:34.97.5 (docker)

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.7.5-ee

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When running the CI, renovate (more or less) successfully scans the project and creates the MR with changes on all `package.json` files but **without** updating `yarn.lock`. 
The MR contains a comment with this error:

```
⚠ Artifact update problem
Renovate failed to update an artifact related to this branch. You probably do not want to merge this MR as-is.
♻ Renovate will retry this branch, including artifacts, only when one of the following happens:

any of the package files in this branch needs updating, or
the branch becomes conflicted, or
you click the rebase/retry checkbox if found above, or
you rename this MR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:
File name: yarn.lock

undefined
```

GitLab is hosted internally and so is the registry. In general, the new versions of all relevant packages are found (also company-internal packages) and updated by renovate, but as mentioned, the yarn.lock is not part of the MR changes.

The main problem for me to resolve this issue is the `undefined` for `yarn.lock` in the `Artifact update problem` comment.

<details>
  <summary>The bot's config.js:</summary>
 
```
module.exports = {
    githubTokenWarn: false,
    platform: 'gitlab',
    baseBranch: ['develop'],
    repositories: ['tgoeblu/demo-project'],
    extends: ['config:base'],
    endpoint: 'https://gitlab.company.net/api/v4/',
    npmrcMerge: true,
    lockFileMaintenance: {
        schedule: ['at any time'],
        enabled: true,
        commitMessageAction: 'Lock file maintenance',
        prBodyDefinitions: { Change: 'All locks refreshed' },
    },
    packageRules: [
        {
            matchDatasources: ['npm'],
            registryUrls: [
                'https://artifactory.company.net:123/artifactory/api/npm/npm/',
            ],
        },
    ],
};

```
</details>
<details>
  <summary>The repositorie's renovate.json:</summary>

```
 {
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base"],
  "timezone": "Europe/Berlin",
  "addLabels": ["renovate"],
  "npmrcMerge": true,
  "dependencyDashboard": true
}

```

</details>

<details>
  <summary>The package.json in the repo:</summary>

```
{
  "devDependencies": {
    "typescript": "~4.8.0"
  }
}

```
 </details>

### Relevant debug logs

```
DEBUG: GET https://nodejs.org/dist/index.json = (code=ECONNRESET, statusCode=-1 retryCount=2, duration=24) (repository=tgoeblu/demo-project, baseBranch=develop, branch=renovate/typescript-4.x)
DEBUG: Datasource connection error (repository=tgoeblu/demo-project, baseBranch=develop, branch=renovate/typescript-4.x)
       "datasource": "node",
       "packageName": "node",
       "url": undefined,
       "errCode": "ECONNRESET"
DEBUG: lock file error (repository=tgoeblu/demo-project, baseBranch=develop, branch=renovate/typescript-4.x)
       "err": {
         "message": "No tool releases found.",
         "stack": "Error: No tool releases found.
             at resolveConstraint (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/util/exec/containerbase.ts:220:11)
             at processTicksAndRejections (node:internal/process/task_queues:96:5)
             at generateInstallCommands (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/util/exec/containerbase.ts:271:27)
             at prepareRawExec (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/util/exec/index.ts:137:11)
             at exec (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/util/exec/index.ts:176:39)
             at Object.generateLockFile (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/modules/manager/npm/post-update/yarn.ts:278:5)
             at getAdditionalFiles (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/modules/manager/npm/post-update/index.ts:629:17)
             at processBranch (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/workers/repository/update/branch/index.ts:405:31)
             at writeUpdates (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/workers/repository/process/write.ts:159:17)
             at update (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/workers/repository/process/extract-update.ts:169:11)
             at Object.renovateRepository (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/workers/repository/index.ts:65:19)
             at attributes.repository (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/workers/global/index.ts:181:11)
             at start (/opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/workers/global/index.ts:166:7)
             at /opt/buildpack/tools/renovate/34.97.5/node_modules/renovate/lib/renovate.ts:18:22"
       },
       "type": "yarn"

```

```
DEBUG: No updated lock files in branch (repository=tgoeblu/demo-project, baseBranch=develop, branch=renovate/typescript-4.x)
DEBUG: Branch timestamp: 2023-01-30T21:05:37.231Z (repository=tgoeblu/demo-project, baseBranch=develop, branch=renovate/typescript-4.x)
DEBUG: PR is older than 2 hours, raise PR with lock file errors (repository=tgoeblu/demo-project, baseBranch=develop, branch=renovate/typescript-4.x)
```

```
 WARN: artifactErrors (repository=tgoeblu/demo-project, baseBranch=develop, branch=renovate/typescript-4.x)
       "artifactErrors": [{"lockFile": "yarn.lock"}]
```

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Not a bug. Raise a discussion instead
