### ISSUE TITLE
pip-compile ignores python `registryUrls`

### ISSUE THREAD

**Issue by tuturiffic** [renovatebot/renovate#20669]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When using the `pip-compile` manager with private pip registries, Renovate is able to identify that a newer package is available, but `pip-compile` cannot resolve packages that are hosted in these private registries. It behaves as though it is not provided the additional registryUrls, and is only looking at pypi.org.

A minimal reproduction can be found at [tuturiffic/renovate-pip-compile-private-registry](https://github.com/tuturiffic/renovate-pip-compile-private-registry). This appears to be the same issue as #14549.

From the PR created by Renovate:

```
Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v "/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry":"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -v "/tmp/containerbase":"/tmp/containerbase" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w "/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry" docker.io/renovate/sidecar bash -l -c "install-tool python 3.11.1 && pip install --user pip-tools && pip-compile requirements.in"
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.
Could not find a version that matches library-infrastructure>=12.0.4 (from -r requirements.in (line 1))
No versions found
Was https://pypi.org/simple reachable?
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Executing command(branch="renovate/library-infrastructure-12.x")
{
  "command": "docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\":\"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.11.1 && pip install --user pip-tools && pip-compile requirements.in\""
}
DEBUG: rawExec err(branch="renovate/library-infrastructure-12.x")
{
  "err": {
    "name": "ExecError",
    "cmd": "/bin/sh -c docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\":\"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.11.1 && pip install --user pip-tools && pip-compile requirements.in\"",
    "stderr": "WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.\nUsing legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.\nCould not find a version that matches library-infrastructure>=12.0.4 (from -r requirements.in (line 1))\nNo versions found\nWas https://pypi.org/simple reachable?\n",
    "stdout": "installing v2 tool python v3.11.1\nlinking tool python v3.11.1\nPython 3.11.1\npip 23.0.1 from /opt/buildpack/tools/python/3.11.1/lib/python3.11/site-packages/pip (python 3.11)\nInstalled v2 /usr/local/buildpack/tools/v2/python.sh in 26 seconds\nskip cleanup, not a docker build: 6b3b6e6cc0fd\nCollecting pip-tools\n  Downloading pip_tools-6.12.2-py3-none-any.whl (52 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 3.5 MB/s eta 0:00:00\nCollecting build\n  Downloading build-0.10.0-py3-none-any.whl (17 kB)\nCollecting click>=8\n  Downloading click-8.1.3-py3-none-any.whl (96 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 8.2 MB/s eta 0:00:00\nRequirement already satisfied: pip>=22.2 in /opt/buildpack/tools/python/3.11.1/lib/python3.11/site-packages (from pip-tools) (23.0.1)\nRequirement already satisfied: setuptools in /opt/buildpack/tools/python/3.11.1/lib/python3.11/site-packages (from pip-tools) (65.5.0)\nCollecting wheel\n  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)\nCollecting packaging>=19.0\n  Downloading packaging-23.0-py3-none-any.whl (42 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 4.9 MB/s eta 0:00:00\nCollecting pyproject_hooks\n  Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)\nInstalling collected packages: wheel, pyproject_hooks, packaging, click, build, pip-tools\nSuccessfully installed build-0.10.0 click-8.1.3 packaging-23.0 pip-tools-6.12.2 pyproject_hooks-1.0.0 wheel-0.38.4\n",
    "options": {
      "cwd": "/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry",
      "encoding": "utf-8",
      "env": {
        "PIP_CACHE_DIR": "/tmp/renovate-cache/others/pip",
        "HOME": "/home/ubuntu",
        "PATH": "/home/ubuntu/.local/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.9.3/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/renovateapp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LC_ALL": "C.UTF-8",
        "LANG": "C.UTF-8",
        "BUILDPACK_CACHE_DIR": "/tmp/containerbase",
        "CONTAINERBASE_CACHE_DIR": "/tmp/containerbase"
      },
      "maxBuffer": 10485760,
      "timeout": 900000
    },
    "exitCode": 2,
    "message": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\":\"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.11.1 && pip install --user pip-tools && pip-compile requirements.in\"\nWARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.\nUsing legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.\nCould not find a version that matches library-infrastructure>=12.0.4 (from -r requirements.in (line 1))\nNo versions found\nWas https://pypi.org/simple reachable?\n",
    "stack": "ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\":\"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.11.1 && pip install --user pip-tools && pip-compile requirements.in\"\nWARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.\nUsing legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.\nCould not find a version that matches library-infrastructure>=12.0.4 (from -r requirements.in (line 1))\nNo versions found\nWas https://pypi.org/simple reachable?\n\n    at ChildProcess.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/exec/common.js:87:24)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)"
  }
}
DEBUG: Failed to pip-compile(branch="renovate/library-infrastructure-12.x")
{
  "err": {
    "name": "ExecError",
    "cmd": "/bin/sh -c docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\":\"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.11.1 && pip install --user pip-tools && pip-compile requirements.in\"",
    "stderr": "WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.\nUsing legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.\nCould not find a version that matches library-infrastructure>=12.0.4 (from -r requirements.in (line 1))\nNo versions found\nWas https://pypi.org/simple reachable?\n",
    "stdout": "installing v2 tool python v3.11.1\nlinking tool python v3.11.1\nPython 3.11.1\npip 23.0.1 from /opt/buildpack/tools/python/3.11.1/lib/python3.11/site-packages/pip (python 3.11)\nInstalled v2 /usr/local/buildpack/tools/v2/python.sh in 26 seconds\nskip cleanup, not a docker build: 6b3b6e6cc0fd\nCollecting pip-tools\n  Downloading pip_tools-6.12.2-py3-none-any.whl (52 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 3.5 MB/s eta 0:00:00\nCollecting build\n  Downloading build-0.10.0-py3-none-any.whl (17 kB)\nCollecting click>=8\n  Downloading click-8.1.3-py3-none-any.whl (96 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 8.2 MB/s eta 0:00:00\nRequirement already satisfied: pip>=22.2 in /opt/buildpack/tools/python/3.11.1/lib/python3.11/site-packages (from pip-tools) (23.0.1)\nRequirement already satisfied: setuptools in /opt/buildpack/tools/python/3.11.1/lib/python3.11/site-packages (from pip-tools) (65.5.0)\nCollecting wheel\n  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)\nCollecting packaging>=19.0\n  Downloading packaging-23.0-py3-none-any.whl (42 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 4.9 MB/s eta 0:00:00\nCollecting pyproject_hooks\n  Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)\nInstalling collected packages: wheel, pyproject_hooks, packaging, click, build, pip-tools\nSuccessfully installed build-0.10.0 click-8.1.3 packaging-23.0 pip-tools-6.12.2 pyproject_hooks-1.0.0 wheel-0.38.4\n",
    "options": {
      "cwd": "/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry",
      "encoding": "utf-8",
      "env": {
        "PIP_CACHE_DIR": "/tmp/renovate-cache/others/pip",
        "HOME": "/home/ubuntu",
        "PATH": "/home/ubuntu/.local/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.9.3/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/renovateapp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LC_ALL": "C.UTF-8",
        "LANG": "C.UTF-8",
        "BUILDPACK_CACHE_DIR": "/tmp/containerbase",
        "CONTAINERBASE_CACHE_DIR": "/tmp/containerbase"
      },
      "maxBuffer": 10485760,
      "timeout": 900000
    },
    "exitCode": 2,
    "message": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\":\"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.11.1 && pip install --user pip-tools && pip-compile requirements.in\"\nWARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.\nUsing legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.\nCould not find a version that matches library-infrastructure>=12.0.4 (from -r requirements.in (line 1))\nNo versions found\nWas https://pypi.org/simple reachable?\n",
    "stack": "ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\":\"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/containerbase\":\"/tmp/containerbase\" -e PIP_CACHE_DIR -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/mnt/renovate/gh/tuturiffic/renovate-pip-compile-private-registry\" docker.io/renovate/sidecar bash -l -c \"install-tool python 3.11.1 && pip install --user pip-tools && pip-compile requirements.in\"\nWARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.\nUsing legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.\nCould not find a version that matches library-infrastructure>=12.0.4 (from -r requirements.in (line 1))\nNo versions found\nWas https://pypi.org/simple reachable?\n\n    at ChildProcess.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/exec/common.js:87:24)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)"
  }
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

EDIT: To make it easier, the reproduction is at https://github.com/tuturiffic/renovate-pip-compile-private-registry

**Comment by HonkingGoose** [comment]
@tuturiffic I see you're listing secrets in the `renovate.json` file of your reproduction. You're not exposing your real secrets here, I hope?

https://github.com/tuturiffic/renovate-pip-compile-private-registry/blob/901efa0402c4a3cc549c8ef960b32f465f6bcd7e/renovate.json#L19-L21

**Comment by tuturiffic** [comment]
@HonkingGoose I'm not sure I follow: that would be the encrypted password in there. In order for me to post a functional reproduction, I do need to include a functional password -- but since it's encrypted, it's not actually readable.

**Comment by HonkingGoose** [comment]
Oh okay, just checking. 😄

**Comment by rarkins** [comment]
Can it be reproduced? See our guide above

**Comment by tuturiffic** [comment]
Yup, it can be reproduced fairly easily, and there's a minimal reproduction that's already up: https://github.com/tuturiffic/renovate-pip-compile-private-registry
