### ISSUE TITLE
GITHUB_COM_TOKEN locally with cli

### ISSUE THREAD

**Issue by cdenneen** [renovatebot/renovate#20810]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

npm cli

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I can confirm my GH token works:

```
❯ curl -s -X GET -u $GITHUB_COM_TOKEN:x-oauth-basic 'https://api.github.com/user' | head -3
{
  "login": "cdenneen",
  "id": 720097,
```
but doesn't seem to work with renovate

```
❯ renovate --dry-run
 WARN: cli config dryRun property has been changed to full
FATAL: Authentication failure
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "IgqlRoFjTli0EtVo5M66K",
           "msg": "Authentication failure"
         }
       ]
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /Users/cdenneen/src/gitlab/gitops/cluster/config/config.js
DEBUG: No config file found on disk - skipping
 WARN: cli config dryRun property has been changed to full
DEBUG: Converting GITHUB_COM_TOKEN into a global host rule
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {"dryRun": "full"}
DEBUG: Env config
       "config": {
         "hostRules": [
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "token": "***********"
       }
DEBUG: Combined config
       "config": {
         "hostRules": [
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "token": "***********",
         "dryRun": "full"
       }
DEBUG: Found valid git version: 2.39.2
DEBUG: Using default github endpoint: https://api.github.com/
DEBUG: GET https://api.github.com/user = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=401 retryCount=0, duration=162)
DEBUG: GitHub failure: Bad credentials
       "token": "***********",
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1678304262505,
           "socket": 1678304262507,
           "lookup": 1678304262550,
           "connect": 1678304262582,
           "secureConnect": 1678304262618,
           "upload": 1678304262618,
           "response": 1678304262664,
           "end": 1678304262667,
           "phases": {
             "wait": 2,
             "dns": 43,
             "tcp": 32,
             "tls": 36,
             "request": 0,
             "firstByte": 46,
             "download": 3,
             "total": 162
           }
         },
         "message": "Response code 401 (Unauthorized)",
         "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/usr/local/lib/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/34.159.1 (https://github.com/renovatebot/renovate)",
             "accept": "application/json, application/vnd.github.v3+json",
             "authorization": "***********",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://api.github.com/user",
           "hostType": "github",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 401,
           "statusMessage": "Unauthorized",
           "body": {
             "message": "Bad credentials",
             "documentation_url": "https://docs.github.com/rest"
           },
           "headers": {
             "server": "GitHub.com",
             "date": "Wed, 08 Mar 2023 19:37:42 GMT",
             "content-type": "application/json; charset=utf-8",
             "content-length": "80",
             "x-github-media-type": "github.v3",
             "x-ratelimit-limit": "60",
             "x-ratelimit-remaining": "42",
             "x-ratelimit-reset": "1678306329",
             "x-ratelimit-used": "18",
             "x-ratelimit-resource": "core",
             "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
             "access-control-allow-origin": "*",
             "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
             "x-frame-options": "deny",
             "x-content-type-options": "nosniff",
             "x-xss-protection": "0",
             "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
             "content-security-policy": "default-src 'none'",
             "vary": "Accept-Encoding, Accept, X-Requested-With",
             "x-github-request-id": "9DAF:6543:46329D5:8F7109F:6408E406"
           },
           "httpVersion": "1.1",
           "retryCount": 0
         }
       }
DEBUG: Error authenticating with GitHub
       "err": {
         "hostType": "github",
         "err": {
           "name": "HTTPError",
           "code": "ERR_NON_2XX_3XX_RESPONSE",
           "timings": {
             "start": 1678304262505,
             "socket": 1678304262507,
             "lookup": 1678304262550,
             "connect": 1678304262582,
             "secureConnect": 1678304262618,
             "upload": 1678304262618,
             "response": 1678304262664,
             "end": 1678304262667,
             "phases": {
               "wait": 2,
               "dns": 43,
               "tcp": 32,
               "tls": 36,
               "request": 0,
               "firstByte": 46,
               "download": 3,
               "total": 162
             }
           },
           "message": "Response code 401 (Unauthorized)",
           "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/usr/local/lib/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
           "options": {
             "headers": {
               "user-agent": "RenovateBot/34.159.1 (https://github.com/renovatebot/renovate)",
               "accept": "application/json, application/vnd.github.v3+json",
               "authorization": "***********",
               "accept-encoding": "gzip, deflate, br"
             },
             "url": "https://api.github.com/user",
             "hostType": "github",
             "username": "",
             "password": "",
             "method": "GET",
             "http2": false
           },
           "response": {
             "statusCode": 401,
             "statusMessage": "Unauthorized",
             "body": {
               "message": "Bad credentials",
               "documentation_url": "https://docs.github.com/rest"
             },
             "headers": {
               "server": "GitHub.com",
               "date": "Wed, 08 Mar 2023 19:37:42 GMT",
               "content-type": "application/json; charset=utf-8",
               "content-length": "80",
               "x-github-media-type": "github.v3",
               "x-ratelimit-limit": "60",
               "x-ratelimit-remaining": "42",
               "x-ratelimit-reset": "1678306329",
               "x-ratelimit-used": "18",
               "x-ratelimit-resource": "core",
               "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
               "access-control-allow-origin": "*",
               "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
               "x-frame-options": "deny",
               "x-content-type-options": "nosniff",
               "x-xss-protection": "0",
               "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
               "content-security-policy": "default-src 'none'",
               "vary": "Accept-Encoding, Accept, X-Requested-With",
               "x-github-request-id": "9DAF:6543:46329D5:8F7109F:6408E406"
             },
             "httpVersion": "1.1",
             "retryCount": 0
           }
         },
         "message": "external-host-error",
         "stack": "Error: external-host-error\n    at handleGotError (/usr/local/lib/node_modules/renovate/lib/util/http/github.ts:128:14)\n    at GithubHttp.request (/usr/local/lib/node_modules/renovate/lib/util/http/github.ts:370:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at GithubHttp.requestJson (/usr/local/lib/node_modules/renovate/lib/util/http/index.ts:256:17)\n    at getUserDetails (/usr/local/lib/node_modules/renovate/lib/modules/platform/github/user.ts:13:7)\n    at Proxy.initPlatform (/usr/local/lib/node_modules/renovate/lib/modules/platform/github/index.ts:153:36)\n    at initPlatform (/usr/local/lib/node_modules/renovate/lib/modules/platform/index.ts:49:24)\n    at globalInitialize (/usr/local/lib/node_modules/renovate/lib/workers/global/initialize.ts:71:12)\n    at /usr/local/lib/node_modules/renovate/lib/workers/global/index.ts:131:16\n    at start (/usr/local/lib/node_modules/renovate/lib/workers/global/index.ts:120:5)\n    at /usr/local/lib/node_modules/renovate/lib/renovate.ts:18:22"
       }
FATAL: Authentication failure
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by Churro** [comment]
renovate doesn't use OAuth tokens, typically starting with `gho_...` to authorize with GitHub. Make sure to generate a personal access token (see [here](https://docs.renovatebot.com/modules/platform/github/)). Confirmation that it is working should be possible like this:
```
curl -X GET -H 'Authorization: token <personal access token>' 'https://api.github.com/user'
```
