### ISSUE TITLE
osvVulnerabilityAlerts - Unable to read vulnerability information

### ISSUE THREAD

**Issue by philippe-granet** [renovatebot/renovate#20875]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.1.1

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.8.2

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

After upgrading to renovate >= v35.x , `osvVulnerabilityAlerts` feature doesn't work anymore and there is only a warn log (even with trace log level): `Unable to read vulnerability information`.  
It work correctly on version 34.160.0.

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Unable to read vulnerability information (repository=[redacted], baseBranch=master)
       "err": {
         "stack": "Error: \n    at OsvOffline.initialize (/opt/buildpack/tools/renovate/35.1.1/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:15:19)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Function.create (/opt/buildpack/tools/renovate/35.1.1/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:25:9)\n    at Vulnerabilities.initialize (/opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:44:23)\n    at Function.create (/opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:49:5)\n    at fetchVulnerabilities (/opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/workers/repository/process/extract-update.ts:177:31)\n    at lookup (/opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/workers/repository/process/extract-update.ts:189:3)\n    at extractDependencies (/opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/workers/repository/process/index.ts:131:31)\n    at Object.renovateRepository (/opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/workers/repository/index.ts:56:9)\n    at attributes.repository (/opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/workers/global/index.ts:181:11)\n    at start (/opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/workers/global/index.ts:166:7)\n    at /opt/buildpack/tools/renovate/35.1.1/node_modules/renovate/lib/renovate.ts:18:22"
       }
```

</details>

### Have you created a minimal reproduction repository?

I have read the minimal reproductions documentation and linked to such a repository in the bug description

**Comment by rarkins** [comment]
The dependency was upgraded recently in 35.1.0: https://github.com/renovatebot/renovate/pull/20868

Can you check if it's the same in 35.0.0?

**Comment by philippe-granet** [comment]
@rarkins Same problem with 35.0.1

**Comment by philippe-granet** [comment]
@rarkins I add debug log:

```
RequestError [HttpError]: fetch failed
    at /opt/buildpack/tools/renovate/35.0.1/node_modules/@octokit/request/dist-src/fetch-wrapper.js:96:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at tryDownloadDb (/opt/buildpack/tools/renovate/35.0.1/node_modules/@renovatebot/osv-offline/dist/lib/download.js:40:26)
    at OsvOffline.initialize (/opt/buildpack/tools/renovate/35.0.1/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:13:25)
    at Function.create (/opt/buildpack/tools/renovate/35.0.1/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:25:9)
    at Vulnerabilities.initialize (/opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:44:23)
    at Function.create (/opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:49:5)
    at fetchVulnerabilities (/opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/workers/repository/process/extract-update.ts:177:31)
    at lookup (/opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/workers/repository/process/extract-update.ts:189:3)
    at extractDependencies (/opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/workers/repository/process/index.ts:131:31)
    at Object.renovateRepository (/opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/workers/repository/index.ts:56:9)
    at attributes.repository (/opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/workers/global/index.ts:181:11)
    at start (/opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/workers/global/index.ts:166:7)
    at /opt/buildpack/tools/renovate/35.0.1/node_modules/renovate/lib/renovate.ts:18:22 {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/renovatebot/osv-offline/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.7 octokit-core.js/4.2.0 Node.js/18.15.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

**Comment by rarkins** [comment]
That log indicates a 500 error from GitHub when fetching https://api.github.com/repos/renovatebot/osv-offline/releases, which would normally point to it being a GitHub problem, not Renovate. Is it repeatable every time though?

**Comment by rarkins** [comment]
It does not reproduce for me, instead generates the expected PR: https://github.com/renovate-reproductions/20875/pull/1
