### ISSUE TITLE
Upgrade Go major dependency with vendor folder fails

### ISSUE THREAD

**Issue by hugoboos** [renovatebot/renovate#20993]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.8.0

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

A Go project with vendoring enabled (`go mod vendor`). A major version upgrade of a dependency fails.

The `gomodUpdateImportPaths` is set.

The `mod` command fails. It is part of the update command.

```sh
$ mod upgrade --mod-name=github.com/google/go-github/v48 -t=50
could not load package: err: exit status 1: stderr: go: inconsistent vendoring in /code:
	github.com/google/go-github/v48@v48.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/google/go-github/v50@v50.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/google/go-github/v48@v48.1.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```

Reproduction repository: https://gitlab.com/hugoboos/renovate-go-update-import

Relevant merge request: https://gitlab.com/hugoboos/renovate-go-update-import/-/merge_requests/2

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Executing command (repository=hugoboos/renovate-go-update-import, branch=renovate/github.com-google-go-github-v48-50.x)
       "command": "docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\":\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" -v \"/tmp/renovate/tmp/cache\":\"/tmp/renovate/tmp/cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" docker.io/containerbase/sidecar bash -l -c \"install-tool golang 1.20.2 && go get -d -t ./... && go install github.com/marwan-at-work/mod/cmd/mod@latest && mod upgrade --mod-name=github.com/google/go-github/v48 -t=50 && go mod tidy && go mod vendor && go mod tidy && go mod tidy\""
DEBUG: rawExec err (repository=hugoboos/renovate-go-update-import, branch=renovate/github.com-google-go-github-v48-50.x)
       "err": {
         "cmd": "/bin/sh -c docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\":\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" -v \"/tmp/renovate/tmp/cache\":\"/tmp/renovate/tmp/cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" docker.io/containerbase/sidecar bash -l -c \"install-tool golang 1.20.2 && go get -d -t ./... && go install github.com/marwan-at-work/mod/cmd/mod@latest && mod upgrade --mod-name=github.com/google/go-github/v48 -t=50 && go mod tidy && go mod vendor && go mod tidy && go mod tidy\"",
         "stderr": "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested\ngo: added github.com/google/go-github/v48 v48.2.0\ncould not load package: err: exit status 1: stderr: go: inconsistent vendoring in /tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import:\n\tgithub.com/google/go-github/v48@v48.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v50@v50.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v48@v48.1.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\n\tTo ignore the vendor directory, use -mod=readonly or -mod=mod.\n\tTo sync the vendor directory, run:\n\t\tgo mod vendor\n\n",
         "stdout": "installing v2 tool golang v1.20.2\nlinking tool golang v1.20.2\ngo version go1.20.2 linux/amd64\nGO111MODULE=\"\"\nGOARCH=\"amd64\"\nGOBIN=\"\"\nGOCACHE=\"/home/ubuntu/.cache/go-build\"\nGOENV=\"/home/ubuntu/.config/go/env\"\nGOEXE=\"\"\nGOEXPERIMENT=\"\"\nGOFLAGS=\"-modcacherw\"\nGOHOSTARCH=\"amd64\"\nGOHOSTOS=\"linux\"\nGOINSECURE=\"\"\nGOMODCACHE=\"/tmp/renovate/tmp/cache/others/go/pkg/mod\"\nGONOPROXY=\"\"\nGONOSUMDB=\"\"\nGOOS=\"linux\"\nGOPATH=\"/tmp/renovate/tmp/cache/others/go\"\nGOPRIVATE=\"\"\nGOPROXY=\"https://proxy.golang.org,direct\"\nGOROOT=\"/opt/buildpack/tools/golang/1.20.2\"\nGOSUMDB=\"off\"\nGOTMPDIR=\"\"\nGOTOOLDIR=\"/opt/buildpack/tools/golang/1.20.2/pkg/tool/linux_amd64\"\nGOVCS=\"\"\nGOVERSION=\"go1.20.2\"\nGCCGO=\"gccgo\"\nGOAMD64=\"v1\"\nAR=\"ar\"\nCC=\"gcc\"\nCXX=\"g++\"\nCGO_ENABLED=\"0\"\nGOMOD=\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import/go.mod\"\nGOWORK=\"\"\nCGO_CFLAGS=\"-O2 -g\"\nCGO_CPPFLAGS=\"\"\nCGO_CXXFLAGS=\"-O2 -g\"\nCGO_FFLAGS=\"-O2 -g\"\nCGO_LDFLAGS=\"-O2 -g\"\nPKG_CONFIG=\"pkg-config\"\nGOGCCFLAGS=\"-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1274939378=/tmp/go-build -gno-record-gcc-switches\"\nInstalled v2 /usr/local/buildpack/tools/v2/golang.sh in 5 seconds\n",
         "options": {
           "cwd": "/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import",
           "encoding": "utf-8",
           "env": {
             ...
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "name": "ExecError",
         "message": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\":\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" -v \"/tmp/renovate/tmp/cache\":\"/tmp/renovate/tmp/cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" docker.io/containerbase/sidecar bash -l -c \"install-tool golang 1.20.2 && go get -d -t ./... && go install github.com/marwan-at-work/mod/cmd/mod@latest && mod upgrade --mod-name=github.com/google/go-github/v48 -t=50 && go mod tidy && go mod vendor && go mod tidy && go mod tidy\"\nWARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested\ngo: added github.com/google/go-github/v48 v48.2.0\ncould not load package: err: exit status 1: stderr: go: inconsistent vendoring in /tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import:\n\tgithub.com/google/go-github/v48@v48.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v50@v50.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v48@v48.1.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\n\tTo ignore the vendor directory, use -mod=readonly or -mod=mod.\n\tTo sync the vendor directory, run:\n\t\tgo mod vendor\n\n",
         "stack": "ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\":\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" -v \"/tmp/renovate/tmp/cache\":\"/tmp/renovate/tmp/cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" docker.io/containerbase/sidecar bash -l -c \"install-tool golang 1.20.2 && go get -d -t ./... && go install github.com/marwan-at-work/mod/cmd/mod@latest && mod upgrade --mod-name=github.com/google/go-github/v48 -t=50 && go mod tidy && go mod vendor && go mod tidy && go mod tidy\"\nWARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested\ngo: added github.com/google/go-github/v48 v48.2.0\ncould not load package: err: exit status 1: stderr: go: inconsistent vendoring in /tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import:\n\tgithub.com/google/go-github/v48@v48.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v50@v50.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v48@v48.1.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\n\tTo ignore the vendor directory, use -mod=readonly or -mod=mod.\n\tTo sync the vendor directory, run:\n\t\tgo mod vendor\n\n\n    at ChildProcess.<anonymous> (/tmp/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)"
       },
       "durationMs": 86751
DEBUG: Failed to update go.sum (repository=hugoboos/renovate-go-update-import, branch=renovate/github.com-google-go-github-v48-50.x)
       "err": {
         "cmd": "/bin/sh -c docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\":\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" -v \"/tmp/renovate/tmp/cache\":\"/tmp/renovate/tmp/cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" docker.io/containerbase/sidecar bash -l -c \"install-tool golang 1.20.2 && go get -d -t ./... && go install github.com/marwan-at-work/mod/cmd/mod@latest && mod upgrade --mod-name=github.com/google/go-github/v48 -t=50 && go mod tidy && go mod vendor && go mod tidy && go mod tidy\"",
         "stderr": "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested\ngo: added github.com/google/go-github/v48 v48.2.0\ncould not load package: err: exit status 1: stderr: go: inconsistent vendoring in /tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import:\n\tgithub.com/google/go-github/v48@v48.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v50@v50.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v48@v48.1.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\n\tTo ignore the vendor directory, use -mod=readonly or -mod=mod.\n\tTo sync the vendor directory, run:\n\t\tgo mod vendor\n\n",
         "stdout": "installing v2 tool golang v1.20.2\nlinking tool golang v1.20.2\ngo version go1.20.2 linux/amd64\nGO111MODULE=\"\"\nGOARCH=\"amd64\"\nGOBIN=\"\"\nGOCACHE=\"/home/ubuntu/.cache/go-build\"\nGOENV=\"/home/ubuntu/.config/go/env\"\nGOEXE=\"\"\nGOEXPERIMENT=\"\"\nGOFLAGS=\"-modcacherw\"\nGOHOSTARCH=\"amd64\"\nGOHOSTOS=\"linux\"\nGOINSECURE=\"\"\nGOMODCACHE=\"/tmp/renovate/tmp/cache/others/go/pkg/mod\"\nGONOPROXY=\"\"\nGONOSUMDB=\"\"\nGOOS=\"linux\"\nGOPATH=\"/tmp/renovate/tmp/cache/others/go\"\nGOPRIVATE=\"\"\nGOPROXY=\"https://proxy.golang.org,direct\"\nGOROOT=\"/opt/buildpack/tools/golang/1.20.2\"\nGOSUMDB=\"off\"\nGOTMPDIR=\"\"\nGOTOOLDIR=\"/opt/buildpack/tools/golang/1.20.2/pkg/tool/linux_amd64\"\nGOVCS=\"\"\nGOVERSION=\"go1.20.2\"\nGCCGO=\"gccgo\"\nGOAMD64=\"v1\"\nAR=\"ar\"\nCC=\"gcc\"\nCXX=\"g++\"\nCGO_ENABLED=\"0\"\nGOMOD=\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import/go.mod\"\nGOWORK=\"\"\nCGO_CFLAGS=\"-O2 -g\"\nCGO_CPPFLAGS=\"\"\nCGO_CXXFLAGS=\"-O2 -g\"\nCGO_FFLAGS=\"-O2 -g\"\nCGO_LDFLAGS=\"-O2 -g\"\nPKG_CONFIG=\"pkg-config\"\nGOGCCFLAGS=\"-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1274939378=/tmp/go-build -gno-record-gcc-switches\"\nInstalled v2 /usr/local/buildpack/tools/v2/golang.sh in 5 seconds\n",
         "options": {
           "cwd": "/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import",
           "encoding": "utf-8",
           "env": {
             ...
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "name": "ExecError",
         "message": "Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\":\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" -v \"/tmp/renovate/tmp/cache\":\"/tmp/renovate/tmp/cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" docker.io/containerbase/sidecar bash -l -c \"install-tool golang 1.20.2 && go get -d -t ./... && go install github.com/marwan-at-work/mod/cmd/mod@latest && mod upgrade --mod-name=github.com/google/go-github/v48 -t=50 && go mod tidy && go mod vendor && go mod tidy && go mod tidy\"\nWARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested\ngo: added github.com/google/go-github/v48 v48.2.0\ncould not load package: err: exit status 1: stderr: go: inconsistent vendoring in /tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import:\n\tgithub.com/google/go-github/v48@v48.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v50@v50.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v48@v48.1.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\n\tTo ignore the vendor directory, use -mod=readonly or -mod=mod.\n\tTo sync the vendor directory, run:\n\t\tgo mod vendor\n\n",
         "stack": "ExecError: Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\":\"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" -v \"/tmp/renovate/tmp/cache\":\"/tmp/renovate/tmp/cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import\" docker.io/containerbase/sidecar bash -l -c \"install-tool golang 1.20.2 && go get -d -t ./... && go install github.com/marwan-at-work/mod/cmd/mod@latest && mod upgrade --mod-name=github.com/google/go-github/v48 -t=50 && go mod tidy && go mod vendor && go mod tidy && go mod tidy\"\nWARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested\ngo: added github.com/google/go-github/v48 v48.2.0\ncould not load package: err: exit status 1: stderr: go: inconsistent vendoring in /tmp/renovate/tmp/base/repos/gitlab/hugoboos/renovate-go-update-import:\n\tgithub.com/google/go-github/v48@v48.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v50@v50.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\tgithub.com/google/go-github/v48@v48.1.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod\n\n\tTo ignore the vendor directory, use -mod=readonly or -mod=mod.\n\tTo sync the vendor directory, run:\n\t\tgo mod vendor\n\n\n    at ChildProcess.<anonymous> (/tmp/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)"
       }
DEBUG: Updated 1 package files (repository=hugoboos/renovate-go-update-import, branch=renovate/github.com-google-go-github-v48-50.x)
DEBUG: No updated lock files in branch (repository=hugoboos/renovate-go-update-import, branch=renovate/github.com-google-go-github-v48-50.x)
```

</details>

### Have you created a minimal reproduction repository?

I have read the minimal reproductions documentation and linked to such a repository in the bug description

**Comment by rarkins** [comment]
What could/should Renovate do differently? Often major updates require manual intervention and there's no automated way around it. Unless you can suggest something Renovate is doing wrong then this is not a valid bug report
