### ISSUE TITLE
Renovate v35 does not fallback to IPv4 if IPv6 is not available

### ISSUE THREAD

**Issue by uhthomas** [renovatebot/renovate#21009]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.8.1

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

N/A

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

The latest version of Renovate (v35) times out when connecting to private docker registries. Renovate v34 works completely fine with the same configuration.

@rarkins Suspects this could be related to the change from Node.js v16 to v18.

See: https://github.com/renovatebot/renovate/discussions/20982

### Relevant debug logs

<details><summary>Logs</summary>

```
{
        "name": "renovate",
        "hostname": "renovate-replacement-test-manual-0-2slz6",
        "pid": 4,
        "level": 40,
        "logContext": "Zy20EbGtT8PWdzoHp3E2K",
        "repository": "example/repository",
        "registryHost": "https://docker-registry.example.com",
        "dockerRepository": "bullseye",
        "err": {
                "name": "TimeoutError",
                "code": "ETIMEDOUT",
                "timings": {
                        "start": 1678971717050,
                        "socket": 1678971717050,
                        "lookup": 1678971717051,
                        "error": 1678971777055,
                        "phases": {
                                "wait": 0,
                                "dns": 1,
                                "total": 60005
                        }
                },
                "event": "request",
                "message": "Timeout awaiting 'request' for 60000ms",
                "stack": "RequestError: Timeout awaiting 'request' for 60000ms\n    at ClientRequest.<anonymous> (/opt/buildpack/tools/renovate/35.8.1/node_modules/got/dist/source/core/index.js:970:65)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.emit (node:domain:489:12)\n    at ClientRequest.origin.emit (/opt/buildpack/tools/renovate/35.8.1/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/opt/buildpack/tools/renovate/35.8.1/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (node:internal/timers:571:11)\n    at processTimers (node:internal/timers:512:7)",
                "options": {
                        "headers": {
                                "user-agent": "RenovateBot/35.8.1 (https://github.com/renovatebot/renovate)",
                                "accept": "application/json",
                                "accept-encoding": "gzip, deflate, br"
                        },
                        "url": "https://docker-registry.example.com/v2/bullseye/tags/list?n=10000",
                        "hostType": "docker",
                        "username": "",
                        "password": "",
                        "method": "GET",
                        "http2": false
                }
        },
        "msg": "Error obtaining docker token",
        "time": "2023-03-16T13:02:57.056Z",
        "v": 0
}
{
        "name": "renovate",
        "hostname": "renovate-replacement-test-manual-0-2slz6",
        "pid": 4,
        "level": 20,
        "logContext": "Zy20EbGtT8PWdzoHp3E2K",
        "repository": "example/repository",
        "msg": "Failed to get authHeaders for getTags lookup",
        "time": "2023-03-16T13:02:57.067Z",
        "v": 0
}
{
        "name": "renovate",
        "hostname": "renovate-replacement-test-manual-0-2slz6",
        "pid": 4,
        "level": 20,
        "logContext": "Zy20EbGtT8PWdzoHp3E2K",
        "repository": "example/repository",
        "dependency": "docker-registry.example.com/bullseye",
        "packageFile": "bullseye.Dockerfile",
        "msg": "Failed to look up docker package docker-registry.example.com/bullseye",
        "time": "2023-03-16T13:02:57.068Z",
        "v": 0
}
```

```
{
        "name": "renovate",
        "hostname": "renovate-replacement-test-manual-0-2slz6",
        "pid": 4,
        "level": 20,
        "logContext": "Zy20EbGtT8PWdzoHp3E2K",
        "repository": "example/repository",
        "urls": {
                "https://bitbucket.example.com/./rest/api/1.0/projects/example/repos/repository/pull-requests (GET,200)": 1,
                "https://bitbucket.example.com/./rest/api/1.0/projects/example/repos/repository/pull-requests/21 (GET,200)": 1,
                "https://bitbucket.example.com/./rest/api/1.0/projects/example/repos/repository/pull-requests/21 (PUT,200)": 1,
                "https://bitbucket.example.com/./rest/api/1.0/projects/example/repos/repository/pull-requests/21/decline (POST,200)": 1,
                "https://bitbucket.example.com/./rest/api/1.0/projects/example/repos/repository/pull-requests/22 (GET,200)": 1,
                "https://bitbucket.example.com/./rest/api/1.0/projects/example/repos/repository/pull-requests/22 (PUT,200)": 1,
                "https://bitbucket.example.com/./rest/api/1.0/projects/example/repos/repository/pull-requests/22/decline (POST,200)": 1,
                "https://docker-registry.example.com/v2/bullseye/tags/list (GET,-1)": 1,
                "https://docker-registry.example.com/v2/stretch/tags/list (GET,-1)": 1,
                "https://docker-registry.example.com/v2/stretch/tags/list (GET,-1)": 1
        },
        "hostStats": {
                "bitbucket.example.com": {
                        "requestCount": 7,
                        "requestAvgMs": 52,
                        "queueAvgMs": 0
                },
                "docker-registry.example.com": {
                        "requestCount": 3,
                        "requestAvgMs": 60002,
                        "queueAvgMs": 0
                }
        },
        "totalRequests": 10,
        "msg": "http statistics",
        "time": "2023-03-16T13:02:58.138Z",
        "v": 0
}
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by rarkins** [comment]
Can you confirm that configuration of host rules has nothing to do with it? And if so remove from the description as it's a possible distraction

**Comment by uhthomas** [comment]
Given our discussion, I'm pretty confident the host rules have nothing to do with it. Will edit the description.

<details>

```json
{
        "name": "renovate",
        "hostname": "renovate-replacement-test-manual-0-2slz6",
        "pid": 4,
        "level": 20,
        "logContext": "Zy20EbGtT8PWdzoHp3E2K",
        "msg": "Converting DOCKER_DOCKER__REGISTRY_EXAMPLE_COM_PASSWORD into a global host rule",
        "time": "2023-03-16T12:59:39.618Z",
        "v": 0
}
{
        "name": "renovate",
        "hostname": "renovate-replacement-test-manual-0-2slz6",
        "pid": 4,
        "level": 20,
        "logContext": "Zy20EbGtT8PWdzoHp3E2K",
        "msg": "Converting DOCKER_DOCKER__REGISTRY_EXAMPLE_COM_USERNAME into a global host rule",
        "time": "2023-03-16T12:59:39.619Z",
        "v": 0
}
{
        "name": "renovate",
        "hostname": "renovate-replacement-test-manual-0-2slz6",
        "pid": 4,
        "level": 20,
        "logContext": "Zy20EbGtT8PWdzoHp3E2K",
        "msg": "Adding password authentication for docker-registry.example.com to hostRules",
        "time": "2023-03-16T12:59:39.680Z",
        "v": 0
}
```

</details>

**Comment by uhthomas** [comment]
I was thinking a bit and thought it might be worth looking at the results from DNS. The Renovate container doesn't have DNS utils, but does have curl. The verbose output shows that it first tries an IPv6 address and then settles on IPv4. Is it possible this could be related?

```
❯ k -n renovate exec renovate-s-27984573-j2vpg -- curl -s -vv https://docker-registry.example.com
*   Trying 4a06:91c0:3605::7:443...
* TCP_NODELAY set
*   Trying 198.141.45.12:443...
* TCP_NODELAY set
* Connected to docker-registry.example.com (198.141.45.12) port 443 (#0)
* ```

**Comment by uhthomas** [comment]
Maybe https://github.com/nodejs/node/pull/39987?

**Comment by viceice** [comment]
so not a direct renovate issue, but a nodejs change from v16 to v18

**Comment by uhthomas** [comment]
> so not a direct renovate issue, but a nodejs change from v16 to v18

Kinda. I suspect this is the issue we're seeing. I believe `AAAA` records exist but are not accessible from this environment.

Despite this, I would expect [got](https://github.com/sindresorhus/got) to fallback to IPv4 if IPv6 is unavailable, like curl does. Should we open an issue there? Is it possible this is actually something which should be implemented in the native Node.js HTTP API?

**Comment by viceice** [comment]
i don't think got will change it in the old version. maybe our DNS caching is doing something wrong?

but I'm wondering why a host would request aaaa records if it hasn't ipv6 addresses? 🤔

**Comment by mtompkins** [comment]
Contributing an early discover of mine as I'm just starting to standup renovate in my pipeline (Gitlab Selfhosted).
In v35:latest / 35.48.2 I see failures from the renovate job that reference ipv6 which is enabled in my docker stack. 

The error is `code=EHOSTUNREACH` . As I have a traefik stack, I'll have to set aside some time to truly debug and perhaps provide some further information to you.

What is interesting is, changing the image to `34-slim` removes this issue.
This last comment was why I troubled to post ... hopefully it confirms that "something" is indeed in play and may not be an edge case.

**Comment by rarkins** [comment]
This could be related to Node 18 which is used since Renovate v35. Renovate itself doesn't know/care about IPv4/v6

**Comment by mtompkins** [comment]
> This could be related to Node 18 which is used since Renovate v35. Renovate itself doesn't know/care about IPv4/v6

Makes perfect sense to me.

**Comment by rarkins** [comment]
We also use `got` v11 for our http abstraction layer. There aren't any known IPv6 issues there: https://github.com/search?q=repo%3Asindresorhus%2Fgot+ipv6&type=issues

**Comment by viceice** [comment]
@rarkins were doing some custom DNS lookup for got via nodejs API. maybe we can improve something?

https://github.com/renovatebot/renovate/blob/6d0aeee2b8243870738eeff4af4c6fa1b64b7808/lib/util/http/dns.ts#L12

but it's disabled by default

https://github.com/renovatebot/renovate/blob/6d0aeee2b8243870738eeff4af4c6fa1b64b7808/lib/util/http/host-rules.ts#L109-L111

- https://github.com/renovatebot/renovate/pull/17574

**Comment by rarkins** [comment]
We only did this DNS optimization in case it was causing problems in the hosted app, but it seemed unrelated. I'm not sure if this hook in got allows us to fix any such problem
