### ISSUE TITLE
Find out why `modules/platform/github/index › getBranchPr(branchName) › aborts reopen if PR is too old` errors locally

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#21279]
### Describe the proposed change(s).

The Renovate maintainers get this error when running `yarn jest platform/github/index -t "aborts reopen"` against the `main` branch locally:

```
  ● modules/platform/github/index › getBranchPr(branchName) › aborts reopen if PR is too old

    Missing mocks!
     *   POST https://api.github.com/repos/some/repo/git/refs

      51 |   missingLog = [];
      52 |   if (missing.length && throwOnPending) {
    > 53 |     throw new Error(`Missing mocks!\n * ${missing.join('\n * ')}`);
         |           ^
      54 |   }
      55 |   if (!isDone && throwOnPending) {
      56 |     throw new Error(`Pending mocks!\n * ${pending.join('\n * ')}`);

      at clear (test/http-mock.ts:53:11)
      at Object.<anonymous> (test/http-mock.ts:120:3)
```

The tests also fail when you run Jest on the _whole file_. 

We should find out why this test/whole file test fails locally, but passes on our GitHub Actions runs.

**Comment by rarkins** [comment]
I deleted `.cache` locally just in case, but it had no effect - the test still fails.

**Comment by rarkins** [comment]
This appears to have disappeared..
