### ISSUE TITLE
Renovate running out of disk space leads to "Autoclosing Skipped" notes on PRs/issues

### ISSUE THREAD

**Issue by jamietanna** [renovatebot/renovate#21461]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.154.6

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

Placeholder value, please select the correct response from the dropdown

### Describe the bug

I've left :point_up: as-is, because it's not something I'm "trying".

When Renovate runs out of disk space when running, we see:

```
### Autoclosing Skipped

This PR has been flagged for autoclosing. However, it is being skipped due to the branch being already modified. Please close/delete it manually or report a bug if you think this is in error.
```

<img width="797" alt="Screenshot 2023-04-12 at 18 03 17" src="https://user-images.githubusercontent.com/3315059/231537813-0046a8c7-ae6e-432d-8ffc-b86258ab4dac.png">

This also appears as "dependency lookup errors" in the Dependency Dashboard.

Ideally, this would not report this - with this wording - or would report a more appropriate error message.

No reproduction as this is a hard issue to reproduce.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by jamietanna** [comment]
Various relevant logs:

```json
{
    "name": "renovate",
    "hostname": "f879b3d0b7a3",
    "pid": 18,
    "level": 40,
    "logContext": "JBP1upARp",
    "repository": "...",
    "hostType": "git",
    "err": {
        "task": {
            "commands": [
                "clone",
                "--filter=blob:none",
                "https://**redacted**@...",
                "."
            ],
            "format": "utf-8",
            "parser": "[function]"
        },
        "message": "Cloning into '.'...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nfatal: unable to checkout working tree\nwarning: Clone succeeded, but checkout failed.\nYou can inspect what was checked out with 'git status'\nand retry with 'git restore --source=HEAD :/'\n\n",\n        "stack": "Error: Cloning into '.'...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nerror: unable to write file ...\nfatal: unable to checkout working tree\nwarning: Clone succeeded, but checkout failed.\nYou can inspect what was checked out with 'git status'\nand retry with 'git restore --source=HEAD :/'\n\n\n    at Object.action (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:1274:25)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:1309:29)\n    at /usr/src/app/node_modules/simple-git/dist/cjs/index.js:1674:43\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:1672:16)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:1656:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:55:24)"\n    },
    "msg": "Host error",
    "time": "2023-04-19T00:04:28.785Z",
    "v": 0
}
{

    "name": "renovate",
    "hostname": "f879b3d0b7a3",
    "pid": 18,
    "level": 30,
    "logContext": "JBP1upARp",
    "repository": "....",
    "msg": "External host error causing abort - skipping",
    "time": "2023-04-19T00:04:28.785Z",
    "v": 0
}
{
    "name": "renovate",
    "hostname": "f879b3d0b7a3",
    "pid": 18,
    "level": 30,
    "logContext": "JBP1upARp",
    "repository": "....",
    "cloned": true,
    "durationMs": 3597,
    "msg": "Repository finished",
    "time": "2023-04-19T00:04:28.792Z",
    "v": 0
}
```

Also:

```json
{
    "name": "renovate",
    "hostname": "f879b3d0b7a3",
    "pid": 18,
    "level": 40,
    "logContext": "JBP1upARp",
    "repository": "...",
    "hostType": "git",
    "err": {
        "task": {
            "commands": [
                "clone",
                "--filter=blob:none",
                "https://**redacted**@github.com/...",
                "."
            ],
            "format": "utf-8",
            "parser": "[function]"
        },
        "message": "Cloning into '.'...\nfatal: sha1 file '/tmp/renovate/github/.../.git/objects/pack/tmp_idx_mwF80s' write error. Out of diskspace\nfatal: fetch-pack: invalid index-pack output\n",
        "stack": "Error: Cloning into '.'...\nfatal: sha1 file '/tmp/renovate/github/.../.git/objects/pack/tmp_idx_mwF80s' write error. Out of diskspace\nfatal: fetch-pack: invalid index-pack output\n\n    at Object.action (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:1274:25)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:1309:29)\n    at /usr/src/app/node_modules/simple-git/dist/cjs/index.js:1674:43\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:1672:16)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:1656:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    },
    "msg": "Host error",
    "time": "2023-04-19T00:06:59.527Z",
    "v": 0
}
```

```json
{
    "name": "renovate",
    "hostname": "f879b3d0b7a3",
    "pid": 18,
    "level": 50,
    "logContext": "JBP1upARp",
    "repository": "...",
    "currentDigest": "2a364900b59b",
    "currentValue": "v0.0.0-20200123153620-2a364900b59b",
    "datasource": "go",
    "depName": "...",
    "digestOneAndOnly": true,
    "followTag": null,
    "packageFile": "go.mod",
    "pinDigests": false,
    "rollbackPrs": false,
    "updatePinnedDependencies": true,
    "unconstrainedValue": false,
    "err": {
        "errno": -28,
        "code": "ENOSPC",
        "syscall": "write",
        "message": "ENOSPC: no space left on device, write",
        "stack": "Error: ENOSPC: no space left on device, write"
    },
    "msg": "lookupUpdates error",
    "time": "2023-04-19T00:08:59.645Z",
    "v": 0
}
```

```json
{
    "name": "renovate",
    "hostname": "f879b3d0b7a3",
    "pid": 18,
    "level": 40,
    "logContext": "JBP1upARp",
    "repository": "...",
    "err": {
        "message": "disk-space",
        "stack": "Error: disk-space\n    at syncGit (/usr/src/app/node_modules/renovate/dist/util/git/index.js:368:23)\n    at async Object.isBranchModified (/usr/src/app/node_modules/renovate/dist/util/git/index.js:546:5)\n    at async cleanUpBranches (/usr/src/app/node_modules/renovate/dist/workers/repository/finalise/prune.js:22:38)\n    at async pruneStaleBranches (/usr/src/app/node_modules/renovate/dist/workers/repository/finalise/prune.js:114:5)\n    at async finaliseRepo (/usr/src/app/node_modules/renovate/dist/workers/repository/finalise/index.js:17:5)\n    at async Object.renovateRepository (/usr/src/app/node_modules/renovate/dist/workers/repository/index.js:77:13)\n    at async q (/usr/src/app/src/server.js:1:44834)\n    at async startWorker (/usr/src/app/src/server.js:1:45949)"
    },
    "branch": "renovate/scala-2.13.x",
    "msg": "Error pruning branch",
    "time": "2023-04-19T00:11:37.730Z",
    "v": 0
}
```

**Comment by rarkins** [comment]
The logs above are still insufficient to determine what's going on. Can you put all the logs into a gist?

**Comment by jamietanna** [comment]
https://gist.github.com/jamietanna/57ef82572951dbe631a25be1aabc41e3 is a new set of logs - let me know if any more would be helpful, or if upping it to `DEBUG` is required
