### ISSUE TITLE
file-access-violation-error

### ISSUE THREAD

**Issue by akshaal** [renovatebot/renovate#21475]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.46.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

"35.42.0" version of renovate worked fine. "35.46.0" fails with "file-access-violation-error". Downgrading back to "35.42.0" mitigated the problem for now. No idea what the problem is or what is special about the repo it tries to handle and fails.

### Relevant debug logs

<details><summary>Logs</summary>

```
 Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "XXXX",
           "repository": "xxx/yyyy",
           "err": {
             "message": "file-access-violation-error",
             "stack": "Error: file-access-violation-error\n    at ensurePath (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/util/fs/util.ts:23:11)\n    at ensureLocalPath (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/util/fs/util.ts:35:10)\n    at readLocalFile (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/util/fs/index.ts:34:40)\n    at Object.extractAllPackageFiles (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/modules/manager/npm/extract/index.ts:518:40)\n    at extractAllPackageFiles (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/modules/manager/index.ts:50:17)\n    at getManagerPackageFiles (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:33:29)\n    at /opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/workers/repository/extract/index.ts:59:28\n    at async Promise.all (index 1)\n    at extractAllDependencies (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/workers/repository/extract/index.ts:56:26)\n    at extract (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/workers/repository/process/extract-update.ts:141:28)\n    at extractDependencies (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/workers/repository/process/index.ts:120:33)\n    at Object.renovateRepository (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/workers/repository/index.ts:61:9)\n    at attributes.repository (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/workers/global/index.ts:181:11)\n    at start (/opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/workers/global/index.ts:166:7)\n    at /opt/buildpack/tools/renovate/35.46.0/node_modules/renovate/lib/renovate.ts:18:22"
           },
           "msg": "Repository has unknown error"
         }
       ]
Error: The process '/usr/bin/docker' failed with exit code 1
Error: Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/actions-runner/_work/_actions/renovatebot/github-action/v36.0.2/dist/index.js:1702:25)
    at ExecState.CheckComplete (/actions-runner/_work/_actions/renovatebot/github-action/v36.0.2/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/actions-runner/_work/_actions/renovatebot/github-action/v36.0.2/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by viceice** [comment]
please check the debug logs. there should be a message indicating the invalid filename

**Comment by akshaal** [comment]
well, I guess this one? '@' ?
```
DEBUG: Preventing access to path with illegal characters (repository=abc/def, baseBranch=master)
       "path": "blahblah/whatever/some@email.address/package.json"
```

**Comment by viceice** [comment]
yes, will loosen the check
