### ISSUE TITLE
file-access-violation-error { }

### ISSUE THREAD

**Issue by mikstew** [renovatebot/renovate#21525]
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.47.1

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Hello!
We use [cookiecutter](https://github.com/cookiecutter/cookiecutter) in our monorepo to create an archetype template for our services and a recent update to renovate (v35.47.1) caused our runs to start failing due to the illegal characters of `{` and `}` in filenames. 

I saw that validation of the filename path was recently added in [this commit](https://github.com/renovatebot/renovate/commit/2de1b29c1fa0b9f1bcd6bfc3913e66cdaae76f76). 

I also noticed two similar issues come up in the last day:
* https://github.com/renovatebot/renovate/issues/21475
* https://github.com/renovatebot/renovate/issues/21481

Would it be possible to relax the restriction on `{` and `}` as well?

Thank you!

### Relevant debug logs

<details><summary>Logs</summary>

```
{
  "name": "renovate",
  "hostname": "runner-12345",
  "pid": 18,
  "level": 20,
  "logContext": "0vt2Y17fmaTCHoQLeFySc",
  "repository": "Repo/engineering/code",
  "path": "tools/archetypes/python-fastapi-archetype/{{cookiecutter.service_name}}/chart/values.yaml",
  "msg": "Preventing access to path with illegal characters",
  "time": "2023-04-14T12:01:50.194Z",
  "v": 0
}
{
  "name": "renovate",
  "hostname": "runner-12345",
  "pid": 18,
  "level": 50,
  "logContext": "0vt2Y17fmaTCHoQLeFySc",
  "repository": "Repo/engineering/code",
  "err": {
    "message": "file-access-violation-error",
    "stack": "Error: file-access-violation-error
      at ensurePath (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/util/fs/util.ts:23:11)
      at ensureLocalPath (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/util/fs/util.ts:35:10)
      at readLocalFile (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/util/fs/index.ts:34:40)
      at getManagerPackageFiles (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:42:40)
      at /opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/workers/repository/extract/index.ts:59:28
      at async Promise.all (index 6)
      at extractAllDependencies (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/workers/repository/extract/index.ts:56:26)
      at extract (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/workers/repository/process/extract-update.ts:141:28)
      at extractDependencies (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/workers/repository/process/index.ts:140:26)
      at Object.renovateRepository (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/workers/repository/index.ts:61:9)
      at attributes.repository (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/workers/global/index.ts:181:11)
      at start (/opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/workers/global/index.ts:166:7)
      at /opt/buildpack/tools/renovate/35.47.1/node_modules/renovate/lib/renovate.ts:18:22"
  },
  "msg": "Repository has unknown error",
  "time": "2023-04-14T12:01:50.215Z",
  "v": 0
}

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above

**Comment by viceice** [comment]
please provide the debug message with the corresponding filename

**Comment by mikstew** [comment]
The filename is `tools/archetypes/python-fastapi-archetype/{{cookiecutter.service_name}}/chart/values.yaml`.

**Comment by viceice** [comment]
ok, is that a real file inside the repo?

**Comment by mikstew** [comment]
Yes, it is a real file in the repo. It's part of our service template, which is maintained in the same repo. I would exclude the path from renovate, except there is a pyproject.toml file within that template that we rely on renovate keeping up to date with the latest versions.

**Comment by mikstew** [comment]
Thank you.
