### ISSUE TITLE
Terraform manager wrongly extracts oci charts

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#21971]
### How are you running Renovate?

Placeholder value, please select the correct response from the dropdown

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

Placeholder value, please select the correct response from the dropdown

### Describe the bug

Registry and repository are wrongly extracted, so renovate add the `v2/` path to wrong place.

```json
     {
        "deps": [
          {
            "currentValue": "8.9.1",
            "depType": "helm_release",
            "depName": "kube-prometheus",
            "datasource": "docker",
            "registryUrls": [
              "https://registry-1.docker.io/bitnamicharts"
            ],
            "updates": [],
            "packageName": "kube-prometheus",
            "warnings": [],
            "versioning": "docker",
            "registryUrl": "https://registry-1.docker.io/bitnamicharts",
            "currentVersion": "8.9.1",
            "fixedVersion": "8.9.1"
          }
        ],
        "packageFile": "terra/modules/devel/modules/core/prometheus.tf"
      },
```

No need for reproduction, can be reproduced with test case

```hcl
resource "helm_release" "prometheus" {
  name       = "kube-prometheus"
  repository = "oci://registry-1.docker.io/bitnamicharts"
  chart      = "kube-prometheus"
  version    = "8.9.1"
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: getLabels(https://registry-1.docker.io/bitnamicharts, kube-prometheus, 8.9.1)
DEBUG: getManifestResponse(https://registry-1.docker.io/bitnamicharts, kube-prometheus, 8.9.1, get)
...
DEBUG: Page Not Found https://registry-1.docker.io/bitnamicharts/v2/
DEBUG: Unknown Error looking up docker manifest
{
  "err": {
    "message": "page-not-found",
    "stack": "Error: page-not-found\n    at getAuthHeaders (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/common.js:47:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DockerDatasource.getManifestResponse (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:53:29)\n    at async DockerDatasource.getConfigDigest (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:124:34)\n    at async DockerDatasource.getLabels (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:226:34)\n    at async /home/ubuntu/renovateapp/node_modules/renovate/dist/util/cache/package/decorator.js:69:24\n    at async DockerDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:527:24)\n    at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n    at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:246:23)"
  },
  "registryHost": "https://registry-1.docker.io/bitnamicharts",
  "dockerRepository": "kube-prometheus",
  "tag": "8.9.1"
}
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by viceice** [comment]
OK, maybe it's just an issue on the datasource

```
DEBUG: Page Not Found https://registry-1.docker.io/bitnamicharts/v2/
DEBUG: Unknown Error looking up docker manifest
{
  "err": {
    "message": "page-not-found",
    "stack": "Error: page-not-found\n    at getAuthHeaders (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/common.js:47:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DockerDatasource.getManifestResponse (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:53:29)\n    at async DockerDatasource.getConfigDigest (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:124:34)\n    at async DockerDatasource.getLabels (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:226:34)\n    at async /home/ubuntu/renovateapp/node_modules/renovate/dist/util/cache/package/decorator.js:69:24\n    at async DockerDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/docker/index.js:527:24)\n    at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n    at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:246:23)"
  },
  "registryHost": "https://registry-1.docker.io/bitnamicharts",
  "dockerRepository": "kube-prometheus",
  "tag": "8.9.1"
}
```

it tries to fetch the labels, but something get's wrong there, so the registryurl is passed as is, instead of removing the path
