### ISSUE TITLE
WARN: Unable to read vulnerability information

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#22502]
### Describe the proposed change(s).

Error found in https://github.com/renovate-reproductions/22487

This seems to only occur in the hosted app, and not when I dry run the same repo locally.

Something/somehow seems incompatible.

### Describe why we need/want these change(s).

```
WARN: Unable to read vulnerability information
{
  "err": {
    "stack": "Error: 
    at OsvOffline.initialize (/opt/buildpack/tools/renovate/35.102.10/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:16:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.create (/opt/buildpack/tools/renovate/35.102.10/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:26:9)
    at Vulnerabilities.initialize (/opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:50:23)
    at Function.create (/opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:55:5)
    at fetchVulnerabilities (/opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/workers/repository/process/extract-update.ts:176:31)
    at lookup (/opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/workers/repository/process/extract-update.ts:191:3)
    at extractDependencies (/opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/workers/repository/process/index.ts:146:11)
    at Object.renovateRepository (/opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/workers/repository/index.ts:61:9)
    at attributes.repository (/opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/workers/global/index.ts:184:11)
    at start (/opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/workers/global/index.ts:169:7)
    at /opt/buildpack/tools/renovate/35.102.10/node_modules/renovate/lib/renovate.ts:18:22"
  }
}
```

**Comment by Gabriel-Ladzaretti** [comment]
seems error comes from `tryDownloadDb()`
https://github.com/renovatebot/osv-offline/blob/ac86db680fbbab26b87c33b6a45effa042b639bf/packages/osv-offline/src/lib/osv-offline.ts#L13-L19

**Comment by rarkins** [comment]
@JamieMagee @viceice @secustor any thoughts on this?

We could either:
- Add logging to the offline csv package, or
- Return information in an error which can then be logged by Renovate?

**Comment by viceice** [comment]
it probably tries to download inside the package folder which is only allowed by root?

**Comment by rarkins** [comment]
Yeah, I'm guessing it's folder permissions too

**Comment by JamieMagee** [comment]
Why not both. I opened https://github.com/renovatebot/osv-offline/issues/364

**Comment by rarkins** [comment]
> Why not both.

Isn't it undesirable for libraries to do their own logging unless "asked"? Otherwise it makes it hard for apps or CLIs to control their output

**Comment by JamieMagee** [comment]
True. I had considered `@renovatebot/osv-offline` to be an internal library, but it would still be hard to pass logging settings from one to the other. I'll update the issue to make `throw`s more useful.

**Comment by JamieMagee** [comment]
https://github.com/renovatebot/osv-offline/issues/364 is complete, and updated in renovate in https://github.com/renovatebot/renovate/pull/22885. @rarkins are you seeing any more useful logs?

**Comment by rarkins** [comment]
@JamieMagee it's an API rate limit error:

```
      "url": "https://api.github.com/repos/renovatebot/osv-offline/releases",

      "data": {
        "message": "API rate limit exceeded for 34.239.12.110. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
        "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
      }
```

You might be able to see https://developer.mend.io/github/renovate-reproductions/22487/-/job/0188fff1-c0fc-7b19-a03a-184c6132684c

Prior to that there's a log for:

```
DEBUG: Adding token authentication for api.github.com to hostRules
```

**Comment by rarkins** [comment]
Oh, I guess the OSV library doesn't use hostRules :)

**Comment by JamieMagee** [comment]
I think it supports a `GITHUB_TOKEN` environment variable

**Comment by rarkins** [comment]
Can we enhance it to take the token as a variable? I'm not sure we want to expose the token in env in all cases

**Comment by karfau** [comment]
For me the GitHub App is running into this issue on a new repository which causes it to fail:
did I miss some config option?
A missing token in that situation is not something that I would have expected, since I'm not configuring the action...
```
ERROR: Repository has unknown error
{
  "err": {
    "name": "HttpError",
    "status": 403,
    "response": {
      "url": "https://api.github.com/repos/renovatebot/osv-offline/releases",
      "status": 403,
      "headers": {
        "access-control-allow-origin": "*",
        "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
        "connection": "close",
        "content-length": "279",
        "content-security-policy": "default-src 'none'; style-src 'unsafe-inline'",
        "content-type": "application/json; charset=utf-8",
        "date": "Wed, 27 Sep 2023 16:46:41 GMT",
        "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
        "server": "Varnish",
        "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
        "x-content-type-options": "nosniff",
        "x-frame-options": "deny",
        "x-github-media-type": "github.v3; format=json",
        "x-github-request-id": "0A73:3E74:134F61:274DE5:65145C71",
        "x-ratelimit-limit": "60",
        "x-ratelimit-remaining": "0",
        "x-ratelimit-reset": "1695835586",
        "x-ratelimit-resource": "core",
        "x-ratelimit-used": "60",
        "x-xss-protection": "1; mode=block"
      },
      "data": {
        "message": "API rate limit exceeded for 34.239.12.110. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
        "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
      }
    },
    "request": {
      "method": "GET",
      "url": "https://api.github.com/repos/renovatebot/osv-offline/releases",
      "headers": {
        "accept": "application/vnd.github.v3+json",
        "user-agent": "octokit-rest.js/19.0.13 octokit-core.js/4.2.4 Node.js/18.18.0 (linux; x64)"
      },
      "request": {
        "fetch": "[function]",
        "hook": "[function]"
      }
    },
    "message": "API rate limit exceeded for 34.239.12.110. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "stack": "HttpError: API rate limit exceeded for 34.239.12.110. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\n    at /opt/containerbase/tools/renovate/36.107.2/node_modules/@octokit/request/dist-node/index.js:122:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at tryDownloadDb (/opt/containerbase/tools/renovate/36.107.2/node_modules/@renovatebot/osv-offline/dist/lib/download.js:43:26)\n    at OsvOffline.initialize (/opt/containerbase/tools/renovate/36.107.2/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:14:24)\n    at Function.create (/opt/containerbase/tools/renovate/36.107.2/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:26:9)\n    at Vulnerabilities.initialize (/opt/containerbase/tools/renovate/36.107.2/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:49:23)\n    at Function.create (/opt/containerbase/tools/renovate/36.107.2/node_modules/renovate/lib/workers/repository/process/vulnerabilities.ts:54:5)\n    at getDashboardMarkdownVulnerabilities (/opt/containerbase/tools/renovate/36.107.2/node_modules/renovate/lib/workers/repository/dependency-dashboard.ts:488:32)\n    at ensureDependencyDashboard (/opt/containerbase/tools/renovate/36.107.2/node_modules/renovate/lib/workers/repository/dependency-dashboard.ts:413:16)\n    at Object.renovateRepository (/opt/containerbase/tools/renovate/36.107.2/node_modules/renovate/lib/workers/repository/index.ts:92:9)\n    at attributes.repository (/opt/containerbase/tools/renovate/36.107.2/node_modules/renovate/lib/workers/global/index.ts:184:11)\n    at start (/opt/containerbase/tools/renovate/36.107.2/node_modules/renovate/lib/workers/global/index.ts:169:7)\n    at /opt/containerbase/tools/renovate/36.107.2/node_modules/renovate/lib/renovate.ts:18:22"
  }
}
```

**Comment by pdonorio** [comment]
Getting this in my renovate runs, both in github cloud or self hosted.

```
WARN: Unable to read vulnerability information (repository=tradeparadigm/mono)
       "err": {
         "name": "HttpError",
         "status": 401,
         "response": {
           "url": "https://api.github.com/repos/renovatebot/osv-offline/releases",
           "status": 401,
```

Anything I could do to debug more?

**Comment by taraspos** [comment]
I'm seeing similar error when running as Github Action, with provided github token:

```
2024-02-13T10:34:27.4695770Z  WARN: Unable to read vulnerability information (repository=xxx)
2024-02-13T10:34:27.4696610Z        "err": {
2024-02-13T10:34:27.4697063Z          "name": "HttpError",
2024-02-13T10:34:27.4697569Z          "status": 401,
2024-02-13T10:34:27.4698045Z          "response": {
2024-02-13T10:34:27.4698832Z            "url": "https://api.github.com/repos/renovatebot/osv-offline/releases",
2024-02-13T10:34:27.4699650Z            "status": 401,
2024-02-13T10:34:27.4700132Z            "headers": {
2024-02-13T10:34:27.4700722Z              "access-control-allow-origin": "*",
2024-02-13T10:34:27.4703473Z              "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
2024-02-13T10:34:27.4705918Z              "connection": "close",
2024-02-13T10:34:27.4706526Z              "content-length": "80",
2024-02-13T10:34:27.4707263Z              "content-security-policy": "default-src 'none'",
2024-02-13T10:34:27.4708129Z              "content-type": "application/json; charset=utf-8",
2024-02-13T10:34:27.4708972Z              "date": "Tue, 13 Feb 2024 10:34:20 GMT",
2024-02-13T10:34:27.4710003Z              "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
2024-02-13T10:34:27.4710921Z              "server": "GitHub.com",
2024-02-13T10:34:27.4711856Z              "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
2024-02-13T10:34:27.4712907Z              "vary": "Accept-Encoding, Accept, X-Requested-With",
2024-02-13T10:34:27.4713742Z              "x-content-type-options": "nosniff",
2024-02-13T10:34:27.4714440Z              "x-frame-options": "deny",
2024-02-13T10:34:27.4715184Z              "x-github-media-type": "github.v3; format=json",
2024-02-13T10:34:27.4716914Z              "x-ratelimit-limit": "60",
2024-02-13T10:34:27.4717594Z              "x-ratelimit-remaining": "59",
2024-02-13T10:34:27.4718293Z              "x-ratelimit-reset": "1707824060",
2024-02-13T10:34:27.4718988Z              "x-ratelimit-resource": "core",
2024-02-13T10:34:27.4719648Z              "x-ratelimit-used": "1",
2024-02-13T10:34:27.4720344Z              "x-xss-protection": "0"
2024-02-13T10:34:27.4720923Z            },
2024-02-13T10:34:27.4721333Z            "data": {
2024-02-13T10:34:27.4721830Z              "message": "Bad credentials",
2024-02-13T10:34:27.4722600Z              "documentation_url": "https://docs.github.com/rest"
2024-02-13T10:34:27.4723292Z            }
2024-02-13T10:34:27.4723759Z          },
2024-02-13T10:34:27.4724169Z          "request": {
2024-02-13T10:34:27.4724650Z            "method": "GET",
2024-02-13T10:34:27.4725453Z            "url": "https://api.github.com/repos/renovatebot/osv-offline/releases",
2024-02-13T10:34:27.4726267Z            "headers": {
2024-02-13T10:34:27.4726852Z              "accept": "application/vnd.github.v3+json",
2024-02-13T10:34:27.4727969Z              "user-agent": "octokit-rest.js/20.0.2 octokit-core.js/5.0.2 Node.js/18.19.0 (linux; x64)",
2024-02-13T10:34:27.4728924Z              "authorization": "***********"
2024-02-13T10:34:27.4729478Z            },
2024-02-13T10:34:27.4730030Z            "request": {"fetch": "[function]", "hook": "[function]"}
2024-02-13T10:34:27.4730705Z          },
2024-02-13T10:34:27.4731153Z          "message": "Bad credentials",
2024-02-13T10:34:27.4743505Z          "stack": "HttpError: Bad credentials\n    at /usr/local/renovate/node_modules/.pnpm/@octokit+request@8.1.6/node_modules/@octokit/request/dist-node/index.js:124:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at tryDownloadDb (/usr/local/renovate/node_modules/.pnpm/@renovatebot+osv-offline@1.5.1/node_modules/@renovatebot/osv-offline/dist/lib/download.js:46:26)\n    at OsvOffline.initialize (/usr/local/renovate/node_modules/.pnpm/@renovatebot+osv-offline@1.5.1/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:14:24)\n    at Function.create (/usr/local/renovate/node_modules/.pnpm/@renovatebot+osv-offline@1.5.1/node_modules/@renovatebot/osv-offline/dist/lib/osv-offline.js:26:9)\n    at Vulnerabilities.initialize (/usr/local/renovate/lib/workers/repository/process/vulnerabilities.ts:56:23)\n    at Function.create (/usr/local/renovate/lib/workers/repository/process/vulnerabilities.ts:61:5)\n    at fetchVulnerabilities (/usr/local/renovate/lib/workers/repository/process/extract-update.ts:177:31)\n    at lookup (/usr/local/renovate/lib/workers/repository/process/extract-update.ts:192:3)\n    at extractDependencies (/usr/local/renovate/lib/workers/repository/process/index.ts:161:11)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:62:9)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:197:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:182:7)\n    at /usr/local/renovate/lib/renovate.ts:18:22"
2024-02-13T10:34:27.4754947Z        }
```

**Comment by MPV** [comment]
Has this been resolved now? As of:
- https://github.com/renovatebot/renovate/discussions/26991
