### ISSUE TITLE
failed to parse `2023.05.20` as pep440

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#23638]
### Discussed in https://github.com/renovatebot/renovate/discussions/23634

<div type='discussions-op-text'>

<sup>Originally posted by **trim21** July 31, 2023</sup>
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

https://github.com/trim21-archive/renovate-bot-bug-pep440/issues/3

failed to handle poetry config:

```
[tool.poetry.group.docs.dependencies]
sphinx = { version = "^7.0.0", python = "^3.9" }
furo = { version = "2023.05.20", python = "^3.9" }
```

### Relevant debug logs

<details><summary>Logs</summary>

```text
WARN: Unexpected range error
{
  "currentValue": "2023.05.20"
  "err": {
    "message": "Invalid pep440 currentValue",
    "stack": "TypeError: Invalid pep440 currentValue\n    at parseCurrentRange (/opt/containerbase/tools/renovate/36.24.2/node_modules/renovate/lib/modules/versioning/pep440/range.ts:240:11)\n    at Object.getNewValue (/opt/containerbase/tools/renovate/36.24.2/node_modules/renovate/lib/modules/versioning/pep440/range.ts:117:14)\n    at generateUpdate (/opt/containerbase/tools/renovate/36.24.2/node_modules/renovate/lib/workers/repository/process/lookup/generate.ts:55:36)\n    at lookupUpdates (/opt/containerbase/tools/renovate/36.24.2/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:295:44)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at withLookupStats (/opt/containerbase/tools/renovate/36.24.2/node_modules/renovate/lib/workers/repository/process/fetch.ts:29:18)\n    at fetchDepUpdates (/opt/containerbase/tools/renovate/36.24.2/node_modules/renovate/lib/workers/repository/process/fetch.ts:74:30)\n    at /opt/containerbase/tools/renovate/36.24.2/node_modules/p-map/index.js:57:22"
  }
}

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above</div>

**Comment by trim21** [comment]
actually renovate can parse `2023.05.20` as pep440, but it failed for some unknown reason in this repo.

**Comment by XF-FW** [comment]
I just want to note that `2023.05.20` is not a PEP440 compliant version number. The leading zero is not contemplated in the spec.

**Comment by trim21** [comment]
> I just want to note that `2023.05.20` is not a PEP440 compliant version number. The leading zero is not contemplated in the spec.

make sense

**Comment by trim21** [comment]
this issue should be closed I think，this version is indeed not a valid pep440 version
