### ISSUE TITLE
Lockfile maintenance PR closed unexpectedly

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#2474]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The Neutrino & Treeherder repositories both use the Renovate `:maintainLockFilesWeekly` preset. 

Twice the PR opened by Renovate was closed by Renovate before we had a chance to merge it:
https://github.com/neutrinojs/neutrino/pull/1070
https://github.com/mozilla/treeherder/pull/3959

It appears that if the `yarn` invocation during the maintenance process fails (see error message below), it's treated as "the lockfile doesn't need updating, let's delete any open branches".

**To Reproduce**

1.  Use weekly lockfile refresh on a repo
2.  When a lockfile refresh PR is opened, leave it open
3.  Wait for transient yarn connectivity/registry issue to occur during one of the times when Renovate is refreshing the lockfile PR

**Expected behavior**
If a transient yarn failure occurs, then either:
* no changes are made to the existing PR and Renovate just tries again later
* a comment is left on the PR saying there was an issue, and Renovate tries again later

**Additional context**

Renovate log from when neutrinojs/neutrino#1070 was closed:
https://renovatebot.com/dashboard#neutrinojs/neutrino/18690405

```
DEBUG:
{
  "cmd": "npm i -g -C ~/.npm/lerna@^2.11.0 lerna@^2.11.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@^2.11.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879"
}
INFO: lock file error
{
  "cmd": "npm i -g -C ~/.npm/lerna@^2.11.0 lerna@^2.11.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@^2.11.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
  "err": {
    "name": "ChildProcessError",
    "code": 1,
    "childProcess": {},
    "stdout": "/home/node/.npm/lerna@^2.11.0/bin/lerna -> /home/node/.npm/lerna@^2.11.0/lib/node_modules/lerna/bin/lerna.js\n+ lerna@2.11.0\nadded 330 packages from 181 contributors in 32.643s\nyarn install v1.9.4\ninfo No lockfile found.\n[1/4] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n",
    "stderr": "warning jest > jest-cli > istanbul-api > istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump\nwarning stylelint > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nwarning workspace-aggregator-85b5fa3a-54cb-4540-b869-8f8a9e6d3906 > @neutrinojs/vue > stylelint-processor-html@1.0.0: Please use stylelint-processor-arbitrary-tags https://github.com/mapbox/stylelint-processor-arbitrary-tags \nwarning workspace-aggregator-85b5fa3a-54cb-4540-b869-8f8a9e6d3906 > @neutrinojs/image-minify > imagemin-gifsicle > gifsicle > bin-wrapper > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5\nerror Received malformed response from registry for undefined. The registry may be down.\nError: Received malformed response from registry for undefined. The registry may be down.\n    at MessageError.ExtendableBuiltin (/usr/src/node_modules/yarn/lib/cli.js:243:66)\n    at new MessageError (/usr/src/node_modules/yarn/lib/cli.js:272:123)\n    at Function. (/usr/src/node_modules/yarn/lib/cli.js:51226:15)\n    at Generator.next ()\n    at step (/usr/src/node_modules/yarn/lib/cli.js:92:30)\n    at /usr/src/node_modules/yarn/lib/cli.js:110:14\n    at new Promise ()\n    at new F (/usr/src/node_modules/yarn/lib/cli.js:23624:28)\n    at Function. (/usr/src/node_modules/yarn/lib/cli.js:89:12)\n    at Function.findVersionInRegistryResponse (/usr/src/node_modules/yarn/lib/cli.js:51268:19)\n"
  },
  "type": "lerna",
  "lernaClient": "yarn"
}
DEBUG: No updated lock files in branch
DEBUG: PR has no releaseTimestamp
DEBUG: No files to commit
INFO: Deleting lock file maintenance branch as master lock file no longer needs updating
DEBUG: DELETE repos/neutrinojs/neutrino/git/refs/heads/renovate/lock-file-maintenance [retries=5]
```

**Comment by edmorley** [comment]
It seems that perhaps the `else` case here (when there is no `config.releaseTimestamp`):
https://github.com/renovatebot/renovate/blob/df8bebe10d62cdfd11280f596b9fe53b851da07b/lib/workers/branch/index.js#L177

...should also `throw new Error('lockfile-error')` ?

**Comment by rarkins** [comment]
I think best if this case throws the error so that it retries the next time.

**Comment by edmorley** [comment]
Many thanks :-)
