### ISSUE TITLE
buf.build Go dependencies result in lookupUpdates error

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25033]
### Describe the proposed change(s).

Context: #24639

Example log:

```
DEBUG: Go module: buf.build/gen/go/prometheus/prometheus/protocolbuffers/go lookup import url https://buf.build/gen/go (repository=sylvainOL/renovate-buf-build)
DEBUG: Go module: buf.build/gen/go/prometheus/prometheus/protocolbuffers/go lookup import url https://buf.build/gen/go (repository=sylvainOL/renovate-buf-build)
ERROR: lookupUpdates error (repository=sylvainOL/renovate-buf-build, packageFile=go.mod)
       "currentDigest": "41588ce133c8",
       "currentValue": "v1.31.0-20230726221845-41588ce133c8.1",
       "datasource": "go",
       "packageName": "buf.build/gen/go/prometheus/prometheus/protocolbuffers/go",
       "digestOneAndOnly": true,
       "followTag": null,
       "lockedVersion": undefined,
       "pinDigests": false,
       "rollbackPrs": false,
       "isVulnerabilityAlert": undefined,
       "updatePinnedDependencies": true,
       "unconstrainedValue": false,
       "err": {
         "task": {
           "commands": ["ls-remote", "https://buf.build/gen/go"],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: not found\nfatal: repository 'https://buf.build/gen/go/' not found\n",
         "stack": "Error: remote: not found\nfatal: repository 'https://**redacted**@3.20.0/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/home/rhys/src/github/renovatebot/renovate/node_modules/.pnpm/simple-git@3.20.0/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /home/rhys/src/github/renovatebot/renovate/node_modules/.pnpm/simple-git@3.20.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/rhys/src/github/renovatebot/renovate/node_modules/.pnpm/simple-git@3.20.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/home/rhys/src/github/renovatebot/renovate/node_modules/.pnpm/simple-git@3.20.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/rhys/src/github/renovatebot/renovate/node_modules/.pnpm/simple-git@3.20.0/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
```

It looks like we need to avoid delegating any lookup to git-refs

**Comment by rarkins** [comment]
Reproduction forked to https://github.com/renovate-reproductions/25033

**Comment by zharinov** [comment]
Am I correct that there is basically only one package and hance we can hardcode sourseURL for it?

**Comment by zharinov** [comment]
Feel free to reopen, if any new problem arises
