### ISSUE TITLE
GHE graphql error

### ISSUE THREAD

**Issue by dylang** [renovatebot/renovate#2516]
**What Renovate type are you using?**

`"renovate": "13.64.12"`

**Describe the bug**

Error with Github Enterprise:

````
 INFO: Retrying graphql query (repository=Alchemy/alchemy)
 INFO: Error retrieving vulnerability alerts (repository=Alchemy/alchemy)
       "err": {
         "message": "Cannot read property 'repository' of null",
         "stack": "TypeError: Cannot read property 'repository' of null\n    at Object.getVulnerabilityAlerts (/home/jenkins/workspace/78f00166/workspace/renovate_PR-55-SZNPO5JOQPM7KB5ESNJTZJDGDAGGXSKGQFF7MFHHTOQYWILBJRCA/node_modules/renovate/lib/platform/github/index.js:1298:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Processing 12 branches (repository=Alchemy/alchemy)
       "branchList": [
         "renovate/babel-loader-8.x",
         "renovate/babel-plugin-styled-components-1.x",
         "renovate/commitlint-monorepo",
         "renovate/eslint-plugin-jsx-a11y-6.x",
         "renovate/is-ci-1.x",
         "renovate/jest-monorepo",
         "renovate/jest-styled-components-6.x",
         "renovate/lerna-3.x",
         "renovate/lock-file-maintenance",
         "renovate/react-monorepo",
         "renovate/styled-components-3.x",
         "renovate/yargs-12.x"
       ]
 INFO: Retrying graphql query (repository=Alchemy/alchemy, dependencies=@commitlint/cli,@commitlint/config-conventional, branch=renovate/commitlint-monorepo)
 WARN: No graphql res.data (repository=Alchemy/alchemy, dependencies=@commitlint/cli,@commitlint/config-conventional, branch=renovate/commitlint-monorepo)
       "query": "\n      query {\n        repository(owner: \"Alchemy\", name: \"alchemy\") {\n          pullRequests(states: [OPEN], first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {\n            nodes {\n              number\n              headRefName\n              title\n              mergeable\n              mergeStateStatus\n              commits(first: 2) {\n                nodes {\n                  commit {\n                    author {\n                      email\n                    }\n                    committer {\n                      email\n                    }\n                    parents(last: 1) {\n                      edges {\n                        node {\n                          abbreviatedOid\n                          oid\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n              body\n            }\n          }\n        }\n      }\n      ",
       "res": {
         "data": null,
         "errors": [
           {
             "message": "Field 'mergeStateStatus' doesn't exist on type 'PullRequest'",
             "locations": [{"line": 10, "column": 15}]
           }
         ]
       }
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

We're not using the latest Github Enterprise, but it's close and it has GraphQL support.
https://developer.github.com/enterprise/2.13/v4/

**Comment by dylang** [comment]
I agree with both.

**Comment by rarkins** [comment]
FYI, I have added a check to skip the two types of graphql queries altogether on GHE, because of its lack of support for the preview headers necessary.
