### ISSUE TITLE
Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#2618]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
An error has occurred:

```
ERROR: Repository has unknown error
{
  "err": {
    "message": "Cannot read property 'endsWith' of undefined",
    "stack": "TypeError: Cannot read property 'endsWith' of undefined\n    at branches.filter.branch (/usr/src/node_modules/renovate/lib/workers/repository/master-issue.js:69:16)\n    at Array.filter ()\n    at ensureMasterIssue (/usr/src/node_modules/renovate/lib/workers/repository/master-issue.js:68:32)\n    at Object.renovateRepository (/usr/src/node_modules/renovate/lib/workers/repository/index.js:38:11)\n    at \n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"
  }
}
```

**Did you see anything helpful in debug logs?**
https://renovatebot.com/dashboard#Jamesking56/Jamesking56.uk/23235312

**To Reproduce**
No idea! I have no idea how this has happened, I've only just linked this to this repo today.

**Expected behavior**
I'm assuming its supposed to make a PR for `gulp-copy`

**Additional context**
Only just linked to my public repo, I've only done the initial configuration PR:  https://github.com/Jamesking56/Jamesking56.uk/pull/16

**Comment by Jamesking56** [comment]
Nice :+1:
