### ISSUE TITLE
Detecting from reference via index in COPY cmd as image in multistage Dockerfile

### ISSUE THREAD

**Issue by phaldan** [renovatebot/renovate#2697]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
My setup includes a Dockerfile with a multistage build, but I don't use an alias for my first build and when transfering files within the multistage build via copy-from cmd from the first to the final build, I reference my first build via index number.
Using the copy-from with an index reference is a valid alternative to a reference by alias name. Copy-from syntax (source: [Docker Docs](https://docs.docker.com/engine/reference/builder/#from)):
```
COPY --from=<name|index>
```

As sees in the log entries below the `0` in the `COPY --from=0` cmd is detected as docker image. Renovate doesn't detect the `0` image as a unsupported dependency (`DEBUG: getDigest(undefined, 0, undefined)`) and tries to pull a token from Docker Hub via `library/0` image. Docker Hub responses for this image with an HTTP 401 error code.

**Did you see anything helpful in debug logs?**
```
...
DEBUG: Matched 1 file(s) for manager dockerfile: Dockerfile
DEBUG: FROM line
{
  "lineNumber": 0,
  "fromLine": "FROM alpine:3.8@sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528"
}
DEBUG: Dockerfile FROM
{
  "depName": "alpine",
  "currentTag": "3.8",
  "currentDigest": "sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528"
}
DEBUG: FROM line
{
  "lineNumber": 9,
  "fromLine": "FROM openjdk:8u171-jre-alpine3.8@sha256:e3168174d367db9928bb70e33b4750457092e61815d577e368f53efb29fea48b"
}
DEBUG: Dockerfile FROM
{
  "depName": "openjdk",
  "currentTag": "8u171-jre-alpine3.8",
  "currentDigest": "sha256:e3168174d367db9928bb70e33b4750457092e61815d577e368f53efb29fea48b"
}
DEBUG: COPY --from line
{
  "lineNumber": 14,
  "fromLine": "COPY --from=0 /JTS3ServerMod ."
}
INFO: Dockerfile COPY --from
{
  "depName": "0"
}
...
DEBUG: getDigest(undefined, 0, undefined)
...
DEBUG: Obtaining docker registry token for library/0 using url https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/0:pull
INFO: Unauthorized docker lookup
{
  "dockerRepository": "library/0"
}
DEBUG: Response code 401 (Unauthorized)
{
  "err": {
    "name": "HTTPError",
    "host": "index.docker.io",
    "hostname": "index.docker.io",
    "method": "GET",
    "path": "/v2/library/0/manifests/latest",
    "protocol": "https:",
    "url": "https://index.docker.io/v2/library/0/manifests/latest",
    "statusCode": 401,
    "statusMessage": "Unauthorized",
    "headers": {
      "content-type": "application/json; charset=utf-8",
      "docker-distribution-api-version": "registry/2.0",
      "www-authenticate": "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/0:pull\",error=\"insufficient_scope\"",
      "date": "Wed, 24 Oct 2018 22:41:04 GMT",
      "content-length": "152",
      "connection": "close",
      "strict-transport-security": "max-age=31536000"
    },
    "body": "{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":[{\"Type\":\"repository\",\"Class\":\"\",\"Name\":\"library/0\",\"Action\":\"pull\"}]}]}\n",
    "message": "Response code 401 (Unauthorized)",
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at stream.catch.then.data (/usr/src/node_modules/renovate/node_modules/got/index.js:386:13)\n    at \n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"
  }
}
INFO: Could not getDigest
{
  "purl": "pkg:docker/0"
}
```

**To Reproduce**

1.  Create repository with a Dockfile as multistage build. For example:
```Dockerfile
FROM alpine:3.8@sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
# Do something

FROM openjdk:8u171-jre-alpine3.8@sha256:e3168174d367db9928bb70e33b4750457092e61815d577e368f53efb29fea48b

COPY --from=0 /etc .
```
2.  Configure renovate like this:
```json
{
  "extends": [
    "config:base"
  ],
  "enabledManagers": [
    "dockerfile"
  ],
  "pinDigests": true
}
```

**Expected behavior**
The index reference in the copy-from cmd should be ignored like the reference via alias name.

**Additional context**
Job: phaldan/docker-JTS3ServerMod: #25866600

**Comment by rarkins** [comment]
Thank you for the detailed log. It sounds like we can check if the `from=` source is a number and if so then simply skip over it gracefully?

**Comment by phaldan** [comment]
Detecting the number in the `from=` and skipping it from further processing sound like a viable solution.
