### ISSUE TITLE
hostRules.headers cannot be configured in config.js

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#26983]
### Describe the proposed change(s).

Example failure:

```
DEBUG: File config
       "config": {
         "allowedHeaders": ["abc"],
         "hostRules": [{"headers": {"abc": "def"}}]
       }
...
DEBUG: Setting global hostRules
DEBUG: Using default github endpoint: https://api.github.com/
DEBUG: hostRules: authentication already set for api.github.com
ERROR: Disallowed hostRules headers
       "allowedHeaders": undefined,
       "header": "abc"
```

Meanwhile it does work if the same hostRules is in renovate.json instead of config.js

**Comment by lmarschall** [comment]
Any updates here, I'm running in the same issue in my config at the moment.

**Comment by RahulGautamSingh** [comment]
I think this happens because `allowedHeaders` hasn't been set to `GlobalConfig.config` object yet, when we try to make requests to fetch the repos.

And we are trying to access `GlobalConfig.allowedHeaders` in here:
https://github.com/renovatebot/renovate/blob/132db01f14ce5c30609b8e82279ab14c9da9e8ff/lib/workers/global/index.ts#L178-L181

But, we only set `allowedHeaders` to GlobalConfig here:
https://github.com/renovatebot/renovate/blob/132db01f14ce5c30609b8e82279ab14c9da9e8ff/lib/workers/global/index.ts#L212

**Comment by RahulGautamSingh** [comment]
Btw, this will also happen regardless of whether `autodiscover` is enabled. When `hostRules` are configured in the file config, then we will verify the `headers` if present, within them against `allowedHeaders` when requests are made. And the first such request is made inside the `initPlatform` function call.

Therefore, tsetting `allowedHeaders` in global config before `initPlatform` is invoked should fix this bug.
Changes should be made in this file:
https://github.com/renovatebot/renovate/blob/132db01f14ce5c30609b8e82279ab14c9da9e8ff/lib/workers/global/index.ts#L160-L166

**Comment by lmarschall** [comment]
Any workaround possible, that I can use this feature at the moment, unfortunately the pipeline stops, at least successfully, but stops  because of config errors, and it doesn't proceed to check the docker-compose files in the repo. Changed my config according to https://github.com/renovatebot/renovate/issues/26983.

```
[0KRunning with gitlab-runner 13.8.0 (775dd39d)
[0;m[0K  on lxrunner docker J7ky3Fid
[0;msection_start:1712213592:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m
[0;m[0KUsing Docker executor with image renovate/renovate:37.278.1 ...
[0;m[0KPulling docker image renovate/renovate:37.278.1 ...
[0;m[0KUsing docker image sha256:bbd5586b09b4004ca63bfd87103844bd407248f49640b4a93380c03019ce7b74 for renovate/renovate:37.278.1 with digest renovate/renovate@sha256:f4c59b073e0a1266802b388f558f62bb3eaa42cdcdc7d31e19ecd76cde9d4f27 ...
[0;msection_end:1712213596:prepare_executor
[0Ksection_start:1712213596:prepare_script
[0K[0K[36;1mPreparing environment[0;m
[0;mRunning on runner-j7ky3fid-project-182-concurrent-0 via lxrunner...
section_end:1712213596:prepare_script
[0Ksection_start:1712213596:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m
[0;m[32;1mFetching changes with git depth set to 20...[0;m
Reinitialized existing Git repository in /builds/it/renovate/.git/
[32;1mChecking out 45e1b6b2 as main...[0;m
Removing renovate/

[32;1mSkipping Git submodules setup[0;m
section_end:1712213597:get_sources
[0Ksection_start:1712213597:restore_cache
[0K[0K[36;1mRestoring cache[0;m
[0;m[32;1mChecking cache for main-renovate-2-protected...[0;m
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted.[0;m 
[32;1mSuccessfully extracted cache[0;m
section_end:1712213598:restore_cache
[0Ksection_start:1712213598:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m
[0;m[32;1m$ renovate $RENOVATE_EXTRA_FLAGS[0;m
DEBUG: Using RE2 regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in config.js
DEBUG: File config
       "config": {
         "endpoint": "https://git.docsinclouds.com/api/v4/",
         "platform": "gitlab",
         "persistRepoData": true,
         "logLevel": "debug",
         "repositories": ["161"],
         "onboardingConfig": {"extends": ["renovate/renovate-config"]},
         "autodiscover": false
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "hostRules": [],
         "repositoryCache": "true",
         "baseDir": "/builds/it/renovate/renovate",
         "optimizeForDisabled": true,
         "token": "***********",
         "gitAuthor": "Renovate <renovate@docsinclouds.com>"
       }
DEBUG: Combined config
       "config": {
         "endpoint": "https://git.docsinclouds.com/api/v4/",
         "platform": "gitlab",
         "persistRepoData": true,
         "logLevel": "debug",
         "repositories": ["161"],
         "onboardingConfig": {"extends": ["renovate/renovate-config"]},
         "autodiscover": false,
         "hostRules": [],
         "repositoryCache": "true",
         "baseDir": "/builds/it/renovate/renovate",
         "optimizeForDisabled": true,
         "token": "***********",
         "gitAuthor": "Renovate <renovate@docsinclouds.com>"
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Enabling forkProcessing while in non-autodiscover mode
DEBUG: Found valid git version: 2.43.2
DEBUG: Setting global hostRules
DEBUG: hostRules: authentication already set for git.docsinclouds.com
DEBUG: GitLab version is: 16.9.1
DEBUG: Using configured gitAuthor (Renovate <renovate@docsinclouds.com>)
DEBUG: Adding token authentication for git.docsinclouds.com (hostType=gitlab) to hostRules
DEBUG: Using configured baseDir: /builds/it/renovate/renovate
DEBUG: Using cacheDir: /builds/it/renovate/renovate/cache
DEBUG: Using containerbaseDir: /builds/it/renovate/renovate/cache/containerbase
DEBUG: Initializing Renovate internal cache into /builds/it/renovate/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
DEBUG: Setting global hostRules
DEBUG: Adding token authentication for git.docsinclouds.com (hostType=gitlab) to hostRules
DEBUG: validatePresets()
DEBUG: Reinitializing hostRules for repo
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for git.docsinclouds.com (hostType=gitlab) to hostRules
 INFO: Repository started (repository=161)
       "renovateVersion": "37.278.1"
DEBUG: Using localDir: /builds/it/renovate/renovate/repos/gitlab/161 (repository=161)
DEBUG: PackageFiles.clear() - Package files deleted (repository=161)
DEBUG: hostRules: applying Bearer authentication for git.docsinclouds.com (repository=161)
DEBUG: 161 default branch = main (repository=161)
DEBUG: Enabling Git FS (repository=161)
DEBUG: Using http URL: https://git.docsinclouds.com/it/monitoring.git (repository=161)
 WARN: File contents are invalid JSON but parse using JSON5. Support for this will be removed in a future release so please change to a support .json5 file name or ensure correct JSON syntax. (repository=161)
       "context": "renovate.json"
DEBUG: Resetting npmrc (repository=161)
DEBUG: Resetting npmrc (repository=161)
DEBUG: checkOnboarding() (repository=161)
DEBUG: isOnboarded() (repository=161)
DEBUG: findPr(renovate/configure, Configure Renovate, !open) (repository=161)
DEBUG: findPr(renovate/configure, chore: Configure Renovate, !open) (repository=161)
DEBUG: findFile(renovate.json) (repository=161)
DEBUG: Initializing git repository into /builds/it/renovate/renovate/repos/gitlab/161 (repository=161)
DEBUG: resetToBranch(main) (repository=161)
DEBUG: resetToBranch(main) (repository=161)
DEBUG:  (repository=161)
       "existingBranches": []
 INFO: git fetch completed (repository=161)
       "durationMs": 1560
DEBUG: latest repository commit (repository=161)
       "latestCommit": {
         "hash": "ed0da9551b245f61644d1c950d9cfaee2e6dbc4a",
         "date": "2024-04-03T11:38:14+00:00",
         "message": "Update renovate.json",
         "refs": "HEAD -> main, origin/main, origin/HEAD",
         "body": "",
         "author_name": "Lukas Marschall",
         "author_email": "lmarschall@docsinclouds.com"
       }
DEBUG: Config file exists, fileName: renovate.json (repository=161)
DEBUG: ensureIssueClosing() (repository=161)
DEBUG: Repo is onboarded (repository=161)
DEBUG: Found renovate.json config file (repository=161)
 WARN: File contents are invalid JSON but parse using JSON5. Support for this will be removed in a future release so please change to a support .json5 file name or ensure correct JSON syntax. (repository=161)
       "context": "renovate.json"
DEBUG: Repository config (repository=161)
       "fileName": "renovate.json",
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
         "extends": ["config:base"],
         "hostRules": [
           {
             "allowedHeaders": ["Authorization"],
             "headers": {"Authorization": "Bearer **redacted**"}
           }
         ],
         "enabledManagers": ["docker-compose"],
         "packageRules": [
           {"managers": ["docker-compose"], "groupName": "Drupal contributed modules"}
         ]
       }
DEBUG: migrateAndValidate() (repository=161)
DEBUG: Config migration necessary (repository=161)
       "oldConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
         "extends": ["config:base"],
         "hostRules": [
           {
             "allowedHeaders": ["Authorization"],
             "headers": {"Authorization": "Bearer **redacted**"}
           }
         ],
         "enabledManagers": ["docker-compose"],
         "packageRules": [
           {"managers": ["docker-compose"], "groupName": "Drupal contributed modules"}
         ]
       },
       "newConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
         "extends": ["config:recommended"],
         "hostRules": [
           {
             "allowedHeaders": ["Authorization"],
             "headers": {"Authorization": "Bearer **redacted**"}
           }
         ],
         "enabledManagers": ["docker-compose"],
         "packageRules": [
           {
             "matchManagers": ["docker-compose"],
             "groupName": "Drupal contributed modules"
           }
         ]
       }
DEBUG: Post-massage config (repository=161)
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "gitAuthor": "Renovate Bot <renovate-bot@mycompany.com>",
         "extends": ["config:recommended"],
         "hostRules": [
           {
             "allowedHeaders": ["Authorization"],
             "headers": {"Authorization": "Bearer **redacted**"}
           }
         ],
         "enabledManagers": ["docker-compose"],
         "packageRules": [
           {
             "matchManagers": ["docker-compose"],
             "groupName": "Drupal contributed modules"
           }
         ]
       }
 WARN: Found renovate config warnings (repository=161)
       "warnings": [
         {
           "topic": "Configuration Error",
           "message": "The \"allowedHeaders\" option is a global option reserved only for Renovate's global configuration and cannot be configured within a repository's config file."
         }
       ]
 INFO: Found renovate config errors (repository=161)
       "errors": [
         {
           "topic": "Configuration Error",
           "message": "hostRules header `Authorization` is not allowed by this bot's `allowedHeaders`."
         }
       ]
 INFO: Repository has invalid config (repository=161)
       "error": {
         "validationSource": "renovate.json",
         "validationError": "The renovate configuration file contains some invalid settings",
         "validationMessage": "hostRules header `Authorization` is not allowed by this bot's `allowedHeaders`.",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at mergeRenovateConfig (/usr/local/renovate/lib/workers/repository/init/merge.ts:185:19)\n    at getRepoConfig (/usr/local/renovate/lib/workers/repository/init/config.ts:14:12)\n    at initRepo (/usr/local/renovate/lib/workers/repository/init/index.ts:55:12)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:62:14)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:212:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:197:7)\n    at /usr/local/renovate/lib/renovate.ts:18:22"
       }
DEBUG: raiseConfigWarningIssue() (repository=161)
DEBUG: getBranchPr(renovate/configure) (repository=161)
DEBUG: findPr(renovate/configure, undefined, open) (repository=161)
DEBUG: ensureIssue() (repository=161)
DEBUG: Updating issue (repository=161)
DEBUG: Repository result: config-validation, status: onboarded, enabled: true, onboarded: true (repository=161)
DEBUG: Repository timing splits (milliseconds) (repository=161)
       "splits": {},
       "total": 3985
DEBUG: Package cache statistics (repository=161)
       "get": {"count": 0, "avgMs": 0, "medianMs": 0, "maxMs": 0, "totalMs": 0},
       "set": {"count": 0, "avgMs": 0, "medianMs": 0, "maxMs": 0, "totalMs": 0}
DEBUG: HTTP statistics (repository=161)
       "urls": {
         "https://git.docsinclouds.com/api/v4/projects/161": {"GET": {"200": 1}},
         "https://git.docsinclouds.com/api/v4/projects/161/issues/5": {
           "GET": {"200": 1},
           "PUT": {"200": 1}
         },
         "https://git.docsinclouds.com/api/v4/projects/161/issues": {
           "GET": {"200": 1}
         },
         "https://git.docsinclouds.com/api/v4/projects/161/merge_requests": {
           "GET": {"200": 1}
         },
         "https://git.docsinclouds.com/api/v4/projects/161/repository/files/renovate.json": {
           "GET": {"200": 1}
         }
       },
       "hosts": {
         "git.docsinclouds.com": {
           "count": 6,
           "reqAvgMs": 234,
           "reqMedianMs": 247,
           "reqMaxMs": 308,
           "queueAvgMs": 0,
           "queueMedianMs": 0,
           "queueMaxMs": 1
         }
       },
       "requests": 6
DEBUG: HTTP cache statistics (repository=161)
DEBUG: Lookup statistics (repository=161)
DEBUG: dns cache (repository=161)
       "hosts": []
 INFO: Repository finished (repository=161)
       "cloned": true,
       "durationMs": 3985
DEBUG: Checking file package cache for expired items
DEBUG: Deleted 0 of 0 file cached entries in 10ms
section_end:1712213607:step_script
[0Ksection_start:1712213607:archive_cache
[0K[0K[36;1mSaving cache for successful job[0;m
[0;m[32;1mCreating cache main-renovate-2-protected...[0;m
/builds/it/renovate/renovate: found 139 matching files and directories[0;m 
[37;1mTemporary file: ../../../cache/it/renovate/main-renovate-2-protected/archive_642454331[0;m 
No URL provided, cache will be not uploaded to shared cache server. Cache will be stored only locally.[0;m 
[32;1mCreated cache[0;m
section_end:1712213608:archive_cache
[0Ksection_start:1712213608:cleanup_file_variables
[0K[0K[36;1mCleaning up file based variables[0;m
[0;msection_end:1712213608:cleanup_file_variables
[0K[32;1mJob succeeded
[0;m
```

**Comment by lmarschall** [comment]
@RahulGautamSingh Thank you very much, for taking care 💯
