### ISSUE TITLE
Handle GitHub weird 500 Internal Error

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2784]
GitHub returns 200 OK but actually it encountered an Internal Server Error, and that triggers a ParseError in our client:

```
    "err": {
        "name": "ParseError",
        "host": "api.github.com",
        "hostname": "api.github.com",
        "method": "GET",
        "path": "/repos/cypress-io/schema-tools/commits/renovate/ramda-0.x/status",
        "protocol": "https:",
        "url": "https://api.github.com/repos/cypress-io/schema-tools/commits/renovate/ramda-0.x/status",
        "statusCode": 200,
        "statusMessage": "OK",
        "body": "HTTP/1.1 500 Internal Server Error\r\n\r\n",
        "message": "Unexpected token H in JSON at position 0 in \"https://api.github.com/repos/cypress-io/schema-tools/commits/renovate/ramda-0.x/status\": \nHTTP/1.1 500 Internal Server Error\r\n\r\n...",
        "stack": "ParseError: Unexpected token H in JSON at position 0 in \"https://api.github.com/repos/cypress-io/schema-tools/commits/renovate/ramda-0.x/status\": \nHTTP/1.1 500 Internal Server Error\r\n\r\n...\n    at stream.catch.then.data (/usr/src/node_modules/renovate/node_modules/got/index.js:380:15)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"
    },
```

**Comment by rarkins** [comment]
In this case we should treat it the same as a 5xx error - i.e. `platform-failure`: https://github.com/renovatebot/renovate/blob/0b6ad1c898d532ff90815367a739dcf4f8df1ef2/lib/platform/github/gh-got-wrapper.js#L108-L120
