### ISSUE TITLE
Support registryAliases for customManagers

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28699]
### Discussed in https://github.com/renovatebot/renovate/discussions/28697

<div type='discussions-op-text'>

<sup>Originally posted by **candrews** April 27, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

The regex/custom manager doesn't apply `registryAlias` configuration to the `registryUrl` value (if present).

For example:

`renovate.json`

```json
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
        "config:base"
    ],
    "registryAliases": {
        "$CI_SERVER_URL": "https://gitlab.com",
        "https://$CI_SERVER_HOST": "https://gitlab.com"
    },
    "customManagers": [
        {
          "customType": "regex",
          "fileMatch": [".*\\.gitlab-ci\\.yml$"],
          "matchStrings": [
            "datasource=(?<datasource>.*?) depName=(?<depName>.*?) (versioning=(?<versioning>.*?))? (registryUrl=(?<registryUrl>.*?))?\\s.*?_VERSION:\\s*\"(?<currentValue>.*)\"\\s"
          ],
          "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
        }
    ]
}
```

and `.gitlab-ci.yml`

```yaml
test:
  variables:
    # renovate: datasource=gitlab-tags depName=gitlab-com/gl-infra/common-ci-tasks versioning=semver registryUrl=https://${CI_SERVER_HOST}
    GITLAB_COMMON_CI_TASKS_VERSION: "v2.5.0"
    testing: "yes"
```

Renovate should report a version update being available, but instead the Dependency Dashboard shows a warning:
> Renovate failed to look up the following dependencies: Failed to look up gitlab-tags package gitlab-com/gl-infra/common-ci-tasks.
> 
> Files affected: .gitlab-ci.yml

Renovate should apply the registry alias configuration in this case.

Project demonstrating this issue: https://github.com/candrews/renovate-registry-url-test/

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: Deleted cached dep updates
INFO: Dependency extraction complete
{
  "baseBranch": "main"
  "stats": {
    "managers": {
      "regex": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 1
    }
  }
}

DEBUG: hostRules: no authentication for ${ci_server_host}
DEBUG: GET https://${ci_server_host}/api/v4/projects/gitlab-com%2Fgl-infra%2Fcommon-ci-tasks/repository/tags?per_page=100 = (code=ENOTFOUND, statusCode=-1 retryCount=2, duration=1)
DEBUG: Gitlab API error
{
  "err": {
    "name": "RequestError",
    "code": "ENOTFOUND",
    "timings": {
      "start": 1714177595111,
      "socket": 1714177595111,
      "lookup": 1714177595112,
      "error": 1714177595112,
      "phases": {
        "wait": 0,
        "dns": 1,
        "total": 1
      }
    },
    "message": "getaddrinfo ENOTFOUND ${ci_server_host}",
    "stack": "RequestError: getaddrinfo ENOTFOUND ${ci_server_host}\n    at ClientRequest.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:111)\n    at Object.onceWrapper (node:events:632:26)\n    at ClientRequest.emit (node:events:529:35)\n    at ClientRequest.emit (node:domain:489:12)\n    at ClientRequest.origin.emit (/usr/local/renovate/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n    at TLSSocket.emit (node:events:517:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)",
    "options": {
      "headers": {
        "user-agent": "RenovateBot/37.321.2 (https://github.com/renovatebot/renovate)",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate, br"
      },
      "url": "https://${ci_server_host}/api/v4/projects/gitlab-com%2Fgl-infra%2Fcommon-ci-tasks/repository/tags?per_page=100",
      "hostType": "gitlab-tags",
      "username": "",
      "password": "",
      "method": "GET",
      "http2": false
    }
  }
}

DEBUG: Datasource connection error
{
  "datasource": "gitlab-tags"
  "packageName": "gitlab-com/gl-infra/common-ci-tasks"
  "errCode": "ENOTFOUND"
}

DEBUG: Failed to look up gitlab-tags package gitlab-com/gl-infra/common-ci-tasks
{
  "dependency": "gitlab-com/gl-infra/common-ci-tasks"
  "packageFile": ".gitlab-ci.yml"
}
```

</details>

from https://developer.mend.io/github/candrews/renovate-registry-url-test/-/job/a59304a4-09ac-4898-afa2-878cd94ab342</div>

**Comment by viceice** [comment]
this is not a bug. only a few managers support registry aliases. it's documented 

https://docs.renovatebot.com/configuration-options/#registryaliases

**Comment by rarkins** [comment]
Users think everything's a bug :)
