### ISSUE TITLE
Invalid enum value. Expected 'application/vnd.oci.image.config.v1+json' | 'application/vnd.cncf.helm.config.v1+json', received 'application/vnd.devcontainers'

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#29241]
### Discussed in https://github.com/renovatebot/renovate/discussions/29238

<div type='discussions-op-text'>

<sup>Originally posted by **lmilbaum** May 24, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

GitLab

### Please tell us more about your question or problem

A pre-commit devcontainer features throws this error

Reconstruction repo - https://github.com/platform-engineering-org-test/renovate-devcontainer

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: Invalid manifest response
{
  "registry": "https://ghcr.io"
  "dockerRepository": "devcontainers-contrib/features/pre-commit"
  "tag": "latest"
  "body": "{\"schemaVersion\":2,\"mediaType\":\"application/vnd.oci.image.manifest.v1+json\",\"config\":{\"mediaType\":\"application/vnd.devcontainers\",\"digest\":\"sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\",\"size\":0},\"layers\":[{\"mediaType\":\"application/vnd.devcontainers.layer.v1+tar\",\"digest\":\"sha256:f06f20f8fa4737e8ef0a3d4446526118d443037a1eb606c31c05cfd94dcba7a8\",\"size\":11776,\"annotations\":{\"org.opencontainers.image.title\":\"devcontainer-feature-pre-commit.tgz\"}}],\"annotations\":{\"dev.containers.metadata\":\"{\\\"id\\\":\\\"pre-commit\\\",\\\"version\\\":\\\"2.0.17\\\",\\\"name\\\":\\\"Pre-Commit (via pipx)\\\",\\\"documentationURL\\\":\\\"http://github.com/devcontainers-contrib/features/tree/main/src/pre-commit\\\",\\\"description\\\":\\\"Pre-Commit is a framework for managing and maintaining multi-language pre-commit hooks.\\\",\\\"options\\\":{\\\"version\\\":{\\\"default\\\":\\\"latest\\\",\\\"description\\\":\\\"Select the version of Pre-Commit to install.\\\",\\\"proposals\\\":[\\\"latest\\\"],\\\"type\\\":\\\"string\\\"}},\\\"installsAfter\\\":[\\\"ghcr.io/devcontainers-contrib/features/pipx-package\\\",\\\"ghcr.io/devcontainers/features/python\\\"]}\",\"com.github.package.type\":\"devcontainer_feature\"}}"
  "headers": {
    "content-length": "1139",
    "content-type": "application/vnd.oci.image.manifest.v1+json",
    "docker-content-digest": "sha256:c18a7604e12b531e5a4e990c630e3f036d932903eb1e3b333e5c9e10a891e1a8",
    "docker-distribution-api-version": "registry/2.0",
    "etag": "\"sha256:c18a7604e12b531e5a4e990c630e3f036d932903eb1e3b333e5c9e10a891e1a8\"",
    "date": "Fri, 24 May 2024 04:57:35 GMT",
    "x-github-request-id": "3F02:282392:25C362E:2CDB0FF:66501E3F",
    "connection": "close"
  }
  "err": {
    "message": "Schema error",
    "stack": "ZodError: Schema error\n    at Object.get error [as error] (/usr/local/renovate/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:55:31)\n    at DockerDatasource.getManifest (/usr/local/renovate/lib/modules/datasource/docker/index.ts:301:23)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at DockerDatasource.getLabels (/usr/local/renovate/lib/modules/datasource/docker/index.ts:461:24)\n    at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n    at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1091:20)\n    at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n    at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n    at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:134:56)\n    at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n    at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n    at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
    "issues": {
      "config": {
        "mediaType": "Invalid enum value. Expected 'application/vnd.oci.image.config.v1+json' | 'application/vnd.cncf.helm.config.v1+json', received 'application/vnd.devcontainers'",
        "size": "Number must be greater than 0"
      }
    }
  }
}

DEBUG: No manifest found
{
  "registryHost": "https://ghcr.io"
  "dockerRepository": "devcontainers-contrib/features/pre-commit"
  "tag": "latest"
}

DEBUG: Invalid manifest response
{
  "registry": "https://ghcr.io"
  "dockerRepository": "devcontainers/features/ruby"
  "tag": "latest"
  "body": "{\"schemaVersion\":2,\"mediaType\":\"application/vnd.oci.image.manifest.v1+json\",\"config\":{\"mediaType\":\"application/vnd.devcontainers\",\"digest\":\"sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\",\"size\":0},\"layers\":[{\"mediaType\":\"application/vnd.devcontainers.layer.v1+tar\",\"digest\":\"sha256:d8b664ac545af10e7b241df64305d0ee7b544b826b7fe53bd7f35af114fdad97\",\"size\":22528,\"annotations\":{\"org.opencontainers.image.title\":\"devcontainer-feature-ruby.tgz\"}}],\"annotations\":{\"dev.containers.metadata\":\"{\\\"id\\\":\\\"ruby\\\",\\\"version\\\":\\\"1.2.1\\\",\\\"name\\\":\\\"Ruby (via rvm)\\\",\\\"documentationURL\\\":\\\"https://github.com/devcontainers/features/tree/main/src/ruby\\\",\\\"description\\\":\\\"Installs Ruby, rvm, rbenv, common Ruby utilities, and needed dependencies.\\\",\\\"options\\\":{\\\"version\\\":{\\\"type\\\":\\\"string\\\",\\\"proposals\\\":[\\\"latest\\\",\\\"none\\\",\\\"3.1\\\",\\\"3.0\\\",\\\"2.7\\\"],\\\"default\\\":\\\"latest\\\",\\\"description\\\":\\\"Select or enter a Ruby version to install\\\"}},\\\"customizations\\\":{\\\"vscode\\\":{\\\"extensions\\\":[\\\"shopify.ruby-lsp\\\"]}},\\\"containerEnv\\\":{\\\"GEM_PATH\\\":\\\"/usr/local/rvm/gems/default:/usr/local/rvm/gems/default@global\\\",\\\"GEM_HOME\\\":\\\"/usr/local/rvm/gems/default\\\",\\\"MY_RUBY_HOME\\\":\\\"/usr/local/rvm/rubies/default\\\",\\\"PATH\\\":\\\"/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:${PATH}\\\"},\\\"installsAfter\\\":[\\\"ghcr.io/devcontainers/features/common-utils\\\"]}\",\"com.github.package.type\":\"devcontainer_feature\"}}"
  "headers": {
    "content-length": "1493",
    "content-type": "application/vnd.oci.image.manifest.v1+json",
    "docker-content-digest": "sha256:1bd97a12f96f140e6ccc8d43bfb7aea289c2a20a9e9fac94f897f2ea74a74d66",
    "docker-distribution-api-version": "registry/2.0",
    "etag": "\"sha256:1bd97a12f96f140e6ccc8d43bfb7aea289c2a20a9e9fac94f897f2ea74a74d66\"",
    "date": "Fri, 24 May 2024 04:57:35 GMT",
    "x-github-request-id": "696F:282392:25C362E:2CDB101:66501E3F",
    "connection": "close"
  }
  "err": {
    "message": "Schema error",
    "stack": "ZodError: Schema error\n    at Object.get error [as error] (/usr/local/renovate/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:55:31)\n    at DockerDatasource.getManifest (/usr/local/renovate/lib/modules/datasource/docker/index.ts:301:23)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at DockerDatasource.getLabels (/usr/local/renovate/lib/modules/datasource/docker/index.ts:461:24)\n    at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n    at DockerDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/docker/index.ts:1091:20)\n    at getRegistryReleases (/usr/local/renovate/lib/modules/datasource/index.ts:77:15)\n    at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:289:15)\n    at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:134:56)\n    at Function.wrap (/usr/local/renovate/lib/util/stats.ts:38:20)\n    at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:58:42)\n    at /usr/local/renovate/lib/workers/repository/process/fetch.ts:104:23\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
    "issues": {
      "config": {
        "mediaType": "Invalid enum value. Expected 'application/vnd.oci.image.config.v1+json' | 'application/vnd.cncf.helm.config.v1+json', received 'application/vnd.devcontainers'",
        "size": "Number must be greater than 0"
      }
    }
  }
}

DEBUG: No manifest
```

</details>
</div>

**Comment by viceice** [comment]
reproduction forked to https://github.com/renovate-reproductions/29241-renovate-devcontainer

**Comment by viceice** [comment]
sample manifest:
```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.devcontainers",
    "digest": "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "size": 0
  },
  "layers": [{
      "mediaType": "application/vnd.devcontainers.layer.v1+tar",
      "digest": "sha256:d8b664ac545af10e7b241df64305d0ee7b544b826b7fe53bd7f35af114fdad97",
      "size": 22528,
      "annotations": {
        "org.opencontainers.image.title": "devcontainer-feature-ruby.tgz"
      }
    }
  ],
  "annotations": {
    "dev.containers.metadata": "{\"id\":\"ruby\",\"version\":\"1.2.1\",\"name\":\"Ruby (via rvm)\",\"documentationURL\":\"https://github.com/devcontainers/features/tree/main/src/ruby\",\"description\":\"Installs Ruby, rvm, rbenv, common Ruby utilities, and needed dependencies.\",\"options\":{\"version\":{\"type\":\"string\",\"proposals\":[\"latest\",\"none\",\"3.1\",\"3.0\",\"2.7\"],\"default\":\"latest\",\"description\":\"Select or enter a Ruby version to install\"}},\"customizations\":{\"vscode\":{\"extensions\":[\"shopify.ruby-lsp\"]}},\"containerEnv\":{\"GEM_PATH\":\"/usr/local/rvm/gems/default:/usr/local/rvm/gems/default@global\",\"GEM_HOME\":\"/usr/local/rvm/gems/default\",\"MY_RUBY_HOME\":\"/usr/local/rvm/rubies/default\",\"PATH\":\"/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:${PATH}\"},\"installsAfter\":[\"ghcr.io/devcontainers/features/common-utils\"]}",
    "com.github.package.type": "devcontainer_feature"
  }
}
```
