### ISSUE TITLE
NO_PROXY not working

### ISSUE THREAD

**Issue by spk83** [renovatebot/renovate#2966]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Getting Unhandled Promise Rejection while trying to run renovate command against self-hosted GitLab instance behind corporate firewall. Proxy and no-proxy variables are set and seems like promise is not being handled correctly by `proxy-agent`.

**Did you see anything helpful in debug logs?**
Tried running with DEBUG log level. Occurs after `GET` action while trying to `initRepo`.

**To Reproduce**

1.  Install renovate `13.154.3` using `npm install -g renovate`
2.  Use following configuration for `renovate.json`
```
{
  "assignees": [
    "jdoe"
  ],
  "baseBranches": [
    "master"
  ],
  "extends": [
    "config:base"
  ],
  "labels":[
    "renovate-bot"
  ],
  "packageRules": [{
      "updateTypes": ["major"],
      "labels": ["RENOVATE-UPDATE-MAJOR"]
    }
  ],
  "pin":{
    "assignees": [
      "jdoe"
    ]
  },
  "automerge": true,
  "major": {
    "automerge": false
  },
  "automergeType": "pr-comment",
  "automergeComment": "@jdoe: renovate-bot has updated minor and patch versions and automerging this MR",
  "semanticCommits": true
}
```

**Expected behavior**
`renovate` to run and update/raise-MR without throwing any error if correct configuration is provided

**Screenshots**
```
DEBUG: GET (repository=ABC/test-repo)
       "path": "projects/ABC%2Ftest-repo"
DEBUG: Caught initRepo error (repository=ABC/test-repo)
 INFO: Unknown GitLab initRepo error (repository=ABC/test-repo)
       "err": {
         "name": "RequestError",
         "hostname": "x.y.com",
         "method": "GET",
         "path": "/api/v4/projects/ABC%2Ftest-repo",
         "protocol": "https:",
         "url": "https://x.y.com/api/v4/projects/ABC%2Ftest-repo",
         "gotOptions": {
           "path": "/api/v4/projects/ABC%2Ftest-repo",
           "protocol": "https:",
           "hostname": "x.y.com",
           "hash": "",
           "search": "",
           "pathname": "/api/v4/projects/ABC%2Ftest-repo",
           "href": "https://x.y.com/api/v4/projects/ABC%2Ftest-repo",
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "headers": {
             "user-agent": "https://github.com/singapore/gl-got",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate",
             "PRIVATE-TOKEN": "xxxxxxx"
           },
           "hooks": {
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "token": "xxxx",
           "baseUrl": "https://x.y.com/api/v4/",
           "name": "GitLab",
           "platform": "gitlab",
           "default": true,
           "method": "GET"
         },
         "message": "Maximum call stack size exceeded",
         "stack": "RequestError: Maximum call stack size exceeded\n    at get (/usr/local/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:223:27)\n    at Immediate.setImmediate [as _onImmediate] (/usr/local/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:292:10)\n    at <anonymous>"
       }
ERROR: Repository has unknown error (repository=ABC/test-repo)
       "err": {
         "name": "RequestError",
         "hostname": "x.y.com",
         "method": "GET",
         "path": "/api/v4/projects/ABC%2Ftest-repo",
         "protocol": "https:",
         "url": "https://x.y.com/api/v4/projects/ABC%2Ftest-repo",
         "gotOptions": {
           "path": "/api/v4/projects/ABC%2Ftest-repo",
           "protocol": "https:",
           "hostname": "x.y.com",
           "hash": "",
           "search": "",
           "pathname": "/api/v4/projects/ABC%2Ftest-repo",
           "href": "https://x.y.com/api/v4/projects/ABC%2Ftest-repo",
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "headers": {
             "user-agent": "https://github.com/singapore/gl-got",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate",
             "PRIVATE-TOKEN": "xxxxxx"
           },
           "hooks": {
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "token": "xxxxx",
           "baseUrl": "https://x.y.com/api/v4/",
           "name": "GitLab",
           "platform": "gitlab",
           "default": true,
           "method": "GET"
         },
         "message": "Maximum call stack size exceeded",
         "stack": "RequestError: Maximum call stack size exceeded\n    at get (/usr/local/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:223:27)\n    at Immediate.setImmediate [as _onImmediate] (/usr/local/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:292:10)\n    at <anonymous>"
       }
 INFO: Unknown error (repository=ABC/test-repo)
       "err": {
         "name": "RequestError",
         "hostname": "x.y.com",
         "method": "GET",
         "path": "/api/v4/projects/ABC%2Ftest-repo",
         "protocol": "https:",
         "url": "https://x.y.com/api/v4/projects/ABC%2Ftest-repo",
         "gotOptions": {
           "path": "/api/v4/projects/ABC%2Ftest-repo",
           "protocol": "https:",
           "hostname": "x.y.com",
           "hash": "",
           "search": "",
           "pathname": "/api/v4/projects/ABC%2Ftest-repo",
           "href": "https://x.y.com/api/v4/projects/ABC%2Ftest-repo",
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "headers": {
             "user-agent": "https://github.com/singapore/gl-got",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate",
             "PRIVATE-TOKEN": "xxxxx"
           },
           "hooks": {
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "token": "xxxxxx",
           "baseUrl": "https://x.y.com/api/v4/",
           "name": "GitLab",
           "platform": "gitlab",
           "default": true,
           "method": "GET"
         },
         "message": "Maximum call stack size exceeded",
         "stack": "RequestError: Maximum call stack size exceeded\n    at get (/usr/local/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:223:27)\n    at Immediate.setImmediate [as _onImmediate] (/usr/local/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:292:10)\n    at <anonymous>"
       },
       "message": "Maximum call stack size exceeded"
(node:44037) UnhandledPromiseRejectionWarning: RequestError: Maximum call stack size exceeded
    at ClientRequest.request.once.error (/usr/local/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:165:14)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.origin.emit.args [as emit] (/usr/local/lib/node_modules/renovate/node_modules/@szmarczak/http-timer/source/index.js:36:11)
    at onerror (/usr/local/lib/node_modules/renovate/node_modules/agent-base/index.js:101:9)
    at callbackError (/usr/local/lib/node_modules/renovate/node_modules/agent-base/index.js:123:5)
    at <anonymous>
(node:44037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44037) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:44037) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at /usr/local/lib/node_modules/renovate/node_modules/es6-promisify/dist/promisify.js:79:21
    at new Promise (<anonymous>)
    at ProxyAgent.callback (/usr/local/lib/node_modules/renovate/node_modules/es6-promisify/dist/promisify.js:54:20)
    at ProxyAgent.addRequest (/usr/local/lib/node_modules/renovate/node_modules/agent-base/index.js:161:26)
    at ProxyAgent.connect (/usr/local/lib/node_modules/renovate/node_modules/proxy-agent/index.js:193:11)
    at /usr/local/lib/node_modules/renovate/node_modules/es6-promisify/dist/promisify.js:75:41
    at new Promise (<anonymous>)
    at ProxyAgent.callback (/usr/local/lib/node_modules/renovate/node_modules/es6-promisify/dist/promisify.js:54:20)
    at ProxyAgent.addRequest (/usr/local/lib/node_modules/renovate/node_modules/agent-base/index.js:161:26)
    at ProxyAgent.connect (/usr/local/lib/node_modules/renovate/node_modules/proxy-agent/index.js:193:11)
    at /usr/local/lib/node_modules/renovate/node_modules/es6-promisify/dist/promisify.js:75:41
    at new Promise (<anonymous>)
    at ProxyAgent.callback (/usr/local/lib/node_modules/renovate/node_modules/es6-promisify/dist/promisify.js:54:20)
    at ProxyAgent.addRequest (/usr/local/lib/node_modules/renovate/node_modules/agent-base/index.js:161:26)
    at ProxyAgent.connect (/usr/local/lib/node_modules/renovate/node_modules/proxy-agent/index.js:193:11)
    at /usr/local/lib/node_modules/renovate/node_modules/es6-promisify/dist/promisify.js:75:41
```

Throws this rejection warning till `rejection id: 45`

```
(node:44037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45)
```

**Additional context**

I have following environment variables set for proxy configuration
```
NO_PROXY, no_proxy, FTP_PROXY, ftp_proxy,
ALL_PROXY, all_proxy, HTTPS_PROXY, https_proxy, HTTP_PROXY, http_proxy
```
These environment variables for tokens
```
GITHUB_TOKEN=xxxxxxxx
GITLAB_TOKEN=yyyyyyyy
```

And used following command to run renovate CLI
```
renovate --platform gitlab --git-author renovate-bot --endpoint https://x.y.com/api/v4 --log-level debug ABC/test-repo
```

**Comment by rarkins** [comment]
Is there a proxy between you and GitLab, or between GitLab and the internet?

**Comment by spk83** [comment]
Proxy is between local terminal and internet, and GitLab and internet. GitLab and local terminal are in same network.

**Comment by rarkins** [comment]
So if you configure proxy, it means that Renovate will attempt to use the proxy for all connections, including the one to GitLab. I suspect that the NO_PROXY config is not working correctly.

If you are on the same network as GitLab then you should be able to connect to it without using any proxy connections at all. You'll then find that lookups to things like npmjs probably fail - as expected.

So please do this:

1. Clear out all proxy settings
2. Run `renovate --platform gitlab --endpoint https://x.y.com/api/v4 --dry-run=true --log-level=debug ABC/test-repo`

The goal should be that you at least can connect to GitLab directly before attempting to use proxies.

**Comment by spk83** [comment]
Yep, you are right about that. Unsetting proxy environment variables did allow to connect with GitLab. It failed with `npm registry failure` after `renovate.json migrated config`. I'll try to debug issue with NO_PROXY config and get back to you. Current NO_PROXY has worked with npm and yarn before while downloading private npm packages, I'll check what is the syntax `proxy-agent` supports.

**Comment by rarkins** [comment]
So the next step is to set the proxy env back again but also set NO_PROXY matching your GitLab server.

Be warned: it's entirely possible that our NO_PROXY implementation has a bug, but I want to make sure that's the case first.

**Comment by spk83** [comment]
I did, set NO_PROXY to `x.y.com` and it started throwing same errors as earlier.  Seems like `proxy-agent` does not support `NO_PROXY` environment variables - https://github.com/TooTallNate/node-proxy-agent/issues/33

**Comment by spk83** [comment]
Looks like it has been pending for a long time - https://github.com/TooTallNate/node-proxy-agent/issues/10

Any particular reason to use `proxy-agent`?

**Comment by spk83** [comment]
I take that back - https://github.com/TooTallNate/node-proxy-agent/blob/master/index.js#L169 

https://github.com/Rob--W/proxy-from-env does support NO_PROXY environment variable

**Comment by spk83** [comment]
I might have understood the issue here - 

1. No `opts` are passed to `ProxyAgent` invocation here - https://github.com/renovatebot/renovate/blob/master/lib/proxy.js#L11

2. If you pass `opts` to `ProxyAgent` invocation, it won't call `getProxyForUrl` with `opts` here - https://github.com/TooTallNate/node-proxy-agent/blob/master/index.js#L169. That is because they would have been set here already - https://github.com/TooTallNate/node-proxy-agent/blob/master/index.js#L149.

3. We could solve this by passing `urlParse` options through `getProxyForUrl ` and use those request options instead.

@rarkins  @kayoub5  Thoughts?

**Comment by spk83** [comment]
Looks like you guys might be doing that by relying on https://github.com/TooTallNate/node-proxy-agent/blob/master/index.js#L162 `connect` to call `getProxyForUrl`.

**Comment by rarkins** [comment]
Do I understand correctly that proxy detection from env appears to be working, but no_proxy is not?

**Comment by spk83** [comment]
Yes, that's what it seems like. Although I couldn't verify if https_proxy is being correctly used or not either as renovate doesn't reach to the step of connecting to internet.

**Comment by spk83** [comment]
Did some testing around `proxy-from-env` lib. NO_PROXY works as expected. 

```js
var http = require('http');
var https = require('https');
var parseUrl = require('url').parse;
var getProxyForUrl = require('proxy-from-env').getProxyForUrl;

var some_url = 'https://x.y.com';

// // Example, if there is a proxy server at 10.0.0.1:1234, then setting the
// // http_proxy environment variable causes the request to go through a proxy.
// process.env.http_proxy = 'http://10.0.0.1:1234';
// 
// // But if the host to be proxied is listed in NO_PROXY, then the request is
// // not proxied (but a direct request is made).
// process.env.no_proxy = 'example.com';

var proxy_url = getProxyForUrl(some_url);  // <-- Our magic.
if (proxy_url) {
  // Should be proxied through proxy_url.
  var parsed_some_url = parseUrl(some_url);
  var parsed_proxy_url = parseUrl(proxy_url);
  // A HTTP proxy is quite simple. It is similar to a normal request, except the
  // path is an absolute URL, and the proxied URL's host is put in the header
  // instead of the server's actual host.
  httpOptions = {
    protocol: parsed_proxy_url.protocol,
    hostname: parsed_proxy_url.hostname,
    port: parsed_proxy_url.port,
    path: parsed_some_url.href,
    headers: {
      Host: parsed_some_url.host,  // = host name + optional port.
    },
  };
} else {
  // Direct request.
  console.log("not using proxy");
  httpOptions = some_url;
}

if (httpOptions.protocol === 'http:') {
  http.get(httpOptions, function(res) {
    var responses = [];
    res.on('data', function(chunk) { responses.push(chunk); });
    res.on('end', function() { console.log(responses.join(''));  });
  });
} else {
  https.get(httpOptions, function(res) {
    var responses = [];
    res.on('data', function(chunk) { responses.push(chunk); });
    res.on('end', function() { console.log(responses.join(''));  });
});
}
```

Although for connecting external websites over HTTPS, script had to use `http` agent as HTTPS_PROXY points to `http://secure-x-proxy.y.com:8080`.

**Comment by rarkins** [comment]
I can reproduce this from a clone of the repo using this command:

```
HTTPS_PROXY=https://renovatebot.com NO_PROXY=api.github.com yarn start foo/bar
```

**Comment by spk83** [comment]
Further testing with `proxy-agent` tells me that proxy settings are correct and works fine

```
var https = require('https');
var ProxyAgent = require('proxy-agent');

var internalOpts = {
  method: 'GET',
  host: 'x.y.com',
  path: '/',
  agent: new ProxyAgent()
};

https.get(internalOpts, onresponse);

var proxyUri = process.env.https_proxy;

var externalOpts = {
  method: 'GET',
  host: 'github.com',
  path: '/',
  agent: new ProxyAgent(proxyUri)
};

https.get(externalOpts, onresponse);

function onresponse (res) {
  console.log(res.statusCode, res.headers);
  res.pipe(process.stdout);
}
```
