### ISSUE TITLE
Reconfigure Check Fails on Gitlab

### ISSUE THREAD

**Issue by dominik-bln** [renovatebot/renovate#2967]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
When opening a reconfigure merge request on Gitlab as described in: 

https://renovatebot.com/docs/reconfigure-renovate/

The check fails with an error that looks like an API incompatibility.

**Did you see anything helpful in debug logs?**

```text
Error checking PR (repository=alpha/alpha)
       "err": {
         "message": "files.map is not a function",
         "stack": "TypeError: files.map is not a function\n    at Object.getPrFiles (/usr/src/app/lib/platform/gitlab/index.js:695:16)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
       },
       "prNo": 1657,
       "branchName": "use-renovate-branch-prefix"
```

**To Reproduce**

1.  In Gitlab open an MR with "Renovate" in the title that changes the `renovate.json`

**Expected behavior**

The MR is checked for correct renovate configuration.

**Comment by rarkins** [comment]
Thanks. Sounds like we have something wrong with getPrFiles
