### ISSUE TITLE
GitHub Enterprise returns 406 - Not Acceptable

### ISSUE THREAD

**Issue by Journerist** [renovatebot/renovate#3026]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
I am using github enterprise, added my personal access token and verified that it works. I also set the endpoint url. Here's my renovate command:

`npx renovate --token my-token --endpoint https://github.corp.my-company.com --dry-run true --log-level debug 'my-username/my-repo'` 

**Did you see anything helpful in debug logs?**
```
Unknown error (repository=my-repo)
       "err": {
         "name": "HTTPError",
         "hostname": "github.corp.my-company.com",
         "method": "GET",
         "path": "/user",
         "protocol": "https:",
         "url": "https://github.corp.my-company.com/user",
         "gotOptions": {
           "path": "/user",
           "protocol": "https:",
           "hostname": "github.corp.my-company.com",
           "hash": "",
           "search": "",
           "pathname": "/user",
           "href": "https://github.corp.my-company.com/user",
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "headers": {
             "user-agent": "https://github.com/sindresorhus/gh-got",
             "accept": "application/vnd.github.v3+json",
             "accept-encoding": "gzip, deflate",
             "authorization": "token my-token"
           },
           "hooks": {
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "baseUrl": "https://github.corp.my-company.com/",
           "name": "GitHub",
           "platform": "github",
           "token": "my-token",
           "default": true,
           "method": "GET"
         },
         "statusCode": 406,
         "statusMessage": "Not Acceptable",
         "headers": {
           "server": "GitHub.com",
           "date": "Fri, 04 Jan 2019 09:23:58 GMT",
           "transfer-encoding": "chunked",
           "connection": "close",
           "status": "406 Not Acceptable",
           "cache-control": "no-cache, no-store",
           "vary": "X-PJAX",
           "set-cookie": [
             "_fi_sess=eyJzZXNzaW9uX2lkIjoiNDg0OWRjYTM5NDliZmMyOTQ3NjUxNmI2MzZhOWRmZGEiLCJsYXN0X3JlYWRfZnJvbV9yZXBsaWNhcyI6MTU0NjU5MzgzODg5MSwicmV0dXJuX3RvIjoiaHR0cHM6Ly9naXRodWIuY29ycC5lYmF5LmNvbS91c2VyIiwiZmxhc2giOnsiZGlzY2FyZCI6W10sImZsYXNoZXMiOnsiYW5hbHl0aWNzX2xvY2F0aW9uX3F1ZXJ5X3N0cmlwIjoidHJ1ZSJ9fX0%3D--21cc6517aeed05066ce79b3c6624fc13e1dda8c1; path=/; secure; HttpOnly"
           ],
           "x-request-id": "8927fa2d-35c0-47b1-9acd-39d899e95d23",
           "x-runtime": "0.005851",
           "x-github-request-id": "16adfc69-b825-414d-9743-7c5eda66b298",
           "strict-transport-security": "max-age=31536000; includeSubdomains",
           "x-frame-options": "deny",
           "x-content-type-options": "nosniff",
           "x-xss-protection": "1; mode=block",
           "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
           "content-security-policy": "default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.corp.my-company.com media.github.corp.my-company.com status.github.com github.corp.my-company.com wss://github.corp.my-company.com; font-src assets.github.corp.my-company.com; form-action 'self' github.corp.my-company.com gist.github.corp.my-company.com pages.github.corp.my-company.com; frame-ancestors 'none'; frame-src render.github.corp.my-company.com; img-src * data:; manifest-src 'self'; media-src 'none'; script-src assets.github.corp.my-company.com; style-src 'unsafe-inline' assets.github.corp.my-company.com",
           "x-runtime-rack": "0.009762"
         },
         "body": "",
         "message": "Response code 406 (Not Acceptable)",
         "stack": "HTTPError: Response code 406 (Not Acceptable)\n    at EventEmitter.emitter.on (/Users/sebarthel/Workspace/slack/renovate-try/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       },
       "message": "Response code 406 (Not Acceptable)"
```

**To Reproduce**

1.  get the current renovate npm package
2. try to use it with your github enterprise

**Expected behavior**
It should create an onboarding PR.

**Additional context**
GitHub Enterprise 2.14.7. I am confused by the 406. I tried my token by opening `curl -s -H 'authorization: token my-token' "https://github.corp.my-company.com/api/v3/organizations/4633/repos?per_page=100&page=1"`

**Comment by rarkins** [comment]
If it's failing on https://github.corp.my-company.com/user then that's probably the first step where Renovate tries to work out which account/username it is running as.

That commit was here: https://github.com/renovatebot/renovate/commit/99faf6fe0da7784460fe0e84162bcebf473002fc#diff-42751e8fceb1062d8a0a4456e13bd2ae

Can you try running `renovate@13.153.0` and see if the error persists/changes?

**Comment by rarkins** [comment]
BTW this is intended to work out if the problem is with that feature/endpoint specifically, or some other authentication problem with your setup.

**Comment by rarkins** [comment]
I didn't notice the exact the URL you gave. Can you try again with the full "base" URL specified? e.g. like `npx renovate --token my-token --endpoint https://github.corp.my-company.com/api/v3/ ... ` ?

**Comment by Journerist** [comment]
this works, awesome! I would suggest to add this information to the documentation. Keep up the good work and thx for the fast support.
