### ISSUE TITLE
Incorrect url used for getReleaseList call with Github Enterprise

### ISSUE THREAD

**Issue by gordlea** [renovatebot/renovate#3079]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
When using renovate with Github Enterprise, the url used in `getReleaseList` is incorrect.

It appears to be using: 

`https://github.mycompany.com/repos/someowner/somepackage/releases?per_page=100`

When, instead, it should be using:

`https://github.mycompany.com/api/v3/repos/someowner/somepackage/releases?per_page=100`

We are configured with the following env variables (this used to work I think):
```
GITHUB_TOKEN=my-ghe-token
GITHUB_ENDPOINT=https://github.myoffice.com/api/v3/
GITHUB_COM_TOKEN=my-gh-token
```

And the following cli params:
`--platform github --onboarding true --automerge false --log-level debug`

I've also tried it with 
```
RENOVATE_TOKEN=my-ghe-token
RENOVATE_ENDPOINT=https://github.myoffice.com/api/v3/
GITHUB_COM_TOKEN=my-gh-token
``` 
as suggested here: https://github.com/renovatebot/renovate/issues/1685

And also by adding the following the the cli command:
```
--token my-token --endpoint https://github.myoffice.com/api/v3/
```
As suggested here: https://github.com/renovatebot/renovate/issues/3026

**Did you see anything helpful in debug logs?**
The following repeats many times:
```
INFO: getReleaseList error (repository=someowner/somepackage, dependencies=@myoffice/package-a,@myoffice/package-b,@myoffice/package-c, branch=renovate/minorpatch-@myofficepackage)
       "err": {
         "name": "GitHubError",
         "hostname": "github.myoffice.com",
         "method": "GET",
         "path": "/repos/someowner/somepackage/releases?per_page=100",
         "protocol": "https:",
         "url": "https://github.myoffice.com/repos/someowner/somepackage/releases?per_page=100",
         "gotOptions": {
           "path": "/repos/someowner/somepackage/releases?per_page=100",
           "protocol": "https:",
           "hostname": "github.myoffice.com",
           "hash": "",
           "search": "?per_page=100",
           "pathname": "/repos/someowner/somepackage/releases",
           "href": "https://github.myoffice.com/repos/someowner/somepackage/releases?per_page=100",
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "headers": {
             "user-agent": "https://github.com/sindresorhus/gh-got",
             "accept": "application/vnd.github.v3+json",
             "accept-encoding": "gzip, deflate",
             "authorization": "token my-ghe-token"
           },
           "hooks": {
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "baseUrl": "https://github.myoffice.com/api/v3/",
           "name": "GitHub",
           "platform": "github",
           "token": "my-ghe-token",
           "default": true,
           "method": "GET"
         },
         "statusCode": 406,
         "statusMessage": "Not Acceptable",
         "headers": {
           "server": "GitHub.com",
           "date": "Wed, 16 Jan 2019 16:46:11 GMT",
           "content-type": "text/html; charset=utf-8",
           "transfer-encoding": "chunked",
           "connection": "close",
           "status": "406 Not Acceptable",
           "cache-control": "no-cache, no-store",
           "vary": "X-PJAX",
           "x-ua-compatible": "IE=Edge,chrome=1",
           "set-cookie": [
             "_fi_sess=somerealcookie; path=/; secure; HttpOnly"
           ],
           "x-request-id": "51161d42a816c1f5ee243dccce7f7bc5",
           "x-runtime": "0.007010",
           "x-github-request-id": "7cb2c21a-fc01-4061-b865-44ac21c14ae6",
           "content-security-policy": "default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src 'self'; connect-src 'self' github.myoffice.com status.github.com wss://github.myoffice.com; font-src 'self'; form-action 'self' github.myoffice.com; frame-ancestors 'none'; img-src * data:; manifest-src 'self'; media-src 'none'; script-src 'self'; style-src 'unsafe-inline' 'self'; worker-src 'self'",
           "strict-transport-security": "max-age=31536000; includeSubdomains",
           "x-content-type-options": "nosniff",
           "x-frame-options": "deny",
           "x-xss-protection": "1; mode=block",
           "x-runtime-rack": "0.012435"
         },
         "body": " ",
         "message": "undefined (406)",
         "stack": "GitHubError: undefined (406)\n    at EventEmitter.emitter.on (/Users/gordlea/dev/renovate-bot/node_modules/got/source/as-promise.js:74:19)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
       }
```

**To Reproduce**

1.  Create repository with '...'
2.  Configure '....'

**Expected behavior**
It should use the correct url:
`https://github.mycompany.com/api/v3/repos/someowner/somepackage/releases?per_page=100`

**Comment by rarkins** [comment]
Thanks for the detailed report. Looks like we need to add the api/v3 prefix whenever the host is not api.github.com
