### ISSUE TITLE
Failed test on Windows

### ISSUE THREAD

**Issue by KonstantinKurganov** [renovatebot/renovate#3136]
**What Renovate type are you using?**
Local dev environment.

**Describe the bug**
several tests fail

**Did you see anything helpful in debug logs?**
No, but I can provide logs

**To Reproduce**

1. `git clone ...`
2. `yarn install`
3. `yarn jset`

**Expected behavior**
All test pass on master branch

**Screenshots**

```
Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `yarn run jest -u` to update them.

Test Suites: 2 failed, 177 passed, 179 total
Tests:       2 failed, 1669 passed, 1671 total
Snapshots:   1 failed, 594 passed, 595 total
Time:        56.685s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Additional context**
Windows 10 x64
node v10.15.0
Yarn 1.10.1

**Comment by rarkins** [comment]
Please paste the failing tests into a comment below so I can take a look

**Comment by KonstantinKurganov** [comment]
here it is
<details><summary>log</summary>

```
 FAIL  test/manager/pip_setup/extract.spec.js (11.313s)
  ● lib/manager/pip_setup/extract › extractPackageFile() › returns found deps

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "lib/manager/pip_setup/extract extractPackageFile() returns found deps 1".

    - Snapshot
    + Received

    @@ -48,22 +48,10 @@
            "depName": "celery",
            "lineNumber": 36,
            "purl": "pkg:pypi/celery",
          },
          Object {
    -       "currentValue": ">=0.11,<2.0",
    -       "depName": "flask",
    -       "lineNumber": 48,
    -       "purl": "pkg:pypi/flask",
    -     },
    -     Object {
    -       "currentValue": ">=1.4,<2.0",
    -       "depName": "blinker",
    -       "lineNumber": 49,
    -       "purl": "pkg:pypi/blinker",
    -     },
    -     Object {
            "currentValue": ">=1.7",
            "depName": "logging_tree",
            "lineNumber": 39,
            "purl": "pkg:pypi/logging_tree",
          },
    @@ -89,7 +77,19 @@
            "currentValue": ">=1.10,<2.0",
            "depName": "django",
            "lineNumber": 45,
            "purl": "pkg:pypi/django",
          },
    +     Object {
    +       "currentValue": ">=0.11,<2.0",
    +       "depName": "flask",
    +       "lineNumber": 48,
    +       "purl": "pkg:pypi/flask",
    +     },
    +     Object {
    +       "currentValue": ">=1.4,<2.0",
    +       "depName": "blinker",
    +       "lineNumber": 49,
    +       "purl": "pkg:pypi/blinker",
    +     },
        ],
      }

      23 |       expect(
      24 |         await extractPackageFile(content, packageFile, config)
    > 25 |       ).toMatchSnapshot();
         |         ^
      26 |     });
      27 |     it('should return null for invalid file', async () => {
      28 |       expect(

      at Object.toMatchSnapshot (test/manager/pip_setup/extract.spec.js:25:9)

 › 1 snapshot failed.
 PASS  test/config/index.spec.js (15.933s)
 PASS  test/platform/github/index.spec.js (5.558s)
 FAIL  test/datasource/maven.spec.js (19.862s)
  ● datasource/maven › getPkgReleases › should return all versions of a specific library if a repository fails

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      85 |     });
      86 |
    > 87 |     it('should return all versions of a specific library if a repository fails', async () => {
         |     ^
      88 |       const releases = await datasource.getPkgReleases({
      89 |         ...config,
      90 |         purl:

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Suite.it (test/datasource/maven.spec.js:87:5)
      at Suite.describe (test/datasource/maven.spec.js:38:3)
      at Object.describe (test/datasource/maven.spec.js:28:1)
```
</details>

**Comment by rarkins** [comment]
If you run `yarn jest datasource/maven` again do the tests pass? It looks like it could be an ephemeral error due to timeout. The first error is actually the same as in #3131

**Comment by KonstantinKurganov** [comment]
Still having this error on master branch
Here is my log 
<details><summary>log</summary>

```
yarn run v1.10.1
$ yarn clean-cache && cross-env NODE_ENV=test LOG_LEVEL=fatal jest datasource/maven
$ node bin/clean-cache.js
 FAIL  test/datasource/maven.spec.js (23.503s)
  datasource/maven
    getPkgReleases
      √ should return empty if library is not found (42ms)
      √ should simply return all versions of a specific library (61ms)
      √ should return versions in all repositories for a specific library (30ms)
      √ should return all versions of a specific library for http repositories (37ms)
      × should return all versions of a specific library if a repository fails (5181ms)
      √ should throw registry-failure if maven-central fails (3109ms)
      √ should return all versions of a specific library if a repository fails because invalid protocol (8ms)
      √ should return all versions of a specific library if a repository fails because invalid metadata file is found in another repository
(9ms)
      √ should return all versions of a specific library if a repository fails because a metadata file is not xml (1ms)
      √ should return all versions of a specific library if a repository does not end with / (4ms)
      √ should return null if no repositories defined (2ms)

  ● datasource/maven › getPkgReleases › should return all versions of a specific library if a repository fails

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      85 |     });
      86 |
    > 87 |     it('should return all versions of a specific library if a repository fails', async () => {
         |     ^
      88 |       const releases = await datasource.getPkgReleases({
      89 |         ...config,
      90 |         purl:

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Suite.it (test/datasource/maven.spec.js:87:5)
      at Suite.describe (test/datasource/maven.spec.js:38:3)
      at Object.describe (test/datasource/maven.spec.js:28:1)


=============================== Coverage summary ===============================
Statements   : 6.16% ( 563/9140 )
Branches     : 1.79% ( 83/4638 )
Functions    : 3.55% ( 37/1041 )
Lines        : 6.23% ( 561/8998 )
================================================================================
Test Suites: 1 failed, 1 total
Tests:       1 failed, 10 passed, 11 total
Snapshots:   0 total
Time:        48.117s
Ran all test suites matching /datasource\\maven/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
</details>

**Comment by KonstantinKurganov** [comment]
@rarkins the same output!

**Comment by rarkins** [comment]
It seems like there's something specific about this one test that is failing in your environment, potentially for others (maybe even all Windows) but I have not heard anyone else. Will leave this open until we work out what it is.

**Comment by Dmitry9** [comment]
Same issue
![fail](https://user-images.githubusercontent.com/22542906/53017280-46235d80-3458-11e9-9032-33336571a8de.png)

**Additional context**
x86_64 x86_64 x86_64 GNU/Linux NAME=Fedora VERSION="27 (Twenty Seven)"
node v10.13.0
Yarn v1.13.0

**Comment by rarkins** [comment]
@Dmitry9 it's actually a different test that's failing for you and hence not the same issue. In your case, can you make sure your system is running Python 3.7 and try again? You need either Python <3.4 with `mock` manually installed, or you can just use the latest Python and it should work out of the box.

**Comment by rarkins** [comment]
Looks like we are kind of tracking two separate issues here.

The first is pip extraction, which requires the `mock` python library to work. Mock comes preloaded with Python 3.7 but you need to manually install it where Python can find it if you are using < Python 3.4. I recommend updating the system Renovate runs in to use Python 3.7. This problem is not OS-specific.

For the Maven test, I still have no idea why it's failing, and if it fails for everyone on Windows or it's specific to @KonstantinKurganov .

**Comment by Dmitry9** [comment]
@rarkins you are correct - when using python 3.7 all tests are passed.
![37](https://user-images.githubusercontent.com/22542906/53035686-ac22db80-347e-11e9-9111-8b34b3d822aa.png)
![renores](https://user-images.githubusercontent.com/22542906/53035755-cf4d8b00-347e-11e9-9c02-f13324a9e522.png)

**Comment by ViceIce** [comment]
The [docs](https://github.com/renovatebot/renovate/blob/master/docs/local-development.md) should mention, that we need python.

**Comment by ViceIce** [comment]
And you should not have the following npm configs:
```ini
registry=https://custom.server.de/
always-auth=true
```

Because some tests require default npm behavior. Or you make shure, that your custom registry fully mirrors the default registry and you have saved password /token to login.

**Comment by ViceIce** [comment]
I do not see any test failures on windows, so i think this can be closed.

@KonstantinKurganov do you see this error with latest master? Which nodejs version you are currently using?
