### ISSUE TITLE
copier: Renovate does not support git+https

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#31516]
### Discussed in https://github.com/renovatebot/renovate/discussions/31454

<div type='discussions-op-text'>

<sup>Originally posted by **reitzig** September 18, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Bitbucket Data Center v8.19.6; Renovate 38.82.1

### Please tell us more about your question or problem

Copier supports source paths with several Git-related protocols:

> If Copier doesn't detect your remote URL as a Git repository, make sure it starts with one of `git+https://`, `git+ssh://`, `git@` or `git://`, or it ends with `.git`.
> https://copier.readthedocs.io/en/stable/generating/

Running Renovate on a repository that contains a `.copier-answers.yaml` with a ` git+https`-URL, we get:

```
git: 'remote-git+https' is not a git command. See 'git --help'.\n
```

I can reproduce a similar error message with my local Git:

```bash
🐧❯ git --version
git version 2.25.1

🐧❯ git clone git+https://bitbucket.some-org/scm/some-project/some-template.git
Cloning into 'some-template'...
fatal: unable to find remote helper for 'git+https'
```

It seems as if Renovate forwarded the URL it found in `.copier-answers.yaml` to `git`; in this case, it would need to remove a `git+` prefix for that to work.

#### Notes

- In our case, plain `https://(...).git` works.
- We would _like_ to use `ssh://` but our Renovate setup uses HTTPS to access our Bitbucket; an automagic mapping would be great (but finicky since Bitbucket HTTPS vs SSH URLs have different structure).

#### References

- [reitzig/reproduction-renovate-31454](https://github.com/reitzig/reproduction-renovate-31454)
- [renovatebot/renovate#29215](https://github.com/renovatebot/renovate/pull/29215/files#diff-03d01a2ea6b7b14347e9a542cc5e5b1ebe808183d78639524716a4de268365d7) -- introduces copier support; tests only extraction of `https`.
- [copier documentation](https://copier.readthedocs.io/en/stable/generating/)

### Logs (if relevant)

<details><summary>Logs</summary>

```
DEBUG: Datasource unknown error (repository=some-project/some-repo, baseBranch=doc/bounded-contexts)
       "datasource": "git-tags",
       "packageName": "git+https://bitbucket.some-org/scm/some-project/some-template.git",
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "git+https://bitbucket.some-org/scm/some-project/some-template.git"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "git: 'remote-git+https' is not a git command. See 'git --help'.\n",
         "stack": "Error: git: 'remote-git+https' is not a git command. See 'git --help'.\n\n    at Object.action (/usr/local/renovate/node_modules/.pnpm/simple-git@3.26.0/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/usr/local/renovate/node_modules/.pnpm/simple-git@3.26.0/node_modules/simple-git/src/lib/plugins/plugin-store.ts:54:29)\n    at /usr/local/renovate/node_modules/.pnpm/simple-git@3.26.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/local/renovate/node_modules/.pnpm/simple-git@3.26.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:121:14)\n    at GitExecutorChain.<anonymous> (/usr/local/renovate/node_modules/.pnpm/simple-git@3.26.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:97:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/renovate/node_modules/.pnpm/simple-git@3.26.0/node_modules/simple-git/dist/cjs/index.js:52:24)"
       }
DEBUG: Failed to look up git-tags package git+https://bitbucket.some-org/scm/some-project/some-template.git (repository=some-project/some-repo, baseBranch=doc/bounded-contexts, packageFile=test-bc-a/.copier-answers.yml, 

```

</details>
</div>

**Comment by reitzig** [comment]
> In our case, plain https://(...).git works.

I have to retract that statement; Renovate does not seem to forward HTTPS credentials to copier, or at least not in a way that copier understands:

```
Command failed: copier update --skip-answered --defaults --answers-file .copier-answers.yml --vcs-ref v2.2.0
Traceback (most recent call last):

<snip>

plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | /usr/bin/git clone --no-checkout https://bitbucket.some.org/scm/some-project/some-repo.git /tmp/copier.vcs.clone.trm6f1wz --filter=blob:none
Stderr:       | Cloning into '/tmp/copier.vcs.clone.trm6f1wz'...
              | fatal: could not read Username for 'https://bitbucket.some.org': No such device or address
```

Funny enough, we end up with "not quite empty" PRs:
![image](https://github.com/user-attachments/assets/4f921966-f9dd-4f8a-ab17-6d454c6ea8ca)

Anyway. Is credential forwarding part of this ticket, anyway, or would you like a separate discussion/issue, @rarkins ?

**Comment by mohammad-ahmadi1** [comment]
Yes, I am getting the same error. I am using `renovate/renovate:38.124.4`
```
"err": {
         "message": "Schema error",
         "stack": "ZodError: Schema error\n    at Object.get error [as error] (/usr/local/renovate/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:55:31)\n    at ZodPipeline.parse (/usr/local/renovate/node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/types.js:160:22)\n    at Object.extractPackageFile (/usr/local/renovate/lib/modules/manager/copier/extract.ts:12:32)\n    at extractPackageFile (/usr/local/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/usr/local/renovate/lib/workers/repository/extract/manager-files.ts:58:43)\n    at /usr/local/renovate/lib/workers/repository/extract/index.ts:57:28\n    at async Promise.all (index 0)\n    at extractAllDependencies (/usr/local/renovate/lib/workers/repository/extract/index.ts:54:26)\n    at extract (/usr/local/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at extractDependencies (/usr/local/renovate/lib/workers/repository/process/index.ts:155:26)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:71:9)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:202:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:187:7)\n    at /usr/local/renovate/lib/renovate.ts:18:22",
         "issues": {"_src_path": "Invalid url"}
       }
```

**Comment by jankatins** [comment]
Just FYI (not sure if this should be a new issue or if this is related to this one), but having an url with git@ at the start also fails: `git@ssh.dev.azure.com:v3/org-name/Project%20Name/repo-name` (there is a space in the project name which ends up as %20 in the url)

```
DEBUG: Parsing Copier answers YAML failed (repository=MCCS nextgen/bla-service, packageFile=.copier-answers.yml)
       "err": {
         "message": "Schema error",
         "stack": "ZodError: Schema error\n    at Object.get error [as error] (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/zod/lib/types.js:55:31)\n    at ZodPipeline.parse (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/zod/lib/types.js:131:22)\n    at Object.extractPackageFile (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/modules/manager/copier/extract.ts:12:32)\n    at extractPackageFile (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:58:43)\n    at /home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/workers/repository/extract/index.ts:57:28\n    at async Promise.all (index 1)\n    at extractAllDependencies (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/workers/repository/extract/index.ts:54:26)\n    at extract (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/workers/repository/process/extract-update.ts:159:28)\n    at extractDependencies (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/workers/repository/process/index.ts:158:26)\n    at Object.renovateRepository (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/workers/repository/index.ts:71:9)\n    at attributes.repository (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/workers/global/index.ts:206:11)\n    at start (/home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/workers/global/index.ts:191:7)\n    at /home/vsts/.npm/_npx/05eeecd92f4e18e0/node_modules/renovate/lib/renovate.ts:19:22",
         "issues": {"_src_path": "Invalid url"}
       }

**Comment by reitzig** [comment]
We accidentally found a workaround. 

I don't know since when, but _today_ Renovate -- presumably the copier manager? -- _does_ add some Git configuration as environment variables, something like 

```
"GIT_CONFIG_KEY_3": "url.https://**redacted**@bitbucket.some.org/scm/.insteadOf",
"GIT_CONFIG_VALUE_3": "ssh://**redacted**@bitbucket.some.org:7999/",
"GIT_CONFIG_KEY_4": "url.https://**redacted**@bitbucket.some.org/scm/.insteadOf",
"GIT_CONFIG_VALUE_4": "ssh://**redacted**@bitbucket.some.org:7999/",
"GIT_CONFIG_KEY_5": "url.https://**redacted**@bitbucket.some.org/scm/.insteadOf",
"GIT_CONFIG_VALUE_5": "https://bitbucket.some.org/scm/",
```

which I interpret as: "if we can make either of HTTPs or SSH work, use that" (which may be completely off, I'm not familiar with the `url.<url>.insteadOf` config of Git).

Whatever the exact semantics of this trio of config settings, it works (for us). 

We now have both HTTPS _and_ SSH credentials configured in our Renovate deployment, and I can't tell which is ultimately being used by `copier`, but it _does_ run successfully. _If_ the HTTPS credentials were used, this ticket would be fixed; if the SSH credentials were used, that's a workaround.

**Comment by reitzig** [comment]
Can confirm that lookup seems to be successful on the reproduction example (alas, there are no new versions available):

> DEBUG: packageFiles with updates
> ```json
> {
>   "baseBranch": "main",
>   "config": {
>     "copier": [
>       {
>         "deps": [
>           {
>             "datasource": "git-tags",
>             "depName": "git+https://github.com/copier-org/autopretty.git",
>             "packageName": "https://github.com/copier-org/autopretty.git",
>             "depType": "template",
>             "currentValue": "v0.4.3",
>             "updates": [],
>             "versioning": "pep440",
>             "warnings": [],
>             "sourceUrl": "https://github.com/copier-org/autopretty",
>             "currentVersion": "v0.4.3",
>             "fixedVersion": "v0.4.3"
>           }
>         ],
>         "packageFile": ".copier-answers.autopretty.yml"
>       }
>     ],
> ```
➡️ run [019cea97-d839-7e7e-935d-2f4cb13873c3](https://developer.mend.io/github/reitzig/reproduction-renovate-31454/-/job/019cea97-d839-7e7e-935d-2f4cb13873c3)

Thanks!
