### ISSUE TITLE
Support SSH keys as secrets

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#32083]
### Describe the proposed change(s).

Sometimes users have git dependencies - including submodules - which are authenticatable only using ssh and not https. We should find a way for users to provide a private SSH key to Renovate.

**Comment by viceice** [comment]
I think the easiest solution is to start the key agent, add the keys, process repo (pass key agent env as required), stop agent.

**Comment by Crocmagnon** [comment]
Hello 👋🏻

As I understand from this issue, currently renovate doesn't support ssh submodules. Is that correct?

We currently use ssh submodules with a `.gitmodules` similar to this on a self hosted bitbucket instance:
```
[submodule ".sub"]
	path = .sub
	url = ssh://git@bitbucket.example.com:7999/PROJECT/repo.git
```

We enabled git submodules with:
```json
  "git-submodules": {
    "enabled": true
  }
```

We observed in renovate logs that it tried to pull the dependency using https instead of ssh. However, https access for SCM has been disabled by the instance admins:
```
{"name":"renovate","hostname":"xxx","pid":204,"level":50,"logContext":"xxx","repository":"PROJECT/repo2","baseBranch":"develop","currentDigest":"xxx","currentValue":"master","datasource":"git-refs","packageName":"https://bitbucket.example.com/scm/PROJECT/repo.git","followTag":null,"packageFile":".gitmodules","pinDigests":false,"rollbackPrs":false,"updatePinnedDependencies":true,"unconstrainedValue":false,"err":{"task":{"commands":["ls-remote","https://**redacted**@bitbucket.example.com/scm/PROJECT/repo.git"],"format":"utf-8","parser":"[function]"},"message":"fatal: remote error: SCM access over HTTP(S) has been disabled\nSCM access over HTTP(S) has been disabled\n","stack":"Error: fatal: remote error: SCM access over HTTP(S) has been disabled\nSCM access over HTTP(S) has been disabled\n\n    at Object.action (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/plugins/plugin-store.ts:54:29)\n    at /usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:121:14)\n    at GitExecutorChain.<anonymous> (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:97:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/cjs/index.js:52:24)"},"msg":"lookupUpdates error","time":"2024-12-12T09:51:08.838Z","v":0}
```

There's an additional log:
```
{"name":"renovate","hostname":"687faa362b5d","pid":204,"level":20,"logContext":"ENAXv4o1WDs7f2iw5IT86","repository":"PRISMCMDB/cmdb-api","baseBranch":"develop","msg":"Found hostRules username and password for url https://bitbucket.example.com/scm/PROJECT/repo.git","time":"2024-12-12T09:51:08.260Z","v":0}
```

I've confirmed with the instance admins that they indeed have credentials setup for API calls to get information on pull requests.

**Comment by rarkins** [comment]
@Crocmagnon that is correct - ssh submodules aren't supported unless they also work over https.

How does Renovate successfully clone your repo to begin with? e.g. have you mounted an SSH key into the Renovate container and got it to work that way?

**Comment by Crocmagnon** [comment]
> have you mounted an SSH key into the Renovate container and got it to work that way?

That's correct.

**Comment by rarkins** [comment]
In that case this issue is not for you. What you need is for git submodules to be able to reuse an existing SSH key, so please start a new discussion

**Comment by bryansoftdev** [comment]
> I think the easiest solution is to start the key agent, add the keys, process repo (pass key agent env as required), stop agent.

Would be nice to have this option available for the hosted apps too

**Comment by mahmoud-mahdi** [comment]
Hi,

is there any plans for this feature in the near future?

**Comment by FlippingBinary** [comment]
For what it's worth, I may have a way to get this to work if your keys are in an ssh agent and you have an `SSH_AUTH_SOCK` env var that points to its socket. Use [`customEnvVariables`](https://docs.renovatebot.com/self-hosted-configuration/#customenvvariables) to set `SSH_AUTH_SOCK` to that same value. I use this method when running renovate locally so the git subprocess can access the ssh agent where my commit signing key is located. As long as renovate isn't also configured to sign commits, it uses git's global settings. So, if ssh is failing just because it can't find your ssh agent, or your able to load your keys into an ssh agent, this method might work for you too.
