### ISSUE TITLE
(bitbucket-server) Error pruning branch: Cannot read property 'number' of null

### ISSUE THREAD

**Issue by ViceIce** [renovatebot/renovate#3228]
**What Renovate type are you using?**
Renovate CLI (Docker v14)

**Describe the bug**
The renovate branches are not deleted. And the following warning is logged.

**Did you see anything helpful in debug logs?**
```
WARN: Error pruning branch (repository=vsaf/icons, branch=renovate/configure)

[2019-02-18T07:22:04.223Z]        "err": {

[2019-02-18T07:22:04.223Z]          "message": "Cannot read property 'number' of null",

[2019-02-18T07:22:04.223Z]          "stack": "TypeError: Cannot read property 'number' of null\n    at Object.deleteBranch (/usr/src/app/lib/platform/bitbucket-server/index.js:263:28)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"

[2019-02-18T07:22:04.223Z]        }

[2019-02-18T07:22:04.223Z]  WARN: Error pruning branch (repository=vsaf/icons, branch=renovate/pin-dependencies)

[2019-02-18T07:22:04.223Z]        "err": {

[2019-02-18T07:22:04.223Z]          "message": "Cannot read property 'number' of null",

[2019-02-18T07:22:04.223Z]          "stack": "TypeError: Cannot read property 'number' of null\n    at Object.deleteBranch (/usr/src/app/lib/platform/bitbucket-server/index.js:263:28)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"

[2019-02-18T07:22:04.223Z]        }
```

**To Reproduce**

1.  Create repository with bitbucket-server
2.  Configure `{"extends": ["config:base"]}`
3.  Merge oboarding pr

**Expected behavior**
The renovate branches should be deleted after merge.

**Comment by iamstarkov** [comment]
what are your Bitbucket server version?

**Comment by ViceIce** [comment]
I recently updated to 6.0.0

**Comment by iamstarkov** [comment]
that might be an issue

**Comment by iamstarkov** [comment]
bitbucket server adapter has been written with 5.x in mind

**Comment by ViceIce** [comment]
I will try to debug a little, maybe i can find the error.

**Comment by rarkins** [comment]
I found the problem, about to push a fix

**Comment by rarkins** [comment]
I could reproduce on 5.x
