### ISSUE TITLE
Proxy not working when accessing Docker registry

### ISSUE THREAD

**Issue by patrickmarabeas** [renovatebot/renovate#3284]
**What Renovate type are you using?**
Renovate Pro running in OpenShift

**Describe the bug**

Renovate does not appear to be using env vars `HTTP_PROXY` or `HTTPS_PROXY` when making requests for (at least) docker registry.

`/renovate/lib/datasource/docker/index.js`

Failing at:

```
await got(apiCheckUrl, { throwHttpErrors: false });
```

node script running `got('https://asia.gcr.io/v2/')` returns the same error.

Can curl the address from terminal successfully.

**Did you see anything helpful in debug logs?**

```
WARN: Error obtaining docker token (repository=######/######)
  "registry": "https://asia.gcr.io ",
  "dockerRepository": "######/######",
  "err": {
    "name": "RequestError",
    "code": "ENOTFOUND",
    "host": "asia.gcr.io",
    "hostname": "asia.gcr.io",
    "method": "GET",
    "path": "/v2/",
    "protocol": "https:",
    "url": "https://asia.gcr.io/v2/ ",
   
    ...

  },
  "message": "getaddrinfo ENOTFOUND asia.gcr.io asia.gcr.io:443",
  "stack": "RequestError: getaddrinfo ENOTFOUND asia.gcr.io asia.gcr.io:443\n    
at ClientRequest.request.once.error (/usr/src/app/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:178:14)\n    
at Object.onceWrapper (events.js:273:13)\n    at ClientRequest.emit (events.js:187:15)\n    
at ClientRequest.origin.emit.args (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    
at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    
at TLSSocket.emit (events.js:182:13)\n   
at emitErrorNT (internal/streams/destroy.js:82:8)\n    
at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    
at process._tickCallback (internal/process/next_tick.js:63:19)"
}
```

**Comment by rarkins** [comment]
This is actually a Pro issue, not CLI - so moving discussion to https://github.com/renovatebot/pro/issues/42
