### ISSUE TITLE
INFO: getReleaseList error with CAS as Gradle dependency

### ISSUE THREAD

**Issue by ChristianMurphy** [renovatebot/renovate#3289]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**

When looking up CAS dependencies `INFO: getReleaseList error` errors appear.
Issue appears to be related to a colon getting added to GitHub URL `https://api.github.com/repos/:Jasig/cas/releases?per_page=100`

**Did you see anything helpful in debug logs?**

```json
INFO: getReleaseList error (repository=:Jasig/cas, dependencies=org.jasig.cas:cas-server-extension-clearpass, branch=renovate/org.jasig.cas-cas-server-extension-clearpass-4.x)
       "err": {
         "name": "GitHubError",
         "hostname": "api.github.com",
         "method": "GET",
         "path": "/repos/:Jasig/cas/releases?per_page=100",
         "protocol": "https:",
         "url": "https://api.github.com/repos/:Jasig/cas/releases?per_page=100",
         "gotOptions": {
           "path": "/repos/:Jasig/cas/releases?per_page=100",
           "protocol": "https:",
           "hostname": "api.github.com",
           "hash": "",
           "search": "?per_page=100",
           "pathname": "/repos/:Jasig/cas/releases",
           "href": "https://api.github.com/repos/:Jasig/cas/releases?per_page=100",
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "headers": {
             "user-agent": "https://github.com/sindresorhus/gh-got",
             "accept": "application/vnd.github.v3+json",
             "accept-encoding": "gzip, deflate",
             "authorization": "** redacted **"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "baseUrl": "https://api.github.com/",
           "name": "GitHub",
           "platform": "github",
           "username": null,
           "password": null,
           "token": "{{redacted}}",
           "default": true,
           "method": "GET"
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "GitHub.com",
           "date": "Fri, 01 Mar 2019 22:55:37 GMT",
           "content-type": "application/json; charset=utf-8",
           "transfer-encoding": "chunked",
           "connection": "close",
           "status": "404 Not Found",
           "x-ratelimit-limit": "5000",
           "x-ratelimit-remaining": "3736",
           "x-ratelimit-reset": "1551484537",
           "x-oauth-scopes": "notifications, repo",
           "x-accepted-oauth-scopes": "repo",
           "x-github-media-type": "github.v3; format=json",
           "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type",
           "access-control-allow-origin": "*",
           "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
           "x-frame-options": "deny",
           "x-content-type-options": "nosniff",
           "x-xss-protection": "1; mode=block",
           "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
           "content-security-policy": "default-src 'none'",
           "content-encoding": "gzip",
           "x-github-request-id": "** redacted **"
         },
         "body": {
           "message": "Not Found",
           "documentation_url": "https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository"
         },
         "rateLimit": {
           "limit": 5000,
           "remaining": 3736,
           "reset": "2019-03-01T23:55:37.000Z"
         },
         "message": "Not Found (404)",
         "stack": "GitHubError: Not Found (404)\n    at EventEmitter.emitter.on (/home/christian/.nvm/versions/node/v11.10.0/lib/node_modules/renovate/node_modules/got/source/as-promise.js:74:19)\n    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
       }
```

**To Reproduce**

```bash
renovate --token {token} Jasig/uPortal-start --git-fs=https
```

**Expected behavior**
Releases should be looked up at <https://api.github.com/repos/Jasig/cas/releases?per_page=100>

**Comment by rarkins** [comment]
Debugged:
![image](https://user-images.githubusercontent.com/6311784/53897435-68ab9e00-4036-11e9-9e48-b13e927fc4a0.png)

`scm:git@github.com:Jasig/cas.git`

**Comment by rarkins** [comment]
Solution: we should apply `sourceUrl` validation and massaging inside `lib/datasource/index.js` instead of relying on each datasource to do it themselves.

**Comment by donotello** [comment]
Reproduced with `testCompile 'com.codeborne:selenide:5.1.0'` in `build.gradle` while testing bitbucket server integration with [one of my test projects](https://github.com/donotello/web_automation_java):

```
INFO: getReleaseList error (repository=:codeborne/selenide, dependencies=com.codeborne:selenide, branch=renovate/com.codeborne-selenide-5.x)
       "err": {
         "name": "GitHubError",
         "hostname": "api.github.com",
         "method": "GET",
         "path": "/repos/:codeborne/selenide/releases?per_page=100",
         "protocol": "https:",
         "url": "https://api.github.com/repos/:codeborne/selenide/releases?per_page=100",
...
```

**Comment by Dmitry9** [comment]
in progress

**Comment by Dmitry9** [comment]
env var RENOVATE_TOKEN={MY_TOKEN}
verified
When I try to recreate with

```shell
$ node lib/renovate Jasig/uPortal-start --log-level=debug > debug.log
```
In debug.log I see:
```
WARN: Found gradle wrapper (gradlew) in the project, but --git-fs is not enabled, not using it. (repository=Jasig/uPortal-start)
```
Then renovate tries to execute
```shell
$ gradle --init-script renovate-plugin.gradle renovate
```
It fails. So I changed `renovate/lib/manager/gradle/index.js:84` from
```javascript
const cmd = await getGradleCommandLine(config);
```
to
```javascript
const cmd = await getGradleCommandLine(config) + '--stacktrace';
```
and logged error.
Then in debug.log I see:
```
DEBUG:  (repository=Jasig/uPortal-start)
       "code": 1,
       "childProcess": {},
       "stdout": "Parallel execution is an incubating feature.\n:buildSrc:compileJava NO-SOURCE\n:buildSrc:compileGroovy NO-SOURCE\n:buildSrc:processResources NO-SOURCE\n:buildSrc:classes UP-TO-DATE\n:buildSrc:jar UP-TO-DATE\n:buildSrc:assemble UP-TO-DATE\n:buildSrc:compileTestJava NO-SOURCE\n:buildSrc:compileTestGroovy NO-SOURCE\n:buildSrc:processTestResources NO-SOURCE\n:buildSrc:testClasses UP-TO-DATE\n:buildSrc:test NO-SOURCE\n:buildSrc:check UP-TO-DATE\n:buildSrc:build UP-TO-DATE\n",
       "stderr": "\nFAILURE: Build failed with an exception.\n\n* Where:\nInitialization script '/tmp/renovate/repos/github/Jasig/uPortal-start/renovate-plugin.gradle' line: 9\n\n* What went wrong:\nCould not find method register() for arguments [renovate, renovate_plugin_rij40xq18x05lfrl8d19cokh$_run_closure1$_closure3@7b489570] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 0s\n"
```

In `/tmp/renovate/repos/github/Jasig/uPortal-start/renovate-plugin.gradle` created [here](https://github.com/renovatebot/renovate/blob/master/lib/manager/gradle/gradle-updates-report.js#L7)

on line 9 (as above trace pointed out) I see:
```
tasks.register("renovate") {
```
From trace:
```
line: 9\n\n* What went wrong:\nCould not find method register() for arguments [renovate, renovate_plugin_rij40xq18x05lfrl8d19cokh$_run_closure1$_closure3@7b489570] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer
```

**Comment by ChristianMurphy** [comment]
@Dmitry9 Try
```sh
renovate --token {token} Jasig/uPortal-start --git-fs=https
```

**Comment by Dmitry9** [comment]
Thank you @ChristianMurphy, it helped.
Renovate called `sh gradle ...` instead of calling gradle binary directly and I saw a message: `23 gradle task build success`
Now I stuck at:
```
DEBUG: Obtaining docker registry token for library/openjdk using url https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/openjdk:pull
DEBUG: Obtaining docker registry token for library/openjdk using url https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/openjdk:pull
```
renovate freezes here. I suppose the server blocks me because before that I had a few attempts that went beyond this step. 

This naive approach doesn't work (replaced [line](https://github.com/renovatebot/renovate/blob/master/lib/datasource/index.js#L91)):

```javascript
const dep = await datasources[datasource].getPkgReleases(config);
if (dep.sourceUrl.includes('github.com:Jasig/basiclti-portlet')) {
    dep.sourceUrl = dep.sourceUrl.replace('github.com:', 'github.com/');
}
```
Some other repos depend on that colon (I saw debug log complained regarding other repo failed lookup but https://github.com/Jasig/basiclti-portlet undergone lookup without failure. Unfortunately I have no debug.log to paste because it was overridden by attempt `Obtaining docker registry token for library/openjdk ...`).
I suspect `dependency.dependencyUrl` [here](https://github.com/renovatebot/renovate/blob/master/lib/datasource/maven/index.js#L17) should be validated against GitHub user API whether or not repository name is including the semicolon

**Comment by rarkins** [comment]
Should be fixed by https://github.com/renovatebot/renovate/commit/2e7e36bb5a063077cd27744d1860f25f0ae03ddd
