### ISSUE TITLE
No space left on device error when cloning repository

### ISSUE THREAD

**Issue by ronnylt** [renovatebot/renovate#3449]
**What Renovate type are you using?**

Renovate GitHub App

**Describe the bug**
````
INFO: Renovating repository
DEBUG: Using localDir: /mnt/renovate/gh/xxxx/xxxx
DEBUG: initRepo("xxx/xxx")
DEBUG: Setting hostRule
{
  "config": {
    "name": "GitHub",
    "endpoint": "https://api.github.com/",
    "platform": "github",
    "username": null,
    "password": null,
    "token": "***********",
    "default": true
  }
}
INFO: Authenticated as user: renovate[bot]
INFO: Using renovate version: 14.57.1
DEBUG: xxx/xxx owner = xxx
DEBUG: xx/xxx default branch = master
DEBUG: Enabling Git FS
INFO: Initialising git repository into /mnt/renovate/gh/xxx/xx
DEBUG: git clone error
{
  "err": {
    "message": "Cloning into '.'...\nfatal: write error: No space left on device\nfatal: index-pack failed\n",
    "stack": "Error: Cloning into '.'...\nfatal: write error: No space left on device\nfatal: index-pack failed\n\n    at /home/ubuntu/renovateapp/node_modules/simple-git/promise.js:21:26\n    at Git. (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:221:18)\n    at Function.Git.fail (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1478:18)\n    at fail (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1436:20)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1445:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
INFO: Platform error - skipping
INFO: Finished repository
```

**Did you see anything helpful in debug logs?**
See logs above

**Comment by rarkins** [comment]
Does it happen every time or was it a one off?

**Comment by ronnylt** [comment]
It happened the first time, so no the initial PR with the integration code was not created.

**Comment by ronnylt** [comment]
Job ID: #55222302

**Comment by ronnylt** [comment]
It seems to be working now. Thanks
