### ISSUE TITLE
Unknown error getting Docker labels

### ISSUE THREAD

**Issue by mastermatt** [renovatebot/renovate#3480]
**What Renovate type are you using?**
Renovate CLI (15.1.1)

**Describe the bug**
The majority of my repos (I think all with Docker) are printing this warning. Renovate is able to still properly process the repos, including Docket digest updates. I'm not sure if there is an actual problem or just a really noisy warning log.

**Did you see anything helpful in debug logs?**
```
WARN: Unknown error getting Docker labels (repository=...)
```
```json
"err": {
  "name": "HTTPError",
  "host": "index.docker.io",
  "hostname": "index.docker.io",
  "method": "GET",
  "path": "/v2/library/node/blobs/sha256:a9c1445cbd528d08e428ba06faa3c56743724ef0db67f52b8cb8ddf81e6f7f49",
  "protocol": "https:",
  "url": "https://index.docker.io/v2/library/node/blobs/sha256:a9c1445cbd528d08e428ba06faa3c56743724ef0db67f52b8cb8ddf81e6f7f49",
  "gotOptions": {
    "path": "/v2/library/node/blobs/sha256:a9c1445cbd528d08e428ba06faa3c56743724ef0db67f52b8cb8ddf81e6f7f49",
    "protocol": "https:",
    "slashes": true,
    "auth": null,
    "host": "index.docker.io",
    "port": null,
    "hostname": "index.docker.io",
    "hash": null,
    "search": null,
    "query": null,
    "pathname": "/v2/library/node/blobs/sha256:a9c1445cbd528d08e428ba06faa3c56743724ef0db67f52b8cb8ddf81e6f7f49",
    "href": "https://index.docker.io/v2/library/node/blobs/sha256:a9c1445cbd528d08e428ba06faa3c56743724ef0db67f52b8cb8ddf81e6f7f49",
    "headers": {
      "user-agent": "https://github.com/renovatebot/renovate",
      "authorization": "** redacted **",
      "accept-encoding": "gzip, deflate"
    },
    "hooks": {
      "beforeError": [],
      "init": [],
      "beforeRequest": [],
      "beforeRedirect": [],
      "beforeRetry": [],
      "afterResponse": []
    },
    "retry": {
      "methods": {},
      "statusCodes": {},
      "errorCodes": {},
      "maxRetryAfter": 10000
    },
    "decompress": true,
    "throwHttpErrors": true,
    "followRedirect": true,
    "stream": false,
    "form": false,
    "json": false,
    "cache": false,
    "useElectronNet": false,
    "gotTimeout": {
      "request": 10000
    },
    "method": "GET"
  },
  "statusCode": 400,
  "statusMessage": "Bad Request",
  "headers": {
    "x-amz-request-id": "89D0AA71B4EC8597",
    "x-amz-id-2": "6i1L/69b4JLcJr9K8/MZAn0+rY/vbrNflewe29mPacu/ZlhCkFFvFaU5lGHKPz2bPyqE8Y02gWY=",
    "content-type": "application/xml",
    "transfer-encoding": "chunked",
    "date": "Wed, 03 Apr 2019 13:52:47 GMT",
    "connection": "close",
    "server": "AmazonS3"
  },
  "body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Bearer ** redacted **</HostId></Error>",
  "message": "Response code 400 (Bad Request)",
  "stack": "HTTPError: Response code 400 (Bad Request)\n    at EventEmitter.emitter.on (/usr/local/lib/node_modules/renovate/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
}
```
> Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified

The odd thing is that it looks like an auth header is passed with no query params. So I don't understand the issue.

**To Reproduce**
Execute CLI against repo with docker files.

**Expected behavior**
No warnings?

**Screenshots**

**Additional context**
We call the CLI like so:
```
GITHUB_COM_TOKEN=${GH_COM_TOKEN} renovate --token ${GHE_TOKEN} --endpoint=${GHE_URL} ${REPO}
```

**Comment by mastermatt** [comment]
This seems to be related to recent work https://github.com/renovatebot/renovate/pull/2907 @rarkins @mikebryant

**Comment by rarkins** [comment]
@mastermatt you can ignore it because it only affects if we can detect the source repository for release notes, but I agree it's noisy and we should either (a) work out why it's failing for you, or (b) lower the log type

**Comment by mastermatt** [comment]
Let me know if I can provide more info to you for debugging (a).

**Comment by rarkins** [comment]
@mastermatt do you have anything special about your Docker setup either in Renovate config or in the Dockerfile? Or do you have default (unauthenticated) Docker config in Renovate and a regular Dockerfile like `FROM node:10.15.0` ?

**Comment by mastermatt** [comment]
Nothing special, as far as I can tell. As I mentioned, this is happening for all our repos and while we do have a few projects that use Docker images hosted in a private Artifactory instance, most just use public Docker Hub.
Here is an example.

```json
{
  "extends": [
    "config:js-app",
    "default:maintainLockFilesMonthly",
    "default:prHourlyLimitNone",
    "default:rebaseStalePrs"
  ],
  "labels": ["dependency"],
  "schedule": ["every 2 weeks of the year before 12:00 on Monday"],
  "timezone": "America/New_York",
  "packageRules": [
    {
      "depTypeList": ["devDependencies"],
      "groupName": ["Dev Dependencies"]
    }
  ]
}
```
```
FROM node:10-alpine@sha256:b85a3b0ef76f5543b3f467e8a25694e72594d2c2bfcf140fa584d4f40ace4130
MAINTAINER My Team

WORKDIR /usr/src/app
COPY . .

CMD ["node", "dist/server.js"]
```

**Comment by rarkins** [comment]
@mastermatt I can't reproduce the problem with your `Dockerfile` and config in a regular repo: https://github.com/renovate-tests/docker10

```
 INFO: Renovating repository (repository=renovate-tests/docker10)
 INFO: Authenticated as user: renovate-tests (repository=renovate-tests/docker10)
 INFO: Using renovate version: 0.0.0-semantic-release (repository=renovate-tests/docker10)
 INFO: Repository config (repository=renovate-tests/docker10)
       "configFile": "renovate.json",
       "config": {
         "extends": [
           "config:js-app",
           "default:maintainLockFilesMonthly",
           "default:prHourlyLimitNone",
           "default:rebaseStalePrs"
         ],
         "labels": ["dependency"],
         "schedule": ["every 2 weeks of the year before 12:00 on Monday"],
         "timezone": "America/New_York",
         "packageRules": [
           {"depTypeList": ["devDependencies"], "groupName": ["Dev Dependencies"]}
         ]
       }
 INFO: Found dockerfile package files (repository=renovate-tests/docker10)
 INFO: Processing 1 branch: renovate/node-10-alpine (repository=renovate-tests/docker10)
 INFO: Skipping branch creation as not within schedule (repository=renovate-tests/docker10, dependencies=node, branch=renovate/node-10-alpine)
 INFO: Request stats (repository=renovate-tests/docker10)
       "rateLimit": 5000,
       "requestCount": 10,
       "rateLimitRemaining": 4922
 INFO: Finished repository (repository=renovate-tests/docker10)
 INFO: Renovate finished
```

**Comment by mastermatt** [comment]
This is very odd indeed.
I can run Renovate via cli from my dev machine (while on our VPN) and not get the error, however, when I have have our Jenkins CI run the same command on the same network, it logs the error.
I've done everything I can think of to remove variables between the two cases.

Thanks for your time @rarkins, but I'm going to shelve this for now. I've already spent too much time on it.

**Comment by rarkins** [comment]
That’s really strange. Is there possibly any cache/proxy in between that might not support the labels api query?

I’ll close for now, we can reopen later if any ideas.
