### ISSUE TITLE
Spaces in Azure DevOps project name results in bad url

### ISSUE THREAD

**Issue by hillerstorm** [renovatebot/renovate#3581]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
If a project name in Azure DevOps has spaces in it, a bad url will be created for cloning (not replacing spaces with `%20`) and git errors out with a bad request.

**Did you see anything helpful in debug logs?**
```
TRACE: getProjectAndRepo(Ecommerce 3.0/Blk.Auth) (repository=Ecommerce 3.0/Blk.Auth)
DEBUG: Repository details (repository=Ecommerce 3.0/Blk.Auth)
       "repositoryDetails": {
         "id": "53e3944f-f8b6-420f-b16d-02791a09c1f8",
         "name": "Blk.Auth",
         "url": "https://awd-develop.visualstudio.com/3a41ab3d-ed0a-47e2-99b7-cf44567e0909/_apis/git/repositories/53e3944f-f8b6-420f-b16d-02791a09c1f8",
         "project": {
           "id": "3a41ab3d-ed0a-47e2-99b7-cf44567e0909",
           "name": "Ecommerce 3.0",
           "url": "https://awd-develop.visualstudio.com/_apis/projects/3a41ab3d-ed0a-47e2-99b7-cf44567e0909",
           "state": "wellFormed",
           "revision": 146,
           "visibility": 0,
           "lastUpdateTime": "2019-04-05T16:18:45.657Z"
         },
         "defaultBranch": "refs/heads/develop",
         "size": 185397,
         "remoteUrl": "https://awd-develop.visualstudio.com/DefaultCollection/Ecommerce%203.0/_git/Blk.Auth",
         "sshUrl": "AWD-Develop@vs-ssh.visualstudio.com:v3/AWD-Develop/Ecommerce%203.0/Blk.Auth",
         "webUrl": "https://awd-develop.visualstudio.com/DefaultCollection/Ecommerce%203.0/_git/Blk.Auth"
       }
DEBUG: Ecommerce 3.0/Blk.Auth owner = ?owner? (repository=Ecommerce 3.0/Blk.Auth)
DEBUG: Ecommerce 3.0/Blk.Auth default branch = develop (repository=Ecommerce 3.0/Blk.Auth)
TRACE: The refs/heads/ name should have started with 'refs/heads/' but it didn't. (develop) (repository=Ecommerce 3.0/Blk.Auth)
 INFO: Initialising git repository into /var/folders/d1/dq3r2b1n1bn11nql5nnf1f600000gn/T/renovate/repos/azure/Ecommerce 3.0/Blk.Auth (repository=Ecommerce 3.0/Blk.Auth)
DEBUG: git clone error (repository=Ecommerce 3.0/Blk.Auth)
       "err": {
         "message": "Cloning into '.'...\nfatal: unable to access 'https://**redacted**@awd-develop.visualstudio.com/Ecommerce 3.0/_git/Blk.Auth/': The requested URL returned error: 400\n",
         "stack": "Error: Cloning into '.'...\nfatal: unable to access 'https://**redacted**@awd-develop.visualstudio.com/Ecommerce 3.0/_git/Blk.Auth/': The requested URL returned error: 400\n\n    at /Users/**awd**/.nvm/versions/node/v11.10.0/lib/node_modules/renovate/node_modules/simple-git/promise.js:21:26\n    at Git.<anonymous> (/Users/**awd**/.nvm/versions/node/v11.10.0/lib/node_modules/renovate/node_modules/simple-git/src/git.js:221:18)\n    at Function.Git.fail (/Users/**awd**/.nvm/versions/node/v11.10.0/lib/node_modules/renovate/node_modules/simple-git/src/git.js:1480:18)\n    at fail (/Users/**awd**/.nvm/versions/node/v11.10.0/lib/node_modules/renovate/node_modules/simple-git/src/git.js:1438:20)\n    at /Users/**awd**/.nvm/versions/node/v11.10.0/lib/node_modules/renovate/node_modules/simple-git/src/git.js:1447:16\n    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
       }
 INFO: Platform error - skipping (repository=Ecommerce 3.0/Blk.Auth)
```

**To Reproduce**

1.  Create a project in Azure DevOps with a space in it (e.g. `New Project`)
2.  Create a repo in said project
3.  Configure Renovate to autodiscover (or just add the repo with project name manually)
4.  Run

**Expected behavior**
Should be able to clone the repos

**Comment by UnleashMayhem** [comment]
This also applies to repo names with spaces, which the fix did not affect. So for repo names, this bug still exists. 
Based on the [fix](https://github.com/renovatebot/renovate/pull/3582/commits/46aabce4028993f8c4b6bacb2341a9b3edf6830b#diff-92bb405708b1464cd562ad01107048d0), is it better to instead uri encode the entire url?

**Comment by hillerstorm** [comment]
@UnleashMayhem oh, I actually didn't even think repo names could have spaces... I had another solution in mind when doing this (which I didn't do because I wanted to touch as little code as I could) which was instead of building the repo manually, you can actually get a field from the `repo` details object in the same function called `remoteUrl` which contains the complete url to the repo in question.
https://github.com/Microsoft/azure-devops-node-api/blob/master/api/interfaces/GitInterfaces.ts#L2170
