### ISSUE TITLE
"poetry" missing in Renovate Docker image

### ISSUE THREAD

**Issue by dominik-bln** [renovatebot/renovate#3617]
**What Renovate type are you using?**
Renovate CLI v16.7.4

**Describe the bug**

Poetry is missing from the renovate/renovate image distributed via docker hub.

**Did you see anything helpful in debug logs?**

```bash
INFO: Branch needs creating (repository=alpha/alpha, dependencies=elasticsearch-dsl, branch=ren/elasticsearch-dsl-7.x)
 INFO: Running poetry via global poetry (repository=alpha/alpha, dependencies=elasticsearch-dsl, branch=ren/elasticsearch-dsl-7.x)
 WARN: Failed to update api/poetry.lock file (repository=alpha/alpha, dependencies=elasticsearch-dsl, branch=ren/elasticsearch-dsl-7.x)
       "err": {
         "name": "ChildProcessError",
         "code": 127,
         "childProcess": {},
         "stdout": "",
         "stderr": "/bin/sh: 1: poetry: not found\n",
         "message": "Command failed: poetry update --lock --no-interaction elasticsearch-dsl\n/bin/sh: 1: poetry: not found\n `poetry update --lock --no-interaction elasticsearch-dsl` (exited with error code 127)",
         "stack": "ChildProcessError: Command failed: poetry update --lock --no-interaction elasticsearch-dsl\n/bin/sh: 1: poetry: not found\n `poetry update --lock --no-interaction elasticsearch-dsl` (exited with error code 127)\n    at callback (/usr/src/app/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:189:13)\n    at maybeClose (internal/child_process.js:970:16)\n    at Socket.stream.socket.on (internal/child_process.js:389:11)\n    at Socket.emit (events.js:189:13)\n    at Pipe._handle.close (net.js:600:12)"
       }
 INFO: Branch created (repository=alpha/alpha, dependencies=elasticsearch-dsl, branch=ren/elasticsearch-dsl-7.x)
```

**To Reproduce**

Run docker hub renovate image on a repository containing a `pyproject.toml` and `poetry.lock` file.

**Expected behavior**

Renovate successfully updates the `poetry.lock` file.

**Comment by dominik-bln** [comment]
Truly impressive turnaround time. Thanks!
