### ISSUE TITLE
Ruby malformed version number string

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3703]
```
    "err": {
        "message": "Malformed version number string 6..1",
        "stack": "Error: Malformed version number string 6..1\n    at new GemVersion (/home/ubuntu/renovateapp/node_modules/@snyk/ruby-semver/lib/ruby/gem-version.js:200:13)\n    at Function.create (/home/ubuntu/renovateapp/node_modules/@snyk/ruby-semver/lib/ruby/gem-version.js:183:12)\n    at compare (/home/ubuntu/renovateapp/node_modules/@snyk/ruby-semver/lib/comparison.js:74:21)\n    at eq (/home/ubuntu/renovateapp/node_modules/@snyk/ruby-semver/lib/comparison.js:35:10)\n    at diff (/home/ubuntu/renovateapp/node_modules/@snyk/ruby-semver/lib/comparison.js:82:7)\n    at increment (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/ruby/version.js:40:13)\n    at increment (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/ruby/version.js:56:12)\n    at increment (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/ruby/version.js:56:12)\n    at ranges.map (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/ruby/strategies/bump.js:15:48)\n    at Array.map (<anonymous>)"
    },
    "currentValue": ">= 3.2, < 5.0",
    "rangeStrategy": "replace",
    "fromVersion": "4.0.2",
    "toVersion": "6.0.1",
    "msg": "getNewValue error",
```

**Comment by rarkins** [comment]
This a ruby semver bug, waiting for external fix.
