### ISSUE TITLE
`dist` folder missing in docker image

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/renovate#3713]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Had a few failures with renovate in the early hours (01:00 BST)
`/usr/src/app/dist` folder is missing

**Did you see anything helpful in debug logs?**
```sh
Running with gitlab-runner 11.10.1 (1f513601)
  on csl-runner 5Ayc1meZ
Using Docker executor with image renovate/renovate:latest ...
Pulling docker image renovate/renovate:latest ...
Using docker image sha256:dc95bd737db95991c82c7a1484efd3af3f7820541772285ac65bc6a8600733ef for renovate/renovate:latest ...
Running on runner-5Ayc1meZ-project-703-concurrent-0 via ip-a-b-c-d.eu-west-2.compute.internal...
$ git config --global http.sslVerify false; git config --global http.proxy http://host:port; git config --global https.proxy https://host:port;
Reinitialized existing Git repository in /builds/path/to/renovate/.git/
Fetching changes...
From https://hosts/path/to/renovate
 + 0d27b8c...d204cbe master     -> origin/master  (forced update)
Checking out d204cbe8 as master...

Skipping Git submodules setup
$ if [ ! -z "$REPOSITORY_LIST" ]; then # collapsed multi-line command
$ mkdir ~/.ssh
$ chmod 700 ~/.ssh
$ echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
$ chmod 644 ~/.ssh/known_hosts
$ echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
$ chmod 600 ~/.ssh/id_ed25519
$ ls -lah /usr/src/app/
total 388K
drwxrwxrwx.   5 root   root     85 May 15 17:52 .
drwxrwxrwx.   3 root   root     17 May  5 04:17 ..
drwxr-xr-x.   2 root   root     27 May 15 17:52 bin
drwxr-xr-x.  10 root   root    183 May 16 07:09 lib
drwxr-xr-x. 571 ubuntu ubuntu  16K May 16 07:09 node_modules
-rw-r--r--.   5 root   root   6.2K May 15 17:39 package.json
-rw-r--r--.   4 root   root   345K May 15 17:39 yarn.lock
$ LOG_LEVEL=${LOG_LEVEL:-fatal} node /usr/src/app/dist/renovate.js $ADDITIONAL_CONFIG
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/usr/src/app/dist/renovate.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
ERROR: Job failed: exit code 1
```

**To Reproduce**

Per the above example this is pulling renovate/renovate:latest as part of CI.

**Expected behavior**
Renovate Cli executed successfully

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
This likely happened because renovate/renovate@16 because tagged as "latest" on Docker. Two suggestions:

1. Pin your script to use a fixed major version of Renovate, e.g. renovate/renovate:17
2. Don't override the Renovate entrypoint (I assume that's what you're doing?). We don't guarantee that the entry point won't change between builds, even patches

If there's something about the Renovate image that forces you to override the entrypoint then let's address that separately

**Comment by adam-moss** [comment]
Ok, cool, that makes sense, pinning is easy enough.

Yes the entry point gets overridden, as I'm using GitLab CI and it expects to stream commands to a shell STDIN.  See https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image for reference.

```yaml
.renovate: &renovate
    stage: maintenance
    variables:
        RENOVATE_CONFIG_FILE: '$CI_PROJECT_DIR/config.js'
    <<: *executor-docker
    image:
        name: renovate/renovate:latest
        entrypoint: [""]
    before_script:
        - |
          if [ ! -z "$REPOSITORY_LIST" ]; then
              export ADDITIONAL_CONFIG="--force-cli --autodiscover=false $REPOSITORY_LIST"
          fi
    script:
        - mkdir ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - LOG_LEVEL=${LOG_LEVEL:-fatal} node /usr/src/app/dist/renovate.js $ADDITIONAL_CONFIG
```

The main driving force here is the injection of ssh credentials, so renovate can correctly process git+ssh type package definitions.

**Comment by rarkins** [comment]
It could be useful to try to make an automated way of doing that, but I can't think of anything easy for now. Anyway, closing this as it's not really a bug, but thanks for reporting.
