### ISSUE TITLE
Duplicated "Dependency deprecation warning" generated every Renovate run

### ISSUE THREAD

**Issue by dylang** [renovatebot/renovate#3844]
**What Renovate type are you using?**
Renovate CLI, Renovate GitHub App, or Renovate Pro?

Self hosted.

**Describe the bug**

Every time Renovate runs it is re-generating `Dependency deprecation warning` tickets. Over 2 days over 300 have been created.  

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

```
INFO: Authenticated as user: service-continuous-deliver (repository=reporting/reporting)
 INFO: Using renovate version: 18.5.5 (repository=reporting/reporting)
 INFO: Initialising git repository into /tmp/renovate/repos/github/reporting/reporting (repository=reporting/reporting)
 INFO: git clone completed (repository=reporting/reporting)
       "cloneSeconds": 4.4
 INFO: Setting git author (repository=reporting/reporting)
       "gitAuthor": {"name": "Renovate Bot", "email": "bot@renovateapp.com"}
 WARN: getGraphqlIssues error (repository=reporting/reporting)
       "query": "\n  query {\n    repository(owner: \"reporting\", name: \"reporting\") {\n      issues(first: 100, after:null, orderBy: {field: UPDATED_AT, direction: DESC}, filterBy: {createdBy: \"service-continuous-deliver\"}) {\n        pageInfo {\n          startCursor\n          hasNextPage\n        }\n        nodes {\n          number\n          state\n          title\n          body\n        }\n      }\n    }\n  }\n  ",
       "err": {
         "name": "HTTPError",
         "hostname": "github.medallia.com",
         "method": "POST",
         "path": "/api/v3/graphql",
         "protocol": "https:",
         "url": "https://github.medallia.com/api/v3/graphql",
         "gotOptions": {
           "path": "/api/v3/graphql",
           "protocol": "https:",
           "hostname": "github.medallia.com",
           "hash": "",
           "search": "",
           "pathname": "/api/v3/graphql",
           "href": "https://github.medallia.com/api/v3/graphql",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/vnd.github.merge-info-preview+json",
             "accept-encoding": "gzip, deflate",
             "authorization": "** redacted **",
             "content-length": 424
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "hostType": "github",
           "baseUrl": "https://github.medallia.com/api/v3/",
           "body": "{\"query\":\"\\n  query {\\n    repository(owner: \\\"reporting\\\", name: \\\"reporting\\\") {\\n      issues(first: 100, after:null, orderBy: {field: UPDATED_AT, direction: DESC}, filterBy: {createdBy: \\\"service-continuous-deliver\\\"}) {\\n        pageInfo {\\n          startCursor\\n          hasNextPage\\n        }\\n        nodes {\\n          number\\n          state\\n          title\\n          body\\n        }\\n      }\\n    }\\n  }\\n  \"}",
           "method": "POST",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "GitHub.com",
           "date": "Thu, 30 May 2019 10:15:57 GMT",
           "content-type": "application/json; charset=utf-8",
           "transfer-encoding": "chunked",
           "connection": "close",
           "status": "404 Not Found",
           "x-oauth-scopes": "repo",
           "x-accepted-oauth-scopes": "repo",
           "x-github-enterprise-version": "2.16.6",
           "x-github-media-type": "github.merge-info-preview; format=json",
           "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type",
           "access-control-allow-origin": "*",
           "x-github-request-id": "299fbc2b-f714-4d6c-9fa9-46fcf86e8cc1",
           "strict-transport-security": "max-age=31536000; includeSubdomains",
           "x-frame-options": "deny",
           "x-content-type-options": "nosniff",
           "x-xss-protection": "1; mode=block",
           "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
           "content-security-policy": "default-src 'none'",
           "x-runtime-rack": "0.015392",
           "content-encoding": "gzip"
         },
         "body": "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/enterprise/2.16/v3\"}",
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/home/jenkins/workspace/medallia_renovate_master-EPD7JO65Z2D3QYCBQKHZL6Z44R23NJF7UMXKRHMCFIRCJPY7SRJA/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Repository config (repository=reporting/reporting)
       "configFile": "renovate.json",
       "config": {
         "$schema": "http://json.schemastore.org/renovate",
         "extends": [
           ":base",
           ":rebaseStalePrs",
           ":semanticCommits",
           ":automergeAll",
           ":maintainLockFilesWeekly",
           ":prHourlyLimitNone",
           "schedule:nonOfficeHours"
         ],
         "timezone": "America/New_York",
         "commitMessage": "{{commitMessagePrefix}} NGR-2825 - {{commitMessageAction}} {{commitMessageTopic}} {{commitMessageExtra}} {{commitMessageSuffix}}",
         "postUpdateOptions": ["yarnDedupeFewer"]
       }
 INFO: Found renovate config warnings (repository=reporting/reporting)
       "warnings": [
         {
           "depName": "Deprecation Warning",
           "message": "Direct editing of commitMessage is now deprecated. Please edit commitMessage's subcomponents instead."
         }
       ]
 INFO: Found dockerfile package files (repository=reporting/reporting)
 INFO: Found npm package files (repository=reporting/reporting)
 INFO: Docker Manifest is unknown (repository=reporting/reporting)
       "err": {
         "name": "HTTPError",
         "host": "virtual-docker.martifactory.io",
         "hostname": "virtual-docker.martifactory.io",
         "method": "GET",
         "path": "/v2/medallia/pdf-comp-service-base/manifests/latest",
         "protocol": "https:",
         "url": "https://virtual-docker.martifactory.io/v2/medallia/pdf-comp-service-base/manifests/latest",
         "gotOptions": {
           "path": "/v2/medallia/pdf-comp-service-base/manifests/latest",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "virtual-docker.martifactory.io",
           "port": null,
           "hostname": "virtual-docker.martifactory.io",
           "hash": null,
           "search": null,
           "query": null,
           "pathname": "/v2/medallia/pdf-comp-service-base/manifests/latest",
           "href": "https://virtual-docker.martifactory.io/v2/medallia/pdf-comp-service-base/manifests/latest",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "authorization": "** redacted **",
             "accept": "application/vnd.docker.distribution.manifest.v2+json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "cache-control": "must-revalidate",
           "content-encoding": "gzip",
           "content-type": "application/json",
           "date": "Thu, 30 May 2019 10:16:16 GMT",
           "docker-distribution-api-version": "registry/2.0",
           "server": "Artifactory/5.11.0",
           "x-artifactory-id": "43118b125dfc84416dbab36fe4bee0ebe87d79f8",
           "x-artifactory-node-id": "art-ip-10-251-0-165",
           "content-length": "151",
           "connection": "Close"
         },
         "body": "{\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"The named manifest is not known to the registry.\",\"detail\":{\"manifest\":\"medallia/pdf-comp-service-base\"}}]}",
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/home/jenkins/workspace/medallia_renovate_master-EPD7JO65Z2D3QYCBQKHZL6Z44R23NJF7UMXKRHMCFIRCJPY7SRJA/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       },
       "registry": "https://virtual-docker.martifactory.io",
       "dockerRepository": "medallia/pdf-comp-service-base",
       "tag": "latest"
 INFO: docker registry failure: failed to get manifest for tag (repository=reporting/reporting)
       "registry": "https://virtual-docker.martifactory.io",
       "dockerRepository": "medallia/pdf-comp-service-base",
       "tag": "latest"
 INFO: Docker Manifest is unknown (repository=reporting/reporting)
       "err": {
         "name": "HTTPError",
         "host": "virtual-docker.martifactory.io",
         "hostname": "virtual-docker.martifactory.io",
         "method": "GET",
         "path": "/v2/medallia/nodejs-base/manifests/latest",
         "protocol": "https:",
         "url": "https://virtual-docker.martifactory.io/v2/medallia/nodejs-base/manifests/latest",
         "gotOptions": {
           "path": "/v2/medallia/nodejs-base/manifests/latest",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "virtual-docker.martifactory.io",
           "port": null,
           "hostname": "virtual-docker.martifactory.io",
           "hash": null,
           "search": null,
           "query": null,
           "pathname": "/v2/medallia/nodejs-base/manifests/latest",
           "href": "https://virtual-docker.martifactory.io/v2/medallia/nodejs-base/manifests/latest",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "authorization": "** redacted **",
             "accept": "application/vnd.docker.distribution.manifest.v2+json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "cache-control": "must-revalidate",
           "content-encoding": "gzip",
           "content-type": "application/json",
           "date": "Thu, 30 May 2019 10:16:16 GMT",
           "docker-distribution-api-version": "registry/2.0",
           "server": "Artifactory/5.11.0",
           "x-artifactory-id": "c9e8b4fea8973f90ae6ce4807660d49b72baba76",
           "x-artifactory-node-id": "art-ip-10-251-0-146",
           "content-length": "145",
           "connection": "Close"
         },
         "body": "{\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"The named manifest is not known to the registry.\",\"detail\":{\"manifest\":\"medallia/nodejs-base\"}}]}",
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/home/jenkins/workspace/medallia_renovate_master-EPD7JO65Z2D3QYCBQKHZL6Z44R23NJF7UMXKRHMCFIRCJPY7SRJA/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       },
       "registry": "https://virtual-docker.martifactory.io",
       "dockerRepository": "medallia/nodejs-base",
       "tag": "latest"
 INFO: docker registry failure: failed to get manifest for tag (repository=reporting/reporting)
       "registry": "https://virtual-docker.martifactory.io",
       "dockerRepository": "medallia/nodejs-base",
       "tag": "latest"
 INFO: Found deprecationMessage (repository=reporting/reporting, dependency=postcss-cssnext)
 INFO: Found deprecationMessage (repository=reporting/reporting, dependency=babel-preset-es2015)
 INFO: Found deprecationMessage (repository=reporting/reporting, dependency=babel-preset-es2015)
 INFO: dependency is deprecated (repository=reporting/reporting)
       "depName": "postcss-cssnext",
       "deprecationMessage": "On registry `https://martifactory.io/api/npm/virtual-npm/`, the \"latest\" version (v3.1.0) of dependency `postcss-cssnext` has the following deprecation notice:\n\n`'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/`\n\nMarking the latest version of an npm package as deprecated results in the entire package being considered deprecated, so contact the package author you think this is a mistake.",
       "packageFiles": ["magic/reporting-webpack-config/package.json"]
 INFO: Issue created (repository=reporting/reporting)
 INFO: dependency is deprecated (repository=reporting/reporting)
       "depName": "babel-preset-es2015",
       "deprecationMessage": "On registry `https://martifactory.io/api/npm/virtual-npm/`, the \"latest\" version (v6.24.1) of dependency `babel-preset-es2015` has the following deprecation notice:\n\n`🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!`\n\nMarking the latest version of an npm package as deprecated results in the entire package being considered deprecated, so contact the package author you think this is a mistake.",
       "packageFiles": [
         "services/pdf-comp-service/package.json",
         "services/reporting-comp-service/package.json"
       ]
 WARN: getGraphqlIssues error (repository=reporting/reporting)
       "query": "\n  query {\n    repository(owner: \"reporting\", name: \"reporting\") {\n      issues(first: 100, after:null, orderBy: {field: UPDATED_AT, direction: DESC}, filterBy: {createdBy: \"service-continuous-deliver\"}) {\n        pageInfo {\n          startCursor\n          hasNextPage\n        }\n        nodes {\n          number\n          state\n          title\n          body\n        }\n      }\n    }\n  }\n  ",
       "err": {
         "name": "HTTPError",
         "hostname": "github.medallia.com",
         "method": "POST",
         "path": "/api/v3/graphql",
         "protocol": "https:",
         "url": "https://github.medallia.com/api/v3/graphql",
         "gotOptions": {
           "path": "/api/v3/graphql",
           "protocol": "https:",
           "hostname": "github.medallia.com",
           "hash": "",
           "search": "",
           "pathname": "/api/v3/graphql",
           "href": "https://github.medallia.com/api/v3/graphql",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/vnd.github.merge-info-preview+json",
             "accept-encoding": "gzip, deflate",
             "authorization": "** redacted **",
             "content-length": 424
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "hostType": "github",
           "baseUrl": "https://github.medallia.com/api/v3/",
           "body": "{\"query\":\"\\n  query {\\n    repository(owner: \\\"reporting\\\", name: \\\"reporting\\\") {\\n      issues(first: 100, after:null, orderBy: {field: UPDATED_AT, direction: DESC}, filterBy: {createdBy: \\\"service-continuous-deliver\\\"}) {\\n        pageInfo {\\n          startCursor\\n          hasNextPage\\n        }\\n        nodes {\\n          number\\n          state\\n          title\\n          body\\n        }\\n      }\\n    }\\n  }\\n  \"}",
           "method": "POST",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "GitHub.com",
           "date": "Thu, 30 May 2019 10:16:30 GMT",
           "content-type": "application/json; charset=utf-8",
           "transfer-encoding": "chunked",
           "connection": "close",
           "status": "404 Not Found",
           "x-oauth-scopes": "repo",
           "x-accepted-oauth-scopes": "repo",
           "x-github-enterprise-version": "2.16.6",
           "x-github-media-type": "github.merge-info-preview; format=json",
           "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type",
           "access-control-allow-origin": "*",
           "x-github-request-id": "d181cb37-9e14-4556-a058-72a8277d6588",
           "strict-transport-security": "max-age=31536000; includeSubdomains",
           "x-frame-options": "deny",
           "x-content-type-options": "nosniff",
           "x-xss-protection": "1; mode=block",
           "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
           "content-security-policy": "default-src 'none'",
           "x-runtime-rack": "0.017387",
           "content-encoding": "gzip"
         },
         "body": "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/enterprise/2.16/v3\"}",
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/home/jenkins/workspace/medallia_renovate_master-EPD7JO65Z2D3QYCBQKHZL6Z44R23NJF7UMXKRHMCFIRCJPY7SRJA/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Issue created (repository=reporting/reporting)
 WARN: getGraphqlIssues error (repository=reporting/reporting)
       "query": "\n  query {\n    repository(owner: \"reporting\", name: \"reporting\") {\n      issues(first: 100, after:null, orderBy: {field: UPDATED_AT, direction: DESC}, filterBy: {createdBy: \"service-continuous-deliver\"}) {\n        pageInfo {\n          startCursor\n          hasNextPage\n        }\n        nodes {\n          number\n          state\n          title\n          body\n        }\n      }\n    }\n  }\n  ",
       "err": {
         "name": "HTTPError",
         "hostname": "github.medallia.com",
         "method": "POST",
         "path": "/api/v3/graphql",
         "protocol": "https:",
         "url": "https://github.medallia.com/api/v3/graphql",
         "gotOptions": {
           "path": "/api/v3/graphql",
           "protocol": "https:",
           "hostname": "github.medallia.com",
           "hash": "",
           "search": "",
           "pathname": "/api/v3/graphql",
           "href": "https://github.medallia.com/api/v3/graphql",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/vnd.github.merge-info-preview+json",
             "accept-encoding": "gzip, deflate",
             "authorization": "** redacted **",
             "content-length": 424
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "hostType": "github",
           "baseUrl": "https://github.medallia.com/api/v3/",
           "body": "{\"query\":\"\\n  query {\\n    repository(owner: \\\"reporting\\\", name: \\\"reporting\\\") {\\n      issues(first: 100, after:null, orderBy: {field: UPDATED_AT, direction: DESC}, filterBy: {createdBy: \\\"service-continuous-deliver\\\"}) {\\n        pageInfo {\\n          startCursor\\n          hasNextPage\\n        }\\n        nodes {\\n          number\\n          state\\n          title\\n          body\\n        }\\n      }\\n    }\\n  }\\n  \"}",
           "method": "POST",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "GitHub.com",
           "date": "Thu, 30 May 2019 10:16:31 GMT",
           "content-type": "application/json; charset=utf-8",
           "transfer-encoding": "chunked",
           "connection": "close",
           "status": "404 Not Found",
           "x-oauth-scopes": "repo",
           "x-accepted-oauth-scopes": "repo",
           "x-github-enterprise-version": "2.16.6",
           "x-github-media-type": "github.merge-info-preview; format=json",
           "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type",
           "access-control-allow-origin": "*",
           "x-github-request-id": "0bbc0504-2fd1-4ab7-beea-f24edff520c1",
           "strict-transport-security": "max-age=31536000; includeSubdomains",
           "x-frame-options": "deny",
           "x-content-type-options": "nosniff",
           "x-xss-protection": "1; mode=block",
           "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
           "content-security-policy": "default-src 'none'",
           "x-runtime-rack": "0.013318",
           "content-encoding": "gzip"
         },
         "body": "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/enterprise/2.16/v3\"}",
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/home/jenkins/workspace/medallia_renovate_master-EPD7JO65Z2D3QYCBQKHZL6Z44R23NJF7UMXKRHMCFIRCJPY7SRJA/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Processing 22 branches: renovate/apollo-server-monorepo, renovate/assign-deep-1.x, renovate/bowser-2.x, renovate/d3-5.x, renovate/d3-scale-3.x, renovate/eslint-config-xo-react-0.x, renovate/eslint-plugin-react-7.x, renovate/filenamify-4.x, renovate/inquirer-6.x, renovate/lock-file-maintenance, renovate/m-alchemy-ui-14.x, renovate/m-comp-service-base-0.x, renovate/major-lerna-monorepo, renovate/penpal-4.x, renovate/precss-4.x, renovate/react-svg-loader-3.x, renovate/react-transition-group-4.x, renovate/styled-components-4.x, renovate/styled-reset-2.x, renovate/stylelint-10.x, renovate/typescript-3.x, renovate/victory-32.x (repository=reporting/reporting)
 WARN: getClosedPrs error (repository=reporting/reporting, dependencies=@types/inquirer, branch=renovate/inquirer-6.x)
       "query": "\n      query {\n        repository(owner: \"reporting\", name: \"reporting\") {\n          pullRequests(states: [CLOSED, MERGED], first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {\n            nodes {\n              number\n              state\n              headRefName\n              title\n              comments(last: 100) {\n                nodes {\n                  databaseId\n                  body\n                }\n              }\n            }\n          }\n        }\n      }\n      ",
       "err": {
         "name": "HTTPError",
         "hostname": "github.medallia.com",
         "method": "POST",
         "path": "/api/v3/graphql",
         "protocol": "https:",
         "url": "https://github.medallia.com/api/v3/graphql",
         "gotOptions": {
           "path": "/api/v3/graphql",
           "protocol": "https:",
           "hostname": "github.medallia.com",
           "hash": "",
           "search": "",
           "pathname": "/api/v3/graphql",
           "href": "https://github.medallia.com/api/v3/graphql",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept-encoding": "gzip, deflate",
             "authorization": "** redacted **",
             "content-length": 523
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "hostType": "github",
           "baseUrl": "https://github.medallia.com/api/v3/",
           "body": "{\"query\":\"\\n      query {\\n        repository(owner: \\\"reporting\\\", name: \\\"reporting\\\") {\\n          pullRequests(states: [CLOSED, MERGED], first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {\\n            nodes {\\n              number\\n              state\\n              headRefName\\n              title\\n              comments(last: 100) {\\n                nodes {\\n                  databaseId\\n                  body\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n      \"}",
           "method": "POST",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "GitHub.com",
           "date": "Thu, 30 May 2019 10:16:38 GMT",
           "content-type": "application/json; charset=utf-8",
           "transfer-encoding": "chunked",
           "connection": "close",
           "status": "404 Not Found",
           "x-oauth-scopes": "repo",
           "x-accepted-oauth-scopes": "repo",
           "x-github-enterprise-version": "2.16.6",
           "x-github-media-type": "github.v4; format=json",
           "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type",
           "access-control-allow-origin": "*",
           "x-github-request-id": "e960a985-371e-4dbd-9d99-8e10fba04da5",
           "strict-transport-security": "max-age=31536000; includeSubdomains",
           "x-frame-options": "deny",
           "x-content-type-options": "nosniff",
           "x-xss-protection": "1; mode=block",
           "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
           "content-security-policy": "default-src 'none'",
           "x-runtime-rack": "0.011877",
           "content-encoding": "gzip"
         },
         "body": "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/enterprise/2.16/v3\"}",
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/home/jenkins/workspace/medallia_renovate_master-EPD7JO65Z2D3QYCBQKHZL6Z44R23NJF7UMXKRHMCFIRCJPY7SRJA/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
```

**To Reproduce**

n/a

**Expected behavior**

* Just keep one set of warnings.
* Close duplicates.

**Screenshots**

<img width="647" alt="Screen Shot 2019-05-30 at 9 59 16 AM" src="https://user-images.githubusercontent.com/51505/58638371-a7ae6000-82c2-11e9-9554-dff0a29b0daf.png">

**Additional context**

Started on May 28th.

**Comment by rarkins** [comment]
Can you work out which version of Renovate it first started on? In the meantime you can set config.suppressNotifications = ['deprecationWarningIssues'] to disable these.

**Comment by dylang** [comment]
Thanks for the quick reply!

We use renovate on our renovate repo, so it updates every 15 minutes or so. We only have logs for the last 100 runs so I don't have that anymore.

**Comment by rarkins** [comment]
Do you install it via CLI, or run the Docker container?

For npm, we just switched v18.x over to `latest` earlier today, which is pretty far from 28th. But for Docker, it can be hard to stop Docker tagging the last thing it sees as `latest`. I'd recommend you consider pinning your Docker image if you're using it, or at least to a major version (e.g. `renovate/renovate:18`)

**Comment by rarkins** [comment]
I've spotted where it came from and pushed a revert fix immediately. We are querying `/api/v3/graphql` instead of `/api/graphql`. We should have a massage function there but for some reason it's not being triggered. This resulted in an empty issue list being retrieved. Sorry :-/

**Comment by dylang** [comment]
Nice work finding the issue!

We install using yarn into our own container.

**Comment by rarkins** [comment]
The commit that caused it is reverted in [v18.5.7](https://github.com/renovatebot/renovate/releases/tag/18.5.7). Sorry for the issue spam you received. 

I have identified the root cause and will revert the revert and fix properly in the next patch. I'll then work out if Renovate will clean up the duplicates properly.

Sorry for the inconvenience and thanks for reporting!
