### ISSUE TITLE
Renovate CLI: Invalid regular expression flags

### ISSUE THREAD

**Issue by mmoayyed** [renovatebot/renovate#3979]
**What Renovate type are you using?**

Renovate CLI

**Describe the bug**

Running:

```
npm install -g renovate
```

Produces:

```
SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/renovate/dist/manager/swift/index.js:2:32)

/home/travis/.nvm/versions/node/v8.9.1/bin/renovate -> /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/renovate/dist/renovate.js
/home/travis/.nvm/versions/node/v8.9.1/bin/renovate-config-validator -> /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/renovate/bin/config-validator.js
> dtrace-provider@0.8.7 install /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/renovate/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js
make: Entering directory `/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/renovate/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/renovate/node_modules/dtrace-provider/build'
> core-js@3.1.4 postinstall /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/renovate/node_modules/core-js
> node scripts/postinstall || echo "ignore"
+ renovate@18.20.2
added 863 packages in 25.578s
/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/renovate/dist/manager/swift/extract.js:5
    space: /(\s+|\/\/[^\n]*|\/\*.*\*\/)+/s,           ^
````

**Did you see anything helpful in debug logs?**

See above please (though not debug logs).

**To Reproduce**

Running `npm install -g renovate` under Travis CI.

**Expected behavior**

A successful installation of CLI.

Here is another build from 11 days ago that passes successfully using the same exact command: https://travis-ci.org/apereo/cas/jobs/546574684

**Screenshots**

See https://travis-ci.org/apereo/cas/jobs/551754086

**Comment by rarkins** [comment]
Can you try again with Node 10?

Note: https://github.com/renovatebot/renovate/blob/master/package.json#L88

**Comment by mmoayyed** [comment]
Thank you. That did quite nicely. For anyone who might be interested, this is what I did try:

```
npm install npm@latest -g
npm -v

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm install 12.5.0
node -v

npm install -g renovate
```
