### ISSUE TITLE
[Question] Renovate autoclose MR when repository is unavailable

### ISSUE THREAD

**Issue by jgarec** [renovatebot/renovate#3981]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Gitlab

### Have you checked the logs? Don't forget to include them if relevant
```
08:36:12   INFO: Found dockerfile package files (repository=my_group/my_app)
08:36:12   WARN: Error obtaining docker token (repository=my_group/my_app)
08:36:12         "registry": "https://my_docker_repository:8500",
08:36:12         "dockerRepository": "my_group/my_image",
08:36:12         "err": {
08:36:12           "name": "RequestError",
08:36:12           "code": "ECONNREFUSED",
08:36:12           "host": "my_docker_repository:8500",
08:36:12           "hostname": "my_docker_repository",
08:36:12           "method": "GET",
08:36:12           "path": "/v2/",
08:36:12           "protocol": "https:",
08:36:12           "url": "https://my_docker_repository:8500/v2/",
08:36:12           "gotOptions": {
08:36:12             "path": "/v2/",
08:36:12             "protocol": "https:",
08:36:12             "slashes": true,
08:36:12             "auth": null,
08:36:12             "host": "my_docker_repository:8500",
08:36:12             "port": "8500",
08:36:12             "hostname": "my_docker_repository",
08:36:12             "hash": null,
08:36:12             "search": null,
08:36:12             "query": null,
08:36:12             "pathname": "/v2/",
08:36:12             "href": "https://my_docker_repository:8500/v2/",
08:36:12             "headers": {
08:36:12               "user-agent": "https://github.com/renovatebot/renovate",
08:36:12               "accept-encoding": "gzip, deflate"
08:36:12             },
08:36:12             "hooks": {
08:36:12               "beforeError": [],
08:36:12               "init": [],
08:36:12               "beforeRequest": [],
08:36:12               "beforeRedirect": [],
08:36:12               "beforeRetry": [],
08:36:12               "afterResponse": []
08:36:12             },
08:36:12             "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
08:36:12             "decompress": true,
08:36:12             "throwHttpErrors": false,
08:36:12             "followRedirect": true,
08:36:12             "stream": false,
08:36:12             "form": false,
08:36:12             "json": false,
08:36:12             "cache": false,
08:36:12             "useElectronNet": false,
08:36:12             "method": "GET",
08:36:12             "gotTimeout": {"request": 60000}
08:36:12           },
08:36:12           "message": "connect ECONNREFUSED 11.22.33.44:8500",
08:36:12           "stack": "RequestError: connect ECONNREFUSED 11.22.33.44:8500\n    at ClientRequest.request.once.error (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:277:13)\n    at ClientRequest.emit (events.js:194:15)\n    at ClientRequest.origin.emit.args (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:189:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
08:36:12         }
08:36:12   INFO: Failed to look up dependency my_docker_repository:8500/my_group/my_image (repository=my_group/my_app, packageFile=Dockerfile, dependency=my_docker_repository:8500/my_group/my_image)
08:36:12   INFO: Processing 0 branches:  (repository=my_group/my_app)
08:36:12   INFO: Deleting orphan branch (repository=my_group/my_app, branch=renovate/docker-my_docker_repository-8500-my-group-my-image-7.x)
08:36:13   INFO: PR autoclosed (repository=my_group/my_app)
08:36:13         "prNo": 1,
08:36:13         "prTitle": "Update my_docker_repository:8500/my_group/my_image Docker tag to v7.5"
```

### What is your question?
1. Is there a way to keep this MR opened if an error occurs when checking a repository ? or to retry ?
2. If not, renovate open another issue. Is it possible to reopen the "autoclosed issue" ? The main reason is to keep the history of this upgrade cleaner.

**Comment by rarkins** [comment]
@jgarec I have transferred this to the main repo, as unfortunately it is not fixable by config right now.

Today we generally throw a "registry-failure" and abort Renovate only if the registry is known to us as an always-available public one (e.g. npmjs.org, Docker Hub, Rubygems.org, etc). For others, Renovate will continue and as a result you can see autoclosings like you did.

There are a few ways we could improve this:
1. Allow users to opt into treating *all* registries as critical and aborting a Renovate run with `registry-failure` for all
2. Detecting/reopening autoclosed PRs

Unfortunately it doesn't seem feasible to default to treating all registries as critical because there are dozens or hundreds of existing users who are happy to let Renovate fail for private registries today and still expect it to continue for everything else.

There's also the matter of what to do about registry failures. We could potentially raise an issue in the repo saying that a registry is unavailable. This would have some benefits, but also the negative that you'd get "noise" from the bot any time there's an ephemeral registry failure.

**Comment by rarkins** [comment]
So, first idea: after creating a branch, check in case there exists a closed Pr with exact name (+ " - autoclosed") and if so then attempt to reopen it and update it if necessary, instead of always creating a new PR.

Second idea: formally introduce the concept of "critical" datasources and let it be configurable by `hostRules`.

**Comment by jgarec** [comment]
In my case, your first idea seems ok.
It will also handle the case where recreateClosed is set to true

**Comment by ViceIce** [comment]
I like both ideas
