### ISSUE TITLE
Avoid "Action Required: Fix Renovate Configuration" during platform errors

### ISSUE THREAD

**Issue by FantasticFiasco** [renovatebot/renovate#4152]
### Which Renovate are you using? CLI, App, or Pro
- App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
- GitHub

### Have you checked the logs? Don't forget to include them if relevant
```
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "github>FantasticFiasco/renovate-config"
    ]
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "github>FantasticFiasco/renovate-config"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>FantasticFiasco/renovate-config"
    ]
  }
}
DEBUG: Failed to retrieve default.json from repo
INFO: default.json preset not found - trying renovate.json
DEBUG: Failed to retrieve renovate.json from repo
DEBUG: Preset fetch error
{
  "err": {
    "message": "dep not found",
    "stack": "Error: dep not found\n    at fetchJSONFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/github/index.js:24:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
INFO: Throwing preset error
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (github>FantasticFiasco/renovate-config)"
  }
}
DEBUG: raiseConfigWarningIssue()
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, null, open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 41 Pull Requests
DEBUG: ensureIssue()
INFO: Reopening previously closed issue
INFO: Patching issue
INFO: Issue updated
```

### What is your question?
Every now and again Renovate is opening an issue in all my configured repositories claiming that the configuration is invalid. Then a couple of hours later the issue is closed again.

**Comment by rarkins** [comment]
Transferring this to the main repo to treat as a bug. Here's the debug log:
```
{"msg":"Failed to retrieve default.json from repo","time":"2019-07-22T15:45:51.847Z"}
{"msg":"default.json preset not found - trying renovate.json","time":"2019-07-22T15:45:51.847Z"}
{"msg":"Failed to retrieve renovate.json from repo","time":"2019-07-22T15:45:52.173Z"}
{"err":{"message":"dep not found","stack":"Error: dep not found\n    at fetchJSONFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/github/index.js:24:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"Preset fetch error","time":"2019-07-22T15:45:52.173Z"}
{"msg":"Throwing preset error","time":"2019-07-22T15:45:52.174Z"}
{"error":{"validationError":"Cannot find preset's package (github>FantasticFiasco/renovate-config)"},"msg":"Repository has invalid config","time":"2019-07-22T15:45:52.174Z"}
```

From this it's clear we're "swallowing" whatever error caused it. If we look at the timestamps, it coincided with GitHub's downtime/instability yesterday. If GitHub returns 404s - i.e. exactly as if the repo or file didn't exist - then there's nothing we can do, but if the errors are timeouts or 5xx errors then we should treat that as a platform error and abort without raising a config warning.

**Comment by FantasticFiasco** [comment]
Thanks for the explanation! Please feel free to close the issue after transferal.

**Comment by rarkins** [comment]
I've added a couple of if statements to find platform errors and throw them up the stack, this should hopefully abort runs without raising config warnings.
