### ISSUE TITLE
Tests fail for git storage platform

### ISSUE THREAD

**Issue by rakeshtembhurne** [renovatebot/renovate#4230]
**What Renovate type are you using?**
Renovate CLI (local development)

**Describe the bug**
`yarn test` shows some tests fail for git storage platform.

**Did you see anything helpful in debug logs?**
Updating snapshots by adding `-u` reduces the number of failing tests. For example, running `yarn jest test/platform/git/storage.spec.ts -u` reduces failed tests count to 3 from 7.

**To Reproduce**
1. fetch and merge the latest code from the renovate repository to master branch
2. run `yarn test` or specifically `yarn jest test/platform/git/storage.spec.ts`

**Expected behavior**
Exceptions should be handled properly and tests should pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/1090611/62326023-bbe12a00-b4ca-11e9-88af-927118b289ac.png)

**Additional context**
NA

**System Details**
OS: Mac OS High Siera (v10.13.6)
```
$ node --version
v10.16.0
$ npm --version
6.9.0
$ yarn --version
1.16.0
$ nvm --version
0.33.2
```

**Bash Output**
```
$ yarn jest test/platform/git/storage.spec.ts
yarn run v1.16.0
$ yarn clean-cache && cross-env NODE_ENV=test LOG_LEVEL=fatal jest test/platform/git/storage.spec.ts
$ node bin/clean-cache.js
Removing /var/folders/pq/9378lq2n3wg11z3v4405gwbm0000gp/T/renovate
 FAIL  test/platform/git/storage.spec.ts (12.134s)
  platform/git/storage
    setBaseBranch(branchName)
      ✓ sets the base branch as master (310ms)
      ✓ sets non-master base branch (324ms)
      ✕ should throw if branch does not exist (228ms)
    getFileList()
      ✕ returns empty array if error (297ms)
      ✓ should return the correct files (353ms)
    branchExists(branchName)
      ✓ should return true if found (260ms)
      ✕ should return false if not found (216ms)
    getAllRenovateBranches()
      ✓ should return all renovate branches (294ms)
    isBranchStale()
      ✓ should return false if same SHA as master (447ms)
      ✓ should return true if SHA different from master (343ms)
      ✕ should throw if branch does not exist (213ms)
    getBranchCommit(branchName)
      ✓ should return same value for equal refs (391ms)
      ✕ should throw if branch does not exist (242ms)
    createBranch(branchName, sha)
      ✓ resets existing branch (571ms)
    mergeBranch(branchName)
      ✓ should perform a branch merge (440ms)
      ✓ should throw if branch merge throws (246ms)
      ✓ should throw if branch merge is stale (704ms)
    deleteBranch(branchName)
      ✓ should send delete (295ms)
    getBranchLastCommitTime
      ✓ should return a Date (315ms)
      ✓ handles error (216ms)
    getFile(filePath, branchName)
      ✓ gets the file (204ms)
      ✓ short cuts 404 (241ms)
      ✕ returns null for 404 (251ms)
    commitFilesToBranch(branchName, files, message, parentBranch)
      ✓ creates file (391ms)
      ✓ deletes file (450ms)
      ✓ updates multiple files (447ms)
    getCommitMessages()
      ✓ returns commit messages (284ms)
    Storage.getUrl()
      ✓ returns https url (195ms)
      ✓ returns ssh url (484ms)
    initRepo())
      ✕ should fetch latest (315ms)
      ✓ should set branch prefix (1033ms)

  ● platform/git/storage › setBaseBranch(branchName) › should throw if branch does not exist

    expect(received).rejects.toMatchSnapshot()

    Snapshot name: `platform/git/storage setBaseBranch(branchName) should throw if branch does not exist 1`

    - Snapshot
    + Received

    - [Error: Cannot set baseBranch to something that does not exist: not_found]
    + [Error: platform-failure]

      74 |     });
      75 |     it('should throw if branch does not exist', async () => {
    > 76 |       await expect(git.setBaseBranch('not_found')).rejects.toMatchSnapshot();
         |                                                            ^
      77 |     });
      78 |   });
      79 |   describe('getFileList()', () => {

      at Object.args [as toMatchSnapshot] (node_modules/expect/build/index.js:242:20)
      at Object.toMatchSnapshot (test/platform/git/storage.spec.ts:76:60)

  ● platform/git/storage › getFileList() › returns empty array if error

    platform-failure

      480 |   for (const errorStr of platformErrorStrings) {
      481 |     if (err.message.includes(errorStr)) {
    > 482 |       throw new Error('platform-failure');
          |             ^
      483 |     }
      484 |   }
      485 | }

      at checkForPlatformFailure (lib/platform/git/storage.ts:482:13)
      at Storage.checkForPlatformFailure [as branchExists] (lib/platform/git/storage.ts:277:9)

  ● platform/git/storage › branchExists(branchName) › should return false if not found

    platform-failure

      480 |   for (const errorStr of platformErrorStrings) {
      481 |     if (err.message.includes(errorStr)) {
    > 482 |       throw new Error('platform-failure');
          |             ^
      483 |     }
      484 |   }
      485 | }

      at checkForPlatformFailure (lib/platform/git/storage.ts:482:13)
      at Storage.checkForPlatformFailure [as branchExists] (lib/platform/git/storage.ts:277:9)

  ● platform/git/storage › isBranchStale() › should throw if branch does not exist

    expect(received).rejects.toMatchSnapshot()

    Snapshot name: `platform/git/storage isBranchStale() should throw if branch does not exist 1`

    - Snapshot
    + Received

    - [Error: Cannot check staleness for branch that does not exist: not_found]
    + [Error: platform-failure]

      112 |     });
      113 |     it('should throw if branch does not exist', async () => {
    > 114 |       await expect(git.isBranchStale('not_found')).rejects.toMatchSnapshot();
          |                                                            ^
      115 |     });
      116 |   });
      117 |

      at Object.args [as toMatchSnapshot] (node_modules/expect/build/index.js:242:20)
      at Object.toMatchSnapshot (test/platform/git/storage.spec.ts:114:60)

  ● platform/git/storage › getBranchCommit(branchName) › should throw if branch does not exist

    expect(received).rejects.toMatchSnapshot()

    Snapshot name: `platform/git/storage getBranchCommit(branchName) should throw if branch does not exist 1`

    - Snapshot
    + Received

    - [Error: Cannot fetch commit for branch that does not exist: not_found]
    + [Error: platform-failure]

      123 |     });
      124 |     it('should throw if branch does not exist', async () => {
    > 125 |       await expect(git.getBranchCommit('not_found')).rejects.toMatchSnapshot();
          |                                                              ^
      126 |     });
      127 |   });
      128 |

      at Object.args [as toMatchSnapshot] (node_modules/expect/build/index.js:242:20)
      at Object.toMatchSnapshot (test/platform/git/storage.spec.ts:125:62)

  ● platform/git/storage › getFile(filePath, branchName) › returns null for 404

    expect(received).rejects.toMatchSnapshot()

    Snapshot name: `platform/git/storage getFile(filePath, branchName) returns null for 404 1`

    - Snapshot
    + Received

    - [Error: repository-changed]
    + [Error: platform-failure]

      194 |       await expect(
      195 |         git.getFile('some-path', 'some-branch')
    > 196 |       ).rejects.toMatchSnapshot();
          |                 ^
      197 |     });
      198 |   });
      199 |   describe('commitFilesToBranch(branchName, files, message, parentBranch)', () => {

      at Object.args [as toMatchSnapshot] (node_modules/expect/build/index.js:242:20)
      at Object.toMatchSnapshot (test/platform/git/storage.spec.ts:196:17)

  ● platform/git/storage › initRepo()) › should fetch latest

    platform-failure

      480 |   for (const errorStr of platformErrorStrings) {
      481 |     if (err.message.includes(errorStr)) {
    > 482 |       throw new Error('platform-failure');
          |             ^
      483 |     }
      484 |   }
      485 | }

      at checkForPlatformFailure (lib/platform/git/storage.ts:482:13)
      at Storage.checkForPlatformFailure [as branchExists] (lib/platform/git/storage.ts:277:9)

 › 4 snapshots failed.

=============================== Coverage summary ===============================
Statements   : 1.76% ( 207/11734 )
Branches     : 0.72% ( 45/6274 )
Functions    : 2.05% ( 28/1368 )
Lines        : 1.79% ( 205/11468 )
================================================================================
Snapshot Summary
 › 4 snapshots failed from 1 test suite. Inspect your code changes or run `yarn run jest -u` to update them.

Test Suites: 1 failed, 1 total
Tests:       7 failed, 24 passed, 31 total
Snapshots:   4 failed, 3 passed, 7 total
Time:        29.487s
Ran all test suites matching /test\/platform\/git\/storage.spec.ts/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rarkins** [comment]
Don’t run with `-u` in cases like these.

What version of `git` are you running?

**Comment by rakeshtembhurne** [comment]
The given output is without `-u` option. 
```$ git --version
git version 2.17.2 (Apple Git-113)```

**Comment by rarkins** [comment]
Isolate to one of the tests that’s failing and debug it step by step. For some reason you’re getting `platform-failure` responses where not expected

**Comment by rakeshtembhurne** [comment]
For test 
```
describe('setBaseBranch(branchName)', () => {
  // ... other tests
  it('should throw if branch does not exist', async () => {
    await expect(git.setBaseBranch('not_found')).rejects.toMatchSnapshot();
  });
});
```
`setBaseBranch()` function calls `branchExists(branchName)` function inside if condition in `lib/platform/git/storage.ts` file.  A boolean value is expected here, but this function internally calls `checkForPlatformFailure(err);` which throws `platform-failure` message.

Now `branchExists()` function is throwing error for this code: 
```
try {
  await this._git!.raw([
    'remote',
    'set-branches',
    '--add',
    'origin',
    branchName,
  ]);
  await this._git!.fetch(['origin', branchName, '--depth=2']);
} catch (err) {
  checkForPlatformFailure(err);
}
```
And the value of `err.message` is:
```
fatal: Couldn't find remote ref not_found
fatal: The remote end hung up unexpectedly
```

This second line `fatal: The remote end hung up unexpectedly` matches with one of the messages that throws `platform-failure` error inside `checkForPlatformFailure()` function.

**Comment by rarkins** [comment]
I'll try to debug the same test on my laptop and see if it follows the same path. The last part about remote end hanging up seems strange because the test is meant to be a local test against file system.

**Comment by rarkins** [comment]
Mine takes this path:
![image](https://user-images.githubusercontent.com/6311784/62373175-e7ebc200-b541-11e9-908e-e9e4c69eeb19.png)

And from inside the branchExists `err`:
![image](https://user-images.githubusercontent.com/6311784/62373333-3a2ce300-b542-11e9-8db5-304f30fdc2e4.png)

So the difference is that somehow you are getting "The remote end hung up unexpectedly" in addition to the expected error message, and this is triggering the platform failure.

I'm running `git version 2.21.0` on OSX. Can you upgrade (e.g. using brew) to rule that variable out?

**Comment by rarkins** [comment]
Maybe run `git config -l` too and check if there's anything in there that could explain it.

**Comment by rakeshtembhurne** [comment]
I checked my git installation, it seems I was using Apple Git which comes by default (or with Xcode). I installed a new `git version 2.22.0` using Homebrew, which passes all the tests. So apparently failing tests are due to incorrect/older version of Git. Upgrading solved my issue.

**Comment by nihalanisumit** [comment]
@rarkins I am almost facing the same issue and updating git version didn't help in my case, unfortunately.

**Comment by rarkins** [comment]
Please raise a new issue with logs, troubleshooting steps you’ve tried, etc
