### ISSUE TITLE
NPM_TOKEN does not get correctly resolved

### ISSUE THREAD

**Issue by cambiph** [renovatebot/renovate#4315]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
${NPM_TOKEN} does not get correctly resolved. The debug logging shows `"authInfoToken": "un*****ed",`

**Did you see anything helpful in debug logs?**

```json
"pkgUrl":` "http://<custom-npm-repo>@govflanders%2Fvl-ui-util",
"authInfoType": "Basic",
"authInfoToken": "un*****ed",
"err": {
  "name": "HTTPError",
  "host": "<custom-npm-repo>",
  "hostname": "<custom-npm-repo>",
  "method": "GET",
  "path": "/artifactory/api/npm/acd-npm/@govflanders%2Fvl-ui-util",
  "protocol": "http:",
  "url": "http://<custom-npm-repo>:8081/artifactory/api/npm/acd-npm/@govflanders%2Fvl-ui-util",
  "gotOptions": {
    "path": "/artifactory/api/npm/acd-npm/@govflanders%2Fvl-ui-util",
    "protocol": "http:",
    "slashes": true,
    "auth": null,
    "host": "<custom-npm-repo>:8081",
    "port": "8081",
    "hostname": "<custom-npm-repo>",
    "hash": null,
    "search": null,
    "query": null,
    "pathname": "/artifactory/api/npm/acd-npm/@govflanders%2Fvl-ui-util",
    "href": "http://<custom-npm-repo>:8081/artifactory/api/npm/acd-npm/@govflanders%2Fvl-ui-util",
    "headers": {
      "user-agent": "https://github.com/renovatebot/renovate",
      "authorization": "** redacted **",
      "cache-control": "no-cache",
      "accept": "application/json",
      "accept-encoding": "gzip, deflate"
    },
    "hooks": {
      "beforeError": [],
      "init": [],
      "beforeRequest": [],
      "beforeRedirect": [],
      "beforeRetry": [],
      "afterResponse": []
    },
    "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
    "decompress": true,
    "throwHttpErrors": true,
    "followRedirect": true,
    "stream": false,
    "form": false,
    "json": true,
    "cache": false,
    "useElectronNet": false,
    "method": "GET",
    "gotTimeout": {"request": 60000}
  },
  "statusCode": 403,
  "statusMessage": "Forbidden",
  "headers": {
    "*redacted*"
  },
  "body": {
    "errors": [
      {
        "status": 403,
        "message": "'Basic undefined' is blocked due to recurrent login failures, please try again in 4 seconds"
      }
    ]
  },
  "message": "Response code 403 (Forbidden)",
  "stack": "HTTPError: Response code 403 (Forbidden)\n    at EventEmitter.emitter.on (/usr/src/app/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
},
"statusCode": 403,
"depName": "@govflanders/vl-ui-util"
 ```
**To Reproduce**
Using a private repo, use this config:

```json
{
    "autodiscover": true,
    "autodiscoverFilter": "milieuinfo/webcomponent*vl*",
    "assignees": ["coemans"],
    "enabled": true,
    "enabledManagers": ["npm"],
    "encrypted": {
      "npmToken": "*redacted*"
    },
    "labels": ["renovate", "dependencies"],
    "npmrc": "registry=http://<custom-npm-repo>/\n_auth=${NPM_TOKEN}",
    "pruneStaleBranches": true,
    "reviewers": ["coemans"]
  }
```

**Expected behavior**
Renovate can authenticate with the custom repo and fetch the package versions.

**Additional context**
When removing the encrypted object and replacing ${NPM_TOKEN} with the decrypted token, all is well.

**Comment by rarkins** [comment]
Encrypting/decrypting was developed essentially just for the hosted app and not CLI, although there's hopefully nothing *preventing* it working with CLI users. You need to:

- Generate a public/private key pair
- Download https://renovatebot.com/encrypt or copy/paste the source code to replace Renovate's public key there with your own public key
- Add your private key in the `privateKey` field in your bot `config.js`
