### ISSUE TITLE
node-re2 fails to build without python

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4348]
I found this log as part of the Dockerfile.slim failing:

```
error /usr/src/app/node_modules/re2: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /usr/src/app/node_modules/re2
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.4.0-1060-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/re2
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

I guess this means we need to document Python as a required dependency now?

**Comment by rarkins** [comment]
After installing python into tsbuild, I'm still getting:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by ViceIce** [comment]
yes, we need python 2 for that, i'll send a pr.

are the docker builds failing?

**Comment by rarkins** [comment]
Oh wow, I just saw it requires python 2! I'll fix

**Comment by rarkins** [comment]
We don't need python at runtime though, right?

**Comment by ViceIce** [comment]
no

**Comment by ViceIce** [comment]
ups, yes we **don't** need at runtime

**Comment by rarkins** [comment]
See PR

**Comment by ViceIce** [comment]
i know, trying locally. build failed.
```dockerfile
RUN yarn install --production --frozen-lockfile
```

missing deps on production node deps install. thinking about a solution without needing build deps

**Comment by rarkins** [comment]
Yeah, I just noticed. I saw the build step pass and pushed this PR too soon. I guess we could prune node_modules as last step in the tsbuild intermediate image and then copy node_modules over?

**Comment by ViceIce** [comment]
I found a solution:

replace
https://github.com/renovatebot/renovate/blob/9ab041be79e703201da618b89a72302089312f9c/Dockerfile.slim#L39

with
```dockerfile
RUN yarn build:docker

RUN yarn install --production --frozen-lockfile
```

https://github.com/renovatebot/renovate/blob/9ab041be79e703201da618b89a72302089312f9c/Dockerfile.slim#L69
with
```dockerfile
COPY --from=tsbuild /usr/src/app/node_modules node_modules
```

**Comment by ViceIce** [comment]
I think the same has to be done to the full image?

**Comment by ViceIce** [comment]
https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#node-gyp-alpine

**Comment by rarkins** [comment]
I think we came up with the same solution. Isn't the full image OK because it already contains Python? Haven't double checked if python 2 is there though

**Comment by ViceIce** [comment]
you can just check the docker hub build logs. are they ok?

**Comment by rarkins** [comment]
Oops, nope:

```
error /usr/src/app/node_modules/re2: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /usr/src/app/node_modules/re2
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.0 | linux | x64
gyp info find Python using Python version 2.7.15 found at "/usr/bin/python2"
gyp http GET https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.16.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.16.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/usr/src/app/node_modules/re2/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/ubuntu/.cache/node-gyp/10.16.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/10.16.0',
gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/10.16.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/usr/src/app/node_modules/re2',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.' ]
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.4.0-1060-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/re2
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
```
