### ISSUE TITLE
Support Docker insecure-registries

### ISSUE THREAD

**Issue by fullstackzach** [renovatebot/renovate#4536]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: getManifestResponse(https://internal-registry.com:5000, docker-image, ea87f50fbdf3ff43e8bf93596edbe56e3071530f) (repository=namespace/repository)
 WARN: Error obtaining docker token (repository=namespace/repository)
       "registry": "https://internal-registry.com:5000",
       "dockerRepository": "repository",
       "err": {
         "name": "RequestError",
         "code": "EPROTO",
         "host": "internal-registry.com:5000",
         "hostname": "internal-registry.com",
         "method": "GET",
         "path": "/v2/",
         "protocol": "https:",
         "url": "https://internal-registry.com:5000/v2/",
         "gotOptions": {
           "path": "/v2/",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "internal-registry.com:5000",
           "port": "5000",
           "hostname": "internal-registry.com",
           "hash": null,
           "search": null,
           "query": null,
           "pathname": "/v2/",
           "href": "https://internal-registry.com:5000/v2/",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": false,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "message": "write EPROTO 140372905225544:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n",
         "stack": "RequestError: write EPROTO 140372905225544:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n\n    at ClientRequest.request.once.error (/builds/user/renovate/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/builds/user/renovate/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at errorOrDestroy (internal/streams/destroy.js:107:12)\n    at onwriteError (_stream_writable.js:436:5)\n    at onwrite (_stream_writable.js:461:5)\n    at _destroy (internal/streams/destroy.js:49:7)\n    at TLSSocket.Socket._destroy (net.js:613:3)\n    at TLSSocket.destroy (internal/streams/destroy.js:37:8)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)"
       }
 INFO: No docker auth found - returning (repository=namespace/repository)
 INFO: Could not getDigest (repository=namespace/repository)
```

### What is your question?

I am trying to setup renovate to update at our pinned digests in Dockerfiles, but the internal docker registry does not support TLS. I understand the above error occurs `SSL routines:ssl3_get_record:wrong version` if you are trying to use TLS against a resource that does not support TLS

I tried setting up a `hostRules` config rule in `config.js`, to have renovate use http with this host but I can't seem to get that to work, and continue to run into the above error
```
module.exports = {
  hostRules: [
    {
      hostType: 'docker',
      baseUrl: 'http://internal-registry.com:5000',
    },
  ],
};
```

Ideally I understand our registry should be configured to support TLS, but that will require a bit more effort in the short term.

Any advice on how to achieve this in the config?

**Comment by rarkins** [comment]
Thanks for confirming that. I think we can boil this down to supporting `insecure-registries`, and it will need code changes so I have transferred this issue into the main repo.

Now we need to work out the most elegant way to do this. Because this setting is per-host, I think it makes most sense to put it in `hostRules`, and probably requires a new setting.

**Comment by fullstackzach** [comment]
Cool - I am interested in working on this. Any thoughts on how to shape that into `hostRules`?
I am thinking since `hostRules` is already an array of objects. Would a boolean that would accompany a host rule make sense?

something like 
```
  "hostRules": [
    {
      "domainName": "insecure-registry.com",
      "username": "<some-username>",
      "password": "<some-password>",
      "insecure-registry": true
    }
  ]
```

**Comment by rarkins** [comment]
Yes I think that would make sense, although we prefer camel case so it would be `insecureRegistry`.

The way it would then work is:
- Renovate would add the `https://` prefix to generate a URL
- Renovate would check hostRules and get a hit back for this rule
- Renovate would change the `https://` to `http://`
- Maybe that's all it takes?

**Comment by fullstackzach** [comment]
Sounds like a good approach. I’ll hack on it locally and see what I can come up with
