### ISSUE TITLE
fail run on nodejs 6.17.1

### ISSUE THREAD

**Issue by tomzhan2019** [renovatebot/renovate#4545]
/usr/lib/node_modules/renovate/dist/renovate.js:14
(async () => {
       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by rarkins** [comment]
Renovate requires at least Node 10: https://github.com/renovatebot/renovate/blob/0228bd05b1487fe3cb180c922b143edcb13c649e/package.json#L94
