### ISSUE TITLE
Maven datasource error

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4569]
Found this error in the app:

```
TypeError [ERR_INVALID_URL]: Invalid URL: ${project.baseUri}../../repository/
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at new URL (internal/url.js:316:22)
    at downloadMavenXml (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/maven/index.js:64:20)
    at Object.getPkgReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/maven/index.js:27:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Comment by zharinov** [comment]
Not enough information to fix it, but at least let's catch and log it

**Comment by zharinov** [comment]
Seems like placeholder in repository URL section

**Comment by zharinov** [comment]
Works good enough for now
