### ISSUE TITLE
Docker quay.io label fetching error

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4626]
Example image: https://quay.io/repository/jetstack/cert-manager-webhook

```
        "body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message></Error>",
        "message": "Response code 400 (Bad Request)",
        "stack": "HTTPError: Response code 400 (Bad Request)\n    at EventEmitter.emitter.on (/home/ubuntu/renovateapp/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
    },
```

**Comment by rarkins** [comment]
**What Renovate type are you using?**

Hosted app

**Describe the bug**

Authenticated requests to quay.io fail

**Did you see anything helpful in debug logs?**

```xml
<Error>
  <Code>InvalidArgument</Code>
  <Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message>
  <ArgumentName>Authorization</ArgumentName>
  <ArgumentValue>Bearer X</ArgumentValue>
  <RequestId>5C0B5B8BC32E9D98</RequestId>
  <HostId>nAf6NG9eaCt3H7kHLIaXT7nM1gmNwJ76xo9Q8xx+gwBnhqflnPi48yDCvc4oGDu0wkM4yuj+1EQ=</HostId>
</Error>
```

**To Reproduce**

I'm not sure exactly. But it's limited to quay.io

**Additional context**

It gets printed as part of a logger.warn: "Unknown error getting Docker labels"

**Comment by ChipWolf** [comment]
Reproduced [here](https://github.com/ChipWolf/renovate-4626).

**Comment by titilambert** [comment]
I have the same issue renovate version 23.55.3
I just know that quay.io API is quite different than the dockerhub one...

**Comment by MaronHatoum** [comment]
not reproducible, reproduction repo: https://github.com/MaronHatoum/renovate-4626/pulls
Logs from the last run: 
```
INFO: Dependency extraction complete (repository=MaronHatoum/renovate-4626)
       "baseBranch": "master",
       "stats": {
         "managers": {
           "cloudbuild": {"fileCount": 1, "depCount": 1},
           "regex": {"fileCount": 1, "depCount": 1}
         },
         "total": {"fileCount": 2, "depCount": 2}
       }
DEBUG: getLabels(https://quay.io, helmpack/chart-testing, latest) (repository=MaronHatoum/renovate-4626)
DEBUG: getManifestResponse(https://quay.io, helmpack/chart-testing, latest) (repository=MaronHatoum/renovate-4626)
DEBUG: getManifestResponse(https://quay.io, helmpack/chart-testing, sha256:61cef8158b5190e40b454ba9f116c6adcf4aa4ff97fa6f9c0486ecbfea393b96) (repository=MaronHatoum/renovate-4626)
DEBUG: found labels in manifest (repository=MaronHatoum/renovate-4626)
       "labels": {
         "helm_version": "v3.9.2",
         "kubectl_version": "v1.24.3",
         "org.opencontainers.image.authors": "The Helm Authors",
         "org.opencontainers.image.created": "2022-07-27T09:59:09Z",
         "org.opencontainers.image.description": "ct - The chart testing tool",
         "org.opencontainers.image.licenses": "Apache-2.0",
         "org.opencontainers.image.revision": "1d3feac8e5ca55ccf11521ff297ccee7f09aa749",
         "org.opencontainers.image.source": "https://github.com/helm/chart-testing",
         "org.opencontainers.image.title": "chart-testing",
         "org.opencontainers.image.vendor": "Helm",
         "org.opencontainers.image.version": "3.7.0",
         "yamale_version": "4.0.0",
         "yamllint_version": "1.26.3"
       }
```
- I think we can close this issue.
