### ISSUE TITLE
Invalid URL for helm charts when using placeholders

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4680]
err:

```
{
        "input": "@stable",
        "message": "Invalid URL: @stable",
        "stack": "TypeError [ERR_INVALID_URL]: Invalid URL: @stable
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at doc.dependencies.map.dep (/home/ubuntu/renovateapp/node_modules/renovate/dist/manager/helm-requirements/extract.js:49:21)
    at Array.map (<anonymous>)
    at Object.extractPackageFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/manager/helm-requirements/extract.js:43:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
    }
```

Either:
(a) we should skip/ignore invalid URLs, or
(b) we should find what`@stable` is referencing

**Comment by rarkins** [comment]
Here's an example from a [public repo](https://github.com/AXOOM/Templates.WebService/blob/master/content/charts/myvendor-myservice/requirements.yaml):

```yaml
dependencies:
  - name: generic-service
    version: 5.0.2
    repository: '@axoom-github'
    alias: app
```

Which appears to be referenced here: https://github.com/AXOOM/Templates.WebService/blob/b7fca8e6a8aa94283a4aa4a1a98c92d77d6d4f55/content/helmfile.yaml#L6-L8

This seems a little complex so I think let's start by skipping placeholders and then finish by adding full support.

**Comment by rarkins** [comment]
Fix in progress
