### ISSUE TITLE
Renovate gives up after first failed update of Ruby Bundler package

### ISSUE THREAD

**Issue by happy-river** [renovatebot/renovate#4747]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitLab

### Have you checked the logs? Don't forget to include them if relevant

Here's the package that fails.  It's trying to update the gem `http` from v3 to v4 and it fails because of another gem in the Gemfile, `goldfinger` which does not have an available version supporting `http` v4.

```
WARN: Failed to generate Gemfile.lock (unknown error)(branch="renovate/http-4.x")
{
  "err": {
    "killed": false,
    "code": 6,
    "signal": null,
    "cmd": "docker run --rm -v /mnt/renovate/gl/spinster-xyz/spinster:/mnt/renovate/gl/spinster-xyz/spinster -w /mnt/renovate/gl/spinster-xyz/spinster renovate/ruby:2.7.0-preview2 bash -l -c \"ruby --version && gem install bundler -v 1.17.3 --no-document && bundle lock --update http\"",
    "stdout": "ruby 2.7.0preview2 (2019-10-22 master 02aadf1032) [x86_64-linux]\nSuccessfully installed bundler-1.17.3\n1 gem installed\nFetching https://github.com/rtomayko/posix-spawn\nFetching https://github.com/tmm1/http_parser.rb\nFetching gem metadata from https://rubygems.org/...........\nFetching gem metadata from https://rubygems.org/..\nResolving dependencies...........\nBundler could not find compatible versions for gem \"http\":\n  In Gemfile:\n    http (~> 4.2.0)\n\n    goldfinger (~> 2.1) was resolved to 2.1.0, which depends on\n      http (~> 3.0)\n",
    "stderr": "Unable to find image 'renovate/ruby:2.7.0-preview2' locally\n2.7.0-preview2: Pulling from renovate/ruby\n5667fdb72017: Already exists\nd83811f270d5: Already exists\nee671aafb583: Already exists\n7fc152dfb3a6: Already exists\nf6d4efe25c50: Already exists\n4882dc756fb8: Already exists\nc8b07aef7970: Pulling fs layer\nff93e93f38ca: Pulling fs layer\n18a289b10325: Pulling fs layer\n52e1db56de04: Pulling fs layer\nc332fb2fe43c: Pulling fs layer\nbd8dd5ee1f75: Pulling fs layer\n52e1db56de04: Waiting\nc332fb2fe43c: Waiting\nbd8dd5ee1f75: Waiting\nff93e93f38ca: Verifying Checksum\nff93e93f38ca: Download complete\nc8b07aef7970: Verifying Checksum\nc8b07aef7970: Download complete\nc332fb2fe43c: Verifying Checksum\nc332fb2fe43c: Download complete\n18a289b10325: Verifying Checksum\n18a289b10325: Download complete\n52e1db56de04: Verifying Checksum\n52e1db56de04: Download complete\nbd8dd5ee1f75: Verifying Checksum\nbd8dd5ee1f75: Download complete\nc8b07aef7970: Pull complete\nff93e93f38ca: Pull complete\n18a289b10325: Pull complete\n52e1db56de04: Pull complete\nc332fb2fe43c: Pull complete\nbd8dd5ee1f75: Pull complete\nDigest: sha256:ea2a86286e53093e562f6f9015a89d514e90fac7b32dbc34b7f4d48e0e31a633\nStatus: Downloaded newer image for renovate/ruby:2.7.0-preview2\n",
    "message": "Command failed: docker run --rm -v /mnt/renovate/gl/spinster-xyz/spinster:/mnt/renovate/gl/spinster-xyz/spinster -w /mnt/renovate/gl/spinster-xyz/spinster renovate/ruby:2.7.0-preview2 bash -l -c \"ruby --version && gem install bundler -v 1.17.3 --no-document && bundle lock --update http\"\nUnable to find image 'renovate/ruby:2.7.0-preview2' locally\n2.7.0-preview2: Pulling from renovate/ruby\n5667fdb72017: Already exists\nd83811f270d5: Already exists\nee671aafb583: Already exists\n7fc152dfb3a6: Already exists\nf6d4efe25c50: Already exists\n4882dc756fb8: Already exists\nc8b07aef7970: Pulling fs layer\nff93e93f38ca: Pulling fs layer\n18a289b10325: Pulling fs layer\n52e1db56de04: Pulling fs layer\nc332fb2fe43c: Pulling fs layer\nbd8dd5ee1f75: Pulling fs layer\n52e1db56de04: Waiting\nc332fb2fe43c: Waiting\nbd8dd5ee1f75: Waiting\nff93e93f38ca: Verifying Checksum\nff93e93f38ca: Download complete\nc8b07aef7970: Verifying Checksum\nc8b07aef7970: Download complete\nc332fb2fe43c: Verifying Checksum\nc332fb2fe43c: Download complete\n18a289b10325: Verifying Checksum\n18a289b10325: Download complete\n52e1db56de04: Verifying Checksum\n52e1db56de04: Download complete\nbd8dd5ee1f75: Verifying Checksum\nbd8dd5ee1f75: Download complete\nc8b07aef7970: Pull complete\nff93e93f38ca: Pull complete\n18a289b10325: Pull complete\n52e1db56de04: Pull complete\nc332fb2fe43c: Pull complete\nbd8dd5ee1f75: Pull complete\nDigest: sha256:ea2a86286e53093e562f6f9015a89d514e90fac7b32dbc34b7f4d48e0e31a633\nStatus: Downloaded newer image for renovate/ruby:2.7.0-preview2\n",
    "stack": "Error: Command failed: docker run --rm -v /mnt/renovate/gl/spinster-xyz/spinster:/mnt/renovate/gl/spinster-xyz/spinster -w /mnt/renovate/gl/spinster-xyz/spinster renovate/ruby:2.7.0-preview2 bash -l -c \"ruby --version && gem install bundler -v 1.17.3 --no-document && bundle lock --update http\"\nUnable to find image 'renovate/ruby:2.7.0-preview2' locally\n2.7.0-preview2: Pulling from renovate/ruby\n5667fdb72017: Already exists\nd83811f270d5: Already exists\nee671aafb583: Already exists\n7fc152dfb3a6: Already exists\nf6d4efe25c50: Already exists\n4882dc756fb8: Already exists\nc8b07aef7970: Pulling fs layer\nff93e93f38ca: Pulling fs layer\n18a289b10325: Pulling fs layer\n52e1db56de04: Pulling fs layer\nc332fb2fe43c: Pulling fs layer\nbd8dd5ee1f75: Pulling fs layer\n52e1db56de04: Waiting\nc332fb2fe43c: Waiting\nbd8dd5ee1f75: Waiting\nff93e93f38ca: Verifying Checksum\nff93e93f38ca: Download complete\nc8b07aef7970: Verifying Checksum\nc8b07aef7970: Download complete\nc332fb2fe43c: Verifying Checksum\nc332fb2fe43c: Download complete\n18a289b10325: Verifying Checksum\n18a289b10325: Download complete\n52e1db56de04: Verifying Checksum\n52e1db56de04: Download complete\nbd8dd5ee1f75: Verifying Checksum\nbd8dd5ee1f75: Download complete\nc8b07aef7970: Pull complete\nff93e93f38ca: Pull complete\n18a289b10325: Pull complete\n52e1db56de04: Pull complete\nc332fb2fe43c: Pull complete\nbd8dd5ee1f75: Pull complete\nDigest: sha256:ea2a86286e53093e562f6f9015a89d514e90fac7b32dbc34b7f4d48e0e31a633\nStatus: Downloaded newer image for renovate/ruby:2.7.0-preview2\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  }
}
```
And here's what happens later in the log, when trying to create a PR for the next Ruby package that needs an update:

```
DEBUG: bundler.updateArtifacts(Gemfile)(branch="renovate/puma-4.x")
INFO: Aborting Bundler artifacts due to previous failed attempt(branch="renovate/puma-4.x")
```

### What is your question?

I think this is a bug. Bundler is failing because there is no current set of package versions that will work with an updated `http` so that error should be recorded in the Renovate master issue so a developer can figure out what to do.  But in the last few lines of `renovate/lib/manager/bundler/artifacts.ts`, it sets `global.repoCache.bundlerArtifactsError` which causes all subsequent `bundler` package updates to fail, even though the error was specific to the package being attempted.

**Comment by rarkins** [comment]
This is deliberate, but maybe it’s time to remove it.
