### ISSUE TITLE
YAML exception (travis): unexpected end of the stream within a single quoted scalar

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4867]
```json
    "err": {
        "name": "YAMLException",
        "reason": "unexpected end of the stream within a single quoted scalar",
        "mark": {
            "name": null,
            "buffer": "language: node_js\nnode_js:\n  - '8'\n  - '10'\n  - '12\n\u0000",
            "position": 52,
            "line": 5,
            "column": 0
        },
        "message": "unexpected end of the stream within a single quoted scalar at line 6, column 1:\n    \n    ^",
        "stack": "YAMLException: unexpected end of the stream within a single quoted scalar at line 6, column 1:\n    \n    ^\n    at generateError (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)\n    at throwError (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)\n    at readSingleQuotedScalar (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:586:3)\n    at composeNode (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:1364:13)\n    at readBlockMapping (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:1036:16)\n    at composeNode (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)\n    at readBlockSequence (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:955:5)\n    at composeNode (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:1358:12)\n    at readBlockMapping (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)\n    at composeNode (/home/ubuntu/renovateapp/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)"
    },
```

**Comment by rarkins** [comment]
Looks like the `12` is missing its trailing `'`. I guess that's an invalid file and we should keep skipping it?
