### ISSUE TITLE
Jest: "Call retries were exceeded" with Node v13

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#4917]
**What Renovate type are you using?**

Self-hosted

**Describe the bug**

Jest test run fails on Node v13

**Did you see anything helpful in debug logs?**

```
Summary of all failing tests
test/workers/global/autodiscover.spec.ts

    Call retries were exceeded
      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

test/datasource/npm/index.spec.ts
    Call retries were exceeded
      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

test/platform/index.spec.ts
    Call retries were exceeded
      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

test/platform/git/storage.spec.ts
    Call retries were exceeded
      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

test/workers/repository/process/lookup/index.spec.js
    Call retries were exceeded
      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

test/workers/global/index.spec.ts
    Call retries were exceeded
      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
```

**To Reproduce**

`yarn jest`

**Comment by rarkins** [comment]
Unless this is an easy fix, let’s wait for node 13 to be more stable
