### ISSUE TITLE
Receiving sporadic npm registry failures when newly onboarding a repository

### ISSUE THREAD

**Issue by peterjuras** [renovatebot/renovate#5402]
**What Renovate type are you using?**

Hosted App on GitHub

**Describe the bug**

I'm receiving multiple registry-errors, not always for the same package but it stops renovate from being configured correctly and opening PRs. I'm also a bit stuck since there is no "retry" button on the hosted dashboard, unless I'm missing something here.

**Did you see anything helpful in debug logs?**

This is the part of the log that shows the error:

```
INFO: Found npm package files
DEBUG: Using file match: \.(?:cs|fs|vb)proj$ for manager nuget
DEBUG: Using file match: ^.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup
DEBUG: pipenv is disabled
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Using file match: \.sbt$ for manager sbt
DEBUG: Using file match: project/[^/]*.scala$ for manager sbt
DEBUG: Using file match: (^|/)Package\.swift for manager swift
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: Using file match: ^.travis.yml$ for manager travis
DEBUG: Found 6 package file(s)
DEBUG: manager.fetchUpdates()
DEBUG: Dependency mhart/alpine-node has unsupported value slim-12.14.1
DEBUG: getLabels(https://index.docker.io, mhart/alpine-node, latest)
DEBUG: getManifestResponse(https://index.docker.io, mhart/alpine-node, latest)
WARN: npm registry failure
{
  "err": {
    "name": "RequestError",
    "code": "ECONNRESET",
    "host": "registry.npmjs.org",
    "hostname": "registry.npmjs.org",
    "method": "GET",
    "path": "/@graphql-codegen%2Ftypescript-react-apollo",
    "protocol": "https:",
    "url": "https://registry.npmjs.org/@graphql-codegen%2Ftypescript-react-apollo",
    "gotOptions": {
      "path": "/@graphql-codegen%2Ftypescript-react-apollo",
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "registry.npmjs.org",
      "port": null,
      "hostname": "registry.npmjs.org",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/@graphql-codegen%2Ftypescript-react-apollo",
      "href": "https://registry.npmjs.org/@graphql-codegen%2Ftypescript-react-apollo",
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "authorization": "** redacted **",
        "cache-control": "no-cache",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate"
      },
      "hooks": {
        "beforeError": [],
        "init": [],
        "beforeRequest": [],
        "beforeRedirect": [],
        "beforeRetry": [],
        "afterResponse": []
      },
      "retry": {
        "methods": {},
        "statusCodes": {},
        "errorCodes": {}
      },
      "decompress": true,
      "throwHttpErrors": true,
      "followRedirect": true,
      "stream": false,
      "form": false,
      "json": true,
      "cache": false,
      "useElectronNet": false,
      "method": "GET"
    },
    "message": "read ECONNRESET",
    "stack": "RequestError: read ECONNRESET\n    at ClientRequest.request.once.error (/home/ubuntu/renovateapp/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/home/ubuntu/renovateapp/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)"
  },
  "regUrl": "https://registry.npmjs.org/",
  "depName": "@graphql-codegen/typescript-react-apollo"
}
INFO: Registry error - skipping
```

In this log, it was `@graphql-codegen/typecript-react-apollo` that threw the error, before that I also had a job run with `/@graphql-codegen/cli`.

**To Reproduce**

I haven't found a way to reproduce this reliably yet.

**Additional context**

**Comment by rarkins** [comment]
I dug into our logs and noticed we get around 100 ECONNRESET errors a day from npm and all are due to scoped packages. I have contacted npm in case they are interested in troubleshooting this, but otherwise I'm going to see if we should be adding some retries in such cases.

**Comment by rarkins** [comment]
If you can tell me the repository or a job ID then I can enqueue a manual retry for you today. Otherwise onboarding is only retried daily unless there's a commit in the default branch for any "interesting" file like `package.json`, `pom.xml`, `renovate.json`, etc.

**Comment by peterjuras** [comment]
Thanks, I updated the renovate.json and it appears to work for now.

Is this a known issue and can I do something to circumvent this?

**Comment by rarkins** [comment]
These are known issues:
- Renovate retries onboarding PRs daily
- npmjs can sometimes return errors that are their fault
- Renovate aborts a repository run if npmjs is returning errors

But there is nothing you can do to circumvent those.
