### ISSUE TITLE
Sudden appearance of a large number of registry-failure events related to npm registry

### ISSUE THREAD

**Issue by esetnik** [renovatebot/renovate#5470]
**What Renovate type are you using?**

Gitlab

**Describe the bug**
https://app.renovatebot.com/dashboard#gitlab/redacted/140765383

**Did you see anything helpful in debug logs?**
The log output is enormous but appears to be truncation of a huge JSON response from the npm registry.

```
...
:thought_balloon: |\\n| [`@typescript-eslint/no-use-before-define`](./docs/rules/no-use-before-define.md)                         | Disallow the use of variables before they are defined                                                                                               | :heavy_check_mark: |          |                   |\\n| [`@typescript-eslint/no-useless-constructor`](./docs/rules/no-useless-constructor.md)                     | Disallow unnecessary constructors                                                                                                                   |                    |          |                   |\\n| [`@typescript-eslint/no-var-requires`](./docs/rules/no-var-requires.md)                                   | Disallows the use of require statements except in import statements                                                                                 | :heavy_check_mark: |          |                   |\\n| [`@typescript-eslint/prefer-for-of`](./docs/rules/prefer-for-of.md)                                       | Prefer a ‘for-of’ loop over a standard ‘for’ loop if the index is only used to access the array being iterated                                      |                    |          |                   |\\n| [`@typescript-eslint/prefer-function-type`](./docs/rules/prefer-function-type.md)                         | Use function types instead of interfaces with call signatures                                                                                       |                    | :wrench: |                   |\\n| [`@typescript-eslint/prefer-includes`](./docs/rules/prefer-includes.md)                                   | Enforce `includes` method over `indexOf` method                                                                                                     | :heavy_check_mark: | :wrench: | :thought_balloon: |\\n| [`@typescript-eslint/prefer-namespace-keyword`](./docs/rules/prefer-namespace-keyword.md)                 | Require the use of the `namespace` keyword instead of the `module` keyword to declare custom TypeScript modules                                     | :heavy_check_mark: | :wrench: |                   |\\n| [`@typescript-eslint/prefer-nullish-coalescing`](./docs/rules/prefer-nullish-coalescing.md)               | Enforce the usage of the nullish coalescing operator instead of logical chaining                                                                    |                    | :wrench: | :thought_balloon: |\\n| [`@typescript-eslint/prefer-optional-chain`](./docs/rules/prefer-optional-chain.md)                       | Prefer using concise optional chain expressions instead of chained logical ands                                                                     |                    | :wrench: |                   |\\n| [`@typescript-eslint/prefer-readonly`](./docs/rules/prefer-readonly.md)                                   | Requires that private members are marked as `readonly` if they're never modified outside of the constructor                                         |                    | :wrench: | :thought_balloon: |\\n| [`@typescript-eslint/prefer-regexp-exec`](./docs/rules/prefer-regexp-exec.md)                             | Prefer RegExp#exec() over String#match() if no global flag is provided                                                                              | :heavy_check_mark: |          | :thought_balloon: |\\n| [`@typescript-eslint/prefer-string-starts-ends-with`](./docs/rules/prefer-string-starts-ends-with.md)     | Enforce the use of `String#startsWith` and `String#endsWith` instead of other equivalent methods of checking substrings                             | :heavy_check_mark: | :wrench: | :thought_balloon: |\\n| [`@typescript-eslint/promise-function-async`](./docs/rules/promise-function-async.md)                     | Requires any function or method that returns a Promise to be marked async                                                                           |                    |          | :thought_balloon: |\\n| [`@typescript-eslint/quotes`](./docs/rules/quotes.md)                                                     | Enforce the consistent use of either backticks, double, or single quotes                                                                            |                    | :wrench: |                   |\\n| [`@typescript-eslint/require-array-sort-compare`](./docs/rules/require-array-sort-compare.md)             | Enforce giving `compare` argument to `Array#sort`                                                                                                   |                    |          | :thought_balloon: |\\n| [`@typescript-eslint/require-await`](./docs/rules/require-await.md)                                       | Disallow async functions which have no `await` expression                                                                                           | :heavy_check_mark: |          | :thought_balloon: |\\n| [`@typescript-eslint/restrict-plus-operands`](./docs/rules/restrict-plus-operands.md)                     | When adding two variable",
    "message": "Unexpected end of JSON input in \"https://**redacted**@typescript-eslint%2Feslint-plugin\": \n{\"_id\":\"@typescript-eslint/eslint-plugin\",\"_rev\":\"570-4380cdd8c0741054e9633b5...",
    "stack": "ParseError: Unexpected end of JSON input in \"https://**redacted**@typescript-eslint%2Feslint-plugin\": \n{\"_id\":\"@typescript-eslint/eslint-plugin\",\"_rev\":\"570-4380cdd8c0741054e9633b5...\n    at EventEmitter. (/home/ubuntu/renovateapp/node_modules/got/source/as-promise.js:65:26)\n    at runMicrotasks ()\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  },
  "errorCodes": "[Circular]",
  "statusCodes": "[Circular]",
  "regUrl": "https://registry.npmjs.org",
  "depName": "@typescript-eslint/eslint-plugin"
```

140765383

**To Reproduce**
It's been failing every hour or two for the last 24 hours and working intermittently in between.

**Additional context**
It looks like the npm registry is returning a huge readme response for the package `@typescript-eslint/eslint-plugin`

npm is currently reporting a service disruption / incident https://status.npmjs.org/incidents/lvgmcrfvrvsh but it doesn't appear directly related to this issue (at least from the incident description).

**Comment by rarkins** [comment]
Please follow in https://github.com/renovatebot/app-support/issues/28 instead
