### ISSUE TITLE
Can't find scoped package in private repo when using .yarnrc

### ISSUE THREAD

**Issue by BryanHunt** [renovatebot/renovate#5821]
### Which Renovate are you using?

Renovate Open Source CLI
### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

The logs say the same thing that the MR does.  It couldn't find the scoped package in our private repo.

### What would you like to do?

I'm trying to onboard a new repository that uses a scoped package that is in our private repository.  Looking at the logs, renovate is trying to fetch the package from the public npm repo instead of our private repo configured in the .yarnrc.

**Comment by rarkins** [comment]
@BryanHunt No need - I've transferred this issue itself into the main repo and classified as a bug

**Comment by rarkins** [comment]
Needs reproduction repo / `.yarnrc`

**Comment by HonzaMac** [comment]
It fails as well on our private npm registry. 
`.yarnrc`:
```
registry "https://artifacts.company.com/artifactory/api/npm/npm-main-dev/"
```

Message from logstash: `Dependency lookup failure: not found`
```
{
    "msg": [
      "Dependency lookup failure: not found"
    ],
    "repository": [
      "company/repo-web"
    ],
    "type": [
      "js_community_uat"
    ],
    "hostname": [
      "jenkins-agent-default-1-us-east-1-production"
    ],
    "err.options.password": [
      ""
    ],
    "err.options.url": [
      "https://registry.npmjs.org/@sad%2Fsharepoint-tools"
    ],
    "level": [
      20
    ],
    "err.response.body.error": [
      "Not found"
    ],
    "err.options.headers.user-agent": [
      "RenovateBot/25.52.5 (https://github.com/renovatebot/renovate)"
    ],
    "err.response.headers.date": [
      "Wed, 07 Jul 2021 06:30:28 GMT"
    ],
    "err.message": [
      "Response code 404 (Not Found)"
    ],
    "name": [
      "renovate"
    ],
    "err.response.headers.server": [
      "cloudflare"
    ],
    "err.options.headers.accept": [
      "application/json"
    ],
    "err.name": [
      "HTTPError"
    ],
    "@version": [
      "1"
    ],
    "packageName": [
      "@sad/sharepoint-tools"
    ],
    "err.response.statusCode": [
      404
    ],
    "err.options.username": [
      ""
    ],
    "err.response.httpVersion": [
      "1.1"
    ],
    "err.response.headers.content-type": [
      "application/json"
    ],
    "err.stack": [
      "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/opt/jenkins/.npm/_npx/3877809/lib/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
    ],
    "@timestamp": [
      "2021-07-07T06:32:17.372Z"
    ],
    "err.response.statusMessage": [
      "Not Found"
    ],
    "err.response.headers.expect-ct": [
      "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
    ]
  }
```
