### ISSUE TITLE
RE2 not usable, falling back to RegExp

### ISSUE THREAD

**Issue by philippe-granet** [renovatebot/renovate#6058]
**What Renovate type are you using?**

Self-hosting on GitLab inside a CI pipeline

**Describe the bug**

I recently upgrade renovate docker image from `renovate/renovate:19.216.7` to `renovate/renovate:19.219.3`  and now, I have this big warning in logs:

```
WARN: RE2 not usable, falling back to RegExp
       "err": {
         "code": "MODULE_NOT_FOUND",
         "requireStack": [
           "/usr/src/app/node_modules/renovate/dist/util/regex.js",
           "/usr/src/app/node_modules/renovate/dist/versioning/regex/index.js",
           "/usr/src/app/node_modules/renovate/dist/versioning/api.generated.js",
           "/usr/src/app/node_modules/renovate/dist/versioning/index.js",
           "/usr/src/app/node_modules/renovate/dist/config/definitions.js",
           "/usr/src/app/node_modules/renovate/dist/config/index.js",
           "/usr/src/app/node_modules/renovate/dist/workers/global/index.js",
           "/usr/src/app/node_modules/renovate/dist/renovate.js",
           "/usr/src/app/dist/renovate.js"
         ],
         "message": "Cannot find module 're2'\nRequire stack:\n- /usr/src/app/node_modules/renovate/dist/util/regex.js\n- /usr/src/app/node_modules/renovate/dist/versioning/regex/index.js\n- /usr/src/app/node_modules/renovate/dist/versioning/api.generated.js\n- /usr/src/app/node_modules/renovate/dist/versioning/index.js\n- /usr/src/app/node_modules/renovate/dist/config/definitions.js\n- /usr/src/app/node_modules/renovate/dist/config/index.js\n- /usr/src/app/node_modules/renovate/dist/workers/global/index.js\n- /usr/src/app/node_modules/renovate/dist/renovate.js\n- /usr/src/app/dist/renovate.js",
         "stack": "Error: Cannot find module 're2'\nRequire stack:\n- /usr/src/app/node_modules/renovate/dist/util/regex.js\n- /usr/src/app/node_modules/renovate/dist/versioning/regex/index.js\n- /usr/src/app/node_modules/renovate/dist/versioning/api.generated.js\n- /usr/src/app/node_modules/renovate/dist/versioning/index.js\n- /usr/src/app/node_modules/renovate/dist/config/definitions.js\n- /usr/src/app/node_modules/renovate/dist/config/index.js\n- /usr/src/app/node_modules/renovate/dist/workers/global/index.js\n- /usr/src/app/node_modules/renovate/dist/renovate.js\n- /usr/src/app/dist/renovate.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:862:27)\n    at Module.require (internal/modules/cjs/loader.js:1042:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Object.<anonymous> (/usr/src/app/node_modules/renovate/dist/util/regex.js:8:17)\n    at Module._compile (internal/modules/cjs/loader.js:1156:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)\n    at Module.load (internal/modules/cjs/loader.js:1000:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:899:14)\n    at Module.require (internal/modules/cjs/loader.js:1042:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Object.<anonymous> (/usr/src/app/node_modules/renovate/dist/versioning/regex/index.js:5:17)\n    at Module._compile (internal/modules/cjs/loader.js:1156:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)\n    at Module.load (internal/modules/cjs/loader.js:1000:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:899:14)\n    at Module.require (internal/modules/cjs/loader.js:1042:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Object.<anonymous> (/usr/src/app/node_modules/renovate/dist/versioning/api.generated.js:25:28)\n    at Module._compile (internal/modules/cjs/loader.js:1156:30)"
       }
```

**Comment by viceice** [comment]
Can you share a minimal gitlab pipeline file please

**Comment by philippe-granet** [comment]
Yes, of course:
```yaml
renovate:
  image: 
    name: renovate/renovate:19.219.3
    entrypoint: [""]
  stage: build
  script:
    - cp config.js /usr/src/app/config.js
    - node /usr/src/app/dist/renovate.js
```
