### ISSUE TITLE
Failed to fetch config with renovate:19.221-slim docker image

### ISSUE THREAD

**Issue by SkReD** [renovatebot/renovate#6086]
**What Renovate type are you using?**

 self-hosted Renovate

**Describe the bug**

According to log it is cannot fetch config from github

**Did you see anything helpful in debug logs?**

Full log
```
 FATAL: Fatal error: platform-failure
        "err": {
          "message": "platform-failure",
          "stack": "Error: platform-failure\n    at fetchJSONFile (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:31:19)\n    at getPresetFromEndpoint (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:80:29)\n    at Object.getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:94:12)\n    at getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:141:58)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:194:43)\n    at Object.parseConfigs (/usr/src/app/node_modules/renovate/dist/config/index.js:48:40)\n    at async Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:62:22)\n    at async /usr/src/app/node_modules/renovate/dist/renovate.js:16:24"
        }
  INFO: Renovate is exiting with a non-zero code due to the following logged errors
        "loggerErrors": [
          {
            "name": "renovate",
            "level": 60,
            "logContext": "fIWStxLEF",
            "err": {
              "message": "platform-failure",
              "stack": "Error: platform-failure\n    at fetchJSONFile (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:31:19)\n    at getPresetFromEndpoint (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:80:29)\n    at Object.getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:94:12)\n    at getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:141:58)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:194:43)\n    at Object.parseConfigs (/usr/src/app/node_modules/renovate/dist/config/index.js:48:40)\n    at async Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:62:22)\n    at async /usr/src/app/node_modules/renovate/dist/renovate.js:16:24"
            },
            "msg": "Fatal error: platform-failure"
          }
        ]
```

**To Reproduce**

I think you just need to renovate config which is extending default `config:base` or another config, which should be loaded from github.

**Additional context**

Error introduced in `renovate:19.221-slim`. `renovate:19.220-slim` runs without errors

**Comment by viceice** [comment]
Should be fixed with [19.221.1](https://github.com/renovatebot/renovate/releases/tag/19.221.1)

**Comment by SkReD** [comment]
Try `19.221.1` with no luck

**Comment by viceice** [comment]
see #6088
