### ISSUE TITLE
Nodejs update fails with pinDigests enabled

### ISSUE THREAD

**Issue by schuch** [renovatebot/renovate#6101]
**What Renovate type are you using?**

Github App
```
INFO: Repository started
{
  "renovateVersion": "19.225.1"
}
```

**Describe the bug**
Renovate fails to raise a pull request for new nodejs versions (https://docs.renovatebot.com/node/) declared in the `engines` field in  `package.json` 

**Did you see anything helpful in debug logs?**

```
DEBUG: Error getting tag commit from GitHub repo
{
  "githubRepo": "nodejs/node",
  "err": {
    "name": "HTTPError",
    "hostname": "api.github.com",
    "method": "GET",
    "path": "/repos/nodejs/node/git/refs/tags/12.16.3",
    "protocol": "https:",
    "url": "https://api.github.com/repos/nodejs/node/git/refs/tags/12.16.3",
    "gotOptions": {
      "path": "/repos/nodejs/node/git/refs/tags/12.16.3",
      "protocol": "https:",
      "hostname": "api.github.com",
      "hash": "",
      "search": "",
      "pathname": "/repos/nodejs/node/git/refs/tags/12.16.3",
      "href": "https://api.github.com/repos/nodejs/node/git/refs/tags/12.16.3",
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept": "application/vnd.github.machine-man-preview+json",
        "accept-encoding": "gzip, deflate",
        "authorization": "** redacted **"
      },
      "hooks": {
        "beforeError": [],
        "init": [],
        "beforeRequest": [],
        "beforeRedirect": [],
        "beforeRetry": [],
        "afterResponse": []
      },
      "retry": {
        "methods": {},
        "statusCodes": {},
        "errorCodes": {}
      },
      "decompress": true,
      "throwHttpErrors": true,
      "followRedirect": true,
      "stream": false,
      "form": false,
      "json": true,
      "cache": false,
      "useElectronNet": false,
      "hostType": "github",
      "baseUrl": "https://api.github.com/",
      "method": "GET"
    },
    "statusCode": 404,
    "statusMessage": "Not Found",
    "headers": {
      "date": "Thu, 30 Apr 2020 16:50:29 GMT",
      "content-type": "application/json; charset=utf-8",
      "transfer-encoding": "chunked",
      "connection": "close",
      "server": "GitHub.com",
      "status": "404 Not Found",
      "x-ratelimit-limit": "5000",
      "x-ratelimit-remaining": "4997",
      "x-ratelimit-reset": "1588268660",
      "x-poll-interval": "300",
      "x-github-media-type": "github.machine-man-preview; format=json",
      "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
      "access-control-allow-origin": "*",
      "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
      "x-frame-options": "deny",
      "x-content-type-options": "nosniff",
      "x-xss-protection": "1; mode=block",
      "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
      "content-security-policy": "default-src 'none'",
      "vary": "Accept-Encoding, Accept, X-Requested-With",
      "content-encoding": "gzip",
      "x-github-request-id": "C69E:5F93:51B73:627D6:5EAB01D4"
    },
    "body": {
      "message": "Not Found",
      "documentation_url": "https://developer.github.com/v3/git/refs/#get-a-reference"
    },
    "message": "Response code 404 (Not Found)",
    "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter. (/home/ubuntu/renovateapp/node_modules/got/source/as-promise.js:74:19)\n    at runMicrotasks ()\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
  }
}
DEBUG: Could not getDigest
{
  "newValue": "12.16.3"
}
```
https://app.renovatebot.com/dashboard#github/schuch/renovate-nodejs/171118282

**To Reproduce**
see greenfield repo https://github.com/schuch/renovate-nodejs

pull request https://github.com/schuch/renovate-nodejs/pull/2 was autoclosed when `pinDigests` was enabled.

**Additional context**
I think the request to https://api.github.com/repos/nodejs/node/git/refs/tags/12.16.3 should be https://api.github.com/repos/nodejs/node/git/refs/tags/v12.16.3

**Comment by rarkins** [comment]
If you were enabling `pinDigests` for docker purposes, you can work around this by configuring it like this:

```json
{
  "docker": {
    "pinDigests": true
  }
}
```

**Comment by schuch** [comment]
Seems to be solved, i am not able to reproduce this.
