### ISSUE TITLE
platform-failure when running renovate

### ISSUE THREAD

**Issue by gmariotti** [renovatebot/renovate#6104]
**What Renovate type are you using?**

Self-Hosted, version 19.225.1 but renovate stopped working since updating to 19.221.2

**Describe the bug**

Same error as in https://github.com/renovatebot/renovate/issues/6086

```
Running renovate bot
FATAL: Fatal error: platform-failure
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at fetchJSONFile (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:31:19)\n    at getPresetFromEndpoint (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:80:29)\n    at Object.getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:94:12)\n    at getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:141:58)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:194:43)\n    at Object.parseConfigs (/usr/src/app/node_modules/renovate/dist/config/index.js:48:40)\n    at async Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:62:22)\n    at async /usr/src/app/node_modules/renovate/dist/renovate.js:16:24"
       }
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "1SDG23-mu",
           "err": {
             "message": "platform-failure",
             "stack": "Error: platform-failure\n    at fetchJSONFile (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:31:19)\n    at getPresetFromEndpoint (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:80:29)\n    at Object.getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:94:12)\n    at getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:141:58)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:194:43)\n    at Object.parseConfigs (/usr/src/app/node_modules/renovate/dist/config/index.js:48:40)\n    at async Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:62:22)\n    at async /usr/src/app/node_modules/renovate/dist/renovate.js:16:24"
           },
           "msg": "Fatal error: platform-failure"
         }
       ]
```

**Did you see anything helpful in debug logs?**

**To Reproduce**

**Additional context**

The `config.js` is the following (redacted private stuff)
```javascript
module.exports = {
    endpoint: '**REDACTED**',
    platform: 'gitlab',
    logFileLevel: 'warn',
    logLevel: 'info',
    logFile: './renovate.log',
    onboarding: true,
    extends: ['config:base', ":semanticCommitTypeAll(fix)"],
    prHourlyLimit: 0,
    assignees: [
        "plutus-ci"
    ],
    labels: [
        'renovate',
        'dependencies'
    ],
    trustLevel: 'high',
    npmrc: process.env.NPMRC_CONTENT,
    hostRules: [
        {
            domainName: '**REDACTED**',
            username: 'plutus-ci',
            password: process.env.RENOVATE_TOKEN
        },
        {
            domainName: '**REDACTED**',
            username: process.env.ARTIFACTORY_USERNAME,
            password: process.env.ARTIFACTORY_PASSWORD
        },
        {
            domainName: '**REDACTED**',
            username: process.env.ARTIFACTORY_USERNAME,
            password: process.env.ARTIFACTORY_PASSWORD
        },
        {
            domainName: '**REDACTED**',
            username: process.env.ARTIFACTORY_USERNAME,
            password: process.env.ARTIFACTORY_PASSWORD
        }
    ],
    onboardingConfig: {
        extends: ['config:base', ":semanticCommitTypeAll(fix)"],
        prHourlyLimit: 0,
        prConcurrentLimit: 0,
        masterIssue: true,
        masterIssueAutoclose: true,
        assignees: [
            "plutus-ci"
        ],
        labels: [
            'renovate',
            'dependencies'
        ]
    },
    repositories: [
        **REDACTED**
    ],
};

```
Environment variables:
- ARTIFACTORY_PASSWORD
- ARTIFACTORY_USERNAME
- GITHUB_COM_TOKEN
- GITLAB_USER
- RENOVATE_TOKEN
- ARTIFACTORY_BASE_URL

**Comment by rarkins** [comment]
Please log at debug level from startup. Does it happen before the first repo is processed, or at the start of the first repo, etc?

**Comment by gmariotti** [comment]
My bad, the pipeline for 19.225.1 failed and I didn't realize. I rerun it and is now working fine.
