### ISSUE TITLE
Docker datasource fails with quay.io image

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#6195]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

#173578276
```json
{
  "registry": "https://quay.io",
  "dockerRepository": "helmpack/chart-testing",
  "err": {
    "name": "HTTPError",
    "host": "quay.io",
    "hostname": "quay.io",
    "method": "GET",
    "path": "/v2/helmpack/chart-testing/blobs/sha256:9bd606e7cb0450e6d7e1cd2152a48298cf6e0d78417d79a32e948bcca8e7dd15",
    "protocol": "https:",
    "url": "https://quay.io/v2/helmpack/chart-testing/blobs/sha256:9bd606e7cb0450e6d7e1cd2152a48298cf6e0d78417d79a32e948bcca8e7dd15",
    "gotOptions": {
      "path": "/v2/helmpack/chart-testing/blobs/sha256:9bd606e7cb0450e6d7e1cd2152a48298cf6e0d78417d79a32e948bcca8e7dd15",
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "quay.io",
      "port": null,
      "hostname": "quay.io",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/v2/helmpack/chart-testing/blobs/sha256:9bd606e7cb0450e6d7e1cd2152a48298cf6e0d78417d79a32e948bcca8e7dd15",
      "href": "https://quay.io/v2/helmpack/chart-testing/blobs/sha256:9bd606e7cb0450e6d7e1cd2152a48298cf6e0d78417d79a32e948bcca8e7dd15",
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "authorization": "** redacted **",
        "accept-encoding": "gzip, deflate"
      },
      "hooks": {
        "beforeError": [],
        "init": [],
        "beforeRequest": [],
        "beforeRedirect": [
          null
        ],
        "beforeRetry": [],
        "afterResponse": []
      },
      "retry": {
        "methods": {},
        "statusCodes": {},
        "errorCodes": {}
      },
      "decompress": true,
      "throwHttpErrors": true,
      "followRedirect": true,
      "stream": false,
      "form": false,
      "json": false,
      "cache": false,
      "useElectronNet": false,
      "method": "GET",
      "hostType": "docker"
    },
    "statusCode": 400,
    "statusMessage": "Bad Request",
    "headers": {
      "x-amz-request-id": "6A0<snip>7004",
      "x-amz-id-2": "cFmc8KCUsl<snip>kr30=",
      "content-type": "application/xml",
      "transfer-encoding": "chunked",
      "date": "Wed, 06 May 2020 15:26:50 GMT",
      "connection": "close",
      "server": "AmazonS3"
    },
    "body": "\nInvalidArgumentOnly one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specifiedAuthorizationBearer eyJhbGciO<snip>2SiIdKSkr30=",
    "message": "Response code 400 (Bad Request)",
    "stack": "HTTPError: Response code 400 (Bad Request)\n    at EventEmitter. (/home/ubuntu/renovateapp/node_modules/got/source/as-promise.js:74:19)\n    at runMicrotasks ()\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
  }
}
```

### What would you like to do?

I would like Renovate to find updates for Docker images hosted at quay.io, a popular Docker image registry.

**Comment by ChipWolf** [comment]
Duplicate of #4626
