### ISSUE TITLE
Unable to install renovate cli on Github Actions

### ISSUE THREAD

**Issue by mmoayyed** [renovatebot/renovate#6251]
**What Renovate type are you using?**

Renovate CLI installed as part of Github Actions CI.

**Describe the bug**

Unable to install/run renovate with:

```
node renovate --labels=Bot --git-author=renovatebot@apereo.org --git-fs=https --token=${RENOVATE_TOKEN} apereo/cas
```

Running node 12.16.3.

**Did you see anything helpful in debug logs?**

I can try with debug logs too; This is an except that might be useful:

```
2020-05-15T15:40:30.4240184Z npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
2020-05-15T15:40:47.2466935Z /opt/hostedtoolcache/node/12.16.3/x64/bin/renovate -> /opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/dist/renovate.js
2020-05-15T15:40:47.2469103Z /opt/hostedtoolcache/node/12.16.3/x64/bin/renovate-config-validator -> /opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/bin/config-validator.js
2020-05-15T15:40:47.3064451Z 
2020-05-15T15:40:47.3067741Z > dtrace-provider@0.8.8 install /opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/node_modules/dtrace-provider
2020-05-15T15:40:47.3068768Z > node-gyp rebuild || node suppress-error.js
2020-05-15T15:40:47.3069151Z 
2020-05-15T15:40:48.3384631Z make: Entering directory '/opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/node_modules/dtrace-provider/build'
2020-05-15T15:40:48.3406749Z   TOUCH Release/obj.target/DTraceProviderStub.stamp
2020-05-15T15:40:48.3455929Z make: Leaving directory '/opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/node_modules/dtrace-provider/build'
2020-05-15T15:40:48.4822892Z 
2020-05-15T15:40:48.4823991Z > re2@1.11.0 install /opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/node_modules/re2
2020-05-15T15:40:48.4825115Z > node-gyp rebuild
2020-05-15T15:40:48.4825226Z 
2020-05-15T15:40:48.8886284Z make: Entering directory '/opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/node_modules/re2/build'
2020-05-15T15:40:48.8910820Z   CXX(target) Release/obj.target/re2/lib/addon.o
2020-05-15T15:40:50.4665835Z   CXX(target) Release/obj.target/re2/lib/new.o
2020-05-15T15:40:52.4570623Z   CXX(target) Release/obj.target/re2/lib/exec.o
2020-05-15T15:40:53.2218078Z ../lib/exec.cc: In static member function â€˜static Nan::NAN_METHOD_RETURN_TYPE WrappedRE2::Exec(Nan::NAN_METHOD_ARGS_TYPE)â€™:
2020-05-15T15:40:53.2222179Z ../lib/exec.cc:116:67: warning: ignoring return value of â€˜v8::Maybe<bool> v8::Object::SetPrototype(v8::Local<v8::Context>, v8::Local<v8::Value>)â€™, declared with attribute warn_unused_result [-Wunused-result]
2020-05-15T15:40:53.2223013Z    (void)groups->SetPrototype(Nan::GetCurrentContext(), Nan::Null());
2020-05-15T15:40:53.2223306Z                                                                    ^
2020-05-15T15:40:53.2224492Z In file included from /home/runner/.cache/node-gyp/12.16.3/include/node/node.h:67:0,
2020-05-15T15:40:53.2224762Z                  from ../lib/./wrapped_re2.h:4,
2020-05-15T15:40:53.2224969Z                  from ../lib/exec.cc:1:
2020-05-15T15:40:53.2225951Z /home/runner/.cache/node-gyp/12.16.3/include/node/v8.h:3700:37: note: declared here
2020-05-15T15:40:53.2226249Z    V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
2020-05-15T15:40:53.2226492Z                                      ^~~~~~~~~~~~
2020-05-15T15:40:53.6944279Z   CXX(target) Release/obj.target/re2/lib/test.o
2020-05-15T15:40:54.7075075Z   CXX(target) Release/obj.target/re2/lib/match.o
2020-05-15T15:40:55.4658796Z ../lib/match.cc: In static member function â€˜static Nan::NAN_METHOD_RETURN_TYPE WrappedRE2::Match(Nan::NAN_METHOD_ARGS_TYPE)â€™:
2020-05-15T15:40:55.4661008Z ../lib/match.cc:131:68: warning: ignoring return value of â€˜v8::Maybe<bool> v8::Object::SetPrototype(v8::Local<v8::Context>, v8::Local<v8::Value>)â€™, declared with attribute warn_unused_result [-Wunused-result]
2020-05-15T15:40:55.4662238Z     (void)groups->SetPrototype(Nan::GetCurrentContext(), Nan::Null());
2020-05-15T15:40:55.4674849Z                                                                     ^
2020-05-15T15:40:55.4676846Z In file included from /home/runner/.cache/node-gyp/12.16.3/include/node/node.h:67:0,
2020-05-15T15:40:55.4677130Z                  from ../lib/./wrapped_re2.h:4,
2020-05-15T15:40:55.4677345Z                  from ../lib/match.cc:1:
2020-05-15T15:40:55.4677887Z /home/runner/.cache/node-gyp/12.16.3/include/node/v8.h:3700:37: note: declared here
2020-05-15T15:40:55.4678153Z    V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
2020-05-15T15:40:55.4678394Z                                      ^~~~~~~~~~~~
2020-05-15T15:40:56.0057360Z   CXX(target) Release/obj.target/re2/lib/replace.o
2020-05-15T15:40:56.7740806Z ../lib/replace.cc: In function â€˜Nan::Maybe<std::__cxx11::basic_string<char> > replace(const Nan::Callback*, const std::vector<re2::StringPiece>&, const re2::StringPiece&, const v8::Local<v8::Value>&, bool, const std::map<std::__cxx11::basic_string<char>, int>&)â€™:
2020-05-15T15:40:56.7742629Z ../lib/replace.cc:322:50: warning: ignoring return value of â€˜v8::Maybe<bool> v8::Object::SetPrototype(v8::Local<v8::Context>, v8::Local<v8::Value>)â€™, declared with attribute warn_unused_result [-Wunused-result]
2020-05-15T15:40:56.7744000Z    (void)groups->SetPrototype(context, Nan::Null());
2020-05-15T15:40:56.7744478Z                                                   ^
2020-05-15T15:40:56.7777109Z In file included from /home/runner/.cache/node-gyp/12.16.3/include/node/node.h:67:0,
2020-05-15T15:40:56.7777757Z                  from ../lib/./wrapped_re2.h:4,
2020-05-15T15:40:56.7778567Z                  from ../lib/replace.cc:1:
2020-05-15T15:40:56.7779725Z /home/runner/.cache/node-gyp/12.16.3/include/node/v8.h:3700:37: note: declared here
2020-05-15T15:40:56.7780484Z    V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
2020-05-15T15:40:56.7780754Z                                      ^~~~~~~~~~~~
2020-05-15T15:40:58.0389117Z   CXX(target) Release/obj.target/re2/lib/search.o
2020-05-15T15:40:59.0273299Z   CXX(target) Release/obj.target/re2/lib/split.o
2020-05-15T15:41:00.2038095Z   CXX(target) Release/obj.target/re2/lib/to_string.o
2020-05-15T15:41:01.1879654Z   CXX(target) Release/obj.target/re2/lib/accessors.o
2020-05-15T15:41:02.3848843Z   CXX(target) Release/obj.target/re2/lib/util.o
2020-05-15T15:41:03.4818726Z   CXX(target) Release/obj.target/re2/vendor/re2/bitstate.o
2020-05-15T15:41:04.7557178Z   CXX(target) Release/obj.target/re2/vendor/re2/compile.o
2020-05-15T15:41:06.7363980Z   CXX(target) Release/obj.target/re2/vendor/re2/dfa.o
2020-05-15T15:41:09.8183207Z   CXX(target) Release/obj.target/re2/vendor/re2/filtered_re2.o
2020-05-15T15:41:10.8447633Z   CXX(target) Release/obj.target/re2/vendor/re2/mimics_pcre.o
2020-05-15T15:41:12.0302677Z   CXX(target) Release/obj.target/re2/vendor/re2/nfa.o
2020-05-15T15:41:13.7774034Z   CXX(target) Release/obj.target/re2/vendor/re2/onepass.o
2020-05-15T15:41:15.0620253Z   CXX(target) Release/obj.target/re2/vendor/re2/parse.o
2020-05-15T15:41:17.9749415Z   CXX(target) Release/obj.target/re2/vendor/re2/perl_groups.o
2020-05-15T15:41:18.0203976Z   CXX(target) Release/obj.target/re2/vendor/re2/prefilter.o
2020-05-15T15:41:19.7416950Z   CXX(target) Release/obj.target/re2/vendor/re2/prefilter_tree.o
2020-05-15T15:41:22.6203974Z   CXX(target) Release/obj.target/re2/vendor/re2/prog.o
2020-05-15T15:41:24.9055884Z   CXX(target) Release/obj.target/re2/vendor/re2/re2.o
2020-05-15T15:41:27.4403790Z   CXX(target) Release/obj.target/re2/vendor/re2/regexp.o
2020-05-15T15:41:30.5798675Z   CXX(target) Release/obj.target/re2/vendor/re2/set.o
2020-05-15T15:41:32.2918828Z   CXX(target) Release/obj.target/re2/vendor/re2/simplify.o
2020-05-15T15:41:33.9234138Z   CXX(target) Release/obj.target/re2/vendor/re2/stringpiece.o
2020-05-15T15:41:34.4439772Z   CXX(target) Release/obj.target/re2/vendor/re2/tostring.o
2020-05-15T15:41:35.4734412Z   CXX(target) Release/obj.target/re2/vendor/re2/unicode_casefold.o
2020-05-15T15:41:35.5168366Z   CXX(target) Release/obj.target/re2/vendor/re2/unicode_groups.o
2020-05-15T15:41:35.6152665Z   CXX(target) Release/obj.target/re2/vendor/util/pcre.o
2020-05-15T15:41:36.9124865Z   CXX(target) Release/obj.target/re2/vendor/util/rune.o
2020-05-15T15:41:36.9983391Z   CXX(target) Release/obj.target/re2/vendor/util/strutil.o
2020-05-15T15:41:37.4501582Z   SOLINK_MODULE(target) Release/obj.target/re2.node
2020-05-15T15:41:37.7189968Z   COPY Release/re2.node
2020-05-15T15:41:37.7368373Z make: Leaving directory '/opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/node_modules/re2/build'
2020-05-15T15:41:37.8118766Z 
2020-05-15T15:41:37.8120651Z > core-js@3.6.5 postinstall /opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/renovate/node_modules/core-js
2020-05-15T15:41:37.8121692Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T15:41:37.8122226Z 
2020-05-15T15:41:38.0367883Z + renovate@19.239.5
2020-05-15T15:41:38.0369077Z added 820 packages from 1165 contributors in 74.523s
2020-05-15T15:41:38.1500102Z internal/modules/cjs/loader.js:960
2020-05-15T15:41:38.1500455Z   throw err;
2020-05-15T15:41:38.1500630Z   ^
2020-05-15T15:41:38.1500712Z 
2020-05-15T15:41:38.1501629Z Error: Cannot find module '/home/runner/work/cas/cas/renovate'
2020-05-15T15:41:38.1501926Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
2020-05-15T15:41:38.1502181Z     at Function.Module._load (internal/modules/cjs/loader.js:840:27)
2020-05-15T15:41:38.1502445Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
2020-05-15T15:41:38.1502823Z     at internal/main/run_main_module.js:18:47 {
2020-05-15T15:41:38.1503321Z   code: 'MODULE_NOT_FOUND',
2020-05-15T15:41:38.1503488Z   requireStack: []
2020-05-15T15:41:38.1503637Z }
```
**To Reproduce**

You can see the full log here:

https://pipelines.actions.githubusercontent.com/YIqBZ3Wpkwgly4obJdABVIKMQNBl5SLi9faMZD1Mkue6VyBgGA/_apis/pipelines/1/runs/39/signedlogcontent/56?urlExpires=2020-05-15T15%3A44%3A55.5902844Z&urlSigningMethod=HMACV1&urlSignature=FwkLDyIwDv%2FRIvBoI5bc1nvVgR1yW9CMLgppGYTTYgU%3D

Not doing anything special, I don't think. Perhaps a node downgrade or upgrade is required?

**Comment by viceice** [comment]
You should use our official [github-action](https://github.com/renovatebot/github-action)

**Comment by mmoayyed** [comment]
Thanks very much for the prompt reply. Didn't know there was one! I will certainly try.

**Comment by mmoayyed** [comment]
One small question: if I already have a `.github/renovate.json` file, do I still need to specify the configuration JS file in the action? I'd assume not, and would expect the action to process my config in the old renovate.json file. Is that accurate?

**Comment by viceice** [comment]
you can set `configurationFile` to `.github/renovate.json` too, but `configurationFile`is required.

You can use a json file or a commonjs file

**Comment by viceice** [comment]
you need to put your renovate cli args to the `configurationFile` config file

**Comment by mmoayyed** [comment]
Thanks very much. All set.
