### ISSUE TITLE
Error "Failed to determine code owners for PR." when using assigneesFromCodeOwners

### ISSUE THREAD

**Issue by dschafhauser** [renovatebot/renovate#6432]
**What Renovate type are you using?**
Self-hosted via docker image 'renovate/renovate:20.25.5' on own GitLab instance.

**Describe the bug**

I've enabled the `assigneesFromCodeOwners` options as described in the docs:
https://docs.renovatebot.com/configuration-options/#assigneesfromcodeowners

However, renovate consistently fails to determine code owners for the PRs it creates.

**Did you see anything helpful in debug logs?**

```
WARN: Failed to determine code owners for PR. (repository=my-repository, branch=renovate/some-dependency-)
"err": {
  "message": "Cannot read property 'every' of null",
  "stack": "TypeError: Cannot read property 'every' of null
    at /usr/src/app/node_modules/renovate/dist/workers/pr/code-owners.js:35:59
    at Array.find (<anonymous>)
    at Object.codeOwnersForPr (/usr/src/app/node_modules/renovate/dist/workers/pr/code-owners.js:35:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async addCodeOwners (/usr/src/app/node_modules/renovate/dist/workers/pr/index.js:24:55)
    at async addAssigneesReviewers (/usr/src/app/node_modules/renovate/dist/workers/pr/index.js:29:21)
    at async Object.ensurePr (/usr/src/app/node_modules/renovate/dist/workers/pr/index.js:226:17)
    at async Object.processBranch (/usr/src/app/node_modules/renovate/dist/workers/branch/index.js:452:42)
    at async Object.writeUpdates (/usr/src/app/node_modules/renovate/dist/workers/repository/process/write.js:25:21)
    at async Object.update (/usr/src/app/node_modules/renovate/dist/workers/repository/process/extract-update.js:60:15)
    at async Object.renovateRepository (/usr/src/app/node_modules/renovate/dist/workers/repository/index.js:40:21)
    at async Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:94:13)
    at async /usr/src/app/node_modules/renovate/dist/renovate.js:28:24"
}
```

**To Reproduce**

I haven't set up a minimal example to reproduce yet.

**Additional context**

None.

**Comment by rarkins** [comment]
I've fixed this particular warning, but I suspect there may be *another* problem, because `prFiles` shouldn't be empty. Cc @fgreinacher
