### ISSUE TITLE
Git refs errors 

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#6512]
Source repo: https://github.com/lsst-sqre/roundtable

Triggers errors like:

```
    "repository": "lsst-sqre/roundtable",
    "err": {
        "message": "fatal: 'github.com/lsst-sqre/ltd-dasher.git' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
        "stack": "Error: fatal: 'github.com/lsst-sqre/ltd-dasher.git' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at toError (/home/ubuntu/renovateapp/node_modules/simple-git/promise.js:90:14)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/promise.js:61:36\n    at Git.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:725:18)\n    at Function.Git.fail (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1475:18)\n    at fail (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1433:20)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1442:16\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    },
    "msg": "Git-Raw-Refs lookup error in github.com/lsst-sqre/ltd-dasher.git",
```

**Comment by rarkins** [comment]
Now lowered error to info but root cause needs to be addressed.

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by olegkrivtsov** [comment]
Hi @rarkins I've tried to reproduce this, but Renovate works OK for me.

1. I forked the repo https://github.com/lsst-sqre/roundtable
2. I ran Renovate `yarn start`:

```
 yarn start
yarn run v1.22.17
$ run-s generate:*
$ node tools/generate-imports.mjs
generating imports
> data/node-js-schedule.json
> node_modules/emojibase-data/en/shortcodes/github.json
$ node -r ts-node/register/transpile-only -- lib/renovate.ts
 INFO: Repository started (repository=olegkrivtsov/roundtable)
       "renovateVersion": "0.0.0-semantic-release"
 INFO: git fetch completed (repository=olegkrivtsov/roundtable)
       "durationMs": 2870
 INFO: Dependency extraction complete (repository=olegkrivtsov/roundtable)
       "baseBranch": "master",
       "stats": {
         "managers": {
           "github-actions": {"fileCount": 2, "depCount": 5},
           "helmv3": {"fileCount": 7, "depCount": 7},
           "kustomize": {"fileCount": 13, "depCount": 17},
           "pip_requirements": {"fileCount": 1, "depCount": 1}
         },
         "total": {"fileCount": 23, "depCount": 30}
       }
 INFO: Repository finished (repository=olegkrivtsov/roundtable)
       "durationMs": 10850
Done in 36.42s.
```

The stack trace provided in this issue description doesn't give enough info where the exception happens.

Maybe you can provide some more info on this problem?
