### ISSUE TITLE
Pull request not automerging [Gitlab]

### ISSUE THREAD

**Issue by Clumsy-Coder** [renovatebot/renovate#6838]
**What Renovate type are you using?**

Gitlab App

**Describe the bug**
After pull request is created, I waited for CI/CD to pass, it won't automerge the pull request and close it.
Same is true for other renovate update branches.

config:
```json5
{
  extends: [
    '@teppeis',
    ':npm',
    // ':docker',
    ':disableRateLimiting',
    ':automergeAll',
    ':automergePr',
    ':automergeLinters',
    ':automergeTypes',
    // ':dependencyDashboard',
    'group:definitelyTyped',
    // 'schedule:daily',
    ':semanticCommits',
    ':automergePr',
  ],
  npm: {
    schedule: ['at any time'],
    bumpVersion: 'patch',
    ignoreDeprecated: false,
    packageRules: [
      {
        depTypeList: ['dependencies', 'devDependencies'],
        automerge: true,
      },
    ],
  },
  hostRules: [
    {
      domainName: 'github.com',
      encrypted: {
        token: '<redacted>',
      },
    },
  ],
}

```

**Relevant debug logs**
```
DEBUG: processBranch with 1 upgrades(branch="renovate/redux-4.0.x")
DEBUG: Setting baseBranch to master(branch="renovate/redux-4.0.x")
DEBUG: Setting current branch to master(branch="renovate/redux-4.0.x")
DEBUG: latest commit(branch="renovate/redux-4.0.x")
{
  "branchName": "master",
  "latestCommitDate": "2020-07-23T00:06:27+00:00"
}
DEBUG: getBranchPr(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 1 results(branch="renovate/redux-4.0.x")
DEBUG: getPr(37)(branch="renovate/redux-4.0.x")
DEBUG: getBranchStatus(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 2 results(branch="renovate/redux-4.0.x")
DEBUG: branchExists=true(branch="renovate/redux-4.0.x")
DEBUG: Branch pr rebase requested: false(branch="renovate/redux-4.0.x")
DEBUG: Branch has 1 upgrade(s)(branch="renovate/redux-4.0.x")
DEBUG: Checking if PR has been edited(branch="renovate/redux-4.0.x")
DEBUG: Found existing branch PR(branch="renovate/redux-4.0.x")
DEBUG: Checking schedule(at any time, Asia/Tokyo)(branch="renovate/redux-4.0.x")
DEBUG: No schedule defined(branch="renovate/redux-4.0.x")
DEBUG: Branch already exists(branch="renovate/redux-4.0.x")
DEBUG: getBranchPr(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 1 results(branch="renovate/redux-4.0.x")
DEBUG: getPr(37)(branch="renovate/redux-4.0.x")
DEBUG: getBranchStatus(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 2 results(branch="renovate/redux-4.0.x")
DEBUG: Branch does not need rebasing(branch="renovate/redux-4.0.x")
DEBUG: Using reuseExistingBranch: true(branch="renovate/redux-4.0.x")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/redux-4.0.x")
{
  "reuseExistingBranch": true,
  "branchName": "renovate/redux-4.0.x"
}
DEBUG: npm.updateDependency(): dependencies.redux = ^4.0.5(branch="renovate/redux-4.0.x")
DEBUG: Checking if we should bump package.json version(branch="renovate/redux-4.0.x")
{
  "bumpVersion": "patch",
  "currentValue": "0.1.1"
}
DEBUG: (branch="renovate/redux-4.0.x")
{
  "newPjVersion": "0.1.2"
}
DEBUG: Version was already bumped(branch="renovate/redux-4.0.x")
DEBUG: No package files need updating(branch="renovate/redux-4.0.x")
DEBUG: Getting updated lock files(branch="renovate/redux-4.0.x")
DEBUG: lock file dirs(branch="renovate/redux-4.0.x")
{
  "dirs": {
    "yarnLockDirs": [],
    "npmLockDirs": [],
    "pnpmShrinkwrapDirs": [],
    "lernaDirs": []
  }
}
DEBUG: Writing package.json files(branch="renovate/redux-4.0.x")
{
  "packageFiles": [
    "package.json"
  ]
}
DEBUG: Writing any updated package files(branch="renovate/redux-4.0.x")
DEBUG: No updated lock files in branch(branch="renovate/redux-4.0.x")
DEBUG: No files to commit(branch="renovate/redux-4.0.x")
DEBUG: Got res with 2 results(branch="renovate/redux-4.0.x")
DEBUG: Status check renovate/unpublish-safe is already up-to-date(branch="renovate/redux-4.0.x")
DEBUG: Checking if we can automerge branch(branch="renovate/redux-4.0.x")
DEBUG: mergeStatus=no automerge(branch="renovate/redux-4.0.x")
DEBUG: Ensuring PR(branch="renovate/redux-4.0.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/redux-4.0.x")
DEBUG: getBranchPr(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 1 results(branch="renovate/redux-4.0.x")
DEBUG: getPr(37)(branch="renovate/redux-4.0.x")
DEBUG: getBranchStatus(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 2 results(branch="renovate/redux-4.0.x")
DEBUG: Found existing PR(branch="renovate/redux-4.0.x")
DEBUG: getBranchStatus(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 2 results(branch="renovate/redux-4.0.x")
DEBUG: Processing existing PR(branch="renovate/redux-4.0.x")
DEBUG: getBranchStatus(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 2 results(branch="renovate/redux-4.0.x")
DEBUG: getBranchStatus() result(branch="renovate/redux-4.0.x")
{
  "branchStatus": "green",
  "branchName": "renovate/redux-4.0.x"
}
DEBUG: Merge Request #37 does not need updating(branch="renovate/redux-4.0.x")
DEBUG: Checking #37 for automerge(branch="renovate/redux-4.0.x")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/redux-4.0.x")
DEBUG: getBranchStatus(renovate/redux-4.0.x)(branch="renovate/redux-4.0.x")
DEBUG: Got res with 2 results(branch="renovate/redux-4.0.x")
DEBUG: Automerging #37(branch="renovate/redux-4.0.x")
DEBUG: Gitlab API error(branch="renovate/redux-4.0.x")
{
  "err": {
    "name": "HTTPError",
    "hostname": "gitlab.com",
    "method": "PUT",
    "path": "/api/v4/projects/clumsy-coder%2Fmaterial-uhunt/merge_requests/37/merge",
    "protocol": "https:",
    "url": "https://gitlab.com/api/v4/projects/clumsy-coder%2Fmaterial-uhunt/merge_requests/37/merge",
    "gotOptions": {
      "path": "/api/v4/projects/clumsy-coder%2Fmaterial-uhunt/merge_requests/37/merge",
      "protocol": "https:",
      "hostname": "gitlab.com",
      "hash": "",
      "search": "",
      "pathname": "/api/v4/projects/clumsy-coder%2Fmaterial-uhunt/merge_requests/37/merge",
      "href": "https://gitlab.com/api/v4/projects/clumsy-coder%2Fmaterial-uhunt/merge_requests/37/merge",
      "retry": {
        "methods": {},
        "statusCodes": {},
        "errorCodes": {}
      },
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "private-token": "**redacted**",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate",
        "content-type": "application/json",
        "content-length": 36
      },
      "hooks": {
        "beforeRequest": [],
        "beforeRedirect": [
          null
        ],
        "beforeRetry": [],
        "afterResponse": [],
        "beforeError": [],
        "init": []
      },
      "decompress": true,
      "throwHttpErrors": true,
      "followRedirect": true,
      "stream": false,
      "form": false,
      "json": true,
      "cache": false,
      "useElectronNet": false,
      "method": "PUT",
      "hostType": "gitlab",
      "baseUrl": "https://gitlab.com/api/v4/",
      "body": "{\"should_remove_source_branch\":true}"
    },
    "statusCode": 401,
    "statusMessage": "Unauthorized",
    "headers": {
      "date": "Thu, 23 Jul 2020 12:34:04 GMT",
      "content-type": "application/json",
      "content-length": "30",
      "connection": "close",
      "set-cookie": [
        "__cfduid=d527d20a7e480dd9be580407aa0c7cf311595507643; expires=Sat, 22-Aug-20 12:34:03 GMT; path=/; domain=.gitlab.com; HttpOnly; SameSite=Lax; Secure"
      ],
      "cache-control": "no-cache",
      "vary": "Origin",
      "x-content-type-options": "nosniff",
      "x-frame-options": "SAMEORIGIN",
      "x-request-id": "NCQjoyYKRN2",
      "x-runtime": "0.048717",
      "ratelimit-limit": "600",
      "ratelimit-observed": "33",
      "ratelimit-remaining": "567",
      "ratelimit-reset": "1595507704",
      "ratelimit-resettime": "Thu, 23 Jul 2020 12:35:04 GMT",
      "gitlab-lb": "fe-10-lb-gprd",
      "gitlab-sv": "localhost",
      "cf-cache-status": "DYNAMIC",
      "cf-request-id": "041d43ade70000dee124b1d200000001",
      "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
      "server": "cloudflare",
      "cf-ray": "5b756ef63eebdee1-SEA"
    },
    "body": {
      "message": "401 Unauthorized"
    },
    "message": "Response code 401 (Unauthorized)",
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at EventEmitter. (/home/ubuntu/renovateapp/node_modules/got/source/as-promise.js:74:19)\n    at runMicrotasks ()\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
  }
}
DEBUG: No permissions to merge PR(branch="renovate/redux-4.0.x")
```

**To Reproduce**

1. Create a new react project.
2. Install an npm package that requires an update. Ex: react-helmet@5.2.1
2. Push to a gitlab repo
3. Use the renovate config provided (you need to provide your own Github Token)
4. Connect repo to renovate dashboard
5. Wait for renovate app to run
6. Check logs

**Additional context**

Connected to the repo using [link](https://docs.renovatebot.com/install-gitlab-app/#dashboard)

**Comment by viceice** [comment]
Do you use protected branches? Renovate need write acces to the protected branches, which is  `maintainer` by default

**Comment by viceice** [comment]
by default renovate only selfadds `developer` rights, so you would need to manually change that if you wish to use automerge to protected branches
