### ISSUE TITLE
python "packaging" package is missing

### ISSUE THREAD

**Issue by caphrim007** [renovatebot/renovate#6990]
**What Renovate type are you using?**

self-hosted, bitbucket, renovate version 22.17.2

**Describe the bug**

When updating a requirements file with hashes in python, an error about missing `packaging` package is raised

```
DEBUG: Failed to update requirements/constraints.txt file (repository=myorg/vss-ops-utils, branch=renovate/identify-1.x)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "hashin identify==1.4.27 -r requirements/constraints.txt",
         "stdout": "",
         "stderr": "Traceback (most recent call last):\n  File \"/usr/local/python/3.8.5/bin/hashin\", line 5, in <module>\n    from
 hashin import main\n  File \"/usr/local/python/3.8.5/lib/python3.8/site-packages/hashin.py\", line 21, in <module>\n    from
 packaging.requirements import Requirement\nModuleNotFoundError: No module named 'packaging'\n",
         "message": "Command failed: hashin identify==1.4.27 -r requirements/constraints.txt\nTraceback (most recent call 
last):\n  File \"/usr/local/python/3.8.5/bin/hashin\", line 5, in <module>\n    from hashin import main\n  File 
\"/usr/local/python/3.8.5/lib/python3.8/site-packages/hashin.py\", line 21, in <module>\n    from packaging.requirements 
import Requirement\nModuleNotFoundError: No module named 'packaging'\n",
         "stack": "Error: Command failed: hashin identify==1.4.27 -r requirements/constraints.txt\nTraceback (most recent call 
last):\n  File \"/usr/local/python/3.8.5/bin/hashin\", line 5, in <module>\n    from hashin import main\n  File 
\"/usr/local/python/3.8.5/lib/python3.8/site-packages/hashin.py\", line 21, in <module>\n    from packaging.requirements 
import Requirement\nModuleNotFoundError: No module named 'packaging'\n\n    at ChildProcess.exithandler 
(child_process.js:303:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit 
(domain.js:483:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit 
(internal/child_process.js:286:5)"
       }
```

is it possible that the python image used by renovate failed to install this?

**Relevant debug logs**

**To Reproduce**

I think this should be reproducible in any repository that uses hashes in the python requirements file. 

**Additional context**

**Comment by caphrim007** [comment]
I ran the renovate container locally and it does appear to be missing the `packaging` package

```
ubuntu@2a3d364aae2c:/usr/src/app$ /usr/local/python/3.8.5/bin/pip freeze
appdirs==1.4.4
certifi==2020.6.20
distlib==0.3.1
filelock==3.0.12
hashin==0.15.0
pip-api==0.0.14
pipenv==2020.8.13
virtualenv==20.0.30
virtualenv-clone==0.5.4
```

**Comment by caphrim007** [comment]
packaging isnt a new depedency of hashin. seems like it should have been installed

https://github.com/peterbe/hashin/blob/master/setup.py#L30

**Comment by caphrim007** [comment]
note, this was working in 22.16.2

```
trupp-a01:~ trupp$ docker run --rm -it --entrypoint /bin/bash renovate/renovate:22.16.2
ubuntu@c1c689ff5313:/usr/src/app$ /usr/local/python/3.8.5/bin/hashin
If you don't use --update-all you must list packages.
usage: hashin [-h] [-r REQUIREMENTS_FILE] [-a ALGORITHM] [-v] [--include-prereleases] [-p PYTHON_VERSION] [--version] [-d] [-u] [-i] [--synchronous] [--index-url INDEX_URL] [packages [packages ...]]
ubuntu@c1c689ff5313:/usr/src/app$
```

**Comment by caphrim007** [comment]
in 22.17.2 the error (running locally) is

```
trupp-a01:~ trupp$ docker run --rm -it --entrypoint /bin/bash renovate/renovate:22.17.2
ubuntu@f69d1af8b5ff:/usr/src/app$ /usr/local/python/3.8.5/bin/hashin
Traceback (most recent call last):
  File "/usr/local/python/3.8.5/bin/hashin", line 5, in <module>
    from hashin import main
  File "/usr/local/python/3.8.5/lib/python3.8/site-packages/hashin.py", line 21, in <module>
    from packaging.requirements import Requirement
ModuleNotFoundError: No module named 'packaging'
ubuntu@f69d1af8b5ff:/usr/src/app$
```

**Comment by rarkins** [comment]
Are you using the `renovate/renovate` Docker image?
