### ISSUE TITLE
Go mod tidy does not work with k8s.io modules

### ISSUE THREAD

**Issue by sluongng** [renovatebot/renovate#7121]
**What Renovate type, platform and version are you using?**

Self hosted using Gitlab CI scheduled pipeline.

With latest `renovate/renovate` docker image

```
$ renovate --version
23.5.0
```

**Describe the bug**

Renovate runs with GOPROXY set to `GOPROXY=<internal-proxy>|https://proxy.golang.org`

Client repo configure a custom postUpgradeTasks (that renovate allowed):
`go mod tidy`

Client repo has the following in go.mod
```
        k8s.io/api v0.0.0-20191004102349-159aefb8556b
        k8s.io/apimachinery v0.0.0-20191004074956-c5d2f014d689
        k8s.io/client-go v11.0.1-0.20191029005444-8e4128053008+incompatible
        k8s.io/klog v1.0.0
```

Client config
```
  "extends": [
    "config:base"
  ],
  "ignorePresets": [
    ":prHourlyLimit2",
    ":prConcurrentLimit20"
  ],
  "prCreation": "not-pending",
  "stabilityDays": 3,
  "separateMultipleMajor": true,
  "packageRules": [
    {
      "managers": ["gomod"],
      "groupName": "k8s modules",
      "packagePatterns": ["^k8s.io"]
    }
  ],
  "postUpgradeTasks": {
    "commands": [
      "go mod tidy",
      "some other commands"
    ]
  }
}
```

**Relevant debug logs**

```
ERROR: Error updating branch: Command failed: go mod tidy
       go: k8s.io/klog/v2/v2@v2.3.0: reading https://proxy.golang.org/k8s.io/klog/v2/v2/@v/v2.3.0.mod: 410 Gone
        server response: not found: k8s.io/klog/v2/v2@v2.3.0: invalid version: unknown revision v2/v2.3.0
        (repository=redacted/my-repo, branch=renovate/major-2-k8s-modules)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "go mod tidy",
         "stdout": "",
         "stderr": "go: k8s.io/klog/v2/v2@v2.3.0: reading https://**redacted**@v/v2.3.0.mod: 410 Gone\n\tserver response: not found: k8s.io/klog/v2/v2@v2.3.0: invalid version: unknown revision v2/v2.3.0\n",
         "message": "Command failed: go mod tidy\ngo: k8s.io/klog/v2/v2@v2.3.0: reading https://**redacted**@v/v2.3.0.mod: 410 Gone\n\tserver response: not found: k8s.io/klog/v2/v2@v2.3.0: invalid version: unknown revision v2/v2.3.0\n",
         "stack": "Error: Command failed: go mod tidy\ngo: k8s.io/klog/v2/v2@v2.3.0: reading https://**redacted**@v/v2.3.0.mod: 410 Gone\n\tserver response: not found: k8s.io/klog/v2/v2@v2.3.0: invalid version: unknown revision v2/v2.3.0\n\
n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:483:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildPr
ocess._handle.onexit (internal/child_process.js:286:5)"
       }
```

**To Reproduce**

Its happening to an internal repo so its hard to publish the repo for repoducable.

**Additional context**

I tried to `cd /tmp/renovate/repos/..../my-repo` and run `go mod tidy` and it was fine.

```
GOSUMDB=off

> go version
go version go1.15 linux/amd64
```

**Comment by sluongng** [comment]
Looking at this closely, I can see that the module is being resolved here is `k8s.io/klog/v2/v2@v2.3.0` instead of `k8s.io/klog/v2@v2.3.0` ?

**Comment by rarkins** [comment]
Without a reproduction, it's hard to troubleshoot anything. Is `klog` the dependency that's being updated in this branch/MR?

**Comment by rarkins** [comment]
Closing this in the absence of any reproduction or progress. Small chance it's related to https://github.com/renovatebot/renovate/issues/7233
