### ISSUE TITLE
Unknow error with gitea local preset

### ISSUE THREAD

**Issue by CorentinWanteeed** [renovatebot/renovate#7447]
Hello ! :)

**What Renovate type, platform and version are you using?**

Docker image `renovate/renovate` version `23.45.0`

**Describe the bug**

Using Gitea, i have this error thrown for each repository (although all seem to work correctly). I wanted to add gitea preset but i am not sure what is the goal and if i will make it correctly.

https://github.com/renovatebot/renovate/blob/13bedd5c808bf4cc3db91194d9034a985ea3c3a1/lib/config/presets/local/index.ts#L33

**Relevant debug logs**

```bash
 WARN: Unknown error fetching default owner preset (repository=foo/bar)
       "err": {
         "message": "Unsupported platform 'gitea' for local preset.",
         "stack": "Error: Unsupported platform 'gitea' for local preset.\n    at Object.getPreset (/usr/src/app/node_modules/renovate/lib/config/presets/local/index.ts:32:13)\n    at Object.getPreset (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:141:56)\n    at Object.getOnboardingConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/config.ts:23:11)\n    at Object.rebaseOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/rebase.ts:42:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at Object.checkOnboardingBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/onboarding/branch/index.ts:30:20)\n    at Object.getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:223:12)\n    at Object.initRepo (/usr/src/app/node_modules/renovate/lib/workers/repository/init/index.ts:21:12)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:37:14)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:67:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:10:22"
       }
```

**To Reproduce**

Connect renovate to gitea and start it :)

Regards,

**Comment by viceice** [comment]
It's only a warning, simply ignore it. Currently we don't have a possibillity to catch that.

**Comment by CorentinWanteeed** [comment]
Ok, but Gitea local preset is not required like other platform are in local preset ? (Gitlab, Github, Bitbucket)

**Comment by viceice** [comment]
local presets are not suppored on gittea. please follow #7448
