### ISSUE TITLE
/node_modules/p-cancelable/index.js:46   throw new Error('The `onCancel` handler was attached after the promise settled.');

### ISSUE THREAD

**Issue by zbyufei** [renovatebot/renovate#7638]
**What Renovate type, platform and version are you using?**

Renovate type:  https://github.com/renovatebot/renovate
platform: bitbucket-server
version: 23.67.0

**Describe the bug**
looking and Found new releases from maven repository

**Relevant debug logs**

DEBUG: Looking up com.squareup.retrofit2:converter-gson in repository ...
DEBUG: Found 0 new releases for com.squareup.retrofit2:converter-gson in repository...
/node_modules/p-cancelable/index.js:46   throw new Error('The `onCancel` handler was attached after the promise settled.');

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/.../node_modules/p-cancelable/index.js:46:12)
    at makeRequest (/.../node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/.../node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:434:26)
    at Request.emit (node:events:327:20)
    at Request.EventEmitter.emit (node:domain:486:12)
    at Timeout.retry (/.../node_modules/got/dist/source/core/index.js:1261:30)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
error Command failed with exit code 1.

**To Reproduce**

**Additional context**

**Comment by rarkins** [comment]
Does it happen every run?

**Comment by zbyufei** [comment]
> Does it happen every run?

happens very often,

Currently only running "yarn start" multiple times to fix

**Comment by rarkins** [comment]
OK, in that case if you can reproduce it in a public repo on github.com then we'll try running it until we can capture it while debugging.
