### ISSUE TITLE
error adding labels to PRs with github enterprise

### ISSUE THREAD

**Issue by volkc** [renovatebot/renovate#7764]
**What Renovate type, platform and version are you using?**

* self-hosted v23.84.5
* github enterprise

**Describe the bug**

I'm having issues adding labels to PRs (see error below). 

Is this a typo? Shouldn't it be `labels.join` instead of `labels?.join`?

https://github.com/renovatebot/renovate/blob/028182c73b6de57871cf482aba80b2316df46e9d/lib/platform/github/index.ts#L1161

**Relevant debug logs**

```
12:57:14         "err": {
12:57:14           "message": "labels.join is not a function",
12:57:14           "stack": "TypeError: labels.join is not a function
    at addLabels (/usr/lib/node_modules/renovate/dist/platform/github/index.js:957:100)
    at Proxy.createPr (/usr/lib/node_modules/renovate/dist/platform/github/index.js:1126:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.ensurePr (/usr/lib/node_modules/renovate/dist/workers/pr/index.js:300:22)
    at async Object.processBranch (/usr/lib/node_modules/renovate/dist/workers/branch/index.js:480:42)
    at async Object.writeUpdates (/usr/lib/node_modules/renovate/dist/workers/repository/process/write.js:42:21)
    at async Object.update (/usr/lib/node_modules/renovate/dist/workers/repository/process/extract-update.js:110:15)
    at async Object.renovateRepository (/usr/lib/node_modules/renovate/dist/workers/repository/index.js:43:21)
    at async Object.start (/usr/lib/node_modules/renovate/dist/workers/global/index.js:77:13)
    at async /usr/lib/node_modules/renovate/dist/renovate.js:28:24"
12:57:14         }
```

**To Reproduce**

```json
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "labels": [ "a-label" ],
    "packageRules": [
        {
            "packageNames": [
                "my-package"
            ],
            "labels": "another-label"
        }
    ]
}
```

**Additional context**

**Comment by rarkins** [comment]
Can you make it into a reproduction repo on GitHub.com?

**Comment by volkc** [comment]
Ok forget about it. It was a configuration issue on our end.
