### ISSUE TITLE
cannot check file exists on postUpgradeTasks

### ISSUE THREAD

**Issue by kochen** [renovatebot/renovate#7767]
**What Renovate type, platform and version are you using?**

Self-host on Gitlab-CI.
Renovate: 23.84.4

**Describe the bug**

We are using the [newly added](https://github.com/renovatebot/renovate/pull/7632) `postUpgradeTasks` (added in [23.76.0](https://github.com/renovatebot/renovate/releases/tag/23.76.0)) to manage [NX workspce](https://nx.dev/latest/angular/workspace/update).
This requires 2 step (see more below):
1. to create the [possibly] required migration list (a JSON file).
2. to run the migration

The second part, cannot (and should not) be run, if the migration file doesn't exist - otherwise a file not found will be thrown (from the NX script itself).
To avoid this, we added a simple `[ -f migrations.json]` before the actual command, and it works great locally (mac/linux bash).

In the CI when `renovate` runs that specific command, it throws an error.

**Relevant debug logs**
```
Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "hyChTN_XE",
           "repository": "REPO",
           "branch": "renovate/nrwl-nx",
           "err": {
             "killed": false,
             "code": 1,
             "signal": null,
             "cmd": "[ -f migrations.json ] && npx nx migrate --run-migrations=migrations.json",
             "stdout": "",
             "stderr": "",
             "message": "Command failed: [ -f migrations.json ] && npx nx migrate --run-migrations=migrations.json\n",
             "stack": "Error: Command failed: [ -f migrations.json ] && npx nx migrate --run-migrations=migrations.json\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:314:20)\n    at ChildProcess.EventEmitter.emit (domain.js:483:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at Pipe.<anonymous> (net.js:676:12)"
           },
           "msg": "Error updating branch: Command failed: [ -f migrations.json ] && npx nx migrate --run-migrations=migrations.json\n"
         }
       ]
```

**To Reproduce**
```
      "postUpgradeTasks": {
        "commands": [
          "[ -f any.file ] echo 'hi'"
        ],
        "fileFilters": ["**/**"]
      },
```

Important to add these in the configuration as well:
```
    trustLevel: 'high',
    allowPostUpgradeCommandTemplating: true,
    allowedPostUpgradeCommands: ['echo'],
```

**Comment by rarkins** [comment]
Please create a reproduction repository so we can take a look

**Comment by bojanbass** [comment]
I am experiencing exactly the same issue, using nx migrate command.

**Comment by bojanbass** [comment]
Another issue is that if I skip command `"[ -f migrations.json ] && npx nx migrate --run-migrations=migrations.json"` I'm missing `migrations.json` file inside a new PR. This file was generated in a post script so I'm wondering if new files, not yet added to git, are not automatically added in post script? What would be the solution to this problem? I supposed new files are included based on `fileFilters: ['**/**']` rule, which should commit matched files.

**Comment by mehrad-rafigh** [comment]
I am experiencing the same issue there. We have a nx monorepo and a self host bitbucket server.
When renovate runs, no postUpgrade is executed. So renovate just pushed package.json and package-lock.json but no code transformation is added. I will try to create a reproduction repository for this

**Comment by mehrad-rafigh** [comment]
@rarkins I made a [reproduction repository](https://github.com/mehrad-rafigh/nx-workspace-with-renovate-bot-bitbucket-server). Hopefully it can help. Ping me, if I can help :)

**Comment by rarkins** [comment]
@mehrad-rafigh can you replace the readme with a description of what it's reproducing and what steps to run?

**Comment by mehrad-rafigh** [comment]
Hi @rarkins I updated the readme.

**Comment by rarkins** [comment]
Can you commit the command `[ -f migrations.json ] && npx nx migrate --run-migrations=migrations.json` into a `.sh` file within the repo and instead run use a post upgrade command like `bash bin/nx-run-migrations.sh` ?

**Comment by rarkins** [comment]
I assume that the `[ -f migrations.json]` bit of the command is being rejected, but wouldn't that depend on the local shell it's running in on whatever machine you run on?

Another option, if the `nx` script fails if the file is not found, would a command like `npx nx migrate --run-migrations=migrations.json || 0` work to give it a clean exit?

**Comment by mehrad-rafigh** [comment]
That did the trick, but now I have the another issue. My regex for `exlcudePackagePatterns` returns an error telling me that it is an invalid Regex.
`^@nrwl\/(?:(?!workspace).)*$`

So what I basically want to achieve is, that only `@nrwl/workspace` runs the migrations, because that package is in charge of updating other packages from nrwl. 
Is there currently anyway to achieve this @rarkins?

**Comment by rarkins** [comment]
Renovate uses the `re2` regex library in order to prevent any catastrophic backtracking. You need to find a pattern which is supported by re2, or perhaps can you work out how to use `packagePatterns` instead of `excludePackagePatterns`?

**Comment by mehrad-rafigh** [comment]
I ended up putting a lot of packages inside of `ignoreDeps`. I could not get it working with `packagePatterns` @rarkins 
But renovate is now doing what it is supposed to. Should the documentation be updated? I would like to make a contribution.

**Comment by rarkins** [comment]
Sure, please go ahead. But packagePatterns almost certainly works as documented so please nothing about that.

**Comment by mehrad-rafigh** [comment]
@rarkins Would be so kind and point me into the right direction? I would like to update the `allowedPostUpgradeCommands` to reflect the problems I had.

**Comment by rarkins** [comment]
All code and code are in this repo: https://github.com/renovatebot/renovate/search?q=allowedPostUpgradeCommands

**Comment by samuelfernandez** [comment]
> Another option, if the nx script fails if the file is not found, would a command like npx nx migrate --run-migrations=migrations.json || 0 work to give it a clean exit?

@rarkins the problem with that is that it won't allow a failure of the migration scripts. The desired behavior is to execute that command only if the file exists

**Comment by samuelfernandez** [comment]
Tried with `npx path-exists-cli migrations.json && npx --no-install nx migrate --run-migrations=migrations.json` and does not work either

**Comment by samuelfernandez** [comment]
@mehrad-rafigh were you able to have it working? I've tested several approaches so far without success

https://github.com/nx-squeezer/squeezer/issues/251

@rarkins This is the error I keep getting:

```
DEBUG: Executing command (repository=nx-squeezer/squeezer, branch=renovate-github/nrwl-workspace)
       "dep": "@nrwl/cli",
       "command": "bash nx-run-migrations.sh"
DEBUG: rawExec err (repository=nx-squeezer/squeezer, branch=renovate-github/nrwl-workspace)
       "dep": "@nrwl/cli",
       "err": {
         "name": "ExecError",
         "cmd": "/bin/sh -c bash nx-run-migrations.sh",
         "stderr": "",
         "stdout": "",
         "options": {
           "cwd": "/tmp/renovate/repos/github/nx-squeezer/squeezer",
           "encoding": "utf-8",
           "env": {
             "RENOVATE_BINARY_SOURCE": "docker",
             "RENOVATE_CONFIG_FILE": "/github-action/renovate-config.js",
             "USER_ID": "1000",
             "LOG_LEVEL": "debug",
             "HOSTNAME": "051d800a70ca",
             "ENV": "/usr/local/etc/env",
             "PWD": "/usr/src/app",
             "NPM_CONFIG_UPDATE_NOTIFIER": "false",
             "NO_UPDATE_NOTIFIER": "1",
             "USER_NAME": "ubuntu",
             "HOME": "/home/ubuntu",
             "USER_HOME": "/home/ubuntu",
             "LANG": "C.UTF-8",
             "RENOVATE_TOKEN": "**redacted**",
             "SHLVL": "1",
             "BASH_ENV": "/usr/local/etc/env",
             "CONTAINERBASE": "1",
             "NPM_CONFIG_FUND": "false",
             "LC_ALL": "C.UTF-8",
             "PATH": "/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "CONTAINERBASE_ENV": "1",
             "DEBIAN_FRONTEND": "noninteractive",
             "BUILDPACK": "1",
             "_": "/opt/buildpack/tools/renovate/34.77.1/bin/renovate",
             "GIT_SSH_COMMAND": "ssh -o BatchMode=yes",
             "TMPDIR": "/tmp",
             "BUILDPACK_CACHE_DIR": "/tmp/renovate/cache/containerbase",
             "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/cache/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "message": "Command failed: bash nx-run-migrations.sh\n",
         "stack": "ExecError: Command failed: bash nx-run-migrations.sh\n\n    at ChildProcess.<anonymous> (/opt/buildpack/tools/renovate/34.77.1/node_modules/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)"
       }
```

There is no error log, just that the command failed. I can't find any hints of what can be happening...

@WolfSoko

**Comment by mehrad-rafigh** [comment]
Hi @samuelfernandez I gave up trying to update nx through renovate bot. We are still running that part manually with renovate telling us that there is a new version of nx. If I find the time in the next weeks I'll try this again and will report my findings.

**Comment by samuelfernandez** [comment]
> Hi @samuelfernandez I gave up trying to update nx through renovate bot. We are still running that part manually with renovate telling us that there is a new version of nx. If I find the time in the next weeks I'll try this again and will report my findings.

@mehrad-rafigh I've been able to make it work using an executable script. You can check it working in this repo: https://github.com/nx-squeezer/squeezer

But maybe even easier, install [`@nx-squeezer/workspace`](https://www.npmjs.com/package/@nx-squeezer/workspace#renovate) and let it configure Renovate for you with the generator `nx g @nx-squeezer/workspace:renovate`

Sorry that I missed this thread. Long term this PR https://github.com/nrwl/nx/pull/14578 would enhance Nx so that this is not a need, and the CLI works when there are no migrations
