### ISSUE TITLE
Use line-based parsing instead of YAML for helmfile

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7810]
**What would you like Renovate to be able to do?**

Automatically update helmfile files even if they use templating.

**Did you already have any implementation ideas?**

Don't use a YAML parser, instead write our own parser that can extract out image/version values without caring about templates.

Note: we would probably assume that the image name/values aren't themselves templated

Context: https://github.com/renovatebot/config-help/issues/996

**Comment by vsimon** [comment]
@rarkins Not sure if related but as a data point, I'm seeing unknown errors on a helmfile repository.

With: renovate/renovate:25.65.2-slim@sha256:b9816eeecba2e2d324986228b87031cd228cc76da3185dfd5b2a69916543b942


```
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "rQ_ESOp-k",
           "repository": "xxxxxxxxxxxx/helmfiles",
           "err": {
             "message": "Cannot read property 'startsWith' of undefined",
             "stack": "TypeError: Cannot read property 'startsWith' of undefined\n    at /usr/src/app/node_modules/renovate/lib/manager/helmfile/extract.ts:43:21\n    at Array.map (<anonymous>)\n    at Object.extractPackageFile (/usr/src/app/node_modules/renovate/lib/manager/helmfile/extract.ts:38:25)\n    at Object.extractPackageFile (/usr/src/app/node_modules/renovate/lib/manager/index.ts:94:9)\n    at Object.getManagerPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:51:25)\n    at /usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:45:28\n    at async Promise.all (index 2)\n    at Object.extractAllDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:43:26)\n    at Object.extract (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:82:20)\n    at Object.extractDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/process/index.ts:58:26)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:46:52)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:111:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
           },
           "msg": "Repository has unknown error"
         }
```

**Comment by viceice** [comment]
@vsimon your error is unrelated, see linked issue. Will fix it soon.

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by rarkins** [comment]
Actually, I have changed my mind on this one. We should be moving towards off the shelf parsing and simpler extract functions, but combine them with the ability to "transform" files prior to extraction to fix any incompatibilities. Closing this.
