### ISSUE TITLE
Detect and warn if existing branch blocks renovate branches

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#8312]
**What would you like Renovate to be able to do?**

In scenarios where the user has created a branch called `renovate`, it would block the creation of all `renovate/` branches including the `renovate/configure` branch. In such scenarios, Renovate should raiw a config warning issue.

**Did you already have any implementation ideas?**

Here's some example logs:

```
{"level":20,"msg":"Committing files to branch renovate/configure","time":"2021-01-15T11:05:43.053Z"}
{"level":20,"err":{"task":{"commands":["push","origin","renovate/configure:renovate/configure","--force","-u","--no-verify","--verbose","--porcelain"],"format":"utf-8"},"message":"Pushing to https://github.com/bbc/simorgh.git\nPOST git-receive-pack (1539 bytes)\nerror: failed to push some refs to 'https://github.com/bbc/simorgh.git'\n","stack":"Error: Pushing to https://github.com/bbc/simorgh.git\nPOST git-receive-pack (1539 bytes)\nerror: failed to push some refs to 'https://github.com/bbc/simorgh.git'\n\n    at GitExecutorChain.onFatalException (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:61:87)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:52:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"},"msg":"Error committing files","time":"2021-01-15T11:05:49.249Z"}
```

If the git push fails we should check for the existence of a blocking branch and raise an issue if one is found - otherwise behave the same.

**Comment by rarkins** [comment]
Related: https://github.com/renovatebot/renovate/discussions/8310

**Comment by rarkins** [comment]
Duplicate of #7968
