### ISSUE TITLE
NuGet Repository URLs and environment variables

### ISSUE THREAD

**Issue by LarsDR** [renovatebot/renovate#8335]
**What Renovate type, platform and version are you using?**
I'm running renovate locally in a Docker container, using the `renovate/renovate:latest` image targeting Bitbucket Git repositories.

**Describe the bug**

According to the NuGet documentation, it's allowed to use environment variables in the registry URLs, like:
`https://www.a-private-nuget-repo.com/%SOME_ENV_VAR%/api/v3/index.json`

In our case, we're storing an API Key in the environment variable, and we have our URL defined in all libraries and services in the 'local' repository `NuGet.config`-files.

Unfortunately this doesn't seem to work with Renovate Bot, which results in a lot of errors like this:

```
renovate_1  | DEBUG: Found package lookup warnings in onboarding (repository=my-repo)
renovate_1  |        "warnings": [
renovate_1  |          "Failed to look up dependency A.Library",
renovate_1  |          "Failed to look up dependency A.Nother.Library"
renovate_1  |        ],
```

I also noticed the following errors earlier in the process:

```
renovate_1  | DEBUG: baseBranch: master (repository=renovatetest/dotnet.repo)
renovate_1  | DEBUG: nuget registry failure: can't get RegistrationsBaseUrl form https://api.nuget.org/%ENV_NUGET_VERSION%/index.json (repository=renovatetest/dotnet.repo)
renovate_1  |        "err": {
renovate_1  |          "name": "RequestError",
renovate_1  |          "message": "URI malformed",
renovate_1  |          "stack": "RequestError: URI malformed\n    at Request._destroy (/usr/src/app/node_modules/got/dist/source/core/index.js:1374:21)\n    at Request.destroy (internal/streams/destroy.js:38:8)\n    at /usr/src/app/node_modules/got/dist/source/core/index.js:348:26\n    at new Request (/usr/src/app/node_modules/got/dist/source/core/index.js:351:11)\n    at makeRequest (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:35:29)\n    at /usr/src/app/node_modules/got/dist/source/as-promise/index.js:146:9\n    at /usr/src/app/node_modules/p-cancelable/index.js:61:11\n    at new Promise (<anonymous>)\n    at new PCancelable (/usr/src/app/node_modules/p-cancelable/index.js:31:19)\n    at Object.asPromise [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:33:21)\n    at getPromiseOrStream (/usr/src/app/node_modules/got/dist/source/create.js:43:121)\n    at /usr/src/app/node_modules/got/dist/source/create.js:68:20\n    at exports.defaultHandler (/usr/src/app/node_modules/got/dist/source/create.js:53:45)\n    at Array.<anonymous> (/usr/src/app/node_modules/got/dist/source/create.js:67:24)\n    at iterateHandlers (/usr/src/app/node_modules/got/dist/source/create.js:89:50)\n    at Function.got [as default] (/usr/src/app/node_modules/got/dist/source/create.js:117:20)\n    at gotRoutine (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:76:25)\n    at Http.request (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:136:20)\n    at Http.requestJson (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:170:28)\n    at Http.getJson (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:181:17)\n    at decodeURI (<anonymous>)\n    at /usr/src/app/node_modules/got/dist/source/core/index.js:326:17\n    at new Request (/usr/src/app/node_modules/got/dist/source/core/index.js:351:11)\n    at makeRequest (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:35:29)\n    at /usr/src/app/node_modules/got/dist/source/as-promise/index.js:146:9\n    at /usr/src/app/node_modules/p-cancelable/index.js:61:11\n    at new Promise (<anonymous>)\n    at new PCancelable (/usr/src/app/node_modules/p-cancelable/index.js:31:19)\n    at Object.asPromise [as default] (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:33:21)\n    at getPromiseOrStream (/usr/src/app/node_modules/got/dist/source/create.js:43:121)\n    at /usr/src/app/node_modules/got/dist/source/create.js:68:20\n    at exports.defaultHandler (/usr/src/app/node_modules/got/dist/source/create.js:53:45)\n    at Array.<anonymous> (/usr/src/app/node_modules/got/dist/source/create.js:67:24)\n    at iterateHandlers (/usr/src/app/node_modules/got/dist/source/create.js:89:50)\n    at Function.got [as default] (/usr/src/app/node_modules/got/dist/source/create.js:117:20)\n    at gotRoutine (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:76:25)\n    at Http.request (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:136:20)\n    at Http.requestJson (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:170:28)\n    at Http.getJson (/usr/src/app/node_modules/renovate/lib/util/http/index.ts:181:17)\n    at Object.getResourceUrl (/usr/src/app/node_modules/renovate/lib/datasource/nuget/v3.ts:51:38)",
renovate_1  |          "options": {
renovate_1  |            "headers": {
renovate_1  |              "user-agent": "https://github.com/renovatebot/renovate",
renovate_1  |              "accept-encoding": "gzip, deflate",
renovate_1  |              "accept": "application/json"
renovate_1  |            },
renovate_1  |            "url": "https://api.nuget.org/%ENV_NUGET_VERSION%/index.json",
renovate_1  |            "username": "",
renovate_1  |            "password": "***********",
renovate_1  |            "method": "GET",
renovate_1  |            "http2": false
renovate_1  |          }
renovate_1  |        }
```

**Have you created a minimal reproduction repository?**
Unfortunately I cannot share my internal private repositories, but any .NET Core NuGet configuration registry URLs with environment variables seem to trigger the issue.

I added the following two repositories, which produce the error mentioned above, when running the docker-compose file:
https://bitbucket.org/renovatetest/dotnet.repo/src/master/
https://bitbucket.org/renovatetest/renovatebot.test/src/master/

_Note that the two repositories actually do not "fail" with the dependency lookup error as described above, since RenovateBot automatically adds the 'correct' NuGet repository URL it seems_

**Comment by rarkins** [comment]
We need to support this only when `trustLevel="high"`, especially as:

> In our case, we're storing an API Key in the environment variable

**Comment by LarsDR** [comment]
Just did a quick reading up upon trust level, and it definitely makes sense, as it could otherwise expose system variables to a malicious third-party.

**Comment by rarkins** [comment]
Next question is: do we do it during the nuget manager extract phase, or during the nuget datasource lookup phase? Because this is a `nuget.config` feature ([docs](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#using-environment-variables)) I think this should be done as part of extract, and be invisible after that.

Something to be cautious of: this URL will be logged, so if you embed secrets and want them massaged from the logs then you'd need to make sure that the same string is added as a `token` or `password` in a host rule so that it is added to the secrets massage list.

**Comment by LarsDR** [comment]
Hmm that's a good question. I don't actually know when in the process, NuGet handles this. My initial thought was to try and do it in your Http util library, when the request is being done - but obviously that would mean it would have to redo the interpolation on every request, however it would also mean you wouldn't necessarily "leak" any data to the log, unless the URL is logged at a later state of doing the request.

However, it's a good note to have, that if interpolation is done on extraction, you'd have to mark the string as sensitive.

**Comment by rarkins** [comment]
URLs can also get logged by the datasource, e.g. if there is an error - so either way would need the string marked as sensitive - either that or we mark *all* substituted environment values as sensitive but that could be far too eager.

**Comment by viceice** [comment]
So i think the best approach is

* extract config as before (done by manager)
* check if url contains env vars
* if true and trustLevel=high replace env, parse url, add credentials to hostrules, clean url
* add url to dependencies

**Comment by rarkins** [comment]
> * add credentials to hostrules

I think it's a bit of work for us to parse the templated URL enough to know it's credentials. Unless you mean add *any* env variable we substitute?

Also should it be added to hostRules, or just to our log sanitizer?

> * if false or trustLevel!=high: throw error

Maybe just log a warning and disable the extracted package file?

**Comment by viceice** [comment]
> > * add credentials to hostrules
> 
> I think it's a bit of work for us to parse the templated URL enough to know it's credentials. Unless you mean add _any_ env variable we substitute?

According to the docs I think we can simply use a regex for env value detecttion in url: `%MY_VAR%`.

> Also should it be added to hostRules, or just to our log sanitizer?

I think we can use `new Url(...)`  to parse after token where replaced. But sure, we can add value of `%MY_VAR%` to sanitizer for safety.

> > * if false or trustLevel!=high: throw error
> 
> Maybe just log a warning and disable the extracted package file?

Sure, so next manager can work and we show a message on dashboard / log.
Maybe log an error to force non zero exit code of renovate?

**Comment by rarkins** [comment]
> Maybe log an error to force non zero exit code of renovate?

Sure, good idea.

Therefore:

- Use simple regex pattern to find any env values
- If they exist in env, replace them and add them to the sanitized strings list
- If they don't exist in env, log an error
- Try to parse all registryUrls after? (maybe that's a generic requirement for manager or datasource index though)

**Comment by bluecitylights** [comment]
Will this also makes it possible to use the environment variable for the repo password?

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" /> 
    <add key="platform-lib" value="https://gitlab.com/api/v4/xxxx/packages/nuget/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <platform-lib>
        <add key="Username" value="Platform_Packages" />
        <add key="ClearTextPassword" value="%PLATFORM_PACKAGES_PASSWORD%" />
      </platform-lib>
  </packageSourceCredentials>
</configuration>
```

**Comment by rarkins** [comment]
@bluecitylights Renovate does no env substitution today

**Comment by bluecitylights** [comment]
@rarkins can i add the repo also to the hostrules in renovate.json? what is the prio of hostrules compared to nuget.config? can i use environment variables in hostrules?

**Comment by rarkins** [comment]
@bluecitylights yes, you can achieve this through configuration. Please open a new discussion in this repo
