### ISSUE TITLE
Repository has unknown error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by schuch** [renovatebot/renovate#8342]
**What Renovate type, platform and version are you using?**

- self-hosted
- GitLab 13.3.9
- `"renovateVersion": "24.22.3"` (docker)

**Describe the bug**
For a specific repo renovate sporadically logs this error:

`ERROR: Repository has unknown error`

Message:
`fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree`

Strangely, this doesn't happen 100% of the time.
It is possible to reproduce it in a dry run.

**Relevant debug logs**

```
 INFO: Repository started (repository=group/subgroup1/subgroup2/repo)
       "renovateVersion": "24.22.3"
DEBUG: Using localDir: /tmp/renovate/repos/gitlab/group/subgroup1/subgroup2/repo (repository=group/subgroup1/subgroup2/repo)
DEBUG: group/subgroup1/subgroup2/repo default branch = main (repository=group/subgroup1/subgroup2/repo)
DEBUG: Enabling Git FS (repository=group/subgroup1/subgroup2/repo)
DEBUG: group/subgroup1/subgroup2/repo http URL = https://private.gitlabhost/group/subgroup1/subgroup2/repo.git (repository=group/subgroup1/subgroup2/repo)
DEBUG: resetMemCache() (repository=group/subgroup1/subgroup2/repo)
DEBUG: checkOnboarding() (repository=group/subgroup1/subgroup2/repo)
DEBUG: isOnboarded() (repository=group/subgroup1/subgroup2/repo)
DEBUG: findFile(renovate.json) (repository=group/subgroup1/subgroup2/repo)
DEBUG: Initializing git repository into /tmp/renovate/repos/gitlab/group/subgroup1/subgroup2/repo (repository=group/subgroup1/subgroup2/repo)
DEBUG: git clone completed (repository=group/subgroup1/subgroup2/repo)
       "durationMs": 193
ERROR: Repository has unknown error (repository=group/subgroup1/subgroup2/repo)
       "err": {
         "task": {
           "concatStdErr": false,
           "format": "utf-8",
           "commands": ["rev-parse", "HEAD"]
         },
         "message": "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:67:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:59:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
DEBUG: Unknown res (repository=group/subgroup1/subgroup2/repo)
       "res": "unknown-error"
DEBUG: Repository timing splits (milliseconds) (repository=group/subgroup1/subgroup2/repo)
       "splits": {},
       "total": 561
DEBUG: http statistics (repository=group/subgroup1/subgroup2/repo)
       "hostStats": ["private.gitlabhost, 1 request, 110ms request average, 1ms queue average"],
       "totalRequests": 1
 INFO: Repository finished (repository=group/subgroup1/subgroup2/repo)
       "durationMs": 561
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "QRTaYMQZU",
           "repository": "group/subgroup1/subgroup2/repo",
           "err": {
             "task": {
               "concatStdErr": false,
               "format": "utf-8",
               "commands": ["rev-parse", "HEAD"]
             },
             "message": "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
             "stack": "Error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:67:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:59:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
           },
           "msg": "Repository has unknown error"
         }
       ]
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

It could very well be that this is not a renovate bug, but a problem with gitlab. But maybe someone in the community has experienced this problem before?

**Comment by viceice** [comment]
Which renovate are you using? npm package, docker image, helm chart ?

**Comment by schuch** [comment]
We use the docker image

**Comment by rarkins** [comment]
Is the git repo empty?

**Comment by schuch** [comment]
No, the git repo is not empty.

But i am no longer able to reproduce this. I will talk some other teams using the same gitlab instance which reported the same error to see if they have more information.

**Comment by strowi** [comment]
If it helps, it seems i'm running into a very similar error with [this example repo](https://gitlab.com/strowi/ci-templates/)

```bash
~> docker run -v $(pwd):/work -e RENOVATE_PLATFORM="gitlab" -e RENOVATE_TOKEN="$GITLAB_TOKEN_PRIV" -e RENOVATE_BASE_DIR="/renovate" -e RENOVATE_ENDPOINT="https://gitlab.com/api/v4" -v $HOME/.ssh:/home/ubuntu/.ssh:ro -v cache:/home/ubuntu/.cache -v /srv/renovate/work:/renovate -v /srv/renovate/config:/opt/renovate:ro -v /var/run/docker.sock:/var/run/docker.sock renovate/renovate:v24.114.1 strowi/ci-templates

24.114: Pulling from renovate/renovate
Digest: sha256:a6a0611449e0c53ee278074255236479f3d89202dd8bf78fcdc01ddfd46c85f1
Status: Downloaded newer image for renovate/renovate:24.114
 INFO: Repository started (repository=strowi/ci-templates)
       "renovateVersion": "24.114.0"
 WARN: Detected empty commit - aborting git push (repository=strowi/ci-templates)
       "commitRes": {
         "author": null,
         "branch": "",
         "commit": "",
         "root": false,
         "summary": {"changes": 0, "insertions": 0, "deletions": 0}
       }
ERROR: Repository has unknown error (repository=strowi/ci-templates)
       "err": {
         "task": {
           "commands": ["rev-parse", "origin/renovate/configure"],
           "format": "utf-8"
         },
         "message": "origin/renovate/configure\nfatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: origin/renovate/configure\nfatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:109:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:106:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:83:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
 INFO: Repository finished (repository=strowi/ci-templates)
       "durationMs": 8447
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "UanIfDJ4A",
           "repository": "strowi/ci-templates",
           "err": {
             "task": {
               "commands": ["rev-parse", "origin/renovate/configure"],
               "format": "utf-8"
             },
             "message": "origin/renovate/configure\nfatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
             "stack": "Error: origin/renovate/configure\nfatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:109:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:106:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:83:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
           },
           "msg": "Repository has unknown error"
         }
       ]
```

**Comment by viceice** [comment]
@strowi please run with debug log to see more info.

Why are you passing the docker socket? Are you using `binarySource=docker` ? If yes, use the renovate slim image which is a lot smaller. So you don't have to download the unused preinstalled global tools.

Be also sure basedir on host and container do match.

**Comment by strowi** [comment]
@viceice no, not using `binarySource=docker`, that docker-socket ist just a remnant of a default `docker run..`. 
But this shouldn't interfere with the git-error part. I'm getting the same error without the socket.

**Comment by rarkins** [comment]
You have a lot of mapped volumes there. Please try to reduce them to the minimum possible which still reproduces, and then add `-e LOG_LEVEL=debug` to your `docker run` string

**Comment by strowi** [comment]
Ahh, Problem solved. 

With `debug` i noticed:
```bash
DEBUG: GitLab API 404 (repository=strowi/ci-templates)
       "url": "https://gitlab.com/api/v4/projects/strowi%2Frenovate-config/repository/branches"
DEBUG: Failed to retrieve renovate.json from repo (repository=strowi/ci-templates)
       "statusCode": 404,
       "url": "https://gitlab.com/api/v4/"
...
```

It seems i ran into [symlinked renove.json](https://github.com/renovatebot/renovate/issues/2641). After copying instead of symlinking the error goes away. Seems the Error-Log mislead me.;)

**Comment by schuch** [comment]
I close this issue to clean up behind me.

I never found out what caused the problem in our case. Maybe it was just a bug in our Gitlab instance.
