### ISSUE TITLE
Renovates fails during config validation 

### ISSUE THREAD

**Issue by erezrokah** [renovatebot/renovate#8371]
**What Renovate type, platform and version are you using?**

I'm using renovate with a GitHub app. Logs say renovate version is `24.26.2`

**Describe the bug**

Renovated started failing during config validation without any changes on my end.

**Relevant debug logs**

```
DEBUG: Preset fetch error
{
  "preset": "workarounds:ignoreSbtLatestIntegration",
  "err": {
    "message": "Cannot convert undefined or null to object",
    "stack": "TypeError: Cannot convert undefined or null to object
  at Function.keys (<anonymous>)
  at getPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:178:31)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:222:37)
  at async resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:252:38)
  at async Object.resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:252:38)
  at async mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:194:52)
  at async Object.getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:231:14)
  at async Object.initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:19:14)
  at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:60:18)
  at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:359:26)
  at async /home/ubuntu/renovateapp/app/worker/index.js:587:5"
  }
}
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Linked repo https://github.com/erezrokah/2fa-with-slack-action/blob/92f87c4678a98999ba2e0a12d540ca2f42fa1c97/renovate.json

Issue https://github.com/erezrokah/2fa-with-slack-action/issues/237

**Comment by xoxys** [comment]
Same here...

**Comment by viceice** [comment]
Already fixed in master. Please wait for new deplyoment

**Comment by viceice** [comment]
ref #8370

**Comment by broksonic21** [comment]
I put a minimal public repo up at https://github.com/broksonic21/renovate_repo_repro/issues/4 (via https://github.com/renovatebot/renovate/issues/8373, which is likely a duplicate) if it helps

**Comment by rarkins** [comment]
Sorry, bad commit now rolled back in the app. The warning issue in repos will be automatically closed on the next run.

**Comment by viceice** [comment]
@broksonic21 Bug is already fixed and waits for ci release

**Comment by broksonic21** [comment]
thanks! for our knowledge, how long does that take?

**Comment by rarkins** [comment]
The new npm version is published and the app is already rolled back to the last good. Renovate runs continuously so will close the issues the next time it runs on the repo (approximately once per hour)

**Comment by mrlubos** [comment]
Thanks for the quick fix!
