### ISSUE TITLE
setup.py parser unable to import files from its own package 

### ISSUE THREAD

**Issue by andreasemprebon** [renovatebot/renovate#8415]
**What Renovate type, platform and version are you using?**

Renovate 24.28.0, but the bug has been introduced with version 24.22.3
Azure DevOps
Python 3.8

**Describe the bug**

Renovate is no longer able to import modules from the same package as the one checked.

**Relevant debug logs**

```
WARN: Failed to read setup.py file (repository=RaceEng/test-python-renovate, packageFile=setup.py)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "python3.8 \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\" \"setup.py\"",
         "stdout": "",
         "stderr": "Traceback (most recent call last):\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 44, in <module>\n    invoke()\n  File \"/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/unittest/mock.py\", line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 37, in invoke\n    load_source('_target_setup_', basename(sys.argv[-1]))\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 12, in load_source\n    return vars(SourceFileLoader('mod', path).load_module())\n  File \"<frozen importlib._bootstrap_external>\", line 462, in _check_name_wrapper\n  File \"<frozen importlib._bootstrap_external>\", line 962, in load_module\n  File \"<frozen importlib._bootstrap_external>\", line 787, in load_module\n  File \"<frozen importlib._bootstrap>\", line 265, in _load_module_shim\n  File \"<frozen importlib._bootstrap>\", line 702, in _load\n  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"setup.py\", line 3, in <module>\n    from testpkg import __version__\nModuleNotFoundError: No module named 'testpkg'\n",
         "message": "Command failed: python3.8 \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\" \"setup.py\"\nTraceback (most recent call last):\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 44, in <module>\n    invoke()\n  File \"/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/unittest/mock.py\", line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 37, in invoke\n    load_source('_target_setup_', basename(sys.argv[-1]))\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 12, in load_source\n    return vars(SourceFileLoader('mod', path).load_module())\n  File \"<frozen importlib._bootstrap_external>\", line 462, in _check_name_wrapper\n  File \"<frozen importlib._bootstrap_external>\", line 962, in load_module\n  File \"<frozen importlib._bootstrap_external>\", line 787, in load_module\n  File \"<frozen importlib._bootstrap>\", line 265, in _load_module_shim\n  File \"<frozen importlib._bootstrap>\", line 702, in _load\n  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"setup.py\", line 3, in <module>\n    from testpkg import __version__\nModuleNotFoundError: No module named 'testpkg'\n",
         "stack": "Error: Command failed: python3.8 \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\" \"setup.py\"\nTraceback (most recent call last):\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 44, in <module>\n    invoke()\n  File \"/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/unittest/mock.py\", line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 37, in invoke\n    load_source('_target_setup_', basename(sys.argv[-1]))\n  File \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\", line 12, in load_source\n    return vars(SourceFileLoader('mod', path).load_module())\n  File \"<frozen importlib._bootstrap_external>\", line 462, in _check_name_wrapper\n  File \"<frozen importlib._bootstrap_external>\", line 962, in load_module\n  File \"<frozen importlib._bootstrap_external>\", line 787, in load_module\n  File \"<frozen importlib._bootstrap>\", line 265, in _load_module_shim\n  File \"<frozen importlib._bootstrap>\", line 702, in _load\n  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"setup.py\", line 3, in <module>\n    from testpkg import __version__\nModuleNotFoundError: No module named 'testpkg'\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:486:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
       },

````

**Have you created a minimal reproduction repository?**

Create a repository with a `setup.py` file with content:
```
from setuptools import setup, find_packages

from testpkg import __version__

setup(
    name="testpkg",
    version=__version__,
    packages=find_packages(),
)
```

and a folder named `testpkg` with a file `__init__.py` inside:
```
__version__ = '1.0'
```

**Additional context**

My colleague @swinkler19 and I spotted this bug while checking the logs of why some of the repositories in our Azure DevOps weren't up-to-date.

This bug seems to have been introduced with commit https://github.com/renovatebot/renovate/commit/6da2f1d2f0a96986eeb9d3d04f43c8767a28b486 that removed the line `sys.path.append(dirname(realpath(sys.argv[-1])))` from the function `def invoke(mock1, mock2):`

It was also a previously solved issued, here the relative issue on GitHub: https://github.com/renovatebot/renovate/issues/6544

According to the above issue and relative PR, the added test should have caught the regression, but it's not the case. Is the test still used or not?

**Comment by rarkins** [comment]
Cc @hisener re: the bug

Cc @viceice re: did our python test not run?

**Comment by viceice** [comment]
@rarkins Looks like ther is something wrong with the tests. Maybe some mocking stopped real python runs?

**Comment by hisener** [comment]
Hmm, in https://github.com/renovatebot/renovate/pull/8320#discussion_r558874402, I wrote those two lines are not necessary anymore because of the working directory change. I will have a look later today.

**Comment by hisener** [comment]
I have a fix but [the test](https://github.com/voyages-sncf-technologies/renovate/commit/85a587e8e223eecc8b71d9eec67e9f23930146b3#diff-18a69769b52d33cd097e3773f603c26621d7f64c43056fcd53209a2b347dd73fR42-R47) was deleted, at least I cannot see it on the master branch.. :thinking: Should I create a PR without a test because figuring out the test will take some time.
