### ISSUE TITLE
pip_setup fails to extract from subdirectory

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#8462]
**What Renovate type, platform and version are you using?**

Self-hosted, but also happens in the app.

**Describe the bug**

A setup.py fails to be extracted in a subdirectory

**Relevant debug logs**

```
 WARN: Failed to read setup.py file (repository=renovate-tests/pipelines, packageFile=api/v2alpha1/python/setup.py)
       "err": {
         "killed": false,
         "code": 255,
         "signal": null,
         "cmd": "docker run --rm --name=renovate_pip --label=renovate_child -v \"/tmp/renovate/repos/github/renovate-tests/pipelines\":\"/tmp/renovate/repos/github/renovate-tests/pipelines\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -w \"/tmp/renovate/repos/github/renovate-tests/pipelines/api/v2alpha1/python\" docker.io/renovate/pip bash -l -c \"python \\\"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\\\" \\\"api/v2alpha1/python/setup.py\\\"\"",
         "stdout": "Generating /tmp/renovate/repos/github/renovate-tests/pipelines/api/v2alpha1/pipeline_spec_pb2.py...\n",
         "stderr": "protoc is not found.  Please compile it or install the binary package.\n",
         "message": "Command failed: docker run --rm --name=renovate_pip --label=renovate_child -v \"/tmp/renovate/repos/github/renovate-tests/pipelines\":\"/tmp/renovate/repos/github/renovate-tests/pipelines\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -w \"/tmp/renovate/repos/github/renovate-tests/pipelines/api/v2alpha1/python\" docker.io/renovate/pip bash -l -c \"python \\\"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\\\" \\\"api/v2alpha1/python/setup.py\\\"\"\nprotoc is not found.  Please compile it or install the binary package.\n",
         "stack": "Error: Command failed: docker run --rm --name=renovate_pip --label=renovate_child -v \"/tmp/renovate/repos/github/renovate-tests/pipelines\":\"/tmp/renovate/repos/github/renovate-tests/pipelines\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -w \"/tmp/renovate/repos/github/renovate-tests/pipelines/api/v2alpha1/python\" docker.io/renovate/pip bash -l -c \"python \\\"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\\\" \\\"api/v2alpha1/python/setup.py\\\"\"\nprotoc is not found.  Please compile it or install the binary package.\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:483:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)"
       },
       "content": "[content]"
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to: https://github.com/renovate-tests/pipelines
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

@hisener seems reasonably likely it's related to your changes? Either that or unlucky coincidence. This is a new repo so I can't tell if it was working or not previously

**Comment by rarkins** [comment]
Whoops, this is actually a *different* error when I reproduced it - `protoc is not found`. Closing/deleting, sorry @hisener
