### ISSUE TITLE
Failed to renovate by error 'template.matchAll is not a function'

### ISSUE THREAD

**Issue by takaaki7** [renovatebot/renovate#8533]
**What Renovate type, platform and version are you using?**
GitHub Actions
renovate version: 24.37.5

**Describe the bug**
Failed to run `npx renovate --token $TOKEN myrepo/myorg` by error 'template.matchAll is not a function'

**Relevant debug logs**

```
Run npx renovate --token $RENOVATE_GITHUB_TOKEN myrepo/myorg
  npx renovate --token $RENOVATE_GITHUB_TOKEN myrepo/myorg
  shell: /bin/bash -e {0}
  env:
    CI: true
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    RENOVATE_GITHUB_TOKEN: ***
 INFO: Repository started (repository=myrepo/myorg)
       "renovateVersion": "24.37.5"
 INFO: Dependency extraction complete (repository=myrepo/myorg)
       "baseBranch": "develop",
       "stats": {
         "managers": {"npm": {"fileCount": 1, "depCount": 63}},
         "total": {"fileCount": 1, "depCount": 63}
       }
ERROR: Repository has unknown error (repository=myrepo/myorg)
       "err": {
         "message": "template.matchAll is not a function",
         "stack": "TypeError: template.matchAll is not a function\n    at Object.compile (/home/runner/.npm/_npx/3804/lib/node_modules/renovate/dist/util/template/index.js:148:34)\n    at Object.generateBranchName (/home/runner/.npm/_npx/3804/lib/node_modules/renovate/dist/workers/repository/updates/branch-name.js:90:38)\n    at Object.flattenUpdates (/home/runner/.npm/_npx/3804/lib/node_modules/renovate/dist/workers/repository/updates/flatten.js:86:39)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Repository finished (repository=myorg/myrepo)
       "durationMs": 31345
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "hYZqRXcSO",
           "repository": "myorg/myrepo",
           "err": {
             "message": "template.matchAll is not a function",
             "stack": "TypeError: template.matchAll is not a function\n    at Object.compile (/home/runner/.npm/_npx/3804/lib/node_modules/renovate/dist/util/template/index.js:148:34)\n    at Object.generateBranchName (/home/runner/.npm/_npx/3804/lib/node_modules/renovate/dist/workers/repository/updates/branch-name.js:90:38)\n    at Object.flattenUpdates (/home/runner/.npm/_npx/3804/lib/node_modules/renovate/dist/workers/repository/updates/flatten.js:86:39)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
           },
           "msg": "Repository has unknown error"
         }
       ]
```

a part of our renovate.json5
```
{
  "force": {
    "constraints": {
      "node": "< 15.0.0"
    }
  },
  "extends": [
    "config:base",
    "docker:disable",
    ":timezone(Asia/Tokyo)",
    ":masterIssue",
  ],
  "prConcurrentLimit": 0,
  "schedule": [
    "every weekday"
  ],
  "labels": ["Type:dependencies"],
  "npm": {
    "extends": [
      ":noUnscheduledUpdates",
      ":semanticPrefixFixDepsChoreOthers",
      ":pinAllExceptPeerDependencies"
    ],
    "major": {
        "enabled": false
    },
    "minor": {
        "automerge": false
    },
    "patch": {
        "automerge": true
    },
    "pin": {
        "automerge": true
    },
    "packageRules": [
      {
        "groupName": "Manuall updates",
        "packageNames": [
          "eslint",
          "prettier",
          "typescript",
          "ts-node-dev",
        ],
        "enabled": false
      },
      {
        "groupName": "mylib",
        "packagePatterns": [
          "^@myorg/"
        ]
      }
    ]
  },
}
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Comment by viceice** [comment]
make sure you have nodejs > v12 on your workflow
