### ISSUE TITLE
All `forking-renovate` operations on `github.com/ampproject/amphtml` are failing with `external-host-error`

### ISSUE THREAD

**Issue by rsimha** [renovatebot/renovate#8641]
**What Renovate type, platform and version are you using?**

We are at https://github.com/ampproject/amphtml, and are using the [`forking-renovate`](https://github.com/apps/forking-renovate) hosted app

**Describe the bug**

We've been using `forking-renovate` for a couple of years without incident. Of late, all operations are returning a `external-host-error` result. See https://app.renovatebot.com/dashboard#github/ampproject/amphtml.

**Relevant debug logs**

From one of the several failed operations on the dashboard, here are some logs. It appears the docker container running the operation has lost authorization somewhere. 

```
WARN: docker registry failure: unauthorized
{
  "registry": "https://index.docker.io",
  "dockerRepository": "library/ubuntu-2004",
  "err": {
    "name": "HTTPError",
    "timings": {
      "start": 1613026448849,
      "socket": 1613026448849,
      "lookup": 1613026448908,
      "connect": 1613026448975,
      "secureConnect": 1613026449153,
      "upload": 1613026449154,
      "response": 1613026449362,
      "end": 1613026449362,
      "phases": {
        "wait": 0,
        "dns": 59,
        "tcp": 67,
        "tls": 178,
        "request": 1,
        "firstByte": 208,
        "download": 0,
        "total": 513
      }
    },
    "message": "Response code 401 (Unauthorized)",
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept-encoding": "gzip, deflate",
        "authorization": "***********",
        "accept": "application/json"
      },
      "url": "https://index.docker.io/v2/library/ubuntu-2004/tags/list?n=10000",
      "username": "",
      "password": "",
      "method": "GET",
      "http2": false
    },
    "response": {
      "statusCode": 401,
      "statusMessage": "Unauthorized",
      "body": {
        "errors": [
          {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": [
              {
                "Type": "repository",
                "Class": "",
                "Name": "library/ubuntu-2004",
                "Action": "pull"
              }
            ]
          }
        ]
      },
      "headers": {
        "content-type": "application/json",
        "docker-distribution-api-version": "registry/2.0",
        "www-authenticate": "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/ubuntu-2004:pull\",error=\"insufficient_scope\"",
        "date": "Thu, 11 Feb 2021 06:54:09 GMT",
        "content-length": "162",
        "connection": "close",
        "strict-transport-security": "max-age=31536000"
      },
      "httpVersion": "1.1"
    }
  }
}
WARN: Host error
{
  "hostType": "docker",
  "lookupName": "ubuntu-2004",
  "err": {
    "name": "HTTPError",
    "timings": {
      "start": 1613026448849,
      "socket": 1613026448849,
      "lookup": 1613026448908,
      "connect": 1613026448975,
      "secureConnect": 1613026449153,
      "upload": 1613026449154,
      "response": 1613026449362,
      "end": 1613026449362,
      "phases": {
        "wait": 0,
        "dns": 59,
        "tcp": 67,
        "tls": 178,
        "request": 1,
        "firstByte": 208,
        "download": 0,
        "total": 513
      }
    },
    "message": "Response code 401 (Unauthorized)",
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept-encoding": "gzip, deflate",
        "authorization": "***********",
        "accept": "application/json"
      },
      "url": "https://index.docker.io/v2/library/ubuntu-2004/tags/list?n=10000",
      "username": "",
      "password": "",
      "method": "GET",
      "http2": false
    },
    "response": {
      "statusCode": 401,
      "statusMessage": "Unauthorized",
      "body": {
        "errors": [
          {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": [
              {
                "Type": "repository",
                "Class": "",
                "Name": "library/ubuntu-2004",
                "Action": "pull"
              }
            ]
          }
        ]
      },
      "headers": {
        "content-type": "application/json",
        "docker-distribution-api-version": "registry/2.0",
        "www-authenticate": "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/ubuntu-2004:pull\",error=\"insufficient_scope\"",
        "date": "Thu, 11 Feb 2021 06:54:09 GMT",
        "content-length": "162",
        "connection": "close",
        "strict-transport-security": "max-age=31536000"
      },
      "httpVersion": "1.1"
    }
  }
}
```
**Have you created a minimal reproduction repository?**

- [x] I don't have time for that, but it happens in a public repository I have linked to

**Additional context**

I've tried disabling and re-enabling the app for our repo, but that didn't work. FWIW, the app is working fine on other repos in the same organization. E.g. https://app.renovatebot.com/dashboard#github/ampproject/amp-github-apps

**Comment by rarkins** [comment]
I think this is the full story:

1. Docker Hub added [rate limiting](https://www.docker.com/increase-rate-limits)
2. Because it hits sporadically, it would cause temporary "flapping" of PRs (closing/opening/closing), so we treated an unauthorized response as an external host error, which causes the run to abort instead of continuing
3. Your repo seems to have some images that I don't think exist on Docker Hub, and are getting back an unauthorized response: https://github.com/ampproject/amphtml/blob/0919da4a432042d10e69a9807450e0aa410fbba9/.circleci/config.yml#L19-L31

Do you know where these `ubuntu-2004` images are sourced from - it looks like CircleCI? If they are non-reachable images then is it ok to add them to the ignore list? i.e. add this to your config:

```
  "ignoreDeps": ["ubuntu-2004"]
```

**Comment by rsimha** [comment]
Yes, these are CircleCI's images (listed [here](https://circleci.com/docs/2.0/configuration-reference/#available-machine-images)). Not sure if they are reachable by renovate, but I'm happy to add them to `ignoreDeps`. Thanks for the quick response!

**Comment by rsimha** [comment]
That did the trick. Thanks for the help, @rarkins!
