### ISSUE TITLE
The `cloneSubmodules` option doesn't work when configured in user config (e.g. renovate.json)

### ISSUE THREAD

**Issue by andreibsk** [renovatebot/renovate#8936]
**What Renovate type, platform and version are you using?**

GitHub marketplace application (version 24.68.1 according to Renovate Dashboard)

**Describe the bug**

I have two private repositories hosted on GitHub. One of them is a submodule in the main repository. I have configured the Renovate GitHub marketplace app to run in the main repository with `"cloneSubmodules": false` as it (the submodule repo) is not required to fulfill this task. Despite this the bot still attempts to clone the submodule repo which results in a `Unable to initialise git submodule at <submodule repo>` warning as seen in the dependency dashboard issue and in the Renovate Dashboard logs (See _Additional context_ about warning). I expected submodules not to be cloned given that I've set `cloneSubmodules` to false. Further inspection of the logs indicates that the bot attempts to clone both the main repository and its submodules _before_ reading the config file (of the main repo).

**Relevant debug logs**

```
INFO: Repository started
{
  "renovateVersion": "24.68.1"
}
DEBUG: Using localDir: /mnt/renovate/gh/andreibsk/<MAIN_REPO>
DEBUG: Repository cache is valid
DEBUG: initRepo("andreibsk/<MAIN_REPO>")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: No dangling containers to remove
DEBUG: andreibsk/<MAIN_REPO> default branch = main
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: Initializing git repository into /mnt/renovate/gh/andreibsk/<MAIN_REPO>
DEBUG: git clone completed
{
  "durationMs": 1586
}
DEBUG: Cloning git submodule at tools/<SUBMODULE_REPO>
WARN: Unable to initialise git submodule at tools/<SUBMODULE_REPO>
DEBUG: latest commit
{
  "latestCommitDate": "2021-03-01T22:13:32+00:00"
}
DEBUG: Setting git author name
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: findFile(renovate.json5)
DEBUG: findFile(.github/renovate.json)
DEBUG: findFile(.github/renovate.json5)
DEBUG: findFile(.gitlab/renovate.json)
DEBUG: findFile(.gitlab/renovate.json5)
DEBUG: findFile(.renovaterc)
DEBUG: findFile(.renovaterc.json)
DEBUG: config file not found
DEBUG: package.json contains config
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
DEBUG: Repo is onboarded
DEBUG: Using package.json for global renovate config
DEBUG: Found package.json config file
DEBUG: package.json>renovate config
{
  "config": {
    "extends": [
      "config:base"
    ],
    "dependencyDashboard": true,
    "cloneSubmodules": false,
    "packageRules": [
      {
        "matchUpdateTypes": [
          "minor",
          "patch",
          "pin"
        ],
        "matchCurrentVersion": "!/^0/",
        "automerge": true,
        "automergeType": "branch"
      }
    ]
  }
}
DEBUG: migrateAndValidate()
...
```

**Have you created a minimal reproduction repository?**

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

This issue also brings an additional question: Why does the submodule clone fail in the first place? Both the main and the submodule repo are on the same GitHub account and the Renovate application is explicitly configured to have access to both repositories. Is there anything else needed for this to work that I've missed? Perhaps some additional details could aid in figuring this out, maybe the details of the thrown error that is ignored at: 
https://github.com/renovatebot/renovate/blob/fa9031f5e9f2d887adb289ad54b694020d43c9ca/lib/util/git/index.ts#L296-L301

**Comment by rarkins** [comment]
See #8924 for further context

The additional question is specific to the hosted github app. If both repos are private, and both are in the same org, and both have Renovate installed, then the token granted should have access to both.

**Comment by andreibsk** [comment]
Thanks for the reply and quick update in the discussion thread (https://github.com/renovatebot/renovate/discussions/8924#discussioncomment-422661), sorry I missed it.

I'll make sure to check the logs tomorrow as both repos satisfy the mentioned criteria for the bot to have access to them (both of them even received the onboarding PR).

**Comment by andreibsk** [comment]
Follow-up with the logs from the new version (24.71.2):

```
INFO: Repository started
{
  "renovateVersion": "24.71.2"
}
DEBUG: Using localDir: /mnt/renovate/gh/andreibsk/<MAIN_REPO>
DEBUG: Repository cache is valid
DEBUG: initRepo("andreibsk/<MAIN_REPO>")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: No dangling containers to remove
DEBUG: andreibsk/<MAIN_REPO> default branch = main
DEBUG: Using app token for git init
DEBUG: resetMemCache()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: Initializing git repository into /mnt/renovate/gh/andreibsk/<MAIN_REPO>
DEBUG: git clone completed
{
  "durationMs": 956
}
DEBUG: Cloning git submodule at tools/<SUBMODULE_REPO>
WARN: Unable to initialise git submodule at tools/<SUBMODULE_REPO>
{
  "err": {
    "task": {
      "commands": [
        "submodule",
        "update",
        "--init",
        "tools/<SUBMODULE_REPO>"
      ],
      "format": "utf-8"
    },
    "message": "Submodule 'tools/<SUBMODULE_REPO>' (https://github.com/andreibsk/<SUBMODULE_REPO>) registered for path 'tools/<SUBMODULE_REPO>'\nCloning into '/mnt/renovate/gh/andreibsk/<MAIN_REPO>/tools/<SUBMODULE_REPO>'...\nfatal: could not read Username for 'https://github.com': No such device or address\nfatal: clone of 'https://github.com/andreibsk/<SUBMODULE_REPO>' into submodule path '/mnt/renovate/gh/andreibsk/<MAIN_REPO>/tools/<SUBMODULE_REPO>' failed\nFailed to clone 'tools/<SUBMODULE_REPO>'. Retry scheduled\nCloning into '/mnt/renovate/gh/andreibsk/<MAIN_REPO>/tools/<SUBMODULE_REPO>'...\nfatal: could not read Username for 'https://github.com': No such device or address\nfatal: clone of 'https://github.com/andreibsk/<SUBMODULE_REPO>' into submodule path '/mnt/renovate/gh/andreibsk/<MAIN_REPO>/tools/<SUBMODULE_REPO>' failed\nFailed to clone 'tools/<SUBMODULE_REPO>' a second time, aborting\n",
    "stack": "Error: Submodule 'tools/<SUBMODULE_REPO>' (https://github.com/andreibsk/<SUBMODULE_REPO>) registered for path 'tools/<SUBMODULE_REPO>'\nCloning into '/mnt/renovate/gh/andreibsk/<MAIN_REPO>/tools/<SUBMODULE_REPO>'...\nfatal: could not read Username for 'https://github.com': No such device or address\nfatal: clone of 'https://github.com/andreibsk/<SUBMODULE_REPO>' into submodule path '/mnt/renovate/gh/andreibsk/<MAIN_REPO>/tools/<SUBMODULE_REPO>' failed\nFailed to clone 'tools/<SUBMODULE_REPO>'. Retry scheduled\nCloning into '/mnt/renovate/gh/andreibsk/<MAIN_REPO>/tools/<SUBMODULE_REPO>'...\nfatal: could not read Username for 'https://github.com': No such device or address\nfatal: clone of 'https://github.com/andreibsk/<SUBMODULE_REPO>' into submodule path '/mnt/renovate/gh/andreibsk/<MAIN_REPO>/tools/<SUBMODULE_REPO>' failed\nFailed to clone 'tools/<SUBMODULE_REPO>' a second time, aborting\n\n    at GitExecutorChain.onFatalException (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:65:87)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:56:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  }
}
DEBUG: latest commit
{
  "latestCommitDate": "2021-03-03T06:01:12+00:00"
}
DEBUG: Setting git author name
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: Config file exists
{
  "fileName": "renovate.json"
}
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
DEBUG: Repository config
{
  "fileName": "renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "dependencyDashboard": true,
    "cloneSubmodules": false,
    "packageRules": [
      {
        "matchUpdateTypes": [
          "minor",
          "patch",
          "pin"
        ],
        "matchCurrentVersion": "!/^0/",
        "automerge": true,
        "automergeType": "branch"
      }
    ]
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
```

**Comment by rarkins** [comment]
@andreibsk we maybe need to treat that as a separate issue/bug. @JamieMagee I forget what the status on "private submodules" was or how it's meant to work.
