### ISSUE TITLE
Renovate fails if boto3-stubs is added to a Poetry lockfile

### ISSUE THREAD

**Issue by orf** [renovatebot/renovate#8968]
**What Renovate type, platform and version are you using?**

Latest release

**Describe the bug**

Some pypi packages have pretty wacky versions: https://pypi.org/project/boto3-stubs/ (1.17.19.0). This causes renovate to exit when creating a SemVer object from it if it is defined in a Poetry lockfile:

`boto3-stubs = "*"`

**Relevant debug logs**

```
 "stack": "TypeError: Invalid Version: 1.16.31.0\n    at new SemVer (/usr/src/app/node_modules/semver/classes/semver.js:38:13)
 at compare (/usr/src/app/node_modules/semver/functions/compare.js:3:32)
at Object.gt [as isGreaterThan] (/usr/src/app/node_modules/semver/functions/gt.js:2:29
at Object.isGreaterThan (/usr/src/app/node_modules/renovate/lib/versioning/poetry/index.ts:79:7)
at /usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:43:16
at Array.filter (<anonymous>
at Object.filterVersions (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:42:35)
at Object.lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:176:28)
at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:42:26)
at /usr/src/app/node_modules/p-map/index.js:57:22"
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
Lowering priority due to inability to reproduce
