### ISSUE TITLE
"Error updating branch" does not result in comment on PR

### ISSUE THREAD

**Issue by fgblomqvist** [renovatebot/renovate#9434]
**What Renovate type, platform and version are you using?**

Latest, self-hosted Renovate, on GitLab.

**Describe the bug**

If Renovate fails to update a branch for an MR, it doesn't add a comment to that MR.

**Relevant debug logs**
Here's an example that involves an LFSd package-lock.json, however Renovate's docker image does not yet support LFS so GitLab returns an error when Renovate tries to push a commit for this file:

<details><summary>Click me to see logs</summary>

```
[07:11:30] DEBUG: 2 file(s) to commit (repository=<snip>, branch=<snip>)
[07:11:30] DEBUG: Committing files to branch <snip> (repository=<snip>, branch=<snip>)
[07:11:31] DEBUG: git commit (repository=<snip>, branch=<snip>)
[07:11:31] "result": {
[07:11:31] "author": null,
[07:11:31] "branch": "<snip>",
[07:11:31] "commit": "26c827ab",
[07:11:31] "root": false,
[07:11:31] "summary": {"changes": 2, "insertions": 44781, "deletions": 85}
[07:11:31] }
[07:11:35] DEBUG: Unknown error committing files (repository=<snip>, branch=<snip>)
[07:11:35] "err": {
[07:11:35] "task": {
[07:11:35] "commands": [
[07:11:35] "push",
[07:11:35] "origin",
[07:11:35] "<snip>:<snip>",
[07:11:35] "--force",
[07:11:35] "-u",
[07:11:35] "--no-verify",
[07:11:35] "--verbose",
[07:11:35] "--porcelain"
[07:11:35] ],
[07:11:35] "format": "utf-8"
[07:11:35] },
[07:11:35] "message": "Pushing to <snip>\nPOST git-receive-pack (237751 bytes)\nremote: GitLab: File \"<snip>/package-lock.json\" is larger than the allowed size of 1 MB\nerror: failed to push some refs to '<snip>'\n",
[07:11:35] "stack": "Error: Pushing to <snip>\nPOST git-receive-pack (237751 bytes)\nremote: GitLab: File \"<snip>/package-lock.json\" is larger than the allowed size of 1 MB\nerror: failed to push some refs to '<snip>'\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:76:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:68:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
[07:11:35] }
[07:11:35] WARN: Error updating branch (repository=<snip>, branch=<snip>)
[07:11:35] "err": {
[07:11:35] "task": {
[07:11:35] "commands": [
[07:11:35] "push",
[07:11:35] "origin",
[07:11:35] "<snip>:<snip>",
[07:11:35] "--force",
[07:11:35] "-u",
[07:11:35] "--no-verify",
[07:11:35] "--verbose",
[07:11:35] "--porcelain"
[07:11:35] ],
[07:11:35] "format": "utf-8"
[07:11:35] },
[07:11:35] "message": "Pushing to <snip>\nPOST git-receive-pack (237751 bytes)\nremote: GitLab: File \"<snip>/package-lock.json\" is larger than the allowed size of 1 MB\nerror: failed to push some refs to '<snip>'\n",
[07:11:35] "stack": "Error: Pushing to <snip>\nPOST git-receive-pack (237751 bytes)\nremote: GitLab: File \"<snip>/package-lock.json\" is larger than the allowed size of 1 MB\nerror: failed to push some refs to '<snip>'\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:76:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:68:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
[07:11:35] }
```

</details>

**Have you created a minimal reproduction repository?**

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I don't think it should be necessary to create a repro repo. I think the relevant line is here:  
https://github.com/renovatebot/renovate/blob/5f8473753973398f07a548642578a81bc0da632e/lib/workers/branch/index.ts#L649

I guess you could argue that this is more of a feature request than a bug report, so feel free to change if needed.

I'm not sure when Renovate decides to add comments, but if it e.g. fails to update an Artifact it does (which is very helpful). I think it would make sense/be expected that Renovate adds a comment in any scenario where it didn't successfully manipulate/create/delete the MR. Otherwise, the MR could look good and might be merged, even though something is wrong with it. If you check the Dep Dashboard, you will see that this MR had an error (but you can't expect everyone to do that, and some people don't even have the Dashboard enabled).

**Comment by viceice** [comment]
Duplicate of #7894

**Comment by fgblomqvist** [comment]
@viceice This is not a duplicate of those since this is about the fact that Renovate doesn't put a comment when it fails to update a branch. The error could be anything. What if GitLab returns "Error: Something went wrong"? It doesn't matter if the error is LFS-related or not, the behavior is still the same 🙂 .

**Comment by fgblomqvist** [comment]
To elaborate, this is the scenario:
* Renovate creates a branch and MR successfully, all is good
* On another run, it wants to make changes to the branch
* It fails to make those changes
* Now it needs to check if an MR already exists, and if it does, add a comment explaining that it failed to update the branch so the MR should probably not be merged

**Comment by viceice** [comment]
Sure but the cause is the same. So feel free to add another pr to handle this specific git error in our git layer. 🤗

**Comment by viceice** [comment]
You should at least see a warning on the dashboard

**Comment by fgblomqvist** [comment]
>Sure but the cause is the same. So feel free to add another pr to handle this specific git error in our git layer. 🤗
But what about the general case? Are you saying that for general errors it's better to assume that users will verify on the dashboard whether there are any errors with the MR? 🤔

**Comment by viceice** [comment]
Ok, can you please update the PR description to reflect what should be happen? Then reopen the issue.

**Comment by fgblomqvist** [comment]
Updated the description, let me know what you think! Idk if this is an easy task or not, but it may not be too bad.

**Comment by rarkins** [comment]
Should be easy to find and add the comment. The challenge may be removing it after without adding unnecessary API calls in the other 99.9% of cases
