### ISSUE TITLE
Artifact update problem: Error: pg_config executable not found on Gitlab

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#9485]
**What Renovate type, platform and version are you using?**

I set up a private project on Gitlab using [the official doc](https://gitlab.com/renovate-bot/renovate-runner/-/blob/master/README.md) and execute it on a [public project](https://gitlab.com/bagage/batimap/) 

**Describe the bug**

CI fails ([example](https://gitlab.com/bagage/batimap/-/merge_requests/812)) because the [`Pipfile`](https://gitlab.com/bagage/batimap/-/blob/master/back/Pipfile) lists `psycopg2` dependency which itself requires `pg_config` binary to be available on the system (installable via `apt install postgresql-client` or equivalent).
An alternative would be to replace `psycopg2` dependency with `psycopg2-binary` instead. But I'm unsure the implications of changing that directly when Renovate runs.

**Relevant debug logs**
See logs on https://gitlab.com/bagage/batimap/-/merge_requests/812

<details><summary>Click me to see logs</summary>

```
Command failed: docker run --rm --name=renovate_python --label=renovate_child -v "/builds/bagage/renovate/renovate/repos/gitlab/bagage/batimap":"/builds/bagage/renovate/renovate/repos/gitlab/bagage/batimap" -v "/builds/bagage/renovate/renovate/cache":"/builds/bagage/renovate/renovate/cache" -v "/builds/bagage/renovate/renovate/cache/others/pipenv":"/builds/bagage/renovate/renovate/cache/others/pipenv" -e PIPENV_CACHE_DIR -w "/builds/bagage/renovate/renovate/repos/gitlab/bagage/batimap/back" docker.io/renovate/python:3.9.3 bash -l -c "pip install --user pipenv && pipenv lock"
Creating a virtualenv for this project...
Pipfile: /builds/bagage/renovate/renovate/repos/gitlab/bagage/batimap/back/Pipfile
Using /usr/local/python/3.9.3/bin/python3.9 (3.9.3) to create virtualenv...
⠋ Creating virtual environment...⠙ Creating virtual environment...⠹ Creating virtual environment...⠸ Creating virtual environment...⠼ Creating virtual environment...⠴ Creating virtual environment...⠦ Creating virtual environment...⠧ Creating virtual environment...⠇ Creating virtual environment...⠏ Creating virtual environment...⠋ Creating virtual environment...⠙ Creating virtual environment...⠹ Creating virtual environment...⠸ Creating virtual environment...⠼ Creating virtual environment...⠴ Creating virtual environment...⠦ Creating virtual environment...⠧ Creating virtual environment...⠇ Creating virtual environment...created virtual environment CPython3.9.3.final.0-64 in 1207ms
  creator CPython3Posix(dest=/home/ubuntu/.local/share/virtualenvs/back-NvXRaIOs, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==54.1.2, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/ubuntu/.local/share/virtualenvs/back-NvXRaIOs
Locking [dev-packages] dependencies...
⠋ Locking...Building requirements...
⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...Resolving dependencies...
⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...✔ Success! 
Locking [packages] dependencies...
⠋Building requirements...
 Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...Resolving dependencies...
⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...⠇ Locking...⠏ Locking...⠋ Locking...⠙ Locking...⠹ Locking...⠸ Locking...⠼ Locking...⠴ Locking...⠦ Locking...⠧ Locking...✘ Locking Failed! 
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /home/ubuntu/.local/share/virtualenvs/back-NvXRaIOs/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-j66evycm/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-j66evycm/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-resolver-j66evycm/psycopg2/pip-egg-info
     cwd: /tmp/pip-resolver-j66evycm/psycopg2/
Complete output (23 lines):
running egg_info
creating /tmp/pip-resolver-j66evycm/psycopg2/pip-egg-info/psycopg2.egg-info
writing /tmp/pip-resolver-j66evycm/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
writing dependency_links to /tmp/pip-resolver-j66evycm/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
writing top-level names to /tmp/pip-resolver-j66evycm/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
writing manifest file '/tmp/pip-resolver-j66evycm/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'

Error: pg_config executable not found.

pg_config is required to build psycopg2 from source.  Please add the directory
containing pg_config to the $PATH or specify the full executable path with the
option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.

If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.

For further information please check the 'doc/src/install.rst' file (also at
<https://www.psycopg.org/docs/install.html>).

----------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 538, in _generate_metadata
    return generate_metadata_legacy(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/build/metadata_legacy.py", line 115, in generate_metadata
    call_subprocess(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by bagage** [comment]
To reproduce:

```
# OK
docker run --rm python:3.9.3 pip install psycopg2
# KO, should be working?
docker run --rm docker.io/renovate/python:3.9.3 pip install psycopg2
```

**Comment by rarkins** [comment]
I am surprised if the official python image comes preinstalled with pg_config. But what else would explain it?

**Comment by bagage** [comment]
It indeed looks like it is.

**Comment by rarkins** [comment]
Strange. I don't see it in https://github.com/docker-library/python/blob/18ef1b6500a622da8b138d1b413c963c279e7ea4/3.9/buster/Dockerfile

**Comment by bagage** [comment]
Erratum: pg_config is installed from `libpq-dev` package. 

And it comes from base image (`buildpack-deps:buster`): https://github.com/docker-library/buildpack-deps/blob/65d69325ad741cea6dee20781c1faaab2e003d87/debian/buster/Dockerfile#L38

**Comment by rarkins** [comment]
Needs solving in https://github.com/containerbase/buildpack/pull/30
