### ISSUE TITLE
Error updating branch for submodule update

### ISSUE THREAD

**Issue by augi** [renovatebot/renovate#9532]
**What Renovate type, platform and version are you using?**

We are running `renovate/renovate:24.113` in k8s, pointing to our GitHub Enterprise installation. 

**Describe the bug**

We would like to use the `git-submodule` feature, and we are aware of the fact that this _manager_ is in _beta testing_ now.

Renovate doesn't create a new PR with submodule update, and its log contains following messages: 
```
DEBUG: Error updating file
WARN: Error updating branch: update failure (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
```

**Relevant debug logs**

The most relevant log message is probably the latest, the `DEBUG: Error updating file`. Unfortunately, there is no more information about what caused the error, even with `trace` `logLevel`.

<details><summary>Click me to see logs</summary>

```
DEBUG: Matched 1 file(s) for manager git-submodules: .gitmodules (repository=some-org/main-repo)
DEBUG: Found git-submodules package files (repository=some-org/main-repo)
 INFO: Dependency extraction complete (repository=some-org/main-repo)
       "baseBranch": "master",
       "stats": {
         "managers": {
           "git-submodules": {"fileCount": 1, "depCount": 1}
         },
         "total": {"fileCount": 1, "depCount": 1}
       }
DEBUG: Found no results from datasource that look like a version (repository=some-org/main-repo, dependency=.teamcity/another-org/another-repo)
       "result": {
         "sourceUrl": "https://our_ghe_address/another-org/another-repo",
         "releases": []
       }
DEBUG: 1 flattened updates found: .teamcity/another-org/another-repo (repository=some-org/main-repo)
DEBUG: packageFiles with updates (repository=some-org/main-repo)
       "config": {
         "git-submodules": [
           {
             "packageFile": ".gitmodules",
             "deps": [
               {
                 "depName": ".teamcity/another-org/another-repo",
                 "lookupName": "https://**redacted**@our_ghe_address/another-org/another-repo.git",
                 "currentValue": "master",
                 "currentDigest": "3fb22ca47f948c74141383e4ad94268233816d32",
                 "depIndex": 0,
                 "updates": [
                   {
                     "updateType": "digest",
                     "newValue": "master",
                     "newVersion": "master",
                     "newDigest": "6dd6bbbcedbbcb6467270c5f59bdd4d5b6cadf11",
                     "newDigestShort": "6dd6bbb",
                     "branchName": "renovate/teamcity-another-org-another-repo-digest"
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": "https://our_ghe_address/another-org/another-repo",
                 "fixedVersion": "master"
               }
             ],
             "datasource": "git-refs"
           }
         ]
       }
DEBUG: processRepo() (repository=some-org/main-repo)
DEBUG: Processing 1 branch: renovate/teamcity-another-org-another-repo-digest (repository=some-org/main-repo)
DEBUG: Calculated maximum PRs remaining this run (repository=some-org/main-repo)
       "prsRemaining": 99
DEBUG: PullRequests limit = 99 (repository=some-org/main-repo)
DEBUG: Calculated maximum branches remaining this run (repository=some-org/main-repo)
       "branchesRemaining": 99
DEBUG: Branches limit = 99 (repository=some-org/main-repo)
DEBUG: processBranch with 1 upgrades (repository=some-org/main-repo, dependencies=.teamcity/another-org/another-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: Setting current branch to master (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: latest commit (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
       "branchName": "master",
       "latestCommitDate": "2021-04-12T17:27:57+02:00"
DEBUG: getBranchPr(renovate/teamcity-another-org-another-repo-digest) (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: findPr(renovate/teamcity-another-org-another-repo-digest, undefined, open) (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: Retrieving PR list (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: Retrieved 25 Pull Requests (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: findPr(renovate/teamcity-another-org-another-repo-digest, undefined, closed) (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: branchExists=false (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: Branch has 1 upgrade(s) (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: recreateClosed is false (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: findPr(renovate/teamcity-another-org-another-repo-digest, chore(deps): update .teamcity/another-org/another-repo commit hash to 6dd6bbb, !open) (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: prAlreadyExisted=false (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: Checking schedule(at any time, null) (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: No schedule defined (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: Branch needs creating (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: Using reuseExistingBranch: false (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
DEBUG: Error updating file (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
       "existingContent": "[submodule \".teamcity/another-org/another-repo\"]\n\tpath = .teamcity/another-org/another-repo\n\turl = git@our_ghe_address:another-org/another-repo.git\n",
       "config": {
         "postUpgradeTasks": {
           "commands": [],
           "fileFilters": [],
           "executionMode": "update"
         },
         "onboardingBranch": "renovate/configure",
         "onboardingCommitMessage": null,
         "onboardingConfigFileName": "renovate.json",
         "onboardingPrTitle": "Configure Renovate",
         "productLinks": {
           "documentation": "https://docs.renovatebot.com/",
           "help": "https://github.com/renovatebot/renovate/discussions",
           "homepage": "https://github.com/renovatebot/renovate"
         },
         "draftPR": false,
         "printConfig": true,
         "binarySource": "global",
         "cacheDir": "/tmp/renovate/cache",
         "dockerMapDotfiles": false,
         "composerIgnorePlatformReqs": true,
         "logContext": null,
         "dependencyDashboard": false,
         "dependencyDashboardApproval": false,
         "dependencyDashboardAutoclose": false,
         "dependencyDashboardTitle": "Dependency Dashboard",
         "dependencyDashboardHeader": "This issue contains a list of Renovate updates and their statuses.",
         "dependencyDashboardFooter": null,
         "configWarningReuseIssue": true,
         "timezone": null,
         "schedule": ["at any time"],
         "updateNotScheduled": true,
         "persistRepoData": false,
         "ignoreScripts": false,
         "platform": "github",
         "endpoint": "https://our_ghe_address/api/v3/",
         "npmrc": null,
         "npmToken": null,
         "yarnrc": null,
         "updateLockFiles": true,
         "skipInstalls": null,
         "ignoreNpmrcFile": false,
         "gitAuthor": "team-user <team-email@company.com>",
         "excludeCommitPaths": [],
         "aliases": {},
         "registryUrls": null,
         "extractVersion": null,
         "versioning": "git",
         "azureAutoComplete": false,
         "azureWorkItemId": 0,
         "pinDigests": false,
         "separateMajorMinor": true,
         "separateMinorPatch": false,
         "rangeStrategy": "replace",
         "branchPrefix": "renovate/",
         "bumpVersion": null,
         "semanticCommits": "enabled",
         "semanticCommitType": "chore",
         "semanticCommitScope": "deps",
         "rollbackPrs": false,
         "recreateClosed": false,
         "rebaseWhen": "auto",
         "rebaseLabel": "rebase",
         "stabilityDays": 0,
         "prCreation": "immediate",
         "prNotPendingHours": 25,
         "prHourlyLimit": 0,
         "prConcurrentLimit": 0,
         "branchConcurrentLimit": null,
         "prPriority": 0,
         "bbUseDefaultReviewers": true,
         "automerge": false,
         "automergeType": "pr",
         "automergeComment": "automergeComment",
         "requiredStatusChecks": [],
         "transitiveRemediation": false,
         "branchName": "renovate/teamcity-another-org-another-repo-digest",
         "additionalBranchPrefix": "",
         "branchTopic": "{{{depNameSanitized}}}-digest",
         "commitMessage": "chore(deps): update .teamcity/another-org/another-repo commit hash to 6dd6bbb",
         "commitBody": null,
         "commitBodyTable": false,
         "commitMessagePrefix": "chore(deps):",
         "commitMessageAction": "Update",
         "commitMessageTopic": "{{{depName}}} commit hash",
         "commitMessageExtra": "to {{newDigestShort}}",
         "commitMessageSuffix": null,
         "prBodyTemplate": "{{{header}}}{{{table}}}{{{notes}}}{{{changelogs}}}{{{configDescription}}}{{{controls}}}{{{footer}}}",
         "prTitle": "chore(deps): update .teamcity/another-org/another-repo commit hash to 6dd6bbb",
         "prHeader": null,
         "prFooter": "This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
         "hashedBranchLength": null,
         "groupSlug": null,
         "labels": [],
         "addLabels": [],
         "assignees": [],
         "assigneesFromCodeOwners": false,
         "assigneesSampleSize": null,
         "assignAutomerge": false,
         "reviewers": [],
         "reviewersFromCodeOwners": false,
         "reviewersSampleSize": null,
         "additionalReviewers": [],
         "postUpdateOptions": [],
         "constraints": {},
         "prBodyDefinitions": {
           "Package": "{{{depNameLinked}}}",
           "Type": "{{{depType}}}",
           "Update": "{{{updateType}}}",
           "Current value": "{{{currentValue}}}",
           "New value": "{{{newValue}}}",
           "Change": "`{{{displayFrom}}}` -> `{{{displayTo}}}`",
           "References": "{{{references}}}",
           "Package file": "{{{packageFile}}}"
         },
         "prBodyColumns": ["Package", "Type", "Update", "Change"],
         "prBodyNotes": [],
         "suppressNotifications": ["deprecationWarningIssues"],
         "pruneStaleBranches": true,
         "unicodeEmoji": true,
         "gitLabAutomerge": false,
         "fetchReleaseNotes": true,
         "cloneSubmodules": false,
         "ignorePrAuthor": false,
         "renovateUsername": "team-user",
         "repository": "some-org/main-repo",
         "localDir": "/tmp/renovate/repos/github/some-org/main-repo",
         "errors": [],
         "warnings": [],
         "branchList": [],
         "defaultBranch": "master",
         "isFork": false,
         "baseBranch": "master",
         "repoIsOnboarded": true,
         "renovateJsonPresent": true,
         "dependencyDashboardChecks": {},
         "manager": "git-submodules",
         "packageFile": ".gitmodules",
         "datasource": "git-refs",
         "parentDir": "",
         "packageFileDir": "",
         "depName": ".teamcity/another-org/another-repo",
         "lookupName": "https://**redacted**@our_ghe_address/another-org/another-repo.git",
         "currentValue": "master",
         "currentDigest": "3fb22ca47f948c74141383e4ad94268233816d32",
         "depIndex": 0,
         "sourceUrl": "https://our_ghe_address/another-org/another-repo",
         "fixedVersion": "master",
         "updateType": "digest",
         "newValue": "master",
         "newVersion": "master",
         "newDigest": "6dd6bbbcedbbcb6467270c5f59bdd4d5b6cadf11",
         "newDigestShort": "6dd6bbb",
         "isDigest": true,
         "depNameSanitized": ".teamcity-another-org-another-repo",
         "baseDeps": [
           {
             "depName": ".teamcity/another-org/another-repo",
             "lookupName": "https://**redacted**@our_ghe_address/another-org/another-repo.git",
             "currentValue": "master",
             "currentDigest": "3fb22ca47f948c74141383e4ad94268233816d32",
             "depIndex": 0,
             "updates": [
               {
                 "updateType": "digest",
                 "newValue": "master",
                 "newVersion": "master",
                 "newDigest": "6dd6bbbcedbbcb6467270c5f59bdd4d5b6cadf11",
                 "newDigestShort": "6dd6bbb",
                 "branchName": "renovate/teamcity-another-org-another-repo-digest"
               }
             ],
             "warnings": [],
             "sourceUrl": "https://our_ghe_address/another-org/another-repo",
             "fixedVersion": "master"
           }
         ],
         "logJSON": null,
         "currentDigestShort": "3fb22ca",
         "displayFrom": "3fb22ca",
         "displayTo": "6dd6bbb",
         "prettyDepType": "dependency",
         "toLowerCase": true
       }
 WARN: Error updating branch: update failure (repository=some-org/main-repo, branch=renovate/teamcity-another-org-another-repo-digest)
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**
Renovate was not able to initialize the submodule, printing `Unable to initialise git submodule` warning, with `Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.` message.

This is probably caused by the fact that we use the _SSH syntax_ to specify submodule origin (not the _https_ one), and the SSH key is not present in the Docker repository (it would be great if there were some docs describing that, if possible).

We overcome this by setting `RENOVATE_CLONE_SUBMODULES` to `false`. Maybe it could be connected to the reported error, so mentioning here to be sure.

**Comment by augi** [comment]
I've just found [this code](https://github.com/renovatebot/renovate/blob/master/lib/manager/git-submodules/update.ts#L17) that IMHO swallows the errors during the update, so maybe this is the code that is actually failing. It would be great to add some logging there.

If this is the issue, then it is related to what I wrote in the `Additional context` section. So we probably need a way how to pass the SSH key to the container. It would be great if you could suggest how to do it 🙏

**Comment by JamieMagee** [comment]
Let me send out a quick PR adding logging there (you can never have enough logging).

As for SSH, I think we explicitly rewrite SSH to HTTPS, and we expect a `hostRule`

https://github.com/renovatebot/renovate/blob/dd26fcf20e5892ecc3028605e61952b148d94916/lib/manager/git-submodules/extract.ts#L113-L117

**Comment by augi** [comment]
Thanks for the future PR 😄 I will try the new version of Renovate ASAP after releasing, to have more information.

Yes, the SSH to HTTPS rewriting works well, and Renovate is able to correctly find all the data needed to create a new PR 👍 You can see that in the log.

Unfortunately, Renovate will fail later, when it tries to apply the proposed change. It is just my guess that it could be related to the fact we disabled submodule cloning (using `RENOVATE_CLONE_SUBMODULES`) because it didn't work because of following message: `Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.`
Again, my guess is that this could be solved by inserting our SSH key into the container. But I don't know what would be the best way, e.g. if there is a envvar prepared for this, of if ssh-agent is running inside the container.

🙏

**Comment by augi** [comment]
Now, using `24.116.1`, the situation is different.

A new log message is present:
```
DEBUG: Found hostRules token for submodule (repository=some-org/main-repo)
       "httpSubModuleUrl": "https://our_ghe/other-org/other-repo.git"
```
But the extraction doesn't work. It looks like it doesn't try to use access via HTTPS and token but tries to make some stuff that requires SSH.
```
DEBUG: Datasource unknown error (repository=some-org/main-repo)
       "datasource": "git-refs",
       "lookupName": "https://our_ghe/other-org/other-repo.git",
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "https://our_ghe/other-org/other-repo.git"
           ],
           "format": "utf-8"
         },
         "message": "fatal: could not read Username for 'https://our_ghe': No such device or address\n",
         "stack": "Error: fatal: could not read Username for 'https://our_ghe': No such device or address\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:109:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:106:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:83:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
```

So now the situation is even worse because it is not even able to detect the proposed update 😢

**Comment by augi** [comment]
It looks like it could be cause by #9556, cc @rarkins @JamieMagee

**Comment by rarkins** [comment]
It's still using HTTPS and not SSH. We may now need to duplicate the token lookup behaviour into the datasource too. The old approach of embedding it in the lookupName wasn't correct.

**Comment by rarkins** [comment]
I created #9581 for that

**Comment by JamieMagee** [comment]
@augi Does version `24.116.2` (or newer) fix your issue?

**Comment by augi** [comment]
@JamieMagee Yes, thanks! I've just used `24.119.2` and it fixes the issue.

**Comment by rarkins** [comment]
@augi are you then back to the original problem? Any new information or logs to share?

**Comment by augi** [comment]
Yes, back to the original problem, and anything new to share 😢

**Comment by rarkins** [comment]
I guess the issue is with the SSH syntax. Maybe a git command like `git config --global url.\"https://${token}@github.com/\".insteadOf \"https://github.com/\"` would help however we would need to make it local and not permanent or global if it is running inside the main Renovate container.

**Comment by Shegox** [comment]
With #10149 implemented through #22061 this problem could be now resolved.

Could you try the newest Renovate version again?

**Comment by augi** [comment]
Hello, I've just tried the latest Renovate version. There are still errors, but maybe we are just not able to configure Renovate properly.

The combined config contains this fragment:
```json
         "git-submodules": {"enabled": true},
         "hostRules": [
           {"matchHost": "git.int.company.com", "timeout": 120000},
           {"matchHost": "git.int.company.com", "token": "***********"},
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
```

The log contains the following WARN: `Could not create directory '/home/ubuntu/.ssh'.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.`

Then I can see this DEBUG: `DEBUG: Dependency https://git.int.company.com/org/proj.git has unsupported/unversioned value master (versioning=git) (repository=org/another-proj)`

Maybe this is the root cause of why it is not working for us.

**Comment by Shegox** [comment]
@augi the unsupoorted/unversioned line should be fine, that just means that Renovate will track the main/master branch.

Otherwise can you try adding the `hostType: github` to the hostRule? This should tell Renovate that this is a Git host and should inject git credentials for that host.

My hostRule configuration looks like this for our GitHub Enterprise Server: 
```json
{
  "hostType": "github",
  "matchHost": "github.enterprise.com",
  "token": "***********",
  "abortOnError": true,
  "abortIgnoreStatusCodes": [404]
},
```

**Comment by Shegox** [comment]
Also can you post how your `.gitmodules` file inside your repository looks?

**Comment by augi** [comment]
I tried to add the `hostType`, but the `Could not create directory '/home/ubuntu/.ssh'` WARN is still present.

The content of the `.gitmodules` file is like this:
```
[submodule "foo/bar"]
	path = foo/bar
	url = git@git.int.company.com:foo/bar.git
```

**Comment by Shegox** [comment]
I just tested it as well with the ssh syntax `git@git.int.company.com:foo/bar.git` just like you have it and for my repo it did work and I checked as well the file `/home/ubuntu/.ssh` isn't created. 

My current guess is that one of the `insteadOf` directives are not taking affect causing Renovate to still using the SSH URL instead of the rewritten HTTPS url. Big question is why that is happening in your environment?

Can you describe in a bit more detail how your Renovate setup looks? 
You're using the standard Renovate docker image in version [`>=36.18.3`](https://github.com/renovatebot/renovate/releases/tag/36.18.3), right?
What global configurations do you inject, do you have `binarySource: "install"` set?

**Comment by augi** [comment]
Thank you very much for your effort! 👍 We are using now the `36.21.0-full` Docker image. We don't set `binarySource` so it defaults to `install`.

I switched to the `trace` log level and I'm able to locate the `Adding Git authentication` message.

I can see `Found git-submodules package files` in the log, but `Updating submodule` is not present 😢

**Comment by augi** [comment]
The WARN:
```
Error: Submodule 'some_dir/some_org/some_project' (git@git.int.company.com:some_org/some_project.git) registered for path 'some_dir/some_org/some_project'\nCloning into '/tmp/renovate/repos/github/updated_org/updated_project/some_dir/some_org/some_project'...\nCould not create directory '/home/ubuntu/.ssh'.\r
Host key verification failed.\r
fatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@git.int.company.com:some_org/some_project.git' into submodule path '/tmp/renovate/repos/github/updated_org/updated_project/some_dir/some_org/some_project' failed\nFailed to clone 'some_dir/some_org/some_project'. Retry scheduled\nCloning into '/tmp/renovate/repos/github/updated_org/updated_project/some_dir/some_org/some_project'...\nCould not create directory '/home/ubuntu/.ssh'.\r
Host key verification failed.\r
fatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@git.int.company.com:some_org/some_project.git' into submodule path '/tmp/renovate/repos/github/updated_org/updated_project/some_dir/some_org/some_project' failed\nFailed to clone 'some_dir/some_org/some_project' a second time, aborting\n\n    at Object.action (/opt/containerbase/tools/renovate/36.21.0/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/opt/containerbase/tools/renovate/36.21.0/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /opt/containerbase/tools/renovate/36.21.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/opt/containerbase/tools/renovate/36.21.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/opt/containerbase/tools/renovate/36.21.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/containerbase/tools/renovate/36.21.0/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

**Comment by Shegox** [comment]
Thanks for the answers, that indeed all looks like it should work :D  

Some more questions: 
- Do you have submodules inside of your submodule? 
- Do you customize the Renovate docker image (e.g. set custom environment variables or tinker with the global/system wide git config)?

And can you see in the trace logs for this section, what Renovate exactly extracts here: 
```
DEBUG: Found git-submodules package files (repository=gh-testing/submodule-parent-3)
DEBUG: Found 1 package file(s) (repository=gh-testing/submodule-parent-3)
 INFO: Dependency extraction complete (repository=gh-testing/submodule-parent-3, baseBranch=master)
       "stats": {
         "managers": {"git-submodules": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }
TRACE: packageFiles (repository=gh-testing/submodule-parent-3)
       "config": {
         "git-submodules": [
           {
             "deps": [
               {
                 "depName": "submodule-child",
                 "packageName": "https://github.enterprise.com/gh-testing/submodule-child.git",
                 "currentValue": "master",
                 "currentDigest": "f32c8dc567c4ad75ca2b193f4624961a2e8eb2d2"
               }
             ],
             "datasource": "git-refs",
             "packageFile": ".gitmodules"
           }
         ]
       }
```

**Comment by Shegox** [comment]
And one more thing, just for testing purposes: 
If possible, can you try switching your submodule from SSH to HTTPs URL? Maybe in a fork, if you don't want to perform this in your production repository? 
I'm really struggling to nailing this one down... 

Do you have `cloneSubmodules: true` set in your configuration by chance?

**Comment by augi** [comment]
1. No, there is no submodule inside another submodule.
2. Yep, we set various environment variables: RENOVATE_PLATFORM, RENOVATE_ENDPOINT, RENOVATE_TOKEN, RENOVATE_GIT_AUTHOR, GITHUB_COM_TOKEN, RENOVATE_HOST_RULES, RENOVATE_ONBOARDING, RENOVATE_REQUIRE_CONFIG, RENOVATE_AUTODISCOVER, RENOVATE_AUTODISCOVER_FILTER, LOG_LEVEL, RENOVATE_PAGINATE_ALL, RENOVATE_ENABLED_MANAGERS, RENOVATE_CLONE_SUBMODULES, RENOVATE_CONFIG_FILE. From the `config.json` file, the only related part is probably this:
```json
      "git-submodules": {
        "enabled": true
      },
```

* `Found git-submodules package files` is present
* `Found 1 package file(s)` is there
* `Dependency extraction complete` also found
* The TRACE is also present.

Actually, is the failing submodule cloning affecting the update capability? I'm asking because it is _just_ a `WARN`: `WARN: Unable to initialise git submodule`

**Comment by Shegox** [comment]
Ah, that might be the case: [`RENOVATE_CLONE_SUBMODULES=true` is the same as `cloneSubmodules: true`](https://docs.renovatebot.com/configuration-options/#clonesubmodules) and is checking out the submodules as part of the repository initialization (right at the beginning). At this might no additional credentials/git `insteadOf` are available and I can actually get the error/warning reproduced there. 

So the order how things are happening and where problems are occuring might be this: 

1. Renovate clones the repository including all submodules (thanks to `RENOVATE_CLONE_SUBMODULES=true`). This should cause the first warning/errors you see about `Error: Submodule 'some_dir/some_org/some_project' (git@git.int.company.com:some_org/some_project.git`

2. Then Renovate then extracts the packages and that `Found git-submodules package files` and logs them. 

Now it should calculate the intended updates and that should look like this. Can you confirm that?
```
DEBUG: packageFiles with updates (repository=gh-testing/submodule-parent-3, baseBranch=master)
       "config": {
         "git-submodules": [
           {
             "deps": [
               {
                 "depName": "folder/submodule-child",
                 "packageName": "https://github.enterprise.com/gh-testing/submodule-child.git",
                 "currentValue": "master",
                 "currentDigest": "f32c8dc567c4ad75ca2b193f4624961a2e8eb2d2",
                 "updates": [
                   {
                     "updateType": "digest",
                     "newValue": "master",
                     "newDigest": "bedf4e2edd30d72211eb20cfe13ace21fa03fbf7",
                     "branchName": "renovate/folder-submodule-child-digest"
                   }
                 ],
                 "versioning": "git",
                 "warnings": []
               }
             ],
             "datasource": "git-refs",
             "packageFile": ".gitmodules"
           }
         ]
       }
```

Only afterwards the actual update is performed which should look like this: 
```
...
TRACE: Adding Git authentication for https://github.enterprise.com/ using token auth. (repository=gh-testing/submodule-parent-3, branch=renovate/submodule-child-digest)
 INFO: Updating submodule submodule-child (repository=gh-testing/submodule-parent-3, branch=renovate/submodule-child-digest)
DEBUG: Updated 1 package files (repository=gh-testing/submodule-parent-3, branch=renovate/submodule-child-digest)
...
```

**Comment by augi** [comment]
Thank you again for your assistance, really appreciated 🙏 Will all the fiddling, Renovate created PR for the new commit in the submodule 🎉 

It looks like the submodule cloning is not required because it is still failing on `Could not create directory '/home/ubuntu/.ssh'.`. As we don't want to update dependencies inside the submodule, I guess we could actually disable the submodule cloning, right?

Anyway, the submodule updates feature is working with the latest version of Renovate, thanks! 👍

**Comment by Shegox** [comment]
That's awesome 🎉 

Yes, the `RENOVATE_CLONE_SUBMODULES` is helpful if you need the submodules as part of the update process (e.g. when updating lock files and Renovate actually needs to access that content). 
Just for updating submodules it isn't need and can be disabled. As `RENOVATE_CLONE_SUBMODULES` doesn't support private repositories the usage within your GitHub Enterprise Server instance is probably anyway limited and it probably is better if somebody needs it, they enable it on repository level.

**Comment by augi** [comment]
> Can you confirm that?

Yep, I can confirm all you wrote 👌
