### ISSUE TITLE
checkoutBranch failure due to git rev-parse ambiguous argument

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#9917]
**What Renovate type, platform and version are you using?**

**Renovate type**

- [x] Hosted app
- [ ] Self hosted

**Renovate platform**

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server (self-hosted)
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server (self-hosted)
- [ ] Gitea (gitea.com, self-hosted)
- [x] GitHub (github.com, GitHub Enterprise)
- [ ] GitLab (gitlab.com, self-hosted)

**Describe the bug**

`git.checkoutBranch()` fails every time.

**Relevant debug logs**

![image](https://user-images.githubusercontent.com/6311784/117541665-2666b880-b015-11eb-8d10-8153158da4d4.png)

<details>
<summary>logs</summary>

```
{"level":30,"renovateVersion":"25.16.7","msg":"Repository started","time":"2021-05-08T13:26:39.338Z"}
{"level":20,"msg":"Using localDir: /mnt/renovate/gh/wyobi/repo","time":"2021-05-08T13:26:39.344Z"}
{"level":20,"msg":"Repository cache is valid","time":"2021-05-08T13:26:39.414Z"}
{"level":20,"msg":"initRepo(\"wyobi/repo\")","time":"2021-05-08T13:26:39.415Z"}
{"level":20,"endpoint":"https://api.github.com/","msg":"Overriding default GitHub endpoint","time":"2021-05-08T13:26:39.415Z"}
{"level":20,"msg":"No dangling containers to remove","time":"2021-05-08T13:26:39.438Z"}
{"level":20,"msg":"wyobi/repo default branch = master","time":"2021-05-08T13:26:39.612Z"}
{"level":20,"msg":"Using app token for git init","time":"2021-05-08T13:26:39.612Z"}
{"level":20,"msg":"resetMemCache()","time":"2021-05-08T13:26:40.188Z"}
{"level":20,"msg":"Resetting npmrc","time":"2021-05-08T13:26:40.188Z"}
{"level":20,"msg":"checkOnboarding()","time":"2021-05-08T13:26:40.188Z"}
{"level":20,"msg":"isOnboarded()","time":"2021-05-08T13:26:40.188Z"}
{"level":20,"msg":"findFile(renovate.json)","time":"2021-05-08T13:26:40.188Z"}
{"level":20,"msg":"Initializing git repository into /mnt/renovate/gh/wyobi/repo","time":"2021-05-08T13:26:40.188Z"}
{"level":20,"durationMs":135517,"msg":"git clone completed","time":"2021-05-08T13:28:55.706Z"}
{"level":20,"latestCommit":{"hash":"5ddba0b774ab1179118b80f2ba0c5590177a0018","date":"2021-04-01T02:03:34+02:00","message":"Merge pull request #578 from wyobi/development","refs":"HEAD -> master, origin/master, origin/HEAD","body":"Development","author_name":"Liquid-NeoN","author_email":"wouter@wyobi.com"},"msg":"latest repository commit","time":"2021-05-08T13:28:55.834Z"}
{"level":20,"gitAuthorName":"Renovate Bot","msg":"Setting git author name","time":"2021-05-08T13:28:55.834Z"}
{"level":20,"gitAuthorEmail":"bot@renovateapp.com","msg":"Setting git author email","time":"2021-05-08T13:28:55.869Z"}
{"level":20,"fileName":"renovate.json","msg":"Config file exists","time":"2021-05-08T13:28:56.183Z"}
{"level":20,"msg":"Retrieving issueList","time":"2021-05-08T13:28:56.184Z"}
{"level":20,"msg":"Retrieved 1 issues","time":"2021-05-08T13:28:56.418Z"}
{"level":20,"msg":"Repo is onboarded","time":"2021-05-08T13:28:56.418Z"}
{"level":20,"msg":"Found renovate.json config file","time":"2021-05-08T13:28:56.571Z"}
{"level":20,"fileName":"renovate.json","config":{"extends":["config:base"],"baseBranches":["development"]},"msg":"Repository config","time":"2021-05-08T13:28:56.574Z"}
{"level":20,"msg":"migrateAndValidate()","time":"2021-05-08T13:28:56.574Z"}
{"level":20,"msg":"No config migration necessary","time":"2021-05-08T13:28:56.574Z"}
{"level":20,"config":{"extends":["github>whitesource/merge-confidence:beta","config:base"],"baseBranches":["development"]},"msg":"massaged config","time":"2021-05-08T13:28:56.574Z"}
{"level":20,"config":{"extends":["github>whitesource/merge-confidence:beta","config:base"],"baseBranches":["development"]},"msg":"migrated config","time":"2021-05-08T13:28:56.574Z"}
{"level":20,"ignorePaths":["**/node_modules/**","**/bower_components/**","**/vendor/**","**/examples/**","**/__tests__/**","**/test/**","**/tests/**","**/__fixtures__/**"],"msg":"Found repo ignorePaths","time":"2021-05-08T13:28:57.000Z"}
{"level":20,"msg":"detectSemanticCommits()","time":"2021-05-08T13:28:57.000Z"}
{"level":20,"msg":"getCommitMessages","time":"2021-05-08T13:28:57.000Z"}
{"level":20,"msg":"Semantic commits detection: unknown","time":"2021-05-08T13:28:57.036Z"}
{"level":20,"msg":"No semantic commits detected","time":"2021-05-08T13:28:57.037Z"}
{"level":20,"msg":"Setting branchPrefix: renovate/","time":"2021-05-08T13:28:57.043Z"}
{"level":20,"msg":"No vulnerability alerts found","time":"2021-05-08T13:29:01.527Z"}
{"level":20,"msg":"No vulnerability alerts found","time":"2021-05-08T13:29:01.527Z"}
{"level":20,"msg":"processRepo()","time":"2021-05-08T13:29:01.527Z"}
{"level":20,"baseBranches":["development"],"msg":"baseBranches","time":"2021-05-08T13:29:01.528Z"}
{"level":20,"msg":"baseBranch: development","time":"2021-05-08T13:29:01.528Z"}
{"level":20,"msg":"extract()","time":"2021-05-08T13:29:01.536Z"}
{"level":20,"msg":"Setting current branch to development","time":"2021-05-08T13:29:01.541Z"}
{"level":50,"err":{"task":{"commands":["rev-parse","origin/development"],"format":"utf-8"},"message":"origin/development\nfatal: ambiguous argument 'origin/development': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n","stack":"Error: origin/development\nfatal: ambiguous argument 'origin/development': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:92:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:90:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:74:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"},"msg":"Repository has unknown error","time":"2021-05-08T13:29:21.656Z"}
{"level":20,"splits":{"init":142190},"total":166115,"msg":"Repository timing splits (milliseconds)","time":"2021-05-08T13:29:25.452Z"}
{"level":20,"hostStats":["api.github.com, 4 requests, 213ms request average, 0ms queue average"],"totalRequests":4,"msg":"http statistics","time":"2021-05-08T13:29:25.453Z"}
{"level":30,"durationMs":166115,"msg":"Repository finished","time":"2021-05-08T13:29:25.453Z"}
```

</details>

**Have you created a minimal reproduction repository?**

It happens only on one repo in the hosted app belonging to @wyobi, and it's private.

**Additional context**

**Comment by mvanholsteijn** [comment]
I found out that the problem is caused by the fact that repository is cloned with `--depth=10`. If the branch from a commit more than 10 commits away, this error occurs.

**Comment by rarkins** [comment]
Can you reproduce that in a public repository? I tried and cannot

**Comment by mvanholsteijn** [comment]
Hmmmm. It is hard to reproduce on a public repository. I tee'd the commands of renovate and found the following difference in response to the following command sequence:

```
git remote set-branches --add origin dev
git fetch origin dev --depth=2
git rev-parse origin/dev
```

On the private repository, the result of the second command is:

```
 git fetch origin dev --depth=2
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 37 (delta 2), reused 29 (delta 2), pack-reused 0
Unpacking objects: 100% (37/37), 2.21 MiB | 7.96 MiB/s, done.
From https://gitlab.binx.io/apps/catfood/catfood-app
 * tag               dev        -> FETCH_HEAD
```

Where as the public git repository returns:

```
git fetch origin dev --depth=2
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 12 (delta 6), reused 10 (delta 4), pack-reused 0
Unpacking objects: 100% (12/12), 4.62 KiB | 675.00 KiB/s, done.
From https://gitlab.com/mvanholsteijn/fromage
 * branch            dev        -> FETCH_HEAD
 * [new branch]      dev        -> origin/dev
```

It actually creates the new local dev branch.

**Comment by mvanholsteijn** [comment]
I can confirm that the following git-wrapper solves the issue:

```
#!/bin/bash
if [[ $1 == fetch ]] && [[ $2 == origin ]] && [[ $3 == dev ]] && [[ $4 == --depth=2 ]] ; then
	/usr/bin/git fetch origin dev:origin/dev --depth=2
else
	/usr/bin/git "$@"
fi
```

**Comment by mvanholsteijn** [comment]
Sorry. The problem was that there was  a tag with the same name as the branch.

**Comment by rarkins** [comment]
@mvanholsteijn if that's something you think Renovate could catch and warn about automatically, please create a feature request and/or PR for it

**Comment by mvanholsteijn** [comment]
oke. I will take a look at it.
