### ISSUE TITLE
Branch automerge fatal: Not possible to fast-forward, aborting

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#9998]
**What Renovate type, platform and version are you using?**

Hosted app on GitHub.com

**Renovate type**

- [x] Hosted app
- [ ] Self hosted

**Renovate platform**

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server (self-hosted)
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server (self-hosted)
- [ ] Gitea (gitea.com, self-hosted)
- [ ] GitHub (github.com, GitHub Enterprise)
- [ ] GitLab (gitlab.com, self-hosted)

**Renovate version (if self hosting)**

I'm self hosting Renovate with version: ...

**Describe the bug**

Branches fail to automerge

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
{"msg":"Setting current branch to master","time":"2021-05-14T14:05:24.371Z"}
{"branchName":"master","latestCommitDate":"2021-05-12T21:36:24+00:00","msg":"latest commit","time":"2021-05-14T14:05:24.622Z"}
{"msg":"getBranchPr(renovate/get-stream-6.x)","time":"2021-05-14T14:05:24.704Z"}
{"msg":"findPr(renovate/get-stream-6.x, undefined, open)","time":"2021-05-14T14:05:24.704Z"}
{"msg":"findPr(renovate/get-stream-6.x, undefined, closed)","time":"2021-05-14T14:05:24.704Z"}
{"msg":"branchExists=true","time":"2021-05-14T14:05:24.705Z"}
{"msg":"dependencyDashboardCheck=undefined","time":"2021-05-14T14:05:24.705Z"}
{"msg":"recreateClosed is false","time":"2021-05-14T14:05:24.706Z"}
{"msg":"findPr(renovate/get-stream-6.x, chore(deps): update dependency get-stream to v6.0.1, !open)","time":"2021-05-14T14:05:24.706Z"}
{"msg":"prAlreadyExisted=false","time":"2021-05-14T14:05:24.706Z"}
{"msg":"Checking if PR has been edited","time":"2021-05-14T14:05:24.706Z"}
{"msg":"Checking schedule(at any time, null)","time":"2021-05-14T14:05:24.783Z"}
{"msg":"No schedule defined","time":"2021-05-14T14:05:24.784Z"}
{"msg":"Branch already exists","time":"2021-05-14T14:05:24.784Z"}
{"msg":"getBranchPr(renovate/get-stream-6.x)","time":"2021-05-14T14:05:24.784Z"}
{"msg":"findPr(renovate/get-stream-6.x, undefined, open)","time":"2021-05-14T14:05:24.785Z"}
{"msg":"findPr(renovate/get-stream-6.x, undefined, closed)","time":"2021-05-14T14:05:24.785Z"}
{"isStale":false,"branches":{"all":["origin/master","origin/renovate/aggregate-error-4.x","origin/renovate/codecov-3.x","origin/renovate/dockerode-3.x","origin/renovate/execa-5.x","origin/renovate/fs-extra-10.x","origin/renovate/get-stream-6.x","origin/renovate/got-11.x","origin/renovate/lock-file-maintenance","origin/renovate/npm-7.x","origin/renovate/p-retry-4.x","origin/renovate/read-pkg-6.x","origin/renovate/sinon-10.x","origin/renovate/xo-0.x"],"branches":{"origin/master":{"current":false,"name":"origin/master","commit":"839f810","label":"chore(deps): update dependency tempy to v1.0.1 (#109)"},"origin/renovate/aggregate-error-4.x":{"current":false,"name":"origin/renovate/aggregate-error-4.x","commit":"2c20584","label":"fix(deps): update dependency aggregate-error to v4"},"origin/renovate/codecov-3.x":{"current":false,"name":"origin/renovate/codecov-3.x","commit":"16f8646","label":"chore(deps): update dependency codecov to v3.8.2"},"origin/renovate/dockerode-3.x":{"current":false,"name":"origin/renovate/dockerode-3.x","commit":"a9214cd","label":"chore(deps): update dependency dockerode to v3.3.0"},"origin/renovate/execa-5.x":{"current":false,"name":"origin/renovate/execa-5.x","commit":"9739a51","label":"fix(deps): update dependency execa to v5"},"origin/renovate/fs-extra-10.x":{"current":false,"name":"origin/renovate/fs-extra-10.x","commit":"20cd955","label":"chore(deps): update dependency fs-extra to v10"},"origin/renovate/get-stream-6.x":{"current":false,"name":"origin/renovate/get-stream-6.x","commit":"acd4fa1","label":"chore(deps): update dependency get-stream to v6.0.1"},"origin/renovate/got-11.x":{"current":false,"name":"origin/renovate/got-11.x","commit":"c4dbcf4","label":"chore(deps): update dependency got to v11.8.2"},"origin/renovate/lock-file-maintenance":{"current":false,"name":"origin/renovate/lock-file-maintenance","commit":"60f49f9","label":"chore(deps): lock file maintenance"},"origin/renovate/npm-7.x":{"current":false,"name":"origin/renovate/npm-7.x","commit":"29cd015","label":"fix(deps): update dependency npm to v7"},"origin/renovate/p-retry-4.x":{"current":false,"name":"origin/renovate/p-retry-4.x","commit":"96e999a","label":"chore(deps): update dependency p-retry to v4.5.0"},"origin/renovate/read-pkg-6.x":{"current":false,"name":"origin/renovate/read-pkg-6.x","commit":"5b490e1","label":"fix(deps): update dependency read-pkg to v6"},"origin/renovate/sinon-10.x":{"current":false,"name":"origin/renovate/sinon-10.x","commit":"e10daa0","label":"chore(deps): update dependency sinon to v10"},"origin/renovate/xo-0.x":{"current":false,"name":"origin/renovate/xo-0.x","commit":"30c5912","label":"chore(deps): update dependency xo to v0.40.1"}},"current":"","detached":false},"currentBranch":"master","currentBranchSha":"839f810b1d63cf4b709d96660a7ff67395aa7d53","msg":"IsBranchStale=false","time":"2021-05-14T14:05:24.871Z"}
{"msg":"Branch is up-to-date","time":"2021-05-14T14:05:24.872Z"}
{"msg":"Branch does not need rebasing","time":"2021-05-14T14:05:24.872Z"}
{"msg":"Using reuseExistingBranch: true","time":"2021-05-14T14:05:24.872Z"}
{"msg":"manager.getUpdatedPackageFiles() reuseExistinbranch=true","time":"2021-05-14T14:05:24.872Z"}
{"msg":"npm.updateDependency(): devDependencies.get-stream = 6.0.1","time":"2021-05-14T14:05:24.942Z"}
{"msg":"No package files need updating","time":"2021-05-14T14:05:24.943Z"}
{"msg":"Getting updated lock files","time":"2021-05-14T14:05:24.943Z"}
{"packageFiles":["package.json"],"msg":"Writing package.json files","time":"2021-05-14T14:05:24.943Z"}
{"msg":"Writing package-lock.json","time":"2021-05-14T14:05:24.943Z"}
{"msg":"Writing any updated package files","time":"2021-05-14T14:05:25.052Z"}
{"msg":"No updated lock files in branch","time":"2021-05-14T14:05:25.053Z"}
{"msg":"No files to commit","time":"2021-05-14T14:05:25.053Z"}
{"msg":"Checking if we can automerge branch","time":"2021-05-14T14:05:25.054Z"}
{"msg":"getBranchPr(renovate/get-stream-6.x)","time":"2021-05-14T14:05:25.054Z"}
{"msg":"findPr(renovate/get-stream-6.x, undefined, open)","time":"2021-05-14T14:05:25.054Z"}
{"msg":"findPr(renovate/get-stream-6.x, undefined, closed)","time":"2021-05-14T14:05:25.054Z"}
{"msg":"getBranchStatus(renovate/get-stream-6.x)","time":"2021-05-14T14:05:25.054Z"}
{"state":"pending","statuses":[],"msg":"branch status check result","time":"2021-05-14T14:05:25.221Z"}
{"checkRuns":[{"name":"test","status":"completed","conclusion":"success"},{"name":"test_matrix (14)","status":"completed","conclusion":"success"},{"name":"test_matrix (12)","status":"completed","conclusion":"success"},{"name":"test_matrix (10)","status":"completed","conclusion":"success"}],"msg":"check runs result","time":"2021-05-14T14:05:25.472Z"}
{"msg":"Automerging branch","time":"2021-05-14T14:05:25.472Z"}
{"level":40,"branch":"renovate/get-stream-6.x","err":{"task":{"commands":["merge","--ff-only","renovate/get-stream-6.x"],"format":"utf-8"},"message":"fatal: Not possible to fast-forward, aborting.\n","stack":"Error: fatal: Not possible to fast-forward, aborting.\n\n    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:92:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:90:16)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:74:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"},"msg":"Branch is not up to date - cannot automerge","time":"2021-05-14T14:05:25.846Z"}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to: https://github.com/semantic-release/apm
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
This branch is confirmed to be only one commit ahead of `master`:

![image](https://user-images.githubusercontent.com/6311784/118293771-4d702f00-b4da-11eb-8d78-b34cbdc9e930.png)

**Comment by rarkins** [comment]
Tried to reproduce this locally:

```
 1005  git clone https://github.com/semantic-release/apm --depth=10
 1006  cd apm
 1010  git fetch origin 'refs/heads/renovate/*:refs/remotes/origin/renovate/*' --depth=2 --force
 1011  git checkout -B renovate/get-stream-6.x origin/renovate/get-stream-6.x
 1013  git checkout master
 1014  git merge --ff-only renovate/get-stream-6.x
```

Worked:

```
Updating 839f810..acd4fa1
Fast-forward
 package-lock.json | 6 +++---
 package.json      | 2 +-
 2 files changed, 4 insertions(+), 4 deletions(-)
```
